import {CHORES,DURATION,TASK_SECONDS,createHome,tickHome,homeSnapshot} from './model.js';
import {createHomeWorld} from './world.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:1}).format(n);
let state=createHome(),speed=1,selected=0,following=true,world,last=performance.now();
document.title=t('Hogar 3D — Robots y tiempo recuperado','3D Home — Robots and time reclaimed');
$('app').innerHTML=`<nav class="nav"><a href="../index.html">← Atlas</a><a href="../robots/index.html">${t('Robots · cuatro escalas','Robots · four scales')} ↗</a><a href="../dyson/index.html">${t('Esfera de Dyson','Dyson sphere')} ↗</a><span><a href="${es?'../../home/index.html':'./index.html'}" lang="en">EN</a> / <a href="${es?'./index.html':'../es/home/index.html'}" lang="es">ES</a></span></nav>
<header><div><span class="eyebrow">${t('NOTEBOOK 04 · HOGAR EN 3D','NOTEBOOK 04 · 3D HOME')}</span><h1>${t('Las tareas desaparecen.<br>La casa sigue siendo tuya.','The chores disappear.<br>The home is still yours.')}</h1></div><p>${t('Pulsa reproducir. Recorre un hogar normal mientras un aspirador, un robot y la IA asumen sus quehaceres.','Press play. Explore an ordinary home as a vacuum, a robot and AI take on its chores.')}</p></header>
<section class="dashboard" aria-label="${t('Tiempo y tareas en esta simulación','Time and tasks in this simulation')}"><article><span>${t('Trabajo humano pendiente','Human work remaining')}</span><strong id="remaining">145 <small>min</small></strong><div class="meter human"><i id="human-bar"></i></div><small>${t('Tiempo activo ilustrativo de esta lista','Illustrative active time for this list')}</small></article><article><span>${t('Tiempo recuperado','Time reclaimed')}</span><strong id="freed">0 <small>min</small></strong><div class="meter"><i id="freed-bar"></i></div><small id="support-note"></small></article><article><span>${t('Quehaceres delegados','Chores delegated')}</span><strong id="done">0 <small>/ 7</small></strong><div class="steps">${CHORES.map(()=>'<i></i>').join('')}</div><small id="agents"></small></article></section>
<div class="controls"><button id="play" class="primary">▶ ${t('Reproducir','Play')}</button><button id="reset" aria-label="${t('Reiniciar','Reset')}">↺</button><label>${t('Velocidad','Speed')} <select id="speed"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label><button id="next">${t('Siguiente tarea','Next chore')} →</button><button id="finish">${t('Ver desenlace','See outcome')} →</button><label class="mode">${t('Hipótesis','Hypothesis')} <select id="mode"><option value="0">${t('Total · sin supervisión','Full · no supervision')}</option><option value="20">${t('Con supervisión · 20 %','Supervised · 20%')}</option></select></label></div>
<div class="layout"><section class="stage"><div class="scene-caption"><b id="scene-status"></b><span>${t('Naranja: persona · verde: robots · violeta: IA','Orange: person · green: robots · purple: AI')}</span></div><div id="house" role="img" aria-label="${t('Casa en tres dimensiones con salón, cocina, dormitorio, lavadero, baño y escritorio','Three-dimensional home with living room, kitchen, bedroom, laundry, bathroom and study')}"></div><div id="room-labels" aria-hidden="true"></div><p id="loading">${t('Preparando la casa…','Preparing the home…')}</p><div class="view-controls"><button id="view">${t('Vista desde arriba','Top view')}</button><button id="zoom-out" aria-label="${t('Alejar','Zoom out')}">−</button><button id="zoom-in" aria-label="${t('Acercar','Zoom in')}">+</button></div><div class="scene-bottom"><span id="action"></span><strong id="percent">0 %</strong></div><div class="timeline"><i id="timeline-progress"></i></div></section><aside><span class="eyebrow">${t('EL RECORRIDO DE TU CASA','YOUR HOME WALKTHROUGH')}</span><div id="task-list">${CHORES.map((task,i)=>`<button data-task="${i}"><span class="task-number">${String(i+1).padStart(2,'0')}</span><span><b>${es?task.es:task.en}</b><small>${task.room[es?0:1]} · ${task.minutes} min</small></span><em>○</em></button>`).join('')}</div><div class="detail"><span id="task-agent"></span><h2 id="task-name"></h2><p id="task-detail"></p><button id="seek">${t('Reproducir desde aquí','Play from here')} →</button></div></aside></div>
<p class="completion" id="completion" role="status" hidden></p>
<details class="assumptions"><summary>${t('Qué estamos suponiendo · tiempos, capacidades y supervisión','What we assume · times, capabilities and supervision')}</summary><p>${t('Este hogar es una hipótesis de automatización completa de siete quehaceres concretos. Los 145 minutos son ejemplos de trabajo humano activo, no mediciones ni una jornada doméstica completa. La animación dura 70 segundos y comprime desplazamientos, lavado y cocción. No estima el precio de un robot.','This home is a full automation hypothesis for seven specific chores. The 145 minutes are examples of active human work, not measurements or a complete household day. The animation takes 70 seconds and compresses travel, washing and cooking. It does not estimate a robot price.')}</p><p>${t('La aspiración autónoma ya existe. La manipulación general de objetos, cocinar, hacer camas y limpiar baños con fiabilidad son capacidades que aquí suponemos. La IA puede ayudar a planificar, pero la delegación sin revisión también es una hipótesis. La opción con supervisión conserva el 20 % del tiempo de las tareas delegadas para apoyo, incidencias y revisión.','Autonomous vacuuming already exists. General object manipulation, reliable cooking, bed-making and bathroom cleaning are capabilities assumed here. AI can help with planning, but delegation without review is also an assumption. The supervised option retains 20% of delegated task time for assistance, exceptions and review.')}</p><p>${t('Desaparece el trabajo pendiente y el desorden, no los muebles ni las personas. No modelamos cuidados personales, reparaciones complejas ni nuevas tareas.','Pending work and clutter disappear, not furniture or people. Personal care, complex repairs and new tasks are not modeled.')} <a href="https://www.irobot.com/en_US/roomba.html" target="_blank" rel="noopener">${t('Ejemplo actual: aspiradores iRobot','Current example: iRobot vacuums')} ↗</a></p></details><footer>${t('Atlas · Hogar 3D · notebook 04 · 18 septiembre 2026','Atlas · 3D Home · notebook 04 · 18 September 2026')}</footer>`;
const roomNames=[[-3,4.75,t('Salón','Living room')],[-3,-4.9,t('Cocina','Kitchen')],[1.6,-4.8,t('Dormitorio','Bedroom')],[1.5,4.75,t('Lavadero','Laundry')],[4.8,4.75,t('Baño','Bathroom')],[4.7,-4.8,t('Escritorio · IA','Study · AI')]];
$('room-labels').innerHTML=roomNames.map(r=>`<span>${r[2]}</span>`).join('');
try{world=createHomeWorld($('house'));$('loading').hidden=true;}catch(e){$('loading').textContent=t('La vista 3D no está disponible. Puedes reproducir el recorrido y seguir los contadores y las tareas.','The 3D view is unavailable. You can play the walkthrough and follow the counters and tasks.');console.error(e);}
function agent(task){return task.actor==='ai'?'IA / AI':task.actor==='vacuum'?t('Aspirador autónomo','Autonomous vacuum'):t('Robot doméstico · hipótesis futura','Household robot · future hypothesis');}
function update(){const v=homeSnapshot(state);if(following)selected=v.index;const task=CHORES[selected];$('remaining').innerHTML=fmt(v.remaining)+' <small>min</small>';$('freed').innerHTML=fmt(v.freed)+' <small>min</small>';$('done').innerHTML=v.done+' <small>/ 7</small>';$('support-note').textContent=fmt(v.support)+' '+t('min de supervisión incluidos','min of supervision included');const delegated=CHORES.slice(0,v.done);$('agents').textContent=delegated.filter(task=>task.actor!=='ai').length+' '+t('con máquinas','with machines')+' · '+delegated.filter(task=>task.actor==='ai').length+' '+t('con IA','with AI');$('human-bar').style.width=v.remaining/v.total*100+'%';$('freed-bar').style.width=v.freed/v.total*100+'%';document.querySelectorAll('.steps i').forEach((el,i)=>el.classList.toggle('done',i<v.done));
 $('play').textContent=state.playing?'Ⅱ '+t('Pausar','Pause'):v.complete?'↺ '+t('Repetir','Replay'):'▶ '+t('Reproducir','Play');$('scene-status').textContent=v.complete?t('RELEVO COMPLETO','HANDOVER COMPLETE'):state.playing?t('EN MARCHA','PLAYING'):t('EN PAUSA','PAUSED');$('action').textContent=v.complete?t('La lista ya está hecha. Tu tiempo vuelve a ti.','The list is done. Your time is yours again.'):(es?CHORES[v.index].es:CHORES[v.index].en)+' · '+(v.phase<.25?t('Preparando la tarea','Preparing the chore'):t('En curso','In progress'));$('percent').textContent=Math.floor(state.time/DURATION*100)+' %';$('timeline-progress').style.width=state.time/DURATION*100+'%';
 document.querySelectorAll('[data-task]').forEach((b,i)=>{b.classList.toggle('done',i<v.done);b.setAttribute('aria-pressed',String(i===selected));b.querySelector('em').textContent=i<v.done?'✓':i===v.index&&!v.complete?'◉':'○';});$('task-name').textContent=es?task.es:task.en;$('task-agent').textContent=agent(task);$('task-detail').textContent=task.detail[es?0:1];$('completion').hidden=!v.complete;$('completion').textContent=state.overhead===0?t('7 de 7 quehaceres delegados · 0 minutos humanos pendientes en esta lista. La persona sigue en casa, ahora con tiempo libre.','7 of 7 chores delegated · 0 human minutes remaining on this list. The person is still home, now with free time.'):t('7 de 7 quehaceres delegados. Quedan ','7 of 7 chores delegated. This hypothesis retains ')+fmt(v.remaining)+t(' minutos humanos de apoyo y supervisión bajo esta hipótesis.',' human minutes for assistance and supervision.');
 world?.render(state,v,selected);document.querySelectorAll('#room-labels span').forEach((label,i)=>{const p=world?.project(roomNames[i][0],roomNames[i][1]);label.hidden=!p;if(p){label.style.left=p.x+'px';label.style.top=p.y+'px';}});}
$('play').onclick=()=>{if(state.time>=DURATION)state.time=0;state.playing=!state.playing;following=true;last=performance.now();update();};$('reset').onclick=()=>{state=createHome(+$('mode').value);following=true;update();};$('speed').onchange=e=>speed=+e.target.value;$('mode').onchange=e=>{state.overhead=+e.target.value;update();};$('next').onclick=()=>{state.time=Math.min(DURATION,(Math.floor(state.time/TASK_SECONDS)+1)*TASK_SECONDS);state.playing=false;following=true;update();};$('finish').onclick=()=>{state.time=DURATION;state.playing=false;following=true;update();};document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{selected=+b.dataset.task;following=false;state.playing=false;update();});$('seek').onclick=()=>{state.time=selected*TASK_SECONDS;state.playing=true;following=true;last=performance.now();update();};$('view').onclick=()=>{const top=world?.toggleView();$('view').textContent=top?t('Vista en perspectiva','Perspective view'):t('Vista desde arriba','Top view');update();};$('zoom-in').onclick=()=>{world?.zoomBy(1.1);update();};$('zoom-out').onclick=()=>{world?.zoomBy(1/1.1);update();};
window.addEventListener('resize',update);document.addEventListener('visibilitychange',()=>last=performance.now());update();
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!document.hidden){if(state.playing)tickHome(state,dt*speed);update();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
