import * as THREE from '../vendor/three.module.js';
import * as Model from './model.js';

export const HOME_ROOMS = [
 {id:'living',es:'Salón',en:'Living room',bounds:[-6,0,0,0,2.9,5],center:[-3,1.2,2.5],color:0xbe8b71},
 {id:'kitchen',es:'Cocina',en:'Kitchen',bounds:[-6,0,-5,0,2.9,0],center:[-3,1.2,-2.5],color:0x789587},
 {id:'laundry',es:'Lavadero',en:'Laundry',bounds:[0,0,0,3.1,2.9,5],center:[1.55,1.2,2.5],color:0x87a8b2},
 {id:'bedroom',es:'Dormitorio',en:'Bedroom',bounds:[0,0,-5,3.1,2.9,0],center:[1.55,1.2,-2.5],color:0xa598b8},
 {id:'bathroom',es:'Baño',en:'Bathroom',bounds:[3.1,0,0,6,2.9,5],center:[4.55,1.2,2.5],color:0x73a9a5},
 {id:'study',es:'Escritorio',en:'Study',bounds:[3.1,0,-5,6,2.9,0],center:[4.55,1.2,-2.5],color:0xc2a677}
];
export const HOME_CHAPTERS=['floor','dishes','cook','laundry','bed','bath','plan'];
export const HOME_CHAPTER_ROOMS=[0,1,1,2,3,4,5];
export const HOME_FOCUS=[[-3,1.05,2.4],[-2.5,1.1,-3.3],[-4,1.15,-4], [1.65,1.2,3],[1.6,1,-2.9],[4.6,1.05,2.1],[4.7,1.2,-3.0]];
export const HOME_BOUNDS=[[-5.95,-.1,.05,-.15,2.20,4.90],[-4.10,-.1,-4.9,-.40,2.16,-.72],[-5.65,-.1,-4.92,-1.08,2.16,-1.08],[.20,-.1,1.02,3.04,2.16,4.53],[.03,-.1,-4.89,3.03,2.16,-.38],[3.24,-.1,.52,5.94,2.24,4.51],[3.38,-.1,-3.65,5.80,2.16,-1.1]];
HOME_BOUNDS.push([-6.25,-.15,-5.25,6.25,3.15,5.25]);
// The same rectangles produce the actual walls and walking collisions.
export const HOME_WALLS=[
 [-6.08,-5.08,6.08,-4.92],[-6.08,4.92,-1.65,5.08],[-.15,4.92,6.08,5.08],[-6.08,-5.08,-5.92,5.08],[5.92,-5.08,6.08,5.08],
 [-.07,-5,.07,-1.65],[-.07,-.35,.07,.65],[-.07,1.95,.07,5],
 [3.03,-5,3.17,-1.65],[3.03,-.35,3.17,.65],[3.03,1.95,3.17,5],
 [-6,-.07,-1.45,.07],[-.15,-.07,1.00,.07],[2.3,-.07,3.95,.07],[5.25,-.07,6,.07]
];
export const HOME_OPENINGS=[
 {axis:'x',at:0,from:-1.65,to:-.35},{axis:'x',at:0,from:.65,to:1.95},
 {axis:'x',at:3.1,from:-1.65,to:-.35},{axis:'x',at:3.1,from:.65,to:1.95},
 {axis:'z',at:0,from:-1.45,to:-.15},{axis:'z',at:0,from:1,to:2.3},{axis:'z',at:0,from:3.95,to:5.25},
 {axis:'z',at:5,from:-1.65,to:-.15}
];
export const HOME_FURNITURE_SOLIDS=[[-5.6,-4.92,-.8,-4.08],[-5.8,-3.55,-4.9,-2.55],[-3.85,-2.45,-2.15,-1.35],[-4.88,3.73,-1.02,4.78],[-3.85,1.68,-2.15,2.65],[-5.90,.05,-5.10,1.90],[-5.38,3.91,-4.88,4.41],[.08,-4.17,2.45,-1.68],[.87,3.52,1.83,4.45],[2.26,3.35,2.94,4.05],[1.45,1.48,2.35,2.32],[3.91,.65,5.17,1.425],[4.38,3.52,5.22,4.25],[5.1,1.72,5.86,2.98],[3.87,-3.49,5.52,-2.58]];
export const HOME_SOLIDS=[...HOME_WALLS,...HOME_FURNITURE_SOLIDS];
export const HOME_STAND_POSITIONS=[[-1.35,1.1,1.25],[-.7,1.1,-3.2],[-4.55,1.1,-3.1],[.55,1.1,2.6],[2.2,1.1,-1.4],[3.55,1.1,2.5],[3.65,1.1,-2.75]];
export const HOME_STANDS=HOME_STAND_POSITIONS;
export const HOME_STAND_SOLIDS=HOME_STAND_POSITIONS.map(([x,y,z])=>[x-.23,z-.19,x+.23,z+.19]);
HOME_SOLIDS.push(...HOME_STAND_SOLIDS,[-1.65,4.95,-.15,5.05]);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
const chapterIndex=i=>typeof i==='string'?Math.max(0,HOME_CHAPTERS.indexOf(i)):Math.floor(clamp(Number(i),0,6));
const overlaps=(x,z,r=.23)=>HOME_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);
export function homePoseAt(i=0){const places=[[-.75,2.65],[-.55,-1.9],[-3.8,-2.95],[.55,1.05],[2.62,-.55],[3.65,1.05],[4.35,-1.15]],q=places[chapterIndex(i)],f=HOME_FOCUS[chapterIndex(i)];return {x:q[0],z:q[1],yaw:Math.atan2(q[0]-f[0],q[1]-f[2]),pitch:Math.atan2(f[1]-1.65,Math.hypot(q[0]-f[0],q[1]-f[2]))};}
export function restoreHomePose(value){if(!value||!['x','z','yaw','pitch'].every(k=>Number.isFinite(value[k])))return homePoseAt(0);let p={x:clamp(value.x,-5.65,5.65),z:clamp(value.z,-4.65,4.65),yaw:value.yaw,pitch:clamp(value.pitch,-1.25,1.25)};if(overlaps(p.x,p.z))p=homePoseAt(0);return p;}
export function homeWalk(p,input,dt){const f=input.forward||0,s=input.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=2.4*Math.min(.05,Math.max(0,dt)),x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*d,-5.68,5.68),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*d,-4.68,4.68);return {...p,x:overlaps(x,p.z)?p.x:x,z:overlaps(overlaps(x,p.z)?p.x:x,z)?p.z:z};}
export function homeRoomAt(p){return HOME_ROOMS.find(r=>p.x>=r.bounds[0]&&p.x<=r.bounds[3]&&p.z>=r.bounds[2]&&p.z<=r.bounds[5])||null;}
export function homeFraming(chapter=0,orbit={},aspect=1,fov=46,frame){const bounds=orbit.whole?HOME_BOUNDS[7]:HOME_BOUNDS[chapterIndex(chapter)],center=new THREE.Vector3((bounds[0]+bounds[3])/2,(bounds[1]+bounds[4])/2,(bounds[2]+bounds[5])/2),yaw=orbit.yaw??.62,pitch=orbit.pitch??.69,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let distance=2;for(const x of [bounds[0],bounds[3]])for(const y of [bounds[1],bounds[4]])for(const z of [bounds[2],bounds[5]]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}return {center,direction,distance:distance*1.1*(orbit.distance??10)/10,bounds};}

export function createHomeScene(es=true){
 const t=(a,b)=>es?a:b,scene=new THREE.Scene();scene.background=new THREE.Color(0xc8d7da);scene.fog=new THREE.Fog(0xc8d7da,38,85);
 const resources=[],owned=new Set(),targets=[],stands=[],own=r=>{if(!owned.has(r)){owned.add(r);resources.push(r);}return r;},release=r=>{if(owned.delete(r)){resources.splice(resources.indexOf(r),1);r.dispose();}};
 const boxGeo=own(new THREE.BoxGeometry(1,1,1)),sphereGeo=own(new THREE.SphereGeometry(1,20,14)),cylinderGeo=own(new THREE.CylinderGeometry(1,1,1,24)),materials=new Map();
 const mat=(color,extra={})=>{const key=String(color)+JSON.stringify(extra);if(!materials.has(key))materials.set(key,own(new THREE.MeshStandardMaterial({color,roughness:.64,metalness:.02,...extra})));return materials.get(key);};
 const palette={ink:mat(0x29444f),wood:mat(0xc5a477),cream:mat(0xf5eddf),steel:mat(0xa6b7bc,{metalness:.65,roughness:.28}),gold:mat(0xebc180,{metalness:.28}),teal:mat(0x8dc6b5),purple:mat(0xb7a3d5),cloth:mat(0xaec2d3,{roughness:.94}),human:mat(0xe3b18a),white:mat(0xf1f4ef),glass:mat(0xc5e4e8,{transparent:true,opacity:.32,depthWrite:false,roughness:.1})};
 function mesh(g,geometry,material,p=[0,0,0]){const m=new THREE.Mesh(geometry,material);m.position.set(...p);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 function box(g,p,size,material=palette.cream){const m=mesh(g,boxGeo,material,p);m.scale.set(...size);return m;}
 function ball(g,p,size,material=palette.cream){const m=mesh(g,sphereGeo,material,p);m.scale.set(...(Array.isArray(size)?size:[size,size,size]));return m;}
 function cylinder(g,p,size,material=palette.steel){const m=mesh(g,cylinderGeo,material,p);m.scale.set(...size);return m;}
 function rod(g,a,b,r,material=palette.steel){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),m=mesh(g,cylinderGeo,material,p.clone().add(q).multiplyScalar(.5).toArray());m.scale.set(r,p.distanceTo(q),r);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());return m;}
 function label(g,initial,p,width=2,{height=80,bg=true,color='#f7efdf',maxHeight=.24,minWidth=96,depthTest=true}={}){const material=own(new THREE.SpriteMaterial({transparent:true,depthWrite:false,depthTest})),m=new THREE.Sprite(material),cache=new Map();m.position.set(...p);g.add(m);let last;function set(value){const text=String(value);if(text===last)return;last=text;let entry=cache.get(text);if(!entry){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),lines=text.split('\n');ctx.font='600 54px system-ui';canvas.width=Math.max(minWidth,Math.min(2048,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line).width))+44)));canvas.height=height;if(bg){ctx.fillStyle='#29444ff2';ctx.fillRect(0,0,canvas.width,height);}ctx.font='600 54px system-ui';ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,height*(i+.5)/lines.length,canvas.width-32));const texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;const w=Math.min(width,maxHeight*canvas.width/height);entry={texture,w,h:w*height/canvas.width};cache.set(text,entry);if(cache.size>96){const [key,old]=cache.entries().next().value;cache.delete(key);release(old.texture);}}else{cache.delete(text);cache.set(text,entry);}material.map=entry.texture;material.needsUpdate=true;m.scale.set(entry.w,entry.h,1);}set(initial);return {m,set,cache};}
 function inspect(m,esText,enText){m.userData.info=[esText,enText||esText];targets.push(m);return m;}
 const architecture=new THREE.Group();scene.add(architecture);const roomGroups=HOME_ROOMS.map(()=>{const g=new THREE.Group();scene.add(g);return g;}),annotations=Array.from({length:7},()=>{const g=new THREE.Group();scene.add(g);return g;});
 scene.add(new THREE.HemisphereLight(0xfff6e7,0x8aa1aa,2.35));const sun=new THREE.DirectionalLight(0xffefda,3.3);sun.position.set(-7,13,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-10,right:10,top:10,bottom:-10,near:.1,far:35});sun.shadow.normalBias=.025;scene.add(sun);own(sun.shadow);
 const floor=box(architecture,[0,-.13,0],[12.32,.24,10.32],palette.wood);HOME_ROOMS.forEach((room,i)=>{const b=room.bounds;box(roomGroups[i],[(b[0]+b[3])/2,.003,(b[2]+b[5])/2],[b[3]-b[0]-.07,.035,b[5]-b[2]-.07],mat(i===1?0xdce0cf:i===4?0xc7dedd:i===2?0xd7e1df:0xd6bf99));});
  const walls=[],wallMaterial=mat(0xefe9db,{transparent:true,opacity:1});function wallPiece(x,y,z,w,h,d){const m=box(architecture,[x,y,z],[w,h,d],wallMaterial);walls.push(m);return m;}
 for(const b of HOME_WALLS){if(b===HOME_WALLS[0]){wallPiece(0,.55,-5,12.16,1.1,.16);wallPiece(0,2.60,-5,12.16,.40,.16);let left=-6.08;for(const x of [-3,1.5,4.7]){const edge=x-.825;wallPiece((left+edge)/2,1.75,-5,edge-left,1.3,.16);left=x+.825;}wallPiece((left+6.08)/2,1.75,-5,6.08-left,1.3,.16);}else{const m=wallPiece((b[0]+b[2])/2,1.4,(b[1]+b[3])/2,b[2]-b[0],2.8,b[3]-b[1]);box(architecture,[m.position.x,.10,m.position.z],[m.scale.x+.018,.16,m.scale.z+.018],palette.cream);}}
 const frontDoor=box(architecture,[-.9,1.08,5],[1.48,2.16,.08],mat(0x78988d));rod(architecture,[-.32,.9,4.94],[-.32,1.16,4.94],.021,palette.steel);walls.push(frontDoor);
 const doorFrames=[];HOME_OPENINGS.forEach(open=>{const span=open.to-open.from;for(const side of [open.from,open.to])doorFrames.push(box(architecture,open.axis==='x'?[open.at,1.08,side]:[side,1.08,open.at],open.axis==='x'?[.20,2.16,.06]:[.06,2.16,.20],palette.wood));doorFrames.push(box(architecture,open.axis==='x'?[open.at,2.16,(open.from+open.to)/2]:[(open.from+open.to)/2,2.16,open.at],open.axis==='x'?[.2,.10,span]:[span,.1,.2],palette.wood));});
 const ceiling=box(architecture,[0,2.88,0],[11.9,.12,9.9],palette.cream);ceiling.visible=false;
 const windows=[];for(const x of [-3,1.5,4.7]){const pane=box(architecture,[x,1.75,-5],[1.65,1.3,.035],palette.glass);pane.castShadow=false;windows.push(pane);box(architecture,[x,1.06,-4.81],[1.85,.10,.28],palette.cream);rod(architecture,[x,1.11,-4.80],[x,2.40,-4.80],.023,palette.steel);for(const dx of [-.85,.85])box(architecture,[x+dx,1.75,-4.80],[.055,1.4,.06],palette.cream);}
 const roomLabels=HOME_ROOMS.map((room,i)=>label(roomGroups[i],es?room.es:room.en,[room.center[0],2.63,room.bounds[2]<0?-4.75:4.65],2.25,{maxHeight:.20}));
 const kitchen=roomGroups[1];box(kitchen,[-3.82,.43,-4.5],[3.56,.86,.8],mat(0x78988d));box(kitchen,[-.98,.43,-4.5],[.36,.86,.8],mat(0x78988d));box(kitchen,[-3.2,.89,-4.5],[4.9,.10,.88],palette.cream);for(let x=-5.15;x<-.9;x+=.72){box(kitchen,[x,.43,-4.086],[.018,.70,.025],palette.steel);rod(kitchen,[x+.20,.73,-4.05],[x+.42,.73,-4.05],.018,palette.steel);}box(kitchen,[-5.35,.96,-3.05],[.9,1.92,.90],palette.white);box(kitchen,[-5.35,1.1,-2.58],[.83,.012,.025],palette.steel);rod(kitchen,[-5.06,.5,-2.57],[-5.06,.86,-2.57],.018,palette.steel);rod(kitchen,[-5.06,1.35,-2.57],[-5.06,1.68,-2.57],.018,palette.steel);
 box(kitchen,[-3,.79,-1.9],[1.70,.12,1.10],palette.wood);for(const x of [-3.72,-2.28])for(const z of [-2.34,-1.46])box(kitchen,[x,.37,z],[.10,.74,.10],palette.wood);
 const sink=box(kitchen,[-2.7,.965,-4.5],[.69,.028,.52],palette.steel);box(kitchen,[-2.7,.98,-4.5],[.48,.025,.31],palette.ink);rod(kitchen,[-2.7,.98,-4.78],[-2.7,1.28,-4.78],.027,palette.steel);rod(kitchen,[-2.7,1.28,-4.78],[-2.7,1.28,-4.50],.027,palette.steel);
 const hob=box(kitchen,[-4.3,.965,-4.45],[.90,.025,.68],mat(0x29444f,{emissive:0x000000,emissiveIntensity:0}));for(const x of [-4.5,-4.1])for(const z of [-4.62,-4.28])cylinder(kitchen,[x,.99,z],[.115,.02,.115],palette.steel);
 const board=box(kitchen,[-3.4,.985,-4.15],[.70,.045,.44],palette.wood),pot=cylinder(kitchen,[-4.3,1.10,-4.4],[.27,.22,.27],palette.steel);for(const x of [-4.65,-3.95])rod(kitchen,[x,1.15,-4.4],[x,1.15,-4.18],.024,palette.ink);const potLid=cylinder(kitchen,[-4.3,1.22,-4.4],[.285,.035,.285],palette.steel);const potKnob=ball(kitchen,[-4.3,1.26,-4.4],.055,palette.ink);
 const dw=new THREE.Group();dw.position.set(-1.6,0,-4.45);kitchen.add(dw);box(dw,[-.40,.43,0],[.045,.84,.73],palette.steel);box(dw,[.40,.43,0],[.045,.84,.73],palette.steel);box(dw,[0,.83,0],[.84,.04,.73],palette.steel);box(dw,[0,.07,0],[.84,.08,.73],palette.steel);box(dw,[0,.44,-.345],[.77,.72,.035],palette.ink);const dishwasherDoor=new THREE.Group();dishwasherDoor.position.set(0,.065,.39);dw.add(dishwasherDoor);box(dishwasherDoor,[0,.37,0],[.78,.72,.055],palette.white);rod(dishwasherDoor,[-.25,.65,.05],[.25,.65,.05],.025,palette.steel);const dwRack=box(dw,[0,.35,.1],[.68,.06,.58],palette.steel);for(let i=0;i<7;i++)rod(dw,[-.29+i*.095,.4,-.13],[-.29+i*.095,.55,.24],.006,palette.steel);
 const dishwasher={group:dw,door:dishwasherDoor,rack:dwRack,body:dw.children[0],state:null};inspect(dishwasher.body,t('Lavavajillas: los mismos platos se trasladan al soporte interior. El lavado es tiempo de máquina comprimido.','Dishwasher: the same plates move into its rack. Washing is compressed machine time.'));
 const living=roomGroups[0],rug=box(living,[-3,.056,2.3],[3.95,.035,3.30],mat(0xc48f76,{roughness:1}));for(let i=0;i<10;i++)box(living,[-3,.076,.80+i*.33],[3.70,.005,.025],mat(0xd1a58d));
 box(living,[-3,.32,4.23],[3.74,.54,1.0],mat(0x5e8d88));box(living,[-3,.79,4.65],[3.82,.95,.21],mat(0x5e8d88));for(const x of [-4.25,-3,-1.75]){ball(living,[x,.70,4.22],[.60,.17,.44],mat(0x8cafab,{roughness:.95}));ball(living,[x,.97,4.50],[.58,.31,.10],mat(0x7da5a0,{roughness:.95}));}for(const x of [-4.82,-1.18])box(living,[x,.66,4.20],[.20,.88,1.05],mat(0x5e8d88));
 box(living,[-3,.55,2.15],[1.70,.10,.97],palette.wood);for(const x of [-3.70,-2.30])for(const z of [1.78,2.52])box(living,[x,.26,z],[.085,.52,.085],palette.ink);
 box(living,[-5.65,1.06,.97],[.45,2.1,1.8],palette.wood);for(const y of [.38,.91,1.46,1.97])box(living,[-5.38,y,.97],[.5,.055,1.75],palette.wood);for(let i=0;i<15;i++){const m=box(living,[-5.35,.56+Math.floor(i/5)*.53,.30+(i%5)*.27],[.25,.30,.18],mat([0x98b2a5,0xd6b588,0xc29387][i%3]));m.rotation.x=(i%3-1)*.07;}
 cylinder(living,[-5.13,.08,4.16],[.25,.10,.25],palette.ink);rod(living,[-5.13,.13,4.16],[-5.13,1.84,4.16],.025,palette.steel);const lamp=mesh(living,own(new THREE.ConeGeometry(.43,.43,28,1,true)),mat(0xffe8b6,{side:THREE.DoubleSide}),[-5.13,1.76,4.16]);lamp.castShadow=false;
 const bedroom=roomGroups[3],bedBase=box(bedroom,[1.25,.24,-2.85],[2.32,.43,2.32],mat(0x927b65)),mattress=box(bedroom,[1.25,.56,-2.85],[2.25,.23,2.30],palette.cream);box(bedroom,[1.25,.88,-4.10],[2.36,1.38,.12],mat(0x8b9ca1));
 const laundry=roomGroups[2],washerGroup=new THREE.Group();washerGroup.position.set(1.35,0,3.95);laundry.add(washerGroup);const washerBody=box(washerGroup,[-.44,.49,0],[.06,.98,.82],palette.white);box(washerGroup,[.44,.49,0],[.06,.98,.82],palette.white);box(washerGroup,[0,.94,0],[.94,.08,.82],palette.white);box(washerGroup,[0,.04,0],[.94,.08,.82],palette.white);box(washerGroup,[0,.49,.39],[.88,.90,.04],palette.white);for(const x of [-.39,.39])box(washerGroup,[x,.49,-.40],[.10,.90,.05],palette.white);for(const y of [.10,.88])box(washerGroup,[0,y,-.40],[.88,.18,.05],palette.white);box(washerGroup,[0,.89,-.427],[.87,.12,.035],palette.steel);cylinder(washerGroup,[-.28,.90,-.46],[.052,.018,.052],palette.ink).rotation.x=Math.PI/2;
 const washerDrum=cylinder(washerGroup,[0,.49,.25],[.32,.02,.32],palette.ink);washerDrum.rotation.x=Math.PI/2;const washerDoor=new THREE.Group();washerDoor.position.set(-.34,.49,-.465);washerGroup.add(washerDoor);const washerRim=mesh(washerDoor,own(new THREE.TorusGeometry(.34,.038,10,32)),palette.steel,[.34,0,0]);const washerGlass=ball(washerDoor,[.34,0,-.01],[.30,.30,.025],palette.glass);washerGlass.castShadow=false;
 const washerDryer={group:washerGroup,body:washerBody,door:washerDoor,drum:washerDrum,state:null};inspect(washerBody,t('Lavadora-secadora: las mismas prendas entran en el tambor y salen a la mesa de doblado. Esperas de máquina comprimidas.','Washer-dryer: the same garments enter the drum and leave for the folding table. Machine waits are compressed.'));
 const basket=box(laundry,[2.6,.31,3.70],[.68,.61,.63],mat(0xb9976e));for(let i=0;i<6;i++)box(laundry,[2.6,.13+i*.088,3.37],[.65,.018,.035],palette.wood);const foldboard=box(laundry,[1.9,.84,1.9],[.90,.12,.84],palette.wood);for(const x of [1.51,2.29])for(const z of [1.57,2.23])box(laundry,[x,.4,z],[.065,.80,.065],palette.steel);box(laundry,[1.5,1.40,4.67],[2.0,.075,.48],palette.wood);
 const bathroom=roomGroups[4],basinStand=box(bathroom,[4.7,.40,1.0],[.88,.80,.65],mat(0x79a7a3));box(bathroom,[4.7,.84,1.0],[.94,.08,.73],palette.cream);box(bathroom,[4.10,.88,1.25],[.38,.04,.35],palette.cream);for(const x of [3.98,4.22])box(bathroom,[x,.43,1.30],[.04,.86,.04],palette.wood);const basin=cylinder(bathroom,[4.7,.90,1.0],[.23,.06,.23],palette.white);box(bathroom,[4.7,.946,1.0],[.25,.007,.18],palette.steel);rod(bathroom,[4.7,.90,.74],[4.7,1.20,.74],.025,palette.steel);rod(bathroom,[4.7,1.20,.74],[4.7,1.20,.94],.025,palette.steel);
 box(bathroom,[4.8,.40,3.9],[.7,.75,.60],palette.white);ball(bathroom,[4.8,.40,3.45],[.37,.25,.46],palette.white);cylinder(bathroom,[4.8,.56,3.46],[.28,.03,.33],palette.steel);box(bathroom,[5.50,.08,2.35],[.75,.12,1.24],palette.cream);const shower=box(bathroom,[5.76,1.03,2.35],[.045,1.90,1.15],palette.glass);shower.castShadow=false;rod(bathroom,[5.85,.32,2.60],[5.85,2.20,2.60],.02,palette.steel);rod(bathroom,[5.85,2.20,2.60],[5.40,2.20,2.60],.02,palette.steel);box(bathroom,[4.7,1.82,.68],[.72,.81,.035],palette.steel);
 const study=roomGroups[5],desk=box(study,[4.7,.88,-3.0],[1.65,.11,.87],palette.wood);for(const x of [4.03,5.36])for(const z of [-3.32,-2.68])box(study,[x,.43,z],[.085,.86,.085],palette.steel);box(study,[4.7,1.04,-3.23],[.29,.04,.24],palette.steel);rod(study,[4.7,1.04,-3.23],[4.7,1.32,-3.23],.035,palette.steel);const screenBody=box(study,[4.7,1.40,-3.23],[1.15,.70,.075],palette.ink),screen=box(study,[4.7,1.40,-3.18],[1.07,.62,.018],mat(0xe0ebdd));box(study,[4.7,.96,-2.93],[.67,.03,.22],palette.steel);
 const planningPanel={group:study,screen,body:screenBody,input:label(study,t('ENTRADA','INPUT'),[4.7,1.60,-3.13],.94,{height:80,maxHeight:.12,color:'#29444f',bg:false}),draft:label(study,'',[4.7,1.40,-3.13],.94,{height:80,maxHeight:.12,color:'#29444f',bg:false}),review:label(study,'',[4.7,1.20,-3.13],.94,{height:80,maxHeight:.12,color:'#29444f',bg:false}),state:null};inspect(screenBody,t('La IA organiza una propuesta. La revisión o delegación completa depende de la hipótesis elegida.','AI organizes a proposal. Review or full delegation depends on the selected hypothesis.'));
 const simulationCaptions=annotations.map((g,i)=>label(g,'',i===2?[-4.3,2.05,-4.62]:[HOME_FOCUS[i][0],2.01,HOME_FOCUS[i][2]],2.45,{height:112,maxHeight:.22}));
 const applianceCaptions={dishwasher:label(kitchen,t('LAVAVAJILLAS','DISHWASHER'),[-1.6,1.20,-4.03],.84,{maxHeight:.13}),washerDryer:label(laundry,t('LAVADORA · SECADORA','WASHER · DRYER'),[1.35,1.13,3.41],1.45,{maxHeight:.15}),hob:label(kitchen,t('PREPARAR → COCINAR → SERVIR','PREPARE → COOK → SERVE'),[-4.3,1.61,-4.4],2.15,{maxHeight:.18}),foldboard:label(laundry,t('MESA DE DOBLADO','FOLDING TABLE'),[1.9,1.14,1.9],1.05,{maxHeight:.14})};
 // Each body has articulated shoulders/elbows and a grasp target from the model.
 function actor(kind){const g=new THREE.Group();scene.add(g);const robot=kind==='robot',skin=robot?palette.teal:palette.human,torso=box(g,[0,1.12,0],[.45,.47,.27],robot?palette.white:mat(0xd5aa77)),hips=box(g,[0,.79,0],[.34,.20,.23],robot?palette.steel:mat(0x617e8b)),head=ball(g,[0,1.57,0],[.17,.21,.16],skin);const neck=rod(g,[0,1.34,0],[0,1.42,0],.063,skin);if(robot){box(g,[0,1.59,.147],[.23,.078,.024],palette.ink);for(const x of [-.075,.075])ball(g,[x,1.60,.163],.019,mat(0x9cd8d0,{emissive:0x6da99f,emissiveIntensity:.18}));}else{for(const x of [-.060,.060])ball(g,[x,1.61,.146],.014,palette.ink);ball(g,[0,1.57,.17],[.027,.035,.024],skin);ball(g,[0,1.73,.02],[.174,.081,.15],mat(0x7e6554));}
 const face=new THREE.Group();face.position.set(0,1.57,0);const features=g.children.filter(m=>m.position.y>1.43);g.add(face);features.forEach(m=>{m.position.sub(face.position);face.add(m);});const legs=[];for(const x of [-.12,.12]){const thigh=rod(g,[x,.76,0],[x,.43,0],.073,robot?palette.steel:mat(0x617e8b)),shin=rod(g,[x,.43,0],[x,.10,0],.06,robot?palette.white:mat(0x617e8b));const knee=ball(g,[x,.43,0],.073,robot?palette.ink:mat(0x617e8b));box(g,[x,.075,.05],[.17,.12,.30],palette.ink);legs.push({thigh,shin,knee});}
 const arms={};for(const [side,x] of [['left',-.275],['right',.275]]){const shoulder=new THREE.Vector3(x,1.30,0),upper=rod(g,shoulder.toArray(),[x,.96,0],.062,skin),lower=rod(g,[x,.96,0],[x,.67,-.04],.050,skin),elbow=ball(g,[x,.96,0],.069,robot?palette.ink:skin),hand=ball(g,[x,.66,-.04],[.065,.09,.05],skin);arms[side]={shoulder,upper,lower,elbow,hand,target:null};}
 return {kind,group:g,g,head:face,headMesh:head,neck,torso,hips,legs,arms,active:false,heldIds:[]};}
 const human=actor('human'),robot=actor('robot'),vacuumGroup=new THREE.Group();scene.add(vacuumGroup);const vacuumBody=cylinder(vacuumGroup,[0,-.01,0],[.30,.18,.30],palette.teal);cylinder(vacuumGroup,[0,.095,0],[.11,.03,.11],palette.ink);for(const x of [-.16,.16])cylinder(vacuumGroup,[x,-.06,0],[.055,.04,.055],palette.ink).rotation.z=Math.PI/2;const vacuum={group:vacuumGroup,body:vacuumBody,active:false};inspect(vacuumBody,t('Aspirador autónomo acotado. La suciedad cambia tras una pasada de contacto registrada en el modelo.','A bounded autonomous vacuum. Dirt changes after a contact pass recorded by the model.'));
 const humanVacuumHandle=rod(scene,[0,0,0],[0,1,0],.022,palette.steel);humanVacuumHandle.visible=false;const actors={human,robot,vacuum},propGroup=new THREE.Group();scene.add(propGroup);const propById=new Map(),objectRecords=[];
 function buildProp(spec){const id=spec.id,kind=spec.kind||'object',g=new THREE.Group();propGroup.add(g);let body,foldFlaps=null;
  if(kind.includes('dirt')||kind.includes('stain')){body=ball(g,[0,0,0],[.055,.009,.08],mat(kind.includes('stain')?0x979d79:0x7c6552,{roughness:1}));}
  else if(kind.includes('plate')){const radius=spec.radius||.23;body=cylinder(g,[0,0,0],[radius,spec.size?.[1]||.035,radius],palette.cream);cylinder(g,[0,.022,0],[radius*.73,.008,radius*.73],palette.white);}
  else if(kind.includes('ingredient')){body=ball(g,[0,0,0],[.10,.095,.10],mat(id.endsWith('1')||id.endsWith('3')?0x96b779:0xddad7c));}
  else if(kind.includes('cloth')||kind.includes('garment')){const size=spec.size||[.32,.10,.23];if(spec.id==='cloth-tool')body=box(g,[0,0,0],size,palette.teal);else{body=box(g,[0,0,0],[size[0]*.50,size[1]*.65,size[2]],palette.purple);foldFlaps=[];for(const sign of [-1,1]){const flap=new THREE.Group();flap.position.set(sign*size[0]*.25,size[1]*.30,0);g.add(flap);box(flap,[sign*size[0]*.125,0,0],[size[0]*.25,size[1]*.32,size[2]],mat(0xc2b1db,{roughness:.97}));foldFlaps.push({group:flap,sign});}}}
  else if(kind.includes('blanket')){body=box(g,[0,0,0],[2.24,.075,1.80],palette.cloth);for(let i=0;i<6;i++)box(g,[-.92+i*.37,.04,0],[.03,.015,1.69],mat(0xc1d2df));}
  else if(kind.includes('pillow'))body=ball(g,[0,0,0],[.42,.13,.24],palette.cream);
  else if(kind.includes('document')){body=box(g,[0,0,0],[.38,.012,.28],palette.white);for(let i=0;i<3;i++)box(g,[0,.008,-.075+i*.055],[.25,.003,.009],palette.ink);}
  else if(kind.includes('tool')){body=box(g,[0,0,0],[.22,.025,.19],palette.teal);}
  else body=box(g,[0,0,0],[.16,.08,.16],palette.wood);
  body.userData.objectId=id;body.userData.kind=kind;inspect(body,t('Objeto persistente: ','Persistent object: ')+id,t('Objeto persistente: ','Persistent object: ')+id);const record={id,kind,spec,group:g,body,foldFlaps,state:null};propById.set(id,record);objectRecords.push(record);return record;}
 const specs=Model.HOME_OBJECTS||[];for(const spec of specs)buildProp(spec);
 const contactGroup=new THREE.Group();scene.add(contactGroup);const contactMarker=ball(contactGroup,[0,0,0],.045,palette.gold);contactMarker.visible=false;const contactLine=rod(contactGroup,[0,0,0],[0,.01,0],.009,palette.gold);contactLine.visible=false;
 const standsGroup=new THREE.Group();scene.add(standsGroup);HOME_STAND_POSITIONS.forEach((p,i)=>{const [x,y,z]=p;box(standsGroup,[x,.055,z],[.44,.10,.36],palette.ink);rod(standsGroup,[x,.10,z],[x,1.04,z],.043,palette.steel);box(standsGroup,[x,1.07,z],[.48,.055,.35],palette.ink);const button=box(standsGroup,[x,1.12,z],[.32,.07,.25],mat(0xebc180,{emissive:0xebc180,emissiveIntensity:.18,name:'stand-'+i}));button.userData.action=i;targets.push(button);stands.push(button);label(standsGroup,String(i+1)+' · ▶',[x,1.29,z],.43,{maxHeight:.15});}); let lastFrame,activeChapter=0;
 const stageNames={completed:['Completado','Completed'],travel:['Ir a la zona','Travel to the area'],vacuum:['Aspirar por contacto','Vacuum by contact'],park:['Volver a la base','Return to dock'],pick:['Recoger','Pick up'],'carry-to-pot':['Llevar a la olla','Carry to the pot'],'load-pot':['Poner en la olla','Load the pot'],'carry-meal':['Llevar la comida','Carry the meal'],'place-meal':['Poner la mesa','Place the meal'],'carry-to-fold':['Llevar a doblado','Carry to folding table'],blanket:['Estirar la manta','Straighten the blanket'],'approach-pillows':['Acercarse a las almohadas','Approach the pillows'],'pillow-left':['Ajustar almohada izquierda','Adjust left pillow'],'pillow-right':['Ajustar almohada derecha','Adjust right pillow'],return:['Volver','Return'],'pick-cloth':['Recoger el paño','Pick up the cloth'],'wipe-sink':['Limpiar el lavabo','Wipe the basin'],'approach-floor':['Acercarse al suelo','Approach the floor'],'wipe-floor':['Limpiar el suelo por contacto','Wipe the floor by contact'],'park-cloth':['Dejar el paño','Put down the cloth'],idle:['En espera','Idle'],loading:['Cargando','Loading'],washing:['Lavado · espera comprimida','Wash · compressed wait'],drying:['Secado · espera comprimida','Dry · compressed wait'],unloading:['Sacando prendas','Unloading'],finished:['Listo','Finished'],cooking:['Cocción · espera comprimida','Cooking · compressed wait'],finish:['Terminar y comprobar','Finish and check'],pending:['Pendiente','Pending'],approach:['Acercarse','Approach'],pickup:['Recoger','Pick up'],carry:['Transportar','Carry'],load:['Cargar','Load'],wash:['Lavado · espera comprimida','Wash · compressed wait'],dry:['Secado · espera comprimida','Dry · compressed wait'],unload:['Sacar','Unload'],fold:['Doblar las mismas prendas','Fold the same garments'],prepare:['Preparar ingredientes','Prepare ingredients'],cook:['Cocinar · espera comprimida','Cook · compressed wait'],serve:['Servir la comida','Serve the meal'],straighten:['Estirar la manta','Straighten the blanket'],pillow:['Colocar almohadas','Place pillows'],wipe:['Limpiar por contacto','Clean by contact'],input:['Leer petición','Read request'],draft:['Proponer','Propose'],review:['Revisar','Review'],approve:['Aprobar','Approve'],done:['Completado','Completed']};
 const vec=v=>Array.isArray(v)&&v.length>=3?v:[0,0,0];
 function setRod(m,a,b,r){const delta=new THREE.Vector3().subVectors(b,a),length=delta.length();m.position.copy(a).add(b).multiplyScalar(.5);m.scale.set(r,Math.max(.001,length),r);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),length>1e-8?delta.multiplyScalar(1/length):new THREE.Vector3(0,1,0));}
 function poseActor(record,state){if(!state){record.group.visible=false;return;}record.state=state;record.active=!!state.active;record.heldIds=[...(state.heldIds||[])];record.group.position.set(...vec(state.position));record.group.rotation.y=Number.isFinite(state.yaw)?state.yaw:0;const crouch=clamp(Number.isFinite(state.crouch)?state.crouch:state.posture==='crouch'?1:0,0,1),lower=crouch*.46,lean=clamp(Number(state.lean)||0,0,1);record.torso.position.set(0,1.12-lower,lean*.10);record.torso.rotation.x=-lean*.16;record.hips.position.y=.79-lower*.65;record.head.position.set(0,1.57-lower,lean*.13);record.neck.position.set(0,1.38-lower,lean*.11);record.group.updateMatrixWorld(true);
  for(const [side,arm] of Object.entries(record.arms)){const shoulder=arm.shoulder.clone();shoulder.y-=lower;shoulder.z+=lean*.16;const raw=state.hands?.[side],target=raw?record.group.worldToLocal(new THREE.Vector3(...vec(raw))):new THREE.Vector3(shoulder.x,shoulder.y-.60,shoulder.z-.04),d=target.clone().sub(shoulder),length=d.length(),mid=shoulder.clone().add(target).multiplyScalar(.5),bend=new THREE.Vector3(side==='left'?-.35:.35,.12,.4).projectOnPlane(length?d.clone().normalize():new THREE.Vector3(0,1,0)).normalize().multiplyScalar(Math.sqrt(Math.max(.008,.40*.40-length*length/4))),elbow=mid.add(bend);setRod(arm.upper,shoulder,elbow,.062);setRod(arm.lower,elbow,target,.050);arm.elbow.position.copy(elbow);arm.hand.position.copy(target);arm.target=raw?[...raw]:null;arm.reach=length;arm.hand.userData.worldTarget=arm.target;}
  const hipY=.79-lower*.65,kneeY=.43-.15*crouch;record.legs.forEach((leg,i)=>{const x=i===0?-.12:.12;leg.knee.position.set(x,kneeY,.19*crouch);setRod(leg.thigh,new THREE.Vector3(x,hipY,0),new THREE.Vector3(x,kneeY,.19*crouch),.073);setRod(leg.shin,new THREE.Vector3(x,kneeY,.19*crouch),new THREE.Vector3(x,.10,0),.060);});record.group.userData.active=record.active;record.group.userData.heldIds=record.heldIds;record.group.userData.posture=state.posture||'stand';
 }
 function withinRoom(position,index){const b=HOME_ROOMS[index].bounds;return position[0]>=b[0]-.05&&position[0]<=b[3]+.05&&position[2]>=b[2]-.05&&position[2]<=b[5]+.05;}
 function update(frame,chapter=frame?.index??0,whole=false,immersive=false){if(!frame)return;lastFrame=frame;activeChapter=chapterIndex(chapter);const roomIndex=HOME_CHAPTER_ROOMS[activeChapter],all=whole||immersive;
  wallMaterial.opacity=immersive?1:.09;wallMaterial.depthWrite=immersive;walls.forEach(m=>m.castShadow=immersive);frontDoor.material.transparent=true;frontDoor.material.opacity=immersive?1:.09;frontDoor.material.depthWrite=immersive;ceiling.visible=immersive;ceiling.castShadow=immersive;
  roomGroups.forEach(g=>g.visible=true);annotations.forEach((g,i)=>g.visible=!whole&&i===activeChapter);simulationCaptions.forEach(caption=>caption.m.visible=!immersive);roomLabels.forEach(r=>r.m.visible=all);standsGroup.visible=true;
  for(const kind of ['human','robot']){const record=actors[kind],state=frame.actors?.[kind];poseActor(record,state);record.group.visible=!!state;}
  const vacuumState=frame.actors?.vacuum;vacuum.state=vacuumState||null;vacuum.active=!!vacuumState?.active;if(vacuumState){vacuum.group.position.set(...vec(vacuumState.position));vacuum.group.rotation.y=vacuumState.yaw||0;}vacuum.group.visible=!!vacuumState;vacuum.body.userData.active=vacuum.active;humanVacuumHandle.visible=vacuumState?.mode==='human-operated'&&!!vacuumState.active;if(humanVacuumHandle.visible)setRod(humanVacuumHandle,new THREE.Vector3(...vec(frame.actors.human.hands.right)),new THREE.Vector3(...vec(vacuumState.position)).add(new THREE.Vector3(0,.05,0)),.022);
  for(const state of frame.objects||[]){let record=propById.get(state.id);if(!record)record=buildProp(state);record.state=state;record.group.position.set(...vec(state.position));if(Array.isArray(state.rotation))record.group.rotation.set(...state.rotation);else record.group.rotation.set(0,Number(state.rotation)||0,0);record.group.visible=state.visible!==false;record.group.userData.objectId=record.id;record.group.userData.status=state.status;record.group.userData.holder=state.holder??null;record.group.userData.ready=!!state.ready;Object.assign(record.body.userData,{objectId:record.id,status:state.status,holder:state.holder??null,ready:!!state.ready});if(record.foldFlaps){const progress=clamp(state.foldProgress??(state.status==='folded'?1:0),0,1);record.foldFlaps.forEach(flap=>flap.group.rotation.z=-flap.sign*Math.PI*progress);record.group.scale.set(1,1,1-.10*progress);record.group.userData.foldProgress=progress;}}
  const appliances=frame.appliances||{};dishwasher.state=appliances.dishwasher||{};washerDryer.state=appliances.washerDryer||{};hob.userData.state=appliances.hob||{};dishwasher.door.rotation.x=dishwasher.state.doorOpen?Math.PI/2:0;washerDryer.door.rotation.y=washerDryer.state.doorOpen?-1.72:0;washerDryer.drum.rotation.y=washerDryer.state.running?(washerDryer.state.cycleProgress||0)*Math.PI*8:0;potLid.visible=potKnob.visible=appliances.hob?.phase==='cooking';
  const a=appliances.hob||{};hob.material.emissive.setHex(a.on?0xa76638:0x000000);hob.material.emissiveIntensity=a.on?.24:0;
  const task=frame.tasks?.[activeChapter],name=task?.stage||task?.status||'pending',description=stageNames[name];simulationCaptions[activeChapter].set((description?t(...description):String(name).replaceAll('-',' '))+'\n'+(frame.capacity==='human'||frame.actorMode==='human'?t('Trabajo humano · mismo guion','Human work · same script'):activeChapter===0?t('Disponible hoy · entorno acotado','Available today · bounded setting'):activeChapter===6?(frame.planning?.reviewRequired?t('IA · ejemplo ficticio','AI · fictional example'):t('IA · delegación completa supuesta','AI · assumed full delegation')):t('Hipótesis futura · manipulación general','Future assumption · general manipulation')));
  function machineLabel(key,title){const s=appliances[key]||{},stage=s.phase||'pending';applianceCaptions[key].set(title+' · '+(stageNames[stage]?t(...stageNames[stage]):stage));}
  machineLabel('dishwasher',t('LAVAVAJILLAS','DISHWASHER'));machineLabel('washerDryer',t('LAVADORA/SECADORA','WASHER/DRYER'));
  const planning=frame.planning||{};planningPanel.state=planning;planningPanel.input.set(planning.inputReady?t('ENTRADA · compras + agenda','INPUT · shopping + schedule'):t('ENTRADA · pendiente','INPUT · pending'));planningPanel.draft.set(planning.draftReady?t('PROPUESTA · lista + horario','DRAFT · list + schedule'):t('PROPUESTA · pendiente','DRAFT · pending'));planningPanel.review.set(planning.approved?(planning.approvalAssumed?t('APROBACIÓN · delegación supuesta','APPROVAL · assumed delegation'):t('APROBACIÓN · revisada','APPROVAL · reviewed')):planning.reviewReady?(planning.reviewRequired?t('REVISIÓN · humana','REVIEW · human'):t('REVISIÓN · delegada (supuesto)','REVIEW · delegated (assumed)')):t('REVISIÓN · pendiente','REVIEW · pending'));
  const contact=(frame.contacts||[]).at(-1),current=contact&&Math.abs((Number(frame.time)||0)-contact.time)<=.22;contactMarker.visible=contactLine.visible=!!current&&!!contact.point&&(all||withinRoom(contact.point,roomIndex));if(contactMarker.visible){contactMarker.position.set(...contact.point);const source=frame.actors?.[contact.actor],hands=source?.hands||{},hand=hands.right||hands.left||contact.point;setRod(contactLine,new THREE.Vector3(...hand),new THREE.Vector3(...contact.point),.009);contactLine.userData.contact=contact;contactMarker.userData.contact=contact;}else{contactLine.userData.contact=null;contactMarker.userData.contact=null;}
  stands.forEach((button,i)=>{button.material.emissiveIntensity=i===activeChapter?.45:.12;button.userData.status=frame.tasks?.[i]?.status||'pending';});scene.updateMatrixWorld(true);
 }
 scene.updateMatrixWorld(true);
 return {scene,resources,targets,stands,standsGroup,annotations,roomGroups,rooms:HOME_ROOMS,bounds:HOME_BOUNDS,solids:HOME_SOLIDS,focus:HOME_FOCUS,parts:{furnitureSolids:HOME_FURNITURE_SOLIDS,architecture,floor,walls,windows,ceiling,doorFrames,roomGroups,roomLabels,props:propById,propById,objectRecords,actors,humanVacuumHandle,contactLine,contactMarker,dishwasher,washerDryer,hob,pot,board,bedBase,mattress,basket,foldboard,basin,planningPanel,simulationCaptions,applianceCaptions,stands},update,get state(){return lastFrame;},get chapter(){return activeChapter;}};
}

function segmentClear(a,b,r=.25,solids=HOME_SOLIDS){for(const q of solids){let low=0,high=1;const min=[q[0]-r,q[1]-r],max=[q[2]+r,q[3]+r],start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];let intersect=true;for(let d=0;d<2;d++){if(Math.abs(delta[d])<1e-12){if(start[d]<=min[d]||start[d]>=max[d]){intersect=false;break;}}else{let near=(min[d]-start[d])/delta[d],far=(max[d]-start[d])/delta[d];if(near>far)[near,far]=[far,near];low=Math.max(low,near);high=Math.min(high,far);if(low>=high){intersect=false;break;}}}if(intersect&&low<high&&high>0&&low<1)return false;}return true;}
let navigationGrid;
function homeGrid(){if(navigationGrid)return navigationGrid;const spacing=.15,minX=-5.70,minZ=-4.65,nx=77,nz=63,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*spacing,z=minZ+zi*spacing;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!overlaps(x,z,.25)});}return navigationGrid={spacing,nx,nz,nodes};}
export function homeGuidePath(from,to){const start=restoreHomePose(from),end=restoreHomePose(to);if(segmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=homeGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const distance=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&distance<d&&segmentClear(p,q)){best=q;d=distance;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const opened=new Set([first.index]),cost=new Map([[first.index,0]]),previous=new Map(),closed=new Set();let found=false;
 while(opened.size){let current=null,best=Infinity;for(const index of opened){const q=g.nodes[index],score=cost.get(index)+Math.hypot(q.x-last.x,q.z-last.z);if(score<best){best=score;current=q;}}opened.delete(current.index);if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const next=g.nodes[zi*g.nx+xi];if(!next.open||closed.has(next.index)||!segmentClear(current,next))continue;const candidate=cost.get(current.index)+g.spacing*Math.hypot(dx,dz);if(candidate<(cost.get(next.index)??Infinity)){cost.set(next.index,candidate);previous.set(next.index,current.index);opened.add(next.index);}}}
 if(!found)return [];const route=[{x:end.x,z:end.z}],ordered=[];for(let i=last.index;i!==undefined;i=previous.get(i)){ordered.push({x:g.nodes[i].x,z:g.nodes[i].z});if(i===first.index)break;}ordered.reverse();ordered.unshift({x:start.x,z:start.z});ordered.push(...route);const simplified=[ordered[0]];let cursor=0;while(cursor<ordered.length-1){let next=ordered.length-1;while(next>cursor+1&&!segmentClear(ordered[cursor],ordered[next]))next--;simplified.push(ordered[next]);cursor=next;}return simplified;
}
export function homeNearestStand(pose){let best=null;HOME_STAND_POSITIONS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),targetYaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(targetYaw-pose.yaw),Math.cos(targetYaw-pose.yaw))),solids=HOME_SOLIDS.filter(b=>b!==HOME_STAND_SOLIDS[index]);if(distance<2.4&&angle<1.35&&Math.abs(Math.atan2(y+.02-1.65,distance)-(pose.pitch||0))<.70&&segmentClear(pose,{x,z},0,solids)&&(!best||distance<best.distance))best={index,distance,angle};});return best;}
function visible(m){for(let q=m;q;q=q.parent)if(!q.visible)return false;return true;}
export const homeOverview={yaw:.62,pitch:.69,distance:10,whole:false};
export function createHomeWorld(host,es=true,onListen=()=>{},onInfo=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.10;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);const built=createHomeScene(es),camera=new THREE.PerspectiveCamera(46,1,.055,120),ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),canvas=renderer.domElement,orbit={...homeOverview};let frame,chapter=0,mode='notebook',pose=homePoseAt(0),dragging=false,lastX=0,lastY=0,pinch=0,pointerDown,disposed=false;canvas.tabIndex=0;
 function resize(){const width=Math.max(1,host.clientWidth),height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.fov=camera.aspect<1?64:46;camera.updateProjectionMatrix();}
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function draw(){if(disposed)return;if(frame)built.update(frame,chapter,orbit.whole&&mode!=='immersive',mode==='immersive');if(mode==='immersive'){camera.position.set(pose.x,1.65,pose.z);camera.rotation.set(pose.pitch,pose.yaw,0,'YXZ');}else{const f=homeFraming(chapter,orbit,camera.aspect,camera.fov,frame);camera.position.copy(f.center).addScaledVector(f.direction,f.distance);camera.lookAt(f.center);}camera.updateMatrixWorld();built.scene.updateMatrixWorld(true);renderer.render(built.scene,camera);}
 function hit(x,y){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return null;pointer.set(x===null?0:(x-r.left)/r.width*2-1,y===null?0:1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);const found=ray.intersectObjects(built.scene.children,true).filter(h=>visible(h.object)&&!h.object.isSprite);for(const h of found){const object=h.object;if(object.userData.action!==undefined||object.userData.info)return h;if(object.material?.opacity>.6)return null;}return null;}
 function inspect(x=null,y=null){const h=hit(x,y);if(!h)return null;const action=h.object.userData.action;if(action!==undefined)onListen(action);else if(h.object.userData.info)onInfo(h.object.userData.info);return action!==undefined?{chapter:action}:h.object.userData.info;}
 function nearest(p=pose){return homeNearestStand(p)?.index??null;}
 function activate(){const h=hit(null,null),index=h?.object.userData.action??nearest();if(index!==null&&index!==undefined)onListen(index);return index;}
 const listeners=[],listen=(target,type,fn,options)=>{target.addEventListener(type,fn,options);listeners.push(()=>target.removeEventListener(type,fn,options));};
 listen(canvas,'pointerdown',e=>{if(mode==='immersive')return;dragging=true;lastX=e.clientX;lastY=e.clientY;pointerDown={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});listen(canvas,'pointermove',e=>{if(!dragging||mode==='immersive')return;orbit.yaw-=(e.clientX-lastX)*.005;orbit.pitch=clamp(orbit.pitch+(e.clientY-lastY)*.004,.12,1.35);lastX=e.clientX;lastY=e.clientY;draw();});listen(canvas,'pointerup',e=>{if(dragging&&pointerDown&&Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)<6)inspect(e.clientX,e.clientY);dragging=false;pointerDown=null;});listen(canvas,'pointercancel',()=>{dragging=false;pointerDown=null;});
 listen(canvas,'wheel',e=>{if(mode==='immersive')return;e.preventDefault();orbit.distance=clamp(orbit.distance*(e.deltaY>0?1.08:.92),4,35);draw();},{passive:false});listen(canvas,'touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});listen(canvas,'touchmove',e=>{if(mode==='immersive'||e.touches.length!==2)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch&&d){orbit.distance=clamp(orbit.distance*pinch/d,4,35);draw();}pinch=d;},{passive:true});
 listen(canvas,'keydown',e=>{if(mode==='immersive')return;if(e.key==='ArrowLeft')orbit.yaw-=.1;else if(e.key==='ArrowRight')orbit.yaw+=.1;else if(e.key==='ArrowUp')orbit.pitch=clamp(orbit.pitch-.08,.12,1.35);else if(e.key==='ArrowDown')orbit.pitch=clamp(orbit.pitch+.08,.12,1.35);else return;e.preventDefault();draw();});listen(canvas,'webglcontextlost',e=>e.preventDefault());
 function getViewState(){return {yaw:orbit.yaw,pitch:orbit.pitch,distance:orbit.distance,whole:!!orbit.whole};}
 function restoreViewState(value={}){const v=value&&typeof value==='object'?(value.orbit||value):{};for(const k of ['yaw','pitch','distance'])if(Number.isFinite(v[k]))orbit[k]=k==='distance'?clamp(v[k],4,35):k==='pitch'?clamp(v[k],.12,1.35):v[k];orbit.whole=v.whole===true;draw();}
 return {canvas,dom:canvas,scene:built.scene,built,camera,orbit,update(value,i){frame=value;chapter=chapterIndex(i??value?.index??chapter);},render(value,dt,i){if(value){frame=value;chapter=chapterIndex(i??value.index??chapter);}draw();},focus(i){chapter=chapterIndex(i);orbit.whole=false;draw();},setMode(value){mode=value==='immersive'?'immersive':'notebook';dragging=false;draw();},setPose(value){pose=restoreHomePose(value);},fit(options={}){Object.assign(orbit,homeOverview,options);draw();},overview(all=true){orbit.whole=all!==false&&all!=='zone';draw();},zoomBy(f){if(Number.isFinite(f)&&f>0)orbit.distance=clamp(orbit.distance/f,4,35);draw();},getViewState,restoreViewState,inspect,nearest,activate,poseAt:homePoseAt,walk:homeWalk,rooms:HOME_ROOMS,solids:HOME_SOLIDS,get stats(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};},dispose(){if(disposed)return;disposed=true;observer.disconnect();listeners.forEach(fn=>fn());for(const r of [...built.resources])r.dispose();renderer.dispose();canvas.remove();}};
}