export function timeBudget(tasks,selected,overhead){const total=tasks.reduce((n,t)=>n+t.minutes,0),delegated=tasks.filter(t=>selected.has(t.id)).reduce((n,t)=>n+t.minutes,0),support=delegated*overhead/100;return {total,delegated,support,freed:delegated-support,remaining:total-delegated+support};}
// Seconds are presentation time, minutes are illustrative human active work.
export const CHORES=[
 {id:'floor',minutes:25,actor:'vacuum',es:'Aspirar el suelo',en:'Vacuum the floor',room:['Salón','Living room'],position:[-3,2.5],detail:['El aspirador recorre la alfombra y recoge la suciedad. Es una automatización disponible hoy, con límites de acceso y mantenimiento.','The vacuum crosses the rug and collects dirt. This automation exists today, with access and maintenance limits.']},
 {id:'dishes',minutes:15,actor:'robot',es:'Recoger y lavar platos',en:'Clear and wash dishes',room:['Cocina','Kitchen'],position:[-2.3,-1.1],detail:['Un robot retira los platos y carga el lavavajillas. La manipulación general y fiable se supone en este escenario futuro.','A robot clears dishes and loads the dishwasher. Reliable general manipulation is assumed in this future scenario.']},
 {id:'cook',minutes:35,actor:'robot',es:'Preparar la comida',en:'Prepare a meal',room:['Cocina','Kitchen'],position:[-3,-3.1],detail:['El robot prepara ingredientes y sirve una comida. Suponemos destreza, seguridad y una cocina compatible; no es una capacidad universal demostrada.','The robot prepares ingredients and serves a meal. Dexterity, safety and a compatible kitchen are assumed; this is not a proven universal capability.']},
 {id:'laundry',minutes:25,actor:'robot',es:'Lavar y doblar ropa',en:'Wash and fold laundry',room:['Lavadero','Laundry'],position:[2.4,2.8],detail:['La ropa del cesto pasa a la lavadora y vuelve doblada. Solo contamos trabajo humano activo: los tiempos de lavado se comprimen en la animación.','Clothes move from the basket to the washer and return folded. Only active human work is counted: wash times are compressed in the animation.']},
 {id:'bed',minutes:10,actor:'robot',es:'Hacer la cama',en:'Make the bed',room:['Dormitorio','Bedroom'],position:[3.35,-1.8],detail:['El robot estira la ropa de cama y coloca las almohadas. La escena supone que puede manipular tejidos y adaptarse al mobiliario.','The robot straightens the bedding and places pillows. The scene assumes it can handle fabric and adapt to furniture.']},
 {id:'bath',minutes:20,actor:'robot',es:'Limpiar el baño',en:'Clean the bathroom',room:['Baño','Bathroom'],position:[4.05,2.2],detail:['El robot limpia el lavabo y el suelo. Se supone resistencia al agua, higiene y manejo seguro de productos.','The robot cleans the basin and floor. Water resistance, hygiene and safe handling of products are assumed.']},
 {id:'plan',minutes:15,actor:'ai',es:'Organizar compras y agenda',en:'Plan shopping and schedules',room:['Escritorio','Study'],position:[4.7,-2.4],detail:['La IA prepara una lista y organiza el calendario. Aquí suponemos delegación completa; en un uso actual pueden hacer falta revisión y aprobación.','AI prepares a list and organizes the calendar. Full delegation is assumed here; current use may require review and approval.']}
];
export const TASK_SECONDS=10,DURATION=CHORES.length*TASK_SECONDS;
export function createHome(overhead=0){return {time:0,overhead,playing:false};}
export function tickHome(s,dt){if(s.playing&&Number.isFinite(dt)&&dt>0)s.time=Math.min(DURATION,s.time+dt);if(s.time>=DURATION)s.playing=false;return s;}
export function homeSnapshot(s){const done=Math.min(CHORES.length,Math.floor(s.time/TASK_SECONDS)),index=Math.min(done,CHORES.length-1),phase=s.time>=DURATION?1:(s.time%TASK_SECONDS)/TASK_SECONDS;return {done,index,phase,work:Math.max(0,(phase-.25)/.75),complete:done===CHORES.length,...timeBudget(CHORES,new Set(CHORES.slice(0,done).map(t=>t.id)),s.overhead)};}
