import {places,t,sources} from './places.js';
const $=s=>document.querySelector(s),es=document.documentElement.lang==='es';
const langs=es?['../../terafab/index.html','./index.html']:['./index.html','../es/terafab/index.html'];
$('#app').innerHTML=`<header class="topbar"><a class="brand" href="../index.html"><b>a.</b><span>ATLAS<small>${t('EXPLICACIONES INTERACTIVAS','INTERACTIVE EXPLANATIONS')}</small></span></a><nav aria-label="${t('Exploraciones','Explorations')}"><a href="../index.html">${t('← Colección','← Collection')}</a><a href="../robots/index.html">Robots</a><a href="./index.html" aria-current="page">Terafab</a></nav><div class="languages"><a href="${langs[0]}" ${!es?'aria-current="true"':''}>EN</a><a href="${langs[1]}" ${es?'aria-current="true"':''}>ES</a></div></header>
<section class="heading"><div><span class="eyebrow">TERAFAB / GRIMES COUNTY, TEXAS</span><h1>${t('Dentro de la fábrica prevista.','Inside the planned factory.')}</h1></div><p>${t('Explora las naves, abre la cubierta<br>y acércate a cada equipo.','Explore the halls, open the roof<br>and move closer to each tool.')}</p></section>
<section class="workspace"><div class="main-view"><div class="viewbar" role="group" aria-label="${t('Vistas de la fábrica','Factory views')}"><button data-view="campus" aria-pressed="true">01 <span>${t('Complejo','Campus')}</span></button><button data-view="cleanroom" aria-pressed="false">02 <span>${t('Sala limpia','Cleanroom')}</span></button><button data-view="layers" aria-pressed="false">03 <span>${t('Capas de la nave','Hall layers')}</span></button></div>
<div class="scene" id="scene"><div id="viewport" tabindex="0" role="img" aria-label="${t('Maqueta 3D de la fábrica. Arrastra para mover, usa más y menos para acercar, flechas para girar. Las zonas también se seleccionan en la lista.','3D factory model. Drag to pan, use plus and minus to zoom, arrows to rotate. Areas can also be selected from the list.')}"></div><div class="scene-loading" id="loading">${t('Preparando el complejo…','Preparing the campus…')}</div><div id="labels" aria-label="${t('Zonas de la fábrica','Factory areas')}"></div><div class="scene-heading"><div><span class="eyebrow" id="view-label">${t('VISTA DEL COMPLEJO','CAMPUS VIEW')}</span><p id="view-note">${t('Volúmenes basados en la imagen oficial','Volumes based on the official rendering')}</p></div><button id="enter" class="primary">${t('Abrir la cubierta ↗','Open the roof ↗')}</button></div><div class="scene-bottom"><span id="gesture-hint">${t('Arrastra · rueda para acercar · Mayús para girar','Drag · scroll to zoom · Shift to rotate')}</span><div class="camera-controls"><button id="rotate-left" aria-label="${t('Girar a la izquierda','Rotate left')}">↶</button><button id="rotate-right" aria-label="${t('Girar a la derecha','Rotate right')}">↷</button><button id="minus" aria-label="${t('Alejar','Zoom out')}">−</button><button id="fit" aria-label="${t('Centrar esta vista','Center this view')}">⌖</button><button id="plus" aria-label="${t('Acercar','Zoom in')}">+</button><button id="fullscreen" aria-label="${t('Pantalla completa','Fullscreen')}">⛶</button></div></div></div>
<div class="transport"><button id="motion" aria-pressed="true">${t('Ⅱ Pausar actividad','Ⅱ Pause activity')}</button><button id="follow" class="follow" aria-pressed="false">${t('◎ Seguir una oblea','◎ Follow a wafer')}</button><span id="activity-note">${t('Movimiento ilustrativo · sin escala temporal','Illustrative motion · no time scale')}</span></div><p class="scope">${t('Reconstrucción a partir del render y del expediente públicos. La distribución interior y los equipos son aproximados.','Reconstruction from the public rendering and application. Interior layout and equipment are approximate.')}</p></div>
<aside class="inspector"><div class="inspector-top"><span class="eyebrow">${t('EXPLORAR LA FÁBRICA','EXPLORE THE FACTORY')}</span><span id="place-count"></span></div><label class="sr-only" for="place-select">${t('Seleccionar una zona','Select an area')}</label><select id="place-select">${places.map((p,i)=>`<option value="${p.id}">${String(i+1).padStart(2,'0')} · ${p.name}</option>`).join('')}</select><div class="detail-body" aria-live="polite"><span class="detail-tag" id="detail-tag"></span><h2 id="detail-name"></h2><p id="detail-body"></p><section class="equipment"><h3>${t('QUÉ ESTÁS VIENDO','WHAT YOU ARE LOOKING AT')}</h3><p id="detail-equipment"></p></section><section class="activity"><h3>${t('CÓMO FUNCIONA','HOW IT WORKS')}</h3><p id="detail-activity"></p></section></div><div class="evidence"><span>${t('BASE DE ESTA RECONSTRUCCIÓN','BASIS FOR THIS RECONSTRUCTION')}</span><p id="detail-evidence"></p><a id="detail-source" target="_blank" rel="noreferrer">${t('Consultar fuente ↗','Read source ↗')}</a></div><div class="tour"><button id="previous" aria-label="${t('Zona anterior','Previous area')}">←</button><button id="tour">${t('▶ Recorrer fábrica','▶ Tour the factory')}</button><button id="next" aria-label="${t('Zona siguiente','Next area')}">→</button></div></aside></section>
<section class="areas"><span class="eyebrow">${t('ACCESO DIRECTO A LAS ZONAS','JUMP TO AN AREA')}</span><div>${places.slice(1).map(p=>`<button data-place="${p.id}" aria-pressed="false">${p.name}</button>`).join('')}</div></section>
<details class="reference"><summary>${t('Comparar con la imagen oficial y consultar las fuentes','Compare with the official rendering and read the sources')}</summary><div class="reference-grid"><figure><a href="${sources.render}" target="_blank" rel="noreferrer"><img src="./official-exterior.jpg" alt="${t('Render oficial: naves alargadas en parejas, corredores centrales y frente conectado','Official rendering: paired long halls, central corridors and connected frontage')}" loading="lazy" width="3840" height="2160"></a><figcaption>${t('Imagen publicada por Terafab · referencia del exterior','Image published by Terafab · exterior reference')}</figcaption></figure><div><h2>${t('Qué conocemos de la fábrica','What we know about the factory')}</h2><p>${t('El expediente de la fase 1 enumera las instalaciones y familias de equipos previstas. La maqueta utiliza esa lista y la imagen exterior, sin convertirlos en un plano de ingeniería.','The Phase 1 application lists planned facilities and equipment families. The model uses that list and the exterior rendering without presenting them as an engineering plan.')}</p><a href="${sources.project}#page=7" target="_blank" rel="noreferrer">${t('Expediente JETI · proyecto (p. 7), instalaciones (pp. 27–28) ↗','JETI application · project (p. 7), facilities (pp. 27–28) ↗')}</a><a href="https://www.terafab.ai/" target="_blank" rel="noreferrer">Terafab · ${t('anuncio y render oficial','announcement and official rendering')} ↗</a><a href="${sources.asml}" target="_blank" rel="noreferrer">ASML · ${t('operaciones de fabricación','manufacturing operations')} ↗</a><a href="${sources.lam}" target="_blank" rel="noreferrer">Lam Research · ${t('deposición, grabado y limpieza','deposition, etch and cleaning')} ↗</a><a href="${sources.transport}" target="_blank" rel="noreferrer">Daifuku · ${t('transporte de obleas protegido','protected wafer transport')} ↗</a><p class="secondary">${t('Equipos genéricos, sin marcas contratadas ni cantidades reales. La ruta animada está abreviada. Consultado el 16 de septiembre de 2026.','Generic equipment, with no claimed contracted brands or actual quantities. The animated route is abbreviated. Consulted September 16, 2026.')}</p></div></div></details>
<footer><span>${t('Explicación independiente · sin afiliación con Terafab, Tesla o SpaceX.','Independent explanation · not affiliated with Terafab, Tesla or SpaceX.')}</span><a href="../robots/index.html">${t('Explorar Robots →','Explore Robots →')}</a></footer>`;

let world=null,selected='campus',view='campus',tour=false,tourElapsed=0,motionTime=0,lastFrame=0,playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;
function detail(id){const p=places.find(p=>p.id===id);if(!p)return;selected=id;$('#place-select').value=id;$('#place-count').textContent=String(places.indexOf(p)+1).padStart(2,'0')+' / '+places.length;for(const key of ['tag','name','body','equipment','activity','evidence'])$('#detail-'+key).textContent=p[key];$('#detail-source').href=sources[p.source];document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.place===id)));$('#previous').disabled=id==='campus';}
function syncView(){view=world?.view||view;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('#view-label').textContent=view==='campus'?t('VISTA DEL COMPLEJO','CAMPUS VIEW'):view==='layers'?t('CORTE VERTICAL · NIVELES SEPARADOS','VERTICAL SECTION · SEPARATED LEVELS'):t('DENTRO DE LA SALA LIMPIA','INSIDE THE CLEANROOM');$('#view-note').textContent=view==='campus'?t('Volúmenes basados en la imagen oficial','Volumes based on the official rendering'):view==='layers'?t('Subfábrica → sala de proceso → filtración','Sub-fab → process room → filtration'):t('Equipos y distribución interior representativos','Representative equipment and interior layout');$('#enter').hidden=view!=='campus';$('#follow').setAttribute('aria-pressed',String(!!world?.following));}
function choose(id){const p=places.find(p=>p.id===id);if(!p)return;detail(id);world?.select(p);syncView();}
function setTour(on){tour=on;tourElapsed=0;$('#tour').textContent=tour?t('Ⅱ Pausar recorrido','Ⅱ Pause tour'):t('▶ Recorrer fábrica','▶ Tour the factory');$('#tour').setAttribute('aria-pressed',String(tour));}
function manual(id){setTour(false);choose(id);}
$('#place-select').onchange=e=>manual(e.target.value);document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>manual(b.dataset.place));
$('#previous').onclick=()=>manual(places[Math.max(0,places.findIndex(p=>p.id===selected)-1)].id);$('#next').onclick=()=>manual(places[(places.findIndex(p=>p.id===selected)+1)%places.length].id);
$('#tour').onclick=()=>{setTour(!tour);if(tour&&selected==='campus')choose('design');};
function switchView(v){setTour(false);world?.setView(v);view=v;detail(v==='campus'?'campus':v==='layers'?'subfab':'lithography');syncView();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#enter').onclick=()=>switchView('cleanroom');
function syncPlaying(){ $('#motion').setAttribute('aria-pressed',String(playing));$('#motion').textContent=playing?t('Ⅱ Pausar actividad','Ⅱ Pause activity'):t('▶ Activar actividad','▶ Start activity');}
$('#motion').onclick=()=>{playing=!playing;syncPlaying();};
$('#follow').onclick=()=>{setTour(false);if(world?.following){world.select(places.find(p=>p.id==='transport'));}else{world?.follow();detail('transport');playing=true;syncPlaying();}syncView();};
$('#plus').onclick=()=>world?.zoomBy(1.25);$('#minus').onclick=()=>world?.zoomBy(.8);$('#fit').onclick=()=>{world?.fit();syncView();};$('#rotate-left').onclick=()=>world?.rotate(-Math.PI/6);$('#rotate-right').onclick=()=>world?.rotate(Math.PI/6);
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#scene').requestFullscreen();}catch{$('#activity-note').textContent=t('Este navegador no permite pantalla completa.','This browser does not allow fullscreen.');}};
$('#viewport').addEventListener('keydown',e=>{const keys={ArrowLeft:()=>world?.rotate(-.2),ArrowRight:()=>world?.rotate(.2),'+':()=>world?.zoomBy(1.2),'=':()=>world?.zoomBy(1.2),'-':()=>world?.zoomBy(.8),Home:()=>world?.fit()};if(keys[e.key]){e.preventDefault();keys[e.key]();}});
$('#viewport').addEventListener('pointerdown',()=>setTour(false));
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){playing=false;setTour(false);syncPlaying();}});
detail('campus');syncPlaying();setTour(false);

const labelButtons=new Map();for(const p of places.slice(1)){const b=document.createElement('button');b.className='place-label';b.textContent=p.name;b.onclick=()=>manual(p.id);$('#labels').append(b);labelButtons.set(p.id,b);}
function labels(){for(const p of places.slice(1)){const b=labelButtons.get(p.id);const allowed=view==='campus'?p.view==='campus':view==='layers'?['subfab','air'].includes(p.id):['lithography','deposition','etch','metrology','memory','packaging','test'].includes(p.id);const position=[...p.position];if(view==='layers'&&p.id==='subfab')position[1]=1;if(view==='layers'&&p.id==='air')position[1]=19;const q=world.project(position);b.hidden=!allowed||!q.visible;b.style.transform=`translate(${q.x}px,${q.y}px) translate(-50%,-125%)`;b.classList.toggle('selected',p.id===selected);}}
try{
 const {createWorld}=await import('./world.js');world=createWorld($('#viewport'),manual);world.setPlaces(places);$('#loading').hidden=true;
 world.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#loading').hidden=false;$('#loading').textContent=t('La vista 3D se ha interrumpido. Recarga para recuperarla; puedes seguir leyendo las zonas.','The 3D view was interrupted. Reload to restore it; area descriptions remain available.');});
 function frame(now){requestAnimationFrame(frame);if(document.hidden){lastFrame=now;return;}if(now-lastFrame<32)return;const dt=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(playing)motionTime+=dt;if(tour){tourElapsed+=dt;if(tourElapsed>=12){tourElapsed=0;const next=places.findIndex(p=>p.id===selected)+1;if(next>=places.length)setTour(false);else choose(places[next].id);}}world.render(motionTime,dt);labels();if($('#follow').getAttribute('aria-pressed')!==String(world.following))syncView();}
 requestAnimationFrame(frame);
}catch(error){console.error(error);$('#loading').innerHTML=`<div><strong>${t('La vista 3D no está disponible','The 3D view is unavailable')}</strong><p>${t('Puedes explorar las zonas en la lista y consultar la imagen oficial debajo.','You can explore areas in the list and view the official rendering below.')}</p><button onclick="location.reload()">${t('Reintentar','Retry')}</button></div>`;for(const id of ['motion','follow','plus','minus','fit','rotate-left','rotate-right','fullscreen','enter'])$('#'+id).disabled=true;}
