import {NotebookPlayer} from '../playback/player.js';
import {responsePlaylist} from './playlist.js';
import {DEFAULTS,contextWindow,createRun,softmax,nextCandidates,tokenize,trainStep,trainingStats} from './model.js';
import {llmFrameAt,phaseIndexInCycle} from './presentation.js';
import {createWorld} from './world.js';
import {VOICES} from './voices.js';
import {OPERATIONS,cueAt} from './flow.js';
const bound=(value,min,max)=>Math.max(min,Math.min(max,Number.isFinite(value)?value:min));
export function createLLMController({document:doc=globalThis.document,window:win=globalThis.window,Player=NotebookPlayer,AudioClass=globalThis.Audio,
 worldFactory=createWorld,world:providedWorld,requestFrame=globalThis.requestAnimationFrame,cancelFrame=globalThis.cancelAnimationFrame,
 now=()=>performance.now(),media=globalThis.matchMedia,storage=globalThis.localStorage}={}){
 const document=doc,es=doc.documentElement.lang==='es',lang=es?'es':'en',t=(a,b)=>es?a:b,$=id=>doc.getElementById(id),reduced=media('(prefers-reduced-motion: reduce)').matches;
 const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const number=(n,d=0)=>new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:d}).format(n);
 const visibleToken=x=>x==='<EOS>'?'⏹ EOS':x==='\n'?'↵':/^\s+$/.test(x)?'␠':x;
 let notebook,bookIndex=-1,options={...DEFAULTS},run=createRun(lang,options),selectedToken=0,queryIndex=contextWindow(run).tokens.length-1,
 world=providedWorld,voice=true,manualPhase=null,manualFlow=null,manualInput=null,manualBase=null,manualBasePhase=null,frame=llmFrameAt(run),trainingWeight=-1.2,trainingSteps=0,trainingPlaying=false,trainingClock=0,
 detailStamp='',last=now(),raf,ready=false,disposed=false,aligning=false,changingLanguage=false,restoredCamera=null,transcriptOpen=false;
 const listeners=[];const listen=(target,event,fn)=>{target.addEventListener(event,fn);listeners.push(()=>target.removeEventListener(event,fn));};
const phases=[
  [t('Tu pregunta','Your question'),t('La aplicación prepara la entrada','The application prepares the input'),t('El mensaje se combina con instrucciones y, si existen, mensajes anteriores. El modelo solo recibe el contexto que la aplicación le envía.','Your message is combined with instructions and, when present, previous messages. The model receives only the context supplied by the application.')],
  [t('Consultar','Retrieve'),t('¿Hace falta una fuente externa?','Is an external source needed?'),t('Una aplicación puede buscar documentos o llamar herramientas. El resultado vuelve como texto al contexto. Sin ese mecanismo, el modelo no abre internet por sí solo.','An application can retrieve documents or call tools. Their results return as context. Without that mechanism, the model does not open the internet by itself.')],
  ['Tokens',t('El texto se convierte en piezas','Text becomes pieces'),t('Cada pieza tiene un identificador. Puede ser una palabra, parte de ella o un signo. Aquí usamos un tokenizador pequeño y reversible; sus cortes no son los de un modelo comercial.','Each piece has an identifier. It can be a word, a word fragment or punctuation. Our small reversible tokenizer does not reproduce a commercial model’s vocabulary.')],
  [t('Vectores','Vectors'),t('De identificadores a números','From identifiers to numbers'),t('Una tabla aprendida convierte cada token en un vector. La posición también se codifica. Los seis valores que ves son de juguete; un modelo real usa representaciones mucho mayores.','A learned table maps each token to a vector. Position is encoded too. These six values are a toy example; real models use much larger representations.')],
  [t('Capas','Layers'),t('Atención + transformaciones','Attention + transformations'),t('La atención mezcla información de los tokens anteriores. Las capas también transforman los vectores con redes y conexiones residuales. Se repite muchas veces. Estas luces no son pensamientos ni una explicación fiel de una red real.','Attention mixes information from earlier tokens. Layers also transform vectors with networks and residual connections, repeatedly. These lights are not thoughts or a faithful explanation of a real network.')],
  [t('Probabilidades','Probabilities'),t('Puntuar posibles continuaciones','Score possible continuations'),t('El vector final se proyecta sobre el vocabulario. Softmax convierte los logits en probabilidades. Una probabilidad alta de texto no significa una probabilidad alta de que sea verdad.','The final vector is projected onto the vocabulary. Softmax turns logits into probabilities. High text probability is not the same as a high probability of truth.')],
  [t('Elegir','Choose'),t('Sale una pieza, no la frase entera','One piece comes out, not the whole sentence'),t('Se puede elegir el token más probable o muestrear una distribución. La temperatura cambia el reparto, no consulta hechos. En este laboratorio modifica la primera elección; el resto de la frase es una continuación guiada.','Decoding can choose the most likely token or sample a distribution. Temperature changes the distribution, not the facts. In this lab it affects the first choice; the rest is a guided continuation.')],
  [t('Repetir','Repeat'),t('Lo escrito vuelve al contexto','The output returns to context'),t('El siguiente paso usa la entrada y lo que ya se ha generado. Se repite hasta terminar. Las implementaciones suelen reutilizar cálculos mediante caché; no necesitan releer todo desde cero.','The next step uses the input and the generated text. This repeats until completion. Implementations commonly cache computations; they need not recompute everything from scratch.')]
];
document.title=t('LLMs — Dentro de una respuesta','LLMs — Inside an answer');
$('app').innerHTML=`<nav class="nav"><a href="../index.html">← Atlas</a><a href="../mente/index.html">${t('Mente','Mind')}</a><a href="../modelos/index.html">${t('Modelos','Models')}</a><a href="../museo/index.html">${t('Museo','Museum')}</a><span>NOTEBOOK 08 · LLMs</span><a class="cinema-link" href="./cinema.html">✦ ${t('Vista cinemática','Cinematic view')}</a><a href="../immersive/index.html?experience=llms">${t('Entrar en 3D ↗','Enter 3D ↗')}</a><div><a href="${es?'../../llms/index.html':'./index.html'}" lang="en">EN</a><a href="${es?'./index.html':'../es/llms/index.html'}" lang="es">ES</a></div></nav>
<header><div><span class="eyebrow">${t('ABRE LA CAJA NEGRA','OPEN THE BLACK BOX')}</span><h1>${t('De tu pregunta<br>a una respuesta.','From your question<br>to an answer.')}</h1></div><div class="hero-side"><p>${t('No hace falta llamarlos listos ni tontos. Sigue la información, cambia el contexto y mira dónde aciertan o pueden fallar.','No need to label them clever or stupid. Follow the information, change the context and see how they can succeed or fail.')}</p><a class="cinema-cta" href="./cinema.html"><b>✦ ${t('Nuevo · Vista cinemática','New · Cinematic view')}</b><span>${t('El mismo viaje en pantalla completa: la pregunta se rompe en tokens, se vuelve vectores, se mira a sí misma y sale como una apuesta.','The same journey full-screen: the question shatters into tokens, becomes vectors, looks at itself and comes out as a bet.')}</span></a></div></header>
<section class="setup"><div class="prompt-box"><label for="scenario">${t('01 · ELIGE UN EXPERIMENTO','01 · CHOOSE AN EXPERIMENT')}</label><select id="scenario"><option value="capital">${t('Una pregunta conocida','A familiar question')}</option><option value="bank">${t('La misma palabra, otro contexto','Same word, different context')}</option><option value="museum">${t('Un horario que necesita una fuente','Opening hours that need a source')}</option></select><blockquote id="question"></blockquote><small id="case-note"></small></div><div class="conditions"><label><input type="checkbox" id="context" checked> ${t('Incluir conversación anterior','Include previous conversation')}</label><p id="history-preview"></p><label><input type="checkbox" id="retrieval"> ${t('Consultar un documento','Retrieve a document')}</label><select id="source" aria-label="${t('Documento de ejemplo','Example document')}"><option value="current">${t('Ficha vigente','Current record')}</option><option value="archive">${t('Archivo antiguo','Old archive')}</option></select><small>${t('La búsqueda de este ejemplo usa fichas locales de un museo ficticio. No navega por internet.','This example retrieves local records for a fictional museum. It does not browse the internet.')}</small></div></section>
<p class="model-note">${t('SIMULACIÓN DIDÁCTICA · respuestas y logits preparados; no ejecuta un LLM real.','EDUCATIONAL SIMULATION · curated answers and logits; does not run a real LLM.')}</p>
<section class="metrics"><article><span>${t('Contexto disponible','Available context')}</span><strong id="context-count"></strong><small>${t('tokens de este tokenizador','tokens with this tokenizer')}</small></article><article><span>${t('Fuentes recuperadas','Retrieved sources')}</span><strong id="source-count">0</strong><small id="source-state"></small></article><article><span>${t('Respuesta generada','Generated output')}</span><strong id="output-count">0</strong><small>${t('tokens · uno tras otro','tokens · one after another')}</small></article><article><span>${t('Pesos modificados al responder','Weights changed while answering')}</span><strong>0</strong><small>${t('inferencia habitual · pesos fijos','standard inference · fixed weights')}</small></article></section>
<div class="transport"><button id="reset" type="button">↺ ${t("Reiniciar experimento","Reset experiment")}</button><span id="status" role="status"></span></div>
<div class="workbench"><div class="machine-panel"><div class="panel-label"><span>${t('EL RECORRIDO DE LA INFORMACIÓN','THE INFORMATION PATH')}</span><span>${t('Pulsa una etapa para inspeccionarla','Select a stage to inspect it')}</span></div><div class="rail" id="rail">${phases.map((p,i)=>`<button data-phase="${i}" aria-pressed="false"><b>${String(i+1).padStart(2,'0')}</b><span>${p[0]}</span></button>`).join('')}</div>

<section class="flow-dashboard" aria-label="${t('Operación activa','Active operation')}"><div class="flow-heading"><span class="signal-dot"></span><strong id="flow-title"></strong><span id="flow-counter"></span></div><div id="operation-rail" class="operation-rail" hidden>${OPERATIONS.map((op,i)=>`<button data-operation="${i}" aria-pressed="false"><b>${i+1}</b>${op.name[es?0:1]}</button>`).join('')}</div><code id="flow-formula"></code><p id="flow-caption"></p><div class="flow-legend"><span class="gold">● ${t('Consulta / activación activa','Active query / activation')}</span><span>▦ ${t('Filas = tokens · columnas = dimensiones','Rows = tokens · columns = dimensions')}</span></div></section>
<div class="machine" id="machine"><div class="scene-tools"><button id="view-reset">${t('Centrar vista','Reset view')}</button><button id="view-out" aria-label="${t('Alejar','Zoom out')}">−</button><button id="view-in" aria-label="${t('Acercar','Zoom in')}">＋</button></div><p class="scene-hint">${t('Arrastra para girar · pulsa bloques y celdas','Drag to orbit · select blocks and cells')}</p></div>
<div class="selection-readout" id="world-selection" role="status">${t('Un recorrido en 3D por el cálculo de cada token.','A 3D walkthrough of the computation for each token.')}</div>
<details class="paper-note"><summary>${t('¿Por qué se representa así?','Why represent it this way?')}</summary><p>${t('Los papers usan diagramas de bloques, matrices y flechas para expresar dependencias. Esta vista 3D desarrolla la atención de la figura 2 de Vaswani: Q/K/V → producto matricial → máscara → softmax → mezcla. La luz sigue vectores de activaciones; no representa un bit físico ni pensamientos. Las ramas Q/K/V pueden calcularse en paralelo.','Papers use block diagrams, matrices and arrows to express dependencies. This 3D view expands attention from Vaswani’s Figure 2: Q/K/V → matrix product → mask → softmax → mixture. Light follows activation vectors; it does not represent a physical bit or thoughts. Q/K/V branches can run in parallel.')}</p><p>${t('Aquí calculamos una cabeza con pesos sintéticos, posición aditiva y un bloque post-norm. No copiamos el encoder-decoder completo del paper de 2017: ilustramos un flujo causal de texto. Llama, por ejemplo, usa pre-normalización, SwiGLU y posiciones rotatorias. La ventana visible de 8 tokens se calcula por separado para poder inspeccionarla; no reproduce todo el contexto del modelo ni genera las respuestas preparadas.','We compute one head with synthetic weights, additive position and a post-norm block. We do not copy the full 2017 encoder-decoder: we illustrate a causal text flow. Llama, for example, uses pre-normalization, SwiGLU and rotary positions. The visible 8-token window is computed separately for inspection; it neither reproduces the model’s full context nor generates the curated answers.')}</p><a href="https://arxiv.org/abs/1706.03762" target="_blank" rel="noopener">Vaswani et al. · Fig. 1–2 / §3</a> · <a href="https://arxiv.org/abs/2302.13971" target="_blank" rel="noopener">LLaMA · §2.2</a></details>
<section class="output"><div><span>${t('LO QUE RECIBES','WHAT YOU RECEIVE')}</span><span id="loop-count"></span></div><p id="answer" aria-live="off"></p><small id="answer-note"></small></section></div>
<aside class="inspector"><span class="eyebrow" id="stage-counter"></span><h2 id="stage-title"></h2><p id="stage-description"></p><div id="stage-detail"></div></aside></div>
<section class="decoder"><div><span class="eyebrow">${t('CAMBIA UNA CONDICIÓN','CHANGE ONE CONDITION')}</span><h2>${t('Probable no significa verdadero.','Probable does not mean true.')}</h2><p>${t('Prueba el horario sin documento, con la ficha vigente y con una antigua. Después baja la temperatura: una respuesta equivocada puede volverse todavía más probable.','Try the opening hours without a document, with the current record and with an old one. Then lower the temperature: a wrong answer can become even more probable.')}</p><button id="try-museum">${t('Probar el caso del museo →','Try the museum example →')}</button></div><div class="decoder-controls"><label for="temperature">${t('Temperatura · primera elección','Temperature · first choice')} <output id="temperature-value"></output></label><input id="temperature" type="range" min="0" max="2" step=".1" value=".7"><label for="decoding">${t('Cómo se elige','How a token is chosen')}</label><select id="decoding"><option value="greedy">${t('El más probable','Most likely')}</option><option value="sample">${t('Muestrear según probabilidades','Sample from probabilities')}</option></select><button id="resample">${t('Otra semilla ↻','Another seed ↻')}</button><small>${t('Con elección máxima, la temperatura no cambia el ganador. La semilla afecta al muestreo, no a la verdad.','With greedy selection, temperature does not change the winner. The seed affects sampling, not truth.')}</small><div id="distribution"></div><p id="decoder-detail" class="decoder-detail"></p><p class="toy-label">${t('Softmax calculado de verdad sobre logits didácticos; no son mediciones de ningún LLM.','Actual softmax computed from teaching logits; not measurements from any LLM.')}</p></div></section>
<section class="training"><div><span class="eyebrow">${t('ANTES DE TU PREGUNTA','BEFORE YOUR QUESTION')}</span><h2>${t('Aprender y responder<br>son procesos distintos.','Learning and answering<br>are different processes.')}</h2><p>${t('Durante el entrenamiento se comparan predicciones con objetivos y se ajustan pesos para reducir el error. Al responder, normalmente se reutilizan esos pesos sin modificarlos. El contexto cambia la respuesta, no reentrena la red.','Training compares predictions with targets and adjusts weights to reduce error. Answering normally reuses those weights without updating them. Context changes the response without retraining the network.')}</p><small>${t('Hay sistemas con memoria externa, aprendizaje en línea o ajustes posteriores; son mecanismos adicionales.','External memory, online learning and later fine-tuning are additional mechanisms.')}</small></div><div class="training-lab"><div class="training-flow"><span>${t('Ejemplos','Examples')}</span><i>→</i><span class="weight-box">w = <b id="weight"></b></span><i>→</i><span>${t('Predicción','Prediction')}</span></div><div class="train-numbers"><div><span>${t('Probabilidad del objetivo','Target probability')}</span><strong id="train-prob"></strong></div><div><span>${t('Error (log loss)','Error (log loss)')}</span><strong id="train-loss"></strong></div></div><div class="learning-meter"><span id="train-meter"></span></div><button id="train-play">▶ ${t('Ver cómo aprende','Watch it learn')}</button><button id="train-reset">↺</button><p>${t('Mini ejemplo binario con un solo peso y descenso de gradiente real. No representa el tamaño ni la calidad de un LLM.','Tiny binary example with one weight and real gradient descent. Does not represent an LLM’s size or quality.')}</p><small id="train-steps"></small></div></section>
<section class="takeaways"><article><h3>${t('¿Busca una respuesta guardada?','Does it retrieve a saved answer?')}</h3><p>${t('Generalmente genera texto a partir de patrones en los pesos y del contexto. Puede memorizar fragmentos; eso no convierte los pesos en una biblioteca con fuentes accesibles.','It generally generates text from patterns in weights and context. It can memorize fragments; that does not make its weights a library of accessible sources.')}</p></article><article><h3>${t('¿Solo adivina palabras?','Is it just guessing words?')}</h3><p>${t('Predecir tokens es el objetivo básico. Para hacerlo bien puede aprender representaciones y cálculos complejos. Ese mecanismo, por sí solo, no demuestra ni ausencia de capacidad ni comprensión humana.','Token prediction is the basic objective. Doing it well can involve learned representations and complex computations. The mechanism alone proves neither an absence of capability nor human understanding.')}</p></article><article><h3>${t('¿Por qué puede equivocarse?','Why can it be wrong?')}</h3><p>${t('Una continuación plausible puede carecer de evidencia. También puede faltar contexto, sobrar ruido o fallar una herramienta. Fuentes, verificación y pruebas específicas ayudan a evaluar la respuesta.','A plausible continuation may lack evidence. Context can be missing, noisy or supplied by a failing tool. Sources, verification and task-specific tests help evaluate an answer.')}</p></article></section>
<details class="sources"><summary>${t('Qué simplifica esta simulación · fuentes','What this simulation simplifies · sources')}</summary><p>${t('Representamos un Transformer autoregresivo de texto. Las etapas, el número de capas, seis dimensiones y un vocabulario minúsculo son visualizaciones didácticas. Respuestas y logits son prefijados; el muestreo inicial, la tokenización reversible, softmax, la máscara causal y el mini entrenamiento sí se calculan aquí. La atención de juguete no produce las respuestas guionizadas. No es una lectura del razonamiento interno de ningún modelo.','We illustrate an autoregressive text Transformer. Stages, layer counts, six dimensions and a tiny vocabulary are teaching simplifications. Answers and logits are curated; initial sampling, reversible tokenization, softmax, causal masking and the small training example are computed here. Toy attention does not produce the scripted answers. This is not a reading of any model’s internal reasoning.')}</p><p>${t('Un producto real puede añadir sistemas de seguridad, contexto multimodal, búsqueda, herramientas y pasos internos adicionales. El entrenamiento suele incluir preentrenamiento y ajustes posteriores. No todas las arquitecturas o productos son iguales.','A real product may add safety systems, multimodal context, search, tools and additional internal steps. Training commonly includes pretraining and post-training. Architectures and products vary.')}</p><ul><li><a href="https://arxiv.org/abs/1706.03762" target="_blank" rel="noopener">Vaswani et al. · Attention Is All You Need</a></li><li><a href="https://arxiv.org/abs/2005.14165" target="_blank" rel="noopener">Brown et al. · Language Models are Few-Shot Learners</a></li><li><a href="https://huggingface.co/docs/transformers/main/tokenizer_summary" target="_blank" rel="noopener">Hugging Face · Tokenization</a></li><li><a href="https://huggingface.co/docs/transformers/main/llm_tutorial" target="_blank" rel="noopener">Hugging Face · Text generation</a></li><li><a href="https://arxiv.org/abs/2005.11401" target="_blank" rel="noopener">Lewis et al. · Retrieval-Augmented Generation</a></li><li><a href="https://www.anthropic.com/research/tracing-thoughts-language-model" target="_blank" rel="noopener">Anthropic · Tracing the thoughts of a large language model</a></li></ul></details><footer>Atlas · ${t('Experimenta. Compara. Comprueba.','Experiment. Compare. Verify.')}</footer>`;

function bars(pieces,logits){const ps=softmax(logits,options.temperature);return pieces.map((piece,i)=>`<div class="prob-row"><code>${esc(visibleToken(piece))}</code><div><i style="width:${ps[i]*100}%"></i></div><b>${number(ps[i]*100,1)} %</b></div>`).join('');}
function contextText(){return `<div class="context-card"><b>${t('Instrucción','Instruction')}</b><p>${t('Responde brevemente.','Answer briefly.')}</p></div>${run.data.history?`<div class="context-card history"><b>${t('Conversación anterior','Previous conversation')}</b><p>${esc(run.data.history)}</p></div>`:''}${run.data.source&&run.phase>=2?`<div class="context-card source"><b>${esc(run.data.source.title)}</b><p>${esc(run.data.source.text)}</p></div>`:''}<div class="context-card"><b>${t('Pregunta','Question')}</b><p>${esc(run.data.question)}</p></div>`;}
function detail(phase){
  const tokens=run.tokens;
  if(phase===0)return contextText();
  if(phase===1)return run.data.source?`<div class="document"><span>↳ ${t('DOCUMENTO LOCAL','LOCAL DOCUMENT')}</span><h3>${esc(run.data.source.title)}</h3><p>${esc(run.data.source.text)}</p><small>${t('Texto que se añade al contexto, no a los pesos.','Text added to context, not to model weights.')}</small></div>`:`<div class="empty-source">${t('Sin documento recuperado','No document retrieved')}</div><p class="small">${t('El recorrido continúa con la pregunta, las instrucciones y los patrones aprendidos. En el caso del museo, activa la consulta y compara.','The path continues with the question, instructions and learned patterns. Enable retrieval for the museum example and compare.')}</p>`;
  if(phase===2)return `<div class="token-list">${tokens.map((token,i)=>`<button data-token="${i}" aria-pressed="${i===selectedToken}" title="${esc(token)}">${esc(visibleToken(token))}<small>ID ${run.tokenIds[i]}</small></button>`).join('')}</div><p class="small">${t('Selecciona una pieza para inspeccionarla en Vectores. ␠ = espacio. Los IDs pertenecen solo al vocabulario didáctico de esta entrada.','Select a piece to inspect it under Vectors. ␠ = space. These IDs belong only to the teaching vocabulary for this input.')}</p>`;
  if(phase===3){const token=tokens[frame.selectedToken],values=frame.selectedVector;return `<div class="vector-example"><code>${esc(visibleToken(token))}</code><span>→</span><div>${values.map(v=>`<b style="--value:${Math.abs(v)*65}%;--sign:${v<0?'#eeaf9a':'#8daef4'}">${number(v,2)}</b>`).join('')}</div></div><p class="small">${t('Valores ilustrativos; no son etiquetas como «país» o «inteligente». El significado está distribuido y cambia al atravesar capas.','Illustrative values, not labels such as “country” or “intelligent”. Meaning is distributed and changes through layers.')}</p>`;}
  if(phase===4){const window=frame.window.tokens,q=frame.queryIndex,a={weights:frame.queryWeights};return `<div class="attention"><p class="small">${t('Elige qué token consulta. Solo puede atender a su pasado y a sí mismo.','Choose a querying token. It can attend only to earlier tokens and itself.')}</p><div class="query-tokens">${window.map((token,i)=>`<button data-query="${i}" aria-pressed="${i===q}">${esc(visibleToken(token))}</button>`).join('')}</div>${window.map((token,i)=>`<div class="attention-row ${i>q?'masked':''}"><code>${esc(visibleToken(token))}</code><span style="--strength:${a.weights[i]*100}%"></span><b>${i>q?'🔒':number(a.weights[i]*100,0)+'%'}</b></div>`).join('')}<small>${t('Ventana de hasta 8 piezas · una cabeza de atención de juguete. No mide importancia factual.','Window of up to 8 pieces · one toy attention head. Does not measure factual importance.')}</small></div>`;}
  if(phase===5||phase===6){const c=nextCandidates(run);return `<div class="candidate-box">${bars(c.pieces,c.logits)}</div><p class="small">${run.outputTokens?t('Continuación guiada del ejemplo. El siguiente token se ha fijado para completar la demostración.','Guided continuation. The next token is fixed to complete the demonstration.'):t('Opciones prefijadas para comparar el efecto de la temperatura y el muestreo.','Curated options for comparing temperature and sampling.')}</p><div class="formula">pᵢ = exp(logitᵢ / T) / Σ exp(logitⱼ / T)</div><small>${t('Con T = 0 usamos elección máxima.','At T = 0 we use greedy selection.')}</small>`;}
  return `<div class="feedback-card"><span>${t('CONTEXTO ORIGINAL','ORIGINAL CONTEXT')}</span><b>＋</b><code>${esc(run.generated.join(''))||'…'}</code><b>↻</b><span>${run.done?t('EOS · respuesta terminada','EOS · answer complete'):t('Vuelve a las capas para el siguiente token','Back through the layers for the next token')}</span></div><p class="small">${t('El contenido generado se reutiliza como contexto. Una equivocación también puede influir en lo siguiente.','Generated content becomes context. A mistake can also influence what comes next.')}</p>`;
}

 function currentFlow(){const clip=notebook?.current;if(manualFlow)return manualFlow;if(!clip)return {index:0,progress:0};return run.phase===4?cueAt(clip.cues,clip.local):{index:0,progress:clip.progress};}
 function rebuild(){const flow=currentFlow(),p=notebook?.current?.progress??0,input=manualPhase===null?run:manualBase===run&&manualBasePhase===manualPhase?manualInput:(manualBase=run,manualBasePhase=manualPhase,manualInput={...run,phase:manualPhase});frame=llmFrameAt(input,{progress:p,operationIndex:flow.index,operationProgress:flow.progress,queryIndex,selectedToken});queryIndex=frame.queryIndex;selectedToken=frame.selectedToken;}
 function applyVoice(){if(notebook?.clock.audio)notebook.clock.audio.muted=!voice;}
 function save(){notebook?.save();}
 function render(){if(disposed)return;rebuild();const phase=frame.phase,r=frame.run;
  $('question').textContent=r.data.question;$('case-note').textContent=r.data.name;$('history-preview').textContent=r.data.history||t('Sin conversación adicional en este ejemplo.','No extra conversation in this example.');
  $('context').disabled=options.scenario!=='bank';$('retrieval').disabled=options.scenario!=='museum';$('source').disabled=options.scenario!=='museum'||!options.retrieval;$('context').checked=options.scenario==='bank'&&options.context;$('retrieval').checked=options.scenario==='museum'&&options.retrieval;
  $('context-count').textContent=number(r.tokens.length+r.generated.length);$('source-count').textContent=r.data.source?'1':'0';$('source-state').textContent=r.data.source?t('documento local de ejemplo','local example document'):t('sin conexión externa','no external connection');$('output-count').textContent=number(r.generated.length);
  $('stage-counter').textContent=`${String(phase+1).padStart(2,'0')} / 08 · ${phases[phase][0]}`;$('stage-title').textContent=phases[phase][1];$('stage-description').textContent=phases[phase][2];
  $('status').textContent=manualPhase!==null||manualFlow?t('Inspección manual · respuesta conservada · voz en pausa','Manual inspection · output preserved · narration paused'):r.done?t('EOS · respuesta terminada','EOS · answer complete'):t('Contexto y escena siguen la narración','Context and scene follow narration');
  doc.querySelectorAll('#rail [data-phase]').forEach(b=>{b.setAttribute('aria-pressed',String(+b.dataset.phase===phase));b.classList.toggle('visited',+b.dataset.phase<=phase);});$('machine').dataset.phase=phase;$('machine').classList.toggle('running',!!notebook?.running&&!reduced);
  $('answer').textContent=r.generated.join('')||t('La respuesta aparecerá aquí, pieza a pieza…','The answer will appear here, piece by piece…');$('answer').classList.toggle('has-output',r.generated.length>0);$('loop-count').textContent=r.loops?`${number(r.loops)} ${t('ciclos','cycles')}`:'';$('answer-note').textContent=r.generated.length?r.data.evidence:t('Respuestas preparadas: el bloque de atención calculado se inspecciona por separado.','Curated responses: the calculated attention block is inspected separately.');
  const detailKey=JSON.stringify([phase,r.generated.length,selectedToken,queryIndex,options]);if(detailKey!==detailStamp){detailStamp=detailKey;$('stage-detail').innerHTML=detail(phase);
  for(const b of doc.querySelectorAll('[data-token]'))b.onclick=()=>{notebook.pause();selectedToken=+b.dataset.token;inspectPhase(3);};
  for(const b of doc.querySelectorAll('[data-query]'))b.onclick=()=>{notebook.pause();queryIndex=+b.dataset.query;manualFlow={...currentFlow()};render();save();};
  }
  $('distribution').innerHTML=bars(frame.decoder.pieces,frame.decoder.logits);$('decoder-detail').textContent=frame.decoder.scripted?t('Continuación guiada: el siguiente token está fijado; no se vuelve a muestrear.','Scripted continuation: the next token is fixed; no further sampling.'):frame.decoder.selectionVisible?(frame.decoder.mode==='sample'?`u=${number(frame.decoder.randomValue,6)} · `:t('Máximo · ','Greedy · '))+t('token elegido: ','chosen token: ')+visibleToken(frame.decoder.choice):frame.decoder.mode==='sample'?t('La semilla fija una extracción uniforme; se revela al terminar Elegir.','The seed fixes a uniform draw; it is revealed when Choose ends.'):t('La elección máxima no cambia con la temperatura.','Greedy selection does not change with temperature.');$('temperature-value').textContent=number(options.temperature,1);$('resample').disabled=options.decoding!=='sample';
  const layers=phase===4,op=OPERATIONS[frame.flow.index];$('operation-rail').hidden=!layers;$('flow-title').textContent=layers?op.name[es?0:1]:phases[phase][1];$('flow-counter').textContent=layers?`${frame.flow.index+1} / 5`:t('Una cabeza · un bloque calculado','One head · one calculated block');$('flow-formula').textContent=layers?op.formula:['messages → context','context + local document','text → token IDs','X = E[token ID] + P','', 'curated logits → softmax(logits / T)','p → decode → one token','context + token → next step'][phase];
  $('flow-caption').textContent=(layers?op.text[es?0:1]:t('El progreso sigue el audio o la inspección pausada.','Progress follows narration or paused inspection.'))+' '+(layers?`N=${frame.window.tokens.length} · X ${frame.shapes.X.join('×')} · Q/K/V ${frame.shapes.Q.join('×')} · A ${frame.shapes.A.join('×')}`:frame.decoder.scripted?t('Continuación guiada; no hay otro muestreo.','Scripted continuation; no additional sampling.') :frame.decoder.mode==='sample'?t('Primera elección muestreada.','Initial choice is sampled.'):t('Primera elección máxima.','Initial choice is greedy.'));
  doc.querySelectorAll('[data-operation]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.operation===frame.flow.index)));world?.updateFrame(frame);applyVoice();
 }
 function inspectPhase(phase){if(disposed)return;notebook.pause();manualFlow=null;const index=phaseIndexInCycle(notebook.clock.timeline,notebook.current.index,phase);if(index===null){manualPhase=phase;render();save();return;}manualPhase=null;notebook.stage(index,false);render();save();}
 function selectOperation(index){if(frame.phase!==4)return;notebook.pause();const c=notebook.current,cue=c.snapshot.phase===4?c.cues?.[index]:null;manualFlow={index,progress:0};if(cue){aligning=true;try{notebook.seek(c.start+cue.start,false);}finally{aligning=false;}}render();save();}
 function validated(saved){const next={...DEFAULTS};if(!saved||typeof saved!=='object')return next;for(const k of ['scenario','source','decoding'])if({scenario:['capital','bank','museum'],source:['current','archive'],decoding:['greedy','sample']}[k].includes(saved[k]))next[k]=saved[k];for(const k of ['context','retrieval'])if(typeof saved[k]==='boolean')next[k]=saved[k];if(Number.isFinite(saved.temperature))next.temperature=bound(saved.temperature,0,2);if(Number.isInteger(saved.seed))next.seed=saved.seed>>>0;return next;}
 function capture(){return {version:1,options:{...options},queryIndex,selectedToken,manualPhase,manualFlow:manualFlow?{...manualFlow}:null,camera:world?.getViewState(),voice,transcript:notebook?.root.querySelector('.ap-transcript').hidden===false,training:{weight:trainingWeight,steps:trainingSteps}};}
 function restore(saved){if(!saved||typeof saved!=='object')return;options=validated(saved.options);run=createRun(lang,options);queryIndex=Math.floor(bound(saved.queryIndex,0,7));selectedToken=Math.floor(bound(saved.selectedToken,0,run.tokens.length-1));manualPhase=Number.isInteger(saved.manualPhase)?bound(saved.manualPhase,0,7):null;manualFlow=saved.manualFlow&&Number.isInteger(saved.manualFlow.index)?{index:bound(saved.manualFlow.index,0,4),progress:bound(saved.manualFlow.progress,0,1)}:null;voice=saved.voice!==false;restoredCamera=saved.camera;transcriptOpen=saved.transcript===true;if(saved.training){trainingWeight=bound(saved.training.weight,-20,20);trainingSteps=Math.floor(bound(saved.training.steps,0,80));}for(const k of ['scenario','source','decoding'])$(k).value=options[k];$('temperature').value=options.temperature;}
 function sync(s){if(disposed||!s)return;if(bookIndex!==s.index||s.reason==='seek'){bookIndex=s.index;run=JSON.parse(JSON.stringify(s.snapshot));if(ready&&!aligning&&!changingLanguage){manualPhase=null;manualFlow=null;}}run.playing=s.running;render();}
 try{world ||= worldFactory($('machine'),{language:lang,onSelect(info){notebook?.pause();if(info.kind==='token')selectedToken=info.index;if(info.kind==='attention')queryIndex=info.index;$('world-selection').textContent=info.text;manualFlow={...currentFlow()};render();save();},onViewChange:()=>save()});}catch{$('machine').insertAdjacentHTML?.('afterbegin',`<p class="world-fallback">${t('3D no disponible: cifras, texto y narración siguen disponibles.','3D unavailable: figures, transcript and narration remain available.')}</p>`);}
 function VoiceAudio(src){const a=new AudioClass(src);a.muted=!voice;return a;}
 notebook=new Player({id:'llms',AudioClass:VoiceAudio,getClips:language=>responsePlaylist(lang,options,VOICES[language],phases.map(p=>p[1])),capture,restore,onSync:sync});
 const voiceLabel=doc.createElement('label');voiceLabel.className='ap-voice';voiceLabel.innerHTML=`<input id="voice-enabled" type="checkbox" ${voice?'checked':''}> ${t('Voz','Voice')}`;notebook.root.querySelector('.ap-bar').append(voiceLabel);$('voice-enabled').onchange=()=>{voice=$('voice-enabled').checked;applyVoice();save();};
 const oldSeek=notebook.seek.bind(notebook);notebook.seek=(seconds,play=notebook.wanted)=>{if(!aligning&&!changingLanguage){manualPhase=null;manualFlow=null;}oldSeek(seconds,play);applyVoice();};
 const oldToggle=notebook.toggle.bind(notebook);notebook.toggle=()=>{manualPhase=null;manualFlow=null;oldToggle();render();save();};
 const oldLanguage=notebook.changeLanguage.bind(notebook);notebook.changeLanguage=language=>{changingLanguage=true;const held={manualPhase,manualFlow,queryIndex,selectedToken},flow=notebook.current.snapshot.phase===4?currentFlow():null,active=notebook.wanted;try{oldLanguage(language);if(flow){const clip=notebook.current,cue=clip.cues?.[flow.index];if(cue)oldSeek(clip.start+cue.start+flow.progress*(cue.end-cue.start),active);}({manualPhase,manualFlow,queryIndex,selectedToken}=held);}finally{changingLanguage=false;}render();save();};
 ready=true;if(restoredCamera)world?.restoreViewState(restoredCamera);notebook.root.querySelector('.ap-transcript').hidden=!transcriptOpen;notebook.el('text').setAttribute('aria-expanded',String(transcriptOpen));if(manualPhase!==null||manualFlow)notebook.pause();
 function restart(){notebook.pause();options=validated(options);run=createRun(lang,options);selectedToken=0;queryIndex=contextWindow(run).tokens.length-1;manualPhase=null;manualFlow=null;bookIndex=-1;notebook.rebuild();render();save();}
 for(const k of ['scenario','source','decoding'])$(k).onchange=e=>{options[k]=e.target.value;restart();};for(const k of ['context','retrieval'])$(k).onchange=e=>{options[k]=e.target.checked;restart();};$('temperature').oninput=e=>{options.temperature=Number(e.target.value);restart();};$('resample').onclick=()=>{options.seed=(options.seed+977)>>>0;restart();};$('try-museum').onclick=()=>{options.scenario='museum';options.retrieval=false;$('scenario').value='museum';restart();};$('reset').onclick=restart;
 for(const b of doc.querySelectorAll('#rail [data-phase]'))b.onclick=()=>inspectPhase(+b.dataset.phase);for(const b of doc.querySelectorAll('[data-operation]'))b.onclick=()=>selectOperation(+b.dataset.operation);
 $('view-reset').onclick=()=>{world?.reset();save();};$('view-in').onclick=()=>{world?.zoom(.85);save();};$('view-out').onclick=()=>{world?.zoom(1.15);save();};
 function renderTraining(){const s=trainingStats(trainingWeight);$('weight').textContent=number(trainingWeight,2);$('train-prob').textContent=number(s.probability*100,1)+' %';$('train-loss').textContent=number(s.loss,3);$('train-meter').style.width=s.probability*100+'%';$('train-steps').textContent=number(trainingSteps)+' '+t('actualizaciones del peso','weight updates');$('train-play').textContent=trainingPlaying?'Ⅱ '+t('Pausar','Pause'):'▶ '+t('Ver cómo aprende','Watch it learn');}
 $('train-play').onclick=()=>{trainingPlaying=!trainingPlaying;renderTraining();save();};$('train-reset').onclick=()=>{trainingPlaying=false;trainingWeight=-1.2;trainingSteps=0;renderTraining();save();};
 listen(doc,'visibilitychange',()=>{last=now();if(doc.hidden){trainingPlaying=false;renderTraining();save();}});
 function tick(current){if(disposed)return;const dt=bound((current-last)/1000,0,.1);last=current;if(!doc.hidden){rebuild();world?.renderFrame(frame,{dt,live:!!notebook.running,reduced});if(trainingPlaying){trainingClock+=dt;if(trainingClock>.45){trainingClock=0;trainingWeight=trainStep(trainingWeight);trainingSteps++;if(trainingSteps>=80)trainingPlaying=false;renderTraining();save();}}}raf=requestFrame(tick);}
 function dispose(){if(disposed)return;save();disposed=true;cancelFrame(raf);listeners.forEach(remove=>remove());notebook.dispose();world?.dispose();}
 listen(win,'pagehide',event=>{save();if(!event?.persisted)dispose();});render();renderTraining();raf=requestFrame(tick);
 return {player:notebook,world,inspectPhase,selectOperation,capture,dispose,get state(){return {options:{...options},run,queryIndex,selectedToken,manualPhase,manualFlow,voice,trainingWeight,trainingSteps,frame};}};
}
if(typeof document!=='undefined'&&document.getElementById('app')&&!globalThis.__LLM_CONTROLLER_TEST__)createLLMController();
