import * as THREE from '../vendor/three.module.js';
import {createStageKit,createAtmosphere,createPost,pointScaleFor,adaptiveScale} from './stage.js';
import {llmFrameAt} from './presentation.js';
const V=a=>new THREE.Vector3(...a),ANGLES=[[-.1,.12],[.12,.15],[0,.1],[0,.06],[0,.06],[-.08,.12],[0,.28],[0,.18]],clamp=THREE.MathUtils.clamp;
const corners=box=>[0,1].flatMap(x=>[0,1].flatMap(y=>[0,1].map(z=>V([x?box.max.x:box.min.x,y?box.max.y:box.min.y,z?box.max.z:box.min.z]))));
export function stageBounds(set){const bounds=new THREE.Box3();set.updateMatrixWorld(true);set.traverse(object=>{if(object.isSprite){const p=object.getWorldPosition(new THREE.Vector3()),scale=object.getWorldScale(new THREE.Vector3()),center=object.center;bounds.expandByPoint(p.clone().add(V([-center.x*scale.x,-center.y*scale.y,0])));bounds.expandByPoint(p.clone().add(V([(1-center.x)*scale.x,(1-center.y)*scale.y,0])));}else if(object.geometry){if(object.isInstancedMesh){object.computeBoundingBox();bounds.union(object.boundingBox.clone().applyMatrix4(object.matrixWorld));}else{object.geometry.computeBoundingBox();bounds.union(object.geometry.boundingBox.clone().applyMatrix4(object.matrixWorld));}}});return bounds;}
export function llmCameraAt(bounds,{aspect=1.5,phase=0,yaw=0,pitch=0,zoom=1}={}){const target=bounds.getCenter(new THREE.Vector3()),angle=ANGLES[phase]||ANGLES[0],azimuth=angle[0]+yaw,elevation=clamp(angle[1]+pitch,-.05,1.2),out=V([Math.sin(azimuth)*Math.cos(elevation),Math.sin(elevation),Math.cos(azimuth)*Math.cos(elevation)]),right=new THREE.Vector3().crossVectors(V([0,1,0]),out).normalize(),up=new THREE.Vector3().crossVectors(out,right).normalize(),fov=aspect<.9?58:44,tan=Math.tan(fov*Math.PI/360);let distance=8;for(const point of corners(bounds)){const p=point.sub(target);distance=Math.max(distance,p.dot(out)+Math.max(Math.abs(p.dot(right))/(tan*Math.max(.25,aspect)*.82),Math.abs(p.dot(up))/(tan*.8))+.3);}distance*=clamp(zoom,.55,1.8);return {position:target.clone().addScaledVector(out,distance).toArray(),target:target.toArray(),fov,near:.1,far:Math.max(260,distance*3),distance};}

export function createWorld(host,{language='es',onSelect=()=>{},onViewChange=()=>{},rendererFactory=()=>new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}),postFactory=createPost,ResizeObserverClass=globalThis.ResizeObserver}={}){
 const es=language==='es',t=(a,b)=>es?a:b,reduce=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false,renderer=rendererFactory(),canvas=renderer.domElement;let dpr=Math.min(globalThis.devicePixelRatio||1,1.75);renderer.setPixelRatio(dpr);host.prepend(canvas);canvas.tabIndex=0;canvas.setAttribute('aria-label',t('Modelo LLM. Arrastra para orbitar; rueda o pellizca para acercar. Selecciona una celda para leer su valor.','LLM model. Drag to orbit; scroll or pinch to zoom. Select a cell to read its value.'));
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(44,1,.1,260),pointScale={value:400};scene.fog=new THREE.FogExp2(0x050b16,.012);scene.add(new THREE.HemisphereLight(0x9fc3ff,0x070b14,1.3));const key=new THREE.DirectionalLight(0xf1f5ff,2);key.position.set(4,9,8);scene.add(key);const rim=new THREE.DirectionalLight(0x4f7dff,2);rim.position.set(-8,5,-9);scene.add(rim);const warm=new THREE.PointLight(0xffb45a,0,14,1.6);scene.add(warm);
 const post=postFactory(renderer,scene,camera),atmosphere=createAtmosphere(scene,{pointScale,dust:320}),kit=createStageKit({es,reduce,pointScale,light:warm}),views=Array.from({length:8},()=>({yaw:0,pitch:0,zoom:1})),pointers=new Map(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let frame=null,active=null,signature='',phase=0,width=1,height=1,disposed=false,decorTime=0,pinch=0;
 const quality=adaptiveScale(dpr,{min:.7,apply(scale){dpr=scale;renderer.setPixelRatio(dpr);resize();}});
 function getViewState(){return {version:1,phase,views:views.map(v=>({...v})),...views[phase],position:camera.position.toArray(),target:active?.userData.bounds.getCenter(new THREE.Vector3()).toArray()||[0,2,0]};}
 function restoreViewState(state){if(!state||!Number.isInteger(state.phase)||state.phase<0||state.phase>7)return false;for(let i=0;i<8;i++){const v=state.views?.[i]||(i===state.phase?state:null);if(v)views[i]={yaw:Number.isFinite(v.yaw)?v.yaw:0,pitch:clamp(Number.isFinite(v.pitch)?v.pitch:0,-.45,1),zoom:clamp(Number.isFinite(v.zoom)?v.zoom:1,.55,1.8)};}return true;}
 const changed=()=>onViewChange(getViewState());
 function reset(){views[phase]={yaw:0,pitch:0,zoom:1};changed();}
 function updateFrame(next){if(disposed)return;frame=next;phase=next.phase;const key=JSON.stringify([phase,next.run.prompt,next.run.generated,next.run.done,next.run.options.temperature,next.run.options.decoding,next.run.seed,next.selectedToken,next.queryIndex,next.flow.index,width/height<.9||width<560]);if(key!==signature){signature=key;if(active)kit.destroy(active);active=kit.buildFrame(next,{aspect:width/height,width});scene.add(active);kit.tick(active,{sig:1,live:true});active.userData.bounds=stageBounds(active);kit.hovered=null;}active.userData.frame=next;kit.tick(active,{sig:phase===4?next.flow.progress:next.progress,live:true});scene.updateMatrixWorld(true);}
 function applyCamera(){if(!active)return;const pose=llmCameraAt(active.userData.bounds,{aspect:width/height,phase,...views[phase]});camera.position.set(...pose.position);camera.fov=pose.fov;camera.far=pose.far;camera.lookAt(V(pose.target));camera.updateProjectionMatrix();camera.updateMatrixWorld(true);pointScale.value=pointScaleFor(height,dpr,camera.fov);}
 function renderFrame(next,{dt=0}={}){if(disposed)return;updateFrame(next);decorTime+=Math.max(0,Math.min(.05,dt));atmosphere.update(decorTime);applyCamera();post.render(dt);quality.frame(dt);}
 function update(run,p,selectedToken=0,queryIndex=7){updateFrame(llmFrameAt({...run,phase:p},{progress:frame?.progress||0,operationIndex:frame?.flow.index||0,queryIndex,selectedToken}));}
 function render(dt=0,flow={index:0,progress:0}){if(frame)renderFrame(llmFrameAt(frame.run,{progress:phase===4?frame.progress:flow.progress,operationIndex:flow.index,operationProgress:flow.progress,queryIndex:frame.queryIndex,selectedToken:frame.selectedToken}),{dt});}
 function resize(){if(disposed)return;width=Math.max(1,host.clientWidth);height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false);post.setSize(width,height,dpr);camera.aspect=width/height;if(frame){updateFrame(frame);applyCamera();}}const observer=new ResizeObserverClass(resize);observer.observe(host);resize();
 const visible=o=>{for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;};
 function pick(e){if(!active)return null;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(active.userData.hits.filter(visible),false)[0];return hit?{mesh:hit.object,id:hit.instanceId,info:kit.pickInfo(hit)}:null;}
 const down=e=>{if(e.button!==undefined&&e.button!==0)return;canvas.focus({preventScroll:true});pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false});canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch=Math.hypot(a.x-b.x,a.y-b.y);}};
 const move=e=>{const previous=pointers.get(e.pointerId);if(!previous){const hit=pick(e);kit.hovered=hit;canvas.style.cursor=hit?'pointer':'grab';return;}const v=views[phase],dx=e.clientX-previous.x,dy=e.clientY-previous.y;previous.moved||=Math.hypot(e.clientX-previous.sx,e.clientY-previous.sy)>5;previous.x=e.clientX;previous.y=e.clientY;if(pointers.size===1){v.yaw-=dx*.006;v.pitch=clamp(v.pitch+dy*.005,-.45,1);}else{const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(pinch>0&&distance>0)v.zoom=clamp(v.zoom*pinch/distance,.55,1.8);pinch=distance;for(const p of pointers.values())p.moved=true;}changed();};
 const up=e=>{const p=pointers.get(e.pointerId);pointers.delete(e.pointerId);pinch=0;if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(p&&!p.moved){const hit=pick(e);if(hit?.info)onSelect(hit.info);}};
 const cancel=e=>{pointers.delete(e.pointerId);pinch=0;},leave=()=>{kit.hovered=null;},wheel=e=>{e.preventDefault();views[phase].zoom=clamp(views[phase].zoom*Math.exp(e.deltaY*.001),.55,1.8);changed();};
 const keydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','+','-','='].includes(e.key))return;e.preventDefault();if(e.key==='Home'){reset();return;}const v=views[phase];if(e.key==='ArrowLeft')v.yaw-=.12;if(e.key==='ArrowRight')v.yaw+=.12;if(e.key==='ArrowUp')v.pitch=Math.min(1,v.pitch+.08);if(e.key==='ArrowDown')v.pitch=Math.max(-.45,v.pitch-.08);if(e.key==='+'||e.key==='=')v.zoom=Math.max(.55,v.zoom*.9);if(e.key==='-')v.zoom=Math.min(1.8,v.zoom*1.1);changed();};
 const lost=e=>{e.preventDefault();onSelect({kind:'error',text:t('Se perdió el contexto 3D. Recarga la página; el texto y el audio siguen disponibles.','3D context lost. Reload the page; text and audio remain available.')});};
 const events={pointerdown:down,pointermove:move,pointerup:up,pointercancel:cancel,lostpointercapture:cancel,pointerleave:leave,wheel,keydown,webglcontextlost:lost};for(const [name,callback] of Object.entries(events))canvas.addEventListener(name,callback,name==='wheel'?{passive:false}:undefined);
 function inspect(){return {phase,flow:frame?.flow,signals:frame?.signals,decoder:frame?.decoder,frame,camera:getViewState(),bounds:active?{min:active.userData.bounds.min.toArray(),max:active.userData.bounds.max.toArray()}:null,portrait:active?.userData.portrait,tensors:active?.userData.tensors.map(m=>m.userData.tensor),paths:active?.userData.paths.map(p=>({head:p.head,arrived:p.arrived,weight:p.weight,span:p.span})),navigation:{mode:'orbit',walking:false}};}
 return {canvas,update,render,updateFrame,renderFrame,getViewState,restoreViewState,inspect,reset,zoom(delta){views[phase].zoom=clamp(views[phase].zoom*delta,.55,1.8);changed();},dispose(){disposed=true;observer.disconnect();for(const [name,callback] of Object.entries(events))canvas.removeEventListener(name,callback);pointers.clear();if(active)kit.destroy(active);kit.dispose();atmosphere.dispose();post.dispose();renderer.dispose();canvas.remove();}};
}
