import * as THREE from './vendor/three.module.js';
import {roadRoute,routePoint,districtContactTargets} from './world.js';

export const INPUTS=[[],[0],[1],[1],[1],[1],[2,3,4,5],[6],[7]];
export const RESOURCES=['Ore','Metals','Structures','Actuators','Batteries','Electronics','Kits','Awaiting testing'];
export function processStatus(frame,next,i){
  const rate=Number(frame.flow[i])||0,cap=frame.worked?.cap?.[i]??Math.floor(frame.capacity[i]);
  if(frame.capacity[i]<=0)return {code:'rest',label:'No available shift',color:0x7995b4,rate};
  if(rate===0&&cap>0)return {code:'waiting',label:'Waiting for materials',color:0xffaa61,rate};
  if(rate<cap)return {code:'supply',label:'Insufficient supply',color:0xffaa61,rate};
  if(frame.projects[i])return {code:'building',label:'Expansion under way',color:0xffc96c,rate};
  if(frame.capacity[i]>=frame.hardware[i])return {code:'full',label:'Machinery at capacity',color:0xddbc78,rate};
  return {code:'working',label:'In production',color:0xa7e3cb,rate};
}

export function createActivity(scene,world,industries){
  const {box,cyl,palette}=world,es=world.es!==false,root=new THREE.Group();scene.add(root);
  const rings=[],beacons=[],stocks=[],stockGroups=[],stockLabels=[],assembly=[],scanners=[],testBodies=[],taskSamples=[],routes=[];let disposed=false,summary=null;
  const resources=[],owned=new Set(),own=r=>{if(r&&!world.owns?.(r)&&!owned.has(r)){owned.add(r);resources.push(r);}return r;};
  function label(group,x,y,z,width,text){const canvas=document.createElement('canvas');canvas.width=768;canvas.height=128;const ctx=canvas.getContext('2d'),texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;const material=own(new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,toneMapped:false})),mesh=new THREE.Mesh(own(new THREE.PlaneGeometry(width,.38)),material);mesh.position.set(x,y,z);mesh.userData={isLabel:true,text:'',countsAsObject:false};group.add(mesh);const set=value=>{if(mesh.userData.text===value)return;mesh.userData.text=value;ctx.clearRect?.(0,0,768,128);ctx.fillStyle='#123b3f';ctx.fillRect(0,0,768,128);ctx.fillStyle='#e4fff5';ctx.font='600 40px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(value,384,64,740);texture.needsUpdate=true;};set(text);return {mesh,set};}
  const materialColors=[palette.yellow,palette.wall,palette.blue,palette.orange,palette.mint,palette.white,palette.orange,palette.white];
  industries.forEach((s,i)=>{
    const material=own(new THREE.MeshBasicMaterial({color:0x99ddc6,transparent:true,opacity:.3,depthWrite:false})),ring=new THREE.LineLoop(own(new THREE.BufferGeometry().setFromPoints([[-8.2,-7.2],[8.2,-7.2],[8.2,7.2],[-8.2,7.2]].map(([x,z])=>new THREE.Vector3(s.x+x,.36,s.z+z)))),material);root.add(ring);rings.push(ring);
    const beaconMat=own(new THREE.MeshStandardMaterial({color:0xa8e4ca,emissive:0x80dcb7,emissiveIntensity:1.2}));cyl(root,s.x+7.5,1,s.z+6.1,.09,1.4,palette.dark,8);beacons.push(cyl(root,s.x+7.5,1.85,s.z+6.1,.18,.35,beaconMat,8));
    if(i<8){const g=new THREE.Group();g.position.set(s.x-6.9,0,s.z-3.7);g.userData={sampleOf:'inventory-'+i,countsAsObject:false};root.add(g);const crates=[];for(let j=0;j<12;j++){const o=box(g,(j%2)*.8,.65+Math.floor(j/4)*.7,Math.floor(j%4/2)*.85,.66,.62,.68,materialColors[i]);o.visible=false;crates.push(o);}stocks.push(crates);stockGroups.push(g);stockLabels.push(label(g,.42,2.8,1.3,4.3,es?'Existencias · muestras':'Inventory · samples'));}
    // Each ordinary operator has a visible task surface; assembly operators
    // use a handheld controller while the fixed gripper touches the chassis.
    for(let slot=0;slot<s.humans;slot++){if(i===7)continue;const anchor=districtContactTargets(industries,i,slot),g=new THREE.Group();g.userData={site:i,slot,countsAsObject:false,scope:anchor.scope};root.add(g);const materials=[];for(const target of anchor.targets){box(g,target[0],target[1]-.65,target[2],.10,.82,.10,palette.wall);box(g,target[0],target[1]-1.03,target[2],.34,.08,.32,palette.dark);box(g,target[0],target[1]-.14,target[2],.30,.20,.28,palette.dark);const sample=box(g,target[0],target[1]-.04,target[2],.26,.08,.25,materialColors[Math.min(7,i)]);sample.userData={contactPoint:[...target],countsAsObject:false,representation:'completed-operation sample'};materials.push(sample);}taskSamples.push({group:g,site:i,slot,targets:anchor.targets,materials});}
  });
  // Fixed-size components are progressively installed; no body grows in scale.
  for(let j=0;j<5;j++){const g=new THREE.Group();g.position.set(industries[7].x-4.8+j*2.4,1.73,industries[7].z-.3);g.rotation.x=Math.PI/2;g.userData={countsAsObject:false,representation:'assembly example from aggregate rate'};root.add(g);
    const chassis=box(g,0,.25,0,.5,.7,.32,palette.wall),battery=box(g,0,.10,-.21,.30,.18,.10,palette.mint),board=box(g,0,.48,-.22,.25,.20,.04,palette.blue),head=new THREE.Group();g.add(head);cyl(head,0,.84,0,.24,.35,palette.white);box(head,0,.86,-.24,.36,.13,.05,palette.dark).userData.role='visor';const limbs=[];for(const side of[-1,1]){limbs.push(box(g,side*.34,.25,0,.13,.65,.16,palette.wall));limbs.push(box(g,side*.15,-.4,0,.17,.6,.18,palette.dark));}const cover=box(g,0,.25,-.30,.54,.72,.045,palette.white);assembly.push({group:g,chassis,battery,board,head,limbs,cover,index:j});}
  label(root,industries[7].x,4.25,industries[7].z+2.9,10,es?'Assembly ilustrado · piezas de tamaño fijo':'Assembly example · fixed-size components');
  for(let j=0;j<4;j++){const source=assembly[0],g=source.group.clone(true);g.traverse(o=>{if(o.userData.role==='visor')o.position.z=.19;});g.rotation.set(0,0,0);g.position.set(industries[8].x-4.5+j*3,1.45,industries[8].z-1.5);g.userData={countsAsObject:false,representation:'calibration example, not a measured quality claim'};root.add(g);testBodies.push(g);const probe=new THREE.Group();root.add(probe);const bar=box(probe,0,0,0,.72,.08,.28,palette.yellow),needles=[-.14,.14].map(x=>({mesh:cyl(probe,x,-.10,0,.018,.20,palette.dark,6),x}));scanners.push({group:probe,bar,needles,target:new THREE.Vector3(g.position.x,2.465,g.position.z),body:g});}
  label(root,industries[8].x,3.8,industries[8].z+2.6,10,es?'Prueba ilustrada · sin resultados de calidad inventados':'Calibration example · no invented quality result');
  const smokeGeo=own(new THREE.SphereGeometry(1,6,4)),smokeMat=own(new THREE.MeshBasicMaterial({color:0xb8cbd6,transparent:true,opacity:.16,depthWrite:false})),smoke=own(new THREE.InstancedMesh(smokeGeo,smokeMat,10)),dust=own(new THREE.InstancedMesh(smokeGeo,own(new THREE.MeshBasicMaterial({color:0xdac49b,transparent:true,opacity:.16,depthWrite:false})),8));root.add(smoke,dust);smoke.frustumCulled=dust.frustumCulled=false;smoke.count=dust.count=0;const temp=new THREE.Object3D();
  const lightCanvas=document.createElement('canvas');lightCanvas.width=64;lightCanvas.height=64;const context=lightCanvas.getContext('2d'),gradient=context.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,214,147,.5)');gradient.addColorStop(1,'rgba(255,214,147,0)');context.fillStyle=gradient;context.fillRect(0,0,64,64);const lightMaterial=own(new THREE.MeshBasicMaterial({map:own(new THREE.CanvasTexture(lightCanvas)),transparent:true,opacity:.5,depthWrite:false,blending:THREE.AdditiveBlending}));
  industries.forEach(s=>{const light=new THREE.Mesh(own(new THREE.PlaneGeometry(15,12)),lightMaterial);light.rotation.x=-Math.PI/2;light.position.set(s.x,.355,s.z+1);root.add(light);});
  for(const [from,to]of[[0,1],[1,2],[1,3],[1,4],[1,5],[2,6],[3,6],[4,6],[5,6],[6,7],[7,8]]){const a=industries[from],b=industries[to],path=roadRoute({x:a.x+6.6,z:a.z+6.8},{x:b.x-6.6,z:b.z+6.8}),material=own(new THREE.LineBasicMaterial({color:0x8edccc,transparent:true,opacity:.8,depthWrite:false})),line=new THREE.Line(own(new THREE.BufferGeometry().setFromPoints(path.map(p=>new THREE.Vector3(p.x,.55,p.z)))),material);root.add(line);const arrows=[];for(let j=0;j<4;j++){const arrow=new THREE.Mesh(own(new THREE.ConeGeometry(.3,.8,3)),own(new THREE.MeshBasicMaterial({color:0x9aefda})));arrow.userData={countsAsObject:false,representation:'direction of aggregate observed flow'};root.add(arrow);arrows.push(arrow);}routes.push({from,to,path,line,arrows});}
  const units=es?['ore batches','refined batches','structures','actuadores','batteries','electrónica','kits','robots por probar']:['ore lots','refined lots','frames','actuators','batteries','electronics','kits','robots to test'];
  function update(frame,next,time,phase,selected,showRoutes,traceSources=[]){if(disposed)return;const fraction=Number.isFinite(phase)?THREE.MathUtils.clamp(phase,0,.999999):0,clock=(Number(frame.absHour)||0)+fraction,statuses=industries.map((_,i)=>processStatus(frame,null,i)),active=statuses.map((s,i)=>s.rate>0&&Number(frame.capacity[i])>0),h=(frame.hour+fraction)%24,night=1-THREE.MathUtils.smoothstep(Math.sin((h-6)/24*Math.PI*2),-.13,.35);lightMaterial.opacity=night*.42;
    rings.forEach((o,i)=>{o.material.color.set(selected===i?0xffffff:statuses[i].color);o.material.opacity=selected===i?.9:statuses[i].code==='waiting'?.35+.1*Math.sin(clock*2):.16;beacons[i].material.color.set(statuses[i].color);beacons[i].material.emissive.set(statuses[i].color);});
    const inventories=[];stocks.forEach((crates,i)=>{const count=Math.max(0,Math.floor(Number(frame.inventory[i])||0)),samples=Math.min(12,count);crates.forEach((o,j)=>{const start=j<samples?Math.floor(j*count/samples):count,end=j<samples?Math.floor((j+1)*count/samples):count;o.visible=j<samples;o.userData={sampleOf:'inventory-'+i,countsAsObject:false,rangeStart:start,rangeEnd:end,representedCount:j<samples?end-start:0};});Object.assign(stockGroups[i].userData,{quantity:count,samples,unit:units[i],representation:'density samples; not one object per lot'});stockLabels[i].set(`${count} ${units[i]} · ${samples} ${es?'muestras':'samples'}`);inventories.push({resource:i,quantity:count,samples,unit:units[i]});});
    taskSamples.forEach(record=>{const on=active[record.site];record.materials.forEach(m=>m.visible=on);Object.assign(record.group.userData,{active:on,observedRate:statuses[record.site].rate,completedHour:frame.worked?.hour??null});});
    assembly.forEach((record,j)=>{const p=(clock*.4+j*.21)%1,on=active[7]&&j<Math.min(5,statuses[7].rate);record.group.visible=on;record.group.scale.setScalar(1);record.chassis.visible=true;record.battery.visible=p>=.20;record.board.visible=p>=.35;record.limbs.forEach(o=>o.visible=p>=.45);record.head.visible=p>=.65;record.cover.visible=p>=.80;Object.assign(record.group.userData,{active:on,phase:on?p:0,stage:p<.2?'chassis':p<.35?'battery':p<.45?'electronics':p<.65?'actuators':p<.8?'head':'cover',observedRate:statuses[7].rate,completedHour:frame.worked?.hour??null});});
    scanners.forEach((record,j)=>{const p=(clock*.4+j*.22)%1,illustrated=active[8]&&j<Math.min(4,statuses[8].rate),stock=Number(frame.inventory[7])>j;record.body.visible=illustrated||stock;record.group.visible=illustrated;const contact=illustrated&&p>=.4&&p<=.75,height=contact?record.target.y+.25:Math.max(record.target.y+.34,record.target.y+.25+.45*Math.abs(Math.cos(p*Math.PI)));record.group.position.set(record.target.x,height,record.target.z);record.needles.forEach(needle=>{const tipY=contact?record.target.y:record.target.y+.30,length=height-tipY;needle.mesh.position.set(needle.x,-length/2,0);needle.mesh.scale.y=length/.20;needle.mesh.userData={contactPoint:[record.target.x+needle.x,tipY,record.target.z],materialPoint:[record.target.x+needle.x,record.target.y,record.target.z],contact,countsAsObject:false};});Object.assign(record.body.userData,{source:illustrated?'last completed calibration interval':'current inventory sample',inventoryQuantity:Number(frame.inventory[7])||0,observedRate:statuses[8].rate,completedHour:frame.worked?.hour??null});record.group.userData={contact,phase:illustrated?p:0,countsAsObject:false,qualityResult:null};});
    for(const [mesh,site,total]of[[smoke,1,10],[dust,0,8]]){mesh.count=active[site]?total:0;mesh.instanceMatrix.array.fill(0);for(let j=0;j<mesh.count;j++){const p=(clock*(site?.15:.3)+j/total)%1;temp.position.set(industries[site].x+(site?5.4+p*2:-1+p*2),site?6.3+p*6:1+p*1.5,industries[site].z+(site?-2+Math.sin(j)*.3:-1+Math.sin(j)*.7));temp.scale.setScalar((site?.3:.25)+p*(site?.8:.55));temp.updateMatrix();mesh.setMatrixAt(j,temp.matrix);}mesh.instanceMatrix.needsUpdate=true;mesh.boundingSphere=null;}
    routes.forEach(r=>{const traced=traceSources.includes(r.from)&&selected===r.to,visible=traced||showRoutes||selected===r.from||selected===r.to,blocked=statuses[r.to].code==='waiting'||statuses[r.to].code==='supply';r.line.visible=visible;r.line.material.color.set(traced?0xffd17f:blocked?0xffad67:0x8edccc);r.line.material.opacity=traced?1:selected===r.from||selected===r.to?.9:.3;r.arrows.forEach((o,j)=>{o.visible=visible&&active[r.from];const point=routePoint(r.path,(clock*.08+j/4)%1);o.position.set(point.x,.65,point.z);o.rotation.set(Math.PI/2,point.angle,0,'YXZ');o.userData.observedRate=statuses[r.from].rate;});});
    summary={time:clock,completedHour:frame.worked?.hour??null,scope:es?'Muestras de operaciones de la última hora completa; existencias actuales exactas. Las piezas no son lotes individuales.':'Examples from the last completed hour; exact current inventories. Parts are not tracked individual lots.',inventories,processes:statuses.map((s,i)=>({site:i,active:active[i],observedRate:s.rate,status:s.code}))};root.updateMatrixWorld(true);
  }
  root.traverse(o=>{if(o.isInstancedMesh)own(o);own(o.geometry);for(const material of(Array.isArray(o.material)?o.material:[o.material]))if(material){own(material);own(material.map);}});
  return {root,parts:{rings,beacons,stocks,stockGroups,stockLabels,assembly,scanners,testBodies,taskSamples,routes,smoke,dust},resources,update,getSummary:()=>summary,dispose(){if(disposed)return;disposed=true;for(const resource of resources)resource.dispose?.();root.removeFromParent();}};
}
