import {immersiveHref} from './immersive/catalog.js';
// Add future explanations here; the home page has no topic-specific routing logic.
const es=document.documentElement.lang==='es';
const copy=es?{brand:'EXPLICACIONES INTERACTIVAS',eyebrow:'NOTEBOOKS · SISTEMAS QUE PUEDES EXPLORAR',title:'Entenderlo cambia<br>cómo lo miras.',intro:'Robots, chips, una esfera de Dyson, un hogar, Starlink, SpaceX, Kardashev, modelos de lenguaje, un cerebro y el precio del caché. Puedes <a href="./museo/index.html">caminar el museo</a> o abrir cada página. Hay también un <a href="./growth/index.html">modelo 2D de producción y costes</a>.',footer:'Una colección abierta a nuevas preguntas.',count:'11 EXPLORACIONES'}:{brand:'INTERACTIVE EXPLANATIONS',eyebrow:'NOTEBOOKS · SYSTEMS YOU CAN EXPLORE',title:'Understanding changes<br>how you see it.',intro:'Robots, chips, a Dyson sphere, a home, Starlink, SpaceX, Kardashev, language models, a brain and the price of cache. You can <a href="./museo/index.html">walk the museum</a> or open each page. There is also a <a href="./growth/index.html">2D model of output and costs</a>.',footer:'A collection open to new questions.',count:'11 EXPLORATIONS'};
document.querySelectorAll('[data-copy]').forEach(el=>el.innerHTML=copy[el.dataset.copy]);
document.querySelector(`[hreflang="${es?'es':'en'}"]`).setAttribute('aria-current','true');
export const explorations=[
 {slug:'museo',number:'00',name:es?'Museo':'Museum',tag:es?'VISITA · PASILLO O PÁGINA':'VISIT · GALLERY OR PAGE',title:es?'Camina la sala<br>o abre la página.':'Walk the gallery<br>or open the page.',description:es?'Dos visitas para cada experiencia: verla en una pantalla del museo, entrar y vivirla, o seguir en la web.':'Two visits for every experience: see it on a museum screen, step in and live it, or stay on the web.',steps:es?['Pasillo','Pantalla','Entrar','Web']:['Gallery','Screen','Enter','Web'],color:'#f3d39a'},
 {slug:'modelos',number:'10',name:es?'Modelos':'Models',tag:es?'LENGUAJE · FAMILIAS Y PRECIO':'LANGUAGE · FAMILIES AND PRICE',title:es?'No todo modelo<br>escribe de uno en uno.':'Not every model<br>writes one by one.',description:es?'Codificador, expertos, estado, difusión, JEPA, Jev y la factura: entrada, caché y salida.':'Encoder, experts, state, diffusion, JEPA, Jev and the bill: input, cache and output.',steps:es?['Familias','Caché','Precio','Disco']:['Families','Cache','Price','Disk'],color:'#e7c98a'},
 {slug:'mente',number:'09',name:es?'Mente':'Mind',tag:es?'MENTE · GROK Y UN CEREBRO':'MIND · GROK AND A BRAIN',title:es?'No es un cerebro<br>que habla.':'Not a brain<br>that speaks.',description:es?'Cambia entre responder y entrenar. Mira qué memoria se llena, qué pesos se mueven y cuánta energía gasta un cerebro en ese intervalo.':'Switch between replying and training. See which memory fills, which weights move and how much energy a brain spends in that interval.',steps:es?['Unidades','Memoria','Pesos','Energía']:['Units','Memory','Weights','Energy'],color:'#f0b4c4'},
 {slug:'llms',number:'08',name:'LLMs',tag:es?'INTELIGENCIA ARTIFICIAL · POR DENTRO':'ARTIFICIAL INTELLIGENCE · INSIDE THE MODEL',title:es?'De tu pregunta<br>a una respuesta.':'From your question<br>to an answer.',description:es?'Sigue los tokens, abre las capas y compara lo aprendido con lo consultado. Cambia el contexto y descubre cómo puede equivocarse.':'Follow tokens, open the layers and compare learned patterns with retrieved evidence. Change context and discover how errors happen.',steps:es?['Contexto','Tokens','Capas','Respuesta']:['Context','Tokens','Layers','Answer'],color:'#99b9ff'},
 {slug:'kardashev',number:'07',name:'Kardashev',tag:es?'CIVILIZACIONES · ESCALAS DE ENERGÍA':'CIVILIZATIONS · ENERGY SCALES',title:es?'Un planeta. Una estrella.<br>Una galaxia.':'A planet. A star.<br>A galaxy.',description:es?'Reproduce el salto entre tipos I, II y III. Compara potencias y descubre por qué 0,73 no significa un 73 %.':'Play the jump between Types I, II and III. Compare power and discover why 0.73 does not mean 73%.',steps:es?['Humanidad','Planeta','Estrella','Galaxia']:['Humanity','Planet','Star','Galaxy'],color:'#bba7ef'},
 {slug:'robots',number:'01',name:'Robots',tag:es?'AUTOMATIZACIÓN · CUATRO ESCALAS':'AUTOMATION · FOUR SCALES',title:es?'Robots que construyen<br>más robots.':'Robots building<br>more robots.',description:es?'De una línea de montaje a una región. Descubre cómo crece una red cuando reinvierte lo que produce.':'From an assembly line to a region. Discover how a network grows when it reinvests what it produces.',steps:es?['Fábrica','Distrito','Ciudad','Región']:['Factory','District','City','Region'],color:'#a7e0cf'},
 {slug:'terafab',number:'02',name:'Terafab',tag:es?'SEMICONDUCTORES · VISITA EN 3D':'SEMICONDUCTORS · 3D FACTORY TOUR',title:es?'Dentro de una<br>megafábrica de chips.':'Inside a<br>chip megafactory.',description:es?'Compara lo anunciado con una fábrica representativa. Explora los equipos y cómo cambia una oblea durante el proceso.':'Compare the announced plan with a representative factory. Explore the equipment and how a wafer changes through processing.',steps:es?['Complejo','Sala limpia','Equipos','Servicios']:['Campus','Cleanroom','Equipment','Utilities'],color:'#b9b1ff'},
 {slug:'dyson',number:'03',name:es?'Esfera de Dyson':'Dyson sphere',tag:es?'ENERGÍA ESTELAR · MODELO 3D':'STELLAR ENERGY · 3D MODEL',title:es?'No es una cáscara rígida.<br>Es un enjambre.':'Not a rigid shell.<br>A swarm.',description:es?'Compara el enjambre que Dyson imaginó con la cáscara de ciencia ficción. Cambia la cobertura y el radio y mira qué pasa con la luz, el calor y la materia.':'Compare the swarm Dyson actually described with the science-fiction shell. Change coverage and radius and watch light, heat and mass respond.',steps:es?['Enjambre','Cáscara','Calor','Materia']:['Swarm','Shell','Heat','Mass'],color:'#f0c075'},
 {slug:'home',number:'04',name:es?'Hogar':'Home',tag:es?'CASA EN 3D · SIMULACIÓN REPRODUCIBLE':'3D HOME · PLAYABLE SIMULATION',title:es?'Un hogar con<br>menos tareas pendientes.':'A home with<br>fewer pending chores.',description:es?'Pulsa reproducir: recorre una casa amueblada y observa cómo los robots y la IA se encargan de sus siete quehaceres.':'Press play: explore a furnished home and watch robots and AI take on its seven chores.',steps:es?['Cocina','Limpieza','Ropa','Agenda']:['Kitchen','Cleaning','Laundry','Planning'],color:'#efbd8c'},
 {slug:'starlink',number:'05',name:'Starlink',tag:es?'CONSTELACIÓN · COBERTURA EN 3D':'CONSTELLATION · 3D COVERAGE',title:es?'Miles de satélites.<br>Un parche que se mueve.':'Thousands of satellites.<br>A moving patch.',description:es?'Mueve al usuario, apaga capas y los láseres, y mira cómo un paquete sube, salta y baja a internet.':'Move the user, switch shells and lasers, and watch a packet go up, hop and come down to the internet.',steps:es?['Capas','Usuario','Láser','Pasarela']:['Shells','User','Laser','Gateway'],color:'#6ee7c5'},
 {slug:'spacex',number:'06',name:'SpaceX',tag:es?'LANZAMIENTO · REUTILIZACIÓN 3D':'LAUNCH · 3D REUSE',title:es?'El tramo caro<br>tiene que volver.':'The expensive stage<br>has to come back.',description:es?'Falcon 9 aterriza; Starship intenta coger el booster con la torre. Sigue los minutos de un vuelo.':'Falcon 9 lands; Starship tries to catch the booster with the tower. Follow the minutes of a flight.',steps:es?['Despegue','Separación','Aterrizaje','Otra vez']:['Liftoff','Separation','Landing','Again'],color:'#e8a06a'}
];
document.querySelector('#collection').innerHTML=explorations.sort((a,b)=>a.number.localeCompare(b.number)).map(p=>{
 const immersive=immersiveHref(p.slug,'./');
 return `<article class="exploration ${p.slug}" style="--accent:${p.color}"><a class="exploration-link" href="./${p.route||p.slug}/index.html"><div class="card-top"><span>${p.tag}</span><b>${p.number}</b></div><h2>${p.name}</h2><h3>${p.title}</h3><div class="mini-diagram" aria-hidden="true">${p.steps.map((s,i)=>`<span><i>${String(i+1).padStart(2,'0')}</i>${s}</span>`).join('<em>→</em>')}</div><p>${p.description}</p></a><div class="mode-actions"><a href="./${p.route||p.slug}/index.html">${p.slug==='museo'?(es?'Visitar museo':'Visit museum'):(es?'Notebook web':'Web notebook')} ↗</a>${p.slug==='llms'?`<a class="immersive-ready" href="./llms/cinema.html">${es?'Vista cinemática':'Cinematic view'} ✦</a>`:''}${p.slug==='museo'?'':immersive?`<a class="immersive-ready" href="${immersive}">${es?'Entrar en 3D':'Enter 3D'} →</a>`:`<span>${es?'Inmersivo 3D · próximamente':'Immersive 3D · coming later'}</span>`}</div></article>`;
}).join('');
document.querySelector('[data-copy="count"]').textContent=String(explorations.length).padStart(2,'0')+' '+(es?'EXPLORACIONES':'EXPLORATIONS');
