import {LESSONS} from './catalog.js';
import {defaults,poseAt,walk} from './common.js';
import {createWorld} from './world.js';
import {StepGuide} from '../llms/guide.js';
import {VOICES} from './voices.js';
const es=document.documentElement.lang==='es',lang=es?'es':'en',text=v=>Array.isArray(v)?v[es?0:1]:v,t=(a,b)=>es?a:b,$=id=>document.getElementById(id),query=new URLSearchParams(location.search),id=query.get('topic')||'internet',lesson=Object.hasOwn(LESSONS,id)?LESSONS[id]:null;
if(id==='internet'&&query.get('mode')==='immersive'){location.replace('./internet-voyage.html');}
else if(!lesson){$('app').innerHTML=`<p>${t('Experiencia no encontrada','Experience not found')}</p><a href="../index.html">Atlas</a>`;}
else{
 let mode=query.get('mode')==='immersive'?'immersive':'web',phase=0,tick=0,params=defaults(lesson),model=lesson.evaluate(params,0),world,player=poseAt(0),travel=null,playing=false,clock=0,last=performance.now(),drag=null,voiceLang=lang,orbit={yaw:.35,pitch:.38,distance:12};const keys=new Set(),touch=new Set();
 document.title=text(lesson.title)+' · Atlas';document.body.classList.toggle('immersive',mode==='immersive');
 $('app').innerHTML=`<header><a href="../museo/index.html?pieza=${id}">← ${t('Museo','Museum')}</a><b>${text(lesson.title)}</b><a id="mode" href="?topic=${id}&mode=${mode==='web'?'immersive':'web'}">${mode==='web'?t('Entrar en 3D ↗','Enter 3D ↗'):t('Notebook web','Web notebook')}</a><a href="${es?'../../journeys/index.html':'../es/journeys/index.html'}?topic=${id}&mode=${mode}">${es?'EN':'ES'}</a></header>
 <div class="metrics" id="metrics"></div><div class="layout"><section class="visual"><div id="world"></div><p id="inspect" hidden></p><div id="position"></div><div class="view-help">${mode==='web'?t('Arrastra para girar · rueda para acercarte · pulsa objetos','Drag to rotate · wheel to zoom · select objects'):t('WASD / flechas: caminar · arrastra: mirar · caminar pausa la guía','WASD / arrows: walk · drag: look · walking pauses the guide')}</div><div class="touch">${[['forward','↑'],['left','←'],['right','→'],['back','↓']].map(([move,label])=>`<button data-move="${move}" aria-label="${move}">${label}</button>`).join('')}</div></section>
 <aside class="lesson" id="lesson"><button id="compact">${t('Ver más escena ↙','More scene ↙')}</button><span id="chapter"></span><h1 id="title"></h1><p id="explanation"></p><nav class="stops">${lesson.steps.map((s,i)=>`<button data-stop="${i}" aria-label="${text(s.title)}">${i+1}</button>`).join('')}</nav><div class="actions"><button id="guide" class="primary">${t('Guiarme','Guide me')}</button><button id="listen">${t('Escuchar','Listen')}</button><button id="next">${t('Siguiente','Next')} →</button></div><span id="voice-state" role="status"></span><div class="voice-options"><label><input id="voice" type="checkbox" checked> MiniMax</label><select id="language" aria-label="${t('Idioma de voz','Voice language')}"><option value="es" ${es?'selected':''}>ES</option><option value="en" ${es?'':'selected'}>EN</option></select><label><input id="instant" type="checkbox" ${matchMedia('(prefers-reduced-motion: reduce)').matches?'checked':''}> ${t('Sin viajes','Instant travel')}</label></div></aside></div>
 <section class="laboratory"><div class="experiment"><span class="eyebrow">${t('TU EXPERIMENTO','YOUR EXPERIMENT')}</span><h2>${text(lesson.challenge)}</h2><div class="controls">${lesson.controls.map(c=>`<label>${text(c.label)} <output id="value-${c.id}"></output><input data-control="${c.id}" type="${c.type==='toggle'?'checkbox':'range'}" ${c.type==='toggle'?(c.value?'checked':''):`min="${c.min}" max="${c.max}" step="${c.step}" value="${c.value}"`}></label>`).join('')}</div><div class="actions"><button id="play">${t('Reproducir experimento','Play experiment')}</button><button id="step">+1 ${text(lesson.unit)}</button><button id="reset">${t('Reiniciar','Reset')}</button></div><label class="timeline">${text(lesson.unit)} <output id="tick">0</output><input id="timeline" type="range" min="0" max="${lesson.horizon}" value="0"></label><div id="chart"></div></div><details class="sources"><summary>${t('Qué representa · fuentes y límites','What it represents · sources and limits')}</summary><p>${text(lesson.limitations)}</p>${lesson.sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${title} ↗</a>`).join('')}</details></section>`;
 const getClip=()=>VOICES[id]?.[voiceLang]?.find(c=>c.id==='step-'+phase)||{id:'step-'+phase,text:lesson.steps[phase].text[voiceLang==='es'?0:1],src:'',duration:18};
 function refresh(){const s=lesson.steps[phase];$('chapter').textContent=`0${phase+1} / 04 · ${mode==='immersive'?'3D':'ATLAS'}`;$('title').textContent=text(s.title);$('explanation').textContent=text(s.text);document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.stop===phase)));$('guide').textContent=touring?t('Pausar guía','Pause guide'):t('Guiarme','Guide me');$('listen').textContent=guide.running?t('Pausar voz','Pause voice'):t('Escuchar','Listen');$('voice-state').textContent=({loading:t('Cargando voz…','Loading voice…'),speaking:t('Escuchando','Listening'),waiting:t('Observa · siguiente en ','Observe · next in ')+Math.ceil(guide.remaining)+' s',reading:t('Tiempo de lectura','Reading time'),paused:t('En pausa','Paused'),ready:t('Explicación terminada','Explanation finished'),finished:t('Recorrido completo','Tour complete'),blocked:t('Pulsa escuchar para permitir audio','Press listen to allow audio'),error:t('Audio no disponible. Reintenta o desactiva MiniMax.','Audio unavailable. Retry or disable MiniMax.')})[guide.state]||'';}
 const guide=new StepGuide({getClip,gap:3,onAdvance(){if(phase===3)return false;go(phase+1,false,true);return false;},onChange:()=>refresh()});guide.automatic=false;let touring=false;
 function halt(){touring=false;travel=null;guide.pause();keys.clear();touch.clear();refresh();}
 function arrive(audio){travel=null;if(audio)guide.enter();refresh();}
 function go(index,audio=false,keep=false){if(!keep)touring=false;guide.stop();phase=index;world?.update(model,phase);refresh();$('inspect').hidden=true;const target=poseAt(index);if(mode==='web'||$('instant').checked){player=target;arrive(audio);}else travel={from:{...player},to:target,elapsed:0,duration:Math.max(.7,Math.min(4,Math.abs(target.z-player.z)/10)),audio};}
 function drawChart(){const series=model.series||[],max=Math.max(1,...series.flatMap(s=>s.values)),n=Math.max(2,...series.map(s=>s.values.length)),colors=['#9ce1c5','#f5c885','#a6b5ff'];$('chart').innerHTML=`<svg viewBox="0 0 420 125" role="img" aria-label="${t('Evolución del experimento','Experiment history')}"><path d="M30 10 V105 H415" fill="none" stroke="#7990a4"/><text x="2" y="17" fill="#c7d9e6" font-size="10">${max.toFixed(max<5?2:0)}</text><text x="12" y="106" fill="#c7d9e6" font-size="10">0</text>${series.map((s,i)=>`<polyline fill="none" stroke="${colors[i%3]}" stroke-width="2.5" points="${s.values.map((v,j)=>`${30+j/(n-1)*380},${105-Math.max(0,v)/max*92}`).join(' ')}"/>`).join('')}</svg><div class="legend">${series.map((s,i)=>`<span style="color:${colors[i%3]}">${text(s.label)}</span>`).join('')}</div>`;}
 function update(){model=lesson.evaluate(params,tick);world?.update(model,phase);$('metrics').innerHTML=model.metrics.map(m=>`<div><span>${text(m.label)}</span><b>${typeof m.value==='number'?new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(m.value):m.value}<small> ${text(m.unit)}</small></b></div>`).join('');for(const c of lesson.controls)$('value-'+c.id).textContent=c.type==='toggle'?'':params[c.id];$('tick').textContent=tick;$('timeline').value=tick;drawChart();}
 try{world=createWorld($('world'),lesson,es,info=>{halt();$('inspect').hidden=false;$('inspect').textContent=text(info);});}catch(e){$('world').innerHTML=`<p class="fallback">${t('No se pudo iniciar WebGL. Puedes usar los controles, gráficos y explicaciones de esta página.','WebGL could not start. You can use this page’s controls, charts and explanations.')}</p>`;console.error(e);}
 $('compact').onclick=()=>$('lesson').classList.toggle('compact');$('guide').onclick=()=>{if(touring){halt();return;}touring=true;go(phase===3?0:phase,true,true);};$('listen').onclick=()=>{if(travel)return;if(guide.running)guide.pause();else if(guide.state==='ready')guide.replay();else guide.resume();};$('next').onclick=()=>go((phase+1)%4,true);document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>go(+b.dataset.stop,true));
 $('language').onchange=e=>{voiceLang=e.target.value;const active=guide.running;guide.stop();if(active)guide.enter();};$('voice').onchange=e=>guide.setEnabled(e.target.checked);
 function playback(){ $('play').textContent=playing?t('Pausar experimento','Pause experiment'):t('Reproducir experimento','Play experiment');}
 $('play').onclick=()=>{if(tick===lesson.horizon)tick=0;playing=!playing;clock=0;update();playback();};$('step').onclick=()=>{playing=false;tick=Math.min(lesson.horizon,tick+1);update();playback();};$('reset').onclick=()=>{playing=false;tick=0;clock=0;update();playback();};$('timeline').oninput=e=>{playing=false;tick=+e.target.value;update();playback();};
 document.querySelectorAll('[data-control]').forEach(el=>el.oninput=()=>{const c=lesson.controls.find(c=>c.id===el.dataset.control);params[c.id]=c.type==='toggle'?el.checked:+el.value;update();});
 document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();halt();touch.add(b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>touch.delete(b.dataset.move);});
 window.addEventListener('keydown',e=>{if(mode!=='immersive'||e.target.closest?.('input,select,textarea'))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();if(touring||travel||guide.running)halt();keys.add(e.code);}if(e.code==='Escape')halt();});window.addEventListener('keyup',e=>keys.delete(e.code));
 if(world){world.canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY,moved:false};world.canvas.setPointerCapture(e.pointerId);});world.canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.sx,e.clientY-drag.sy)>5)drag.moved=true;if(drag.moved){if(mode==='immersive'){if(travel||touring)halt();player.yaw-=dx*.003;player.pitch=Math.max(-.8,Math.min(.8,player.pitch-dy*.003));}else{orbit.yaw+=dx*.006;orbit.pitch=Math.max(.08,Math.min(1.2,orbit.pitch+dy*.004));}}drag.x=e.clientX;drag.y=e.clientY;});world.canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved)world.inspect(e.clientX,e.clientY);drag=null;});world.canvas.addEventListener('pointercancel',()=>drag=null);world.canvas.addEventListener('wheel',e=>{if(mode==='web'){e.preventDefault();orbit.distance=Math.max(6,Math.min(20,orbit.distance+e.deltaY*.01));}},{passive:false});}
 function pause(){halt();playing=false;playback();}window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();last=performance.now();});window.addEventListener('pagehide',e=>{pause();guide.stop();if(!e.persisted)world?.dispose();});
 refresh();update();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden){if(travel){travel.elapsed+=dt;const p=Math.min(1,travel.elapsed/travel.duration),q=p*p*(3-2*p);for(const key of ['x','z','pitch'])player[key]=travel.from[key]+(travel.to[key]-travel.from[key])*q;const angle=Math.atan2(Math.sin(travel.to.yaw-travel.from.yaw),Math.cos(travel.to.yaw-travel.from.yaw));player.yaw=travel.from.yaw+angle*q;if(p===1)arrive(travel.audio);}else if(mode==='immersive'){player=walk(player,Number(keys.has('KeyW')||keys.has('ArrowUp')||touch.has('forward'))-Number(keys.has('KeyS')||keys.has('ArrowDown')||touch.has('back')),Number(keys.has('KeyD')||keys.has('ArrowRight')||touch.has('right'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')||touch.has('left')),dt);}
 guide.tick(dt);if(touring&&guide.state==='ready'){if(phase===3){touring=false;guide.state='finished';refresh();}else go(phase+1,true,true);}if(playing){clock+=dt;if(clock>=.7){clock=0;tick=Math.min(lesson.horizon,tick+1);update();if(tick===lesson.horizon){playing=false;playback();}}}world?.render(player,dt,playing||guide.running,orbit,mode);$('position').textContent=mode==='immersive'?`${t('Estación','Station')} ${Math.max(1,Math.min(4,Math.round(-player.z/16)+1))} · ${player.z.toFixed(1)} m`:'';if(guide.state==='waiting')refresh();}requestAnimationFrame(frame);}requestAnimationFrame(frame);
}
