import {L,control,toggle,metric,chapter} from './common.js';
export function carbonRun(p,t){let air=10,land=20,ocean=40,fossil=30;const history=[{air,land,ocean,fossil,emitted:0}];for(let i=1;i<=t;i++){const emitted=Math.min(fossil,p.stop&&i>10?0:p.emissions),photosynthesis=Math.min(air,.02*air*p.uptake),respiration=.01*land,intoOcean=.02*air,outOfOcean=.005*ocean;fossil-=emitted;air+=emitted-photosynthesis+respiration-intoOcean+outOfOcean;land+=photosynthesis-respiration;ocean+=intoOcean-outOfOcean;history.push({air,land,ocean,fossil,emitted});}return history;}
export const carbon={id:'carbon',room:'life',title:L('El viaje del carbono y el clima','Carbon’s journey and climate'),color:'#83d5d8',unit:L('intervalo','interval'),horizon:60,
 challenge:L('Parar emisiones no vacía la atmósfera de inmediato','Stopping emissions does not empty the atmosphere immediately'),controls:[control('emissions',L('Transferencia fósil · u. / intervalo','Fossil transfer · units / interval'),.5,0,2,.1),control('uptake',L('Captación terrestre · multiplicador','Land uptake · multiplier'),1,.5,2,.1),toggle('stop',L('Detener emisiones después del intervalo 10','Stop emissions after interval 10'),true)],
 steps:[chapter(L('1 · Carbono y energía son cosas distintas','1 · Carbon and energy are different things'),L('Una molécula de dióxido de carbono tiene un átomo de carbono y dos de oxígeno. El CO₂ absorbe y emite radiación infrarroja. Eso influye en el balance energético terrestre. Las bolas representan materia; el pulso luminoso representa energía. El efecto invernadero no se debe a una pared sólida en el cielo.','A carbon dioxide molecule contains one carbon atom and two oxygen atoms. CO₂ absorbs and emits infrared radiation, affecting Earth’s energy balance. Balls represent matter; the light pulse represents energy. The greenhouse effect is not caused by a solid wall in the sky.')),
 chapter(L('2 · El bosque intercambia carbono','2 · A forest exchanges carbon'),L('La fotosíntesis incorpora carbono a la vegetación. La respiración y la descomposición devuelven parte al aire. Aquí el suelo y los organismos comparten un depósito simplificado. Aumentar la captación cambia el balance, pero no convierte ese depósito en un almacén ilimitado ni elimina las emisiones fósiles.','Photosynthesis incorporates carbon into vegetation. Respiration and decomposition return some to the air. Here soil and organisms share one simplified reservoir. Raising uptake changes the balance, but it does not make that reservoir an unlimited store or eliminate fossil emissions.')),
 chapter(L('3 · El océano absorbe y devuelve','3 · The ocean absorbs and releases'),L('El océano intercambia carbono con la atmósfera. La química del agua y la circulación influyen en cuánto absorbe y durante cuánto tiempo. Nuestro depósito resume procesos muy diferentes en dos flujos. Sigue el gráfico: carbono que deja el aire puede estar en el mar; no ha desaparecido.','The ocean exchanges carbon with the atmosphere. Water chemistry and circulation affect how much it absorbs and for how long. Our reservoir compresses very different processes into two flows. Follow the chart: carbon leaving the air may be in the sea; it has not disappeared.')),
 chapter(L('4 · Mover una reserva antigua','4 · Moving an ancient reserve'),L('Quemar combustibles fósiles traslada carbono de una reserva geológica al ciclo activo. Activa la parada después del intervalo diez. Las emisiones cesan, pero los depósitos siguen intercambiando carbono y la atmósfera tarda en ajustarse. El modelo conserva cien unidades de carbono: ninguna se crea ni se destruye.','Burning fossil fuels transfers carbon from a geological reserve into the active cycle. Enable the stop after interval ten. Emissions cease, but reservoirs keep exchanging carbon and the atmosphere takes time to adjust. The model conserves one hundred carbon units: none are created or destroyed.'))],
 limitations:L('Modelo cerrado de cuatro depósitos con 100 unidades arbitrarias; no representan gigatoneladas, ppm ni años. Inicio: aire 10, tierra 20, océano 40, fósil 30. Flujos por intervalo: 2 % del aire hacia tierra (× control), 1 % de tierra de vuelta; 2 % del aire al mar y 0,5 % del mar de vuelta. No calcula temperatura, acidificación, sumideros profundos ni una proyección climática.','Closed four-reservoir model with 100 arbitrary units; these are not gigatonnes, ppm or years. Initial stocks: air 10, land 20, ocean 40, fossil 30. Per-interval flows: 2% of air to land (× control), 1% of land back; 2% of air to sea, 0.5% of sea back. It does not calculate temperature, acidification, deep sinks or a climate projection.'),
 sources:[['NASA · The Carbon Cycle','https://science.nasa.gov/earth/earth-observatory/the-carbon-cycle/'],['NOAA · Carbon cycle and greenhouse effect','https://gml.noaa.gov/outreach/carbon_toolkit/'],['NOAA · Measuring atmospheric CO₂','https://gml.noaa.gov/ccgg/about/co2_measurements_ndir.html']],
 evaluate(p,t){const history=carbonRun(p,t),s=history.at(-1);return {...s,history,metrics:[metric(L('Carbono en el aire','Carbon in the air'),s.air,L('u.','units')),metric(L('Reserva fósil restante','Remaining fossil stock'),s.fossil,L('u.','units')),metric(L('Emisión en este intervalo','Emission this interval'),s.emitted,L('u.','units'))],series:[{label:L('Aire · carbono','Air · carbon'),values:history.map(h=>h.air)},{label:L('Tierra · carbono','Land · carbon'),values:history.map(h=>h.land)},{label:L('Océano · carbono','Ocean · carbon'),values:history.map(h=>h.ocean)}]};},
 build(k){const {group,sphere,box,cylinder,tube,label,pulse}=k;const air=group(0);sphere(air,[0,2,0],.7,0x637d91,L('C: átomo de carbono.','C: carbon atom.'));for(const x of [-1.45,1.45]){sphere(air,[x,2,0],.55,0xed8f86,L('O: átomo de oxígeno.','O: oxygen atom.'));tube(air,[[x,2,0],[0,2,0]],.09,0xbfd1d8);}label(air,'O = C = O',0,3.5,0,4);const photonPath=[[-3,1,0],[0,2,0],[1,3.5,0]],photon=pulse(air,photonPath,0xffd584);tube(air,photonPath,.02,0xdfae68);
 const forest=group(1);box(forest,[0,.12,0],[6,.2,3],0x436c53);for(let i=0;i<7;i++){const x=-2.5+i*.8,z=Math.sin(i*3)*.8;cylinder(forest,[x,1,z],.1,1.8,0x9b7957);sphere(forest,[x,2,z],.6,0x85b885);}const photos=[[-3,3.3,0],[-1,2,0],[0,.5,0]],resp=[[1,.5,0],[2,2,0],[3,3.3,0]],p1=pulse(forest,photos,0x91e5b9),p2=pulse(forest,resp,0xf2be8c);tube(forest,photos,.03,0x91e5b9);tube(forest,resp,.03,0xf2be8c);
 const sea=group(2);box(sea,[0,1,0],[6,2,3],0x578ebb,null,{transparent:true,opacity:.35,depthWrite:false});const waterPoints=[];for(let i=0;i<20;i++)waterPoints.push([-3+i*.32,2+Math.sin(i*.8)*.08,1.6]);tube(sea,waterPoints,.06,0x9cdeed);const dissolved=[];for(let i=0;i<50;i++)dissolved.push(sphere(sea,[-2.8+(i%10)*.6,.3+Math.floor(i/10)*.32,1.65],.08,0xa7ded4));label(sea,'AIR ⇄ OCEAN',0,3.4,0,5);
 const fossil=group(3);for(let i=0;i<4;i++)box(fossil,[0,.35+i*.4,0],[6,.35,3],i===1?0x3b4549:0x85725f);box(fossil,[1.5,2.1,0],[1.4,1,.9],0x8798a3);cylinder(fossil,[1.7,3,0],.18,1.2,0xb4b6ad);const stock=box(fossil,[-1,.76,1.55],[2.5,.3,.1],0xd8b877,L('Reserva fósil: al disminuir, aumenta el carbono en el ciclo activo.','Fossil reserve: as it shrinks, carbon in the active cycle increases.'));const emitted=pulse(fossil,[[1.7,3.6,0],[1.7,4.2,0],[3,4.3,0]],0xd2ded9);
 return(s,time)=>{photon(photonPath,time*.25);p1(photos,time*.15);p2(resp,time*.11);stock.scale.x=Math.max(.001,s.fossil/30);dissolved.forEach((m,i)=>m.visible=i<s.ocean);emitted(s.emitted>0?[[1.7,3.6,0],[1.7,4.2,0],[3,4.3,0]]:[],time*.3);};}
};
