import {L,control,toggle,metric,chapter,clamp} from './common.js';
import {carbonTrace,sampleCarbon,carbonStoryTime} from './carbon-model.js';
export {carbonRun} from './carbon-model.js';
let key,trace,reference;
export function carbonExperiment(p){const next=[p.emissions,p.uptake,p.stop].join(':');if(next!==key){trace=carbonTrace(p);reference=carbonTrace({...p,stop:false});key=next;}return {trace,reference};}
export function carbonPose(i){const targets=[[-7,4.6,0],[-4,1.5,0],[5,0,0],[-1,1.5,1]],x=[-10,-5,5,10][i],z=11,[tx,ty,tz]=targets[i];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export const carbon={id:'carbon',room:'life',title:L('El viaje del carbono y el clima','Carbon’s journey and climate'),color:'#83d5d8',unit:L('intervalo','interval'),horizon:60,continuous:true,
 poseAt:carbonPose,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.8*Math.min(.05,dt);return {...p,x:clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-13,13),z:clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-8,13)};},
 overview:{yaw:.16,pitch:.36,distance:9.5},fitLabel:L('Ver el ciclo completo','Fit the whole cycle'),
 narrationTime(p,chapter,progress,language){return carbonStoryTime(chapter,progress,language);},
 challenge:L('Parar emisiones no vacía la atmósfera de inmediato','Stopping emissions does not empty the atmosphere immediately'),controls:[control('emissions',L('Transferencia fósil · u. / intervalo','Fossil transfer · units / interval'),.5,0,2,.1),control('uptake',L('Captación terrestre · multiplicador','Land uptake · multiplier'),1,.5,2,.1),toggle('stop',L('Detener emisiones después del intervalo 10','Stop emissions after interval 10'),true)],
 steps:[chapter(L('1 · Carbono y energía son cosas distintas','1 · Carbon and energy are different things'),L('Una molécula de dióxido de carbono tiene un átomo de carbono y dos de oxígeno. El CO₂ absorbe y emite radiación infrarroja. Eso influye en el balance energético terrestre. Las bolas representan materia; el pulso luminoso representa energía. El efecto invernadero no se debe a una pared sólida en el cielo.','A carbon dioxide molecule contains one carbon atom and two oxygen atoms. CO₂ absorbs and emits infrared radiation, affecting Earth’s energy balance. Balls represent matter; the light pulse represents energy. The greenhouse effect is not caused by a solid wall in the sky.')),
 chapter(L('2 · El bosque intercambia carbono','2 · A forest exchanges carbon'),L('La fotosíntesis incorpora carbono a la vegetación. La respiración y la descomposición devuelven parte al aire. Aquí el suelo y los organismos comparten un depósito simplificado. Aumentar la captación cambia el balance, pero no convierte ese depósito en un almacén ilimitado ni elimina las emisiones fósiles.','Photosynthesis incorporates carbon into vegetation. Respiration and decomposition return some to the air. Here soil and organisms share one simplified reservoir. Raising uptake changes the balance, but it does not make that reservoir an unlimited store or eliminate fossil emissions.')),
 chapter(L('3 · El océano absorbe y devuelve','3 · The ocean absorbs and releases'),L('El océano intercambia carbono con la atmósfera. La química del agua y la circulación influyen en cuánto absorbe y durante cuánto tiempo. Nuestro depósito resume procesos muy diferentes en dos flujos. Sigue el gráfico: carbono que deja el aire puede estar en el mar; no ha desaparecido.','The ocean exchanges carbon with the atmosphere. Water chemistry and circulation affect how much it absorbs and for how long. Our reservoir compresses very different processes into two flows. Follow the chart: carbon leaving the air may be in the sea; it has not disappeared.')),
 chapter(L('4 · Mover una reserva antigua','4 · Moving an ancient reserve'),L('Quemar combustibles fósiles traslada carbono de una reserva geológica al ciclo activo. Activa la parada después del intervalo diez. Las emisiones cesan, pero los depósitos siguen intercambiando carbono y la atmósfera tarda en ajustarse. El modelo conserva cien unidades de carbono: ninguna se crea ni se destruye.','Burning fossil fuels transfers carbon from a geological reserve into the active cycle. Enable the stop after interval ten. Emissions cease, but reservoirs keep exchanging carbon and the atmosphere takes time to adjust. The model conserves one hundred carbon units: none are created or destroyed.'))],
 limitations:L('Modelo cerrado de cuatro depósitos con 100 unidades arbitrarias; no representan gigatoneladas, ppm ni años. Inicio: aire 10, tierra 20, océano 40, fósil 30. Flujos por intervalo: 2 % del aire hacia tierra (× control), 1 % de tierra de vuelta; 2 % del aire al mar y 0,5 % del mar de vuelta. Los tamaños y las partículas son ilustrativos: los números miden carbono, que cambia de forma química al pasar entre depósitos. La parada afecta solo a la fuente fósil, no significa cero neto de todos los gases. Una fuente continua también se detiene cuando agota sus 30 unidades. No calcula temperatura, acidificación, sumideros profundos ni una proyección climática; el océano real contiene mucho más carbono del sugerido por estas proporciones.','Closed four-reservoir model with 100 arbitrary units; these are not gigatonnes, ppm or years. Initial stocks: air 10, land 20, ocean 40, fossil 30. Per-interval flows: 2% of air to land (× control), 1% of land back; 2% of air to sea, 0.5% of sea back. Sizes and particles are illustrative: the counters measure carbon, which changes chemical form between reservoirs. Stopping affects only the fossil source, not net zero for every greenhouse gas. A continuous source also stops when its 30 units run out. No temperature, acidification, deep sinks or climate projection is calculated; the real ocean contains much more carbon than these proportions suggest.'),
 sources:[['NASA · The Carbon Cycle','https://science.nasa.gov/earth/earth-observatory/the-carbon-cycle/'],['NOAA · Carbon cycle and greenhouse effect','https://gml.noaa.gov/outreach/carbon_toolkit/'],['IPCC · Net zero and temperature (FAQ 3.3)','https://www.ipcc.ch/report/ar6/wg3/downloads/faqs/IPCC_AR6_WGIII_FAQ_Chapter_03.pdf']],
 evaluate(p,t){const {trace,reference}=carbonExperiment(p),s=sampleCarbon(trace,t),history=trace.states.slice(0,Math.floor(t)+1);return {...s,trace,reference,history,emitted:history.at(-1).emitted,
 metrics:[metric(L('Aire','Air'),s.air,L('u.','units')),metric(L('Tierra y seres vivos','Land and living things'),s.land,L('u.','units')),metric(L('Océano','Ocean'),s.ocean,L('u.','units')),metric(L('Reserva fósil','Fossil stock'),s.fossil,L('u.','units'))],
 series:[{label:L('Aire · tu experimento','Air · your experiment'),values:trace.states.map(h=>h.air)},{label:L('Aire · sin parada fósil','Air · without fossil stop'),values:reference.states.map(h=>h.air)},{label:L('Reserva fósil','Fossil stock'),values:trace.states.map(h=>h.fossil)}]};},
 // The specialized renderer builds one persistent, connected landscape.
 build(){return ()=>{};}
};
