import {L,control,metric,chapter} from './common.js';
export function translate(sequence){const code={AUG:'Met',GCU:'Ala',UUU:'Phe',UUC:'Phe',GAA:'Glu'},amino=[];for(const codon of sequence){if(['UAA','UAG','UGA'].includes(codon))break;amino.push(code[codon]);}return amino;}
export const cell={id:'cell',room:'life',title:L('Una célula fabrica una proteína','A cell makes a protein'),color:'#f2a6bc',unit:L('paso','step'),horizon:18,
 challenge:L('Cambia un codón: ¿cambia la proteína?','Change a codon: does the protein change?'),controls:[control('variant',L('Variante: 0 original · 1 sinónimo · 2 parada','Variant: 0 original · 1 synonymous · 2 stop'),0,0,2)],
 steps:[chapter(L('1 · La información queda en el núcleo','1 · Information stays in the nucleus'),L('En esta célula eucariota, el ADN contiene instrucciones que pueden copiarse a ARN. La transcripción produce una molécula de ARN a partir de una región del ADN. Ampliamos solo un fragmento inventado para seguirlo con claridad: no representa un gen humano completo.','In this eukaryotic cell, DNA contains instructions that can be copied into RNA. Transcription produces an RNA molecule from a region of DNA. We enlarge a short invented fragment so we can follow it clearly: it does not represent a complete human gene.')),
 chapter(L('2 · Sale una copia, no el ADN','2 · A copy leaves, not the DNA'),L('Después de su procesamiento, el ARN mensajero puede salir del núcleo a través de poros. Aquí mostramos cinco codones: grupos de tres letras. Cambia la variante: UUU y UUC codifican el mismo aminoácido; UAA es una señal de parada. No todos los cambios de ADN alteran una proteína.','After processing, messenger RNA can leave the nucleus through pores. Here we show five codons: groups of three letters. Change the variant: UUU and UUC encode the same amino acid; UAA signals a stop. Not every DNA change alters a protein.')),
 chapter(L('3 · El ribosoma lee tripletes','3 · The ribosome reads triplets'),L('El ribosoma avanza por el mensajero. Los ARN de transferencia ayudan a incorporar los aminoácidos correspondientes, formando una cadena. Pulsa reproducir para seguir cada codón. En este ejemplo AUG inicia la traducción; cuando llega una señal de parada, la cadena se libera.','The ribosome moves along the messenger. Transfer RNAs help add the corresponding amino acids, forming a chain. Press play to follow each codon. In this example AUG starts translation; when a stop signal arrives, the chain is released.')),
 chapter(L('4 · La cadena debe funcionar','4 · The chain must work'),L('Una proteína necesita plegarse y puede requerir modificaciones y transporte. El retículo y el aparato de Golgi intervienen en determinadas rutas, no en todas las proteínas. Las mitocondrias contribuyen a producir ATP para procesos celulares. Nuestra cadena corta es una demostración del código genético, no una proteína funcional.','A protein must fold and may need modification and transport. The endoplasmic reticulum and Golgi apparatus participate in certain routes, not in every protein’s journey. Mitochondria help produce ATP for cellular processes. Our short chain demonstrates the genetic code; it is not a functional protein.'))],
 limitations:L('Fragmento artificial de cinco codones bajo el código genético estándar. ADN, ARN, orgánulos y aminoácidos están fuera de escala. Se omiten regulación, intrones, procesamiento, cinética, errores y degradación. Los pasos no son segundos biológicos.','Artificial five-codon fragment under the standard genetic code. DNA, RNA, organelles and amino acids are not to scale. Regulation, introns, processing, kinetics, errors and degradation are omitted. Steps are not biological seconds.'),
 sources:[['NHGRI · Genetic code cracked','https://www.genome.gov/25520300/online-education-kit-1966-genetic-code-cracked'],['NHGRI · Transcription','https://www.genome.gov/genetics-glossary/Transcription'],['NHGRI · Translation','https://www.genome.gov/genetics-glossary/Translation'],['NHGRI · Messenger RNA','https://www.genome.gov/genetics-glossary/Messenger-RNA-mRNA'],['NHGRI · Mitochondria','https://www.genome.gov/genetics-glossary/Mitochondria']],
 evaluate(p,t){const sequence=['AUG','GCU',['UUU','UUC','UAA'][p.variant],'GAA','UAA'],protein=translate(sequence),read=Math.min(5,Math.floor(t/3)),length=Math.min(protein.length,read),released=read>protein.length;return {sequence,protein,read,length,released,variant:p.variant,metrics:[metric(L('Codón variable','Variable codon'),sequence[2]),metric(L('Aminoácidos unidos','Amino acids linked'),length),metric(L('Cadena final','Final chain'),protein.join('–'))],series:[{label:L('Cadena construida · aminoácidos','Built chain · amino acids'),values:Array.from({length:t+1},(_,i)=>Math.min(protein.length,Math.floor(i/3)))}]};},
 build(k){const {group,sphere,box,cylinder,tube,label,THREE}=k,g=group(0);sphere(g,[0,2,0],2,0xce84b9,L('Núcleo de una célula eucariota.','Nucleus of a eukaryotic cell.'),{transparent:true,opacity:.14,depthWrite:false});const strands=[[],[]];for(let i=0;i<28;i++){const a=i*.5,y=.4+i*.12,p=[Math.cos(a)*.75,y,Math.sin(a)*.75],q=[-p[0],y,-p[2]];strands[0].push(p);strands[1].push(q);if(i%2===0)tube(g,[p,q],.045,i%4?0xe7b26d:0x8ee0d0);}strands.forEach((s,i)=>tube(g,s,.09,i?0xf7bc95:0x83c6e3));
 const mrna=group(1);const membrane=sphere(mrna,[-2,2,0],1.5,0xd184b9,null,{transparent:true,opacity:.13,depthWrite:false});membrane.scale.z=.5;const letters=[],variants=[];for(let i=0;i<15;i++)letters.push(sphere(mrna,[-3+i*.43,1.8,0],.16,[0x8ad7c1,0xf6ca88,0xc3a0ed][i%3]));for(let i=0;i<3;i++){const v=new THREE.Group();mrna.add(v);label(v,['AUG · GCU · UUU · GAA · UAA','AUG · GCU · UUC · GAA · UAA','AUG · GCU · UAA · GAA · UAA'][i],0,3.5,0,6);variants.push(v);}
 const rib=group(2),ribo=new THREE.Group();rib.add(ribo);const upper=sphere(ribo,[0,2.1,0],.85,0xd6a0dd,L('Ribosoma: ensambla aminoácidos usando el ARN mensajero.','Ribosome: assembles amino acids using messenger RNA.'));upper.scale.set(1,.7,.65);const lower=sphere(ribo,[0,1.25,0],.6,0x9760ad);lower.scale.set(1,.5,.7);tube(rib,[[-3,1.6,0],[3,1.6,0]],.06,0x7edaca);for(let i=0;i<5;i++)box(rib,[-2.4+i*1.2,1.6,.16],[.8,.2,.16],i===4?0xff8d8d:0x81cab5);const chain=[];for(let i=0;i<4;i++)chain.push(sphere(ribo,[.25+i*.3,2.55+i*.28,0],.19,[0xf5b576,0x90d4f0,0xf09cbd,0xc1e999][i]));
 const organelles=group(3);const mito=sphere(organelles,[-1.5,1.8,0],1.1,0xf2b07d,L('Mitocondria: participa en la producción de ATP; no fabrica todas las proteínas.','Mitochondrion: participates in ATP production; it does not make all proteins.'));mito.scale.set(1.6,.7,.65);const crista=[];for(let i=0;i<10;i++)crista.push([-2.7+i*.26,1.8+Math.sin(i*2)*.4,.7]);tube(organelles,crista,.08,0x915b63);for(let i=0;i<4;i++){const sack=cylinder(organelles,[1.4,.9+i*.4,0],.8,.15,0x91bce1,L('Sacos del aparato de Golgi, representación esquemática.','Golgi apparatus sacs, schematic representation.'));sack.scale.x=1.6;}label(organelles,'ATP',-1.5,3,0,1.4);
 return(s,time)=>{variants.forEach((v,i)=>v.visible=i===s.variant);letters.forEach((m,i)=>m.material.emissive.setHex(Math.floor(i/3)===s.read?0x345a55:0));ribo.position.x=-2.4+Math.min(4,s.read)*1.2;chain.forEach((m,i)=>m.visible=i<s.length);chain.forEach((m,i)=>{m.position.y=2.55+i*.28+(s.released?Math.sin(time+i)*.08:0);});};}
};
