import {L,control,metric,chapter} from './common.js';
export function gridRun(p,hours){
 let stored=10;const history=[];
 for(let hour=0;hour<=hours;hour++){
  const solar=p.sun*Math.max(0,Math.sin((hour-6)*Math.PI/12)),wind=8+4*Math.sin(hour*.4),generated=solar+wind,current=generated*1000/p.voltage,loss=current*current*20/1e6,available=generated-loss;
  const discharge=Math.min(6,stored,Math.max(0,p.demand-available)),charge=Math.min(6,20-stored,Math.max(0,available-p.demand)),served=Math.min(p.demand,available+discharge),curtailed=Math.max(0,available-served-charge);
  const before=stored;stored+=charge-discharge;history.push({hour,solar,wind,generated,current,loss,available,discharge,charge,served,curtailed,before,stored});
 }return history;
}
export const electricity={id:'electricity',room:'industry',title:L('Electricidad: hasta el enchufe','Electricity: to the outlet'),color:'#ffd278',unit:L('hora','hour'),horizon:23,
 challenge:L('¿Puede la red cubrir la demanda al caer la noche?','Can the grid meet demand after sunset?'),
 controls:[control('sun',L('Solar máxima · MW','Peak solar · MW'),28,0,40),control('demand',L('Demanda · MW','Demand · MW'),22,10,45),control('voltage',L('Transporte · kV','Transmission · kV'),200,50,400,10)],
 steps:[chapter(L('1 · Convertir energía','1 · Converting energy'),L('El viento hace girar un generador. Los paneles convierten luz en electricidad. Sigue la potencia disponible durante un día: al anochecer desaparece la aportación solar. Un megavatio mide potencia; mantenerlo una hora produce un megavatio hora de energía.','Wind turns a generator. Panels convert light into electricity. Follow available power over a day: solar production disappears at night. A megawatt measures power; sustaining it for one hour produces one megawatt hour of energy.')),
 chapter(L('2 · Elevar la tensión','2 · Raising voltage'),L('Un transformador cambia la tensión de una corriente alterna. Para transportar la misma potencia, una tensión mayor permite una corriente menor. En nuestro circuito simplificado, la potencia es tensión por corriente y el calentamiento del cable es corriente al cuadrado por resistencia. Prueba el control de tensión.','A transformer changes alternating voltage. For the same power, higher voltage allows lower current. In our simplified circuit, power equals voltage times current, and cable heating equals current squared times resistance. Try the voltage control.')),
 chapter(L('3 · Atravesar la red','3 · Crossing the grid'),L('Las torres sostienen conductores; parte de la energía se transforma en calor. Las subestaciones vuelven a reducir la tensión antes de distribuirla. Las luces que recorren los cables representan transferencia de energía, no electrones viajando desde la central hasta tu casa.','Towers support conductors; some energy becomes heat. Substations reduce voltage again before distribution. Lights moving along these wires represent energy transfer, not electrons travelling from the power station to your home.')),
 chapter(L('4 · Equilibrar cada hora','4 · Balancing every hour'),L('La ciudad pide potencia y la batería guarda energía. Este ejemplo empieza con diez megavatios hora y permite cargar o descargar hasta seis megavatios. Avanza las horas: una batería vacía no cubre un déficit, y una llena obliga a recortar un excedente. El gráfico muestra demanda y suministro efectivo.','The city demands power and the battery stores energy. This example starts with ten megawatt hours and allows charging or discharging at up to six megawatts. Advance the hours: an empty battery cannot cover a shortage, and a full one forces surplus curtailment. The chart shows demand and actual supply.'))],
 limitations:L('Balance horario de ejemplo, no una red nacional: circuito equivalente resistivo de 20 Ω, P = VI, batería ideal de 20 MWh, límite de 6 MW y rendimiento del 100 %. Se omiten frecuencia, potencia reactiva, red trifásica, fallos y pérdidas del almacenamiento. El indicador de batería corresponde al final de la hora seleccionada.','Illustrative hourly balance, not a national grid: equivalent 20 Ω resistive circuit, P = VI, ideal 20 MWh battery, 6 MW limit and 100% efficiency. Frequency, reactive power, three-phase topology, faults and storage losses are omitted. Battery level is measured at the end of the selected hour.'),
 sources:[['EIA · Delivery to consumers','https://www.eia.gov/energyexplained/electricity/delivery-to-consumers.php'],['DOE · Quadrennial Energy Review','https://www.energy.gov/sites/prod/files/2017/02/f34/Quadrennial%20Energy%20Review--Second%20Installment%20%28Full%20Report%29.pdf']],
 evaluate(p,t){const history=gridRun(p,t),s=history.at(-1);return {...s,demand:p.demand,history,metrics:[metric(L('Entregado / solicitado','Delivered / requested'),`${s.served.toFixed(1)} / ${p.demand}`,'MW'),metric(L('Calor en el cable','Cable heat loss'),s.loss,'MW'),metric(L('Energía almacenada','Stored energy'),s.stored,'MWh')],series:[{label:L('Suministro · MW','Supply · MW'),values:history.map(h=>h.served)},{label:L('Demanda · MW','Demand · MW'),values:history.map(()=>p.demand)}]};},
 build(k){const {group,box,cylinder,sphere,tube,label,pulse,THREE}=k;const g=group(0);cylinder(g,[-1,1.6,0],.1,3.2,0xc2d2d9);const rotor=new THREE.Group();rotor.position.set(-1,3.4,.25);g.add(rotor);sphere(rotor,[0,0,0],.2,0xffffff);for(let i=0;i<3;i++){const blade=box(rotor,[0,.65,0],[.13,1.2,.08],0xd8e8ef);blade.position.set(Math.sin(i*2*Math.PI/3)*.65,Math.cos(i*2*Math.PI/3)*.65,0);blade.rotation.z=-i*2*Math.PI/3;}
  for(let x=0;x<3;x++)for(let z=0;z<2;z++){const panel=box(g,[x*.8,.6,1+z*.7],[.7,.07,.6],0x264ba0,L('Células fotovoltaicas: luz → electricidad.','Photovoltaic cells: light → electricity.'));panel.rotation.x=.3;}
  const tr=group(1);for(const x of [-1.4,1.4]){box(tr,[x,1.8,0],[1.1,2.8,.4],0x55707e);for(let i=0;i<9;i++)tube(tr,[[x-.65,.65+i*.25,.25],[x-.65,.65+i*.25,-.35],[x+.65,.65+i*.25,-.35],[x+.65,.65+i*.25,.25],[x-.65,.65+i*.25,.25]],.065,x<0?0xe3ab5f:0xdb734e,L('Bobinas acopladas por un núcleo magnético; no se conectan eléctricamente entre sí.','Coils coupled by a magnetic core; they are not electrically connected to one another.'));}label(tr,'AC → AC',0,3.7,0);
  const grid=group(2),paths=[];for(const x of [-2.7,2.7]){for(const side of [-1,1])tube(grid,[[x+side*.65,0,0],[x+side*.18,3.2,0]],.07,0x9eb7c3);for(let i=0;i<4;i++){const y=.4+i*.65;tube(grid,[[x-.55,y,0],[x+.4,y+.6,0]],.035,0x9eb7c3);}box(grid,[x,3.2,0],[1.8,.1,.15],0x9eb7c3);}for(const z of [-.5,0,.5]){const pts=[[-2.7,3.1,z],[0,2.6,z],[2.7,3.1,z]];tube(grid,pts,.025,0xcfd6c8);paths.push({pts,move:pulse(grid,pts,0xffd278)});}
  const city=group(3),lights=[];for(let i=0;i<5;i++){const x=-2+i;box(city,[x,.8,0],[.65,1.6,.65],0x738e9e);for(let j=0;j<3;j++)lights.push(box(city,[x,.45+j*.42,.34],[.35,.22,.02],0xffd278));}box(city,[0,.6,1.6],[2.2,1.2,.7],0x354e5a);const fill=box(city,[0,.6,1.98],[2,.95,.03],0x79dcbc,L('Batería: capacidad en MWh; carga y descarga en MW.','Battery: capacity in MWh; charge and discharge in MW.'));label(city,'MW ≠ MWh',0,3,0);
  return(s,time)=>{rotor.rotation.z=-time*(.4+s.wind/12);paths.forEach(({pts,move},i)=>move(pts,(time*.3+i/3)%1));fill.scale.x=Math.max(.001,s.stored/20);lights.forEach((m,i)=>m.material.color.setHex(i/lights.length<s.served/s.demand?0xffd278:0x263947));};
 }
};
