import {L,control,toggle,metric,chapter,clamp} from './common.js';
import {cascade,atRound,storyRound} from './ideas-model.js';
export {socialEdges,spread} from './ideas-model.js';
let lastKey,lastTrace;
export function experiment(p){const key=[p.contacts,p.probability,p.bridges,p.seed??731].join(':');if(key!==lastKey){lastTrace=cascade(p);lastKey=key;}return lastTrace;}
export function ideaPose(i){const x=[-11,-3,6,13][i],z=13,dx=x,dz=z;return {x,z,yaw:Math.atan2(dx,dz),pitch:-Math.atan2(.45,Math.hypot(dx,dz))};}
export const ideas={id:'ideas',room:'mind',title:L('Cómo se propaga una idea','How an idea spreads'),color:'#e5a5f2',unit:L('ronda','round'),horizon:64,continuous:true,overview:{yaw:.2,pitch:.85,distance:11},fitLabel:L('Ver toda la red','Fit whole network'),
 poseAt:ideaPose,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.8*Math.min(.05,dt);return {...p,x:clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-13,13),z:clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-12,14)};},
 narrationTime(p,chapter,progress){return storyRound(experiment(p),chapter,progress);},
 challenge:L('Una persona, cuatro comunidades, 64 posibles lectores','One person, four communities, 64 possible readers'),controls:[control('probability',L('Probabilidad de transmitir · %','Transmission probability · %'),85,0,100,5),control('contacts',L('Vecinos por cada lado','Neighbours on each side'),2,1,4),toggle('bridges',L('Puentes entre comunidades','Bridges between communities'),true),control('seed',L('Azar reproducible · semilla','Repeatable randomness · seed'),731,1,999)],
 steps:[chapter(L('1 · Alguien comparte','1 · Someone shares'),L('Una persona conoce una idea y la transmite a sus contactos. Cada persona recién alcanzada tiene una sola ronda para intentar transmitirla. La probabilidad es un control del experimento, no una medida del comportamiento humano. Amarillo significa activo; verde, alcanzado anteriormente; gris, todavía no alcanzado.','One person knows an idea and shares it with contacts. Each newly reached person has one round to attempt transmission. Probability is an experimental control, not a measurement of human behaviour. Yellow means active; green means reached earlier; grey means not yet reached.')),
 chapter(L('2 · Una red puede multiplicar','2 · A network can multiply'),L('Si varias personas alcanzan a otras nuevas, las primeras rondas pueden crecer deprisa. Pero los contactos se repiten y muchos ya conocen la idea. Compara la curva verde con una referencia lineal que añade dos personas por ronda. No toda difusión crece exponencialmente, ni puede hacerlo para siempre.','When several people reach new people, early rounds can grow quickly. But contacts overlap and many already know the idea. Compare the green curve with a linear reference adding two people per round. Not every diffusion process grows exponentially, and none can do so forever in a finite population.')),
 chapter(L('3 · Cruzar una comunidad','3 · Crossing a community'),L('Estos cuatro grupos tienen conexiones internas y unos pocos puentes. Desactívalos: la idea queda encerrada en el primer grupo, aunque aumentes la probabilidad. La estructura de la red importa tanto como la facilidad de compartir. Un puente ofrece una oportunidad, no garantiza que el mensaje cruce.','These four groups have internal connections and a few bridges. Disable them: the idea stays in the first group even if you raise the probability. Network structure matters as much as ease of sharing. A bridge offers an opportunity; it does not guarantee that the message crosses.')),
 chapter(L('4 · Saturación o extinción','4 · Saturation or extinction'),L('El contador nunca supera las sesenta y cuatro personas de esta red. La difusión termina cuando no quedan emisores activos, incluso si algunas personas no recibieron nada. Este modelo describe contactos y transmisión; no mide verdad, persuasión, calidad ni la recomendación de una plataforma.','The counter never exceeds this network’s sixty-four people. Diffusion ends when no active senders remain, even if some people received nothing. This model describes contacts and transmission; it does not measure truth, persuasion, quality or a platform’s recommendation system.'))],
 limitations:L('Cascada independiente progresiva en una red sintética de 64 personas. Cada nuevo emisor intenta una vez cada contacto todavía no alcanzado; los receptores se activan en la siguiente ronda. La semilla fija monedas distintas por dirección: cambiar la probabilidad o los puentes conserva esas mismas oportunidades. Una semilla muestra un caso, no un promedio ni una predicción humana. Sin olvido, reinfección, persuasión ni recomendación. La referencia naranja suma dos personas por ronda.','Progressive independent cascade on a synthetic network of 64 people. Each new sender tries each unreached contact once; recipients activate in the next round. The seed fixes separate coins per direction: changing probability or bridges preserves those opportunities. One seed shows a realization, not an average or a prediction of human behaviour. No forgetting, reinfection, persuasion or recommendation. The orange reference adds two people per round.'),
 sources:[['Kempe, Kleinberg & Tardos · Independent Cascade (2003)','https://www.cs.cornell.edu/home/kleinber/kdd03-inf.pdf'],['Theory of Computing · Influence in a Social Network (2015)','https://theoryofcomputing.org/articles/v011a004/v011a004.pdf']],
 evaluate(p,t){const trace=experiment(p),s=atRound(trace,t);return {...s,trace,metrics:[metric(L('Personas alcanzadas','People reached'),`${s.known.size} / 64`),metric(L('Nuevos emisores · esta ronda','New senders · this round'),s.active.length),metric(L('Comunidades alcanzadas','Communities reached'),new Set([...s.known].map(i=>Math.floor(i/16))).size+' / 4')],series:[{label:L('Red · personas acumuladas','Network · people reached'),values:s.history},{label:L('Referencia lineal: +2 / ronda','Linear reference: +2 / round'),values:s.history.map((_,i)=>Math.min(64,1+2*i))},{label:L('Nuevas personas / ronda','New people / round'),values:s.activeHistory}]};},
 // The specialized renderer in ideas-world.js builds one persistent population.
 build(){return ()=>{};}
};
