import {STAGES,SOURCES,stageFact} from './internet-route.js';
import {createVoyageWorld} from './internet-world.js';
import {VOICES} from './voices-internet-voyage.js';
import {StepGuide} from '../llms/guide.js';
import {bindFirstPerson} from '../immersive/first-person.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),txt=a=>a[es?0:1];
let phase=0,time=0,last=performance.now(),voiceLang=es?'es':'en',touring=false,exploring=false,moving=true,world,controls;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,keys=new Set(),touch=new Set();
document.title=t('Internet · Un clic al otro lado del océano','Internet · A click across the ocean')+' · Atlas';
$('app').innerHTML=`
 <div id="world" aria-label="${t('Escena tridimensional del recorrido de Internet','Three-dimensional Internet journey scene')}"></div>
 <header><a class="brand" href="../museo/index.html?pieza=internet">ATLAS<span> / ${t('MUSEO','MUSEUM')}</span></a><div class="top-links"><a href="./index.html?topic=internet">${t('Notebook','Notebook')} ↗</a><button id="sources">${t('Fuentes','Sources')}</button><a href="${es?'../../journeys/internet-voyage.html':'../es/journeys/internet-voyage.html'}" lang="${es?'en':'es'}">${es?'EN':'ES'}</a></div></header>
 <section class="story" aria-labelledby="title"><span class="eyebrow">INTERNET / ${t('EL VIAJE DE UN CLIC','THE JOURNEY OF A CLICK')}</span><p class="place" id="place"></p><h1 id="title"></h1><p class="caption" id="caption"></p><div class="fact"><strong id="number"></strong><span id="fact"></span></div><div class="legend"><i class="gold"></i>${t('Petición','Request')}<i class="mint"></i>${t('Respuesta','Response')}</div>
 <details id="transcript" open><summary>${t('Leer la explicación','Read the explanation')} <span>MiniMax</span></summary><p id="words"></p></details>
 </section>
 <div class="scene-meta"><span class="signal-dot"></span><span id="badge"></span><small>${t('Escalas y velocidades visuales adaptadas','Visual scales and speeds adapted')}</small></div>
 <div class="scene-actions"><button id="explore">${t('Explorar en primera persona','Explore in first person')} ↗</button><button id="motion" aria-label="${t('Pausar animación','Pause animation')}">Ⅱ</button></div><p id="look-help" hidden>${t('Ratón: mirar · WASD: moverte · Q/E: bajar/subir · Esc: soltar ratón','Mouse: look · WASD: move · Q/E: down/up · Esc: release mouse')}</p>
 <div class="touch" hidden>${[['forward','↑'],['left','←'],['back','↓'],['right','→'],['up','＋'],['down','−']].map(([d,v])=>`<button data-move="${d}" aria-label="${d}">${v}</button>`).join('')}</div>
 <footer><div class="transport"><button id="previous" aria-label="${t('Escena anterior','Previous scene')}">←</button><button id="play" class="primary">▶ ${t('Comenzar el viaje','Start the journey')}</button><button id="next" aria-label="${t('Escena siguiente','Next scene')}">→</button><button id="listen">${t('Escuchar esta escena','Listen to this scene')}</button><select id="language" aria-label="${t('Idioma de la narración','Narration language')}"><option value="es" ${es?'selected':''}>Voz · ES</option><option value="en" ${es?'':'selected'}>Voice · EN</option></select><label class="sound"><input id="sound" type="checkbox" checked> ${t('Voz','Voice')}</label><span id="status" role="status"></span><span class="counter" id="counter"></span></div>
 <div class="progress"><div id="progress"></div></div><nav class="chapters" aria-label="${t('Etapas del viaje','Journey chapters')}">${STAGES.map((s,i)=>`<button data-stage="${i}" title="${txt(s.title)}"><span>${String(i+1).padStart(2,'0')}</span>${[t('Tu ordenador','Your computer'),t('La ciudad','The city'),t('España','Spain'),t('La costa','The coast'),t('El Atlántico','The Atlantic'),t('Virginia','Virginia'),t('El servidor','The server'),t('La vuelta','The return'),t('Tu pantalla','Your screen')][i]}</button>`).join('')}</nav></footer>
 <dialog id="source-dialog"><button id="close-sources" class="close" aria-label="${t('Cerrar','Close')}">×</button><span class="eyebrow">${t('UN RECORRIDO DOCUMENTADO','A DOCUMENTED JOURNEY')}</span><h2>${t('Real en lo esencial. Ilustrativo en el recorrido.','Real infrastructure. An illustrative journey.')}</h2><p>${t('MAREA conecta Sopelana y Virginia Beach mediante unos 6.600 km de cable. Las conexiones terrestres hacia Ashburn están documentadas. No estamos midiendo tu conexión ni mostrando planos privados de un operador.','MAREA connects Sopelana and Virginia Beach with around 6,600 km of cable. Terrestrial connections to Ashburn are documented. This is not a measurement of your connection or an operator’s private floor plan.')}</p><ul><li>${t('Madrid, el proveedor, el servidor y sus edificios forman un ejemplo. Las curvas del globo son corredores esquemáticos, no coordenadas del cable tendido.','Madrid, the provider, the server and the buildings form an example. Globe curves show schematic corridors, not surveyed cable coordinates.')}</li><li>${t('HTTPS sobre TCP, con DNS y conexión preparados antes del viaje principal. Una CDN cercana o HTTP/3 cambiarían parte de la historia.','HTTPS over TCP, with DNS and connection setup before the main journey. A nearby CDN or HTTP/3 would change parts of the story.')}</li><li>${t('6.600 ÷ 200.000 × 1.000 ≈ 33 ms por sentido. Velocidad en fibra supuesta: 200.000 km/s. No incluye los enlaces terrestres, las colas, los equipos ni la aplicación.','6,600 ÷ 200,000 × 1,000 ≈ 33 ms one way. Assumed speed in fiber: 200,000 km/s. Excludes terrestrial links, queues, equipment and the application.')}</li><li>${t('Los puntos de luz, fibras, distancias y tiempos de animación están adaptados para enseñar. La vuelta puede tomar otro camino.','Light points, fibers, distances and animation timing are adapted for teaching. The return path can differ.')}</li></ul><div class="source-links">${SOURCES.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}</div></dialog>`;
const clip=()=>VOICES[voiceLang].find(c=>c.id===STAGES[phase].id);
const guide=new StepGuide({getClip:clip,gap:3,onAdvance(){if(phase===STAGES.length-1){touring=false;moving=false;return false;}setStage(phase+1);return true;},onChange:()=>refresh()});
guide.automatic=false;
function refresh(){
 const s=STAGES[phase],[n,f]=stageFact(s,es);$('place').textContent=txt(s.place);$('title').textContent=txt(s.title);$('caption').textContent=txt(s.caption);$('number').textContent=n;$('fact').textContent=f;$('badge').textContent=txt(s.badge);$('words').textContent=clip().text;$('words').lang=voiceLang;
 $('counter').textContent=`${String(phase+1).padStart(2,'0')} / 09`;
 document.querySelectorAll('[data-stage]').forEach(b=>{b.setAttribute('aria-current',+b.dataset.stage===phase?'step':'false');});
 $('previous').disabled=phase===0;$('next').disabled=phase===STAGES.length-1;
 $('play').textContent=touring&&guide.running?'Ⅱ '+t('Pausar viaje','Pause journey'):guide.state==='finished'?'↻ '+t('Volver a empezar','Start again'):'▶ '+t(guide.clip?'Continuar viaje':'Comenzar el viaje',guide.clip?'Continue journey':'Start the journey');
 $('listen').textContent=guide.running?t('Pausar voz','Pause voice'):t('Escuchar esta escena','Listen to this scene');
 $('status').textContent=({loading:t('Preparando voz…','Loading voice…'),speaking:t('Narrando','Narrating'),waiting:t('Observa · ','Observe · ')+Math.ceil(guide.remaining)+' s',reading:t('Tiempo de lectura','Reading time'),paused:t('En pausa','Paused'),ready:t('Escena completada','Scene complete'),finished:t('Viaje completado','Journey complete'),blocked:t('Pulsa escuchar para activar el audio','Press listen to enable audio'),error:t('No se pudo cargar la voz. Reintenta o desactívala.','Voice could not load. Retry or turn it off.')})[guide.state]||t('9 escenas · recorrido guiado','9 scenes · guided journey');
 $('motion').textContent=moving?'Ⅱ':'▶';$('motion').setAttribute('aria-label',moving?t('Pausar animación','Pause animation'):t('Reanudar animación','Resume animation'));
 document.body.classList.toggle('returning',phase>=7);
}
function leaveExplore(){exploring=false;controls?.release();world?.explore(false);$('explore').textContent=t('Explorar en primera persona','Explore in first person')+' ↗';$('look-help').hidden=true;document.querySelector('.touch').hidden=true;keys.clear();touch.clear();}
function setStage(i){leaveExplore();phase=i;time=0;moving=true;world?.go(i,reduced);refresh();document.querySelector(`[data-stage="${i}"]`).scrollIntoView({behavior:reduced?'instant':'smooth',inline:'nearest',block:'nearest'});}
function go(i){guide.stop();touring=false;guide.automatic=false;setStage(i);}
$('previous').onclick=()=>go(Math.max(0,phase-1));$('next').onclick=()=>go(Math.min(STAGES.length-1,phase+1));
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>go(+b.dataset.stage));
$('play').onclick=()=>{if(touring&&guide.running){guide.pause();moving=false;}else{leaveExplore();touring=true;guide.automatic=true;moving=true;if(guide.state==='finished'){setStage(0);guide.enter();}else guide.resume();}refresh();};
$('listen').onclick=()=>{if(guide.running){guide.pause();moving=false;}else{touring=false;guide.automatic=false;moving=true;if(guide.state==='ready')guide.replay();else guide.resume();}refresh();};
$('language').onchange=e=>{voiceLang=e.target.value;const active=guide.running;guide.stop();if(active)guide.enter();refresh();};
$('sound').onchange=e=>{guide.setEnabled(e.target.checked);refresh();};
$('motion').onclick=()=>{moving=!moving;if(!moving)guide.pause();refresh();};
$('sources').onclick=()=>{guide.pause();moving=false;controls?.release();$('source-dialog').showModal();refresh();};$('close-sources').onclick=()=>$('source-dialog').close();
$('explore').onclick=()=>{if(exploring){leaveExplore();return;}exploring=true;$('explore').blur();touring=false;guide.automatic=false;world?.explore(true);$('explore').textContent=t('Volver a la cámara guiada','Return to guided camera');$('look-help').hidden=false;document.querySelector('.touch').hidden=!matchMedia('(pointer:coarse)').matches;controls?.request();refresh();};
try{world=createVoyageWorld($('world'),es);controls=bindFirstPerson({canvas:world.canvas,enabled:()=>exploring,onLook:(dx,dy)=>world.look(dx,dy),onActivate(){},onState(){}});}catch(e){$('world').innerHTML=`<p class="fallback">${t('WebGL no está disponible. Puedes seguir las nueve explicaciones, el texto y el audio.','WebGL is unavailable. You can still follow all nine explanations, text and audio.')}</p>`;$('explore').disabled=true;console.error(e);}
document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();touch.add(b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>touch.delete(b.dataset.move);});
window.addEventListener('keydown',e=>{if(!exploring||e.target.closest('input,select,button,a,dialog'))return;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='Escape'){controls?.release();keys.clear();}});window.addEventListener('keyup',e=>keys.delete(e.code));
function pause(){guide.pause();keys.clear();touch.clear();moving=false;refresh();}window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();last=performance.now();});window.addEventListener('pagehide',e=>{pause();guide.stop();if(!e.persisted){controls?.dispose();world?.dispose();}});
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden){guide.tick(dt);if(moving)time+=dt;const audioProgress=guide.audio&&Number.isFinite(guide.audio.currentTime)?guide.audio.currentTime/clip().duration:null;const progress=Math.min(1,audioProgress??time/16);$('progress').style.width=`${(phase+progress)/STAGES.length*100}%`;if(exploring){const press=(codes,d)=>codes.some(k=>keys.has(k))||touch.has(d)?1:0;world?.move(press(['KeyW','ArrowUp'],'forward')-press(['KeyS','ArrowDown'],'back'),press(['KeyD','ArrowRight'],'right')-press(['KeyA','ArrowLeft'],'left'),press(['KeyE'],'up')-press(['KeyQ'],'down'),dt);}world?.render(dt,reduced?0:time,progress,reduced);if(guide.state==='waiting')$('status').textContent=t('Observa · ','Observe · ')+Math.ceil(guide.remaining)+' s';}requestAnimationFrame(frame);}
refresh();requestAnimationFrame(frame);
