import * as THREE from '../../vendor/three.module.js';
import {sampleChip} from './microchip-model.js';

export const MICROCHIP_FOCUS=[[-12,2.2,0],[-4.5,2.6,0],[6.1,2.7,0],[13,2.8,0]];
export const microchipOverview={yaw:.06,pitch:.28,distance:9.5};
export const MICROCHIP_BOUNDS=[[-15,.15,-1.8,-8.5,4.5,2.1],[-7.1,.15,-1.0,-1.6,5.95,1.7],[-.85,.02,-.6,15.4,5.95,3.6],[10.1,.02,-.5,15.5,6.2,3.6],[-16,.02,-3,16,6.2,6.9]];
export function microchipPoseAt(index){const x=[-12,-4.5,5.2,13][index],z=9,[tx,ty,tz]=MICROCHIP_FOCUS[index];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export function microchipWalk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),d=3.8*Math.min(.05,dt),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*d,-18,18),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*d,-9,14);const inside=(px,pz)=>px>-16.2&&px<16.2&&pz>-2.9&&pz<2.9;if(inside(x,p.z))x=p.x;if(inside(x,z))z=p.z;return {...p,x,z};}
const C={low:0x5eafff,high:0x86e7b3,pending:0x526b7b,metal:0xb4bcc9,silicon:0x6e89b8,oxide:0xf3c987,gate:0xc6aedf,board:0x214c4e,field:0xd8b0f0};
const levelColor=value=>value===1?C.high:value===0?C.low:C.pending;

export function createMicrochipScene(lesson,es=true){
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x152b3b);scene.fog=new THREE.Fog(0x152b3b,55,115);
 const resources=[],targets=[],stands=[],routes=[],gates=[],terminals={},logicalNodes={},own=x=>(resources.push(x),x),t=(a,b)=>es?a:b,L=(a,b)=>[a,b];
 const mat=(color,extra={})=>own(new THREE.MeshStandardMaterial({color,roughness:.48,metalness:.22,...extra}));
 scene.add(new THREE.HemisphereLight(0xcce7ff,0x324941,2.35));const sun=new THREE.DirectionalLight(0xffe8c6,3);sun.position.set(-10,17,11);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-22,right:22,top:15,bottom:-15,near:.1,far:60});sun.shadow.normalBias=.045;scene.add(sun);resources.push(sun.shadow);
 function mesh(g,geometry,material,p=[0,0,0]){const m=new THREE.Mesh(geometry,material);m.position.set(...p);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 function box(g,p,size,color,extra){return mesh(g,own(new THREE.BoxGeometry(...size)),mat(color,extra),p);}
 function ball(g,p,r,color,extra){return mesh(g,own(new THREE.SphereGeometry(r,16,12)),mat(color,extra),p);}
 function cylinder(g,p,r,h,color,extra){return mesh(g,own(new THREE.CylinderGeometry(r,r,h,16)),mat(color,extra),p);}
 function curveOf(points){const path=new THREE.CurvePath();for(let i=1;i<points.length;i++)path.add(new THREE.LineCurve3(new THREE.Vector3(...points[i-1]),new THREE.Vector3(...points[i])));return path;}
 function tube(g,points,r,color,extra={}){const curve=points instanceof THREE.Curve?points:curveOf(points),m=mesh(g,own(new THREE.TubeGeometry(curve,Math.max(24,curve.curves?.length*10||40),r,7,false)),mat(color,extra));return {mesh:m,curve};}
 function rod(g,a,b,r,color,extra={}){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),m=cylinder(g,p.clone().add(q).multiplyScalar(.5).toArray(),r,p.distanceTo(q),color,extra);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());return m;}
 function label(g,words,p,width=3,{height=96,bg=true,depthTest=true}={}){
  const canvas=document.createElement('canvas');canvas.width=768;canvas.height=height;const ctx=canvas.getContext('2d'),texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;
  const m=new THREE.Sprite(own(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false,depthTest})));m.position.set(...p);m.scale.set(width,width*height/768,1);if(!depthTest)m.renderOrder=10;g.add(m);let previous;
  function set(words){if(words===previous)return;previous=words;const lines=String(words).split('\n');ctx.font='600 60px system-ui';canvas.width=Math.max(96,Math.min(2048,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line).width))+48)));m.scale.set(width,width*height/canvas.width,1);ctx.clearRect(0,0,canvas.width,height);if(bg){ctx.fillStyle='#14323fed';ctx.fillRect(0,0,canvas.width,height);}ctx.fillStyle='#eff6f9';ctx.font='600 60px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,height*(i+.5)/lines.length,canvas.width-36));texture.needsUpdate=true;}set(words);return {m,set};
 }
 function inspect(m,esText,enText){m.userData.info=L(esText,enText);targets.push(m);return m;}
 const annotations=new THREE.Group();scene.add(annotations);const zoneAnnotations=Array.from({length:4},()=>{const g=new THREE.Group();annotations.add(g);return g;});
 box(scene,[0,-.15,1],[40,.3,26],0x273f4a);for(let x=-18;x<=18;x+=2)box(scene,[x,.012,1],[.012,.016,24],0x365460);for(let z=-10;z<=12;z+=2)box(scene,[0,.012,z],[38,.016,.012],0x365460);
 const table=box(scene,[0,.64,0],[33,.32,5.1],0x3b5960);box(scene,[0,.84,0],[32.5,.10,4.9],C.board);for(const x of [-14,0,14])for(const z of [-1.9,1.9])box(scene,[x,.29,z],[.32,.6,.32],0x73868e,{metalness:.65});
 for(const x of [-15.7,-8.2,-1.3,15.6]){box(scene,[x,.91,0],[.045,.035,4.6],0xc6a873,{metalness:.7});for(const z of [-2.05,2.05])cylinder(scene,[x,.93,z],.085,.05,C.metal,{metalness:.8});}
 // A planar MOS cross-section is deliberately enlarged; the dielectric is a separate solid.
 const mosGroup=new THREE.Group();mosGroup.position.set(-12,0,0);scene.add(mosGroup);box(mosGroup,[0,1.04,0],[5.7,.28,3.0],0x587878);const substrate=box(mosGroup,[0,1.65,0],[5.2,1,2.4],C.silicon,{roughness:.65});
 const source=box(mosGroup,[-1.85,1.96,.02],[1.3,.38,2.44],0x77b5c4),drain=box(mosGroup,[1.85,1.96,.02],[1.3,.38,2.44],0x77b5c4);
 const channel=box(mosGroup,[0,2.115,.035],[2.4,.048,2.43],C.pending,{emissive:C.pending,emissiveIntensity:.1});const oxide=box(mosGroup,[0,2.215,0],[2.45,.13,2.5],C.oxide,{roughness:.34});const gate=box(mosGroup,[0,2.52,0],[2.45,.48,2.5],C.gate,{metalness:.55});
 const sourceContact=box(mosGroup,[-1.85,2.43,0],[.35,.55,.55],C.metal,{metalness:.75}),drainContact=box(mosGroup,[1.85,2.43,0],[.35,.55,.55],C.metal,{metalness:.75});
 const biasWires=[tube(mosGroup,[[-1.85,2.70,0],[-1.85,3.02,-.8],[-2.75,3.02,-.8]],.040,C.metal).mesh,tube(mosGroup,[[1.85,2.70,0],[1.85,3.02,-.8],[2.75,3.02,-.8]],.040,C.metal).mesh];for(const x of [-2.75,2.75])ball(mosGroup,[x,3.02,-.8],.09,C.metal);
 const gateInput=tube(mosGroup,[[0,3.65,-.25],[0,2.8,-.25]],.052,C.pending).mesh;ball(mosGroup,[0,3.65,-.25],.12,C.gate);const field=[];
 for(const x of [-.8,0,.8]){const group=new THREE.Group();group.position.set(x,2.30,1.39);mosGroup.add(group);cylinder(group,[0,.025,0],.024,.23,C.field,{emissive:C.field,emissiveIntensity:.7});const cone=mesh(group,own(new THREE.ConeGeometry(.067,.12,9)),mat(C.field,{emissive:C.field,emissiveIntensity:.7}),[0,-.13,0]);cone.rotation.z=Math.PI;field.push(group);inspect(cone,'Flecha de campo eléctrico en la cara seccionada. El campo controla el canal a través del aislante; no es conducción de partículas a través de él.','Electric-field arrow on the cut face. The field controls the channel through the dielectric; this is not particle conduction through it.');}
 const mosLabels=zoneAnnotations[0];label(mosLabels,t('NMOS · CORTE ESQUEMÁTICO','NMOS · SCHEMATIC SECTION'),[-12,4.03,0],5.5);label(mosLabels,t('fuente n+ · 0 V','source n+ · 0 V'),[-13.85,3.20,0],2.0);label(mosLabels,t('puerta','gate'),[-12,3.20,0],1.25);label(mosLabels,t('drenador n+ · +VDS','drain n+ · +VDS'),[-10.15,3.20,0],2.25);label(mosLabels,t('aislante','insulator'),[-9.72,2.65,1.48],1.70);label(mosLabels,t('sustrato p · ampliado','p substrate · enlarged'),[-12,1.80,1.30],3.55);const channelCaption=label(mosLabels,'',[-12,1.00,1.80],5.2,{height:128,depthTest:false});
 inspect(substrate,'Corte de un NMOS planar, ampliado y no a escala. El cuerpo es silicio tipo p; fuente y drenador son regiones dopadas n+. No representa la geometría de un chip comercial moderno.','Enlarged, not-to-scale planar NMOS section. The body is p-type silicon; source and drain are n+ doped regions. This is not the geometry of a modern commercial chip.');
 inspect(source,'Fuente n+ a 0 V en este sesgo ilustrativo. Un canal habilitado solo conduce corriente si hay diferencia de potencial entre drenador y fuente.','Source n+ at 0 V in this illustrative bias. An enabled channel carries current only with a drain-to-source potential difference.');inspect(drain,'Drenador n+ a +VDS: sesgo ilustrativo, sin valor numérico de tensión ni cálculo de corriente. El canal ideal se activa con A alto.','Drain n+ at +VDS: illustrative bias, with no numerical voltage or current calculation. The ideal channel is enabled by high A.');inspect(oxide,'El dieléctrico aísla eléctricamente la puerta del semiconductor. Las flechas muestran campo eléctrico, no partículas que lo atraviesan.','The dielectric electrically insulates the gate from the semiconductor. Arrows show electric field, not particles crossing it.');inspect(gate,'La tensión de puerta controla el canal mediante un campo eléctrico. Estado ideal: A=1 abre el NMOS, A=0 lo cierra.','Gate voltage controls the channel through an electric field. Ideal state: A=1 enables the NMOS, A=0 disables it.');inspect(channel,'Canal de inversión esquemático: conecta las dos regiones n+ al activarse. Se omiten umbral, corriente analógica y fugas.','Schematic inversion channel: connects the two n+ regions when enabled. Threshold, analogue current and leakage are omitted.');
 const mos={group:mosGroup,substrate,source,drain,sourceContact,drainContact,oxide,gate,channel,field,gateInput,biasWires};
 // The two insulated gates control separate pull-up/pull-down channels. There is no VDD→GND wire.
 const inverterGroup=new THREE.Group();inverterGroup.position.set(-4.5,0,0);scene.add(inverterGroup);box(inverterGroup,[0,.99,0],[4.6,.2,2.1],0x426d73);
 function transistor(y,isP){const group=new THREE.Group();group.position.set(0,y,0);inverterGroup.add(group);const body=box(group,[0,0,0],[.54,1.10,.58],isP?0xba9cc8:0x92adc9,{transparent:true,opacity:.37,depthWrite:false});body.castShadow=false;
  const channel=box(group,[0,0,.35],[.15,.68,.12],C.pending,{emissive:C.pending,emissiveIntensity:.18}),oxide=box(group,[-.26,0,.24],[.10,.66,.52],C.oxide),gate=box(group,[-.43,0,.24],[.13,.66,.52],C.gate,{metalness:.5});
  const top=box(group,[0,.49,.25],[.33,.14,.35],C.metal,{metalness:.7}),bottom=box(group,[0,-.49,.25],[.33,.14,.35],C.metal,{metalness:.7});return {group,body,channel,oxide,gate,source:isP?top:bottom,drain:isP?bottom:top,on:false};}
 const pm=transistor(3.5,true),nm=transistor(1.8,false);const powerRails=[];
 for(const [a,b] of [[[0,4.7,.25],[0,3.99,.25]],[[0,3.01,.25],[0,2.65,.25]],[[0,2.65,.25],[0,2.29,.25]],[[0,1.31,.25],[0,.60,.25]]])powerRails.push(tube(inverterGroup,[a,b],.047,C.metal).mesh);
 tube(inverterGroup,[[0,2.65,.25],[2.3,2.65,.25]],.047,C.metal);ball(inverterGroup,[0,2.65,.25],.09,C.metal);const inverterOutput=ball(inverterGroup,[2.3,2.65,.25],.23,C.pending,{emissive:C.pending,emissiveIntensity:.35});
 const gateWires=[];gateWires.push(tube(inverterGroup,[[-2.1,2.65,.25],[-1.20,2.65,.25]],.045,C.pending).mesh);for(const y of [3.5,1.8])gateWires.push(tube(inverterGroup,[[-1.20,2.65,.25],[-1.20,y,.25],[-.50,y,.25]],.045,C.pending).mesh);ball(inverterGroup,[-1.20,2.65,.25],.075,C.metal);
 const pullup=tube(inverterGroup,[[0,4.7,.30],[0,3.5,.40],[0,2.65,.30],[2.3,2.65,.30]],.031,C.high,{emissive:C.high,emissiveIntensity:.7}),pulldown=tube(inverterGroup,[[2.3,2.65,.30],[0,2.65,.30],[0,1.8,.40],[0,.60,.30]],.031,C.low,{emissive:C.low,emissiveIntensity:.7});
 const invLabels=zoneAnnotations[1];label(invLabels,'CMOS',[-4.5,5.28,0],2.2);label(invLabels,'VDD',[-4.5,4.64,.65],1.5);label(invLabels,'GND',[-4.5,.57,.75],1.6);label(invLabels,'pMOS',[-3.58,3.5,.55],1.18);label(invLabels,'nMOS',[-3.58,1.8,.55],1.18);const invInputCaption=label(invLabels,'',[-6.36,3.28,.55],1.5),invOutputCaption=label(invLabels,'',[-2.20,3.27,.55],2.3);label(invLabels,t('Demostración independiente','Separate demonstration'),[-4.5,1.03,1.15],4.8);
 inspect(pm.gate,'Entrada A conectada a la puerta aislada del pMOS. A=0 habilita el camino desde VDD; A=1 lo cierra.','Input A connects to the insulated pMOS gate. A=0 enables the path from VDD; A=1 disables it.');inspect(nm.gate,'La misma A controla la puerta aislada del nMOS. A=1 habilita el camino de salida a tierra.','The same A controls the insulated nMOS gate. A=1 enables the output-to-ground path.');inspect(pm.channel,'Camino ideal de carga de la salida a VDD. No se conecta eléctricamente a la puerta y no forma un cortocircuito hacia GND.','Ideal output charging path from VDD. It is not electrically connected to the gate and does not create a short circuit to GND.');inspect(nm.channel,'Camino ideal para descargar la salida hacia GND. El otro transistor está cerrado en el estado lógico estable.','Ideal path to discharge the output toward GND. The other transistor is disabled in a stable logical state.');inspect(inverterOutput,'NOT A: salida del inversor. Esta demostración no alimenta el sumador; el sumador recibe directamente A, B y Cin.','NOT A: inverter output. This demonstration does not feed the adder; the adder receives A, B and Cin directly.');
 const inverter={group:inverterGroup,pm,nm,gateWires,powerRails,paths:{pullup,pulldown},output:inverterOutput};
 // The adder is one circuit. Chapter four observes the same output terminals, not a copy.
 const adderGroup=new THREE.Group();scene.add(adderGroup);const adderBoard=box(adderGroup,[7.3,2.90,-.30],[16.5,4.45,.18],0x193f45,{roughness:.58});box(adderGroup,[7.3,2.9,-.44],[16.9,4.8,.10],0x789597,{metalness:.6});for(const x of [-.70,15.4])for(const y of [.75,5.05]){const screw=cylinder(adderGroup,[x,y,-.14],.095,.04,C.metal,{metalness:.8});screw.rotation.x=Math.PI/2;}
 const gateLabels=new THREE.Group();zoneAnnotations[2].add(gateLabels);const gateResultLabels=new THREE.Group();zoneAnnotations[3].add(gateResultLabels);
 function gateShape(operation){const shape=new THREE.Shape();if(operation==='AND'){shape.moveTo(-.86,-.55);shape.lineTo(-.86,.55);shape.lineTo(.05,.55);shape.absarc(.05,0,.55,Math.PI/2,-Math.PI/2,true);shape.lineTo(-.86,-.55);}else{shape.moveTo(-.90,-.55);shape.quadraticCurveTo(-.62,0,-.90,.55);shape.quadraticCurveTo(.33,.55,1.08,0);shape.quadraticCurveTo(.33,-.55,-.90,-.55);}return shape;}
 const gateSettings=[['xor1','XOR',3,3.85],['and1','AND',3,1.68],['xor2','XOR',7.6,3.85],['and2','AND',7.6,1.68],['or','OR',11.25,1.68]];
 const gateRecords={},pinNamesByGate={xor1:['a','b'],and1:['a','b'],xor2:['x','cin'],and2:['x','cin'],or:['ab','cx']};
 for(const [id,operation,x,y] of gateSettings){const group=new THREE.Group();group.position.set(x,y,0);adderGroup.add(group);const body=mesh(group,own(new THREE.ExtrudeGeometry(gateShape(operation),{depth:.30,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.045,bevelThickness:.045,curveSegments:18})),mat(operation==='XOR'?0x8e80b3:operation==='AND'?0x658fa4:0x98a986));
  if(operation==='XOR'){const arc=new THREE.QuadraticBezierCurve3(new THREE.Vector3(-1.06,-.55,.34),new THREE.Vector3(-.63,0,.34),new THREE.Vector3(-1.06,.55,.34));tube(group,arc,.025,0xd6cdf0);}
  const ports={in1:new THREE.Vector3(x-1.17,y+.28,.35),in2:new THREE.Vector3(x-1.17,y-.28,.35),out:new THREE.Vector3(x+1.17,y,.35)},pads={};
  for(const [key,p] of Object.entries(ports)){pads[key]=ball(adderGroup,p.toArray(),.088,C.pending,{emissive:C.pending,emissiveIntensity:.2});terminals[`${id}.${key}`]=p;}pinNamesByGate[id].forEach((name,i)=>terminals[`${id}.${name}`]=ports[i===0?'in1':'in2']);
  for(const py of [.28,-.28])rod(group,[-1.17,py,.35],[-.65,py,.35],.034,C.metal);rod(group,[.50,0,.35],[1.17,0,.35],.034,C.metal);
  const caption=label(gateLabels,operation,[x,y,.45],1.33,{bg:false}),valueCaption=label(gateLabels,'',[x+1.34,y+.64,.55],1.8);const record={id,operation,group,body,ports,pads,caption,valueCaption,value:null};gates.push(record);gateRecords[id]=record;logicalNodes[id]=pads.out;
  inspect(body,operation==='XOR'?'XOR: salida 1 cuando las dos entradas son distintas. Este bloque funcional contiene varios transistores; no es un único transistor.':operation==='AND'?'AND: salida 1 solamente si ambas entradas son 1. Bloque lógico ideal, no diseño de fabricación.':'OR: salida 1 si al menos una de sus dos entradas es 1. Combina los dos términos del acarreo.',operation==='XOR'?'XOR: output 1 when its two inputs differ. This functional block contains several transistors; it is not a single transistor.':operation==='AND'?'AND: output 1 only when both inputs are 1. Ideal logic block, not a fabrication design.':'OR: output 1 if at least one of its two inputs is 1. It combines the two carry terms.');
 }
 const inputs={},outputs={},inputCaptions={},outputCaptions={};
 for(const [id,y,name] of [['a',4.63,'A'],['b',3.01,'B'],['cin',.94,'Cin']]){const group=new THREE.Group();group.position.set(.02,y,.35);adderGroup.add(group);box(group,[0,0,0],[.62,.48,.26],0x33515d);const pad=ball(group,[0,0,.17],.14,C.pending,{emissive:C.pending,emissiveIntensity:.4});terminals[id]=new THREE.Vector3(.02,y,.52);inputs[id]={group,pad,value:null};logicalNodes[id]=pad;inputCaptions[id]=label(gateLabels,`${name} = —`,[.02,y+.47,.65],1.40);inspect(pad,`${name}: entrada directa del sumador. El color azul representa 0 y el verde 1; el gris significa pendiente.`,`${name}: direct adder input. Blue means 0 and green means 1; grey means pending.`);}
 for(const [id,y,name] of [['sum',3.85,'Sum'],['cout',1.68,'Cout']]){const group=new THREE.Group();group.position.set(14.27,y,.35);adderGroup.add(group);box(group,[0,0,0],[.87,.67,.28],0x365563);const pad=ball(group,[0,0,.22],.215,C.pending,{emissive:C.pending,emissiveIntensity:.32});terminals[id]=new THREE.Vector3(14.27,y,.57);outputs[id]={group,pad,value:null};logicalNodes[id]=pad;outputCaptions[id]=label(gateResultLabels,`${name} = —`,[14.27,y+.60,.75],2.1);inspect(pad,id==='sum'?'Sum: bit de suma. Aparece cuando llega la señal del segundo XOR; un 0 válido sigue siendo una señal.':'Cout: acarreo de salida. Aparece cuando llega la señal de OR. El resultado completo espera ambas salidas.',id==='sum'?'Sum: sum bit. It appears when the second XOR signal arrives; a valid 0 is still a signal.':'Cout: carry out. It appears when the OR signal arrives. The complete result waits for both outputs.');}
 // Junction dots are real fan-outs; route depths keep other crossings electrically separate.
 const junctions=[];for(const [p,node] of [[[1.02,4.63,.52],'a'],[[.83,3.01,.52],'b'],[[5.33,3.85,.35],'xor1'],[[5.9,.94,.52],'cin']]){const dot=ball(adderGroup,p,.071,C.pending);dot.userData.node=node;junctions.push(dot);}
 const specifications=[
  ['a-xor1','a','xor1','in1',[[1.02,4.63,.52],[1.38,4.63,.52],[1.38,4.13,.35]]],
  ['b-xor1','b','xor1','in2',[[.83,3.01,.52],[1.32,3.01,.52],[1.32,3.57,.35]]],
  ['a-and1','a','and1','in1',[[1.02,4.63,.52],[1.02,4.63,1.02],[1.02,1.96,1.02],[1.52,1.96,.35]]],
  ['b-and1','b','and1','in2',[[.83,3.01,.52],[.83,3.01,.74],[.83,1.40,.74],[1.52,1.40,.35]]],
  ['xor1-xor2','xor1','xor2','in1',[[5.33,3.85,.35],[5.75,3.85,.35],[5.75,4.13,.35]]],
  ['cin-xor2','cin','xor2','in2',[[5.9,.94,.52],[5.9,3.57,.83],[6.11,3.57,.35]]],
  ['xor1-and2','xor1','and2','in1',[[5.33,3.85,.35],[5.33,3.85,1.11],[5.33,1.96,1.11],[6.09,1.96,.35]]],
  ['cin-and2','cin','and2','in2',[[5.9,.94,.52],[6.10,.94,.52],[6.10,1.40,.35]]],
  ['and1-or','and1','or','in1',[[4.65,1.68,.35],[4.65,1.10,1.25],[9.68,1.10,1.25],[9.68,1.96,.35]]],
  ['and2-or','and2','or','in2',[[9.29,1.68,.35],[9.56,1.68,.74],[9.56,1.40,.35]]],
  ['xor2-sum','xor2','sum',null,[[10.2,3.85,.35],[12.35,3.85,.35]]],
  ['or-cout','or','cout',null,[[13.1,1.68,.35]]]
 ];
 for(const [id,from,to,pin,middle] of specifications){const start=terminals[`${from}.out`]||terminals[from],end=terminals[pin?`${to}.${pin}`:to],points=[start.toArray(),...middle,end.toArray()],wire=tube(adderGroup,points,.040,C.pending,{roughness:.4,metalness:.48});const packet=ball(adderGroup,start.toArray(),.103,C.pending,{emissive:C.pending,emissiveIntensity:.8});packet.visible=false;
  const segments=[],geo=own(new THREE.CylinderGeometry(.043,.043,1,8)),material=mat(C.pending,{emissive:C.pending,emissiveIntensity:.35});for(let i=0;i<32;i++){const p=wire.curve.getPoint(i/32),q=wire.curve.getPoint((i+1)/32),segment=mesh(adderGroup,geo,material,p.clone().add(q).multiplyScalar(.5).toArray());segment.scale.y=p.distanceTo(q);segment.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());segment.visible=false;segments.push(segment);}
  const route={id,from,to,pin:pin?pinNamesByGate[to][pin==='in1'?0:1]:to,port:pin,sourceTerminal:terminals[`${from}.out`]?`${from}.out`:from,targetTerminal:pin?`${to}.${pin}`:to,curve:wire.curve,path:wire.mesh,packet,packets:[packet],segments,material,level:null,active:false,arrived:false};routes.push(route);inspect(wire.mesh,`Conexión ${from} → ${to}. El pulso indica propagación pedagógica de un nivel lógico, no un electrón ni una latencia real.`,`Connection ${from} → ${to}. The pulse indicates teaching-scale propagation of a logic level, not an electron or real latency.`);
 }
 const logicCaption=label(zoneAnnotations[2],t('DOS XOR + DOS AND + UNA OR','TWO XOR + TWO AND + ONE OR'),[7.5,5.28,.4],8.8,{height:72}),logicNote=label(zoneAnnotations[2],t('Azul: 0 · verde: 1 · gris: pendiente','Blue: 0 · green: 1 · grey: pending'),[7.5,.58,3.10],8.1,{height:72,depthTest:false});const resultCaption=label(zoneAnnotations[3],'',[12.85,5.45,.6],4.8),resultNote=label(zoneAnnotations[3],'',[12.85,1.05,3.10],4.2,{height:128,depthTest:false});
 const overviewLabelsGroup=new THREE.Group();scene.add(overviewLabelsGroup);for(const [words,x,width] of [[t('CAMPO Y CANAL','FIELD + CHANNEL'),-12,5.2],[t('INVERSOR CMOS','CMOS INVERTER'),-4.5,5.1],[t('PUERTAS CONECTADAS','CONNECTED GATES'),5.2,6.2],[t('SUMA Y ACARREO','SUM + CARRY'),13,5.0]])label(overviewLabelsGroup,words,[x,.7,5.2],width,{depthTest:false});
 const standsGroup=new THREE.Group();scene.add(standsGroup);for(let i=0;i<4;i++){const x=[-12,-4.5,5.2,13][i],z=6.4;box(standsGroup,[x,.52,z],[1.7,1.04,.75],0x294955);box(standsGroup,[x,1.09,z],[1.9,.09,.95],0x9da9af);const button=box(standsGroup,[x,1.23,z+.12],[.85,.20,.5],0xffd991,{emissive:0xdfb876,emissiveIntensity:.45});button.userData.action=i;targets.push(button);stands.push(button);label(standsGroup,`${i+1} · ${(es?['TRANSISTOR','INVERSOR','CIRCUITO','RESULTADO']:['TRANSISTOR','INVERTER','CIRCUIT','RESULT'])[i]}`,[x,.67,z+.40],1.65);label(standsGroup,t('▶ ESCUCHAR','▶ LISTEN'),[x,1.34,z+.20],.86);}
 let lastState;
 const paint=(m,value,intensity=.30)=>{const color=levelColor(value);m.material.color.setHex(color);if(m.material.emissive){m.material.emissive.setHex(color);m.material.emissiveIntensity=value===null?.06:intensity;}};
 function update(model,time=0,phase=0,whole=false,immersive=false){
  const s=sampleChip(model.trace,Number.isFinite(time)?time:0);lastState=s;const signalMap=new Map(s.signals.map(signal=>[signal.id,signal]));
  paint(mos.gateInput,s.mos.gateValue);paint(mos.channel,s.mos.channelOn?1:null,.55);mos.field.forEach(arrow=>arrow.visible=s.mos.channelOn);channelCaption.set((s.mos.channelOn?t('A = 1 · campo → canal habilitado','A = 1 · field → enabled channel'):t('A = 0 · canal cerrado','A = 0 · channel off'))+'\n'+t('0 V / +VDS: sesgo ilustrativo','0 V / +VDS: illustrative bias'));
  pm.on=s.inverter.pOn;nm.on=s.inverter.nOn;paint(pm.channel,pm.on?1:null,.45);paint(nm.channel,nm.on?0:null,.45);pullup.mesh.visible=pm.on;pulldown.mesh.visible=nm.on;gateWires.forEach(wire=>paint(wire,s.inputs.a));paint(inverterOutput,s.inverter.output,.55);invInputCaption.set(`A = ${s.inputs.a}`);invOutputCaption.set(`NOT A = ${s.inverter.output}`);
  for(const [id,record] of Object.entries(inputs)){record.value=s.inputs[id];paint(record.pad,record.value,.5);inputCaptions[id].set(`${id==='cin'?'Cin':id.toUpperCase()} = ${record.value}`);}
  routes.forEach(route=>{const signal=signalMap.get(route.id);route.level=signal?.value??null;route.active=!!signal?.active&&s.active!==false;route.arrived=!!signal?.arrived;route.packet.visible=route.active;paint(route.packet,route.level,.9);route.material.color.setHex(levelColor(route.level));route.material.emissive.setHex(levelColor(route.level));if(route.active)route.packet.position.copy(route.curve.getPoint(Math.max(0,Math.min(1,signal.progress))));route.segments.forEach((segment,i)=>segment.visible=route.arrived||route.active&&i/32<signal.progress);route.path.material.color.setHex(route.arrived?levelColor(route.level):C.pending);route.path.material.emissive.setHex(route.arrived?levelColor(route.level):C.pending);route.path.material.emissiveIntensity=route.arrived?.18:.02;});
  gates.forEach(record=>{const gate=s.gates.find(g=>g.id===record.id);record.value=gate?.value??s.nodes[record.id]??null;record.status=gate?.status;record.progress=gate?.progress??0;const processing=gate?.status==='processing';record.body.material.emissive.setHex(processing?C.gate:levelColor(record.value));record.body.material.emissiveIntensity=processing?.14+.08*Math.sin(record.progress*4*Math.PI):record.value===null?.025:.25;paint(record.pads.out,record.value);const incoming=routes.filter(r=>r.to===record.id);for(const key of ['in1','in2']){const route=incoming.find(r=>r.port===key)||incoming[key==='in1'?0:1];paint(record.pads[key],route?.arrived?route.level:null);}record.valueCaption.set(`${({xor1:'X',and1:'AB',xor2:'S',and2:'Cin·X',or:'C'})[record.id]} = ${record.value===null?'—':record.value}`);});
  for(const [id,record] of Object.entries(outputs)){record.value=s.nodes[id]??null;paint(record.pad,record.value,.8);outputCaptions[id].set(`${id==='sum'?'Sum':'Cout'} = ${record.value===null?'—':record.value}`);}junctions.forEach(dot=>paint(dot,typeof s.inputs[dot.userData.node]==='number'?s.inputs[dot.userData.node]:s.nodes[dot.userData.node]??null));
  resultCaption.set(s.result.ready?`${s.inputs.a} + ${s.inputs.b} + ${s.inputs.cin} = ${s.result.binary}₂`:t('Esperando ambas salidas','Waiting for both outputs'));resultNote.set(s.result.ready?`Sum ${s.result.sum} + 2 × Cout ${s.result.cout}\n${t('Valor decimal: ','Decimal value: ')}${s.result.decimal}`:t('Sum y Cout se revelan al llegar\nUn 0 azul también es una señal','Sum and Cout reveal on arrival\nA blue 0 is also a signal'));
  overviewLabelsGroup.visible=whole;zoneAnnotations.forEach((group,i)=>group.visible=!whole&&i===phase);gateLabels.visible=!whole&&(phase===2||phase===3);gates.forEach(record=>{record.caption.m.visible=phase===2||phase===3&&record.id==='or';record.valueCaption.m.visible=phase===2;});Object.values(inputCaptions).forEach(caption=>caption.m.visible=phase===2);if(phase===3&&!whole){zoneAnnotations[2].visible=true;logicCaption.m.visible=false;logicNote.m.visible=false;}else{logicCaption.m.visible=true;logicNote.m.visible=true;}standsGroup.visible=immersive;stands.forEach((button,i)=>button.material.emissiveIntensity=i===phase?1:.16);
 }
 return {scene,resources,targets,stands,standsGroup,routes,gates,gateRecords,terminals,logicalNodes,inputs,outputs,junctions,mos,inverter,adder:{group:adderGroup,board:adderBoard},parts:{table,substrate,source,drain,oxide,gate,channel,pm,nm},annotations,zoneAnnotations,overviewLabelsGroup,outlines:[],focus:MICROCHIP_FOCUS,bounds:MICROCHIP_BOUNDS,update,get state(){return lastState;}};
}

export function microchipFraming(phase,orbit={},aspect=1,fov=46){
 const whole=orbit.whole===true,index=whole?4:Math.max(0,Math.min(3,phase)),center=new THREE.Vector3(...(whole?[0,2.25,0]:MICROCHIP_FOCUS[index])),yaw=orbit.yaw??microchipOverview.yaw,pitch=orbit.pitch??microchipOverview.pitch;
 const direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch));
 const bounds=MICROCHIP_BOUNDS[index],tan=Math.tan(fov*Math.PI/360);let distance=4;for(const x of [bounds[0],bounds[3]])for(const y of [bounds[1],bounds[4]])for(const z of [bounds[2],bounds[5]]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}distance*=1.12*(orbit.distance??microchipOverview.distance)/microchipOverview.distance;return {center,distance,direction,bounds};
}
const visible=object=>{for(let o=object;o;o=o.parent)if(!o.visible)return false;return true;};
export function createMicrochipWorld(options,legacyLesson,legacyEs,legacyInspect){
 const objectAPI=!!options?.container,host=objectAPI?options.container:options,lesson=objectAPI?options.lesson:legacyLesson,es=objectAPI?options.lang!=='en':legacyEs,onInspect=(objectAPI?options.onInspect:legacyInspect)||(()=>{}),initialMode=objectAPI?options.mode||'web':'web';
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);renderer.domElement.tabIndex=0;
 const built=createMicrochipScene(lesson,es),camera=new THREE.PerspectiveCamera(46,1,.1,150),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let model,phase=0,elapsed=0;
 function resize(){renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/Math.max(1,host.clientHeight);camera.fov=camera.aspect<1?65:46;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function nearest(player){let best=null,distance=5.8;built.stands.forEach((stand,i)=>{const p=stand.getWorldPosition(new THREE.Vector3()),d=Math.hypot(player.x-p.x,player.z-p.z);if(d<distance){best=i;distance=d;}});return best;}
 function hit(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);return ray.intersectObjects(built.targets.filter(visible))[0];}
 return {canvas:renderer.domElement,update(s,i){model=s;phase=i;},render(player,dt,animation,orbit=microchipOverview,mode=initialMode,time){
  if(Number.isFinite(time))elapsed=time;else if(model&&Number.isFinite(model.t))elapsed=model.t;if(model)built.update(model,elapsed,phase,mode==='web'&&orbit.whole===true,mode==='immersive');
  if(mode==='immersive'){camera.position.set(player.x,1.65,player.z);camera.rotation.set(player.pitch,player.yaw,0,'YXZ');}else{const framing=microchipFraming(phase,orbit,camera.aspect,camera.fov);camera.position.copy(framing.center).addScaledVector(framing.direction,framing.distance);camera.lookAt(framing.center);}renderer.render(built.scene,camera);
 },inspect(x,y){const h=hit(x,y);if(h)onInspect(h.object.userData.action===undefined?h.object.userData.info:{chapter:h.object.userData.action});},nearest,activate(){const r=renderer.domElement.getBoundingClientRect(),h=hit(r.left+r.width/2,r.top+r.height/2),chapter=h?.object.userData.action!==undefined&&h.distance<8?h.object.userData.action:nearest({x:camera.position.x,z:camera.position.z});if(chapter!==null)onInspect({chapter});},dispose(){observer.disconnect();built.resources.forEach(resource=>resource.dispose());renderer.dispose();},poseAt:microchipPoseAt};
}
