import {MIN_K,MAX_K,HUMAN_POWER,createState,tick,snapshot,powerAt,multiplier,yearsAtGrowth} from './model.js';
import {createWorld,COLLECTOR_COUNT} from './world.js';
import {advanceScene} from './motion.js';
import {NarrationPlayer} from '../narrator.js';
import {VOICES} from './voices.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),fmt=(v,d=2)=>new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:d}).format(v);
const sci=x=>{const e=Math.floor(Math.log10(x)),m=x/10**e;return fmt(m)+' × 10'+[...String(e)].map(n=>'⁰¹²³⁴⁵⁶⁷⁸⁹'[n]??'⁻').join('');};
const stages=[
 {k:MIN_K,name:t('Referencia humana','Human reference'),scope:t('Un mundo que empieza','A world getting started'),text:t('Usamos 20 TW redondeados como referencia didáctica. Dan K ≈ 0,73. Eso NO significa disponer del 73 % de la potencia del tipo I: aquí es solo un 0,2 %.','We use a rounded 20 TW as a teaching reference. That gives K ≈ 0.73. This does NOT mean having 73% of Type I power: here it is only 0.2%.'),note:t('Referencia elegida, no un dato en tiempo real.','Chosen reference, not a live statistic.')},
 {k:1,name:t('Tipo I · planetaria','Type I · planetary'),scope:t('La escala de un planeta','The scale of a planet'),text:t('El primer umbral de esta convención es 10¹⁶ W. Imagina redes de generación y distribución a escala planetaria. El número no exige una tecnología concreta ni implica controlar el clima.','The first threshold in this convention is 10¹⁶ W. Imagine generation and distribution networks at planetary scale. The number requires no specific technology and does not imply control over the weather.'),note:t('No equivale exactamente a toda la luz que llega a la Tierra.','It is not exactly all sunlight reaching Earth.')},
 {k:2,name:t('Tipo II · estelar','Type II · stellar'),scope:t('Una estrella como referencia','A star as a reference'),text:t('El umbral continuo es 10²⁶ W. Un enjambre de colectores ilustra una posible vía. Nuestro Sol emite unas 3,828 veces esa potencia: el umbral es una normalización, no una estrella exacta.','The continuous threshold is 10²⁶ W. A collector swarm illustrates one possible route. Our Sun emits about 3.828 times that power: the threshold is a normalization, not an exact star.'),note:t('Los colectores del dibujo no son un proyecto de ingeniería.','The depicted collectors are not an engineering plan.')},
 {k:3,name:t('Tipo III · galáctica','Type III · galactic'),scope:t('Muchísimos sistemas estelares','Vast numbers of stellar systems'),text:t('El umbral continuo es 10³⁶ W: unos 2.600 millones de luminosidades solares. La galaxia representa sistemas distribuidos; no una sola máquina ni un control instantáneo de toda la galaxia.','The continuous threshold is 10³⁶ W: about 2.6 billion solar luminosities. The galaxy represents distributed systems, not one machine or instantaneous control of an entire galaxy.'),note:t('Es una clasificación hipotética, no una civilización observada en esta escena.','This is a hypothetical classification, not a civilization observed in this scene.')}
];
let state=createState(),world,player,speed=1,chartMode='log',last=performance.now(),uiClock=0,inspect=false,voiceLanguage=es?'es':'en',tour=false;
// This notebook explicitly presents moving scenes; the separate control pauses all motion.
let sceneMotion=0,sceneMoving=true;
const assetState={earth:'loading',satellite:'loading'};
document.title=t('Kardashev — Escalas de civilización','Kardashev — Scales of civilization');
$('app').innerHTML=`<nav class="nav"><a href="../index.html">← Atlas</a><a href="../dyson/index.html">${t('Explorar Dyson','Explore Dyson')} ↗</a><span><a href="${es?'../../kardashev/index.html':'./index.html'}" lang="en">EN</a> / <a href="${es?'./index.html':'../es/kardashev/index.html'}" lang="es">ES</a></span></nav>
<header><span class="eyebrow">NOTEBOOK 07 · ${t('ESCALAS DE CIVILIZACIÓN','SCALES OF CIVILIZATION')}</span><h1>${t('Un planeta. Una estrella. <br>Una galaxia.','A planet. A star. <br>A galaxy.')}</h1><p>${t('De nuestra Tierra a una galaxia. Mira, escucha y descubre la enorme diferencia entre cada nivel.','From our Earth to a galaxy. Watch, listen and discover the enormous distance between each level.')}</p></header>
<nav class="chapter-nav" aria-label="${t('Escalas de civilización','Civilization scales')}"><div class="stages">${stages.map((s,i)=>`<button data-stage="${i}"><span>${i===0?t('≈ 0,73','≈ 0.73'):i===1?'I':i===2?'II':'III'}</span><div><b>${s.name}</b><small>${sci(powerAt(s.k))} W</small></div></button>`).join('')}</div></nav><section class="dashboard"><article><span>${t('Índice Kardashev–Sagan','Kardashev–Sagan index')}</span><strong id="k-value"></strong><small>${t('Escala continua · no es un porcentaje','Continuous scale · not a percentage')}</small></article><article><span>${t('Potencia utilizada','Power used')}</span><strong id="power"></strong><small id="human-multiple"></small></article><article><span>${t('Hasta el siguiente tipo','To the next type')}</span><strong id="gap"></strong><small id="gap-note"></small></article></section>
<div class="transport"><button id="play" class="primary">▶ ${t('Reproducir recorrido','Play journey')}</button><button id="reset" aria-label="${t('Reiniciar','Reset')}">↺</button><label>${t('Velocidad','Speed')} <select id="speed"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label><button id="decade">${t('+0,1 K = ×10','+0.1 K = ×10')}</button><button id="motion" aria-pressed="true"></button><span id="play-state"></span></div>
<div class="layout"><div class="visual-stack"><section class="stage"><div class="scene-top"><span class="eyebrow" id="view-label"></span><span>${t('VISTA 3D · ESCALAS ADAPTADAS','3D VIEW · SCALES ADAPTED')}</span></div><div id="space" role="img" tabindex="0" aria-label="${t('Planeta, colectores alrededor de una estrella y galaxia. Arrastra o usa las flechas para girar.','Planet, collectors around a star and galaxy. Drag or use arrow keys to rotate.')}"></div><p id="loading">${t('Preparando las escalas…','Preparing the scales…')}</p><div class="view-controls"><button id="fit">${t('Centrar','Center')}</button><button id="minus" aria-label="${t('Alejar','Zoom out')}">−</button><button id="plus" aria-label="${t('Acercar','Zoom in')}">+</button></div><div class="scene-bottom"><span id="scene-note"></span></div><div id="parts" class="parts" hidden>${[['all',t('Todo','All')],['panels',t('Paneles solares','Solar arrays')],['antenna',t('Antena','Antenna')],['body',t('Cuerpo','Body')]].map(([id,label])=>`<button data-part="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div></section><section class="voice-panel" aria-label="${t('Guía de voz','Voice guide')}"><div class="voice-heading"><span class="voice-icon" aria-hidden="true">◖))</span><div><strong id="voice-title">${t('Escucha lo que estás viendo','Listen to what you are seeing')}</strong><span id="voice-status" role="status">${t('Voz MiniMax · con transcripción','MiniMax voice · transcript available')}</span></div></div><div class="voice-controls"><button id="listen" class="primary">▶ ${t('Escuchar escena','Listen to scene')}</button><button id="voice-tour">${t('Recorrido completo','Full guided tour')}</button><button id="voice-next" hidden>${t('Siguiente →','Next →')}</button><button id="voice-stop" aria-label="${t('Detener voz','Stop voice')}" hidden>■</button><label class="voice-language">${t('Voz','Voice')} <select id="voice-language" aria-label="${t('Idioma de la narración','Narration language')}"><option value="es" ${es?'selected':''}>Español</option><option value="en" ${!es?'selected':''}>English</option></select></label></div><details class="transcript"><summary>${t('Leer explicación','Read explanation')}</summary><p id="transcript"></p></details></section></div><aside><span class="eyebrow">${t('QUÉ ESTÁS VIENDO','WHAT YOU ARE SEEING')}</span><div class="lesson"><h2 id="lesson-title"></h2><p id="lesson-text"></p><small id="lesson-note"></small></div><ul class="scene-legend" id="scene-legend"></ul><div class="inspect-entry"><button id="inspect">${t('Inspeccionar satélite real','Inspect real spacecraft')} ↗</button><p>${t('MarCO · modelo 3D de NASA / VTAD','MarCO · NASA / VTAD 3D model')}</p></div></aside></div>
<section class="scale-control"><label for="scale">${t('Desliza por la escala continua','Slide along the continuous scale')} <output id="scale-output"></output></label><input type="range" id="scale" min="${MIN_K}" max="3" step="any" value="${MIN_K}"><div class="scale-labels"><span>${t('≈ 0,73','≈ 0.73')}</span><span>1</span><span>2</span><span>3</span></div><p>${t('La reproducción recorre magnitudes, no años. Cada +0,1 K multiplica la potencia por 10; cada +1 K, por 10.000.000.000.','Playback travels through magnitudes, not years. Each +0.1 K multiplies power by 10; each +1 K, by 10,000,000,000.')}</p></section>
<section class="comparison"><div><span class="eyebrow">${t('EL SALTO QUE CUESTA IMAGINAR','THE HARD-TO-IMAGINE JUMP')}</span><h2>${t('Diez mil millones de veces.<br>Por cada tipo.','Ten billion times.<br>For every type.')}</h2><p>${t('En una gráfica logarítmica los saltos iguales representan multiplicaciones iguales. Cambia a la escala lineal: los niveles bajos parecen desaparecer junto al tipo III.','On a logarithmic chart, equal jumps represent equal multipliers. Switch to a linear scale: the lower levels seem to disappear beside Type III.')}</p><div class="chart-buttons"><button id="log" aria-pressed="true">${t('Logarítmica','Logarithmic')}</button><button id="linear" aria-pressed="false">${t('Lineal','Linear')}</button></div></div><div><svg id="chart" viewBox="0 0 620 220" role="img"></svg><p class="chart-note" id="chart-note"></p></div></section>
<section class="experiment"><div><span class="eyebrow">${t('EXPERIMENTO MATEMÁTICO','MATHEMATICAL EXPERIMENT')}</span><h2>${t('¿Y si la potencia creciera cada año?','What if power grew every year?')}</h2><p>${t('Mantén una tasa constante e imagina el salto desde el punto seleccionado hasta el siguiente tipo. Es interés compuesto, sin límites de recursos ni construcción.','Hold a growth rate constant and imagine the jump from the selected point to the next type. This is compound growth, without resource or construction limits.')}</p></div><div><label for="growth">${t('Crecimiento anual supuesto','Assumed annual growth')} <output id="growth-label">2 %</output></label><input id="growth" type="range" min="0" max="10" step=".5" value="2"><strong id="years"></strong><small>${t('Resultado condicionado a la tasa · NO es una fecha de llegada','Conditional on the rate · NOT an arrival date')}</small></div></section>
<details class="assumptions"><summary>${t('1964 frente a la escala continua · fuentes y límites','1964 versus the continuous scale · sources and limits')}</summary><p>${t('Kardashev propuso tres tipos. Su tipo I era cercano a la Tierra de su época; II y III se referían a potencias del orden de una estrella y una galaxia (aproximadamente 4×10²⁶ y 4×10³⁷ W). No eran los tres umbrales equidistantes de este control.','Kardashev proposed three types. His Type I was close to Earth in his era; II and III referred to power on the order of a star and a galaxy (approximately 4×10²⁶ and 4×10³⁷ W). They were not the three equally spaced thresholds in this control.')} <a href="https://articles.adsabs.harvard.edu/pdf/1964SvA.....8..217K" target="_blank" rel="noopener">Kardashev, 1964 ↗</a> · <a href="https://doi.org/10.1088/0004-637X/792/1/27" target="_blank" rel="noopener">Wright et al., 2014 ↗</a></p><p>${t('Aquí usamos la convención continua habitual: K = (log₁₀(P en W) − 6) / 10. Así, I = 10¹⁶ W, II = 10²⁶ W y III = 10³⁶ W. El índice mide potencia, no energía acumulada: 1 W = 1 J/s. La referencia humana de 20 TW es redondeada y editable mediante el índice, no una medición de hoy.','Here we use the common continuous convention: K = (log₁₀(P in W) − 6) / 10. Thus I = 10¹⁶ W, II = 10²⁶ W and III = 10³⁶ W. The index measures power, not stored energy: 1 W = 1 J/s. The 20 TW human reference is rounded and can be explored using the index; it is not a measurement for today.')} <a href="https://doi.org/10.1038/s41598-023-38351-y" target="_blank" rel="noopener">${t('Fórmula y contexto: Zhang et al., 2023','Formula and context: Zhang et al., 2023')} ↗</a></p><p>${t('Las luces y colectores ilustran el cambio de ámbito; su cantidad no representa una fracción física de energía. La luminosidad solar nominal usada para comparar es 3,828×10²⁶ W. Los niveles IV y V no pertenecen a la clasificación original y quedan fuera de esta simulación. La escala no mide bienestar, justicia, inteligencia ni eficiencia. Ninguna tasa de crecimiento garantiza alcanzar otro tipo.','Lights and collectors illustrate the change in scope; their count does not represent a physical energy fraction. The nominal solar luminosity used for comparison is 3.828×10²⁶ W. Types IV and V are not part of the original classification and are outside this simulation. The scale does not measure well-being, justice, intelligence or efficiency. No growth rate guarantees reaching another type.')}</p></details>
<section class="asset-credits"><h2>${t('Imágenes y modelos reales','Real imagery and models')}</h2><p><a href="https://science.nasa.gov/resource/marco-3d-model/" target="_blank" rel="noopener">MarCO · NASA / VTAD ↗</a> · <a href="https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/base-map/" target="_blank" rel="noopener">Blue Marble · NASA Earth Observatory ↗</a></p><p>${t('MarCO se muestra ampliado y en una posición ilustrativa: su misión fue hacia Marte. Los colectores de Dyson y la galaxia son visualizaciones conceptuales, no modelos de misiones reales. La textura de la Tierra es un mosaico de diciembre de 2004, no una imagen en directo.','MarCO is enlarged and placed illustratively: its mission travelled toward Mars. Dyson collectors and the galaxy are conceptual visualizations, not real mission models. Earth uses a December 2004 mosaic, not live imagery.')}</p></section><footer>Atlas · Kardashev · <a href="../dyson/index.html">${t('Siguiente exploración: construir un enjambre de Dyson','Next exploration: building a Dyson swarm')} ↗</a></footer>`;
try{world=createWorld($('space'),{onAsset(kind,ok){assetState[kind]=ok?'ready':'error';paint();}});$('loading').hidden=true;}catch(e){$('loading').textContent=t('La vista 3D no está disponible. Los controles, cifras y gráficas siguen funcionando.','The 3D view is unavailable. Controls, figures and charts still work.');console.error(e);}
function chart(v){const left=64,right=600,top=16,bottom=182,x=k=>left+(k-MIN_K)/(MAX_K-MIN_K)*(right-left),y=p=>bottom-(chartMode==='log'?(Math.log10(p)-Math.log10(HUMAN_POWER))/(36-Math.log10(HUMAN_POWER)):p/1e36)*(bottom-top);let svg='';for(const exponent of [16,26,36]){const yy=y(10**exponent);if(chartMode==='linear'&&exponent<36)continue;svg+=`<path d="M${left} ${yy}H${right}" stroke="#324056"/><text x="2" y="${yy+4}" fill="#a6b7cd" font-size="11">10<tspan baseline-shift="super" font-size="8">${exponent}</tspan> W</text>`;}const pts=Array.from({length:161},(_,i)=>{const k=MIN_K+(MAX_K-MIN_K)*i/160;return `${x(k)},${y(powerAt(k))}`;}).join(' ');svg+=`<polyline points="${pts}" fill="none" stroke="#afa6e7" stroke-width="2.5"/><circle cx="${x(v.k)}" cy="${y(v.power)}" r="5" fill="#ffce96"/>`;for(const s of stages)svg+=`<text x="${x(s.k)}" y="211" fill="#a6b7cd" text-anchor="middle" font-size="11">K ${fmt(s.k)}</text>`;$('chart').innerHTML=svg;$('chart').setAttribute('aria-label',t('Potencia frente a índice K. Punto seleccionado: ','Power versus K index. Selected point: ')+sci(v.power)+' W');$('chart-note').textContent=chartMode==='log'?t('Altura: log₁₀ de la potencia. La recta oculta un crecimiento multiplicativo.','Height: log₁₀ of power. The straight line encodes multiplicative growth.'):t('Altura: potencia en W. Tipo II es una diez mil millonésima parte del tipo III.','Height: power in W. Type II is one ten-billionth of Type III.');}
function paint(){const v=snapshot(state),stage=currentScene();const lesson=sceneDescriptions[stage];$('k-value').textContent='K '+fmt(v.k,3);$('power').textContent=sci(v.power)+' W';$('human-multiple').textContent=(v.vsHuman<1e6?fmt(v.vsHuman):sci(v.vsHuman))+' '+(Math.abs(v.vsHuman-1)<1e-8?t('vez la referencia humana','times the human reference'):t('veces la referencia humana','times the human reference'));$('gap').textContent=v.k>=3?t('Tipo III alcanzado','Type III reached'):(v.remainingFactor<=1e10?fmt(v.remainingFactor):sci(v.remainingFactor))+'×';$('gap-note').textContent=v.k>=3?t('Fin del recorrido ilustrativo','End of the illustrative journey'):t('Potencia necesaria para el tipo ','Power needed for Type ')+['','I','II','III'][v.next];$('scale').value=v.k;$('scale-output').textContent='K '+fmt(v.k,3);$('play').textContent=state.playing?'Ⅱ '+t('Pausar','Pause'):v.k>=3?'↺ '+t('Repetir animación','Replay animation'):'▶ '+t('Animar crecimiento','Animate growth');$('play-state').textContent=state.playing?t('Recorriendo magnitudes','Exploring magnitudes'):t('En pausa','Paused');$('decade').disabled=v.k>=3;$('view-label').textContent=inspect?'MARCO · NASA / VTAD':{planet:t('ESCALA PLANETARIA','PLANETARY SCALE'),star:t('ESCALA ESTELAR','STELLAR SCALE'),galaxy:t('ESCALA GALÁCTICA','GALACTIC SCALE')}[v.view];$('motion').textContent=sceneMoving?t('Ⅱ Pausar escena','Ⅱ Pause scene'):t('▶ Mover escena','▶ Animate scene');$('motion').setAttribute('aria-pressed',String(sceneMoving));$('scene-note').textContent=inspect?t('Modelo real · arrastra para girar · rueda para acercar','Real model · drag to rotate · scroll to zoom'):(v.view==='star'?COLLECTOR_COUNT.toLocaleString(es?'es-ES':'en-US')+' '+t('colectores al completar el nivel · ','collectors at the full level · '):'')+t('Movimiento acelerado · sin escala física','Accelerated motion · not to physical scale');$('lesson-title').textContent=lesson.scope;$('lesson-text').textContent=lesson.text;$('lesson-note').textContent=lesson.note;document.querySelectorAll('[data-stage]').forEach((b,i)=>b.setAttribute('aria-pressed',String(!inspect&&i===stage)));updateSceneUI(lesson);const rate=+$('growth').value,years=yearsAtGrowth(v.k,v.next,rate);$('growth-label').textContent=fmt(rate)+' %';$('years').textContent=!Number.isFinite(years)?t('Sin crecimiento, no se alcanza','No growth, no arrival'):years===0?t('Umbral alcanzado','Threshold reached'):fmt(years,0)+' '+t('años hipotéticos','hypothetical years');chart(v);world?.render({...state,motion:sceneMotion},v,inspect);}

const sceneDescriptions=[
  {scope:t('Un planeta. Nuestro punto de partida.','One planet. Our starting point.'),text:t('La Tierra real, rodeada de ejemplos de tecnología espacial. Los satélites están ampliados para que puedas reconocer sus piezas.','Our real Earth, surrounded by examples of space technology. Spacecraft are enlarged so you can recognize their components.'),note:t('20 TW es una referencia redondeada. K ≈ 0,73 equivale al 0,2 % del tipo I.','20 TW is a rounded reference. K ≈ 0.73 is 0.2% of Type I.'),legend:[t('Tierra · mosaico Blue Marble de la NASA','Earth · NASA Blue Marble mosaic'),t('MarCO · CubeSat real, posición ilustrativa','MarCO · real CubeSat, illustrative position'),t('Órbitas · guías visuales, no trayectorias de misión','Orbits · visual guides, not mission trajectories')]},
  {scope:t('Tipo I. Energía a escala planetaria.','Type I. Energy at planetary scale.'),text:t('Imagina generación, almacenamiento y distribución conectados a escala de un planeta. Este umbral no exige una tecnología concreta.','Imagine generation, storage and distribution connected at planetary scale. This threshold requires no specific technology.'),note:t('Los satélites ilustran infraestructura; no generan toda la potencia indicada.','The satellites illustrate infrastructure; they do not generate all the indicated power.'),legend:[t('10¹⁶ W · umbral de esta convención','10¹⁶ W · threshold in this convention'),t('500× nuestra referencia humana','500× our human reference'),t('No implica controlar el clima','Does not imply control of the weather')]},
  {scope:t('Tipo II. Aprovechar una estrella.','Type II. Harnessing a star.'),text:t('Un enjambre conceptual de unidades independientes. Observa sus paneles, equipos de servicio y radiadores alrededor de la estrella.','A conceptual swarm of independent units. Look for panels, service equipment and radiators surrounding the star.'),note:t('Diseño hipotético. No son MarCO ni una propuesta de ingeniería validada.','Hypothetical design. These are not MarCO spacecraft or a validated engineering proposal.'),legend:[t('Centro luminoso · estrella','Luminous center · star'),t('Paneles azules · captación de luz','Blue panels · light collection'),t('Piezas claras · radiadores conceptuales','Light surfaces · conceptual radiators')]},
  {scope:t('Tipo III. Muchísimos sistemas estelares.','Type III. Vast numbers of stellar systems.'),text:t('La perspectiva abarca una galaxia. El brillo dorado representa una expansión hipotética de la infraestructura energética por sus sistemas.','The view spans a galaxy. Golden light represents a hypothetical expansion of energy infrastructure across its systems.'),note:t('No representa civilizaciones detectadas ni control instantáneo a distancia.','Does not represent detected civilizations or instantaneous control across space.'),legend:[t('Brazos espirales · sistemas estelares','Spiral arms · stellar systems'),t('Dorado · expansión hipotética','Gold · hypothetical expansion'),t('10³⁶ W · unos 2.600 millones de luminosidades solares','10³⁶ W · about 2.6 billion solar luminosities')]},
  {scope:t('MarCO. Pequeño, pero real.','MarCO. Small, but real.'),text:t('Explora el modelo oficial de un CubeSat de espacio profundo. Selecciona una pieza para iluminarla y ver qué hace.','Explore the official model of a deep-space CubeSat. Select a component to highlight it and see what it does.'),note:t('NASA / VTAD · misión hacia Marte · ampliado, sin escala con la Tierra.','NASA / VTAD · mission to Mars · enlarged, not to scale with Earth.'),legend:[t('Paneles solares · producen electricidad','Solar arrays · generate electricity'),t('Reflectarray · antena plana de comunicaciones','Reflectarray · flat communications antenna'),t('Cuerpo · equipos y sistemas del vehículo','Body · spacecraft equipment and systems')]}
];
const partDescriptions={
  all:t('Gira el modelo y selecciona una pieza.','Rotate the model and select a component.'),
  panels:t('Paneles solares: convierten la luz en electricidad para los equipos del vehículo.','Solar arrays: convert light into electricity for the spacecraft equipment.'),
  antenna:t('Antena reflectarray: superficie desplegable para comunicaciones. No es un panel solar.','Reflectarray antenna: a deployable surface for communications. It is not a solar panel.'),
  body:t('Cuerpo central: aloja los equipos, la electrónica y los sistemas del vehículo.','Central body: houses spacecraft equipment, electronics and systems.')
};
function currentScene(){if(inspect)return 4;const v=snapshot(state);return v.view==='planet'?(v.k<1?0:1):v.view==='star'?2:3;}
function currentClip(){return VOICES[voiceLanguage][currentScene()];}
function updateSceneUI(lesson){
  $('app').classList.toggle('inspecting',inspect);$('parts').hidden=!inspect;
  $('inspect').textContent=inspect?'← '+t('Volver a las escalas','Back to the scales'):t('Inspeccionar satélite real','Inspect real spacecraft')+' ↗';
  $('scene-legend').innerHTML=lesson.legend.map((line,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${line}</li>`).join('');
  if(!player||player.state==='stopped'){$('transcript').textContent=currentClip().text;$('transcript').lang=voiceLanguage;}
  if(world){$('loading').hidden=!inspect||assetState.satellite==='ready';$('loading').textContent=assetState.satellite==='error'?t('No se pudo cargar MarCO. Puedes volver a las escalas.','MarCO could not load. You can return to the scales.'):t('Cargando el modelo de la NASA…','Loading the NASA model…');}
}
function voiceUI(status){
  const active=['playing','loading'].includes(status);
  const labels={playing:t('Escuchando','Listening'),loading:t('Cargando voz…','Loading voice…'),paused:t('Narración en pausa','Narration paused'),finished:t('Explicación terminada','Explanation finished'),blocked:t('Pulsa Escuchar para continuar','Press Listen to continue'),error:t('No se pudo cargar el audio. Puedes reintentar o leer la explicación.','Audio could not load. Retry or read the explanation.'),stopped:t('Voz MiniMax · con transcripción','MiniMax voice · transcript available')};
  $('voice-status').textContent=labels[status]??'';
  $('listen').textContent=active?'Ⅱ '+t('Pausar voz','Pause voice'):['paused','blocked','error'].includes(status)?'▶ '+t('Continuar voz','Resume voice'):'▶ '+t('Escuchar escena','Listen to scene');
  $('voice-stop').hidden=status==='stopped';$('voice-next').hidden=status==='stopped'||!player||player.index+1>=player.items.length;
  if(status==='stopped'){$('voice-title').textContent=t('Escucha lo que estás viendo','Listen to what you are seeing');tour=false;}
}
player=new NarrationPlayer({
  onBegin(){state.playing=false;},
  onClip(item,index,total){
    const i=VOICES[voiceLanguage].findIndex(c=>c.id===item.id);inspect=i===4;if(i<4)state.k=stages[i].k;
    world?.highlight('all');document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.part==='all')));
    $('voice-title').textContent=(total>1?`${index+1} / ${total} · `:'')+item.title;
    $('transcript').textContent=item.text;$('transcript').lang=voiceLanguage;paint();
  },onState(status){voiceUI(status);}
});
function stopVoice(){player.stop();}
function setK(k){stopVoice();inspect=false;world?.highlight('all');state.k=Math.max(MIN_K,Math.min(MAX_K,k));state.playing=false;paint();}
$('listen').onclick=()=>{
  if(['playing','loading','paused','blocked','error'].includes(player.state)){player.toggle();return;}
  tour=false;player.start([currentClip()]);
};
$('voice-tour').onclick=()=>{tour=true;player.start(VOICES[voiceLanguage].slice(0,4));};
$('voice-next').onclick=()=>player.next();
$('voice-stop').onclick=()=>{stopVoice();paint();};
$('voice-language').onchange=e=>{
  const remaining=player.items.slice(player.index).map(c=>c.id),wasActive=['playing','loading'].includes(player.state),wasTour=tour;
  stopVoice();voiceLanguage=e.target.value;
  if(wasActive){tour=wasTour;player.start(remaining.map(id=>VOICES[voiceLanguage].find(c=>c.id===id)));}else paint();
};
$('inspect').onclick=()=>{stopVoice();state.playing=false;inspect=!inspect;world?.highlight('all');paint();};
for(const b of document.querySelectorAll('[data-part]'))b.onclick=()=>{
  const part=b.dataset.part;world?.highlight(part);$('lesson-note').textContent=partDescriptions[part];
  document.querySelectorAll('[data-part]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));
};
$('motion').onclick=()=>{sceneMoving=!sceneMoving;paint();};
$('play').onclick=()=>{stopVoice();inspect=false;if(state.k>=MAX_K)state=createState();state.playing=!state.playing;last=performance.now();paint();};
$('reset').onclick=()=>{stopVoice();inspect=false;state=createState();world?.fit();paint();};
$('scale').oninput=e=>setK(+e.target.value);$('decade').onclick=()=>setK(state.k+.1);
$('speed').onchange=e=>speed=+e.target.value;
for(const b of document.querySelectorAll('[data-stage]'))b.onclick=()=>setK(stages[+b.dataset.stage].k);
$('growth').oninput=paint;
for(const mode of ['log','linear'])$(mode).onclick=()=>{chartMode=mode;$('log').setAttribute('aria-pressed',String(mode==='log'));$('linear').setAttribute('aria-pressed',String(mode==='linear'));paint();};
$('fit').onclick=()=>world?.fit();$('plus').onclick=()=>world?.zoomBy(1.15);$('minus').onclick=()=>world?.zoomBy(1/1.15);
window.addEventListener('pagehide',()=>player.stop());
document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden){state.playing=false;if(player.state==='playing'||player.state==='loading')player.audio?.pause();paint();}});
paint();
function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(!document.hidden){const wasPlaying=state.playing;tick(state,dt*speed);sceneMotion=advanceScene(sceneMotion,dt,sceneMoving);world?.render({...state,motion:sceneMotion},snapshot(state),inspect);uiClock+=dt;if(wasPlaying&&uiClock>.08){paint();uiClock=0;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
