import * as THREE from '../../vendor/three.module.js';
import * as Model from './model.js';
import {createPost} from '../fx/fx.js';
import {MODELS_ROOM,MODELS_LAYOUT,MODELS_STANDS,MODELS_FOCUS,MODELS_BOUNDS,MODELS_WALLS,MODELS_SOLIDS,modelsPoseAt,restoreModelsPose,modelsNearestStand} from './walk.js';
export * from './walk.js';
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a)),chapter=n=>Math.floor(clamp(Number(n),0,11));
const TITLES=[['Familias y caché','Families and cache'],['Decodificador causal','Causal decoder'],['Codificador bidireccional','Bidirectional encoder'],['Fuente y decodificador','Source and decoder'],['Dos expertos, mezcla ponderada','Two experts, weighted mixture'],['Estado recurrente y Jamba','Recurrent state and Jamba'],['Refinar todas las posiciones','Refine every position'],['Predecir representaciones','Predict representations'],['Dos decisiones independientes','Two independent decisions'],['Prefijo frío y prefijo reutilizado','Cold and reused prefix'],['Memoria por token','Memory per token'],['Escribir y leer la caché','Write and read the cache']];
export const modelsOverview={yaw:.10,pitch:.10,distance:10,whole:false};
export function modelsFraming(index=0,orbit={},aspect=1,fov=46){const i=chapter(index),b=orbit.whole?[-23.2,0,-9.7,23.2,4.5,9.7]:MODELS_BOUNDS[i],center=new THREE.Vector3((b[0]+b[3])/2,(b[1]+b[4])/2,(b[2]+b[5])/2),yaw=orbit.yaw??MODELS_LAYOUT[i].yaw+(aspect<1?.06:.10),pitch=orbit.pitch??.10,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let d=2;for(const x of[b[0],b[3]])for(const y of[b[1],b[4]])for(const z of[b[2],b[5]]){const p=new THREE.Vector3(x,y,z).sub(center);d=Math.max(d,p.dot(direction)+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),p.dot(direction)+Math.abs(p.dot(up))/tan);}return {center,direction,distance:d*1.02*(orbit.distance??10)/10,bounds:b};}
export function createModelsScene(es=true){
 const t=(a,b)=>es?a:b,scene=new THREE.Scene(),resources=[],owned=new Set(),targets=[],stands=[],stations=[],own=r=>{if(!owned.has(r)){owned.add(r);resources.push(r);}return r;},release=r=>{if(owned.delete(r)){resources.splice(resources.indexOf(r),1);r.dispose();}};let disposed=false,lastFrame;
 scene.background=new THREE.Color(0x211b14);scene.fog=new THREE.Fog(0x211b14,58,100);
 const cube=own(new THREE.BoxGeometry(1,1,1)),cylinder=own(new THREE.CylinderGeometry(1,1,1,20)),sphere=own(new THREE.SphereGeometry(1,20,12)),plane=own(new THREE.PlaneGeometry(1,1)),materialCache=new Map();
 function mat(color,extra={}){const key=String(color)+JSON.stringify(extra);if(!materialCache.has(key))materialCache.set(key,own(new THREE.MeshStandardMaterial({color,roughness:.60,metalness:.12,...extra})));return materialCache.get(key);}
 const P={board:mat(0x302d26),wood:mat(0x65503b),steel:mat(0xa4977e,{metalness:.65,roughness:.30}),gold:mat(0xe1bb76),mint:mat(0x90cdbd),coral:mat(0xd48e7b),white:mat(0xeee6d6),dim:mat(0x585b58),ink:mat(0x222c31),glass:mat(0xd7e6df,{transparent:true,opacity:.13,depthWrite:false})};
 const mesh=(g,geo,m,p=[0,0,0])=>{const o=new THREE.Mesh(geo,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;g.add(o);return o;};
 function box(g,p,size,m=P.white){const o=mesh(g,cube,m,p);o.scale.set(...size);return o;}
 function ball(g,p,r,m=P.gold){const o=mesh(g,sphere,m,p);o.scale.setScalar(r);return o;}
 function rod(g,a,b,r=.012,m=P.steel){const o=mesh(g,cylinder,m);setRod(o,a,b,r);return o;}
 function setRod(o,a,b,r=.012){a=new THREE.Vector3(...a);b=new THREE.Vector3(...b);const d=b.clone().sub(a),len=d.length();o.position.copy(a).add(b).multiplyScalar(.5);o.scale.set(r,Math.max(.0001,len),r);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),len?d.multiplyScalar(1/len):new THREE.Vector3(0,1,0));o.userData.from=a.toArray();o.userData.to=b.toArray();}
 function label(g,initial,p,width=3.6,maxHeight=.15){const m=new THREE.Mesh(plane,own(new THREE.MeshBasicMaterial({transparent:true,depthWrite:false,toneMapped:false}))),cache=new Map();g.add(m);m.position.set(...p);m.userData.isLabel=true;let last;function set(value){const text=String(value);if(text===last)return;last=text;let entry=cache.get(text);if(!entry){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font='600 48px system-ui';canvas.width=Math.max(90,Math.min(1600,Math.ceil(ctx.measureText(text).width+32)));canvas.height=68;ctx.fillStyle='#26312ff5';ctx.fillRect(0,0,canvas.width,68);ctx.font='600 48px system-ui';ctx.fillStyle='#fff4df';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,canvas.width/2,34,canvas.width-22);const texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;const w=Math.min(width,maxHeight*canvas.width/68);entry={texture,w,h:w*68/canvas.width};cache.set(text,entry);if(cache.size>6){const [key,old]=cache.entries().next().value;cache.delete(key);release(old.texture);}}m.material.map=entry.texture;m.material.needsUpdate=true;m.scale.set(entry.w,entry.h,1);m.userData.text=text;}set(initial);return {m,set,cache};}
 function cell(g,p,width=.36,height=.25,color=P.dim,text=''){const body=box(g,p,[width,height,.12],color),caption=label(g,text,[p[0],p[1],p[2]+.10],width-.03,.12);body.userData.info=text;targets.push(body);return {body,caption};}
 function valueBar(g,x,baseY,width=.25,color=P.mint,captionWidth=.42){const body=box(g,[x,baseY,.25],[width,.001,.20],color);body.userData.info=t('Valor calculado','Calculated value');targets.push(body);return {body,caption:label(g,'',[x,baseY-.16,.39],captionWidth,.10),baseY};}
 function setBar(record,value,height=1,signed=false){const y=Number.isFinite(value)?value:0,h=Math.abs(y)*height;record.body.visible=h>1e-12;record.body.scale.y=h>0?h:.0001;record.body.position.y=record.baseY+(signed&&y<0?-1:1)*h/2;record.body.userData.value=y;record.body.userData.height=h;record.caption.set(fmt(y));}
 const fmt=n=>Number.isFinite(n)?(Math.abs(n)<.0001&&n!==0?n.toExponential(1):n.toFixed(2)):'—',integer=n=>Number.isFinite(n)?Math.round(n).toLocaleString(es?'es-ES':'en-US'):'—',money=n=>Number.isFinite(n)?'$'+n.toFixed(4):'—',vec=a=>'['+(a||[]).map(fmt).join(', ')+']';
 const info=(o,text)=>{o.userData.info=text;targets.push(o);return o;};
 scene.add(new THREE.HemisphereLight(0xfff0d7,0x726348,2.3));const key=new THREE.DirectionalLight(0xffedca,3.1);key.position.set(-9,17,8);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-26,right:26,top:14,bottom:-14,near:.2,far:60});key.shadow.normalBias=.035;own(key.shadow);scene.add(key);const rim=new THREE.DirectionalLight(0xc5e9dd,1.5);rim.position.set(12,9,-12);scene.add(rim);
 const architecture=new THREE.Group();scene.add(architecture);const floor=box(architecture,[0,-.12,0],[48.2,.24,20.2],mat(0x746753,{roughness:.9}));for(let x=-24;x<=24;x+=2.4)box(architecture,[x,.008,0],[.012,.008,20],P.wood);for(let z=-10;z<=10;z+=2)box(architecture,[0,.008,z],[48,.008,.012],P.wood);const walls=MODELS_WALLS.map(b=>box(architecture,[(b[0]+b[2])/2,2.65,(b[1]+b[3])/2],[b[2]-b[0],5.3,b[3]-b[1]],P.wood));for(const z of[-8.9,8.9])for(let x=-18;x<=18;x+=7.2){const light=box(architecture,[x,4.85,z],[3.2,.06,.30],mat(0xf5e0b5,{emissive:0xecc688,emissiveIntensity:.35}));light.castShadow=false;}
 const xToken=i=>(i-3.5)*.40;
 for(const spec of MODELS_LAYOUT){const g=new THREE.Group();g.position.set(spec.x,0,spec.z);g.quaternion.set(0,spec.index<6?0:1,0,spec.index<6?1:0);scene.add(g);const board=box(g,[0,2.10,0],[4.8,4.2,.14],P.board);for(const x of[-2.35,2.35])box(g,[x,2.10,.01],[.075,4.2,.18],P.steel);const title=label(g,String(spec.index+1).padStart(2,'0')+' · '+t(...TITLES[spec.index]),[0,4.04,.20],3.8,.21),scope=label(g,t('Cálculo de ejemplo · no es un modelo entrenado','Toy calculation · not a trained model'),[0,3.78,.18],3.6,.12),content=new THREE.Group();g.add(content);const s={index:spec.index,group:g,board,title,scope,content};stations.push(s);info(board,t('Estación calculada. Los colores y trayectos representan datos, no objetos físicos dentro de un modelo.','Calculated station. Colors and paths represent data, not physical objects inside a model.'));
  const standGroup=new THREE.Group();standGroup.position.set(0,0,2.25);g.add(standGroup);box(standGroup,[0,.05,0],[.48,.10,.40],P.ink);rod(standGroup,[0,.10,0],[0,1.0,0],.055,P.steel);const button=box(standGroup,[0,1.15,0],[.43,.30,.12],P.mint);button.userData.action=spec.index;button.userData.chapter=spec.index;targets.push(button);stands.push(button);label(standGroup,t('ESCUCHAR','LISTEN'),[0,.89,.14],.8,.10);s.stand=button;s.standGroup=standGroup;
  if(spec.index===0){s.intro={cards:Array.from({length:9},(_,i)=>cell(content,[(i%3-1)*1.16,3.15-Math.floor(i/3)*.62,.20],1.04,.42,i<5?P.mint:P.gold,t(...[['Causal','Causal'],['Codificador','Encoder'],['Dos mitades','Two halves'],['Expertos','Experts'],['Estado','State'],['Difusión','Diffusion'],['JEPA','JEPA'],['Decisiones','Decisions'],['Caché','Cache']][i]))),costs:Array.from({length:3},(_,i)=>label(content,'',[(i-1)*1.15,.76,.28],1.08,.14)),note:label(content,t('Entrada nueva · prefijo repetido · salida','Fresh input · reused prefix · output'),[0,1.08,.20],3.4,.14)};}
  if(spec.index===1||spec.index===2){const kind=spec.index===1?'causal':'encoder';s.attention={kind,tokens:Array.from({length:8},(_,i)=>cell(content,[xToken(i),2.96,.25],.37,.27,P.dim,'t'+i)),keys:Array.from({length:8},(_,i)=>label(content,'',[xToken(i),2.58,.28],.42,.11)),scores:Array.from({length:8},(_,i)=>label(content,'',[xToken(i),2.19,.28],.42,.11)),masks:Array.from({length:8},(_,i)=>cell(content,[xToken(i),1.92,.23],.30,.17,P.dim,'×')),values:Array.from({length:8},(_,i)=>label(content,'',[xToken(i),1.63,.28],.42,.10)),bars:Array.from({length:8},(_,i)=>valueBar(content,xToken(i),.80,.29,P.mint)),links:Array.from({length:8},(_,i)=>rod(content,[0,3.15,.20],[xToken(i),2.76,.23],.010,P.gold)),query:label(content,'',[0,3.40,.30],3.35,.14),scoreHeading:label(content,t('Q·K / √2','Q·K / √2'),[0,2.39,.24],2,.11),output:label(content,'',[0,.40,.30],3.35,.15)};s.attention.keys.forEach(c=>c.m.visible=false);s.attention.values.forEach(c=>c.m.visible=false);s.attention.keyComponents=Array.from({length:8},(_,i)=>[0,1].map(d=>label(content,'',[xToken(i),2.72-d*.16,.32],.40,.12)));s.attention.valueComponents=Array.from({length:8},(_,i)=>[0,1].map(d=>label(content,'',[xToken(i),1.65-d*.16,.32],.40,.12)));for(const [prefix,y]of[['K',2.72],['V',1.65]])for(let d=0;d<2;d++)label(content,prefix+d,[-1.70,y-d*.16,.32],.18,.10);}
  if(spec.index===3){s.encdec={source:Array.from({length:8},(_,i)=>cell(content,[xToken(i),2.87,.24],.37,.25,P.mint,'s'+i)),decoder:Array.from({length:8},(_,i)=>cell(content,[xToken(i),1.91,.24],.37,.25,P.dim,'t'+i)),crossLinks:Array.from({length:8},(_,i)=>rod(content,[0,2.07,.40],[xToken(i),2.72,.40],.01,P.gold)),decoderLinks:Array.from({length:8},(_,i)=>rod(content,[0,1.78,.44],[xToken(i),1.78,.44],.01,P.coral)),bars:Array.from({length:8},(_,i)=>valueBar(content,xToken(i),.88,.29,P.mint)),sourceLabel:label(content,t('Fuente: codificador bidireccional','Source: bidirectional encoder'),[0,3.38,.28],3.3,.14),decoderLabel:label(content,'',[0,2.35,.28],3.3,.14),output:label(content,'',[0,.40,.28],3.3,.14)};}
  if(spec.index===4){s.moe={router:cell(content,[0,3.20,.30],1.15,.29,P.gold,t('Router','Router')),experts:Array.from({length:8},(_,i)=>{const x=(i%4-1.5)*.86,y=2.39-Math.floor(i/4)*1.08;return {cell:cell(content,[x,y,.25],.68,.30,P.dim,'E'+i),logit:label(content,'',[x,y+.30,.30],.79,.11),weight:label(content,'',[x,y-.30,.30],.79,.11),value:label(content,'',[x,y-.50,.30],.79,.10),in:rod(content,[0,3.02,.20],[x,y+.18,.20],.010,P.gold),out:rod(content,[x,y-.18,.18],[0,.65,.18],.010,P.mint)};}),output:label(content,'',[0,.42,.30],3.5,.15)};}
  if(spec.index===5){s.ssm={bars:Array.from({length:3},(_,i)=>valueBar(content,(i-1)*1.08,2.05,.48,P.mint)),state:label(content,'',[0,3.07,.28],3.3,.14),equation:label(content,t('h = g ⊙ hprev + (1−g) ⊙ tanh(x)','h = g ⊙ hprev + (1−g) ⊙ tanh(x)'),[0,3.41,.28],3.5,.14),input:label(content,'',[0,1.18,.28],3.3,.14),gate:label(content,'',[0,.91,.28],3.3,.14),jamba:Array.from({length:8},(_,i)=>cell(content,[xToken(i),.50,.24],.36,.22,i===7?P.gold:P.mint,i===7?'A':'M')),note:label(content,t('Jamba: 7 Mamba + 1 atención','Jamba: 7 Mamba + 1 attention'),[0,.26,.28],3.3,.11)};}
  if(spec.index===6){s.diffusion={tokens:Array.from({length:8},(_,i)=>cell(content,[xToken(i),2.80,.25],.37,.32,P.dim,'·')),ar:Array.from({length:8},(_,i)=>cell(content,[xToken(i),1.29,.25],.37,.32,P.dim,'·')),round:label(content,'',[0,3.39,.28],3.4,.16),parallel:label(content,t('8 posiciones se revisan en cada ronda','8 positions are revised each round'),[0,2.21,.28],3.4,.14),serial:label(content,'',[0,1.87,.28],3.4,.14),note:label(content,t('Estados discretos predefinidos · no inferencia real','Predefined discrete states · not live inference'),[0,.55,.28],3.4,.12)};}
  if(spec.index===7){const patches=[],contextEncoder=cell(content,[-1.03,2.53,.23],1.46,.23,P.mint,t('Encoder contexto','Context encoder')),targetEncoder=cell(content,[1.03,2.53,.23],1.46,.23,P.gold,t('Encoder objetivo','Target encoder'));for(const side of[-1,1])for(let i=0;i<16;i++){const x=side*1.03+(i%4-1.5)*.17,y=3.10+(Math.floor(i/4)-1.5)*.17;const p=box(content,[x,y,.22],[.15,.15,.06],side<0&&[5,6,9,10].includes(i)?P.dim:[P.mint,P.gold,P.coral][(i+Math.floor(i/4))%3]);p.userData.patchIndex=i;p.userData.branch=side<0?'context':'target';p.userData.inputVisible=side>0||![5,6,9,10].includes(i);patches.push(p);}s.jepa={patches,contextEncoder,targetEncoder,predictor:cell(content,[-1.03,2.09,.23],1.46,.23,P.mint,t('Predictor','Predictor')),targetMask:cell(content,[1.03,2.09,.23],1.46,.23,P.gold,t('Selección de salida','Output selection')),predicted:Array.from({length:6},(_,i)=>valueBar(content,-1.68+i*.28,1.22,.16,P.mint,.24)),target:Array.from({length:6},(_,i)=>valueBar(content,.28+i*.28,1.22,.16,P.gold,.24)),squared:Array.from({length:6},(_,i)=>label(content,'',[(i-2.5)*.57,.69,.30],.54,.11)),error:label(content,'',[0,.40,.30],3.5,.14),note:label(content,t('Imagen sintética · objetivo ve toda la entrada','Synthetic image · target sees the full input'),[0,3.51,.28],3.5,.12)};}
  if(spec.index===8){s.typed={questions:Array.from({length:2},(_,q)=>{const x=q===0?-1.0:1.0;return {title:label(content,t('Pregunta ','Question ')+(q+1),[x,2.92,.28],1.6,.15),options:Array.from({length:2},(_,i)=>cell(content,[x+(i-.5)*.74,2.25,.25],.65,.30,P.dim,t(i===0?'sí':'no',i===0?'yes':'no'))),bars:Array.from({length:2},(_,i)=>valueBar(content,x+(i-.5)*.74,1.23,.42,P.mint)),choice:label(content,'',[x,.60,.28],1.75,.14)};}),note:label(content,t('Contrato genérico · arquitectura Jev no publicada','Generic contract · Jev architecture unpublished'),[0,3.42,.28],3.5,.13)};}
  if(spec.index===9){s.cache={prefix:cell(content,[-1.0,2.87,.25],1.76,.41,P.gold,''),suffix:cell(content,[1.12,2.87,.25],1.20,.41,P.coral,''),store:cell(content,[-.40,1.93,.25],1.95,.42,P.dim,''),output:cell(content,[.44,.93,.25],1.90,.42,P.gold,''),links:[rod(content,[-1,2.65,.30],[-.4,2.16,.30],.015,P.gold),rod(content,[1.12,2.65,.30],[.44,1.15,.30],.015,P.coral),rod(content,[-.4,1.7,.30],[.44,1.15,.30],.015,P.mint)],request:label(content,'',[0,3.43,.28],3.4,.15),total:label(content,'',[0,.42,.28],3.4,.14),costs:label(content,'',[0,1.44,.28],3.4,.13)};}
  if(spec.index===10){s.memory={mha:valueBar(content,-.64,.78,.51,P.gold,.87),mla:valueBar(content,.35,.78,.51,P.mint,.87),inset:valueBar(content,1.42,1.4,.28,P.mint),axis:[0,.5,1].map((v,i)=>({line:rod(content,[-1.52,.78+v*2.55,.22],[-1.38,.78+v*2.55,.22],.008,P.steel),caption:label(content,'',[-1.58,.78+v*2.55,.28],.39,.10)})),tokens:label(content,'',[0,3.52,.28],3.3,.14),ratio:label(content,'',[0,.27,.28],3.5,.12),insetLabel:label(content,t('MLA ×16 · ampliación','MLA ×16 · magnified'),[1.25,2.84,.28],1.2,.11),names:[label(content,'MHA',[-.64,.48,.28],.78,.12),label(content,'MLA',[.35,.48,.28],.78,.12)]};s.memory.inset.body.userData.countsAsObject=false;}
  if(spec.index===11){const curve=()=>{const geometry=own(new THREE.BufferGeometry());geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(201*3),3));const line=new THREE.Line(geometry,own(new THREE.LineBasicMaterial({color:0x90cdbd})));content.add(line);return {line,geometry,points:[]};};s.rule={writeRead:curve(),fresh:curve(),marker:ball(content,[0,.8,.3],.075,P.gold),rule:label(content,'',[0,3.40,.28],3.5,.14),breakEven:label(content,'',[0,3.10,.28],3.5,.13),total:label(content,'',[0,.40,.28],3.5,.13),axis:label(content,t('Llamadas → · coste acumulado ↑','Calls → · cumulative cost ↑'),[0,.69,.28],3.3,.12)};s.rule.fresh.line.material.color.set(0xd48e7b);}
 }
 const flowMaterial=mat(0xffe3a9,{emissive:0xf0ba66,emissiveIntensity:.65});
 function traveler(g){const m=ball(g,[0,0,.50],.040,flowMaterial);m.userData.isIllustration=true;m.userData.countsAsObject=false;m.userData.scope=t('Marcador de flujo de activaciones, no bit físico','Activation-flow marker, not a physical bit');return m;}
 for(const s of stations){if(s.attention)s.attention.travelers=Array.from({length:8},()=>traveler(s.content));if(s.moe)s.moe.travelers=Array.from({length:8},()=>traveler(s.content));if(s.cache)s.cache.travelers=Array.from({length:3},()=>traveler(s.content));}
 function travel(m,a,b,u,visible,phase){m.position.set(...a).lerp(new THREE.Vector3(...b),clamp(u));m.visible=visible;m.userData.from=[...a];m.userData.to=[...b];m.userData.progress=clamp(u);m.userData.phase=phase;}
 const parts={architecture,floor,walls,stations,stands,attention:{causal:stations[1].attention,encoder:stations[2].attention,cross:stations[3].encdec},moe:stations[4].moe,ssm:stations[5].ssm,diffusion:stations[6].diffusion,jepa:stations[7].jepa,typed:stations[8].typed,cache:stations[9].cache,memory:stations[10].memory,rule:stations[11].rule}; function updateStation(s,f){const trace=f.trace,params=trace.params||f.params||{},p=clamp(f.progress),q=Math.floor(clamp(Number(params.query),0,7));s.frame=f;s.group.userData.chapter=s.index;s.group.userData.progress=p;
  if(s.intro){const prices=Model.tariffById?.(params.tariff);s.intro.costs[0].set(t('Nueva ','Fresh ')+money(prices?.miss));s.intro.costs[1].set(t('Caché ','Cache ')+money(prices?.hit));s.intro.costs[2].set(t('Salida ','Output ')+money(prices?.output));}
  if(s.attention){const a=s.attention,row=trace.attention?.[a.kind]?.[q],keys=trace.attention?.k||[],values=trace.attention?.v||[],queries=trace.attention?.q||[];if(row){a.row=row;a.queryIndex=q;a.phase=f.attention?.phase??(p<.25?'query':p<.5?'scores':p<.8?'weights':'mix');a.query.set('Q'+q+' = '+vec(queries[q]));a.scoreHeading.m.visible=p>=.25;for(let i=0;i<8;i++){const allowed=row.allowed[i],weight=row.weights[i];a.tokens[i].body.material=i===q?P.white:allowed&&p>=.5?P.mint:P.dim;a.tokens[i].body.userData={tokenIndex:i,activeQuery:i===q,allowed,info:'t'+i+' · K='+vec(keys[i])+' · V='+vec(values[i])};for(let d=0;d<2;d++){a.keyComponents[i][d].set(fmt(keys[i]?.[d]));a.valueComponents[i][d].set(fmt(values[i]?.[d]));}a.scores[i].m.visible=p>=.25;a.scores[i].set(allowed?fmt(row.scores[i]):p>=.5?'−∞':fmt(row.scores[i]));a.masks[i].body.material=p>=.5?(allowed?P.mint:P.dim):P.dim;a.masks[i].caption.set(p>=.5?(allowed?'✓':'×'):'—');a.masks[i].body.userData.allowed=allowed;setBar(a.bars[i],p>=.5?weight:0,.60);a.bars[i].caption.set(p>=.5?(100*weight).toFixed(1)+'%':'—');a.bars[i].body.userData.weight=weight;a.bars[i].body.userData.allowed=allowed;a.links[i].visible=allowed&&p>=.5;setRod(a.links[i],[xToken(q),3.10,.42],[xToken(i),2.76,.42],.006+.030*weight);a.links[i].userData.weight=weight;const scoring=p>=.25&&p<.5,mixing=p>=.5&&p<.8;travel(a.travelers[i],scoring?[xToken(q),3.10,.50]:[xToken(i),1.65,.50],scoring?[xToken(i),2.76,.50]:[0,.40,.50],scoring?(p-.25)/.25:(p-.5)/.30,scoring||mixing&&allowed&&weight>0,scoring?'score':'weighted-value');a.travelers[i].userData.weight=weight;}a.output.set(p>=.8?'Σ aV = '+vec(row.output):t('Mezcla pendiente','Mixture pending'));a.outputReady=p>=.8;}}
  if(s.encdec){const a=s.encdec,row=trace.attention?.cross?.[q],decoder=trace.attention?.causal?.[q];if(row&&decoder){a.row=row;a.decoderRow=decoder;a.queryIndex=q;a.decoderLabel.set(t('Decodificador: consulta ','Decoder: query ')+q+' · j≤'+q);for(let i=0;i<8;i++){a.source[i].body.material=P.mint;a.source[i].body.userData={tokenIndex:i,sourceVisible:true,info:'s'+i+' · K='+vec(trace.attention.crossK?.[i])+' · V='+vec(trace.attention.crossV?.[i])};a.decoder[i].body.material=i===q?P.white:decoder.allowed[i]?P.gold:P.dim;a.decoder[i].body.userData={tokenIndex:i,allowed:decoder.allowed[i],activeQuery:i===q};a.crossLinks[i].visible=p>=.5;setRod(a.crossLinks[i],[xToken(q),2.08,.47],[xToken(i),2.72,.47],.006+.030*row.weights[i]);a.crossLinks[i].userData.weight=row.weights[i];a.decoderLinks[i].visible=decoder.allowed[i];setRod(a.decoderLinks[i],[xToken(q),1.72,.44],[xToken(i),1.72,.44],.012);a.decoderLinks[i].userData.allowed=decoder.allowed[i];setBar(a.bars[i],p>=.5?row.weights[i]:0,.70);a.bars[i].caption.set(p>=.5?(100*row.weights[i]).toFixed(1)+'%':'—');}a.output.set(p>=.8?'Σ aV = '+vec(row.output):t('Atención cruzada pendiente','Cross attention pending'));}}
  if(s.moe){const a=s.moe,data=trace.moe;if(data){a.state=data;a.outputReady=p>=.8;for(let i=0;i<8;i++){const e=a.experts[i],active=data.active.includes(i),weight=data.weights[i];e.cell.body.material=p>=.35&&active?P.gold:P.dim;e.cell.body.userData={expertIndex:i,active,weight,logit:data.logits[i],info:'E'+i+' · logit '+fmt(data.logits[i])+' · a='+fmt(weight)+(active&&p>=.55?' · y='+vec(data.expertOutputs[i]):' · '+t('sin ejecutar','not executed'))};e.logit.set('logit '+fmt(data.logits[i]));e.weight.set(p>=.35?'a='+fmt(weight):'a=—');e.value.set(p<.35?'—':!active?t('Sin ejecutar','Not executed'):p<.55?t('Pendiente','Pending'):vec(data.expertOutputs[i]));e.in.visible=e.out.visible=active&&p>=.35;e.in.userData.weight=e.out.userData.weight=weight;setRod(e.in,[0,3.02,.45],[e.cell.body.position.x,e.cell.body.position.y+.18,.45],.006+.027*weight);setRod(e.out,[e.cell.body.position.x,e.cell.body.position.y-.18,.18],[0,.65,.18],.006+.027*weight);const entering=p>=.35&&p<.55,leaving=p>=.55&&p<.8;travel(a.travelers[i],entering?[0,3.02,.50]:[e.cell.body.position.x,e.cell.body.position.y-.18,.50],entering?[e.cell.body.position.x,e.cell.body.position.y+.18,.50]:[0,.65,.50],entering?(p-.35)/.20:(p-.55)/.25,active&&(entering||leaving),entering?'route-to-expert':'weighted-mixture');a.travelers[i].userData.weight=weight;}a.output.set(p>=.8?'Σ aᵢ yᵢ = '+vec(data.output):t('Mezcla pendiente','Mixture pending'));}}
  if(s.ssm){const a=s.ssm,data=trace.ssm,n=Math.floor(clamp(Number(f.completed),0,8)),h=f.ssm?.state??data?.states?.[n];if(h){a.state=h;a.completed=n;for(let i=0;i<3;i++){setBar(a.bars[i],h[i],.70,true);a.bars[i].caption.m.visible=false;a.bars[i].body.material=h[i]<0?P.coral:P.mint;}const stateLabel=s.ssm.stateDisplay;if(stateLabel)stateLabel.set('h'+n+' = '+vec(h));a.input.set('x'+Math.min(7,n)+' = '+vec(data.inputs[Math.min(7,n)]));a.gate.set('g'+Math.min(7,n)+' = '+vec(data.gates[Math.min(7,n)]));}}
  if(s.diffusion){const a=s.diffusion,data=f.diffusion||trace.diffusion,round=Math.floor(clamp(Number(f.round??data.round),0,data.rounds??params.denoise??8)),values=data.state||data.states?.[round]||[],ar=f.autoregressive?.state||trace.autoregressive?.states?.[f.completed??0]||[];a.state=values;a.roundIndex=round;a.rounds=data.rounds??params.denoise;for(let i=0;i<8;i++){a.tokens[i].caption.set(values[i]??'·');a.tokens[i].body.material=values[i]&&values[i]!=='·'?P.mint:P.dim;a.tokens[i].body.userData.token=values[i]??'·';a.ar[i].caption.set(ar[i]??'·');a.ar[i].body.material=ar[i]&&ar[i]!=='·'?P.gold:P.dim;a.ar[i].body.userData.token=ar[i]??'·';}a.round.set(t('Ronda ','Round ')+round+'/'+a.rounds);a.serial.set(t('Autorregresivo: ','Autoregressive: ')+(f.completed??0)+'/8 '+t('posiciones escritas','positions written'));}
  if(s.jepa){const a=s.jepa,data=trace.jepa;if(data){a.state=data;for(let i=0;i<6;i++){setBar(a.predicted[i],data.predicted[i],.36,true);setBar(a.target[i],data.target[i],.36,true);a.predicted[i].body.userData.dimension=a.target[i].body.userData.dimension=i;a.predicted[i].body.material=i===f.activeDimension?P.white:P.mint;a.target[i].body.material=i===f.activeDimension?P.white:P.gold;a.squared[i].set('e'+i+'='+fmt(data.squared[i]));a.squared[i].m.visible=i<(f.jepa?.completedDimensions??Math.floor(p*6));}a.error.set(f.jepa?.ready===true?'MSE = Σe²/6 = '+fmt(data.error)+t(' · ejemplo',' · toy'):t('Dos representaciones fijas · pesos sin cambios','Two fixed representations · unchanged weights'));}}
  if(s.typed){const a=s.typed,data=trace.jev||trace.typed||[];a.state=data;for(let qi=0;qi<2;qi++){const item=data[qi],r=a.questions[qi],revealed=qi<(f.typedRevealed??0);if(!item)continue;const probabilities=item.probabilities||item.probs;r.state=item;r.revealed=revealed;for(let i=0;i<2;i++){r.options[i].body.material=revealed&&i===item.index?P.gold:P.dim;r.options[i].body.userData={questionIndex:qi,optionIndex:i,probability:probabilities[i],chosen:i===item.index};setBar(r.bars[i],revealed?probabilities[i]:0,.73);r.bars[i].caption.set(revealed?(100*probabilities[i]).toFixed(1)+'%':'—');}r.choice.set(revealed?t('Elegida: ','Choice: ')+t(item.index===0?'sí':'no',item.choice):t('Pendiente','Pending'));}}
  if(s.cache){const a=s.cache,data=trace.bill,request=f.requestIndex??0,running=f.billRunning||{};a.state=data;a.running=running;a.requestIndex=request;a.cold=request===0;a.prefix.caption.set(t('Prefijo ','Prefix ')+integer(params.prefix));a.suffix.caption.set(t('Nueva ','Fresh ')+integer(params.suffix));a.output.caption.set(t('Salida ','Output ')+integer(params.output));const hasHit=!a.cold&&data.laterCounts.hit>0;a.store.caption.set(a.cold?t('Escribir / calcular','Write / compute'):hasHit?t('Reusar ','Reuse ')+integer(data.laterCounts.hit)+' · '+t('calcular ','compute ')+integer(data.laterCounts.miss):t('Sin acierto · recalcular','No hit · recompute'));a.store.body.material=hasHit?P.mint:P.gold;a.links[0].material=hasHit?P.mint:P.gold;a.links[2].visible=true;a.links[2].material=hasHit?P.mint:P.gold;a.request.set(t('Llamada ','Request ')+(request+1)+'/'+params.repeats+' · '+(a.cold?t('fría','cold'):t('repetida','repeated')));a.costs.set(t('Entrada ','Input ')+money(a.cold?data.first.missCost:data.later.hitCost+data.later.missCost)+' · '+t('salida ','output ')+money(data.first.outputCost));a.total.set(t('Completadas ','Completed ')+(running.completedRequests??0)+' · '+money(running.withCache)+' / '+money(running.noCache));a.output.body.userData.recomputedEveryRequest=true;a.prefix.body.userData.hitFraction=params.hitFraction;a.store.body.userData.hitTokens=a.cold?0:data.laterCounts?.hit;const u=p===1?1:(p*params.repeats)%1,paths=[[[-1,2.65,.50],[-.4,2.16,.50],0,.35],[ [1.12,2.65,.50],[.44,1.15,.50],.35,.65],[[-.4,1.70,.50],[.44,1.15,.50],.65,1]];a.travelers.forEach((m,i)=>{const [from,to,start,end]=paths[i];travel(m,from,to,(u-start)/(end-start),p<1&&u>=start&&u<end,['prefix','fresh-suffix','recomputed-output'][i]);m.material=i===0&&hasHit?P.mint:i===1?P.coral:flowMaterial;m.userData.requestIndex=request;m.userData.cold=a.cold;});}
  if(s.memory){const a=s.memory,n=f.memoryTokens??params.tokens,values=Model.contextMemory(n),max=Model.contextMemory(32000).mha,h=2.55/max;a.state={tokens:n,mha:values.mha,mla:values.mla,scale:h};setBar(a.mha,values.mha,h);setBar(a.mla,values.mla,h);setBar(a.inset,values.mla,h*16);a.mha.caption.set('MHA '+(values.mha?values.mha.toExponential(2):'0'));a.mla.caption.set('MLA '+(values.mla?values.mla.toExponential(2):'0'));a.names.forEach(c=>c.m.visible=false);a.inset.caption.set('×16');a.mha.body.userData.elements=values.mha;a.mla.body.userData.elements=values.mla;a.inset.body.userData.elements=values.mla;a.inset.body.userData.magnification=16;a.axis.forEach((tick,i)=>tick.caption.set((max*i/2).toExponential(1)));a.tokens.set(integer(n)+' '+t('tokens · eje común en elementos','tokens · shared element axis'));a.ratio.set('MHA / MLA = '+fmt(Model.mhaElementsPerToken()/Model.mlaElementsPerToken())+'× · '+t('ambas crecen linealmente','both grow linearly'));}
  if(s.rule){const a=s.rule,data=trace.rule,done=f.completedRequests??f.billRunning?.completedRequests??0,n=data.withCache.length-1,max=Math.max(...data.noCache,...data.withCache,1e-12);a.state=data;a.completedRequests=done;for(const [r,costs]of[[a.writeRead,data.withCache],[a.fresh,data.noCache]]){r.points=costs.map((value,i)=>[-1.55+(i/Math.max(1,n))*3.1,.94+value/max*1.85,.30]);const attr=r.geometry.attributes.position;for(let i=0;i<r.points.length;i++)attr.setXYZ(i,...r.points[i]);attr.needsUpdate=true;r.geometry.setDrawRange(0,Math.min(done+1,r.points.length));r.geometry.computeBoundingSphere();r.line.userData.costs=costs;}a.marker.position.set(...a.writeRead.points[Math.min(done,n)]);a.rule.set(t('Escribir ','Write ')+data.write+'× · '+t('leer ','read ')+data.read+'×');a.breakEven.set(t('Primera llamada más barata: ','First cheaper request: ')+(data.firstCheaper??t('ninguna con este prefijo','none with this prefix')));a.total.set(t('Solo prefijo · ','Prefix only · ')+done+' '+t('llamadas','calls')+' · '+money(data.withCache[Math.min(done,n)])+' / '+money(data.noCache[Math.min(done,n)]));}
 }
 // Keep the label separate from the recurrent vector stored in the public record.
 stations[5].ssm.stateDisplay=stations[5].ssm.state;delete stations[5].ssm.state;
 function update(frame,selected=frame?.chapter??0,whole=false,immersive=false){if(disposed||!frame?.trace)return;lastFrame=frame;const current=chapter(selected);walls.forEach(w=>w.visible=immersive||whole);for(const s of stations){s.group.visible=immersive||whole||s.index===current;s.standGroup.visible=immersive||whole;const progress=s.index===frame.chapter?frame.progress:s.index<frame.chapter?1:0,f=s.index===frame.chapter?frame:Model.modelsFrameAt(frame.trace,s.index,progress);updateStation(s,f);s.stand.material=s.index===current?P.gold:P.mint;}scene.updateMatrixWorld(true);}
 scene.updateMatrixWorld(true);return {scene,parts,stations,stands,targets,resources,solids:MODELS_SOLIDS,bounds:MODELS_BOUNDS,update,get state(){return lastFrame;},dispose(){if(disposed)return;disposed=true;for(const r of [...resources])r.dispose();}};
}
function isVisible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
export function createModelsWorld(host,es=true,onListen=()=>{},onInfo=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);const built=createModelsScene(es),camera=new THREE.PerspectiveCamera(46,1,.055,180),post=createPost(renderer,built.scene,camera,{strength:.35,radius:.40,threshold:1.2}),canvas=renderer.domElement,orbit={...modelsOverview},ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let active=0,mode='notebook',pose=modelsPoseAt(0),frame,disposed=false,dragging=false,lastX=0,lastY=0,down,pinch=0;const listeners=[];canvas.tabIndex=0;
 function listen(target,event,fn,options){target.addEventListener(event,fn,options);listeners.push(()=>target.removeEventListener(event,fn,options));}
 function draw(){if(disposed)return;const fov=mode==='immersive'?80:camera.aspect<1?64:46;if(camera.fov!==fov){camera.fov=fov;camera.updateProjectionMatrix();}if(frame)built.update(frame,active,orbit.whole&&mode!=='immersive',mode==='immersive');if(mode==='immersive'){camera.position.set(pose.x,1.65,pose.z);camera.rotation.set(pose.pitch,pose.yaw,0,'YXZ');}else{const f=modelsFraming(active,orbit,camera.aspect,camera.fov);camera.position.copy(f.center).addScaledVector(f.direction,f.distance);camera.lookAt(f.center);}camera.updateMatrixWorld();built.scene.updateMatrixWorld(true);post.render(0);}
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();post.setSize(w,h,Math.min(globalThis.devicePixelRatio||1,1.5));draw();}const observer=new ResizeObserver(resize);observer.observe(host);
 function inspect(x,y){if(disposed)return null;const rect=canvas.getBoundingClientRect();pointer.set((x-rect.left)/rect.width*2-1,1-(y-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);for(const hit of ray.intersectObjects(built.scene.children,true)){if(!isVisible(hit.object)||hit.object.isSprite||hit.object.userData.isLabel)continue;const o=hit.object,action=o.userData.action;if(Number.isInteger(action))return {action,index:action,object:o,distance:hit.distance};if(o.userData.info)return {info:o.userData.info,object:o,distance:hit.distance};if(o.isMesh&&(!o.material?.transparent||o.material.opacity>.5))return null;}return null;}
 const fire=hit=>{if(!hit)return false;if(Number.isInteger(hit.action)){onListen(hit.action);return true;}if(hit.info){onInfo(hit.info,hit);return true;}return false;};
 listen(canvas,'pointerdown',e=>{if(mode!=='notebook')return;dragging=true;lastX=e.clientX;lastY=e.clientY;down={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});listen(canvas,'pointermove',e=>{if(!dragging||mode!=='notebook')return;orbit.yaw-=(e.clientX-lastX)*.004;orbit.pitch=clamp(orbit.pitch+(e.clientY-lastY)*.004,-.35,1.15);lastX=e.clientX;lastY=e.clientY;draw();});listen(canvas,'pointerup',e=>{if(mode==='notebook'){dragging=false;if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5)fire(inspect(e.clientX,e.clientY));down=null;}});listen(canvas,'wheel',e=>{if(mode!=='notebook')return;e.preventDefault();orbit.distance=clamp(orbit.distance*(e.deltaY>0?1.06:.94),5,22);draw();},{passive:false});listen(canvas,'touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});listen(canvas,'touchmove',e=>{if(mode!=='notebook'||e.touches.length!==2)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch){orbit.distance=clamp(orbit.distance*pinch/Math.max(1,d),5,22);draw();}pinch=d;},{passive:true});listen(canvas,'webglcontextlost',e=>e.preventDefault());resize();
 return {canvas,dom:canvas,camera,built,scene:built.scene,orbit,render(f){frame=f;active=chapter(f?.chapter??active);draw();},focus(index){active=chapter(index);orbit.yaw=MODELS_LAYOUT[active].yaw+(camera.aspect<1?.06:.10);orbit.pitch=.10;orbit.distance=10;orbit.whole=false;draw();},fit(){orbit.distance=10;orbit.whole=false;draw();},overview(){orbit.whole=true;orbit.yaw=.38;orbit.pitch=.65;orbit.distance=10;draw();},zoomBy(f){orbit.distance=clamp(orbit.distance/f,5,22);draw();},setMode(value){mode=value==='immersive'?'immersive':'notebook';draw();},setPose(value){pose=restoreModelsPose(value);draw();},getViewState(){return {chapter:active,mode,orbit:{...orbit},pose:{...pose}};},restoreViewState(saved){if(!saved||typeof saved!=='object')return false;active=chapter(saved.chapter);mode=saved.mode==='immersive'?'immersive':'notebook';const o=saved.orbit||{};orbit.yaw=Number.isFinite(o.yaw)?o.yaw:MODELS_LAYOUT[active].yaw+(camera.aspect<1?.06:.10);orbit.pitch=clamp(Number.isFinite(o.pitch)?o.pitch:.10,-.35,1.15);orbit.distance=clamp(Number.isFinite(o.distance)?o.distance:10,5,22);orbit.whole=o.whole===true;pose=restoreModelsPose(saved.pose);draw();return true;},nearest(){return modelsNearestStand(pose);},activate(){const near=modelsNearestStand(pose);if(!near)return false;onListen(near.index);return true;},inspect,stats(){return {geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,resources:built.resources.length};},dispose(){if(disposed)return;disposed=true;observer.disconnect();listeners.forEach(fn=>fn());built.dispose();post.dispose();renderer.dispose();canvas.remove?.();}};
}