import {createExperience,visible} from './world.js';
import {STOPS,poseAt,nearestStop,walk,travelPose,standPosition} from './model.js';
import {bindFirstPerson} from './first-person.js';
import {createTranscript} from './transcript.js';
import {DEFAULTS,createRun,advance,contextWindow,tokenize} from '../llms/model.js';
import {StepGuide,narrationId} from '../llms/guide.js';
import {llmFrameAt} from '../llms/presentation.js';
import {VOICES} from './voices.js';
import {guideProgress,cueAt,OPERATIONS} from '../llms/flow.js';
export function createLLMImmersiveController({document:doc=globalThis.document,window:win=globalThis.window,Guide=StepGuide,AudioClass=globalThis.Audio,
 worldFactory=createExperience,world:providedWorld,binder=bindFirstPerson,transcriptFactory=createTranscript,
 requestFrame=globalThis.requestAnimationFrame,cancelFrame=globalThis.cancelAnimationFrame,now=()=>performance.now(),media=globalThis.matchMedia,
 storage=globalThis.localStorage,search=globalThis.location?.search||''}={}){
 const document=doc,window=win,matchMedia=media,performance={now},location={search};let raf,disposed=false,frameLLM,restoring=false;
 const listeners=[],requestAnimationFrame=fn=>{raf=requestFrame(fn);return raf;},listen=(target,event,fn)=>{target.addEventListener(event,fn);listeners.push(()=>target.removeEventListener(event,fn));};
const es=document.documentElement.lang==='es',lang=es?'es':'en',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const requested=params.get('experience')||'llms';
document.title=t('Dentro de una respuesta · Atlas 3D','Inside an answer · Atlas 3D');
if(requested!=='llms'){
 $('app').innerHTML=`<section class="fallback"><h1>${t('Elige una experiencia en el museo','Choose an experience in the museum')}</h1><a href="../museo/index.html">← ${t('Museo','Museum')}</a></section>`;
}else{
 $('app').innerHTML=`
 <nav class="topbar" aria-label="${t('Navegación','Navigation')}"><a class="brand" href="../museo/index.html?pieza=llms">ATLAS <span>/ ${t('MUSEO','MUSEUM')}</span></a><div class="formats"><a href="../llms/index.html">Notebook</a><a href="../llms/cinema.html">${t('Cinemática','Cinematic')}</a><span aria-current="page">${t('Inmersivo','Immersive')} <i>3D</i></span></div><button id="route-toggle" aria-expanded="false" aria-controls="route">☷ ${t('Recorrido','Route')}</button></nav>
 <aside class="reader" aria-label="${t('Texto de la narración','Narration text')}"><div class="reader-heading"><span class="eyebrow" id="chapter"></span><h1 id="title"></h1><p id="description"></p></div><div class="voice-controls"><button id="listen" class="primary">▶ ${t('Escuchar','Listen')}</button><select id="language" aria-label="${t('Idioma de la narración','Narration language')}"><option value="es" ${es?'selected':''}>ES</option><option value="en" ${es?'':'selected'}>EN</option></select></div><div class="progress" role="progressbar" aria-label="${t('Narración','Narration')}" aria-valuemin="0" aria-valuemax="100"><i id="progress"></i></div><label class="audio-scrub" for="audio-time">${t("Momento de la explicación","Explanation moment")} <output id="audio-time-value">0%</output><input id="audio-time" type="range" min="0" max="1" step=".001" value="0"></label><p class="status" id="status" role="status"></p><div class="transcript" id="transcript" tabindex="0"></div><footer class="reader-footer"><span>MINIMAX · ${t('TEXTO DE LA VOZ','VOICE TRANSCRIPT')}</span><button id="reader-toggle" aria-expanded="true">${t('Ocultar texto','Hide text')}</button></footer></aside>
 <section class="viewport" aria-label="${t('Escena inmersiva','Immersive scene')}"><div id="world"></div><div class="crosshair" aria-hidden="true"></div><div class="scene-caption"><span class="eyebrow">${t('SIGUE LA SEÑAL DORADA','FOLLOW THE GOLD SIGNAL')}</span><p id="scene-caption"></p></div><div id="stands">${STOPS.map(s=>`<button class="stand-button" data-listen="${s.index}" hidden aria-label="${t('Escuchar','Listen to')} ${s.titles[es?0:1]}"><span>▶</span> ${t('Escuchar','Listen')} <kbd>E</kbd></button>`).join('')}</div><div class="inspect" id="inspect" role="status" hidden></div><div class="operation-dock" id="attention" hidden><div class="operation-heading"><span id="operation-title"></span><label>${t('Token','Token')} <select id="query" aria-label="${t('Token que consulta','Query token')}"></select></label></div><div class="steps">${OPERATIONS.map((o,i)=>`<button data-operation="${i}" title="${o.name[es?0:1]}" aria-label="${o.name[es?0:1]}">${i+1}<span>${[t('Proyectar','Project'),t('Comparar','Compare'),t('Enmascarar','Mask'),t('Mezclar','Mix'),t('Transformar','Transform')][i]}</span></button>`).join('')}</div><p id="formula"></p></div><div class="touch" aria-label="${t('Caminar','Walk')}"><button data-move="forward" aria-label="${t('Adelante','Forward')}">↑</button><button data-move="left" aria-label="${t('Izquierda','Left')}">←</button><button data-move="back" aria-label="${t('Atrás','Back')}">↓</button><button data-move="right" aria-label="${t('Derecha','Right')}">→</button></div><div class="scene-footer"><span id="position"></span><span>${t('Modelo didáctico · pesos sintéticos','Teaching model · synthetic weights')}</span></div></section>
 <div class="transport"><button id="lock">${t('Activar ratón','Enable mouse')}</button><p id="camera-help">${t('Ratón: mirar · WASD: caminar · E: escuchar · Esc: cursor','Mouse: look · WASD: walk · E: listen · Esc: cursor')}</p><button id="tour">${t('Guiarme','Guide me')}</button><button id="next" class="primary">${t('Siguiente','Next')} →</button></div>
 <aside class="route" id="route" hidden><div class="route-heading"><h2>${t('Dentro de una respuesta','Inside an answer')}</h2><button id="route-close" aria-label="${t('Cerrar recorrido','Close route')}">×</button></div><p>${t('Ocho estaciones. Acércate al botón de cada stand para escuchar sin que se mueva la cámara.','Eight stations. Approach each stand’s button to listen without moving the camera.')}</p><div class="stop-list">${STOPS.map(s=>`<button data-stop="${s.index}"><b>${String(s.index+1).padStart(2,'0')}</b><span>${s.titles[es?0:1]}</span></button>`).join('')}</div><label>${t('Ejemplo','Example')}<select id="scenario"><option value="capital">${t('La capital de Francia','The capital of France')}</option><option value="bank">${t('Una palabra ambigua','An ambiguous word')}</option><option value="museum">${t('Un museo con fuente externa','A museum with an external source')}</option></select></label><label>${t('Temperatura','Temperature')}<input id="temperature" type="range" min="0" max="2" step="0.05" value="0.7" aria-label="${t('Temperatura','Temperature')}"><output id="temperature-value">0.70</output></label><label><input id="voice" type="checkbox" checked> ${t('Voz MiniMax','MiniMax voice')}</label><label><input id="motion" type="checkbox" ${matchMedia('(prefers-reduced-motion: reduce)').matches?'checked':''}> ${t('Traslados instantáneos','Instant travel')}</label><p class="note">${t('Geometría de la información, no del hardware. Las operaciones del bloque se calculan; los logits y las respuestas son ejemplos preparados independientes.','Information geometry, not hardware. The block operations are computed; logits and answers are separate curated examples.')}</p><a href="https://arxiv.org/abs/1706.03762" target="_blank" rel="noreferrer">Attention Is All You Need ↗</a></aside>
 <div class="welcome" id="welcome"><article><span class="eyebrow">ATLAS / 01 · LLMs</span><h2>${t('Camina por dentro<br>de una respuesta.','Walk inside<br>an answer.')}</h2><p>${t('La claridad de la vista cinemática, ahora en un espacio que puedes recorrer. Sigue una pregunta, ve cómo cambian sus vectores y observa cómo sale una sola pieza de texto.','The clarity of the cinematic view, now in a space you can walk through. Follow a question, see its vectors change and watch a single piece of text emerge.')}</p><div class="welcome-controls"><span><kbd>W A S D</kbd> ${t('caminar','walk')}</span><span><kbd>↔</kbd> ${t('ratón para mirar','mouse to look')}</span><span><kbd>E</kbd> ${t('escuchar un stand','listen at a stand')}</span></div><div class="actions"><button class="primary" id="start-free">${t('Entrar y explorar','Enter and explore')} →</button><button id="start-tour">${t('Recorrido con guía','Guided tour')}</button></div><p class="note">${t('La voz y su texto permanecen juntos. Esc libera el ratón para usar los menús. En móvil, arrastra para mirar.','Voice and transcript stay together. Esc releases the mouse for menus. On mobile, drag to look.')}</p></article></div>`;
 let run=createRun(lang),player=poseAt(0),world=providedWorld,guide,controls,travel=null,guided=false,started=false,last=performance.now(),uiTime=0,voiceLanguage=lang,query=null,manualOperation=0,manualProgress=0,lastOperation=-1,inspectUntil=0,queryKey='';
 const keys=new Set(),touch=new Set(),visited=new Set(),transcript=transcriptFactory($('transcript')),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 const getClip=()=>VOICES[voiceLanguage].find(c=>c.id===narrationId(run));
 const descriptions=[t('Instrucciones y pregunta entran juntas.','Instructions and question enter together.'),t('Buscar información es una herramienta opcional.','Retrieval is an optional tool.'),t('El texto se convierte en piezas con identificadores.','Text becomes pieces with identifiers.'),t('Cada token se representa con números y posición.','Each token is represented with numbers and position.'),t('Una consulta, varias conexiones. Sigue cada operación.','One query, several connections. Follow each operation.'),t('Probabilidad de continuar, no de decir la verdad.','Probability of continuing, not of telling the truth.'),t('Se elige una sola pieza. Los pesos no cambian.','One piece is chosen. The weights stay fixed.'),t('La salida vuelve a la entrada y comienza otro ciclo.','Output returns to the input and another cycle begins.')];
 const storageKey='atlas-llms-immersive-v1';let lastSaved='';
 function progress(){const clip=guide?.clip||getClip();return guide?.seekPending?guide.seekTarget/clip.duration:guide?guideProgress(guide,clip):0;}
 function present(){const clip=guide?.clip||getClip(),p=progress(),cue=guide?.running?cueAt(clip.cues,p*clip.duration):{index:manualOperation,progress:run.phase===4?manualProgress:p};frameLLM=llmFrameAt(run,{progress:p,operationIndex:cue.index,operationProgress:cue.progress,queryIndex:query??contextWindow(run).tokens.length-1});query=frameLLM.queryIndex;return frameLLM;}
 function capture(){return {version:1,options:{...run.options},phase:run.phase,chosen:run.chosen,generated:[...run.generated],seed:run.seed,done:run.done,loops:run.loops,player:{...player},query,manualOperation,manualProgress,progress:progress(),voice:guide.enabled,language:voiceLanguage,running:guide.running,started,visited:[...visited],instant:$('motion').checked,readerCompact:document.body.classList.contains('reader-compact')};}
 function save(){if(disposed||restoring||!world||!guide)return;try{const value=JSON.stringify(capture());if(value!==lastSaved){storage.setItem(storageKey,value);lastSaved=value;}}catch{}}
 function syncQuery(){const {tokens}=contextWindow(run),key=JSON.stringify(tokens);if(key!==queryKey){queryKey=key;$('query').replaceChildren(...tokens.map((token,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+' · '+visible(token);return o;}));}query=Math.max(0,Math.min(tokens.length-1,query??tokens.length-1));$('query').value=query;}
 function syncUIflow(){const clip=guide?.clip||getClip(),p=progress(),cue=frameLLM.flow;
  $('audio-time').value=p;$('audio-time-value').textContent=Math.round(p*100)+'%';$('progress').style.width=p*100+'%';document.querySelector('.progress').setAttribute('aria-valuenow',String(Math.round(p*100)));transcript.sync(clip,p*clip.duration);
  if(run.phase===4){const op=OPERATIONS[cue.index];$('scene-caption').textContent=op.text[es?0:1];if(lastOperation!==cue.index){lastOperation=cue.index;$('operation-title').textContent=op.name[es?0:1];$('formula').textContent=op.formula;document.querySelectorAll('[data-operation]').forEach(b=>b.setAttribute('aria-current',String(+b.dataset.operation===cue.index)));}}else $('scene-caption').textContent=descriptions[run.phase];
 }
 function refresh(){if(disposed)return;present();
  const s=STOPS[run.phase],clip=guide?.clip||getClip();$('chapter').textContent=`${String(run.phase+1).padStart(2,'0')} / 08 · ${t('ESTACIÓN','STATION')}`;$('title').textContent=s.titles[es?0:1];$('description').textContent=descriptions[run.phase];transcript.show(clip);
  $('listen').textContent=guide?.running?'Ⅱ '+t('Pausar voz','Pause voice'):'▶ '+t('Escuchar','Listen');$('tour').textContent=guided?t('Pausar guía','Pause guide'):t('Guiarme','Guide me');$('next').textContent=run.done?t('Reiniciar','Restart')+' ↺':run.phase===7?t('Otro token','Next token')+' →':t('Siguiente','Next')+' →';$('attention').hidden=run.phase!==4;syncQuery();
  document.querySelectorAll('[data-stop]').forEach(b=>{b.setAttribute('aria-current',String(+b.dataset.stop===run.phase));b.classList.toggle('visited',visited.has(+b.dataset.stop));});syncUIflow();
 }
 function stopTravel(){guided=false;travel=null;keys.clear();touch.clear();refresh();}
 function pause(){stopTravel();guide.pause();save();}
 function select(index){guide.stop();manualOperation=0;manualProgress=0;lastOperation=-1;if(index===7&&!run.generated.length){run.phase=6;advance(run);}else run.phase=index;syncQuery();world.updateFrame(present());visited.add(index);$('inspect').hidden=true;refresh();}
 function arrive(audio){travel=null;if(audio)guide.enter();refresh();save();}
 function go(index,audio=true){select(index);const target=world?.arrivalPose?.(index)||poseAt(index);if($('motion').checked){player=target;arrive(audio);}else travel={from:{...player},to:target,elapsed:0,duration:Math.max(.65,Math.min(3.2,Math.hypot(target.x-player.x,target.z-player.z)/12)),audio};}
 function next(){guide.stop();if(run.done){run=createRun(lang,run.options);visited.clear();queryKey='';go(0);return;}advance(run);go(run.phase);}
 // Stand activation deliberately preserves the player's position and orientation.
 function listenAt(index){stopTravel();if(run.phase!==index)select(index);if(guide.running){guide.pause();return;}world.updateFrame(present());if(guide.state==='ready')guide.replay();else guide.resume();refresh();}
 function nearbyListen(){const candidates=STOPS.map(s=>({index:s.index,d:Math.hypot(player.x-standPosition(s.index).x,player.z-standPosition(s.index).z)})).sort((a,b)=>a.d-b.d);if(candidates[0].d<6)listenAt(candidates[0].index);else showInspect(t('Acércate al botón de un stand para escucharlo.','Approach a stand’s button to listen.'));}
 function showInspect(text){$('inspect').textContent=text;$('inspect').hidden=false;inspectUntil=performance.now()+5500;}
 function querySelect(value){guided=false;guide.pause();query=value;manualOperation=2;manualProgress=0;world.updateFrame(present());$('query').value=value;lastOperation=-1;refresh();}
 function setRoute(open){$('route').hidden=!open;$('route-toggle').setAttribute('aria-expanded',String(open));if(open){controls?.release();keys.clear();touch.clear();}else world?.canvas.focus({preventScroll:true});}
 guide=new Guide({getClip,AudioClass,onAdvance:()=>false,onChange:()=>{refresh();save();},gap:3});guide.automatic=false;
 try{world ||= worldFactory($('world'),{es,onInspect:info=>showInspect(info.text),onAction:info=>{if(info.action==='listen')listenAt(info.index);else if(info.action==='query')querySelect(info.query);}});syncQuery();world.updateFrame(present());}
 catch(error){world?.dispose();world=null;guide.dispose();$('app').innerHTML=`<section class="fallback"><h1>${t('El modo 3D no está disponible en este navegador.','3D mode is unavailable in this browser.')}</h1><a href="../llms/index.html">${t('Abrir cuaderno','Open notebook')} →</a></section>`;return {guide,dispose(){},get state(){return {run,player,frame:frameLLM};}};}
 if(world){
  controls=binder({canvas:world.canvas,document,window,coarse:matchMedia('(pointer: coarse)').matches,enabled:()=>started&&$('route').hidden,onLook(dx,dy){if(!dx&&!dy)return;if(travel||guided)pause();player.yaw-=dx*.0023;player.pitch=Math.max(-1.15,Math.min(1.15,player.pitch-dy*.0023));save();},onActivate:(x,y)=>world.inspect(x,y),onState(state){document.body.dataset.camera=state;$('lock').textContent=state==='locked'?t('Esc · liberar ratón','Esc · release mouse'):t('Activar ratón','Enable mouse');}});
  function start(auto){started=true;$('welcome').hidden=true;guided=auto;player=world.arrivalPose?.(0)||poseAt(0);select(0);if(auto)guide.enter();controls.request();world.canvas.focus({preventScroll:true});refresh();}
  $('start-free').onclick=()=>start(false);$('start-tour').onclick=()=>start(true);$('lock').onclick=()=>controls.locked()?controls.release():controls.request();
  $('listen').onclick=()=>listenAt(run.phase);$('tour').onclick=()=>{if(guided){pause();return;}guided=true;go(run.phase);};$('next').onclick=()=>{stopTravel();next();};
  $('route-toggle').onclick=()=>setRoute($('route').hidden);$('route-close').onclick=()=>setRoute(false);
  $('reader-toggle').onclick=()=>{const compact=document.body.classList.toggle('reader-compact');$('reader-toggle').setAttribute('aria-expanded',String(!compact));$('reader-toggle').textContent=compact?t('Mostrar texto','Show text'):t('Ocultar texto','Hide text');};
  for(const b of document.querySelectorAll('[data-stop]'))b.onclick=()=>{stopTravel();setRoute(false);go(+b.dataset.stop);};
  for(const b of document.querySelectorAll('[data-listen]'))b.onclick=()=>listenAt(+b.dataset.listen);
  function setProgress(value){guided=false;travel=null;const p=Math.max(0,Math.min(1,Number.isFinite(Number(value))?Number(value):0)),clip=getClip(),cue=cueAt(clip.cues,p*clip.duration);manualOperation=cue.index;manualProgress=cue.progress;if(!guide.clip||!guide.enabled)guide.enter({offset:p*clip.duration,play:false});else guide.seek(p*clip.duration);guide.pause();lastOperation=-1;refresh();save();}
  for(const b of document.querySelectorAll('[data-operation]'))b.onclick=()=>{const cue=getClip().cues?.[+b.dataset.operation];if(cue)setProgress(cue.start/getClip().duration);};
  $('audio-time').oninput=()=>setProgress($('audio-time').value);
  $('query').onchange=e=>querySelect(+e.target.value);
  function changeLanguage(language){if(!['es','en'].includes(language))return;const old=guide.clip||getClip(),p=progress(),cue=run.phase===4?cueAt(old.cues,p*old.duration):null,running=guide.running;guide.stop();voiceLanguage=language;$('language').value=language;const next=getClip(),target=cue?next.cues?.[cue.index]:null,offset=target?target.start+cue.progress*(target.end-target.start):p*next.duration;manualOperation=cue?.index??0;manualProgress=cue?.progress??p;guide.enter({offset,play:running});refresh();save();}
  $('language').onchange=e=>changeLanguage(e.target.value);
  $('voice').onchange=e=>{guide.setEnabled(e.target.checked);refresh();save();};$('motion').onchange=save;
  $('temperature').oninput=e=>{run.options.temperature=Number(e.target.value);$('temperature-value').textContent=run.options.temperature.toFixed(2);world.updateFrame(present());save();};
  $('scenario').onchange=e=>{$('temperature').value=.7;$('temperature-value').textContent='0.70';pause();guide.stop();const phase=run.phase;run=createRun(lang,{scenario:e.target.value,retrieval:e.target.value==='museum'});queryKey='';select(phase);};
  const inputTarget=target=>target.closest?.('input,select,textarea,button,a,[tabindex="0"]:not(canvas)');
  listen(window,'keydown',e=>{if(e.code==='Escape'){controls.release();keys.clear();touch.clear();if(!$('route').hidden)setRoute(false);return;}if(!started||inputTarget(e.target)||!$('route').hidden)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();stopTravel();guide.pause();keys.add(e.code);save();}if(e.code==='KeyE'&&!e.repeat){e.preventDefault();nearbyListen();}if(e.code==='KeyM'&&!e.repeat){e.preventDefault();setRoute(true);}});
  listen(window,'keyup',e=>keys.delete(e.code));listen(window,'blur',()=>{pause();controls.release();});
  listen(document,'visibilitychange',()=>{if(document.hidden){pause();controls.release();}last=performance.now();});
  for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();stopTravel();guide.pause();touch.add(b.dataset.move);save();b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>touch.delete(b.dataset.move);}
  listen(window,'pagehide',e=>{save();if(!e.persisted)dispose();else pause();});
  restore();refresh();if(params.get('entrance')==='painting'){started=true;$('welcome').hidden=true;visited.add(0);refresh();}
  function tick(now){if(disposed)return;const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;
   if(!document.hidden){
    if(travel){travel.elapsed+=dt;player=travelPose(travel.from,travel.to,travel.elapsed/travel.duration);if(travel.elapsed>=travel.duration)arrive(travel.audio);}
    else if(started&&$('route').hidden){const input={forward:Number(keys.has('KeyW')||keys.has('ArrowUp')||touch.has('forward'))-Number(keys.has('KeyS')||keys.has('ArrowDown')||touch.has('back')),strafe:Number(keys.has('KeyD')||keys.has('ArrowRight')||touch.has('right'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')||touch.has('left'))};player=walk(player,input,dt);if(input.forward||input.strafe){const near=nearestStop(player);if(near.index!==run.phase&&near.distance<5)select(near.index);}}
    guide.tick(dt);if(guided&&guide.state==='ready'){if(run.phase===7){guided=false;refresh();}else next();}
    const clip=guide.clip||getClip(),p=progress(),cue=guide.running?cueAt(clip.cues,p*clip.duration):{index:manualOperation,progress:manualProgress};
    if(guide.running){manualOperation=cue.index;manualProgress=cue.progress;}world.renderFrame(present(),player,{dt,live:guide.running,reduced});
    uiTime+=dt;if(uiTime>.12){uiTime=0;const near=nearestStop(player);$('position').textContent=`${t('Estación','Station')} ${near.index+1} / 8 · ${run.generated.length} ${t('tokens emitidos','emitted tokens')}`;$('position').dataset.x=player.x;$('position').dataset.z=player.z;$('position').dataset.yaw=player.yaw;
     syncUIflow();
     const states={idle:t('Pulsa el botón del stand o Escuchar.','Press the stand button or Listen.'),loading:t('Cargando voz…','Loading voice…'),speaking:t('Escuchando · puedes explorar mientras tanto','Listening · you can explore meanwhile'),reading:t('Tiempo de lectura','Reading time'),paused:t('Voz en pausa','Voice paused'),waiting:t('Pausa para observar · ','Pause to observe · ')+Math.ceil(guide.remaining)+' s',ready:t('Explicación terminada','Explanation complete'),error:t('No se pudo cargar la voz. Pulsa Escuchar para reintentar.','Voice failed to load. Press Listen to retry.'),blocked:t('Pulsa Escuchar para permitir el audio.','Press Listen to allow audio.')};$('status').textContent=travel?t('Viajando a la estación…','Travelling to the station…'):states[guide.state]||'';
     for(const b of document.querySelectorAll('[data-listen]')){const p=world.projectStand(+b.dataset.listen,player);b.hidden=!started||!p.visible;b.style.left=p.x+'px';b.style.top=p.y+'px';}
     if(now>inspectUntil)$('inspect').hidden=true;save();
    }
   }requestAnimationFrame(tick);
  }requestAnimationFrame(tick);
  function restore(){let saved;try{saved=JSON.parse(storage.getItem(storageKey));}catch{}if(!saved||saved.version!==1)return;restoring=true;try{const opts={...DEFAULTS};if(['capital','bank','museum'].includes(saved.options?.scenario))opts.scenario=saved.options.scenario;for(const id of ['context','retrieval'])if(typeof saved.options?.[id]==='boolean')opts[id]=saved.options[id];if(['current','archive'].includes(saved.options?.source))opts.source=saved.options.source;if(['greedy','sample'].includes(saved.options?.decoding))opts.decoding=saved.options.decoding;if(Number.isFinite(saved.options?.temperature))opts.temperature=Math.max(0,Math.min(2,saved.options.temperature));if(Number.isInteger(saved.options?.seed))opts.seed=saved.options.seed>>>0;run=createRun(lang,opts);run.phase=Math.max(0,Math.min(7,Number.isInteger(saved.phase)?saved.phase:0));if(Number.isInteger(saved.chosen)&&saved.chosen>=0&&saved.chosen<3){const output=tokenize(run.data.completions[saved.chosen]);if(Array.isArray(saved.generated)&&saved.generated.length<=output.length&&saved.generated.every((v,i)=>v===output[i])){run.chosen=saved.chosen;run.outputTokens=output;run.generated=[...saved.generated];run.done=saved.done===true&&run.generated.length===output.length;run.loops=run.generated.length+(run.done?1:0);}}if(Number.isInteger(saved.seed))run.seed=saved.seed>>>0;const pose=saved.player;if(pose&&['x','z','yaw','pitch'].every(k=>Number.isFinite(pose[k])))player={x:Math.max(-10,Math.min(4.7,pose.x)),z:Math.max(-106,Math.min(10,pose.z)),yaw:Math.atan2(Math.sin(pose.yaw),Math.cos(pose.yaw)),pitch:Math.max(-1.15,Math.min(1.15,pose.pitch))};query=Number.isInteger(saved.query)?Math.max(0,Math.min(7,saved.query)):null;queryKey=JSON.stringify(contextWindow(run).tokens);voiceLanguage=['es','en'].includes(saved.language)?saved.language:lang;guide.enabled=saved.voice!==false;manualOperation=Number.isInteger(saved.manualOperation)?Math.max(0,Math.min(4,saved.manualOperation)):0;manualProgress=Number.isFinite(saved.manualProgress)?Math.max(0,Math.min(1,saved.manualProgress)):0;started=saved.started===true;$('welcome').hidden=started;$('language').value=voiceLanguage;$('voice').checked=guide.enabled;$('motion').checked=saved.instant===true;$('scenario').value=opts.scenario;$('temperature').value=opts.temperature;$('temperature-value').textContent=opts.temperature.toFixed(2);document.body.classList.toggle('reader-compact',saved.readerCompact===true);$('reader-toggle').setAttribute('aria-expanded',String(saved.readerCompact!==true));for(const i of saved.visited||[])if(Number.isInteger(i)&&i>=0&&i<8)visited.add(i);guide.enter({offset:Math.max(0,Math.min(1,Number.isFinite(saved.progress)?saved.progress:0))*getClip().duration,play:started&&saved.running===true});lastSaved=JSON.stringify(capture());}finally{restoring=false;}}
  function dispose(){if(disposed)return;save();disposed=true;cancelFrame(raf);listeners.forEach(remove=>remove());keys.clear();touch.clear();guide.dispose();controls.dispose();world.dispose();}
  return {guide,world,controls,select,listenAt,setProgress,changeLanguage,capture,dispose,get state(){return {run,player:{...player},query,manualOperation,manualProgress,frame:frameLLM,started,guided,travel,voiceLanguage,keys:new Set(keys),touch:new Set(touch)};}};

 }
}

}
if(typeof document!=='undefined'&&document.getElementById('app')&&!globalThis.__LLM_IMMERSIVE_CONTROLLER_TEST__)createLLMImmersiveController();
