// Every collision rectangle below is rendered as a wall, board support, or audio stand.
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
export const MODELS_ROOM=[-24,-10,24,10];
export const MODELS_LAYOUT=Array.from({length:12},(_,index)=>({index,x:-18+(index%6)*7.2,z:index<6?-7:7,yaw:index<6?0:Math.PI}));
export const MODELS_STANDS=MODELS_LAYOUT.map(s=>[s.x,1.15,s.z+(s.index<6?2.25:-2.25)]);
export const MODELS_FOCUS=MODELS_LAYOUT.map(s=>[s.x,2.1,s.z]);
export const MODELS_BOUNDS=MODELS_LAYOUT.map(s=>[s.x-2.45,.30,s.z-.45,s.x+2.45,4.38,s.z+.55]);
export const MODELS_WALLS=[[-24.12,-10.12,24.12,-9.88],[-24.12,9.88,24.12,10.12],[-24.12,-10,-23.88,10],[23.88,-10,24.12,10]];
export const MODELS_BOARD_SOLIDS=MODELS_LAYOUT.map(s=>[s.x-2.4,s.z-.28,s.x+2.4,s.z+.28]);
export const MODELS_STAND_SOLIDS=MODELS_STANDS.map(([x,y,z])=>[x-.24,z-.20,x+.24,z+.20]);
export const MODELS_SOLIDS=[...MODELS_WALLS,...MODELS_BOARD_SOLIDS,...MODELS_STAND_SOLIDS];
const index=n=>Math.floor(clamp(Number(n),0,11));
export const modelsCollision=(x,z,r=.24)=>MODELS_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);
export function modelsPoseAt(chapter=0){const s=MODELS_LAYOUT[index(chapter)];return {x:s.x,z:s.z+(s.index<6?4.35:-4.35),yaw:s.yaw,pitch:.05};}
export function restoreModelsPose(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return modelsPoseAt(0);const p={x:clamp(saved.x,-23.5,23.5),z:clamp(saved.z,-9.5,9.5),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return modelsCollision(p.x,p.z)?modelsPoseAt(0):p;}
export function modelsWalk(pose,dx,dz){if(typeof dx==='object'){const f=dx.forward||0,s=dx.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=2.5*clamp(dz,0,.05);dx=(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)/n*d;dz=(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)/n*d;}dx=Number.isFinite(dx)?dx:0;dz=Number.isFinite(dz)?dz:0;const count=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.10));let p={...pose};for(let i=0;i<count;i++){const x=clamp(p.x+dx/count,-23.5,23.5),z=clamp(p.z+dz/count,-9.5,9.5);if(!modelsCollision(x,p.z))p.x=x;if(!modelsCollision(p.x,z))p.z=z;}return p;}
export function modelsSegmentClear(a,b,r=.25,solids=MODELS_SOLIDS){for(const q of solids){let lo=0,hi=1,hit=true;const start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];for(let d=0;d<2;d++){const min=q[d]-r,max=q[d+2]+r;if(Math.abs(delta[d])<1e-12){if(start[d]<=min||start[d]>=max){hit=false;break;}}else{let near=(min-start[d])/delta[d],far=(max-start[d])/delta[d];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>=hi){hit=false;break;}}}if(hit&&hi>0&&lo<1)return false;}return true;}
export function modelsNearestStand(pose){let best=null;MODELS_STANDS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),yaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(yaw-pose.yaw),Math.cos(yaw-pose.yaw))),pitch=Math.atan2(y-1.65,distance);if(distance<2.45&&angle<.85&&Math.abs(pitch-(pose.pitch||0))<.60&&modelsSegmentClear(pose,{x,z},0,MODELS_SOLIDS.filter(b=>b!==MODELS_STAND_SOLIDS[index]))&&(!best||distance<best.distance))best={index,distance,angle,pitch};});return best;}
let grid;
function navigationGrid(){if(grid)return grid;const step=.35,minX=-23.5,minZ=-9.5,nx=135,nz=55,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*step,z=minZ+zi*step;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!modelsCollision(x,z,.25)});}return grid={step,nx,nz,nodes};}
export function modelsGuidePath(from,to){const start=restoreModelsPose(from),end=restoreModelsPose(to);if(modelsSegmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=navigationGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const v=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&v<d&&modelsSegmentClear(p,q)){best=q;d=v;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const open=new Set([first.index]),cost=new Map([[first.index,0]]),previous=new Map(),closed=new Set();let found=false;while(open.size){let current,best=Infinity;for(const id of open){const q=g.nodes[id],v=cost.get(id)+Math.hypot(q.x-last.x,q.z-last.z);if(v<best){best=v;current=q;}}open.delete(current.index);if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!modelsSegmentClear(current,q))continue;const v=cost.get(current.index)+g.step*Math.hypot(dx,dz);if(v<(cost.get(q.index)??Infinity)){cost.set(q.index,v);previous.set(q.index,current.index);open.add(q.index);}}}if(!found)return [];const points=[];for(let id=last.index;id!==undefined;id=previous.get(id)){points.push({x:g.nodes[id].x,z:g.nodes[id].z});if(id===first.index)break;}points.reverse();points.unshift({x:start.x,z:start.z});points.push({x:end.x,z:end.z});const result=[points[0]];for(let i=0;i<points.length-1;){let j=points.length-1;while(j>i+1&&!modelsSegmentClear(points[i],points[j]))j--;result.push(points[j]);i=j;}return result;}