import * as THREE from '../vendor/three.module.js';
import * as Model from './factory-model.js';
import {FAB_ROOM,FAB_WALLS,FAB_STATIONS,FAB_FURNITURE_SOLIDS,FAB_SOLIDS,FAB_STANDS,FAB_FOCUS,FAB_BOUNDS,fabPoseAt,restoreFabPose,fabWalk,fabNearestStand} from './walk.js';
export {FAB_ROOM,FAB_WALLS,FAB_STATIONS,FAB_FURNITURE_SOLIDS,FAB_SOLIDS,FAB_STANDS,FAB_FOCUS,FAB_BOUNDS,fabPoseAt,restoreFabPose,fabWalk,fabNearestStand};
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
const chapterIndex=n=>Math.floor(clamp(Number(n),0,5));
const vector=p=>Array.isArray(p)?p:[0,0,0];
const OP_STATIONS=Model.OPERATION_STATIONS;
const NAMES={input:['Entrada · FOUP','Input · FOUP'],deposit:['Deposición','Deposition'],track:['Resina · hornear · revelar','Resist · bake · develop'],expose:['Exposición óptica','Optical exposure'],etch:['Grabado · limpieza','Etch · clean'],inspect:['Metrología','Metrology'],probe:['Prueba eléctrica en oblea','Electrical wafer probe'],dice:['Separación de chips','Die separation'],package:['Encapsulado','Packaging'],final:['Prueba del conjunto','Assembly test']};
const CHAPTER_NAMES=[['Contexto y límites','Context and limits'],['Servicios y transporte protegido','Utilities and protected transport'],['Película y resina','Film and resist'],['Exponer y revelar','Expose and develop'],['Transferir, medir y repetir','Transfer, measure and repeat'],['Probar, separar y ensamblar','Probe, separate and assemble']];
const operationOf=frame=>Math.floor(clamp(Number(frame?.operationIndex??frame?.opIndex??frame?.step??frame?.index??(typeof frame?.operation==='number'?frame.operation:0)),0,12));
const chapterOf=frame=>frame?.chapter??(operationOf(frame)<3?2:operationOf(frame)<5?3:operationOf(frame)<9?4:5);
const stationOf=frame=>typeof frame?.stationId==='string'?frame.stationId:typeof frame?.operation?.stationId==='string'?frame.operation.stationId:OP_STATIONS[operationOf(frame)];
export const fabOverview={yaw:.40,pitch:.53,distance:10,whole:false,operation:null};
export function fabFraming(chapter=0,orbit={},aspect=1,fov=46,frame){let bounds=FAB_BOUNDS[orbit.whole?0:chapterIndex(chapter)];if(!orbit.whole&&Number.isInteger(orbit.operation)){const spec=FAB_STATIONS.find(s=>s.id===OP_STATIONS[orbit.operation]),[x,z]=spec.position;bounds=[x-1.85,.36,z-1.55,x+1.85,4.32,z+2.42];if(['lift','travel','lower'].includes(frame?.phase)&&frame?.wafer?.position){const p=frame.wafer.position;bounds=[p[0]-1.20,Math.min(.4,p[1]-.65),p[2]-1.20,p[0]+1.20,5.62,p[2]+1.20];}}if(!orbit.whole&&operationOf(frame)<=10&&frame?.wafer?.visible!==false&&Array.isArray(frame?.wafer?.position)){const p=frame.wafer.position;bounds=[Math.min(bounds[0],p[0]-.62),Math.min(bounds[1],p[1]-.08),Math.min(bounds[2],p[2]-.62),Math.max(bounds[3],p[0]+.62),Math.max(bounds[4],p[1]+.08),Math.max(bounds[5],p[2]+.62)];}if(!orbit.whole&&Number.isInteger(orbit.operation)&&frame){const op=orbit.operation;function include(lo,hi){bounds=[Math.min(bounds[0],lo[0]),Math.min(bounds[1],lo[1]),Math.min(bounds[2],lo[2]),Math.max(bounds[3],hi[0]),Math.max(bounds[4],hi[1]),Math.max(bounds[5],hi[2])];}if(op===10||op===11)include([.76,-.10,3.85],[2.44,2.26,5.15]);if(op>=11){const station=FAB_STATIONS.find(s=>s.id===OP_STATIONS[op]),[x,z]=station.position;include([x-4.25,1.4,z+2.0],[x-.55,4.60,z+5.0]);}if(op>=10&&frame.handler?.active)for(const p of[frame.handler.base,frame.handler.joint,frame.handler.end])if(Array.isArray(p))include([p[0]-.20,p[1]-.20,p[2]-.20],[p[0]+.20,p[1]+.20,p[2]+.20]);if(op>=11&&frame.package?.position){const p=frame.package.position;include([p[0]-.45,p[1]-.12,p[2]-.40],[p[0]+.45,p[1]+.31,p[2]+.40]);}for(const d of frame.dies||[])if(d.holder==='handler-1'||op>=11&&d.id===frame.selectedDieId){const p=d.position;include([p[0]-.13,p[1]-.03,p[2]-.13],[p[0]+.13,p[1]+.08,p[2]+.13]);}}
const center=new THREE.Vector3((bounds[0]+bounds[3])/2,(bounds[1]+bounds[4])/2,(bounds[2]+bounds[5])/2),yaw=orbit.yaw??fabOverview.yaw,pitch=orbit.pitch??fabOverview.pitch,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let distance=2;for(const x of[bounds[0],bounds[3]])for(const y of[bounds[1],bounds[4]])for(const z of[bounds[2],bounds[5]]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}return {center,direction,distance:distance*1.12*(orbit.distance??10)/10,bounds};}
export function createFabScene(es=true){
 const t=(a,b)=>es?a:b,scene=new THREE.Scene();scene.background=new THREE.Color(0xc6d4d8);scene.fog=new THREE.Fog(0xc6d4d8,40,90);const resources=[],owned=new Set(),targets=[],stands=[],own=r=>{if(!owned.has(r)){owned.add(r);resources.push(r);}return r;},release=r=>{if(owned.delete(r)){resources.splice(resources.indexOf(r),1);r.dispose();}};let disposed=false,lastFrame,activeChapter=0;
 const cube=own(new THREE.BoxGeometry(1,1,1)),cylinder=own(new THREE.CylinderGeometry(1,1,1,32)),sphere=own(new THREE.SphereGeometry(1,20,12)),materials=new Map();
 const mat=(color,extra={})=>{const key=String(color)+JSON.stringify(extra);if(!materials.has(key))materials.set(key,own(new THREE.MeshStandardMaterial({color,roughness:.58,metalness:.08,...extra})));return materials.get(key);};
 const palette={white:mat(0xebefed),ivory:mat(0xf1f2e9),steel:mat(0x93aab0,{metalness:.62,roughness:.3}),dark:mat(0x27424f),teal:mat(0x8bc8b8),film:mat(0x8edfc2,{metalness:.3,roughness:.36}),resist:mat(0xad9dd9),exposed:mat(0xf0ca79),silicon:mat(0x56778a,{metalness:.65,roughness:.26}),gold:mat(0xd8b271,{metalness:.4}),rejected:mat(0xaa7772),glass:mat(0xa8d5dd,{transparent:true,opacity:.2,depthWrite:false,roughness:.1})};
 function mesh(g,geo,m,p=[0,0,0]){const o=new THREE.Mesh(geo,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;g.add(o);return o;}
 function box(g,p,size,m=palette.white){const o=mesh(g,cube,m,p);o.scale.set(...size);return o;}
 function cyl(g,p,r,h,m=palette.steel){const o=mesh(g,cylinder,m,p);o.scale.set(r,h,r);return o;}
 function ball(g,p,size,m=palette.steel){const o=mesh(g,sphere,m,p);o.scale.set(...(Array.isArray(size)?size:[size,size,size]));return o;}
 function rod(g,a,b,r=.035,m=palette.steel){const o=cyl(g,[0,0,0],r,1,m);setRod(o,new THREE.Vector3(...a),new THREE.Vector3(...b),r);return o;}
 function setRod(o,a,b,r=.035){const delta=new THREE.Vector3().subVectors(b,a),length=delta.length();o.position.copy(a).add(b).multiplyScalar(.5);o.scale.set(r,Math.max(.0001,length),r);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),length?delta.multiplyScalar(1/length):new THREE.Vector3(0,1,0));}
 function caption(g,initial,p,width=2,maxHeight=.18){const m=new THREE.Sprite(own(new THREE.SpriteMaterial({transparent:true,depthWrite:false}))),cache=new Map();m.position.set(...p);g.add(m);let last;function set(value){const text=String(value);if(text===last)return;last=text;let entry=cache.get(text);if(!entry){const c=document.createElement('canvas'),ctx=c.getContext('2d');ctx.font='600 54px system-ui';c.width=Math.max(100,Math.min(1800,ctx.measureText(text).width+40));c.height=80;ctx.fillStyle='#27424ff0';ctx.fillRect(0,0,c.width,80);ctx.font='600 54px system-ui';ctx.fillStyle='#f5eee0';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,c.width/2,40,c.width-30);const texture=own(new THREE.CanvasTexture(c));texture.colorSpace=THREE.SRGBColorSpace;const w=Math.min(width,maxHeight*c.width/80);entry={texture,w,h:w*80/c.width};cache.set(text,entry);if(cache.size>64){const [key,old]=cache.entries().next().value;cache.delete(key);release(old.texture);}}m.material.map=entry.texture;m.material.needsUpdate=true;m.scale.set(entry.w,entry.h,1);}set(initial);return {m,set,cache};}
 function info(o,a,b=a){o.userData.info=[a,b];targets.push(o);return o;}
 scene.add(new THREE.HemisphereLight(0xeaf6ff,0x82989b,2.45));const light=new THREE.DirectionalLight(0xfff4de,3.0);light.position.set(-10,15,12);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-15,right:15,top:13,bottom:-13,near:.1,far:45});light.shadow.normalBias=.02;scene.add(light);own(light.shadow);
 const architecture=new THREE.Group();scene.add(architecture);const floor=box(architecture,[-.5,-.12,.25],[23.2,.24,14.3],mat(0xb4c4c5,{roughness:.9}));for(let x=-11.5;x<11;x+=1)box(architecture,[x,.006,.25],[.014,.008,14.1],mat(0x91aaad));for(let z=-6.5;z<7.3;z+=1)box(architecture,[-.5,.006,z],[23,.008,.014],mat(0x91aaad));
 const wallMat=mat(0xd8e5e4,{transparent:true,opacity:.10,depthWrite:false}),walls=FAB_WALLS.map(b=>box(architecture,[(b[0]+b[2])/2,2.95,(b[1]+b[3])/2],[b[2]-b[0],5.9,b[3]-b[1]],wallMat)),ceiling=box(architecture,[-.5,5.97,.25],[23,.12,14.1],palette.white);ceiling.visible=false;const filtersGroup=new THREE.Group();architecture.add(filtersGroup);const filters=[];for(const x of[-10,-6,-2,2,6,10])for(const z of[-4,2]){const filter=box(filtersGroup,[x,5.80,z],[2.55,.13,1.50],palette.ivory);for(let i=-3;i<=3;i++)box(filtersGroup,[x+i*.32,5.72,z],[.018,.025,1.30],palette.steel);filters.push(filter);}
 const rails=new THREE.Group();architecture.add(rails);for(const z of[-2.2,3.8])rod(rails,[-10,5.15,z],[8,5.15,z],.055,palette.steel);for(const x of[-10,8])rod(rails,[x,5.15,-2.2],[x,5.15,3.8],.055,palette.steel);
 const stations={},stationGroups=new THREE.Group();scene.add(stationGroups);
 for(const spec of FAB_STATIONS){const [x,z]=spec.position,g=new THREE.Group();g.position.set(x,0,z);stationGroups.add(g);const record={id:spec.id,group:g,body:null,arm:{},door:null,chamber:null,cutaway:[],frontBars:[]};stations[spec.id]=record;
  if(spec.id==='input'){for(const side of[-.7,.7])box(g,[side,1.55,0],[.08,2.5,1.1],palette.steel);for(const y of[.3,1.15,2.55])box(g,[0,y,0],[1.5,.06,1.3],palette.white);box(g,[0,1.12,1.8],[1.5,.06,1.5],palette.steel);record.body=g.children[0];}
  else{record.body=box(g,[-1.28,1.35,0],[.16,2.70,2.35],own(new THREE.MeshStandardMaterial({color:0xebefed,roughness:.58,metalness:.08,transparent:true,opacity:1})));record.leftPanel=record.body;record.rightPanel=box(g,[1.28,1.35,0],[.16,2.70,2.35],own(new THREE.MeshStandardMaterial({color:0xebefed,roughness:.58,metalness:.08,transparent:true,opacity:1})));record.cutaway.push(record.rightPanel);box(g,[0,.25,0],[2.55,.50,2.35],palette.white);record.roof=box(g,[0,2.62,0],[2.55,.18,2.35],palette.white);box(g,[0,1.50,-1.17],[2.40,2.05,.08],palette.dark);box(g,[0,1.12,1.8],[1.5,.06,1.5],palette.steel);for(const sx of[-.65,.65])box(g,[sx,.54,1.8],[.09,1.08,1.3],palette.white);
   const chamber=new THREE.Group();g.add(chamber);record.chamber=chamber;const chuck=cyl(chamber,[0,1.63,0],.63,.08,palette.steel);record.chuck=chuck;for(const sy of[.66,2.42])record.frontBars.push(box(g,[0,sy,1.15],[2.55,.08,.08],palette.steel));
   const door=new THREE.Group();door.position.set(-1.20,1.65,1.205);g.add(door);record.door=door;box(door,[1.20,0,0],[2.36,1.38,.035],palette.glass);for(const dy of[-.72,.72]){const bar=box(door,[1.20,dy,0],[2.40,.045,.045],palette.steel);if(dy>0)record.doorTop=bar;}for(const dx of[.02,2.38])box(door,[dx,0,0],[.045,1.48,.045],palette.steel);
   if(spec.kind==='chamber'){const vessel=mesh(chamber,own(new THREE.CylinderGeometry(.89,.89,.95,40,1,true)),own(new THREE.MeshStandardMaterial({color:0x97b0b4,metalness:.6,roughness:.3,side:THREE.DoubleSide,transparent:true,opacity:.12,depthWrite:false})),[0,1.76,0]);record.vessel=vessel;const lid=cyl(chamber,[0,2.24,0],.91,.10,palette.steel);record.lid=lid;for(const sx of[-.78,.78])rod(chamber,[sx,.56,-.78],[sx,1.45,-.78],.065,palette.gold);}
   if(spec.kind==='track'){for(const sx of[-.83,.83])cyl(chamber,[sx,1.62,-.52],.30,.10,palette.steel);record.coatHead=rod(chamber,[.72,2.15,0],[0,2.15,0],.035,palette.gold);cyl(chamber,[0,2.07,0],.07,.18,palette.steel);}
   if(spec.kind==='scanner'){record.optics=cyl(chamber,[0,2.28,0],.30,.55,palette.dark);record.opticRoof=box(chamber,[0,2.68,-.08],[1.45,.06,1.0],palette.steel);box(chamber,[0,1.50,0],[1.35,.12,1.3],palette.dark);for(const side of[-.94,.94])rod(chamber,[side,.65,0],[side,2.35,0],.08,palette.steel);record.exposureBeam=mesh(chamber,own(new THREE.CylinderGeometry(.11,.42,.45,24,1,true)),mat(0xf4d68b,{transparent:true,opacity:.15,depthWrite:false,emissive:0xe8bb6d,emissiveIntensity:.2}),[0,1.98,0]);record.exposureBeam.visible=false;}
   if(spec.kind==='metrology'){rod(chamber,[.86,1.0,-.4],[.86,2.2,-.4],.07,palette.steel);rod(chamber,[.86,2.2,-.4],[0,2.2,0],.06,palette.steel);cyl(chamber,[0,2.10,0],.13,.26,palette.dark);}
   if(spec.kind==='test'){record.testPanel=new THREE.Group();record.testPanel.position.set(.89,1.94,-.75);chamber.add(record.testPanel);box(record.testPanel,[0,0,0],[.52,.38,.18],palette.dark);record.testContacts=[];for(const side of[-1,1])record.testContacts.push(rod(chamber,[side*.46,1.53,-.72],[side*.35,1.735,0],.018,palette.gold));}
   if(spec.kind==='dice'){record.sawHead=new THREE.Group();record.sawHead.position.set(0,2.03,0);chamber.add(record.sawHead);const saw=cyl(record.sawHead,[0,0,0],.24,.030,palette.steel);saw.rotation.z=Math.PI/2;box(record.sawHead,[.16,.09,-.07],[.26,.23,.20],palette.dark);}
   if(spec.kind==='package'){box(chamber,[0,1.56,0],[1.30,.10,1.15],palette.dark);for(const side of[-.8,.8])rod(chamber,[side,1.0,-.5],[side,2.34,-.5],.052,palette.steel);rod(chamber,[-.8,2.34,-.5],[.8,2.34,-.5],.06,palette.steel);}
   const screen=box(g,[.95,2.03,1.21],[.48,.43,.035],palette.dark);box(g,[.95,2.03,1.234],[.41,.34,.014],mat(0x98cbbb,{emissive:0x41665b,emissiveIntensity:.12}));record.screen=screen;
  }
  const base=rod(scene,[x+1.04,1.7,z+.85],[x+.55,1.7,z+1.3],.035,palette.steel),forearm=rod(scene,[x+.55,1.7,z+1.3],[x,1.7,z+1.8],.028,palette.steel),hand=box(scene,[x,1.66,z+1.8],[.78,.035,.65],palette.steel);const endpoint=new THREE.Object3D();scene.add(endpoint);record.arm={base,forearm,hand,endpoint,kind:'blade'};record.title=caption(g,t(...NAMES[spec.id]),[0,2.91,1.28],2.50,.17);record.status=caption(g,'',[0,2.73,1.28],2.35,.13);info(record.body,t('Equipo genérico · interior didáctico y ampliado. No es una máquina contratada por Terafab.','Generic tool · educational enlarged interior. Not a tool contracted by Terafab.'));
 }
 const carrier=new THREE.Group();scene.add(carrier);box(carrier,[0,.155,0],[.92,.31,1.12],palette.dark);for(const sx of[-.48,.48])cyl(carrier,[sx,.13,0],.10,.07,palette.steel).rotation.z=Math.PI/2;const hoist=rod(scene,[0,4.4,0],[0,2.5,0],.018,palette.steel),foup=new THREE.Group();scene.add(foup);for(const sx of[-.66,.66])box(foup,[sx,0,0],[.07,1.10,1.4],palette.gold);box(foup,[0,-.55,0],[1.38,.05,1.4],palette.gold);box(foup,[0,.55,0],[1.38,.05,1.4],palette.gold);box(foup,[0,0,-.68],[1.38,1.10,.04],palette.dark);for(let i=0;i<7;i++)for(const sx of[-.6,.6])box(foup,[sx,-.40+i*.13,0],[.09,.015,1.12],palette.steel);const foupDoor=box(foup,[0,0,.72],[1.38,1.10,.045],palette.gold);box(foup,[0,.62,0],[.62,.12,.34],palette.dark);info(foupDoor,t('FOUP: recipiente cerrado que protege las obleas durante el transporte.','FOUP: an enclosed container protects wafers during transport.'));
 const wafer=new THREE.Group();scene.add(wafer);const waferBody=cyl(wafer,[0,0,0],.58,.08,palette.silicon);const remnantShape=new THREE.Shape();remnantShape.absarc(0,0,.58,0,Math.PI*2,false);for(let i=0;i<9;i++){const x=(i%3-1)*.28,y=(Math.floor(i/3)-1)*.28,path=new THREE.Path();path.moveTo(x-.115,y-.115);path.lineTo(x-.115,y+.115);path.lineTo(x+.115,y+.115);path.lineTo(x+.115,y-.115);path.closePath();remnantShape.holes.push(path);}const remnant=mesh(wafer,own(new THREE.ExtrudeGeometry(remnantShape,{depth:.08,bevelEnabled:false,curveSegments:48})),palette.silicon,[0,-.04,0]);remnant.rotation.x=-Math.PI/2;remnant.visible=false;const waferCells=[],sectionGroup=new THREE.Group();scene.add(sectionGroup);const sectionBase=box(sectionGroup,[0,0,0],[3.24,.20,.26],palette.silicon),sectionCells=[];
 for(let i=0;i<9;i++){const x=(i%3-1)*.28,z=(Math.floor(i/3)-1)*.28,film=box(wafer,[x,.036,z],[.22,.020,.22],palette.film),resist=box(wafer,[x,.056,z],[.22,.020,.22],palette.resist);waferCells.push({film,resist});const sx=-1.44+i*.36,sFilm=box(sectionGroup,[sx,.20,0],[.34,.20,.26],palette.film),sResist=box(sectionGroup,[sx,.40,0],[.34,.20,.26],palette.resist);sectionCells.push({film:sFilm,resist:sResist});}
 const sectionCaption=caption(sectionGroup,t('Sección ampliada · 9 celdas de ejemplo','Magnified section · 9 example cells'),[0,.76,0],3.24,.17);info(sectionBase,t('Ampliación del mismo estado de material. Colores y espesores no están a escala.','Magnification of the same material state. Colors and thicknesses are not to scale.'));info(waferBody,t('Oblea de ejemplo: las nueve celdas visibles corresponden al corte ampliado. No indican una cantidad o tamaño real de chips.','Example wafer: its nine visible cells correspond to the magnified section. They do not assert a real die count or size.'));
 const dies=Array.from({length:9},(_,i)=>{const g=new THREE.Group();scene.add(g);const body=box(g,[0,0,0],[.23,.03,.23],palette.silicon);const dieFilm=box(g,[0,.019,0],[.19,.008,.19],palette.film);const circuitSegments=Array.from({length:6},()=>rod(g,[0,0,0],[0,.001,0],.004,palette.gold));return {id:'die-'+i,group:g,body,film:dieFilm,connections:circuitSegments,circuitSegments};});
 const rack=new THREE.Group();rack.position.set(1.6,0,4.5);scene.add(rack);box(rack,[0,1.66,0],[1.18,.10,1.18],palette.dark);for(const sx of[-.51,.51])for(const sz of[-.51,.51])box(rack,[sx,.80,sz],[.045,1.6,.045],palette.steel);for(let i=0;i<4;i++){box(rack,[-.45+i*.30,1.715,0],[.012,.035,.96],palette.steel);box(rack,[0,1.715,-.45+i*.30],[.96,.035,.012],palette.steel);}const rackCaption=caption(rack,t('Chips de ejemplo · se conservan','Example dies · retained'),[0,2.10,0],1.55,.15);
 const packageGroup=new THREE.Group();scene.add(packageGroup);const packageBody=box(packageGroup,[0,0,0],[.88,.06,.78],palette.gold),packageConnections=[];for(const side of[-1,1])packageConnections.push(rod(packageGroup,[side*.15,.08,0],[side*.35,.035,0],.018,palette.steel));const enclosure=box(packageGroup,[0,.14,0],[.84,.25,.74],mat(0x536b73,{transparent:true,opacity:.48,depthWrite:false}));for(let i=0;i<4;i++)for(const side of[-1,1])ball(packageGroup,[side*.27,-.065,-.24+i*.16],.025,palette.steel);const packageRecord={group:packageGroup,body:packageBody,connections:packageConnections,enclosure};
 const detailGroup=new THREE.Group(),detailModel=new THREE.Group();scene.add(detailGroup);detailGroup.add(detailModel);detailGroup.userData={representsId:'package-1',countsAsObject:false,isIllustration:true};detailModel.userData={representsId:'package-1',countsAsObject:false,isIllustration:true};const detailBody=box(detailModel,[0,0,0],[.88,.06,.78],packageBody.material),detailConnections=packageConnections.map(()=>rod(detailModel,[0,0,0],[0,.001,0],.018,palette.steel)),detailEnclosure=box(detailModel,[0,.14,0],[.84,.25,.74],enclosure.material),detailDieGroup=new THREE.Group();detailModel.add(detailDieGroup);detailDieGroup.position.set(...Model.FACTORY_LAYOUT.packageDieLocal);detailDieGroup.userData={representsId:null,countsAsObject:false,isIllustration:true};const detailDieBody=box(detailDieGroup,[0,0,0],[.23,.03,.23],palette.silicon),detailDieFilm=box(detailDieGroup,[0,.019,0],[.19,.008,.19],palette.film),detailCircuitSegments=Array.from({length:6},()=>rod(detailDieGroup,[0,0,0],[0,.001,0],.004,palette.gold)),detailDiePads=Array.from({length:2},()=>box(detailDieGroup,[0,.02,0],[.023,.008,.038],palette.gold)),detailPackagePads=[-1,1].map(side=>box(detailModel,[side*.35,.035,0],[.048,.01,.080],palette.steel));for(let i=0;i<4;i++)for(const side of[-1,1])ball(detailModel,[side*.27,-.065,-.24+i*.16],.025,palette.steel);const detailCaption=caption(detailGroup,t('Detalle ampliado · mismo paquete','Magnified detail · same package'),[0,1.78,0],3.55,.18),detailCaptionScale=detailCaption.m.scale.clone(),packageDetail={group:detailGroup,model:detailModel,body:detailBody,die:{group:detailDieGroup,body:detailDieBody,film:detailDieFilm,pads:detailDiePads,circuitSegments:detailCircuitSegments},pads:detailPackagePads,connections:detailConnections,enclosure:detailEnclosure,caption:detailCaption,state:null};detailGroup.visible=false;
 const gantryRails=new THREE.Group();architecture.add(gantryRails);for(const z of[2,4.5])rod(gantryRails,[-8,3.6,z],[1.6,3.6,z],.035,palette.steel);for(const x of[-8,1.6])rod(gantryRails,[x,3.6,2],[x,3.6,4.5],.035,palette.steel);const handlerEndpoint=new THREE.Object3D();scene.add(handlerEndpoint);const handler={kind:'pickup',endpoint:handlerEndpoint,base:rod(scene,[0,3.3,0],[0,3.3,0],.04,palette.steel),forearm:rod(scene,[0,3.3,0],[0,1.7,0],.035,palette.steel),hand:box(scene,[0,1.8,0],[.25,.20,.25],palette.dark)};info(packageBody,t('Encapsulado de ejemplo con un chip válido, soporte y dos conexiones ilustrativas.','Example package with one valid die, support and two illustrative connections.'));
 const standsGroup=new THREE.Group();scene.add(standsGroup);for(let i=0;i<6;i++){const [x,y,z]=FAB_STANDS[i],g=new THREE.Group();g.position.set(x,0,z);standsGroup.add(g);box(g,[0,.05,0],[.48,.10,.42],palette.dark);rod(g,[0,.1,0],[0,y-.18,0],.055,palette.steel);const button=box(g,[0,y,0],[.43,.30,.13],own(new THREE.MeshStandardMaterial({color:0x91d6bd,roughness:.55,emissive:0x64bfa0,emissiveIntensity:.12})));button.userData.action=i;button.userData.chapter=i;stands.push(button);targets.push(button);caption(g,String(i+1).padStart(2,'0')+' · '+t('ESCUCHAR','LISTEN'),[0,y-.25,.13],.85,.09);caption(g,t(...CHAPTER_NAMES[i]),[0,y-.42,.13],1.3,.11);}
 const probeHead=new THREE.Group();scene.add(probeHead);box(probeHead,[0,.07,0],[.45,.14,.28],palette.dark);const needles=Array.from({length:2},()=>{const m=rod(scene,[0,0,0],[0,.45,0],.010,palette.gold),tip=new THREE.Object3D();scene.add(tip);return {mesh:m,tip};});
 const circuitView=new THREE.Group();scene.add(circuitView);const circuitNodes=Array.from({length:4},(_,i)=>ball(circuitView,[-.9+i*.6,0,0],.075,palette.gold)),circuitWires=Array.from({length:6},()=>rod(circuitView,[0,0,0],[.01,0,0],.028,palette.gold)),circuitCaption=caption(circuitView,t('Red de ejemplo · continuidad, no función del chip','Example network · continuity, not chip function'),[0,.32,0],2.8,.16),circuitResult=caption(circuitView,'',[0,.64,0],2.4,.16);
 const condensedLayers=Array.from({length:3},(_,i)=>box(sectionGroup,[0,-.30-i*.11,0],[2.7,.055,.22],i===2?palette.gold:i===1?palette.ivory:palette.teal));const condensedCaption=caption(sectionGroup,t('Resumen de estructuras · receta omitida','Structure summary · recipe omitted'),[0,1.07,0],2.7,.14);
 const contactMarker=ball(scene,[0,0,0],.055,mat(0xf3d894,{emissive:0xc2a45f,emissiveIntensity:.20}));contactMarker.visible=false;
 const parts={architecture,floor,walls,ceiling,filtersGroup,filters,rails,gantryRails,stations,stationGroups,carrier,hoist,foup,foupDoor,wafer:{group:wafer,body:waferBody,remnant,cells:waferCells},section:{group:sectionGroup,body:sectionBase,cells:sectionCells,caption:sectionCaption},dies,rack,rackCaption,package:packageRecord,packageDetail,handler,probeHead,needles,circuitView,circuitNodes,circuitWires,circuitCaption,circuitResult,condensedLayers,condensedCaption,stands,contactMarker,furnitureSolids:FAB_FURNITURE_SOLIDS};
 function pose(g,state){g.visible=!!state&&state.visible!==false;if(!state)return;g.position.set(...vector(state.position));if(Array.isArray(state.rotation))g.rotation.set(...state.rotation);else if(Array.isArray(state.quaternion))g.quaternion.fromArray(state.quaternion);else g.rotation.set(0,0,0);g.userData.objectId=state.id;g.userData.holder=state.holder??null;g.userData.state=state;}
 function arm(record,state){const s=state||{},a=new THREE.Vector3(...vector(s.base)),b=new THREE.Vector3(...vector(s.joint)),c=new THREE.Vector3(...vector(s.end));record.base.visible=record.forearm.visible=record.hand.visible=!!state&&state.active!==false;if(!state)return;setRod(record.base,a,b,.035);setRod(record.forearm,b,c,.028);record.hand.position.copy(c).add(new THREE.Vector3(0,record.kind==='pickup'?.10:-.0175,0));if(record.endpoint)record.endpoint.position.copy(c);record.hand.userData.target=c.toArray();record.hand.userData.holdingId=s.holdingId??null;}
 function update(frame,chapter=chapterOf(frame),whole=false,immersive=false){if(disposed||!frame)return;lastFrame=frame;activeChapter=chapterIndex(chapter);wallMat.opacity=immersive?1:.10;wallMat.depthWrite=immersive;walls.forEach(w=>w.castShadow=immersive);ceiling.visible=immersive;filtersGroup.visible=immersive||whole;rails.visible=immersive||whole||['lift','travel','lower'].includes(frame.phase);
  pose(wafer,frame.wafer);waferBody.visible=Number(frame.wafer?.cutProgress)<=0;remnant.visible=Number(frame.wafer?.cutProgress)>0;pose(foup,frame.foup);foupDoor.position.y=clamp(frame.foup?.lidOpen)*1.12;pose(carrier,frame.carrier);if(frame.carrier&&frame.foup){setRod(hoist,new THREE.Vector3(...frame.carrier.position),new THREE.Vector3(...frame.foup.position).add(new THREE.Vector3(0,.60,0)),.018);hoist.visible=frame.carrier.active===true&&(immersive||whole||['lift','travel','lower'].includes(frame.phase));}else hoist.visible=false;
  const section=frame.section||{},film=section.film||[],resist=section.resist||[],exposed=section.exposed||[];for(let i=0;i<9;i++){const f=clamp(Number(film[i])),r=clamp(Number(resist[i])),e=clamp(Number(exposed[i]));for(const [cell,baseY,h]of [[waferCells[i],.040,.020],[sectionCells[i],.10,.20]]){cell.film.visible=f>0&&(cell!==waferCells[i]||frame.wafer.remainingDieIds?.includes('die-'+i)!==false);cell.film.scale.y=h*f;cell.film.position.y=baseY+h*f/2;cell.resist.visible=r>0&&(cell!==waferCells[i]||frame.wafer.remainingDieIds?.includes('die-'+i)!==false);cell.resist.scale.y=h*r;cell.resist.position.y=baseY+h*f+h*r/2;cell.resist.material=e>.5?palette.exposed:palette.resist;cell.film.userData.amount=f;cell.resist.userData.amount=r;cell.resist.userData.exposed=e;}}
  const active=stations[stationOf(frame)]||stations.input;const displayAnchor=immersive?FAB_STANDS[activeChapter]:[active.group.position.x,3.15,active.group.position.z+.32];sectionGroup.position.set(displayAnchor[0],immersive?1.98:displayAnchor[1],immersive?displayAnchor[2]-.30:displayAnchor[2]);sectionGroup.visible=!whole&&operationOf(frame)<=8;sectionCaption.m.visible=!immersive;
  for(const [id,record]of Object.entries(stations)){const s=frame.machines?.[id];record.state=s||null;const cutaway=id===active.id&&!whole,notebookCutaway=!immersive&&!whole;if(record.roof)record.roof.visible=immersive?!cutaway:whole;if(record.opticRoof)record.opticRoof.visible=immersive?!cutaway:whole;if(record.leftPanel){record.leftPanel.material.opacity=notebookCutaway?.12:1;record.leftPanel.material.depthWrite=!notebookCutaway;record.leftPanel.castShadow=!notebookCutaway;}if(record.rightPanel){record.rightPanel.material.opacity=cutaway||notebookCutaway?.12:1;record.rightPanel.material.depthWrite=!(cutaway||notebookCutaway);record.rightPanel.castShadow=!(cutaway||notebookCutaway);}record.group.userData.state=s;if(record.door){record.door.rotation.y=0;record.door.position.y=1.65+1.55*clamp(Number(s?.chamberOpen));}if(record.lid){record.lid.position.y=2.24+clamp(Number(s?.chamberOpen))*.65;record.lid.visible=immersive||whole;}record.frontBars.forEach((bar,i)=>bar.visible=i===0||immersive||whole);if(record.doorTop)record.doorTop.visible=immersive||whole;if(record.vessel){record.vessel.material.transparent=true;record.vessel.material.opacity=s?.active?.22:.12;record.vessel.material.depthWrite=false;}if(record.exposureBeam)record.exposureBeam.visible=!!s?.active;if(record.probeHead)record.probeHead.position.y=1.98-(s?.active?.20:0);arm(record.arm,s?.arm);record.status.set(s?.active?t('OPERACIÓN · tiempo comprimido','OPERATION · compressed time'):s?.doorOpen?t('PUERTO ABIERTO','PORT OPEN'):t('EN ESPERA','WAITING'));record.status.m.visible=!immersive&&id===active.id;record.title.m.visible=true;}
  for(let i=0;i<9;i++){const state=frame.dies?.[i];pose(dies[i].group,state);dies[i].id=state?.id??dies[i].id;dies[i].body.userData.valid=state?.valid??null;dies[i].body.userData.objectId=dies[i].id;dies[i].body.visible=state?.holder!=='wafer-1'||frame.wafer.cutProgress>0;dies[i].body.userData.partOfWafer=state?.holder==='wafer-1';dies[i].film.visible=dies[i].body.visible&&Number(film[i])>0;for(let j=0;j<dies[i].circuitSegments.length;j++){const edge=state?.circuit?.edges?.[Math.floor(j/2)],segment=edge?.segments?.[j%2],m=dies[i].circuitSegments[j],progress=clamp(Number(edge?.progress));m.visible=!!segment&&progress>0;if(m.visible){const a=new THREE.Vector3(...segment[0]),b=new THREE.Vector3(...segment[1]);b.lerp(a,1-progress);setRod(m,a,b,.004);m.userData.edgeId=edge.id;m.userData.broken=edge.broken;}}dies[i].body.material=state?.valid===false?palette.rejected:palette.silicon;}
  pose(packageGroup,frame.package);packageRecord.state=frame.package;const connections=frame.package?.connections||[];packageConnections.forEach((m,i)=>{const c=connections[i],progress=clamp(Number(c?.progress??c)),side=i===0?-1:1,pad=new THREE.Vector3(side*.075,.12,0),terminal=new THREE.Vector3(side*.35,.035,0),a=i===0?terminal:pad,b=i===0?pad:terminal,end=a.clone().lerp(b,progress);m.visible=progress>0;setRod(m,a,end,.018);m.userData.progress=progress;m.userData.connected=c?.connected===true;m.userData.from=a.toArray();m.userData.to=end.toArray();});const enclosureProgress=clamp(Number(frame.package?.enclosureProgress));enclosure.visible=enclosureProgress>0;enclosure.scale.y=.25*Math.max(.001,enclosureProgress);enclosure.position.y=enclosureProgress*.125;arm(handler,frame.handler?.arm??frame.handler);
  const detailOp=operationOf(frame),packagedDie=frame.dies?.find(d=>d.id===frame.package?.dieId),sourceDie=dies.find(d=>d.id===packagedDie?.id);packageDetail.state=frame.package;detailGroup.visible=detailOp>=11&&!whole;detailGroup.position.set(immersive?4:active.group.position.x-2.4,immersive?1.75:2.6,immersive?3.55:active.group.position.z+3.2);detailModel.rotation.set(immersive?Math.PI/2:.72,0,0);detailModel.scale.setScalar(immersive?1.8:3.8);detailCaption.m.position.set(0,immersive?1.03:1.78,0);detailCaption.m.scale.copy(detailCaptionScale).multiplyScalar(immersive?Math.min(1,2.15/detailCaptionScale.x):1);detailDieGroup.visible=!!packagedDie;detailDieGroup.userData.representsId=frame.package?.dieId??null;detailDieGroup.userData.state=packagedDie??null;detailBody.position.copy(packageBody.position);detailBody.quaternion.copy(packageBody.quaternion);detailBody.scale.copy(packageBody.scale);detailBody.material=packageBody.material;detailEnclosure.position.copy(enclosure.position);detailEnclosure.quaternion.copy(enclosure.quaternion);detailEnclosure.scale.copy(enclosure.scale);detailEnclosure.visible=enclosure.visible;detailEnclosure.userData.progress=enclosureProgress;packageConnections.forEach((source,i)=>{const target=detailConnections[i];target.position.copy(source.position);target.quaternion.copy(source.quaternion);target.scale.copy(source.scale);target.visible=source.visible;target.userData={...source.userData};});if(sourceDie){detailDieBody.material=sourceDie.body.material;detailDieFilm.visible=sourceDie.film.visible;detailDieFilm.material=sourceDie.film.material;sourceDie.circuitSegments.forEach((source,i)=>{const target=detailCircuitSegments[i];target.position.copy(source.position);target.quaternion.copy(source.quaternion);target.scale.copy(source.scale);target.visible=source.visible;target.userData={...source.userData};});const nodes=packagedDie.circuit?.nodes||[];for(let i=0;i<2;i++){const node=nodes.find(n=>n.id===(i===0?'in':'out'));detailDiePads[i].visible=!!node;if(node)detailDiePads[i].position.set(...node.position);detailDiePads[i].userData.nodeId=node?.id??null;}}else{detailDieFilm.visible=false;detailCircuitSegments.forEach(m=>m.visible=false);detailDiePads.forEach(m=>m.visible=false);}
  const probe=frame.probe;probeHead.visible=!!probe&&probe.active!==false;needles.forEach((n,i)=>{const needle=probe?.needles?.[i];n.mesh.visible=probeHead.visible&&!!needle;if(needle){setRod(n.mesh,new THREE.Vector3(...needle.base),new THREE.Vector3(...needle.tip),.010);n.tip.position.set(...needle.tip);n.mesh.userData.nodeId=needle.nodeId;n.mesh.userData.contact=!!probe.contact;}});if(probe?.head?.position)probeHead.position.set(...probe.head.position);
  condensedLayers.forEach((m,i)=>{const progress=clamp(Number(section.condensedLayers?.[i]?.progress));m.visible=progress>0;m.scale.x=2.70*Math.max(.001,progress);m.userData.progress=progress;m.userData.recipeOmitted=true;});condensedCaption.m.visible=operationOf(frame)===8&&!immersive;
  const op=operationOf(frame),circuitId=frame.quality?.probe?.activeDieId||frame.selectedDieId||'die-0',sample=frame.dies?.find(d=>d.id===circuitId)||frame.dies?.[0],showCircuit=op===9||op===10;circuitView.visible=showCircuit&&!whole;circuitView.position.set(active.group.position.x,op===8?4.15:3.20,active.group.position.z+.32);circuitView.userData.dieId=sample?.id;circuitCaption.m.visible=!immersive;circuitResult.m.visible=!immersive&&op>=9;circuitResult.set((sample?.id||'')+' · '+(sample?.valid===true?t('CONTINUIDAD VERIFICADA','CONTINUITY VERIFIED'):sample?.valid===false?t('CONEXIÓN ABIERTA DETECTADA','OPEN CONNECTION DETECTED'):t('MEDICIÓN PENDIENTE','MEASUREMENT PENDING')));for(let j=0;j<6;j++){const edge=sample?.circuit?.edges?.[Math.floor(j/2)],segment=edge?.segments?.[j%2],m=circuitWires[j],progress=clamp(Number(edge?.progress));m.visible=!!segment&&progress>0;if(m.visible){const a=new THREE.Vector3(segment[0][0]*12,0,0),b=new THREE.Vector3(segment[1][0]*12,0,0);b.lerp(a,1-progress);setRod(m,a,b,.028);m.userData.edgeId=edge.id;m.userData.broken=edge.broken;}}circuitNodes.forEach((m,i)=>m.visible=Number(sample?.circuit?.buildProgress)>0);
  const last=(frame.events||[]).filter(e=>Array.isArray(e.point)&&Number.isFinite(e.time)).at(-1);contactMarker.visible=!!last&&Math.abs((frame.time||0)-last.time)<.16;if(contactMarker.visible)contactMarker.position.set(...last.point);stands.forEach((s,i)=>{s.material.emissiveIntensity=i===activeChapter?.38:.12;});scene.updateMatrixWorld(true);
 }
 scene.updateMatrixWorld(true);return {scene,parts,stands,targets,resources,rooms:[{id:'lab',bounds:FAB_ROOM}],solids:FAB_SOLIDS,bounds:FAB_BOUNDS,update,get state(){return lastFrame;},dispose(){if(disposed)return;disposed=true;for(const resource of [...resources])resource.dispose();}};
}
function visible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
export function createFabWorld(host,es=true,onListen=()=>{},onInfo=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.10;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);const built=createFabScene(es),camera=new THREE.PerspectiveCamera(46,1,.055,140),ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),canvas=renderer.domElement,orbit={...fabOverview};let frame,chapter=0,mode='notebook',pose=fabPoseAt(0),dragging=false,lastX=0,lastY=0,pinch=0,pointerDown,disposed=false;canvas.tabIndex=0;
 function resize(){const width=Math.max(1,host.clientWidth),height=Math.max(1,host.clientHeight);renderer.setSize(width,height,false);camera.aspect=width/height;camera.fov=camera.aspect<1?64:46;camera.updateProjectionMatrix();}
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function draw(){if(disposed)return;const fov=mode==='immersive'?72:camera.aspect<1?64:46;if(camera.fov!==fov){camera.fov=fov;camera.updateProjectionMatrix();}if(frame)built.update(frame,chapter,orbit.whole&&mode!=='immersive',mode==='immersive');if(mode==='immersive'){camera.position.set(pose.x,1.65,pose.z);camera.rotation.set(pose.pitch,pose.yaw,0,'YXZ');}else{const f=fabFraming(chapter,orbit,camera.aspect,camera.fov,frame);camera.position.copy(f.center).addScaledVector(f.direction,f.distance);camera.lookAt(f.center);}camera.updateMatrixWorld();built.scene.updateMatrixWorld(true);renderer.render(built.scene,camera);}
 function hit(x,y){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return null;pointer.set(x===null?0:(x-r.left)/r.width*2-1,y===null?0:1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);const found=ray.intersectObjects(built.scene.children,true).filter(h=>visible(h.object)&&!h.object.isSprite);for(const h of found){const o=h.object;if(o.userData.action!==undefined||o.userData.info)return h;if(o.material?.opacity>.6)return null;}return null;}
 function inspect(x=null,y=null){const h=hit(x,y);if(!h)return null;const action=h.object.userData.action;if(action!==undefined)onListen(action);else if(h.object.userData.info)onInfo(h.object.userData.info);return action!==undefined?{chapter:action}:h.object.userData.info;}
 function activate(){const h=hit(null,null),index=h?.object.userData.action??fabNearestStand(pose)?.index;if(index!==null&&index!==undefined)onListen(index);return index??null;}
 const listeners=[],listen=(target,type,fn,options)=>{target.addEventListener(type,fn,options);listeners.push(()=>target.removeEventListener(type,fn,options));};
 listen(canvas,'pointerdown',e=>{if(mode==='immersive')return;dragging=true;lastX=e.clientX;lastY=e.clientY;pointerDown={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});listen(canvas,'pointermove',e=>{if(!dragging||mode==='immersive')return;orbit.yaw-=(e.clientX-lastX)*.005;orbit.pitch=clamp(orbit.pitch+(e.clientY-lastY)*.004,.12,1.35);lastX=e.clientX;lastY=e.clientY;draw();});listen(canvas,'pointerup',e=>{if(dragging&&pointerDown&&Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)<6)inspect(e.clientX,e.clientY);dragging=false;pointerDown=null;});listen(canvas,'pointercancel',()=>{dragging=false;pointerDown=null;});
 listen(canvas,'wheel',e=>{if(mode==='immersive')return;e.preventDefault();orbit.distance=clamp(orbit.distance*(e.deltaY>0?1.08:.92),4,35);draw();},{passive:false});listen(canvas,'touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});listen(canvas,'touchmove',e=>{if(mode==='immersive'||e.touches.length!==2)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch&&d){orbit.distance=clamp(orbit.distance*pinch/d,4,35);draw();}pinch=d;},{passive:true});listen(canvas,'keydown',e=>{if(mode==='immersive')return;if(e.key==='ArrowLeft')orbit.yaw-=.1;else if(e.key==='ArrowRight')orbit.yaw+=.1;else if(e.key==='ArrowUp')orbit.pitch=clamp(orbit.pitch-.08,.12,1.35);else if(e.key==='ArrowDown')orbit.pitch=clamp(orbit.pitch+.08,.12,1.35);else return;e.preventDefault();draw();});listen(canvas,'webglcontextlost',e=>e.preventDefault());
 function getViewState(){return {yaw:orbit.yaw,pitch:orbit.pitch,distance:orbit.distance,whole:orbit.whole,operation:orbit.operation,chapter};}
 function restoreViewState(saved={}){const s=saved&&typeof saved==='object'?(saved.orbit||saved):{};for(const key of['yaw','pitch','distance'])if(Number.isFinite(s[key]))orbit[key]=key==='distance'?clamp(s[key],4,35):key==='pitch'?clamp(s[key],.12,1.35):s[key];orbit.whole=s.whole===true;orbit.operation=Number.isInteger(s.operation)?Math.floor(clamp(s.operation,0,12)):null;if(Number.isFinite(s.chapter))chapter=chapterIndex(s.chapter);draw();}
 return {canvas,dom:canvas,scene:built.scene,built,camera,orbit,render(value,dt=0,index){if(value)frame=value;if(index!==undefined)chapter=chapterIndex(index);draw();},update(value,index){if(value)frame=value;if(index!==undefined)chapter=chapterIndex(index);},focus(index){chapter=chapterIndex(index);orbit.whole=false;orbit.operation=null;draw();},focusOperation(index){orbit.operation=Math.floor(clamp(index,0,12));orbit.whole=false;draw();},trackOperation(index){const next=Math.floor(clamp(index,0,12));if(orbit.operation===next&&!orbit.whole)return;orbit.operation=next;orbit.whole=false;draw();},fit(options={}){Object.assign(orbit,fabOverview,options);draw();},overview(all=true){orbit.whole=all!==false;orbit.operation=null;draw();},zoomBy(f){if(Number.isFinite(f)&&f>0)orbit.distance=clamp(orbit.distance/f,4,35);draw();},setMode(value){mode=value==='immersive'?'immersive':'notebook';dragging=false;draw();},setPose(value){pose=restoreFabPose(value);},getViewState,restoreViewState,inspect,activate,nearest:()=>fabNearestStand(pose)?.index??null,poseAt:fabPoseAt,walk:fabWalk,solids:FAB_SOLIDS,get stats(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};},dispose(){if(disposed)return;disposed=true;observer.disconnect();listeners.forEach(fn=>fn());built.dispose();renderer.dispose();canvas.remove();}};
}