// Navigation uses the same wall and equipment rectangles rendered by lab-world.js.
export const FAB_ROOM=[-12,-6.8,11,7.3];
export const FAB_WALLS=[[-12.08,-6.88,11.08,-6.72],[-12.08,-6.8,-11.92,7.3],[10.92,-6.8,11.08,7.3],[-12.08,7.22,-10.75,7.38],[-9.25,7.22,11.08,7.38]];
export const FAB_STATIONS=[{id:'input',position:[-10,-4],kind:'rack'},{id:'deposit',position:[-4,-4],kind:'chamber'},{id:'track',position:[0,-4],kind:'track'},{id:'expose',position:[4,-4],kind:'scanner'},{id:'etch',position:[8,-4],kind:'chamber'},{id:'inspect',position:[8,2],kind:'metrology'},{id:'probe',position:[4,2],kind:'probe'},{id:'dice',position:[0,2],kind:'dice'},{id:'package',position:[-4,2],kind:'package'},{id:'final',position:[-8,2],kind:'test'}];
export const FAB_FURNITURE_SOLIDS=FAB_STATIONS.map(s=>{const [x,z]=s.position,r=s.id==='input'?.78:1.4,d=s.id==='input'?.65:1.25;return [x-r,z-d,x+r,z+d];});
FAB_FURNITURE_SOLIDS.push([1.01,3.91,2.19,5.09]);
export const FAB_STANDS=[[-10,1.15,4.7],[-10,1.15,-1.15],[-2,1.15,-1.15],[4,1.15,-1.15],[8,1.15,-1.15],[4,1.15,4.7]];
export const FAB_STAND_SOLIDS=FAB_STANDS.map(([x,y,z])=>[x-.24,z-.21,x+.24,z+.21]);
export const FAB_SOLIDS=[...FAB_WALLS,...FAB_FURNITURE_SOLIDS,...FAB_STAND_SOLIDS];
export const FAB_FOCUS=[[-2,1.9,0],[-10,1.7,-2.9],[-2,1.7,-3.3],[3,1.7,-3.3],[8,1.7,-1],[ -2,1.7,2.7]];
export const FAB_BOUNDS=[[-12.15,-.15,-6.9,11.15,6.12,7.4],[-11.15,-.15,-5.1,-8.75,6.08,-.6],[-5.55,-.15,-5.5,1.55,6.08,-.6],[-1.55,-.15,-5.5,5.55,6.08,-.6],[6.45,-.15,-5.5,9.55,6.08,4.2],[-9.55,-.15,.4,5.55,6.08,5.3]];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
const chapter=n=>Math.floor(clamp(Number(n),0,5));
export function fabCollision(x,z,r=.24){return FAB_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);}
export function fabPoseAt(index=0){const i=chapter(index),s=FAB_STANDS[i],x=s[0],z=s[2]+1.35;return {x,z,yaw:0,pitch:.05};}
export function restoreFabPose(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return fabPoseAt(0);const pose={x:clamp(saved.x,-11.65,10.65),z:clamp(saved.z,-6.45,6.95),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return fabCollision(pose.x,pose.z)?fabPoseAt(0):pose;}
export function fabWalk(pose,input,dt){const f=input.forward||0,s=input.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=2.5*clamp(dt,0,.05),x=clamp(pose.x+(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)/n*d,-11.65,10.65),z=clamp(pose.z+(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)/n*d,-6.45,6.95),nextX=fabCollision(x,pose.z)?pose.x:x;return {...pose,x:nextX,z:fabCollision(nextX,z)?pose.z:z};}
export function fabSegmentClear(a,b,r=.25,solids=FAB_SOLIDS){for(const q of solids){let lo=0,hi=1;const start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];let intersects=true;for(let dim=0;dim<2;dim++){const min=q[dim]-r,max=q[dim+2]+r;if(Math.abs(delta[dim])<1e-12){if(start[dim]<=min||start[dim]>=max){intersects=false;break;}}else{let near=(min-start[dim])/delta[dim],far=(max-start[dim])/delta[dim];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>=hi){intersects=false;break;}}}if(intersects&&hi>0&&lo<1)return false;}return true;}
let grid;
function navigationGrid(){if(grid)return grid;const spacing=.20,minX=-11.65,minZ=-6.45,nx=112,nz=68,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*spacing,z=minZ+zi*spacing;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!fabCollision(x,z,.25)});}return grid={spacing,nx,nz,nodes};}
export function fabGuidePath(from,to){const start=restoreFabPose(from),end=restoreFabPose(to);if(fabSegmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=navigationGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const distance=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&distance<d&&fabSegmentClear(p,q)){best=q;d=distance;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const open=new Set([first.index]),cost=new Map([[first.index,0]]),prev=new Map(),closed=new Set();let found=false;while(open.size){let current,best=Infinity;for(const index of open){const q=g.nodes[index],score=cost.get(index)+Math.hypot(q.x-last.x,q.z-last.z);if(score<best){best=score;current=q;}}open.delete(current.index);if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!fabSegmentClear(current,q))continue;const candidate=cost.get(current.index)+g.spacing*Math.hypot(dx,dz);if(candidate<(cost.get(q.index)??Infinity)){cost.set(q.index,candidate);prev.set(q.index,current.index);open.add(q.index);}}}if(!found)return [];const ordered=[];for(let i=last.index;i!==undefined;i=prev.get(i)){ordered.push({x:g.nodes[i].x,z:g.nodes[i].z});if(i===first.index)break;}ordered.reverse();ordered.unshift({x:start.x,z:start.z});ordered.push({x:end.x,z:end.z});const route=[ordered[0]];let cursor=0;while(cursor<ordered.length-1){let next=ordered.length-1;while(next>cursor+1&&!fabSegmentClear(ordered[cursor],ordered[next]))next--;route.push(ordered[next]);cursor=next;}return route;}
export function fabNearestStand(pose){let best=null;FAB_STANDS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),targetYaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(targetYaw-pose.yaw),Math.cos(targetYaw-pose.yaw))),pitch=Math.atan2(y-1.65,distance),solids=FAB_SOLIDS.filter(s=>s!==FAB_STAND_SOLIDS[index]);if(distance<2.4&&angle<.85&&Math.abs(pitch-(pose.pitch||0))<.60&&fabSegmentClear(pose,{x,z},0,solids)&&(!best||distance<best.distance))best={index,distance,angle,pitch};});return best;}