import * as THREE from '../../vendor/three.module.js';
import * as Model from './model.js';
export const SPACE_VIEWS=['follow','booster','upper','overview'];
export const spaceOverview={yaw:.55,pitch:.27,distance:10,view:'follow'};
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
const fallbackLayout={visualScale:.1,falconLaunch:[0,.20,0],ASDS:{point:[16,.25,0],deckY:.25},RTLS:{point:[-6.5,.15,0],deckY:.15},starshipLaunch:[0,.90,0],tower:{point:[0,11,0],catchPlaneY:11},splashdown:{point:[34,0,0],waterY:0}};
const fallbackHardware={falcon:{boosterHeight:4.5,upperHeight:1.19,fairingHeight:1.31,upperAttach:[0,4.5,0],fairingAttach:[0,1.19,0],payloadLocal:[0,1.70,0],diameter:.37,legFootLocal:[0,-.10,0]},starship:{boosterHeight:7.2,shipHeight:5.2,upperAttach:[0,7.2,0],diameter:.9,catchPinLocal:[0,7.1,0]}};
export const SPACE_LAYOUT=Model.SPACE_LAYOUT||Model.FLIGHT_LAYOUT||fallbackLayout;
export const SPACE_HARDWARE=Model.HARDWARE||fallbackHardware;
const positionOf=p=>Array.isArray(p?.position)?p.position:[0,0,0];
const rotationOf=p=>Array.isArray(p?.rotation)?p.rotation:Array.isArray(p?.rotationEuler)?p.rotationEuler:[0,0,0];
const layoutPoint=(key,vehicle)=>{const selected=SPACE_LAYOUT[vehicle||(key==='tower'||key==='splashdown'?'starship':'falcon')]||SPACE_LAYOUT;const value=selected[key];if(Array.isArray(value))return value;if(Array.isArray(value?.point))return value.point;if(key==='launch'){const v=SPACE_LAYOUT[vehicle==='starship'?'starshipLaunch':'falconLaunch'];if(Array.isArray(v))return v;const p=selected.launch||SPACE_LAYOUT.launch?.[vehicle];if(Array.isArray(p))return p;}return fallbackLayout[key]?.point||fallbackLayout[key]||[0,0,0];};
const seed=n=>{const x=Math.sin(Number(n)*127.1+311.7)*43758.5453123;return x-Math.floor(x);};
function visible(m){for(let p=m;p;p=p.parent)if(!p.visible)return false;return true;}
const PLUME_VERTEX='varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}';
const PLUME_FRAGMENT='uniform vec3 uColor;uniform float uTime;uniform float uPower;varying vec2 vUv;void main(){float d=1.-vUv.y;float pulse=.91+.09*sin(uTime*39.+vUv.x*23.-d*19.);float fade=pow(1.-d,1.5);float throat=smoothstep(0.,.035,d);float diamonds=.75+.25*pow(abs(sin(d*24.)),4.);float a=fade*throat*pulse*uPower;gl_FragColor=vec4(uColor*(1.2+diamonds)*a,a*.75);}';
const SMOKE_VERTEX='attribute float aSize;attribute float aAlpha;attribute vec3 aColor;varying vec3 vColor;varying float vAlpha;uniform float uScale;void main(){vColor=aColor;vAlpha=aAlpha;vec4 mv=modelViewMatrix*vec4(position,1.);gl_PointSize=aSize*uScale/max(.1,-mv.z);gl_Position=projectionMatrix*mv;}';
const SMOKE_FRAGMENT='varying vec3 vColor;varying float vAlpha;void main(){float d=length(gl_PointCoord-.5);float a=smoothstep(.5,.06,d)*vAlpha;gl_FragColor=vec4(vColor*(1.-d*.5),a);}';
const SKY_VERTEX='varying vec3 vDirection;void main(){vDirection=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}';
const SKY_FRAGMENT='varying vec3 vDirection;void main(){vec3 d=normalize(vDirection);float h=max(0.,d.y);vec3 sky=mix(vec3(.30,.48,.59),vec3(.065,.16,.28),pow(h,.55));float band=smoothstep(.07,.18,h)*(1.-smoothstep(.32,.58,h));float n=.5+.27*sin(d.x*19.+d.z*13.)+.18*sin(d.x*39.-d.z*27.);float cloud=smoothstep(.66,.88,n)*band*.32;sky=mix(sky,vec3(.68,.74,.76),cloud);gl_FragColor=vec4(sky,1.);}';
const GROUND_VERTEX='varying vec3 vWorld;void main(){vec4 p=modelMatrix*vec4(position,1.);vWorld=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}';
const GROUND_FRAGMENT='varying vec3 vWorld;uniform float uTime;void main(){float coast=8.+sin(vWorld.z*.055)*1.1;float sea=step(coast,vWorld.x);float grain=fract(sin(dot(vWorld.xz,vec2(12.9898,78.233)))*43758.5453);vec3 land=mix(vec3(.13,.20,.17),vec3(.21,.24,.19),grain*.45);float wave=.5+.5*sin(vWorld.x*.7+vWorld.z*.4-uTime*.3);vec3 water=mix(vec3(.045,.14,.19),vec3(.09,.24,.29),wave*.18);float beach=smoothstep(coast-1.3,coast-.1,vWorld.x)*(1.-sea);gl_FragColor=vec4(mix(mix(land,vec3(.38,.37,.29),beach),water,sea),1.);}';

export function createSpaceScene(es=true){
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x173044);scene.fog=new THREE.Fog(0x284b60,120,250);const resources=[],owned=new Set(),targets=[],own=r=>{if(!owned.has(r)){owned.add(r);resources.push(r);}return r;};
 const boxGeo=own(new THREE.BoxGeometry(1,1,1)),cylinderGeo=own(new THREE.CylinderGeometry(1,1,1,24)),sphereGeo=own(new THREE.SphereGeometry(1,20,12)),matCache=new Map();
 const mat=(color,extra={})=>{const key=String(color)+JSON.stringify(extra);if(!matCache.has(key))matCache.set(key,own(new THREE.MeshStandardMaterial({color,roughness:.5,metalness:.08,...extra})));return matCache.get(key);};
 const envCanvas=document.createElement('canvas');envCanvas.width=256;envCanvas.height=128;const envCtx=envCanvas.getContext('2d');for(let y=0;y<128;y++){const sky=y<64,u=sky?y/64:(y-64)/64,r=sky?80+95*u:145-75*u,g=sky?127+62*u:153-60*u,b=sky?157+45*u:123-61*u;envCtx.fillStyle='rgb('+Math.round(r)+','+Math.round(g)+','+Math.round(b)+')';envCtx.fillRect(0,y,256,1);}envCtx.fillStyle='#fff2ce';envCtx.fillRect(40,31,12,8);const environment=own(new THREE.CanvasTexture(envCanvas));environment.mapping=THREE.EquirectangularReflectionMapping;environment.colorSpace=THREE.SRGBColorSpace;scene.environment=environment;scene.environmentIntensity=.45;
 const palette={white:mat(0xe9e9df,{roughness:.4}),dark:mat(0x252d35,{roughness:.6}),steel:mat(0xa9b7bd,{metalness:.8,roughness:.32}),warm:mat(0xdab680,{roughness:.65}),concrete:mat(0xa7aaa3,{roughness:.94}),tile:mat(0x20282a,{roughness:.95}),gold:mat(0xdba851,{metalness:.25}),nozzle:mat(0x59626b,{metalness:.85,roughness:.35})};
 function mesh(parent,geometry,material,p=[0,0,0]){const m=new THREE.Mesh(geometry,material);m.position.set(...p);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function box(parent,p,size,material=palette.steel){const m=mesh(parent,boxGeo,material,p);m.scale.set(...size);return m;}
 function cylinder(parent,p,radius,height,material=palette.steel){const m=mesh(parent,cylinderGeo,material,p);m.scale.set(radius,height,radius);return m;}
 function rod(parent,a,b,r,material=palette.steel){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),m=mesh(parent,cylinderGeo,material,p.clone().add(q).multiplyScalar(.5).toArray());m.scale.set(r,Math.max(.0001,p.distanceTo(q)),r);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());return m;}
 function setRod(m,a,b,r){const delta=new THREE.Vector3().subVectors(b,a),length=delta.length();m.position.copy(a).add(b).multiplyScalar(.5);m.scale.set(r,Math.max(.0001,length),r);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),length?delta.multiplyScalar(1/length):new THREE.Vector3(0,1,0));}
 function label(parent,text,p,width=1.6,maxHeight=.22){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font='600 54px system-ui';canvas.width=Math.max(120,Math.min(1800,ctx.measureText(text).width+40));canvas.height=84;ctx.fillStyle='#193544ed';ctx.fillRect(0,0,canvas.width,84);ctx.font='600 54px system-ui';ctx.fillStyle='#f4e9d2';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,canvas.width/2,42,canvas.width-30);const texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Sprite(own(new THREE.SpriteMaterial({map:texture,depthWrite:false})));const w=Math.min(width,maxHeight*canvas.width/84);m.scale.set(w,w*84/canvas.width,1);m.position.set(...p);parent.add(m);return m;}
 function info(m,a,b){m.userData.info=[a,b];targets.push(m);return m;}
 scene.add(new THREE.HemisphereLight(0xd9ebff,0x61745a,1.6));const sun=new THREE.DirectionalLight(0xffe6bd,3.0);sun.position.set(-20,38,28);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-30,right:40,top:35,bottom:-35,near:.1,far:130});sun.shadow.normalBias=.018;scene.add(sun);own(sun.shadow);
 const sky=mesh(scene,own(new THREE.SphereGeometry(260,32,16)),own(new THREE.ShaderMaterial({vertexShader:SKY_VERTEX,fragmentShader:SKY_FRAGMENT,side:THREE.BackSide,depthWrite:false})));sky.castShadow=sky.receiveShadow=false;sky.renderOrder=-1000;
 const terrainUniforms={uTime:{value:0}},ground=mesh(scene,own(new THREE.PlaneGeometry(240,240)),own(new THREE.ShaderMaterial({uniforms:terrainUniforms,vertexShader:GROUND_VERTEX,fragmentShader:GROUND_FRAGMENT})));ground.rotation.x=-Math.PI/2;ground.position.y=-.035;ground.castShadow=false;
 // Launch and recovery are different physical places in this compressed observer map.
 const facilities=new THREE.Group();scene.add(facilities);const fLaunch=layoutPoint('launch','falcon'),sLaunch=layoutPoint('launch','starship'),asdsPoint=layoutPoint('ASDS'),rtlsPoint=layoutPoint('RTLS');
 const launchPad=cylinder(facilities,[fLaunch[0],.05,fLaunch[2]],1.65,.17,palette.concrete);const launchMount=new THREE.Group();launchMount.position.set(...fLaunch);facilities.add(launchMount);const supportRing=mesh(launchMount,own(new THREE.TorusGeometry(.31,.045,8,32)),palette.dark,[0,.12,0]);supportRing.rotation.x=Math.PI/2;for(let i=0;i<4;i++){const a=i*Math.PI/2;box(launchMount,[Math.cos(a)*.28,.01,Math.sin(a)*.28],[.06,.24,.06],palette.steel);}
 const rtls=new THREE.Group();rtls.position.set(...rtlsPoint);facilities.add(rtls);cylinder(rtls,[0,-.08,0],1.55,.16,palette.concrete);const rtlsRing=mesh(rtls,own(new THREE.RingGeometry(.69,.73,48)),own(new THREE.MeshBasicMaterial({color:0xf7f0d4})),[0,.004,0]);rtlsRing.rotation.x=-Math.PI/2;label(rtls,'RTLS',[0,.24,-1.15],.65,.14);
 const ASDS=new THREE.Group();ASDS.position.set(...asdsPoint);facilities.add(ASDS);const deck=box(ASDS,[0,-.202,0],[3.65,.38,6.2],palette.dark);box(ASDS,[0,-.006,0],[3.55,.012,6.05],mat(0x778286,{roughness:.9}));const deckRing=mesh(ASDS,own(new THREE.RingGeometry(.69,.73,48)),own(new THREE.MeshBasicMaterial({color:0xf7f0d4})),[0,.001,0]);deckRing.rotation.x=-Math.PI/2;for(const a of [-Math.PI/4,Math.PI/4]){const line=box(ASDS,[0,.001,0],[.045,.0016,1.10],mat(0xedeadb));line.rotation.y=a;}for(const [x,z] of [[-1.50,-2.70],[1.50,-2.70]]){box(ASDS,[x,.20,z],[.24,.40,.62],palette.white);rod(ASDS,[x,.4,z],[x,1.35,z],.013,palette.steel);}label(ASDS,'ASDS',[0,.32,2.45],.65,.14);
 const tower=new THREE.Group();tower.position.set(sLaunch[0],0,sLaunch[2]);facilities.add(tower);const catchPlane=SPACE_LAYOUT.starship?.tower?.catchPlaneY??SPACE_LAYOUT.tower?.catchPlaneY??11;const towerHeight=catchPlane+.90;for(const x of [-2.85,-1.85])for(const z of [-.50,.50])box(tower,[x,towerHeight/2,z],[.11,towerHeight,.11],palette.steel);for(let y=.2;y<towerHeight;y+=.66){box(tower,[-2.35,y,0],[1.11,.07,1.11],palette.steel);for(const z of [-.52,.52])rod(tower,[-2.85,y,z],[-1.85,Math.min(towerHeight,y+.66),z],.028,palette.dark);}const arms=[];for(const sign of [-1,1]){const g=new THREE.Group();g.position.set(-1.0,catchPlane-.09,sign*1.05);tower.add(g);const beam=box(g,[0,0,0],[3.4,.18,.15],palette.gold);rod(g,[-1.5,-.10,0],[.5,-.10,0],.035,palette.steel);arms.push({group:g,beam,sign,contactLocal:new THREE.Vector3(1, .09,0)});}const starMount=new THREE.Group();starMount.position.set(sLaunch[0],sLaunch[1]-.12,sLaunch[2]);facilities.add(starMount);const launchRing=mesh(starMount,own(new THREE.TorusGeometry(.51,.07,8,40)),palette.steel,[0,.24,0]);launchRing.rotation.x=Math.PI/2;for(let i=0;i<6;i++){const a=i*Math.PI/3;box(starMount,[Math.cos(a)*.52,-.15,Math.sin(a)*.52],[.08,.65,.08],palette.steel);}
 const strongback=new THREE.Group();strongback.position.set(-.40,.15,0);facilities.add(strongback);for(const x of [-.09,.09])box(strongback,[x,2.2,0],[.055,4.4,.07],palette.steel);for(let y=.2;y<4.4;y+=.35)rod(strongback,[-.09,y,0],[.09,y+.25,0],.012,palette.steel);
 const tanks=[];for(const [x,z,r] of [[-4,-4,.62],[-5.5,-4,.50],[3,-3,.45]]){const tank=cylinder(facilities,[x,r*.9,z],r,r*1.8,palette.white);tanks.push(tank);}
 // The service complex is context, not a surveyed launch-site reconstruction.
 const service=new THREE.Group();facilities.add(service);const asphalt=mat(0x444e50,{roughness:.98}),serviceWhite=mat(0xbbc4c2,{roughness:.8}),pipeMat=mat(0xd9ded7,{roughness:.6,metalness:.3});
 box(service,[-4.0,.003,-5.2],[2.0,.02,10.3],asphalt);box(service,[-.4,.008,-5.5],[9.3,.03,1.20],asphalt);for(let i=0;i<10;i++)box(service,[-4.0,.020,-9.5+i*.8],[.045,.004,.38],palette.white);
 const processing=box(service,[-7.0,1.02,-7.1],[4.0,2.04,3.4],serviceWhite);box(service,[-7.0,2.06,-7.1],[4.16,.12,3.55],palette.dark);box(service,[-7.0,.69,-5.39],[2.1,1.35,.04],palette.dark);for(let y=.2;y<1.35;y+=.15)box(service,[-7.0,y,-5.35],[2.1,.014,.03],palette.steel);for(const x of [-8.45,-5.55])box(service,[x,1.30,-5.36],[.62,.54,.03],mat(0x436271,{roughness:.3,metalness:.15}));
 box(service,[-2.3,.43,-7.3],[1.7,.86,1.3],serviceWhite);box(service,[-2.3,.89,-7.3],[1.83,.07,1.43],palette.dark);for(const x of [-2.7,-1.9])box(service,[x,.57,-6.63],[.42,.36,.025],mat(0x436271,{roughness:.3,metalness:.15}));
 for(const [x,z,r] of [[-4,-4,.62],[-5.5,-4,.50],[3,-3,.45]]){const cap=mesh(service,sphereGeo,palette.white,[x,r*1.8,z]);cap.scale.set(r,.10,r);const a=[x,r*.20,z+.1],b=[x,r*.20,-2.0],c=[-.6,r*.20,-2.0],d=[-.6,r*.20,-.6];for(const [from,to] of [[a,b],[b,c],[c,d]])rod(service,from,to,.040,pipeMat);for(const y of [r*.25,r*1.5])cylinder(service,[x,y,z],r+.006,.025,palette.steel);}
 for(const z of [-8.8,-7.3]){box(service,[-9.3,.44,z],[.82,.88,.85],palette.dark);for(let y=.12;y<.9;y+=.15)box(service,[-9.3,y,z+.43],[.82,.018,.022],palette.steel);}
 // Service pipes terminate at the mounts; they never move with either vehicle.
 rod(service,[-.6,.19,-.6],[-.38,.19,-.30],.035,pipeMat);rod(service,[-.6,.19,-.6],[-.55,.45,-.35],.035,pipeMat);
 const vehicles=new THREE.Group();scene.add(vehicles);const engineRecords=[];
 function engine(parent,id,p,radius,height,type){const g=new THREE.Group();g.position.set(...p);g.userData.engineId=id;parent.add(g);const profile=[new THREE.Vector2(radius,0),new THREE.Vector2(radius*.94,height*.16),new THREE.Vector2(radius*.63,height*.56),new THREE.Vector2(radius*.34,height),new THREE.Vector2(radius*.29,height),new THREE.Vector2(radius*.56,height*.54),new THREE.Vector2(radius*.89,height*.16),new THREE.Vector2(radius*.96,0)];const bell=mesh(g,own(new THREE.LatheGeometry(profile,24)),palette.nozzle);bell.castShadow=false;const exit=new THREE.Object3D();g.add(exit);exit.userData.engineId=id;const plume=new THREE.Group();exit.add(plume);const uniforms=[];for(const [scale,color] of [[1,0xffa964],[.48,0xffefcf]]){const u={uColor:{value:new THREE.Color(color).multiplyScalar(scale===1?1.25:2)},uTime:{value:0},uPower:{value:0}};const geo=own(new THREE.CylinderGeometry(radius*.36,radius*(type==='vacuum'?2.7:1.9)*scale,1,24,1,true));const m=mesh(plume,geo,own(new THREE.ShaderMaterial({uniforms:u,vertexShader:PLUME_VERTEX,fragmentShader:PLUME_FRAGMENT,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide,toneMapped:false})),[0,-.5,0]);m.castShadow=m.receiveShadow=false;uniforms.push(u);}plume.visible=false;const record={id,group:g,bell,exit,nozzleRoot:exit,plume,uniforms,type,on:false,throttle:0};engineRecords.push(record);return record;}
 function gridFin(parent,a,y,r,length,width){const pivot=new THREE.Group();pivot.position.set(Math.cos(a)*r,y,Math.sin(a)*r);pivot.rotation.y=-a;parent.add(pivot);const surface=new THREE.Group();pivot.add(surface);const bars=[];for(const z of [-width/2,width/2])bars.push(box(surface,[length/2,0,z],[length,.024,.024],palette.dark));for(const x of [0,length])bars.push(box(surface,[x,0,0],[.024,.024,width],palette.dark));for(let i=1;i<6;i++){bars.push(box(surface,[length*i/6,0,0],[.012,.03,width],palette.steel));bars.push(box(surface,[length/2,0,-width/2+width*i/6],[length,.03,.012],palette.steel));}return {pivot,surface,bars,angle:a,deploy:0};}
 const f9=new THREE.Group(),fBooster=new THREE.Group(),fUpper=new THREE.Group();vehicles.add(f9);f9.add(fBooster,fUpper);const r=.185;
 cylinder(fBooster,[0,2.02,0],r,3.80,palette.white);mesh(fBooster,own(new THREE.CylinderGeometry(r*.98,r*.98,.24,32,1,true)),palette.dark,[0,.12,0]);cylinder(fBooster,[0,4.20,0],r,.60,palette.dark);for(const y of [.25,1.2,2.2,3.2,3.86])cylinder(fBooster,[0,y,0],r+.002,.012,palette.steel);const soot=cylinder(fBooster,[0,.65,0],r+.001,.8,mat(0x858780,{roughness:.86,transparent:true,opacity:.25,depthWrite:false}));
 const fEngines=[engine(fBooster,'falcon-booster-0',[0,0,0],.035,.14,'sea')];for(let i=0;i<8;i++){const a=i*Math.PI/4;fEngines.push(engine(fBooster,'falcon-booster-'+(i+1),[Math.cos(a)*.118,0,Math.sin(a)*.118],.035,.14,'sea'));}
 const fFins=Array.from({length:4},(_,i)=>gridFin(fBooster,i*Math.PI/2+.35,4.12,r,.24,.22)),fLegs=[];for(let i=0;i<4;i++){const a=i*Math.PI/2+.35,pivot=new THREE.Vector3(Math.cos(a)*.16,.94,Math.sin(a)*.16),stowed=new THREE.Vector3(Math.cos(a)*.205,2.08,Math.sin(a)*.205),footTarget=new THREE.Vector3(Math.cos(a)*.65,-.10,Math.sin(a)*.65),strut=rod(fBooster,pivot.toArray(),stowed.toArray(),.023,palette.dark),brace=rod(fBooster,[Math.cos(a)*.16,.26,Math.sin(a)*.16],stowed.toArray(),.013,palette.steel),foot=box(fBooster,stowed.toArray(),[.13,.036,.10],palette.dark);fLegs.push({angle:a,pivot,stowed,footTarget,strut,brace,foot,contactLocal:new THREE.Vector3(),deploy:0});}
 cylinder(fUpper,[0,.67,0],r,1.04,palette.white);mesh(fUpper,own(new THREE.CylinderGeometry(r,r,.15,32,1,true)),palette.dark,[0,.075,0]);const fUpperEngines=[engine(fUpper,'falcon-upper-0',[0,-.10,0],.10,.28,'vacuum')];
 const fairings=[];const fairProfile=[new THREE.Vector2(.25,0),new THREE.Vector2(.255,.72),new THREE.Vector2(.235,.96),new THREE.Vector2(.16,1.15),new THREE.Vector2(.035,1.30),new THREE.Vector2(.004,1.31)];for(let i=0;i<2;i++){const g=new THREE.Group();f9.add(g);const shell=mesh(g,own(new THREE.LatheGeometry(fairProfile,32,i*Math.PI,Math.PI)),mat(0xf1eee5,{side:THREE.DoubleSide,roughness:.42}));shell.userData.partId=i?'fairingRight':'fairingLeft';const rim=rod(g,[0,0,-.25],[0,.77,-.25],.009,palette.steel);fairings.push({group:g,shell,rim,index:i,id:i?'fairingRight':'fairingLeft'});}
 const payloadGroup=new THREE.Group();f9.add(payloadGroup);const payloadBody=box(payloadGroup,[0,0,0],[.25,.36,.22],mat(0xc5ad6c,{metalness:.45,roughness:.3}));const payloadWings=[];for(const side of [-1,1]){const hinge=new THREE.Group();hinge.position.set(side*.135,0,0);payloadGroup.add(hinge);box(hinge,[side*.14,0,0],[.28,.25,.018],mat(0x2e5370,{metalness:.45,roughness:.3}));for(let j=0;j<4;j++)box(hinge,[side*.14,-.09+j*.06,.012],[.27,.007,.004],palette.steel);payloadWings.push({hinge,side});}payloadBody.userData.partId='payload';info(payloadBody,es?'Carga ilustrativa: no representa una misión concreta.':'Illustrative payload: not a specific mission.', 'Illustrative payload: not a specific mission.');
 const falcon={group:f9,booster:fBooster,upper:fUpper,engines:fEngines,upperEngine:fUpperEngines[0],upperEngines:fUpperEngines,fairings,fins:fFins,legs:fLegs,payload:payloadGroup,payloadWings,soot};label(fBooster,es?'1 · FALCON 9':'1 · FALCON 9',[0,2.62,.23],.50,.10);label(fUpper,es?'2 · ETAPA SUPERIOR':'2 · UPPER STAGE',[0,.79,.21],.48,.10);
 const star=new THREE.Group(),sh=new THREE.Group(),ship=new THREE.Group();vehicles.add(star);star.add(sh,ship);const sr=.45;
 cylinder(sh,[0,3.55,0],sr,6.90,palette.steel);const hotStageRing=new THREE.Group();sh.add(hotStageRing);for(const y of [7.01,7.18]){const rim=mesh(hotStageRing,own(new THREE.TorusGeometry(sr,.018,6,40)),palette.steel,[0,y,0]);rim.rotation.x=Math.PI/2;}for(let i=0;i<14;i++){const a=i*Math.PI/7;box(hotStageRing,[Math.cos(a)*sr,7.095,Math.sin(a)*sr],[.026,.17,.026],palette.dark);}mesh(sh,own(new THREE.CylinderGeometry(sr*.97,sr*.97,.36,40,1,true)),palette.dark,[0,.18,0]);for(let y=.42;y<7.05;y+=.60)cylinder(sh,[0,y,0],sr+.003,.016,mat(0xaebfc6,{metalness:.72,roughness:.4}));
 const shEngines=[];for(const [count,radius,phase] of [[20,.355,0],[10,.225,Math.PI/10],[3,.09,0]])for(let i=0;i<count;i++){const a=i*Math.PI*2/count+phase;shEngines.push(engine(sh,'starship-booster-'+shEngines.length,[Math.cos(a)*radius,0,Math.sin(a)*radius],.044,.16,'sea'));}
 const shFins=Array.from({length:SPACE_HARDWARE.starship.gridFins??3},(_,i)=>gridFin(sh,i*Math.PI*2/(SPACE_HARDWARE.starship.gridFins??3)+.30,6.75,sr,.42,.42)),pins=[];for(const sign of [-1,1]){const pin=box(sh,[0,7.14,sign*.49],[.14,.08,.20],palette.dark);const point=new THREE.Object3D();point.position.set(0,7.10,sign*.52);sh.add(point);pins.push({mesh:pin,point,sign,contactLocal:point.position.clone()});}
 mesh(ship,own(new THREE.CylinderGeometry(sr,sr,.15,40,1,true)),palette.dark,[0,.075,0]);cylinder(ship,[0,1.96,0],sr,3.62,palette.steel);const noseProfile=[new THREE.Vector2(sr,0),new THREE.Vector2(.42,.38),new THREE.Vector2(.32,.84),new THREE.Vector2(.16,1.20),new THREE.Vector2(.006,1.42)];mesh(ship,own(new THREE.LatheGeometry(noseProfile,40)),palette.steel,[0,3.78,0]);
 const shipEngines=[];for(let i=0;i<3;i++){const a=i*Math.PI*2/3;shipEngines.push(engine(ship,'starship-upper-'+i,[Math.cos(a)*.145,-.10,Math.sin(a)*.145],.06,.18,'sea'));}for(let i=0;i<3;i++){const a=i*Math.PI*2/3+Math.PI/3;shipEngines.push(engine(ship,'starship-upper-'+(i+3),[Math.cos(a)*.30,-.10,Math.sin(a)*.30],.10,.25,'vacuum'));}
 const flaps=[];for(const [y,h,z] of [[.72,.90,0],[4.05,.55,0]])for(const side of [-1,1]){const hinge=new THREE.Group();hinge.position.set(side*.45,y,z);ship.add(hinge);const surface=box(hinge,[side*.17,0,0],[.34,h,.035],palette.tile);flaps.push({hinge,surface,side});}
 const tileGeo=own(new THREE.CircleGeometry(.036,6)),tileMat=palette.tile,tileCount=21*14,tiles=new THREE.InstancedMesh(tileGeo,tileMat,tileCount),tileMatrix=new THREE.Matrix4(),tilePosition=new THREE.Vector3(),tileQuaternion=new THREE.Quaternion(),normal=new THREE.Vector3();for(let row=0;row<21;row++)for(let col=0;col<14;col++){const a=Math.PI*.5+(col+.5)/14*Math.PI;tilePosition.set(Math.sin(a)*.454,.26+row*.165,Math.cos(a)*.454);normal.set(Math.sin(a),0,Math.cos(a));tileQuaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);tileMatrix.compose(tilePosition,tileQuaternion,new THREE.Vector3(1,1,1));tiles.setMatrixAt(row*14+col,tileMatrix);}tiles.castShadow=false;tiles.receiveShadow=true;ship.add(tiles);own(tiles);
 const starPayload=new THREE.Group();star.add(starPayload);box(starPayload,[0,0,0],[.32,.40,.30],palette.warm);const starship={payload:starPayload,group:star,booster:sh,upper:ship,ship,engines:shEngines,upperEngines:shipEngines,fins:shFins,pins,catchPins:pins,flaps,tiles,hotStageRing};label(sh,'1 · SUPER HEAVY',[0,4.60,.51],.85,.13);label(ship,'2 · STARSHIP',[0,2.64,.51],.85,.13);
 // Particles are re-evaluated from historic emission samples; no integration clock.
 const SMOKE=720,smokeGeometry=own(new THREE.BufferGeometry()),smokePositions=new Float32Array(SMOKE*3),smokeSizes=new Float32Array(SMOKE),smokeAlpha=new Float32Array(SMOKE),smokeColors=new Float32Array(SMOKE*3);smokeGeometry.setAttribute('position',new THREE.BufferAttribute(smokePositions,3));smokeGeometry.setAttribute('aSize',new THREE.BufferAttribute(smokeSizes,1));smokeGeometry.setAttribute('aAlpha',new THREE.BufferAttribute(smokeAlpha,1));smokeGeometry.setAttribute('aColor',new THREE.BufferAttribute(smokeColors,3));const pointScale={value:400},smoke=new THREE.Points(smokeGeometry,own(new THREE.ShaderMaterial({uniforms:{uScale:pointScale},vertexShader:SMOKE_VERTEX,fragmentShader:SMOKE_FRAGMENT,transparent:true,depthWrite:false})));smoke.frustumCulled=false;scene.add(smoke);
 const flameLight=new THREE.PointLight(0xffb568,0,18,1.8);scene.add(flameLight); let lastFrame;
 const partGroups={booster:fBooster,upper:fUpper,payload:payloadGroup,fairingLeft:fairings[0].group,fairingRight:fairings[1].group};
 function applyPose(group,state){group.visible=!!state&&state.visible!==false;if(!state)return;group.position.set(...positionOf(state));group.rotation.set(...rotationOf(state),'XYZ');group.userData.id=state.id;group.userData.status=state.status;group.userData.attachedTo=state.attachedTo??null;group.userData.pose=state;}
 function updateEngines(records,state,body,time){const raw=state?.representativeIndices??state?.activeIndices??state?.indices??body?.engineMask??[],indices=Array.isArray(raw)?raw:[],mask=indices.length===records.length&&indices.every(v=>typeof v==='boolean')?indices.map((v,i)=>v?i:-1):indices.map(v=>typeof v==='number'?v:Number(String(v).split('-').at(-1))),on=state?.firing===true||state?.on===true||state?.active===true,throttle=clamp(state?.throttle??body?.throttle??(on?1:0));records.forEach((record,i)=>{record.on=on&&mask.includes(i);record.throttle=record.on?throttle:0;record.plume.visible=record.on;const length=(record.type==='vacuum'?1.45:records.length>9?1.70:1.15)*(.30+.70*throttle);record.plume.scale.set(1,length,1);record.plume.userData.engineId=record.id;record.plume.userData.on=record.on;record.plume.userData.symbolic=state?.activeCount==null;for(const u of record.uniforms){u.uTime.value=time;u.uPower.value=record.throttle;}});}
 function update(frame){if(!frame)return;lastFrame=frame;const starMode=frame.vehicle==='starship',vehicle=starMode?starship:falcon,parts=frame.parts||{},hardware=frame.hardware||{};f9.visible=!starMode;star.visible=starMode;const groups=starMode?{booster:sh,upper:ship,payload:starPayload}:partGroups;for(const [id,g] of Object.entries(groups))applyPose(g,parts[id]);
  tower.visible=starMount.visible=starMode;launchMount.visible=strongback.visible=!starMode;ASDS.visible=!starMode&&frame.recovery==='droneship';rtls.visible=!starMode&&frame.recovery==='rtls';
  const fins=clamp(hardware.finsDeploy??hardware.finDeploy??frame.finsDeploy??frame.finDeploy??0),legs=clamp(hardware.legsDeploy??frame.legsDeploy??0);vehicle.fins.forEach(fin=>{fin.deploy=fins;fin.surface.rotation.z=(1-fins)*Math.PI/2;});
  fLegs.forEach(leg=>{leg.deploy=legs;const radial=.65-.16,vertical=-.10-.94,length=Math.hypot(radial,vertical),start=Math.atan2(.205-.16,2.08-.94),end=Math.atan2(radial,vertical),angle=start+(end-start)*legs,endpoint=new THREE.Vector3(Math.cos(leg.angle)*(.16+Math.sin(angle)*length),.94+Math.cos(angle)*length,Math.sin(leg.angle)*(.16+Math.sin(angle)*length));setRod(leg.strut,leg.pivot,endpoint,.023);setRod(leg.brace,new THREE.Vector3(Math.cos(leg.angle)*.16,.26,Math.sin(leg.angle)*.16),endpoint,.013);leg.foot.position.copy(endpoint).add(new THREE.Vector3(0,.018,0));leg.foot.rotation.y=-leg.angle;leg.contactLocal.copy(endpoint);leg.foot.visible=legs>.01;});
  const closure=clamp(frame.tower?.armsClosure??hardware.armsClosure??frame.recoveryState?.armsClosure??0);arms.forEach(arm=>arm.group.position.z=arm.sign*(1.05-.53*closure));
  payloadWings.forEach(wing=>wing.hinge.rotation.z=wing.side*Math.PI/2*(1-clamp(frame.payloadDeploy??frame.payload?.deploymentProgress??frame.payload?.deployProgress??0)));flaps.forEach(flap=>flap.hinge.rotation.y=flap.side*.30*clamp(hardware.flapsDeploy??hardware.flapDeploy??0));
  const inactive=starMode?falcon:starship;updateEngines(inactive.engines,{firing:false},null,Number(frame.time)||0);updateEngines(inactive.upperEngines,{firing:false},null,Number(frame.time)||0);updateEngines(vehicle.engines,frame.engines?.booster,parts.booster,Number(frame.time)||0);updateEngines(vehicle.upperEngines,frame.engines?.upper,parts.upper,Number(frame.time)||0);
  const samples=frame.effects?.smokeSamples||[];smokePositions.fill(0);smokeSizes.fill(0);smokeAlpha.fill(0);smokeColors.fill(0);let cursor=0;for(let j=0;j<samples.length&&cursor<SMOKE;j++){const sample=samples[j],glow=sample.kind==='exhaust-glow',origin=sample.position||sample.point,age=Math.max(0,Number(sample.age)||0),lifetime=Number(sample.lifetime)||6;if(!Array.isArray(origin)||age>=lifetime)continue;for(let k=0;k<6&&cursor<SMOKE;k++,cursor++){const n=j*17+k*31+(sample.id?Array.from(String(sample.id)).reduce((s,c)=>s+c.charCodeAt(0),0):0),a=seed(n)*Math.PI*2,spread=(sample.ground?.24:.08)+age*(sample.ground?.19:.07),wind=age*.06,power=clamp(sample.power??1);smokePositions[cursor*3]=origin[0]+Math.cos(a)*spread*(.5+seed(n+4))+wind;smokePositions[cursor*3+1]=Math.max(-.005,origin[1]+age*(sample.ground?.07:.03)+(seed(n+6)-.5)*spread*.5);smokePositions[cursor*3+2]=origin[2]+Math.sin(a)*spread;smokeSizes[cursor]=(glow?.025+age*.025:.20+age*.17)*(.6+seed(n+9))*(sample.ground?1.5:1);smokeAlpha[cursor]=Math.min(1,.12+age*3)*(1-age/lifetime)*(glow?.045:.23)*power;smokeColors.set(glow?[1.3,.55,.2]:[.62,.65,.67],cursor*3);}}
  for(const attribute of Object.values(smokeGeometry.attributes))attribute.needsUpdate=true;smoke.visible=cursor>0;smoke.userData.count=cursor;smoke.userData.modelTime=frame.time;terrainUniforms.uTime.value=Number(frame.time)||0;
  scene.updateMatrixWorld(true);const active=vehicle.engines.find(e=>e.on)||vehicle.upperEngines.find(e=>e.on);flameLight.intensity=active?20*active.throttle:0;if(active)active.exit.getWorldPosition(flameLight.position);scene.updateMatrixWorld(true);
 }
 scene.updateMatrixWorld(true);
 return {scene,resources,targets,parts:{vehicles:{falcon,starship},falcon,starship,engines:engineRecords,pads:{launch:launchPad,launchMount,ASDS,RTLS:rtls,tower,starMount},tower:{group:tower,arms,catchPlane},smoke:{points:smoke,geometry:smokeGeometry,positions:smokePositions,sizes:smokeSizes,alpha:smokeAlpha,colors:smokeColors,pointScale},ground,sky,facilities,service,flameLight},vehicles:{falcon,starship},engineRecords,update,render:update,get state(){return lastFrame;}};
}
function transformedBounds(state,local){const points=[],matrix=new THREE.Matrix4().compose(new THREE.Vector3(...positionOf(state)),new THREE.Quaternion().setFromEuler(new THREE.Euler(...rotationOf(state),'XYZ')),new THREE.Vector3(1,1,1));for(const x of [local[0],local[3]])for(const y of [local[1],local[4]])for(const z of [local[2],local[5]])points.push(new THREE.Vector3(x,y,z).applyMatrix4(matrix));return points;}
export function spaceViewBounds(frame,view='follow'){const star=frame?.vehicle==='starship',parts=frame?.parts||{},r=star?.98:(frame?.legsDeploy>0?1.35:.46),boosterHeight=star?7.25:4.52,upperTop=star?5.24:1.21;let selected=view==='follow'?frame?.chapter===2?'booster':frame?.chapter===3?'upper':'stack':view;const points=[];
 function part(id,bounds){const p=parts[id];if(p&&p.visible!==false)points.push(...transformedBounds(p,bounds));}
 if(selected==='stack'||selected==='booster'||selected==='overview')part('booster',[-r,-2.1,-r,r,boosterHeight,r]);
 if(selected==='stack'||selected==='upper'||selected==='overview'){part('upper',[-(star?.98:.36),-1.8,-(star?.98:.36),star?.98:.36,upperTop,star?.98:.36]);if(!star){part('fairingLeft',[-.28,0,-.28,.28,1.32,.28]);part('fairingRight',[-.28,0,-.28,.28,1.32,.28]);part('payload',[-.46,-.25,-.31,.46,.48,.31]);}}
 if(selected==='overview'){for(const key of [star?'tower':frame?.recovery==='rtls'?'RTLS':'ASDS']){const p=layoutPoint(key);const rr=star?3.1:frame?.recovery==='rtls'?1.7:3.4;points.push(new THREE.Vector3(p[0]-rr,0,p[2]-rr),new THREE.Vector3(p[0]+rr,star?((SPACE_LAYOUT.starship?.tower?.catchPlaneY??11)+1.0):.65,p[2]+rr));}const p=layoutPoint('launch',star?'starship':'falcon');points.push(new THREE.Vector3(p[0]-2.9,0,p[2]-1.8),new THREE.Vector3(p[0]+1.7,star?((SPACE_LAYOUT.starship?.tower?.catchPlaneY??11)+1.0):4.7,p[2]+1.8));}
 if(selected==='booster'&&frame?.time>=70){const p=layoutPoint(star?'tower':frame?.recovery==='rtls'?'RTLS':'ASDS'),rr=star?3.05:frame?.recovery==='rtls'?1.65:3.2;points.push(new THREE.Vector3(p[0]-rr,0,p[2]-rr),new THREE.Vector3(p[0]+rr,star?((SPACE_LAYOUT.starship?.tower?.catchPlaneY??11)+1.0):.75,p[2]+rr));}
 if(!points.length){const p=layoutPoint('launch',star?'starship':'falcon');points.push(new THREE.Vector3(p[0]-.7,p[1]-1,p[2]-.7),new THREE.Vector3(p[0]+.7,p[1]+(star?12.4:7),p[2]+.7));}
 const bounds=new THREE.Box3().setFromPoints(points);bounds.expandByScalar(.07);return {bounds,points,selected};
}
export function spaceFraming(frame,view='follow',orbit={},aspect=1,fov=46){const b=spaceViewBounds(frame,view),center=b.bounds.getCenter(new THREE.Vector3()),yaw=orbit.yaw??spaceOverview.yaw,pitch=orbit.pitch??spaceOverview.pitch,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let distance=2;for(const x of [b.bounds.min.x,b.bounds.max.x])for(const y of [b.bounds.min.y,b.bounds.max.y])for(const z of [b.bounds.min.z,b.bounds.max.z]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}return {center,direction,distance:distance*1.10*(orbit.distance??10)/10,bounds:b.bounds,selected:b.selected};}
export function createSpaceWorld(host,es=true){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});const dpr=Math.min(globalThis.devicePixelRatio||1,1.6);renderer.setPixelRatio(dpr);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);const built=createSpaceScene(es),camera=new THREE.PerspectiveCamera(46,1,.045,600),canvas=renderer.domElement,orbit={...spaceOverview};let frame,disposed=false,dragging=false,lastX=0,lastY=0,pinch=0;canvas.tabIndex=0;
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<1?62:46;camera.updateProjectionMatrix();built.parts.smoke.pointScale.value=h*dpr/(2*Math.tan(camera.fov*Math.PI/360));}
 const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function draw(){if(disposed)return;if(frame)built.update(frame);const f=spaceFraming(frame,orbit.view,orbit,camera.aspect,camera.fov);camera.position.copy(f.center).addScaledVector(f.direction,f.distance);camera.position.y=Math.max(.15,camera.position.y);camera.lookAt(f.center);camera.updateMatrixWorld();built.scene.updateMatrixWorld(true);renderer.render(built.scene,camera);}
 const listeners=[],listen=(target,type,fn,options)=>{target.addEventListener(type,fn,options);listeners.push(()=>target.removeEventListener(type,fn,options));};
 listen(canvas,'pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture?.(e.pointerId);});listen(canvas,'pointermove',e=>{if(!dragging)return;orbit.yaw-=(e.clientX-lastX)*.006;orbit.pitch=clamp(orbit.pitch+(e.clientY-lastY)*.004,-.12,1.2);lastX=e.clientX;lastY=e.clientY;draw();});listen(canvas,'pointerup',()=>dragging=false);listen(canvas,'pointercancel',()=>dragging=false);listen(canvas,'wheel',e=>{e.preventDefault();orbit.distance=clamp(orbit.distance*(e.deltaY>0?1.08:.92),4,32);draw();},{passive:false});listen(canvas,'touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});listen(canvas,'touchmove',e=>{if(e.touches.length!==2)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch&&d)orbit.distance=clamp(orbit.distance*pinch/d,4,32);pinch=d;draw();},{passive:true});listen(canvas,'keydown',e=>{if(e.key==='ArrowLeft')orbit.yaw-=.1;else if(e.key==='ArrowRight')orbit.yaw+=.1;else if(e.key==='ArrowUp')orbit.pitch=clamp(orbit.pitch-.08,-.12,1.2);else if(e.key==='ArrowDown')orbit.pitch=clamp(orbit.pitch+.08,-.12,1.2);else return;e.preventDefault();draw();});listen(canvas,'webglcontextlost',e=>e.preventDefault());
 function setView(view){if(SPACE_VIEWS.includes(view))orbit.view=view;draw();}
 function getViewState(){return {view:orbit.view,yaw:orbit.yaw,pitch:orbit.pitch,distance:orbit.distance};}
 function restoreViewState(saved={}){const value=saved&&typeof saved==='object'?saved.orbit||saved:{};if(SPACE_VIEWS.includes(value.view))orbit.view=value.view;for(const k of ['yaw','pitch','distance'])if(Number.isFinite(value[k]))orbit[k]=k==='distance'?clamp(value[k],4,32):k==='pitch'?clamp(value[k],-.12,1.2):value[k];draw();}
 return {canvas,dom:canvas,scene:built.scene,built,camera,orbit,render(value,dt=0){if(value)frame=value;draw();},update(value){if(value)frame=value;},focus:setView,setView,fit(){Object.assign(orbit,spaceOverview);draw();},overview(){setView('overview');},zoomBy(f){if(Number.isFinite(f)&&f>0)orbit.distance=clamp(orbit.distance/f,4,32);draw();},getViewState,restoreViewState,get stats(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};},dispose(){if(disposed)return;disposed=true;observer.disconnect();listeners.forEach(fn=>fn());for(const resource of [...built.resources])resource.dispose();renderer.dispose();canvas.remove();}};
}