import assert from 'node:assert/strict';
import {simulate,sample,crossingYear,STAGES,DEFAULTS,POWER_PER_TONNE} from './site-src/lunar/model.js';
import {missionPose,deliveryEvents,deliveriesAt,MISSION_STAGES} from './site-src/lunar/mission.js';
import {lunarFrameAt} from './site-src/lunar/presentation.js';
const close=(a,b)=>assert(Math.abs(a-b)<1e-7*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
let states=0,batches=0,frames=0;
for(const local of [0,.5,.9,.98])for(const flights of [0,2,24])for(const flightGrowth of [0,.2,.5])for(const power of [5,250,1000]){
 const run=simulate({local,flights,flightGrowth,power});let last=DEFAULTS.seed;
 assert(Object.isFrozen(run)&&Object.isFrozen(run.rows)&&Object.isFrozen(run.params));
 for(const r of run.rows){states++;assert(Object.isFrozen(r));assert(Object.values(r).filter(v=>typeof v==='number').every(Number.isFinite));assert(r.capital>=last-1e-8);assert(r.stock>=0);assert(r.capital<=run.powerLimit+1e-6);assert(r.earthOnly<=run.powerLimit+1e-6);
  close(r.capital,run.params.seed+r.localTotal+r.usedImports);close(r.delivered,run.params.seed+r.stock+r.usedImports);close(r.capital+r.stock,r.delivered+r.localTotal);close(r.localMade,r.build*local);close(r.power,r.capital*POWER_PER_TONNE);assert(Number.isInteger(r.flights));close(r.localIncorporated,r.localTotal);close(r.annualIncorporated,r.localTotal-run.rows[Math.max(0,r.month-12)].localTotal);last=r.capital;
 }
 const events=deliveryEvents(run);assert(Object.isFrozen(events));assert(events.length<=240);assert.equal(events.reduce((n,e)=>n+e.count,0),run.rows.at(-1).flights-run.rows[0].seedFlights);
 for(const e of events){batches++;assert(Object.isFrozen(e));assert.equal(e.last-e.first+1,e.count);assert.equal(e.number,e.last);const before=lunarFrameAt(run,8,.5,{month:e.arrival-1e-5}),arrival=lunarFrameAt(run,8,.5,{month:e.arrival});assert(before.deliveries.some(d=>d.last===e.last));assert(!arrival.deliveries.some(d=>d.last===e.last));close(before.row.delivered,run.rows[e.arrival-1].delivered);close(arrival.row.delivered-before.row.delivered,e.count*run.params.payload);}
 if(flights===0)close(run.rows.at(-1).capital,100);
 if(local===0)assert(run.rows.every(r=>r.capital<=r.earthOnly+1e-6));
}
const run=simulate();assert.equal(run.rows.at(-1).flights,44);assert.equal(run.rows[5].flights,4);assert.equal(run.rows[6].flights,5);
assert(simulate({flightGrowth:.2}).rows.at(-1).delivered>run.rows.at(-1).delivered);
for(const key of ['reinvest','uptime']){const stopped=simulate({[key]:0});close(stopped.rows.at(-1).capital,100);close(stopped.rows.at(-1).localIncorporated,0);}
const ideal=simulate({flights:120,payload:1000,uptime:1,power:100000});close(ideal.rows[12].capital,200);close(ideal.rows[24].capital,400);close(sample(ideal,-2).month,0);close(sample(ideal,999).month,240);
const seed=1e16/2**34;close(crossingYear(seed,1e16,12),2064);close(crossingYear(seed,1e16,24),2098);close(crossingYear(seed,1e26,24)-2030,2*(crossingYear(seed,1e26,12)-2030));
for(const scenario of [run,simulate({flights:0}),simulate({power:5}),simulate({local:0}),simulate({reinvest:0}),simulate({uptime:0}),simulate({flights:24,flightGrowth:.5,power:1000}),ideal])for(let index=0;index<STAGES.length;index++)for(let j=0;j<=50;j++){
 const f=lunarFrameAt(scenario,index,j/50);frames++;assert(Object.isFrozen(f)&&Object.isFrozen(f.operation)&&Object.isFrozen(f.deliveries));assert.equal(f.stage,STAGES[index].id);assert.equal(f.row,sample(scenario,f.month));close(f.visualTime,(index+j/50)*20);assert.equal(f.inFlightCount,f.deliveries.reduce((n,e)=>n+e.count,0));assert.equal(f.operation.month,f.row.month);assert.equal(f.operation.active,f.row.month>0&&f.row.build>0);close(f.operation.build,f.operation.local+f.operation.imported);assert.equal(f.operation.kind,'completed-month-example');assert.deepEqual(f,lunarFrameAt(scenario,index,j/50));if(index<7){assert(f.mission.camera.every(Number.isFinite)&&f.mission.target.every(Number.isFinite));}else assert.equal(f.mission,null);
}
const manual=lunarFrameAt(run,5,.63,{month:123.271,source:'manual',view:'mission'});assert.equal(manual.month,123.271);assert.equal(manual.row.month,123);assert.equal(manual.progress,.63);assert.equal(manual.view,'mission');assert.equal(manual.mission.cargoLocation,'rover');assert.equal(manual.source,'manual');
const early=lunarFrameAt(run,8,.5,{month:4.5});assert.equal(early.row.month,4);assert.equal(early.row.capital,100);assert.equal(early.row.earthOnly,100);
for(let i=0;i<=1000;i++){const u=i/1000,f=missionPose('refuel',u),cargo=missionPose('unload',u);close(f.refuel.depotLevel+f.refuel.shipLevel,1);if(u>.3&&u<.7)assert(f.refuel.connected);assert(f.refuel.transferProgress>=0&&f.refuel.transferProgress<=1);for(const key of ['lift','loadProgress','handoffProgress','cargo','depositProgress'])assert(cargo[key]>=0&&cargo[key]<=1);if(u<.5)assert.equal(cargo.handoffProgress,0);if(u<.65)assert.equal(cargo.cargo,0);if(u<.92)assert.equal(cargo.depositProgress,0);if(u<1)assert.notEqual(cargo.cargoLocation,'surface');}
const fueled=missionPose('refuel',1);assert(fueled.refuel.departed);assert.equal(fueled.refuel.shipLevel,1);assert(!fueled.refuel.connected);assert.equal(missionPose('unload',1).cargoLocation,'surface');assert(missionPose('return',1).lunarOrbit);assert.equal(missionPose('return',1).flame,0);assert.equal(missionPose('booster',1).flame,0);assert(!missionPose('booster',1).upperIgnited);assert(missionPose('booster',1).captured);close(missionPose('liftoff',1).height+15.7,missionPose('booster',0).upper);
assert.equal(MISSION_STAGES.length,7);assert.equal(STAGES.length,14);const events=deliveryEvents(run);assert.equal(events.length,40);assert.equal(deliveriesAt(events,5.5).length,1);assert.equal(deliveriesAt(events,6).length,0);assert.equal(events.at(-1).number,44);
for(const bad of [NaN,Infinity,-Infinity,'12',null]){assert.throws(()=>simulate({flights:bad}));assert.throws(()=>sample(run,bad));assert.throws(()=>crossingYear(bad,1e16,12));assert.throws(()=>lunarFrameAt(run,0,bad));assert.throws(()=>lunarFrameAt(run,0,.5,{month:bad}));assert.throws(()=>deliveriesAt(events,bad));assert.throws(()=>missionPose('refuel',bad));}
assert.throws(()=>simulate({local:1}));assert.throws(()=>simulate({seed:1000,power:5}));assert.throws(()=>crossingYear(0,1e16,12));assert.throws(()=>lunarFrameAt(run,14,0));assert.throws(()=>lunarFrameAt(run,0,.5,{view:'wrong'}));assert.throws(()=>missionPose('wrong',0));
console.log(`Lunar: ${states} monthly states, ${batches} delivery batches, ${frames} reversible frames; mass balance, completed-month ledger, power, incorporation labels, docking/transfer/unloading endpoints: OK`);
