import assert from 'node:assert/strict';
import {flux,capture,leak,swarmTemperature,shellTemperature,radiatingTemperature,sphereArea,snapshot,tickDyson,swarmLayout,visibleCollectors,COLLECTOR_MAX,RING_COUNT,L_SUN,AU,SIGMA,M_JUPITER,WORLD_POWER,WORLD_ENERGY_EJ,defaults} from './site-src/dyson/model.js';
const near=(a,b,tol=1e-6)=>assert(Math.abs(a-b)<=tol+1e-12*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b} ± ${tol}`);

near(flux(1),L_SUN/(4*Math.PI*AU*AU),1e-6);
assert(Math.abs(flux(1)-1361)<2,'IAU luminosity must recover the solar constant near 1361 W/m²');
for(const c of [0,.18,.5,1])near(capture(c)+leak(c),L_SUN,1e-3);
near(capture(0),0);near(capture(1),L_SUN);
near(swarmTemperature(1),swarmTemperature(1),0);
near(snapshot({...defaults,coverage:.1,form:'swarm'}).swarmTemperature,snapshot({...defaults,coverage:.9,form:'swarm'}).swarmTemperature,1e-9);
near(swarmTemperature(1)/swarmTemperature(4),2,1e-9);
assert(shellTemperature(1)>swarmTemperature(1));
near(radiatingTemperature('swarm',1,1),swarmTemperature(1),1e-9);
near(radiatingTemperature('shell',.5,1),swarmTemperature(1),1e-9);
near(radiatingTemperature('shell',1,1),shellTemperature(1),1e-9);
const full=snapshot({...defaults,form:'shell',coverage:1,radiusAu:1});
assert(full.closedShell);near(full.massUsed,M_JUPITER,1e12);
near(full.column,M_JUPITER/sphereArea(1),1e-6);
near(full.vsSun,1,1e-12);
near(WORLD_POWER,WORLD_ENERGY_EJ*1e18/(365.25*24*3600),1e-6);
assert(WORLD_POWER>1.8e13&&WORLD_POWER<2.1e13,'2025 world mean power should be ~19 TW');
assert(L_SUN/WORLD_POWER>1e13,'A full Dyson harvest dwarfs current world power');
const s={...defaults,playing:true,coverage:0};tickDyson(s,.5);assert(s.coverage>.01);tickDyson(s,50);assert.equal(s.coverage,1);assert.equal(s.playing,false);
const twoSided=Math.pow(flux(1)/(2*SIGMA),.25),outer=Math.pow(flux(1)/SIGMA,.25);
near(swarmTemperature(1),twoSided,1e-9);near(shellTemperature(1),outer,1e-9);
assert(Math.abs(swarmTemperature(1)-331)<3);assert(Math.abs(shellTemperature(1)-394)<4);
const pts=swarmLayout();assert.equal(pts.length,COLLECTOR_MAX);assert.equal(new Set(pts.map(p=>p.ring)).size,RING_COUNT);
pts.forEach(p=>{const r=Math.hypot(p.x,p.y,p.z);assert(r>0.9&&r<1.1,'Swarm collectors stay on near-unit orbits');});
assert.equal(visibleCollectors(0),0);assert.equal(visibleCollectors(1),COLLECTOR_MAX);assert.equal(visibleCollectors(.18),Math.floor(.18*COLLECTOR_MAX));
assert.equal(snapshot(defaults).collectors,visibleCollectors(.18));
console.log('Dyson energy conservation, swarm/shell temperatures, Jupiter mass sheet, orbital layout and world-power comparison: OK');
