import {L,control,metric,chapter,clamp} from './common.js';
import {buildCellTrace,sampleCell} from './cell-model.js';
export {translate} from './cell-model.js';
let cachedVariant,cachedTrace;
export function cellExperiment(p){if(cachedVariant!==p.variant||!cachedTrace){cachedTrace=buildCellTrace(p);cachedVariant=p.variant;}return cachedTrace;}
export function cellPoseAt(i){const f=[[-3.9,4.3,-1.2],[-.85,4,.2],[4.7,3.25,-.55],[3.4,4,-2.2]][i],x=[-7.8,-1.5,5.5,11.6][i],z=11.2;return {x,z,yaw:Math.atan2(x-f[0],z-f[2]),pitch:Math.atan2(f[1]-1.65,Math.hypot(x-f[0],z-f[2]))};}
export const cell={id:'cell',room:'life',title:L('Una célula fabrica una proteína','A cell makes a protein'),color:'#f2a6bc',unit:L('paso','step'),horizon:24,continuous:true,
 poseAt:cellPoseAt,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.5*Math.min(.05,dt);let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-16,16),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-12,15);const inside=(a,b)=>(a/11.7)**2+((b+1)/7.7)**2<1;if(inside(x,z)){if(!inside(x,p.z))z=p.z;else if(!inside(p.x,z))x=p.x;else{x=p.x;z=p.z;}}return {...p,x,z};},
 overview:{yaw:.06,pitch:.25,distance:9.5},fitLabel:L('Ver la célula completa','Fit the whole cell'),
 narrationTime(p,i,u){u=clamp(u,0,1);const stop=p.variant===2?15:21;return i===0?4*clamp((u-.12)/.76,0,1):i===1?4+3*clamp((u-.08)/.8,0,1):i===2?7+(stop-7)*clamp((u-.12)/.78,0,1):stop+(24-stop)*clamp((u-.1)/.78,0,1);},
 challenge:L('Cambia un codón: ¿cambia la cadena?','Change a codon: does the chain change?'),controls:[control('variant',L('Variante: 0 original · 1 sinónimo · 2 parada','Variant: 0 original · 1 synonymous · 2 stop'),0,0,2)],
 steps:[chapter(L('1 · La información queda en el núcleo','1 · Information stays in the nucleus'),L('En esta célula eucariota, el ADN contiene instrucciones que pueden copiarse a ARN. La transcripción produce una molécula de ARN a partir de una región del ADN. Ampliamos solo un fragmento inventado para seguirlo con claridad: no representa un gen humano completo.','In this eukaryotic cell, DNA contains instructions that can be copied into RNA. Transcription produces an RNA molecule from a region of DNA. We enlarge a short invented fragment so we can follow it clearly: it does not represent a complete human gene.')),
 chapter(L('2 · Sale una copia, no el ADN','2 · A copy leaves, not the DNA'),L('Después de su procesamiento, el ARN mensajero puede salir del núcleo a través de poros. Aquí mostramos cinco codones: grupos de tres letras. Cambia la variante: UUU y UUC codifican el mismo aminoácido; UAA es una señal de parada. No todos los cambios de ADN alteran una proteína.','After processing, messenger RNA can leave the nucleus through pores. Here we show five codons: groups of three letters. Change the variant: UUU and UUC encode the same amino acid; UAA signals a stop. Not every DNA change alters a protein.')),
 chapter(L('3 · El ribosoma lee tripletes','3 · The ribosome reads triplets'),L('El ribosoma avanza por el mensajero. Los ARN de transferencia ayudan a incorporar los aminoácidos correspondientes, formando una cadena. Pulsa reproducir para seguir cada codón. En este ejemplo AUG inicia la traducción; cuando llega una señal de parada, la cadena se libera.','The ribosome moves along the messenger. Transfer RNAs help add the corresponding amino acids, forming a chain. Press play to follow each codon. In this example AUG starts translation; when a stop signal arrives, the chain is released.')),
 chapter(L('4 · La cadena debe funcionar','4 · The chain must work'),L('Una proteína necesita plegarse y puede requerir modificaciones y transporte. El retículo y el aparato de Golgi intervienen en determinadas rutas, no en todas las proteínas. Las mitocondrias contribuyen a producir ATP para procesos celulares. Nuestra cadena corta es una demostración del código genético, no una proteína funcional.','A protein must fold and may need modification and transport. The endoplasmic reticulum and Golgi apparatus participate in certain routes, not in every protein’s journey. Mitochondria help produce ATP for cellular processes. Our short chain demonstrates the genetic code; it is not a functional protein.'))],
 limitations:L('Fragmento artificial de cinco codones ampliado dentro de un mRNA mayor: flancos y regiones no traducidas quedan fuera de la ampliación. Código genético estándar. La transcripción copia la hebra molde y conserva el ADN en el núcleo. El procesamiento aparece como un checkpoint condensado: parte puede ocurrir durante la transcripción; no mostramos intrones ni reacciones de cap/cola. Un mismo mRNA procesado atraviesa un poro y permanece después de traducirse. AUG usa un tRNA iniciador en P; los siguientes tRNA entran en A. STOP recibe un factor de liberación, nunca un aminoácido ni un tRNA de parada. El primer STOP termina la lectura; los codones posteriores no se traducen. Cadena esperada y construida son distintas. Esta cadena de dos o cuatro residuos no es una proteína funcional; no simulamos su plegamiento. Elegimos traducción citosólica: ER y Golgi son contexto para otras rutas, no un destino universal. Geometrías y 24 pasos son didácticos, fuera de escala y sin segundos biológicos. Se omiten regulación, vigilancia, degradación, energía y cinética. Retroceder reconstruye la explicación, no revierte biología.','Artificial five-codon fragment enlarged within a longer mRNA: flanks and untranslated regions remain outside the enlargement. Standard genetic code. Transcription copies the template strand and retains DNA in the nucleus. Processing is a condensed checkpoint: some can occur during transcription; introns and cap/tail reactions are not shown. One processed mRNA crosses a pore and remains after translation. AUG uses an initiator tRNA in P; later tRNAs enter A. STOP receives a release factor, never an amino acid or stop tRNA. The first STOP ends reading; later codons are not translated. Expected and built chains are separate. This two- or four-residue chain is not a functional protein; folding is not simulated. We choose cytosolic translation: ER and Golgi are context for other routes, not a universal destination. Geometry and 24 steps teach the sequence, not scale or biological seconds. Regulation, surveillance, degradation, energy and kinetics are omitted. Rewinding reconstructs the explanation and does not reverse biology.'),
 sources:[['NCBI · Standard genetic code','https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG1'],['NCBI · DNA to RNA: processing and export','https://www.ncbi.nlm.nih.gov/books/NBK26887/'],['NCBI · RNA to protein: tRNA and ribosomes','https://www.ncbi.nlm.nih.gov/books/NBK26829/'],['NCBI · Protein destinations','https://www.ncbi.nlm.nih.gov/books/NBK26907/'],['NHGRI · Transcription','https://www.genome.gov/genetics-glossary/Transcription'],['NHGRI · Translation','https://www.genome.gov/genetics-glossary/Translation']],
 evaluate(p,t){const trace=cellExperiment(p),s=sampleCell(trace,t);return {...s,trace,protein:s.expected.aminoAcids,read:s.translation.readCodons,length:s.chain.length,released:s.chain.released,variant:p.variant,
 metrics:[metric(L('Fragmento copiado','Fragment copied'),`${s.transcription.fragmentBasesCompleted} / 15`,L('bases','bases')),metric(L('Codones examinados','Codons examined'),`${s.translation.readCodons} / ${s.expected.readCodons}`),metric(L('Cadena construida','Built chain'),s.chain.length,L('aminoácidos','amino acids')),metric(L('Longitud esperada','Expected length'),s.expected.length,L('aminoácidos','amino acids'))],
 series:[{label:L('Residuos incorporados','Incorporated residues'),values:trace.states.map(v=>v.chain.length)}]};},
 // A single cutaway cell and the same exported RNA live in cell-world.js.
 build(){return ()=>{};}
};
