import {L,control,toggle,metric,chapter,rng} from './common.js';
export function evolve(p,t){let frequency=.5;const random=rng(p.seed),history=[frequency];for(let i=0;i<t;i++){const selected=frequency*(1+p.advantage)/(frequency*(1+p.advantage)+1-frequency),mutated=selected*(1-p.mutation)+(1-selected)*p.mutation;if(p.drift){let count=0;for(let n=0;n<50;n++)if(random()<mutated)count++;frequency=count/50;}else frequency=mutated;history.push(frequency);}return history;}
export const evolution={id:'evolution',room:'life',title:L('Evolución: muchas generaciones','Evolution: many generations'),color:'#b9df92',unit:L('generación','generation'),horizon:80,
 challenge:L('¿Selección, azar o ambos?','Selection, chance, or both?'),controls:[control('advantage',L('Ventaja reproductiva de A','Reproductive advantage of A'),.15,-.4,.4,.05),control('mutation',L('Probabilidad de mutación por copia','Mutation probability per copy'),.01,0,.05,.005),toggle('drift',L('Población finita: 50 individuos','Finite population: 50 individuals'),true),control('seed',L('Repetición aleatoria · semilla','Random run · seed'),41,1,100)],
 steps:[chapter(L('1 · Variación heredable','1 · Heritable variation'),L('Esta población idealizada tiene dos variantes de un gen: A y B. Empezamos con la mitad de cada una. Los cuerpos recuerdan a células, pero sus colores son etiquetas del modelo, no especies reales. La evolución se mide aquí como un cambio en la frecuencia de esas variantes entre generaciones.','This idealised population has two variants of one gene: A and B. We start with half of each. The shapes resemble cells, but their colours are model labels, not real species. Here evolution is measured as a change in variant frequencies across generations.')),
 chapter(L('2 · Diferencias en reproducción','2 · Differences in reproduction'),L('Una ventaja positiva hace que A contribuya, en promedio, con más descendientes. Una ventaja negativa favorece a B. Cambia el control para representar otro entorno. Los individuos no deciden adaptarse: una diferencia heredable modifica las probabilidades reproductivas y la composición de la siguiente generación.','A positive advantage makes A contribute more offspring on average. A negative advantage favours B. Change the control to represent another environment. Individuals do not decide to adapt: an inherited difference changes reproductive probabilities and the composition of the next generation.')),
 chapter(L('3 · Copiar también introduce variación','3 · Copying also introduces variation'),L('En cada generación se seleccionan las variantes que formarán la siguiente y algunas copias pueden mutar. Nuestro modelo permite cambios de A a B y de B a A con igual probabilidad. Las mutaciones no aparecen porque un organismo las necesite. Esta tasa es didáctica, no una tasa genética medida.','Each generation selects the variants forming the next, and some copies may mutate. Our model allows A-to-B and B-to-A changes with equal probability. Mutations do not appear because an organism needs them. This rate is educational, not a measured genetic rate.')),
 chapter(L('4 · El azar cambia la trayectoria','4 · Chance changes the trajectory'),L('Con solo cincuenta individuos, el muestreo aleatorio puede aumentar o perder una variante: es deriva genética. Cambia la semilla para comparar historias. Desactiva población finita para ver la expectativa matemática. Con ventaja y mutación a cero, esa expectativa permanece estable, mientras una población pequeña puede fluctuar.','With only fifty individuals, random sampling can increase or lose a variant: this is genetic drift. Change the seed to compare histories. Disable finite population to see the mathematical expectation. With advantage and mutation at zero, that expectation stays stable while a small population can fluctuate.'))],
 limitations:L('Modelo haploide de un locus y dos alelos, generaciones discretas, población fija de 50, reproducción ponderada y muestreo binomial. Sin migración, recombinación, dominancia ni estructura espacial. Sin deriva se muestra una expectativa continua; los 50 cuerpos redondean su proporción. Las tasas son experimentales, no datos de una especie.','Haploid one-locus, two-allele model with discrete generations, fixed population of 50, weighted reproduction and binomial sampling. No migration, recombination, dominance or spatial structure. Without drift, a continuous expectation is shown; the 50 bodies round its proportion. Rates are experimental, not species data.'),
 sources:[['UC Berkeley · Natural selection','https://evolution.berkeley.edu/evolution-101/mechanisms-the-processes-of-evolution/natural-selection/'],['UC Berkeley · Genetic drift','https://evolution.berkeley.edu/evolution-101/mechanisms-the-processes-of-evolution/genetic-drift/'],['NHGRI · Mutation','https://www.genome.gov/genetics-glossary/Mutation']],
 evaluate(p,t){const history=evolve(p,t),frequency=history.at(-1),expected=evolve({...p,drift:false},t);return {frequency,t,advantage:p.advantage,mutation:p.mutation,history,metrics:[metric(L('Variante A','Variant A'),frequency*100,'%'),metric(L('Variante B','Variant B'),(1-frequency)*100,'%'),metric(L('Generaciones transcurridas','Generations elapsed'),t)],series:[{label:L('A · frecuencia %','A · frequency %'),values:history.map(x=>x*100)},{label:L('A · expectativa sin deriva %','A · expectation without drift %'),values:expected.map(x=>x*100)}]};},
 build(k){const {group,sphere,tube,label}=k,colors=[0xb7e293,0xd9a4d3];const cell=(g,p,r,c)=>{const b=sphere(g,p,r,c,L('Organismo haploide idealizado: A verde o B violeta.','Idealised haploid organism: A green or B violet.'));b.scale.x=1.55;const dna=[];for(let i=0;i<12;i++)dna.push([p[0]+Math.cos(i*.6)*r*.5,p[1]+Math.sin(i*.6)*r*.5,p[2]+r*.85]);tube(g,dna,.025,0xf0efd9);return b;};const start=group(0);for(let i=0;i<8;i++)cell(start,[-2.4+(i%4)*1.6,1+Math.floor(i/4)*1.8,0],.45,colors[i%2]);label(start,'A : B = 1 : 1',0,4,0,4);
 const env=group(1),parents=[cell(env,[-1.7,2,0],.7,colors[0]),cell(env,[1.7,2,0],.7,colors[1])];label(env,'A',-1.7,3.5,0,1);label(env,'B',1.7,3.5,0,1);const children=[];for(let i=0;i<10;i++)children.push(cell(env,[-3+i*.65,.55,0],.16,colors[i<5?0:1]));
 const division=group(2),daughterA=cell(division,[-1.3,1.8,0],.75,colors[0]),daughterB=cell(division,[1.3,1.8,0],.75,colors[0]);tube(division,[[-1.3,1.8,0],[0,1.8,0],[1.3,1.8,0]],.12,0xb7e293);label(division,'A → A / B ?',0,3.5,0,4);
 const pop=group(3),bodies=[];for(let i=0;i<50;i++)bodies.push(cell(pop,[-3+(i%10)*.67,.5+Math.floor(i/10)*.67,0],.17,colors[i<25?0:1]));label(pop,'50',0,4,0,1);
 return(s,time)=>{parents[0].scale.set(1.55*(1+s.advantage*.6),1+s.advantage*.6,1);parents[1].scale.set(1.55,1,1);children.forEach((m,i)=>m.material.color.setHex(colors[i<Math.round(10*(1+s.advantage)/(2+s.advantage))?0:1]));daughterB.material.color.setHex(s.mutation>0?colors[1]:colors[0]);const pulse=.97+Math.sin(time*1.5)*.03;daughterA.scale.y=daughterB.scale.y=pulse;bodies.forEach((m,i)=>m.material.color.setHex(colors[i<Math.round(s.frequency*50)?0:1]));};}
};
