import {L,control,toggle,metric,chapter} from './common.js';
export function fullAdder(a,b,carry){return {sum:a^b^carry,carry:(a&b)|(carry&(a^b)),xor:a^b};}
export const microchip={id:'microchip',room:'mind',title:L('Dentro de un microchip','Inside a microchip'),color:'#c0a2ff',unit:L('paso','step'),horizon:12,
 challenge:L('Construye una suma con interruptores','Build an addition from switches'),controls:[toggle('a',L('Bit A','Bit A'),true),toggle('b',L('Bit B','Bit B'),true),toggle('carry',L('Acarreo de entrada','Carry in'),false)],
 steps:[chapter(L('1 · Un campo abre un canal','1 · A field opens a channel'),L('La puerta de un transistor MOS controla, mediante un campo eléctrico, un canal entre fuente y drenador. La capa aislante separa la puerta del semiconductor. Este corte ampliado es esquemático: los chips modernos también utilizan geometrías tridimensionales. Una señal lógica es un rango de tensión, no una bolita física.','A MOS transistor gate uses an electric field to control a channel between source and drain. An insulating layer separates the gate from the semiconductor. This enlarged cross-section is schematic: modern chips also use three-dimensional geometries. A logic signal is a voltage range, not a physical bead.')),
 chapter(L('2 · Dos transistores invierten un bit','2 · Two transistors invert a bit'),L('Un inversor CMOS combina un transistor de tipo p y otro de tipo n. Idealmente, una entrada baja activa el camino hacia la alimentación; una entrada alta activa el camino hacia tierra. Así, la salida es lo contrario de la entrada. Cambia A para ver ambos caminos.','A CMOS inverter combines a p-type and an n-type transistor. Ideally, a low input enables the path to the supply; a high input enables the path to ground. The output therefore reverses the input. Change A to see both paths.')),
 chapter(L('3 · Combinar puertas lógicas','3 · Combining logic gates'),L('Una puerta XOR produce uno cuando sus dos entradas son diferentes. AND necesita ambas entradas a uno; OR necesita al menos una. Conecta estas operaciones para formar un sumador completo. Los pulsos de color indican qué señales usamos; su velocidad es una ayuda visual, no un tiempo electrónico real.','An XOR gate produces one when its inputs differ. AND needs both inputs to be one; OR needs at least one. Connect these operations to build a full adder. Coloured pulses show the signals being used; their speed is a visual aid, not a real electronic timing.')),
 chapter(L('4 · Suma y acarreo','4 · Sum and carry'),L('Un sumador completo recibe A, B y un acarreo previo. Devuelve un bit de suma y un nuevo acarreo. Uno más uno da diez en binario: suma cero y acarreo uno. Prueba las ocho combinaciones de entrada. Los procesadores encadenan circuitos de este tipo y añaden registros, memoria y control.','A full adder receives A, B and a previous carry. It returns a sum bit and a new carry. One plus one is binary ten: sum zero and carry one. Try all eight input combinations. Processors connect circuits of this kind and add registers, memory and control.'))],
 limitations:L('Circuito lógico ideal, no un diseño de fabricación. Inversor y sumador son demostraciones separadas. El progreso muestra una secuencia pedagógica, no latencias reales. Se omiten tensiones analógicas, retardos, consumo, fugas, reloj y diseño físico.','Ideal logic circuit, not a fabrication design. The inverter and adder are separate demonstrations. Progress shows a teaching sequence, not real latency. Analogue voltages, delays, power consumption, leakage, clocking and physical layout are omitted.'),
 sources:[['Intel · The transistor explained','https://www.intel.com/content/www/us/en/newsroom/tech101/the-transistor-explained.html'],['Intel · Microprocessors','https://www.intel.com/content/www/us/en/education/k12/the-journey-inside/explore-the-curriculum/microprocessors.html']],
 evaluate(p,t){const a=+p.a,b=+p.b,c=+p.carry,o=fullAdder(a,b,c);return {a,b,c,...o,t,metrics:[metric(L('Entradas A + B + Cin','Inputs A + B + Cin'),`${a} + ${b} + ${c}`),metric(L('Resultado binario','Binary result'),`${o.carry}${o.sum}`,L('bits','bits')),metric(L('Valor decimal','Decimal value'),a+b+c)],series:[{label:L('XOR intermedio · nivel lógico','Intermediate XOR · logic level'),values:Array.from({length:t+1},(_,i)=>i>=4?o.xor:0)},{label:L('Suma · nivel lógico','Sum · logic level'),values:Array.from({length:t+1},(_,i)=>i>=8?o.sum:0)}]};},
 build(k){const {group,box,sphere,tube,label,pulse}=k;const on=0x91efca,off=0x435d72,g=group(0);box(g,[0,.65,0],[5,1.3,3],0x536c95,L('Sustrato de silicio; sección conceptual de un MOSFET.','Silicon substrate; conceptual MOSFET cross-section.'));for(const x of [-1.7,1.7])box(g,[x,1.35,0],[1.1,.3,2.5],0x68b9bb);box(g,[0,1.62,0],[2.3,.12,2.5],0xeac887,L('Óxido aislante entre puerta y canal.','Insulating oxide between gate and channel.'));box(g,[0,1.92,0],[2.3,.5,2.5],0x91a6bb);const channel=box(g,[0,1.38,1.27],[2.2,.12,.06],on);label(g,'SOURCE       GATE       DRAIN',0,3.1,0,5);
 const inv=group(1);tube(inv,[[0,.35,0],[0,3.7,0]],.035,0x75838c);const pm=box(inv,[0,2.8,0],[1.1,.7,.6],on),nm=box(inv,[0,1.1,0],[1.1,.7,.6],off),out=sphere(inv,[2,1.95,0],.35,on);tube(inv,[[0,1.95,0],[2,1.95,0]],.06,0xc1d0d5);tube(inv,[[-2,1.95,0],[-1,1.95,0],[-1,2.8,0],[0,2.8,0]],.04,0xbca4ff);tube(inv,[[-1,1.95,0],[-1,1.1,0],[0,1.1,0]],.04,0xbca4ff);label(inv,'VDD',0,4.1,0);label(inv,'GND',0,.1,.5);label(inv,'pMOS',0,2.8,.35,1);label(inv,'nMOS',0,1.1,.35,1);label(inv,'NOT A',2,2.7,0,1.5);
 const logic=group(2),signals=[];for(const [name,x,y] of [['XOR',-1.8,3],['XOR',1.2,3],['AND',-1.8,1],['AND',1.2,1],['OR',3,1.8]]){const m=box(logic,[x,y,0],[1.2,.7,.55],off,L('Bloque funcional: contiene varios transistores.','Functional block: contains multiple transistors.'));label(logic,name,x,y,.29,1);signals.push(m);}const paths=[[[-3.2,3,0],[-1.8,3,0],[1.2,3,0],[3,3,0]],[[-3.2,1,0],[-1.8,1,0],[1.2,1,0],[3,1.8,0]]],pulses=paths.map(p=>{tube(logic,p,.045,0x8194b1);return pulse(logic,p,on);});
 const add=group(3),bits=[];for(let i=0;i<5;i++){const x=-2.4+i*1.2,m=box(add,[x,1.8,0],[.85,1.1,.5],off);bits.push(m);label(add,['A','B','Cin','Sum','Cout'][i],x,2.8,0,1);}label(add,'A + B + Cin = Sum + 2 × Cout',0,3.8,0,6);
 return(s,time)=>{channel.material.color.setHex(s.a?on:off);pm.material.color.setHex(s.a?off:on);nm.material.color.setHex(s.a?on:off);out.material.color.setHex(s.a?off:on);[s.xor,s.sum,s.a&s.b,s.c&s.xor,s.carry].forEach((v,i)=>signals[i].material.color.setHex(v?on:off));[s.a,s.b,s.c,s.sum,s.carry].forEach((v,i)=>{bits[i].material.color.setHex(v?on:off);bits[i].scale.y=v?1:.4;});pulses.forEach((p,i)=>p(paths[i],(time*.2+i*.5)%1));};}
};
