import {LESSONS,SOURCES,scopeMarkup} from './lessons.js';
const $=id=>document.getElementById(id);
export const CONTROL_KEYS=['hours','reinvest','buildHours','shifts','limited','slots','supply','wage','installed','life','service','power','energy','supervision','material'];
export const COST_FIELDS=[['wage','Coste laboral completo €/h','Fully loaded labor €/h',0,200,1],['installed','Robot instalado €','Installed robot €',0,500000,1000],['life','Vida útil, años','Useful life, years',1,20,1],['service','Servicio y software €/año','Service and software €/year',0,100000,100],['power','Consumo activo, kW','Active power, kW',0,50,.1],['energy','Electricidad €/kWh','Electricity €/kWh',0,2,.01],['supervision','Supervisión por robot €/día','Supervision per robot €/day',0,1000,1],['material','Material por unidad €','Material per unit €',0,1000,1]];
export function mountGrowth(es){
 const t=(a,b)=>es?a:b,range=(id,label,a,b,step)=>`<label for="${id}">${label}<output id="${id}-value"></output><input id="${id}" type="range" min="${a}" max="${b}" step="${step}"></label>`;
 $('app').innerHTML=`<nav class="nav"><a href="../museo/index.html?pieza=growth">← ${t('Museo','Museum')}</a><span>ATLAS / 11</span><a href="../robots/factory.html">${t('Fábrica','Factory')} ↗</a><a id="page-language" href="${es?'../../growth/index.html':'../es/growth/index.html'}">${es?'EN':'ES'}</a></nav>
 <header><div><span class="eyebrow">${t('UNA FÁBRICA QUE AMPLÍA SU CAPACIDAD','A FACTORY EXPANDING ITS CAPACITY')}</span><h1>${t('Cuando lo que produces<br>también puede producir.','When what you make<br>can also make things.')}</h1></div><p>${t('Sigue el trabajo: bienes, nuevos robots y más capacidad. Compara el bucle con personas y una flota fija, y encuentra sus frenos.','Follow the work: goods, new robots and more capacity. Compare the loop with people and a fixed fleet, and find its constraints.')}</p></header>
 <p class="truth-strip">${t('Escenarios educativos · mismo ritmo por hora · productividad, reinversión y costes son supuestos editables.','Teaching scenarios · same hourly pace · productivity, reinvestment and costs are editable assumptions.')}</p>
 <section id="metrics" class="dashboard" aria-label="${t('Cifras de la fábrica','Factory figures')}"></section>
 <section class="plot"><div class="plot-title"><b>${t('Tres escenarios, una tarea','Three scenarios, one task')}</b><div class="chart-options"><button data-metric="0">${t('Capacidad','Capacity')}</button><button data-metric="1">${t('Bienes / día','Goods / day')}</button><button data-metric="2">${t('Acumulado','Cumulative')}</button></div></div><div id="chart" class="chart"></div><p id="doubling-events" class="milestones"></p></section>
 <div class="modebar"><div><button id="mode-diagram">2D</button><button id="mode-notebook">3D</button><button id="mode-immersive">${t('Entrar y caminar','Enter and walk')} ↗</button></div><span id="mode-help"></span></div>
 <nav class="chapters" aria-label="${t('Seis etapas','Six stages')}">${LESSONS.map((l,i)=>`<button id="chapter-${i}" data-chapter="${i}"><small>${String(i+1).padStart(2,'0')}</small>${l.title[es?0:1]}</button>`).join('')}</nav>
 <div class="layout"><section class="stage visual"><div id="diagram" class="diagram"></div><div id="space" tabindex="0" role="img" aria-label="${t('Tres líneas de producción y la incorporación de robots nuevos','Three production lines and deployment of new robots')}"></div><p id="loading">${t('Preparando la fábrica…','Preparing the factory…')}</p><div class="scene-heading"><b id="scene-status"></b><span id="scene-caption"></span></div><div class="view-controls"><button id="fit">${t('Zona','Area')}</button><button id="closeup">${t('Seguir el primer robot','Follow the first robot')}</button><button id="overview">${t('Fábrica completa','Whole factory')}</button><button id="zoom-in" aria-label="${t('Acercar','Zoom in')}">+</button><button id="zoom-out" aria-label="${t('Alejar','Zoom out')}">−</button><button id="capture" hidden>${t('Activar ratón','Enable mouse look')}</button></div><small id="camera-help"></small><div id="walk-pad" class="walk-pad" hidden><button data-move="forward" aria-label="${t('Avanzar','Forward')}">↑</button><button data-move="left" aria-label="${t('Izquierda','Left')}">←</button><button data-move="back" aria-label="${t('Retroceder','Backward')}">↓</button><button data-move="right" aria-label="${t('Derecha','Right')}">→</button></div><button id="listen-here" hidden></button><span id="position" hidden></span><p id="inspect" hidden></p></section>
 <aside><span class="eyebrow" id="chapter-number"></span><h2 id="focus-name"></h2><p id="focus-detail"></p><div class="actions"><button id="listen" class="primary">▶ ${t('Escuchar esta etapa','Listen to this stage')}</button><button id="next">${t('Siguiente','Next')} →</button></div><label class="check"><input id="follow" type="checkbox" checked>${t('Seguir las zonas de la voz','Follow narrated areas')}</label><p id="mechanism" class="mechanism"></p><details><summary>${t('Leer lo que dice la voz','Read the narration')}</summary><p id="narration-text"></p></details></aside></div>
 <section class="lab"><div class="lab-heading"><b>${t('Cambia los supuestos','Change the assumptions')}</b><span id="time-source"></span></div><div class="controls">${range('hours',t('Horas por robot / día','Hours per robot / day'),1,24,1)}${range('reinvest',t('Fracción de trabajo reinvertida','Reinvested work fraction'),0,1,.05)}${range('buildHours',t('Horas para construir un robot','Hours to build a robot'),120,960,60)}<label for="shifts">${t('Turnos humanos de 8 h','8-hour human shifts')}<select id="shifts"><option value="1">${t('1 turno · 10 personas','1 shift · 10 people')}</option><option value="2">${t('2 turnos · 20 personas','2 shifts · 20 people')}</option><option value="3">${t('3 turnos · 30 personas','3 shifts · 30 people')}</option></select></label><label class="check"><input id="limited" type="checkbox">${t('Limitar instalaciones y suministro','Limit facilities and supply')}</label>${range('slots',t('Plazas de la flota creciente','Growing-fleet slots'),10,200,10)}${range('supply',t('Suministro de trabajo equivalente / día','Equivalent-work supply / day'),0,4000,100)}</div>
 <div class="presets"><button id="preset-fair">${t('24 h: comparar turnos','24 h: compare shifts')}</button><button id="preset-no-grow">${t('Sin reinversión','No reinvestment')}</button><button id="preset-unlimited">${t('Explorar sin límites','Explore without limits')}</button><button id="preset-default">${t('Supuestos iniciales','Initial assumptions')}</button></div>
 <div class="experiment-controls"><button id="play" class="primary">▶ ${t('Reproducir sin voz','Play without narration')}</button><button id="reset">↺</button><button id="step">${t('Avanzar','Advance')}</button><button id="finish">${t('Final de etapa','Stage end')}</button><label for="phase">${t('Etapa','Stage')}<output id="phase-value"></output><input id="phase" type="range" min="0" max="1" step=".001" value="0"></label><label for="day">${t('Día del ejemplo','Example day')}<output id="day-label"></output><input id="day" type="range" min="0" max="90" step=".001" value="0"></label></div><p class="experiment-note">${t('El footer, la voz y los controles sitúan el mismo modelo. Cambiar supuestos recalcula toda la historia. Los días son del ejemplo. La fracción interpola trabajo, sin inventar horarios de turnos.','Footer, voice and controls position the same model. Changing assumptions recalculates the whole history. Days belong to the example. Fractions interpolate work, without inventing shift schedules.')}</p><div id="ledger" class="ledger"></div>
 <details><summary>${t('Leer los valores de las curvas','Read chart values')}</summary><div class="table-wrap"><table><thead><tr><th>${t('Día','Day')}</th><th>${t('Humano','Human')}</th><th>${t('Flota fija','Fixed fleet')}</th><th>${t('Reinversión','Reinvestment')}</th></tr></thead><tbody id="table"></tbody></table></div></details></section>
 <section class="cost lab"><span class="eyebrow">${t('COSTE POR UNIDAD · EXPERIMENTO SEPARADO','UNIT COST · SEPARATE EXPERIMENT')}</span><h2>${t('Más productores. ¿Menor coste?','More producers. Lower cost?')}</h2><p>${t('A plena utilización, este coste por unidad permanece constante al añadir robots idénticos. Más horas reparten mejor sus costes fijos. Cambia los supuestos para comprobar cuándo el robot sale más barato o más caro.','At full utilization, unit cost stays constant when identical robots are added. More hours spread fixed costs better. Change the assumptions to see when the robot costs less or more.')}</p><div id="cost-result" class="cost-parts"></div><div id="cost-bars"></div><details><summary>${t('Editar costes y leer la fórmula','Edit costs and read the formula')}</summary><div class="cost-grid">${COST_FIELDS.map(([id,a,b,min,max,step])=>`<label for="${id}">${t(a,b)}<input id="${id}" type="number" min="${min}" max="${max}" step="${step}"></label>`).join('')}</div><p id="cost-formula"></p></details></section>
 <details class="assumptions"><summary>${t('Qué suponemos, qué falta y fuentes','Assumptions, omissions and sources')}</summary>${scopeMarkup(es)}<div class="source-links">${SOURCES.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}</div></details><footer>Atlas · ${t('Crecimiento','Growth')} · 03/10/2026</footer>`;
}
export function growthInputs(params,es){for(const id of CONTROL_KEYS){const el=$(id);if(el.type==='checkbox')el.checked=params[id];else el.value=params[id];if($(id+'-value'))$(id+'-value').textContent=id==='reinvest'?Math.round(params[id]*100)+' %':new Intl.NumberFormat(es?'es-ES':'en-US').format(params[id]);}for(const id of ['slots','supply'])$(id).disabled=!params.limited;}
const humanIcon=`<svg viewBox="0 0 40 58" aria-hidden="true"><circle cx="20" cy="8" r="6" fill="#eac4a2"/><path d="M14 7Q20-4 26 7" stroke="#efb38e" stroke-width="5" fill="none"/><path d="M14 16H26L28 36H12Z" fill="#c78866"/><path d="M14 20L7 31L17 35M26 20L33 31L23 35" stroke="#eac4a2" stroke-width="5" fill="none"/><path d="M16 36L14 53M24 36L26 53" stroke="#8b9bac" stroke-width="6"/><rect x="14" y="29" width="12" height="8" rx="2" fill="#dfc989"/></svg>`;
const robotIcon=`<svg viewBox="0 0 40 58" aria-hidden="true"><rect x="13" y="2" width="14" height="11" rx="4" fill="#cfddd7"/><path d="M16 7H24" stroke="#72bfa7" stroke-width="3"/><rect x="11" y="17" width="18" height="18" rx="4" fill="#b3c5bf"/><path d="M12 20L5 29L16 35M28 20L35 29L24 35M15 37L14 53M25 37L26 53" stroke="#819b95" stroke-width="5" fill="none"/><circle cx="20" cy="25" r="4" fill="#83cdb9"/><rect x="15" y="29" width="10" height="7" rx="1" fill="#dfc989"/></svg>`;
export function paintGrowthView({es,params:p,frame:f,chapter,progress,metric,timeSource,playing,mode,text,language}){
 const t=(a,b)=>es?a:b,fmt=(x,d=1)=>new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:d}).format(x),compact=x=>new Intl.NumberFormat(es?'es-ES':'en-US',{notation:'compact',maximumFractionDigits:1}).format(x),money=x=>new Intl.NumberFormat(es?'es-ES':'en-US',{style:'currency',currency:'EUR'}).format(x),l=LESSONS[chapter],b=f.active?f.budget:f.potentialBudget,period=f.active?t('Presupuesto diario','Daily budget'):t('Capacidad potencial al final','Potential capacity at the end');
 const headerValues=metric===2?[f.elapsed.human,f.elapsed.fixed,f.elapsed.goods]:[b.human,b.fixed,metric===0?b.work:b.output],headerPeriod=metric===2?t('Acumulado transcurrido','Elapsed cumulative'):period;
 const cards=chapter===2||chapter===3?[[t('Trabajo utilizado','Utilized work'),fmt(b.work)+' h',period],[t('Bienes disponibles','Available goods'),fmt(b.output),t('Unidades equivalentes / día','Equivalent units / day')],[t('Construir capacidad','Building capacity'),fmt(b.buildWork)+' h',t('Resta bienes hoy','Reduces goods today')],[t('Puesta en marcha','Commissioning'),fmt(f.pending,0),t('Robots enteros, aún sin producir','Whole robots, not producing yet')]]:chapter===5?[[t('Humano + material','Human + material'),money(f.costs.human),t('Por unidad, misma tarea','Per unit, same task')],[t('Robot + material','Robot + material'),money(f.costs.robot),t('Plena utilización asumida','Assumed full utilization')],[t('Diferencia por unidad','Difference per unit'),money(f.costs.human-f.costs.robot),t('Puede ser negativa','Can be negative')],[t('Flota al final','Final fleet'),fmt(f.fleet,0),t('No cambia el coste de robots idénticos','Does not change identical robots’ unit cost')]]:[[t('Trabajo humano','Human work'),fmt(headerValues[0]),headerPeriod+(metric===2?'':' · '+t('unidades / día','units / day'))],[t('Diez robots fijos','Ten fixed robots'),fmt(headerValues[1]),headerPeriod],[metric===0?t('Capacidad con reinversión','Capacity with reinvestment'):t('Bienes con reinversión','Goods with reinvestment'),fmt(headerValues[2]),metric===0?t('Incluye construir robots; bienes: ','Includes building robots; goods: ')+fmt(b.output):headerPeriod],[t('Robots activos','Active robots'),fmt(f.fleet,0),headerValues[0]?fmt(headerValues[2]/headerValues[0],2)+'× '+t('la referencia humana','the human reference'):t('Referencia humana sin producción','Human reference produces nothing')]];
 $('metrics').innerHTML=cards.map(([name,value,note])=>`<article><span>${name}</span><strong>${value}</strong><small>${note}</small></article>`).join('');
 $('chapter-number').textContent=String(chapter+1).padStart(2,'0')+' / 06';$('focus-name').textContent=l.title[es?0:1];$('focus-detail').textContent=l.body[es?0:1];$('mechanism').textContent=l.formula[es?0:1];$('scene-status').textContent=l.title[es?0:1];$('scene-caption').textContent=l.caption[es?0:1];$('narration-text').textContent=text||'';$('narration-text').lang=language;
 $('phase').value=progress;$('phase-value').textContent=fmt(progress*100,1)+' %';$('day').max=f.trace.horizon;$('day').value=f.time;$('day-label').textContent=fmt(f.time,3);$('time-source').textContent=timeSource==='manual'?t('Inspección manual','Manual inspection'):t('Sigue la voz','Following narration');$('play').textContent=playing?'Ⅱ':'▶ '+t('Reproducir sin voz','Play without narration');
 document.querySelectorAll('[data-chapter]').forEach(e=>e.setAttribute('aria-pressed',String(+e.dataset.chapter===chapter)));document.querySelectorAll('[data-metric]').forEach(e=>e.setAttribute('aria-pressed',String(+e.dataset.metric===metric)));
 $('closeup').hidden=![2,3].includes(chapter);
 for(const value of ['diagram','notebook','immersive'])$('mode-'+value).setAttribute('aria-pressed',String(mode===value));$('diagram').hidden=mode!=='diagram';$('space').hidden=mode==='diagram';document.querySelector('.view-controls').hidden=mode==='diagram';for(const id of ['capture','walk-pad','position','listen-here'])$(id).hidden=mode!=='immersive';$('mode-help').textContent=mode==='immersive'?t('WASD · ratón · E para escuchar','WASD · mouse · E to listen'):mode==='diagram'?t('Mismo modelo en un esquema legible','The same model in a readable diagram'):t('Arrastra para girar · rueda para acercar','Drag to orbit · wheel to zoom');$('camera-help').textContent=mode==='immersive'?t('Esc libera el ratón y pausa. Caminar detiene la guía.','Esc releases the mouse and pauses. Walking stops the guide.'):t('Piezas ilustrativas. Las cantidades las miden cifras y barras.','Illustrative pieces. Figures and bars measure quantities.');
 const keys=metric===2?['humanTotal','fixedTotal','goods']:['human','fixed',metric===0?'work':'output'],current=metric===2?[f.elapsed.human,f.elapsed.fixed,f.elapsed.goods]:[b.human,b.fixed,metric===0?b.work:b.output],colors=['#efb38e','#9cbeef','#83cdb9'],names=[t('Humano','Human'),t('10 robots fijos','10 fixed robots'),t('Reinversión','Reinvestment')],max=Math.max(1,...f.trace.rows.flatMap(r=>keys.map(k=>r[k]))),x=d=>65+625*d/Math.max(1,f.trace.horizon),y=n=>140-120*n/max,past=f.trace.rows.filter(r=>r.day<f.time),points=keys.map((k,i)=>(metric===2?past.map(r=>[r.day,r[k]]):past.flatMap(r=>[[r.day,r[k]],[Math.min(f.time,r.day+1),r[k]]])).concat([[f.time,current[i]]])),unit=metric===2?t('Bienes acumulados · sólo trabajo transcurrido','Cumulative goods · only elapsed work'):metric===0?t('Presupuesto diario de trabajo, incluye construcción','Daily work budget, including construction'):t('Presupuesto de bienes por día después de reinvertir','Daily goods budget after reinvestment');
 $('chart').innerHTML=`<p class="chart-unit">${unit}${f.active?'':t(' · punto final: capacidad potencial; sin producción futura',' · final point: potential capacity; no future production')}</p><svg viewBox="0 0 720 175" role="img" aria-label="${unit}">${[0,.25,.5,.75,1].map(q=>`<path d="M65 ${y(max*q)}H690" stroke="#677c6633"/><text x="56" y="${y(max*q)+4}" text-anchor="end">${compact(max*q)}</text>`).join('')}${[0,30,60,90].filter(d=>d<=f.trace.horizon).map(d=>`<text x="${x(d)}" y="165" text-anchor="middle">${d}</text>`).join('')}${points.map((s,i)=>`<polyline data-series="${i}" data-last-day="${f.time}" points="${s.map(([d,n])=>x(d)+','+y(n)).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width="3" ${i===0?'stroke-dasharray="6 4"':''}/><circle cx="${x(f.time)}" cy="${y(current[i])}" r="4" fill="${colors[i]}"/>`).join('')}<path d="M${x(f.time)} 20V140" stroke="#e5bc75" stroke-dasharray="3 5"/></svg><div class="chart-key">${names.map((name,i)=>`<span style="--line:${colors[i]}">${name}</span>`).join('')}</div>`;
 $('doubling-events').textContent=t('Duplicaciones ocurridas: ','Completed doublings: ')+(f.milestones.length?f.milestones.map(m=>fmt(m.threshold,0)+' · '+t('día ','day ')+m.time).join(' → '):t('ninguna todavía','none yet'))+' · '+(f.bottlenecks.supply?t('el suministro limita el trabajo','supply limits work'):f.bottlenecks.slots?t('las plazas frenan nuevos robots','slots constrain new robots'):p.reinvest===0?t('sin reinversión no crece la flota','without reinvestment the fleet does not grow'):t('reinversión en curso','reinvestment in progress'));
 $('table').innerHTML=[...new Set([0,15,30,45,60,75,90].filter(d=>d<f.time).concat([f.time]))].map(d=>`<tr><td>${fmt(d,3)}</td>${(d===f.time?current:keys.map(k=>f.trace.rows[d][k])).map(v=>`<td>${fmt(v)}</td>`).join('')}</tr>`).join('');
 const share=b.work?b.buildWork/b.work:0,assembling=f.active&&(b.buildWork>0||f.bank>0),constructionStatus=!assembling?t('Sin montaje activo','No active assembly'):f.construction.awaitingDayClose?t('Trabajo listo; espera el cierre del día','Work ready; awaiting day close'):t('Trabajo de montaje en curso','Assembly work in progress');
 $('ledger').innerHTML=`<b>${t('Un trabajo, dos destinos','One work budget, two destinations')} · ${period}</b><div class="split-bar"><span style="width:${100*(1-share)}%"></span><i style="width:${100*share}%"></i></div><p>${fmt(b.work)} = ${fmt(b.output)} ${t('bienes','goods')} + ${fmt(b.buildWork)} ${t('horas para construir','hours building')}</p><div class="cost-parts"><span>${t('Bienes transcurridos','Elapsed goods')}<b id="elapsed-goods">${fmt(f.elapsed.goods)}</b></span><span>${t('Robots fabricados','Robots built')}<b>${fmt(f.made,0)}</b></span><span>${t('Saldo + montaje hoy','Carried work + today’s assembly')}<b>${fmt(f.bank+f.assemblyWork)} h</b></span><span>${t('Duplicación ideal','Ideal doubling')}<b>${f.idealDoubling===null?'—':fmt(f.idealDoubling)+' d'}</b></span></div><p class="note">${t('Balance transcurrido: trabajo = bienes + trabajo de robots terminados + saldo + montaje de hoy. Duplicación ideal: sin esperas, límites ni redondeo a robots enteros.','Elapsed balance: work = goods + work in completed robots + carried work + today’s assembly. Ideal doubling: no delay, constraints or whole-robot rounding.')}</p>`;
 $('diagram').innerHTML=`<div class="diagram-lines">${[['human',b.human,f.elapsed.human,10,humanIcon],['fixed',b.fixed,f.elapsed.fixed,10,robotIcon],['growing',b.output,f.elapsed.goods,f.fleet,robotIcon]].map(([id,rate,total,count,icon],i)=>`<article class="diagram-line ${id}"><div class="line-title"><b>${names[i]}</b><span>${fmt(count,0)} ${t(id==='human'?'puestos':'robots activos',id==='human'?'workstations':'active robots')}</span></div><div class="line-work"><span class="input-stock">${t('Entrada','Input')}<i>▥</i></span><span class="flow-arrow">→</span><div class="operators">${Array.from({length:Math.min(10,count)},()=>icon).join('')}</div><span class="flow-arrow">→</span><div class="output-stock"><b>${fmt(rate)}</b><small>${period} · / ${t('día','day')}</small><span>${fmt(total)} ${t('ya producidos','already made')}</span></div></div>${id==='growing'?`<div class="reinvestment-path"><span>${assembling?'↘ ':''}${fmt(f.active?b.buildWork:0)} h ${t('para construir','building')}</span><b>${assembling?f.construction.nextRobotId:''} · ${constructionStatus}</b><progress max="1" value="${f.construction.fraction}" aria-label="${t('Trabajo de construcción','Construction work')}"></progress><span>${fmt(f.pending,0)} ${t('en pruebas · 2 días','commissioning · 2 days')}</span><span>${f.active&&f.pending?'↗ '+t('se incorporarán tras las pruebas','will join after commissioning'):t('Sin incorporación futura acreditada','No future deployment credited')}</span></div>`:''}</article>`).join('')}</div><p>${t('Diez iconos muestran los puestos iniciales. La cifra incluye toda la flota; los lotes nuevos se identifican en 3D. Los objetos y flechas son un esquema del flujo, no una escala de materiales.','Ten icons show initial workstations. The figure includes the entire fleet; new batches are identified in 3D. Objects and arrows schematically show flow, not a material scale.')}</p>`;
 const saving=f.costs.human-f.costs.robot;
 $('cost-result').innerHTML=[[t('Humano + material','Human + material'),money(f.costs.human)],[t('Robot + material','Robot + material'),money(f.costs.robot)],[t(saving>=0?'Ahorro por unidad':'Sobrecoste del robot',saving>=0?'Saving per unit':'Robot surcharge'),money(Math.abs(saving))],[t('Variación con flota idéntica','Change with an identical fleet'),'0 %']].map(([name,n])=>`<span>${name}<b>${n}</b></span>`).join('');
 const robotParts=[p.material,p.installed/(p.life*365*p.hours),p.service/(365*p.hours),p.supervision/p.hours,p.power*p.energy],humanParts=[p.material,p.wage],maxCost=Math.max(1,f.costs.human,f.costs.robot),partNames=[t('Material','Material'),t('Instalación','Installation'),t('Servicio','Service'),t('Supervisión','Supervision'),t('Electricidad','Electricity')];
 $('cost-bars').innerHTML=[['human',humanParts,[partNames[0],t('Trabajo','Labor')]],['robot',robotParts,partNames]].map(([id,values,names])=>`<div class="cost-row"><b>${t(id==='human'?'Humano':'Robot',id==='human'?'Human':'Robot')}</b><div class="cost-stack">${values.map((n,i)=>`<span style="width:${100*n/maxCost}%;--part:${['#b9b39a','#83cdb9','#9cbeef','#efb38e','#e5bc75'][i]}" title="${names[i]}: ${money(n)}"></span>`).join('')}</div><output>${money(values.reduce((s,n)=>s+n,0))}</output></div>`).join('')+`<div class="cost-breakdown">${partNames.map((name,i)=>`<span>${name}: ${money(robotParts[i])}</span>`).join('')}</div>`;
 $('cost-formula').textContent=t('Humano = material + €/hora. Robot = material + [instalación/(vida×365) + servicio/365 + supervisión + kW×€/kWh×horas] / horas. Son ejemplos a plena utilización; no financian nuevos robots.','Human = material + €/hour. Robot = material + [installation/(life×365) + service/365 + supervision + kW×€/kWh×hours] / hours. Full-utilization examples; these do not finance new robots.');
}
