import {LESSONS} from './journeys/catalog.js';
import {immersiveHref} from './immersive/catalog.js';
import {CATALOG} from './catalog.js';
// Add future explanations here; the home page has no topic-specific routing logic.
const es=document.documentElement.lang==='es';
const copy=es?{brand:'EXPLICACIONES INTERACTIVAS',eyebrow:'NOTEBOOKS · SISTEMAS QUE PUEDES EXPLORAR',title:'Entenderlo cambia<br>cómo lo miras.',intro:'Robots, chips, una esfera de Dyson, un hogar, Starlink, SpaceX, Kardashev, modelos de lenguaje, un cerebro, una industria en la Luna y ocho mundos que se pueden caminar: de internet a la evolución. Empieza por el <a href="./museo/index.html">museo</a> o filtra por tipo de experiencia.',footer:'Una colección abierta a nuevas preguntas.',count:''}:{brand:'INTERACTIVE EXPLANATIONS',eyebrow:'NOTEBOOKS · SYSTEMS YOU CAN EXPLORE',title:'Understanding changes<br>how you see it.',intro:'Robots, chips, a Dyson sphere, a home, Starlink, SpaceX, Kardashev, language models, a brain, an industry on the Moon and eight worlds you can walk through: from the internet to evolution. Start with the <a href="./museo/index.html">museum</a> or filter by kind of experience.',footer:'A collection open to new questions.',count:''};
document.querySelectorAll('[data-copy]').forEach(el=>el.innerHTML=copy[el.dataset.copy]);
document.querySelector(`[hreflang="${es?'es':'en'}"]`).setAttribute('aria-current','true');
export const explorations=[
 {slug:'lunar',name:es?'Tierra → Luna':'Earth → Moon',tag:es?'SEMILLA INDUSTRIAL · CRECIMIENTO EXPONENCIAL':'INDUSTRIAL SEED · EXPONENTIAL GROWTH',title:es?'Una semilla.<br>Una industria que crece.':'One seed.<br>An industry that grows.',description:es?'Envía equipos, fabrica con recursos lunares y reinvierte. Compara crecimiento ideal, entregas terrestres y límites de energía y componentes.':'Ship equipment, manufacture with lunar resources and reinvest. Compare ideal growth, Earth deliveries and power and component constraints.',steps:es?['Enviar','Fabricar','Reinvertir','Crecer']:['Deliver','Manufacture','Reinvest','Grow'],color:'#ffc478'},
 {slug:'museo',name:es?'Museo':'Museum',tag:es?'CUATRO SALAS · NUEVE MUNDOS 3D':'FOUR GALLERIES · NINE 3D WORLDS',title:es?'Pasea por las ideas.<br>Atraviesa un cuadro.':'Walk through ideas.<br>Step through a painting.',description:es?'Inteligencia, industria, cosmos y vida: veinte cuadros. LLMs y ocho experiencias nuevas abren mundos transitables con guía de voz.':'Intelligence, industry, cosmos and life: twenty paintings. LLMs and eight new experiences open walkable worlds with voice guides.',steps:es?['Atrio','Salas','Cuadros','Mundos']:['Atrium','Galleries','Paintings','Worlds'],color:'#f3d39a'},
 {slug:'modelos',name:es?'Modelos':'Models',tag:es?'LENGUAJE · FAMILIAS Y PRECIO':'LANGUAGE · FAMILIES AND PRICE',title:es?'No todo modelo<br>escribe de uno en uno.':'Not every model<br>writes one by one.',description:es?'Codificador, expertos, estado, difusión, JEPA, Jev y la factura: entrada, caché y salida.':'Encoder, experts, state, diffusion, JEPA, Jev and the bill: input, cache and output.',steps:es?['Familias','Caché','Precio','Disco']:['Families','Cache','Price','Disk'],color:'#e7c98a'},
 {slug:'mente',name:es?'Mente':'Mind',tag:es?'MENTE · GROK Y UN CEREBRO':'MIND · GROK AND A BRAIN',title:es?'No es un cerebro<br>que habla.':'Not a brain<br>that speaks.',description:es?'Cambia entre responder y entrenar. Mira qué memoria se llena, qué pesos se mueven y cuánta energía gasta un cerebro en ese intervalo.':'Switch between replying and training. See which memory fills, which weights move and how much energy a brain spends in that interval.',steps:es?['Unidades','Memoria','Pesos','Energía']:['Units','Memory','Weights','Energy'],color:'#f0b4c4'},
 {slug:'llms',name:'LLMs',tag:es?'INTELIGENCIA ARTIFICIAL · POR DENTRO':'ARTIFICIAL INTELLIGENCE · INSIDE THE MODEL',title:es?'De tu pregunta<br>a una respuesta.':'From your question<br>to an answer.',description:es?'Sigue los tokens, abre las capas y compara lo aprendido con lo consultado. Cambia el contexto y descubre cómo puede equivocarse.':'Follow tokens, open the layers and compare learned patterns with retrieved evidence. Change context and discover how errors happen.',steps:es?['Contexto','Tokens','Capas','Respuesta']:['Context','Tokens','Layers','Answer'],color:'#99b9ff'},
 {slug:'kardashev',name:'Kardashev',tag:es?'CIVILIZACIONES · ESCALAS DE ENERGÍA':'CIVILIZATIONS · ENERGY SCALES',title:es?'Un planeta. Una estrella.<br>Una galaxia.':'A planet. A star.<br>A galaxy.',description:es?'Reproduce el salto entre tipos I, II y III. Compara potencias y descubre por qué 0,73 no significa un 73 %.':'Play the jump between Types I, II and III. Compare power and discover why 0.73 does not mean 73%.',steps:es?['Humanidad','Planeta','Estrella','Galaxia']:['Humanity','Planet','Star','Galaxy'],color:'#bba7ef'},
 {slug:'robots',name:'Robots',tag:es?'AUTOMATIZACIÓN · CUATRO ESCALAS':'AUTOMATION · FOUR SCALES',title:es?'Robots que construyen<br>más robots.':'Robots building<br>more robots.',description:es?'De una línea de montaje a una región. Descubre cómo crece una red cuando reinvierte lo que produce.':'From an assembly line to a region. Discover how a network grows when it reinvests what it produces.',steps:es?['Fábrica','Distrito','Ciudad','Región']:['Factory','District','City','Region'],color:'#a7e0cf'},
 {slug:'terafab',name:'Terafab',tag:es?'SEMICONDUCTORES · VISITA EN 3D':'SEMICONDUCTORS · 3D FACTORY TOUR',title:es?'Dentro de una<br>megafábrica de chips.':'Inside a<br>chip megafactory.',description:es?'Compara lo anunciado con una fábrica representativa. Explora los equipos y cómo cambia una oblea durante el proceso.':'Compare the announced plan with a representative factory. Explore the equipment and how a wafer changes through processing.',steps:es?['Complejo','Sala limpia','Equipos','Servicios']:['Campus','Cleanroom','Equipment','Utilities'],color:'#b9b1ff'},
 {slug:'dyson',name:es?'Esfera de Dyson':'Dyson sphere',tag:es?'ENERGÍA ESTELAR · MODELO 3D':'STELLAR ENERGY · 3D MODEL',title:es?'No es una cáscara rígida.<br>Es un enjambre.':'Not a rigid shell.<br>A swarm.',description:es?'Compara el enjambre que Dyson imaginó con la cáscara de ciencia ficción. Cambia la cobertura y el radio y mira qué pasa con la luz, el calor y la materia.':'Compare the swarm Dyson actually described with the science-fiction shell. Change coverage and radius and watch light, heat and mass respond.',steps:es?['Enjambre','Cáscara','Calor','Materia']:['Swarm','Shell','Heat','Mass'],color:'#f0c075'},
 {slug:'home',name:es?'Hogar':'Home',tag:es?'CASA EN 3D · SIMULACIÓN REPRODUCIBLE':'3D HOME · PLAYABLE SIMULATION',title:es?'Un hogar con<br>menos tareas pendientes.':'A home with<br>fewer pending chores.',description:es?'Pulsa reproducir: recorre una casa amueblada y observa cómo los robots y la IA se encargan de sus siete quehaceres.':'Press play: explore a furnished home and watch robots and AI take on its seven chores.',steps:es?['Cocina','Limpieza','Ropa','Agenda']:['Kitchen','Cleaning','Laundry','Planning'],color:'#efbd8c'},
 {slug:'starlink',name:'Starlink',tag:es?'CONSTELACIÓN · COBERTURA EN 3D':'CONSTELLATION · 3D COVERAGE',title:es?'Miles de satélites.<br>Un parche que se mueve.':'Thousands of satellites.<br>A moving patch.',description:es?'Mueve al usuario, apaga capas y los láseres, y mira cómo un paquete sube, salta y baja a internet.':'Move the user, switch shells and lasers, and watch a packet go up, hop and come down to the internet.',steps:es?['Capas','Usuario','Láser','Pasarela']:['Shells','User','Laser','Gateway'],color:'#6ee7c5'},
 {slug:'growth',name:es?'Crecimiento':'Growth',tag:es?'MODELO 2D · PRODUCCIÓN Y COSTES':'2D MODEL · OUTPUT AND COSTS',title:es?'Cuando lo que produces<br>también puede producir.':'When what you make<br>can also make things.',description:es?'Compara trabajo humano, robots y reinversión: producción, costes y límites del crecimiento.':'Compare human work, robots and reinvestment: output, costs and the limits of growth.',steps:es?['Horas','Robots','Reinvertir','Límites']:['Hours','Robots','Reinvest','Limits'],color:'#9fd3a8'},
 {slug:'spacex',name:'SpaceX',tag:es?'LANZAMIENTO · REUTILIZACIÓN 3D':'LAUNCH · 3D REUSE',title:es?'El tramo caro<br>tiene que volver.':'The expensive stage<br>has to come back.',description:es?'Falcon 9 aterriza; Starship intenta coger el booster con la torre. Sigue los minutos de un vuelo.':'Falcon 9 lands; Starship tries to catch the booster with the tower. Follow the minutes of a flight.',steps:es?['Despegue','Separación','Aterrizaje','Otra vez']:['Liftoff','Separation','Landing','Again'],color:'#e8a06a'}
];
Object.values(LESSONS).forEach((l,i)=>explorations.push({slug:l.id,href:`./journeys/index.html?topic=${l.id}`,name:l.title[es?0:1],tag:es?'NOTEBOOK + MUNDO 3D · MINIMAX ES / EN':'NOTEBOOK + 3D WORLD · MINIMAX ES / EN',title:l.challenge[es?0:1],description:l.steps[0].text[es?0:1],steps:l.steps.map(s=>s.title[es?0:1].replace(/^\d · /,'')),color:l.color}));
for(const p of explorations)Object.assign(p,CATALOG[p.slug]);
// Traits: what kind of experience each card opens. Filters show one kind at a time.
const TRAITS={walk:es?'Caminable':'Walkable','3d':'3D','2d':'2D',voice:es?'Con voz':'Narrated'};
const traitsOf=p=>[...p.kinds,...(p.voice?['voice']:[])];
document.querySelector('#collection').innerHTML=explorations.sort((a,b)=>a.number.localeCompare(b.number)).map(p=>{
 const immersive=immersiveHref(p.slug,'./');
 return `<article class="exploration ${p.slug}" data-traits="${traitsOf(p).join(' ')}" style="--accent:${p.color}"><a class="exploration-link" href="${p.href||`./${p.route||p.slug}/index.html`}"><div class="card-top"><span>${p.tag}</span><b>${p.number}</b></div><ul class="traits" aria-label="${es?'Tipo de experiencia':'Kind of experience'}">${traitsOf(p).map(k=>`<li class="trait-${k}">${TRAITS[k]}</li>`).join('')}</ul><h2>${p.name}</h2><h3>${p.title}</h3><div class="mini-diagram" aria-hidden="true">${p.steps.map((s,i)=>`<span><i>${String(i+1).padStart(2,'0')}</i>${s}</span>`).join('<em>→</em>')}</div><p>${p.description}</p></a><div class="mode-actions"><a href="${p.href||`./${p.route||p.slug}/index.html`}">${p.slug==='museo'?(es?'Visitar museo':'Visit museum'):(es?'Notebook web':'Web notebook')} ↗</a>${p.slug==='llms'?`<a class="immersive-ready" href="./llms/cinema.html">${es?'Vista cinemática':'Cinematic view'} ✦</a>`:''}${p.slug==='museo'?'':immersive?`<a class="immersive-ready" href="${immersive}">${es?'Entrar en 3D':'Enter 3D'} →</a>`:`<span>${es?'Inmersivo 3D · próximamente':'Immersive 3D · coming later'}</span>`}</div></article>`;
}).join('');
const countLabel=n=>String(n).padStart(2,'0')+' '+(es?'EXPLORACIONES':'EXPLORATIONS');
document.querySelector('[data-copy="count"]').textContent=countLabel(explorations.length);
const filters=[['all',es?'Todo':'All'],['walk',es?'Para caminar':'Walkable'],['3d',es?'Escenas 3D':'3D scenes'],['2d',es?'Gráficos 2D':'2D charts'],['voice',es?'Con voz':'Narrated']];
const filterBar=document.querySelector('#filters'),cards=[...document.querySelectorAll('.exploration')];
const has=(card,k)=>k==='all'||card.dataset.traits.split(' ').includes(k);
filterBar.innerHTML=filters.map(([k,label])=>`<button type="button" data-filter="${k}" aria-pressed="${k==='all'}">${label} <span>${cards.filter(c=>has(c,k)).length}</span></button>`).join('');
function applyFilter(k){let shown=0;for(const c of cards){c.hidden=!has(c,k);shown+=!c.hidden;}filterBar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===k)));document.querySelector('[data-copy="count"]').textContent=countLabel(shown);try{sessionStorage.setItem('atlas-filter',k);}catch{}}
filterBar.onclick=e=>{const b=e.target.closest('[data-filter]');if(b)applyFilter(b.dataset.filter);};
try{const saved=sessionStorage.getItem('atlas-filter');if(saved&&filters.some(([k])=>k===saved))applyFilter(saved);}catch{}
