import * as THREE from '../vendor/three.module.js';
import {sampleCell} from './cell-model.js';

export const CELL_FOCUS=[[-3.9,4.3,-1.2],[-.85,4.0,.2],[4.7,3.25,-.55],[3.4,4.0,-2.2]];
export const cellOverview={yaw:.06,pitch:.25,distance:9.5};
export const CELL_BOUNDS=[[-6.7,2.45,-2.2,-.3,6.85,1.8],[-4.4,2.55,-1.75,8.1,6.3,1.6],[1.1,2.0,-1.6,8.7,6.45,1.6],[-3.4,1.05,-5.0,10.0,6.9,2.1],[-11.8,.1,-8.2,14.0,9.6,9.3]];
const NC=new THREE.Vector3(-3.5,4.4,-1.4),NPC_NORMAL=new THREE.Vector3(Math.sqrt(3)/2,0,.5),NPC_CENTER=NC.clone().addScaledVector(NPC_NORMAL,2.7),SPACING=.43,CODON_SPACING=SPACING*3;
export function cellPoseAt(i){const x=[-7.8,-1.5,5.5,11.6][i],z=11.2,[tx,ty,tz]=CELL_FOCUS[i];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export function cellWalk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),d=3.8*Math.min(.05,dt),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*d,-15,15),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*d,-10,15);const inside=(px,pz)=>(px/11.6)**2+((pz+1)/7.6)**2<1;if(inside(x,p.z))x=p.x;if(inside(x,z))z=p.z;return {...p,x,z};}
const C={A:0x91dcc0,U:0xf0c382,T:0xf0c382,G:0xc6a2dc,C:0x80bde6,Met:0xf1c385,Ala:0x91cbe5,Phe:0xe8a8ce,Glu:0xa9d59f};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));

export function createCellScene(lesson,es=true){
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x192d3c);scene.fog=new THREE.Fog(0x192d3c,55,120);
 const resources=[],targets=[],stands=[],own=x=>(resources.push(x),x),t=(a,b)=>es?a:b,L=(a,b)=>[a,b],mat=(color,extra={})=>own(new THREE.MeshStandardMaterial({color,roughness:.52,metalness:.04,...extra}));
 scene.add(new THREE.HemisphereLight(0xd6eaff,0x3c424c,2.6));const sun=new THREE.DirectionalLight(0xffe1ce,3);sun.position.set(-10,17,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-17,right:17,top:14,bottom:-14,near:.1,far:55});sun.shadow.normalBias=.045;scene.add(sun);resources.push(sun.shadow);
 function mesh(g,geo,material,p=[0,0,0]){const m=new THREE.Mesh(geo,material);m.position.set(...p);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
 function box(g,p,size,color,extra){return mesh(g,own(new THREE.BoxGeometry(...size)),mat(color,extra),p);}
 function ball(g,p,r,color,extra){return mesh(g,own(new THREE.SphereGeometry(r,20,14)),mat(color,extra),p);}
 function cylinder(g,p,r,h,color,extra){return mesh(g,own(new THREE.CylinderGeometry(r,r,h,16)),mat(color,extra),p);}
 function rod(g,a,b,r,color,extra={}){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),m=cylinder(g,p.clone().add(q).multiplyScalar(.5).toArray(),r,p.distanceTo(q),color,extra);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());return m;}
 function tube(g,points,r,color,extra={},segments=48){const curve=points instanceof THREE.Curve?points:new THREE.CatmullRomCurve3(points.map(p=>p instanceof THREE.Vector3?p:new THREE.Vector3(...p)));return {mesh:mesh(g,own(new THREE.TubeGeometry(curve,segments,r,7,false)),mat(color,extra)),curve};}
 function label(g,words,p,width=3,{height=96,bg=true,depthTest=true}={}){
  const material=own(new THREE.SpriteMaterial({transparent:true,depthWrite:false,depthTest})),m=new THREE.Sprite(material),cache=new Map();m.position.set(...p);g.add(m);if(!depthTest)m.renderOrder=10;let last;
  // A GPU texture keeps its original image dimensions. Each distinct caption
  // gets an immutable canvas, then reuses that texture when seeking backward.
  function set(value){const words=String(value);if(words===last)return;last=words;let entry=cache.get(words);
   if(!entry){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),lines=words.split('\n');ctx.font='600 60px system-ui';canvas.width=Math.max(96,Math.min(2048,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line).width))+48)));canvas.height=height;if(bg){ctx.fillStyle='#173341ec';ctx.fillRect(0,0,canvas.width,height);}ctx.fillStyle='#f4f7f8';ctx.font='600 60px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,height*(i+.5)/lines.length,canvas.width-36));const texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;entry={texture,height:width*height/canvas.width};cache.set(words,entry);}
   material.map=entry.texture;material.needsUpdate=true;m.scale.set(width,entry.height,1);
  }set(words);return {m,set};
 }
 function inspect(object,a,b){object.userData.info=L(a,b);targets.push(object);return object;}
 function shell(g,radius,p,scale,color,predicate,opacity=.18){const geometry=own(new THREE.SphereGeometry(radius,64,40)),positions=geometry.attributes.position,indices=geometry.index.array,keep=[];for(let i=0;i<indices.length;i+=3){const c=new THREE.Vector3();for(let j=0;j<3;j++)c.add(new THREE.Vector3().fromBufferAttribute(positions,indices[i+j]));c.normalize();if(predicate(c))keep.push(indices[i],indices[i+1],indices[i+2]);}geometry.setIndex(keep);geometry.computeVertexNormals();const m=mesh(g,geometry,mat(color,{transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide}),p);m.scale.set(...scale);m.castShadow=false;return m;}
 function ellipse(g,center,rx,ry,z,r,color){const points=[];for(let i=0;i<=96;i++){const a=i/96*Math.PI*2;points.push([center[0]+Math.cos(a)*rx,center[1]+Math.sin(a)*ry,z]);}return tube(g,points,r,color,{},96).mesh;}
 const annotations=new THREE.Group();scene.add(annotations);const zoneAnnotations=Array.from({length:4},()=>{const g=new THREE.Group();annotations.add(g);return g;});
 const floor=box(scene,[0,-.16,1],[32,.3,29],0x2d4350);for(let x=-14;x<=14;x+=2)box(scene,[x,.015,1],[.012,.012,27],0x3e5863);for(let z=-11;z<=13;z+=2)box(scene,[0,.015,z],[30,.012,.012],0x3e5863);const platform=cylinder(scene,[0,.16,-1],11.5,.30,0x355762);platform.scale.z=.72;
 // Front section is open: these are two membrane surfaces, not an opaque ball over the mechanism.
 const outer=shell(scene,1,[0,4.5,-1],[11,4.2,7],0xbfa2cb,c=>c.z<=.25,.10),inner=shell(scene,1,[0,4.5,-1],[10.88,4.10,6.88],0x89bcb8,c=>c.z<=.25,.10),cutFactor=Math.sqrt(1-.25**2);
 const rim=[ellipse(scene,[0,4.5],11*cutFactor,4.2*cutFactor,.75,.045,0xcbb2d7),ellipse(scene,[0,4.5],10.88*cutFactor,4.1*cutFactor,.72,.040,0x99cbc6)];
 const membrane={outer,inner,rim};inspect(outer,'Membrana celular: dos superficies de una bicapa, con una sección frontal abierta para ver el interior. Toda la célula está ampliada; no es una escala física.','Cell membrane: two bilayer surfaces, with an open front section to see inside. The entire cell is enlarged; this is not a physical scale.');
 // The nuclear window leaves the right flank intact. Both envelope layers have a genuine pore hole.
 const nuclearPredicate=c=>!(c.z>0&&c.x<.35)&&c.dot(NPC_NORMAL)<Math.cos(.255);
 const nuclearOuter=shell(scene,2.7,NC.toArray(),[1,1,1],0xc697c8,nuclearPredicate,.18),nuclearInner=shell(scene,2.57,NC.toArray(),[1,1,1],0x9fafd3,nuclearPredicate,.12);inspect(nuclearOuter,'Envoltura nuclear doble y seccionada. El ADN permanece en el núcleo; la copia mensajera atraviesa un poro real en ambas capas.','Double, sectioned nuclear envelope. DNA stays in the nucleus; the messenger copy crosses a real pore in both layers.');
 const poreGroup=new THREE.Group();poreGroup.position.copy(NPC_CENTER);poreGroup.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),NPC_NORMAL);scene.add(poreGroup);const rings=[],lobes=[];for(const [r,z] of [[.68,.035],[.63,-.13]])rings.push(mesh(poreGroup,own(new THREE.TorusGeometry(r,.065,8,48)),mat(0xe0bca5),[0,0,z]));for(let i=0;i<8;i++){const a=i/8*Math.PI*2,x=Math.cos(a)*.66,y=Math.sin(a)*.66;lobes.push(ball(poreGroup,[x,y,.10],.105,0xd5b69f));rod(poreGroup,[x,y,.10],[Math.cos(a)*.79,Math.sin(a)*.79,.42],.022,0xcabdd3);}
 const pore={group:poreGroup,center:NPC_CENTER.clone(),normal:NPC_NORMAL.clone(),rings,lobes,holeRadius:.56};rings.forEach(r=>inspect(r,'Poro nuclear: anillo esquemático de simetría octogonal, que comunica núcleo y citosol. La copia pasa por el hueco; la geometría no modela selectividad molecular.','Nuclear pore: schematic octagonal ring connecting nucleus and cytosol. The copy passes through the opening; geometry does not model molecular selectivity.'));
 const dnaGroup=new THREE.Group();scene.add(dnaGroup);const dnaPositions=[[],[]],pairs=[];for(let i=0;i<15;i++){const a=i*.67,y=3.00+i*.18,p=new THREE.Vector3(-3.9+Math.cos(a)*.62,y,-1.2+Math.sin(a)*.62),q=new THREE.Vector3(-3.9-Math.cos(a)*.62,y,-1.2-Math.sin(a)*.62);dnaPositions[0].push(p);dnaPositions[1].push(q);const mid=p.clone().lerp(q,.5),coding=rod(dnaGroup,p.toArray(),mid.toArray(),.043,0x8dccbc),template=rod(dnaGroup,mid.toArray(),q.toArray(),.043,0xefc19a);pairs.push({index:i,coding,template});}
 const strands=dnaPositions.map((points,i)=>tube(dnaGroup,points,.070,i?0xefbd9c:0x89badd,{},80).mesh);strands.forEach(m=>inspect(m,'ADN de doble hebra retenido en el núcleo. Solo ampliamos quince pares del fragmento sintético; no es un gen completo.','Double-stranded DNA retained in the nucleus. We enlarge only fifteen pairs from the synthetic fragment; this is not a complete gene.'));
 const dna={group:dnaGroup,strands,pairs,positions:dnaPositions};const nucleus={outer:nuclearOuter,inner:nuclearInner,dna,pore};
 const polymeraseGroup=new THREE.Group();scene.add(polymeraseGroup);const polymeraseBody=ball(polymeraseGroup,[0,0,0],.30,0xebcf9b);const jaw1=ball(polymeraseGroup,[.15,.13,.02],.20,0xc6b590),jaw2=ball(polymeraseGroup,[.15,-.13,.02],.20,0xc6b590);const polymerase={group:polymeraseGroup,body:polymeraseBody,jaws:[jaw1,jaw2]};inspect(polymeraseBody,'ARN polimerasa esquemática: usa una hebra molde de ADN para sintetizar una copia de RNA. El ADN no se convierte en RNA ni sale del núcleo.','Schematic RNA polymerase: uses a DNA template strand to synthesize an RNA copy. DNA does not turn into RNA or leave the nucleus.');
 const nuclearRNA=Array.from({length:15},(_,i)=>new THREE.Vector3(-3.05+Math.sin(i*.55)*.16,3.02+i*.15,-.90+Math.cos(i*.55)*.20)),finalRNA=Array.from({length:15},(_,i)=>new THREE.Vector3(1.5+i*SPACING,3.25,-.55)),approach=NPC_CENTER.clone().addScaledVector(NPC_NORMAL,-.80),exit=NPC_CENTER.clone().addScaledVector(NPC_NORMAL,.85);
 function exportPath(start,end){const curve=new THREE.CurvePath();curve.add(new THREE.QuadraticBezierCurve3(start.clone(),new THREE.Vector3(-2.7,4.4,-.85),approach.clone()));curve.add(new THREE.LineCurve3(approach.clone(),NPC_CENTER.clone()));curve.add(new THREE.LineCurve3(NPC_CENTER.clone(),exit.clone()));curve.add(new THREE.QuadraticBezierCurve3(exit.clone(),new THREE.Vector3(1.05,3.9,.20),end.clone()));return curve;}
 const baseCurves=nuclearRNA.map((p,i)=>exportPath(p,finalRNA[i])),exportCurve=baseCurves[0],mrnaGroup=new THREE.Group();scene.add(mrnaGroup);mrnaGroup.userData.moleculeId='mrna-copy-1';const bases=[];
 for(let i=0;i<15;i++){const m=ball(mrnaGroup,nuclearRNA[i].toArray(),.085,C.A,{emissive:C.A,emissiveIntensity:.16});bases.push({index:i,mesh:m,base:null,codonIndex:Math.floor(i/3),curve:baseCurves[i]});}
 const backboneGeo=own(new THREE.CylinderGeometry(.022,.022,1,8)),backboneMat=mat(0x94d4c4,{emissive:0x7daea4,emissiveIntensity:.15}),backbone=[];for(let i=0;i<14;i++)backbone.push(mesh(mrnaGroup,backboneGeo,backboneMat));
 const marker=ball(mrnaGroup,[0,0,0],.12,0xffe7a6,{emissive:0xffd479,emissiveIntensity:.8});const markerCaption=label(zoneAnnotations[1],'5′',[0,0,0],.46,{bg:false,depthTest:false});const codons=[];
 for(let i=0;i<5;i++){const caption=label(scene,'',[0,0,0],1.02,{height:80,bg:false,depthTest:false}),highlight=box(mrnaGroup,[0,0,0],[1.14,.035,.28],0xf4d494,{emissive:0xefd58d,emissiveIntensity:.55});codons.push({index:i,caption,highlight,anchor:new THREE.Vector3(),status:'future',codon:null});}
 const anchors=Array.from({length:5},(_,i)=>finalRNA[3*i+1].clone()),mrna={id:'mrna-copy-1',group:mrnaGroup,bases,backbone,codons,marker,markerCaption,exportCurve,baseCurves,anchors,finalPositions:finalRNA};bases.forEach(base=>inspect(base.mesh,'Una base de la misma copia de mRNA. La cadena no desaparece ni se consume al traducirse; el fragmento visible tiene cinco codones y la lectura termina en el primer Stop.','A base of the same mRNA copy. The chain does not disappear or get consumed during translation; the visible fragment contains five codons and reading ends at the first Stop.'));
 // Two cutaway subunits expose the mRNA channel. A/P offsets agree with physical codon spacing.
 const ribosomeGroup=new THREE.Group();scene.add(ribosomeGroup);const large=shell(ribosomeGroup,1,[0,.94,0],[1.30,.82,.83],0xd9a3bf,c=>c.z<.30,.73),small=shell(ribosomeGroup,1,[0,-.49,0],[1.12,.32,.68],0x949aca,c=>c.z<.65,.84);const subunitRims=[ellipse(ribosomeGroup,[0,.94],1.24,.78,.25,.028,0xebbed0),ellipse(ribosomeGroup,[0,-.49],.88,.25,.45,.025,0xb9bcdf)];
 const sites={P:new THREE.Vector3(-CODON_SPACING/2,.03,.04),A:new THREE.Vector3(CODON_SPACING/2,.03,.04),E:new THREE.Vector3(-CODON_SPACING*1.5,.03,.04)},siteLabels={P:label(ribosomeGroup,'P',[-CODON_SPACING/2,.22,.85],.35,{height:80,bg:false,depthTest:false}),A:label(ribosomeGroup,'A',[CODON_SPACING/2,.22,.85],.35,{height:80,bg:false,depthTest:false})},ribosome={group:ribosomeGroup,large,small,subunitRims,sites,siteLabels,anchors,site:null};inspect(large,'Subunidad grande de un ribosoma citosólico, con sección abierta para ver el proceso. Los aminoácidos y RNA están ampliados de manera distinta; no es una estructura atómica.','Large subunit of a cytosolic ribosome, opened to reveal the process. Amino acids and RNA use different magnifications; this is not an atomic structure.');inspect(small,'Subunidad pequeña: sitúa el mensajero y participa en la lectura. El canal entre subunidades sigue la misma copia de mRNA de 5′ a 3′.','Small subunit: positions the messenger and participates in reading. The channel between subunits follows the same mRNA copy from 5′ to 3′.');
 function trna(kind){const group=new THREE.Group();ribosomeGroup.add(group);const shape=tube(group,[[0,.01,0],[0,.27,0],[.10,.66,-.08],[.40,.70,-.08],[.45,.95,.10]],.035,kind==='initiator'?0xe3bb80:0x87c5bd);const anti=[];for(let i=0;i<3;i++)anti.push(ball(group,[-.075+i*.075,0,0],.040,0xb3ddd5));const aminoAcid=ball(group,[.45,.99,.10],.12,C.Met,{emissive:C.Met,emissiveIntensity:.22});return {group,body:shape.mesh,anticodon:anti,aminoAcid,kind,site:null,bound:false,codonIndex:null,value:null};}
 const trnas={initiator:trna('initiator'),elongation:trna('elongation'),peptidyl:trna('peptidyl')};Object.values(trnas).forEach(record=>inspect(record.body,'ARN de transferencia esquemático en forma de L. Su extremo inferior se coloca sobre un codón; lleva un aminoácido al centro de síntesis. No dibujamos reglas mecánicas de anticodón ni un tRNA para Stop.','Schematic L-shaped transfer RNA. Its lower end sits over a codon; it brings an amino acid to the synthesis centre. We do not draw mechanical anticodon rules or a tRNA for Stop.'));
 const factorGroup=new THREE.Group();ribosomeGroup.add(factorGroup);const factorBody=ball(factorGroup,[.06,.36,0],.15,0xe9dab5);rod(factorGroup,[.06,.15,0],[.35,.90,.08],.035,0xd6c4a3);ball(factorGroup,[.35,.90,.08],.095,0xe9dab5);const releaseFactor={group:factorGroup,body:factorBody,site:'A',bound:false,active:false};inspect(factorBody,'Factor de liberación eucariota esquemático: reconoce Stop en el sitio A y permite liberar la cadena. UAA no codifica un aminoácido y no tiene un tRNA de Stop.','Schematic eukaryotic release factor: recognizes Stop at the A site and enables chain release. UAA does not encode an amino acid and has no Stop tRNA.');
 const chainGroup=new THREE.Group();scene.add(chainGroup);const residues=[],bonds=[],residueGeometry=own(new THREE.SphereGeometry(.14,18,12));for(let i=0;i<4;i++){const m=mesh(chainGroup,residueGeometry,mat(C.Met,{emissive:C.Met,emissiveIntensity:.20}));const caption=label(chainGroup,'',[0,0,0],.58,{bg:false,depthTest:false});residues.push({index:i,mesh:m,caption,aminoAcid:null});if(i<3)bonds.push(mesh(chainGroup,own(new THREE.CylinderGeometry(.030,.030,1,8)),mat(0xe3cfbd)));}const chain={group:chainGroup,residues,bonds,length:0,attached:false,released:false,position:chainGroup.position};residues.forEach(record=>inspect(record.mesh,'Residuo de la cadena artificial. Se añade únicamente al evento de aceptación del modelo. La cadena de dos o cuatro aminoácidos no representa una proteína funcional ni un plegado real.','Residue of the artificial chain. It is added only at the model acceptance event. The two- or four-amino-acid chain represents neither a functional protein nor a real fold.'));
 // Context organelles remain in the same cell. This cytosolic example does not route through ER/Golgi.
 const mitoGroup=new THREE.Group();mitoGroup.position.set(-1.0,2.0,-3.4);scene.add(mitoGroup);const mitoOuter=shell(mitoGroup,1,[0,0,0],[1.75,.67,.91],0xe4ac83,c=>c.z<.33,.77),mitoInner=shell(mitoGroup,1,[0,0,0],[1.58,.53,.75],0xae7e83,c=>c.z<.33,.65),cristae=[];for(let i=0;i<7;i++){const x=-1.25+i*.41;cristae.push(tube(mitoGroup,[[x,-.42,-.18],[x+.16,-.08,.16],[x,.35,.11],[x-.11,.07,-.12]],.065,0xad7695).mesh);}const mitochondrion={group:mitoGroup,outer:mitoOuter,inner:mitoInner,cristae};inspect(mitoOuter,'Mitocondria con membrana exterior, membrana interior y crestas. Contribuye a producir ATP; no es el destino obligatorio de esta cadena.','Mitochondrion with outer membrane, inner membrane and cristae. It contributes to ATP production; it is not a compulsory destination for this chain.');
 const erGroup=new THREE.Group();scene.add(erGroup);const erSheets=[],erRibosomes=[];for(let row=0;row<4;row++){const points=[[-1.8,5.2+row*.28,-3.1],[.0,5.1+row*.28,-3.7],[1.6,5.5+row*.26,-4.3],[2.4,5.6+row*.20,-3.6]],sheet=tube(erGroup,points,.16,0x84b9c0,{},40).mesh;erSheets.push(sheet);for(let j=0;j<6;j++){const p=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))).getPoint(j/5);p.y+=.17;erRibosomes.push(ball(erGroup,p.toArray(),.050,0xba9fc7));}}const er={group:erGroup,sheets:erSheets,ribosomes:erRibosomes};inspect(erSheets[0],'Retículo endoplásmico esquemático cerca de la envoltura nuclear. Sus rutas incluyen ciertas proteínas; el ribosoma de este ejemplo es citosólico y la cadena no entra aquí.','Schematic endoplasmic reticulum near the nuclear envelope. Its routes include certain proteins; this example ribosome is cytosolic and its chain does not enter here.');
 const golgiGroup=new THREE.Group();golgiGroup.position.set(5.8,5.2,-3.9);scene.add(golgiGroup);const cisternae=[],vesicles=[];for(let i=0;i<5;i++){const sack=tube(golgiGroup,[[-1.10,.25*i,-.20],[-.50,.25*i+.07,.18],[.50,.25*i+.07,.18],[1.10,.25*i,-.20]],.095,0xb6bbdd,{},36).mesh;cisternae.push(sack);}for(const [x,y,z] of [[1.45,.4,.1],[-1.40,.6,.1],[1.30,1.25,-.1],[-1.25,-.1,.1]])vesicles.push(ball(golgiGroup,[x,y,z],.11,0xc8c5df));const golgi={group:golgiGroup,cisternae,vesicles};inspect(cisternae[0],'Aparato de Golgi: sacos aplanados y vesículas, representación esquemática. Participa en determinadas modificaciones y rutas; no enviamos esta cadena artificial automáticamente al Golgi.','Golgi apparatus: flattened sacs and vesicles, schematic representation. It participates in certain modifications and routes; this artificial chain is not automatically sent to the Golgi.');
 const organelles={mitochondrion,er,golgi};
 label(zoneAnnotations[0],t('ADN RETENIDO · COPIA EN RNA','DNA RETAINED · RNA COPY'),[-3.9,6.65,.3],5.7,{height:80});const dnaCaption=label(zoneAnnotations[0],'',[-3.9,6.06,.5],5.5,{height:128,depthTest:false}),copyStatus=label(zoneAnnotations[0],'',[-3.9,2.68,1.3],5.4,{height:80,depthTest:false});
 label(zoneAnnotations[1],t('SALE LA MISMA COPIA','THE SAME COPY LEAVES'),[-.5,6.05,.9],5.1,{height:80});const exportCaption=label(zoneAnnotations[1],'',[-.5,5.48,1.1],4.8,{height:80,depthTest:false});
 const riboCaption=label(zoneAnnotations[2],'',[3.3,5.85,1.0],4.3,{height:128,depthTest:false}),directionCaption=label(zoneAnnotations[2],'5′ → 3′',[4.8,2.2,.8],1.5,{height:80,depthTest:false});
 const chainCaption=label(zoneAnnotations[3],'',[4.5,6.65,1.0],5.8,{height:80,depthTest:false});label(zoneAnnotations[3],t('Mitocondria · crestas','Mitochondrion · cristae'),[-1,1.28,-2.35],3.4,{height:80});label(zoneAnnotations[3],t('Retículo endoplásmico','Endoplasmic reticulum'),[-.4,6.55,-3.25],3.8,{height:80});label(zoneAnnotations[3],t('Golgi','Golgi'),[8.35,5.9,-3.1],1.6,{height:80});
 const overviewLabelsGroup=new THREE.Group();scene.add(overviewLabelsGroup);for(const [words,x,width] of [[t('NÚCLEO','NUCLEUS'),-7.8,3.1],[t('COPIA mRNA','mRNA COPY'),-1.5,3.6],[t('TRADUCCIÓN','TRANSLATION'),5.5,4.0],[t('CONTEXTO CELULAR','CELL CONTEXT'),11.6,4.7]])label(overviewLabelsGroup,words,[x,.72,8.1],width,{height:80,depthTest:false});
 const standsGroup=new THREE.Group();scene.add(standsGroup);for(let i=0;i<4;i++){const x=[-7.8,-1.5,5.5,11.6][i],z=8.7;box(standsGroup,[x,.52,z],[1.7,1.04,.75],0x294955);box(standsGroup,[x,1.09,z],[1.9,.09,.95],0x9da9af);const button=box(standsGroup,[x,1.23,z+.12],[.85,.20,.5],0xffd991,{emissive:0xdfb876,emissiveIntensity:.45});button.userData.action=i;targets.push(button);stands.push(button);label(standsGroup,`${i+1} · ${(es?['COPIAR','EXPORTAR','TRADUCIR','CONTEXTO']:['COPY','EXPORT','TRANSLATE','CONTEXT'])[i]}`,[x,.67,z+.40],1.65);label(standsGroup,t('▶ ESCUCHAR','▶ LISTEN'),[x,1.34,z+.20],.86);}
 let lastState;
 const placeBond=(m,p,q)=>{m.position.copy(p).add(q).multiplyScalar(.5);m.scale.y=p.distanceTo(q);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.clone().sub(p).normalize());};
 const aminoColor=(m,name)=>{m.material.color.setHex(C[name]||0xb8c7c8);m.material.emissive?.setHex(C[name]||0xb8c7c8);};
 function riboPosition(s){const i=s.translation.codonIndex??0,w=s.translation.window,base=anchors[i].x-(i===0?-CODON_SPACING/2:CODON_SPACING/2);let shift=0;if(w&&w.kind==='elongation')shift=clamp((s.time-w.commit)/(w.end-w.commit))*CODON_SPACING;return new THREE.Vector3(base+shift,3.25,-.55);}
 function update(model,time=0,phase=0,whole=false,immersive=false){
  const s=sampleCell(model.trace,Number.isFinite(time)?time:0);lastState=s;const letters=s.sequence.join(''),coding=s.dna.coding.join(''),template=s.dna.template.join('');pairs.forEach((pair,i)=>{pair.coding.material.color.setHex(C[coding[i]]);pair.template.material.color.setHex(C[template[i]]);pair.coding.userData.base=coding[i];pair.template.userData.base=template[i];});dna.coding=[...s.dna.coding];dna.template=[...s.dna.template];
  const polymeraseIndex=s.transcription.progress*14,polymeraseLow=Math.min(14,Math.floor(polymeraseIndex));polymeraseGroup.position.copy(dnaPositions[1][polymeraseLow]).lerp(dnaPositions[1][Math.min(14,polymeraseLow+1)],polymeraseIndex-polymeraseLow);polymeraseGroup.position.x+=.18;polymeraseGroup.visible=!s.transcription.complete;const exportProgress=s.mrna.exportProgress;
  bases.forEach((base,i)=>{base.base=letters[i];base.mesh.material.color.setHex(C[base.base]);base.mesh.material.emissive.setHex(C[base.base]);base.mesh.visible=i<s.transcription.nucleotidesCopied;const u=clamp(exportProgress*1.45-i/14*.45);base.mesh.position.copy(exportProgress<=0?nuclearRNA[i]:exportProgress>=1?finalRNA[i]:base.curve.getPoint(u));});
  backbone.forEach((m,i)=>{m.visible=bases[i].mesh.visible&&bases[i+1].mesh.visible;if(m.visible)placeBond(m,bases[i].mesh.position,bases[i+1].mesh.position);});marker.visible=bases[0].mesh.visible;marker.position.copy(bases[0].mesh.position);markerCaption.m.position.copy(marker.position).add(new THREE.Vector3(-.20,.30,.35));
  codons.forEach((record,i)=>{record.codon=s.sequence[i];record.status=s.codons[i].status;record.anchor.copy(bases[3*i+1].mesh.position);record.caption.set(record.codon);record.caption.m.position.copy(record.anchor).add(new THREE.Vector3(0,-.43,1.00));record.caption.m.visible=!whole&&s.mrna.exported&&(phase===2||phase===3);record.caption.m.material.opacity=record.status==='skipped'?.32:1;record.highlight.position.copy(record.anchor).add(new THREE.Vector3(0,-.18,.0));record.highlight.visible=!!s.codons[i].active;});
  ribosomeGroup.position.copy(riboPosition(s));ribosomeGroup.visible=s.mrna.exported;Object.values(siteLabels).forEach(record=>record.m.visible=!whole&&phase===2);const window=s.translation.window,translocation=window?.kind==='elongation'?clamp((s.time-window.commit)/(window.end-window.commit)):0;large.position.y=.94+(s.translation.recycled?.52:0);small.position.y=-.49-(s.translation.recycled?.22:0);subunitRims[0].position.y=s.translation.recycled?.52:0;subunitRims[1].position.y=s.translation.recycled?-.22:0;
  Object.values(trnas).forEach(record=>{record.group.visible=false;record.aminoAcid.visible=false;record.site=null;record.bound=false;record.codonIndex=null;record.value=null;});
  const activeTrna=s.translation.trna;if(activeTrna){const record=activeTrna.kind==='initiator'?trnas.initiator:trnas.elongation,site=sites[activeTrna.site].clone();if(activeTrna.kind==='elongation')site.x-=translocation*CODON_SPACING;record.group.visible=activeTrna.active;record.site=activeTrna.site;record.bound=activeTrna.bound;record.codonIndex=activeTrna.codonIndex;record.value=activeTrna.aminoAcid;record.group.position.copy(site).add(new THREE.Vector3((1-activeTrna.progress)*1.3,(1-activeTrna.progress)*.85,(1-activeTrna.progress)*.50));record.aminoAcid.visible=activeTrna.carryingAminoAcid;aminoColor(record.aminoAcid,activeTrna.aminoAcid);}
  if(s.chain.attached&&s.translation.peptidylSite==='P'&&activeTrna?.kind!=='initiator'){const carrier=s.chain.length===1?trnas.initiator:trnas.peptidyl;carrier.group.visible=true;carrier.group.position.copy(sites.P);carrier.site='P';carrier.bound=true;carrier.codonIndex=Math.max(0,(s.translation.codonIndex??1)-1);carrier.value=s.chain.aminoAcids.at(-1);carrier.aminoAcid.visible=false;}
  releaseFactor.active=!!s.translation.releaseFactor?.active;releaseFactor.bound=!!s.translation.releaseFactor?.bound;factorGroup.visible=releaseFactor.active;factorGroup.position.copy(sites.A);if(s.translation.releaseFactor)factorGroup.position.add(new THREE.Vector3((1-s.translation.releaseFactor.progress)*1.1,(1-s.translation.releaseFactor.progress)*.75,0));
  chain.length=s.chain.length;chain.attached=s.chain.attached;chain.released=s.chain.released;chain.releaseProgress=s.chain.releaseProgress;const site=s.translation.peptidylSite==='A'?sites.A.clone().add(new THREE.Vector3(-translocation*CODON_SPACING,0,0)):sites.P.clone(),anchor=ribosomeGroup.position.clone().add(site).add(new THREE.Vector3(.45,.95,.10));
  if(s.chain.released){const releaseState=sampleCell(model.trace,s.chain.releaseTime??model.trace.events.find(e=>e.type==='chain-released').at),releaseAnchor=riboPosition(releaseState).add(sites.P).add(new THREE.Vector3(.45,.95,.10));anchor.copy(releaseAnchor).add(new THREE.Vector3(.40*s.chain.releaseProgress,.60*s.chain.releaseProgress,1.15*s.chain.releaseProgress));}chainGroup.position.copy(anchor);
  residues.forEach((record,i)=>{record.aminoAcid=s.chain.aminoAcids[i]??null;record.mesh.visible=i<s.chain.length;record.mesh.position.set(Math.sin(i*.9)*.15,(s.chain.length-1-i)*.34,0);aminoColor(record.mesh,record.aminoAcid);record.caption.set(record.aminoAcid||'');record.caption.m.position.copy(record.mesh.position).add(new THREE.Vector3(.37,.03,.35));record.caption.m.visible=record.mesh.visible&&!whole&&(phase===2||phase===3);});bonds.forEach((m,i)=>{m.visible=i<s.chain.length-1;if(m.visible)placeBond(m,residues[i].mesh.position,residues[i+1].mesh.position);});
  dnaCaption.set(`5′ ${s.dna.coding.join(' · ')} 3′\n3′ ${s.dna.template.join(' · ')} 5′`);copyStatus.set(t('Fragmento sintético: ','Synthetic fragment: ')+s.transcription.nucleotidesCopied+' / 15 '+t('bases copiadas','bases copied'));exportCaption.set(!s.mrna.processed?t('Procesamiento condensado','Condensed processing'):!s.mrna.exported?t('mRNA por el poro · ADN retenido','mRNA through pore · DNA retained'):t('La copia permanece en el citosol','The copy remains in the cytosol'));
  const current=s.translation.codonIndex===null?'—':s.sequence[s.translation.codonIndex];riboCaption.set(s.translation.recycled?t('Ribosoma reciclado\nRNA conservado','Ribosome recycled\nRNA retained'):s.translation.releaseFactor?`${current} · ${t('Stop','Stop')}\n${t('Factor de liberación en A','Release factor at A')}`:activeTrna?`${current} → ${activeTrna.aminoAcid}\n${activeTrna.kind==='initiator'?t('ARNt iniciador en P','Initiator tRNA at P'):t('ARNt entrante en A','Incoming tRNA at A')}`:t('Cinco codones ampliados\nLectura hasta el primer Stop','Five enlarged codons\nRead through the first Stop'));chainCaption.set((s.chain.released?t('Cadena liberada: ','Released chain: '):t('Cadena artificial: ','Artificial chain: '))+(s.chain.aminoAcids.join('–')||'—'));
  zoneAnnotations.forEach((group,i)=>group.visible=!whole&&i===phase);overviewLabelsGroup.visible=whole;standsGroup.visible=immersive;stands.forEach((button,i)=>button.material.emissiveIntensity=i===phase?1:.16);markerCaption.m.visible=marker.visible&&!whole&&phase===1;
 }
 return {scene,resources,targets,stands,standsGroup,membrane,nucleus,dna,pore,polymerase,mrna,ribosome,trnas,releaseFactor,chain,organelles,annotations,zoneAnnotations,overviewLabelsGroup,parts:{floor,platform,membrane,nucleus,dna,pore,polymerase,mrna,ribosome,mitochondrion,er,golgi},outlines:[],focus:CELL_FOCUS,bounds:CELL_BOUNDS,update,get state(){return lastState;}};
}

export function cellFraming(phase,orbit={},aspect=1,fov=46){const whole=orbit.whole===true,index=whole?4:Math.max(0,Math.min(3,phase)),bounds=CELL_BOUNDS[index],center=new THREE.Vector3((bounds[0]+bounds[3])/2,(bounds[1]+bounds[4])/2,(bounds[2]+bounds[5])/2),yaw=orbit.yaw??cellOverview.yaw,pitch=orbit.pitch??cellOverview.pitch,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let distance=4;for(const x of [bounds[0],bounds[3]])for(const y of [bounds[1],bounds[4]])for(const z of [bounds[2],bounds[5]]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}distance*=1.12*(orbit.distance??cellOverview.distance)/cellOverview.distance;return {center,distance,direction,bounds};}
const visible=object=>{for(let o=object;o;o=o.parent)if(!o.visible)return false;return true;};
export function createCellWorld(options,legacyLesson,legacyEs,legacyInspect){const objectAPI=!!options?.container,host=objectAPI?options.container:options,lesson=objectAPI?options.lesson:legacyLesson,es=objectAPI?options.lang!=='en':legacyEs,onInspect=(objectAPI?options.onInspect:legacyInspect)||(()=>{}),initialMode=objectAPI?options.mode||'web':'web';
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);renderer.domElement.tabIndex=0;const built=createCellScene(lesson,es),camera=new THREE.PerspectiveCamera(46,1,.1,150),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let model,phase=0,elapsed=0;
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<1?65:46;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function nearest(player){let best=null,distance=5.8;built.stands.forEach((stand,i)=>{const p=stand.getWorldPosition(new THREE.Vector3()),d=Math.hypot(player.x-p.x,player.z-p.z);if(d<distance){best=i;distance=d;}});return best;}
 function hit(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);return ray.intersectObjects(built.targets.filter(visible))[0];}
 return {canvas:renderer.domElement,update(s,i){model=s;phase=i;},render(player,dt,animation,orbit=cellOverview,mode=initialMode,time){if(Number.isFinite(time))elapsed=time;else if(model&&Number.isFinite(model.t))elapsed=model.t;if(model)built.update(model,elapsed,phase,mode==='web'&&orbit.whole===true,mode==='immersive');if(mode==='immersive'){camera.position.set(player.x,1.65,player.z);camera.rotation.set(player.pitch,player.yaw,0,'YXZ');}else{const framing=cellFraming(phase,orbit,camera.aspect,camera.fov);camera.position.copy(framing.center).addScaledVector(framing.direction,framing.distance);camera.lookAt(framing.center);}renderer.render(built.scene,camera);},inspect(x,y){const h=hit(x,y);if(h)onInspect(h.object.userData.action===undefined?h.object.userData.info:{chapter:h.object.userData.action});},nearest,activate(){const r=renderer.domElement.getBoundingClientRect(),h=hit(r.left+r.width/2,r.top+r.height/2),chapter=h?.object.userData.action!==undefined&&h.distance<8?h.object.userData.action:nearest({x:camera.position.x,z:camera.position.z});if(chapter!==null)onInspect({chapter});},dispose(){observer.disconnect();built.resources.forEach(resource=>resource.dispose());renderer.dispose();},poseAt:lesson?.poseAt||cellPoseAt};
}
