import {L,control,metric,chapter,clamp} from './common.js';
import {buildGridTrace,sampleGrid} from './electricity-model.js';
export {gridRun} from './electricity-model.js';
let key,trace;
export function electricityExperiment(p){const next=[p.sun,p.demand,p.voltage].join(':');if(next!==key){trace=buildGridTrace(p);key=next;}return trace;}
export function electricityPose(i){const targets=[[-12,2.3,1.2],[-5.5,2,0],[4.7,2.2,0],[10.4,1.2,2.3]],x=[-14,-6,4,13][i],z=11.5,[tx,ty,tz]=targets[i];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export const electricity={id:'electricity',room:'industry',title:L('Electricidad: hasta el enchufe','Electricity: to the outlet'),color:'#ffd278',unit:L('hora','hour'),horizon:24,continuous:true,
 poseAt:electricityPose,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.8*Math.min(.05,dt);return {...p,x:clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-17,17),z:clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-10,13)};},
 overview:{yaw:.08,pitch:.4,distance:9.5},fitLabel:L('Ver la red completa','Fit the whole grid'),
 narrationTime(p,i,u){u=clamp(u,0,1);return i===0?6+12*u:i===1?12+.4*u:i===2?12.4+.6*u:24*Math.max(0,u-.18)/.82;},
 challenge:L('¿Puede la red cubrir la demanda al caer la noche?','Can the grid meet demand after sunset?'),
 controls:[control('sun',L('Solar máxima · MW','Peak solar · MW'),28,0,40),control('demand',L('Demanda · MW','Demand · MW'),22,10,45),control('voltage',L('Transporte · kV','Transmission · kV'),200,50,400,10)],
 steps:[chapter(L('1 · Convertir energía','1 · Converting energy'),L('El viento hace girar un generador. Los paneles convierten luz en electricidad. Sigue la potencia disponible durante un día: al anochecer desaparece la aportación solar. Un megavatio mide potencia; mantenerlo una hora produce un megavatio hora de energía.','Wind turns a generator. Panels convert light into electricity. Follow available power over a day: solar production disappears at night. A megawatt measures power; sustaining it for one hour produces one megawatt hour of energy.')),
 chapter(L('2 · Elevar la tensión','2 · Raising voltage'),L('Un transformador cambia la tensión de una corriente alterna. Para transportar la misma potencia, una tensión mayor permite una corriente menor. En nuestro circuito simplificado, la potencia es tensión por corriente y el calentamiento del cable es corriente al cuadrado por resistencia. Prueba el control de tensión.','A transformer changes alternating voltage. For the same power, higher voltage allows lower current. In our simplified circuit, power equals voltage times current, and cable heating equals current squared times resistance. Try the voltage control.')),
 chapter(L('3 · Atravesar la red','3 · Crossing the grid'),L('Las torres sostienen conductores; parte de la energía se transforma en calor. Las subestaciones vuelven a reducir la tensión antes de distribuirla. Las luces que recorren los cables representan transferencia de energía, no electrones viajando desde la central hasta tu casa.','Towers support conductors; some energy becomes heat. Substations reduce voltage again before distribution. Lights moving along these wires represent energy transfer, not electrons travelling from the power station to your home.')),
 chapter(L('4 · Equilibrar cada hora','4 · Balancing every hour'),L('La ciudad pide potencia y la batería guarda energía. Este ejemplo empieza con diez megavatios hora y permite cargar o descargar hasta seis megavatios. Avanza las horas: una batería vacía no cubre un déficit, y una llena obliga a recortar un excedente. El gráfico muestra demanda y suministro efectivo.','The city demands power and the battery stores energy. This example starts with ten megawatt hours and allows charging or discharging at up to six megawatts. Advance the hours: an empty battery cannot cover a shortage, and a full one forces surplus curtailment. The chart shows demand and actual supply.'))],
 limitations:L('Red aislada de ejemplo, no una red nacional ni una predicción. Los perfiles solar y eólico son sintéticos; cada intervalo dura una hora y las cifras MW son potencias medias de esa hora. El estado inicial a las 00:00 contiene 10 MWh; el nivel de batería y los totales MWh se interpolan dentro de la hora. Batería ideal de 20 MWh, carga/descarga máxima 6 MW y rendimiento 100 %. Recortamos generación en origen, proporcionalmente entre solar y viento; ese excedente nunca entra en el cable. Circuito AC equivalente con valores RMS, factor de potencia 1 y resistencia total 20 Ω: P = VI, pérdidas = I²R. La comparación del transformador mantiene 30 MW fijos. Transformadores e inversores ideales; se omiten frecuencia, potencia reactiva, topología trifásica, fallos y pérdidas de conversión/almacenamiento. Las luces indican transferencia de energía, no electrones recorriendo toda la red; su velocidad es ilustrativa. La casa es un ejemplo de consumo dentro de la ciudad: los MW del header pertenecen al conjunto. La guía demuestra tres mecanismos y luego reinicia explícitamente el balance diario a las 00:00.','Isolated example grid, not a national grid or a forecast. Solar and wind profiles are synthetic; each interval lasts one hour and MW figures are hourly mean powers. The initial state at 00:00 contains 10 MWh; battery level and cumulative MWh interpolate within the hour. Ideal 20 MWh battery, maximum charge/discharge 6 MW and 100% efficiency. Generation is curtailed at source, proportionally across solar and wind; that surplus never enters the cable. Equivalent AC circuit with RMS values, unity power factor and total resistance 20 Ω: P = VI, losses = I²R. The transformer comparison holds power at 30 MW. Ideal transformers and inverters; frequency, reactive power, three-phase topology, faults and conversion/storage losses are omitted. Lights indicate energy transfer, not electrons crossing the whole network; their speed is illustrative. The house exemplifies consumption within the city: header MW belong to the whole system. The guide demonstrates three mechanisms, then explicitly restarts the daily balance at 00:00.'),
 sources:[['EIA · Generation, transmission and distribution','https://www.eia.gov/energyexplained/electricity/delivery-to-consumers.php'],['DOE · Solar inverters and grid services','https://www.energy.gov/cmei/systems/solar-integration-inverters-and-grid-services-basics'],['EIA · Energy storage','https://www.eia.gov/energyexplained/electricity/energy-storage-for-electricity-generation.php']],
 evaluate(p,t){const trace=electricityExperiment(p),s=sampleGrid(trace,t),history=trace.states.slice(0,s.completed+1),powers=[...trace.hours,trace.hours.at(-1)];return {...s,trace,history,
 metrics:[metric(L('Entregado / solicitado','Delivered / requested'),`${s.served.toFixed(2)} / ${p.demand}`,'MW'),metric(L('Calor en el cable','Cable heat loss'),s.loss,'MW'),metric(L('Energía almacenada','Stored energy'),s.stored,'MWh'),metric(L('Corriente de transporte','Transmission current'),s.current,'A')],
 series:[{label:L('Suministro medio · MW','Mean supply · MW'),values:powers.map(h=>h.served)},{label:L('Demanda · MW','Demand · MW'),values:powers.map(()=>p.demand)}]};},
 // One connected scene is implemented in electricity-world.js.
 build(){return ()=>{};}
};
