import {L,control,toggle,metric,chapter,clamp} from './common.js';
import {buildEvolutionTrace,sampleEvolution} from './evolution-model.js';
export {evolve} from './evolution-model.js';
let key,trace;
export function evolutionExperiment(p){const next=[p.advantage,p.mutation,p.drift,p.seed].join(':');if(next!==key){trace=buildEvolutionTrace(p);key=next;}return trace;}
export function evolutionPose(i){const targets=[[-5,1.55,0],[0,3,-1.8],[5,2.8,.5],[0,1.6,0]],x=[-10,-3,5,10][i],z=11,[tx,ty,tz]=targets[i];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export const evolution={id:'evolution',room:'life',title:L('Evolución: muchas generaciones','Evolution: many generations'),color:'#b9df92',unit:L('generación','generation'),horizon:80,continuous:true,
 poseAt:evolutionPose,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.8*Math.min(.05,dt),dx=(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,dz=(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,inside=(x,z)=>Math.abs(x)<11.5&&Math.abs(z)<3.8;let x=clamp(p.x+dx,-13,13),z=clamp(p.z+dz,-7,13);if(inside(x,p.z))x=p.x;if(inside(x,z))z=p.z;return {...p,x,z};},
 overview:{yaw:.08,pitch:.5,distance:9.5},fitLabel:L('Ver ambas generaciones','Fit both generations'),
 narrationTime(p,index,progress){const u=clamp(progress,0,1);return index===0?0:index===1?.02+.38*u:index===2?.4+.6*u:1+79*u;},
 challenge:L('La ventaja cambia probabilidades; el azar decide las copias','Advantage changes probabilities; chance determines the copies'),controls:[control('advantage',L('Ventaja reproductiva de A · s','Reproductive advantage of A · s'),.15,-.4,.4,.05),control('mutation',L('Probabilidad de mutación por copia · μ','Mutation probability per copy · μ'),.01,0,.05,.005),toggle('drift',L('Población finita: 50 individuos','Finite population: 50 individuals'),true),control('seed',L('Repetición aleatoria · semilla','Random run · seed'),41,1,100)],
 steps:[chapter(L('1 · Variación heredable','1 · Heritable variation'),L('Esta población idealizada tiene dos variantes de un gen: A y B. Empezamos con la mitad de cada una. Los cuerpos recuerdan a células, pero sus colores son etiquetas del modelo, no especies reales. La evolución se mide aquí como un cambio en la frecuencia de esas variantes entre generaciones.','This idealised population has two variants of one gene: A and B. We start with half of each. The shapes resemble cells, but their colours are model labels, not real species. Here evolution is measured as a change in variant frequencies across generations.')),
 chapter(L('2 · Diferencias en reproducción','2 · Differences in reproduction'),L('Una ventaja positiva hace que A contribuya, en promedio, con más descendientes. Una ventaja negativa favorece a B. Cambia el control para representar otro entorno. Los individuos no deciden adaptarse: una diferencia heredable modifica las probabilidades reproductivas y la composición de la siguiente generación.','A positive advantage makes A contribute more offspring on average. A negative advantage favours B. Change the control to represent another environment. Individuals do not decide to adapt: an inherited difference changes reproductive probabilities and the composition of the next generation.')),
 chapter(L('3 · Copiar también introduce variación','3 · Copying also introduces variation'),L('En cada generación se seleccionan las variantes que formarán la siguiente y algunas copias pueden mutar. Nuestro modelo permite cambios de A a B y de B a A con igual probabilidad. Las mutaciones no aparecen porque un organismo las necesite. Esta tasa es didáctica, no una tasa genética medida.','Each generation selects the variants forming the next, and some copies may mutate. Our model allows A-to-B and B-to-A changes with equal probability. Mutations do not appear because an organism needs them. This rate is educational, not a measured genetic rate.')),
 chapter(L('4 · El azar cambia la trayectoria','4 · Chance changes the trajectory'),L('Con solo cincuenta individuos, el muestreo aleatorio puede aumentar o perder una variante: es deriva genética. Cambia la semilla para comparar historias. Desactiva población finita para ver la expectativa matemática. Con ventaja y mutación a cero, esa expectativa permanece estable, mientras una población pequeña puede fluctuar.','With only fifty individuals, random sampling can increase or lose a variant: this is genetic drift. Change the seed to compare histories. Disable finite population to see the mathematical expectation. With advantage and mutation at zero, that expectation stays stable while a small population can fluctuate.'))],
 limitations:L('Modelo Wright–Fisher haploide: un gen, dos variantes A/B, generaciones discretas y 50 individuos de igual tamaño. Cada descendiente procede de un progenitor de la generación anterior; A tiene peso reproductivo 1+s y B peso 1. La mutación por copia es simétrica, con probabilidad μ. La población cambia de composición, no de tamaño. Sin población finita se muestran proporciones continuas de una referencia determinista de población infinita, no 50 organismos redondeados ni la media exacta de poblaciones finitas bajo selección. Cambiar los controles recalcula la historia desde generación 0; no cambia el entorno a mitad de una historia. Las células, los tamaños y las tasas son ilustrativos, no datos de una especie. Sin migración, recombinación, dominancia, estructura espacial ni límites ecológicos.','Haploid Wright–Fisher model: one gene, two A/B variants, discrete generations and 50 equally sized individuals. Each offspring comes from a parent in the previous generation; A has reproductive weight 1+s and B has weight 1. Mutation per copy is symmetric with probability μ. Composition changes; population size does not. Disabling finite population shows continuous proportions of a deterministic infinite-population reference, not 50 rounded organisms or the exact mean of finite populations under selection. Changing controls recalculates the history from generation 0; it does not change the environment halfway through a run. Cells, sizes and rates are illustrative, not species data. No migration, recombination, dominance, spatial structure or ecological limits.'),
 sources:[['Genetics · Wright–Fisher, selection and mutation (2014)','https://pmc.ncbi.nlm.nih.gov/articles/PMC4224163/'],['NHGRI · Genetic drift','https://www.genome.gov/genetics-glossary/Genetic-Drift'],['NHGRI · Mutation','https://www.genome.gov/genetics-glossary/Mutation'],['UC Berkeley · Natural selection','https://evolution.berkeley.edu/evolution-101/mechanisms-the-processes-of-evolution/natural-selection/']],
 evaluate(p,t){const trace=evolutionExperiment(p),s=sampleEvolution(trace,t);return {...s,trace,advantage:p.advantage,mutation:p.mutation,history:trace.history.slice(0,s.t+1),metrics:[metric(L('Variante A','Variant A'),s.frequency*100,'%'),metric(L('Variante B','Variant B'),(1-s.frequency)*100,'%'),metric(L('Generaciones completadas','Completed generations'),s.t)],series:[{label:p.drift?L('A · tu población de 50','A · your population of 50'):L('A · proporción sin muestreo','A · proportion without sampling'),values:trace.history.map(x=>x*100)},{label:L('A · referencia determinista','A · deterministic reference'),values:trace.reference.map(x=>x*100)}]};},
 // The specialized renderer retains real parent/copy identities from the model.
 build(){return ()=>{};}
};
