import {L,control,toggle,metric,chapter,rng} from './common.js';
export function socialEdges(p){const edges=[],seen=new Set();const add=(a,b)=>{const key=[Math.min(a,b),Math.max(a,b)].join(':');if(!seen.has(key)){seen.add(key);edges.push([a,b]);}};for(let i=0;i<64;i++)for(let j=1;j<=p.contacts;j++)add(i,Math.floor(i/16)*16+(i+j)%16);if(p.bridges)for(let j=0;j<3;j++)add(j*16+8,(j+1)*16);return edges;}
export function spread(p,t){const edges=socialEdges(p),random=rng(731),known=new Set([0]),history=[1],activeHistory=[1],first=Array(64).fill(Infinity);first[0]=0;let active=[0];for(let turn=1;turn<=t;turn++){const next=new Set();for(const source of active)for(const [a,b] of edges){const target=a===source?b:b===source?a:-1;if(target>=0&&!known.has(target)&&random()<p.probability/100)next.add(target);}active=[...next].sort((a,b)=>a-b);active.forEach(i=>{known.add(i);first[i]=turn;});history.push(known.size);activeHistory.push(active.length);}return {edges,known,active,first,history,activeHistory};}
export const ideas={id:'ideas',room:'mind',title:L('Cómo se propaga una idea','How an idea spreads'),color:'#e5a5f2',unit:L('ronda','round'),horizon:24,
 challenge:L('Una persona, cuatro comunidades, 64 posibles lectores','One person, four communities, 64 possible readers'),controls:[control('probability',L('Probabilidad de transmitir · %','Transmission probability · %'),55,0,100,5),control('contacts',L('Vecinos por cada lado','Neighbours on each side'),2,1,4),toggle('bridges',L('Puentes entre comunidades','Bridges between communities'),true)],
 steps:[chapter(L('1 · Alguien comparte','1 · Someone shares'),L('Una persona conoce una idea y la transmite a sus contactos. Cada persona recién alcanzada tiene una sola ronda para intentar transmitirla. La probabilidad es un control del experimento, no una medida del comportamiento humano. Amarillo significa activo; verde, alcanzado anteriormente; gris, todavía no alcanzado.','One person knows an idea and shares it with contacts. Each newly reached person has one round to attempt transmission. Probability is an experimental control, not a measurement of human behaviour. Yellow means active; green means reached earlier; grey means not yet reached.')),
 chapter(L('2 · Una red puede multiplicar','2 · A network can multiply'),L('Si varias personas alcanzan a otras nuevas, las primeras rondas pueden crecer deprisa. Pero los contactos se repiten y muchos ya conocen la idea. Compara la curva verde con una referencia lineal que añade dos personas por ronda. No toda difusión crece exponencialmente, ni puede hacerlo para siempre.','When several people reach new people, early rounds can grow quickly. But contacts overlap and many already know the idea. Compare the green curve with a linear reference adding two people per round. Not every diffusion process grows exponentially, and none can do so forever in a finite population.')),
 chapter(L('3 · Cruzar una comunidad','3 · Crossing a community'),L('Estos cuatro grupos tienen conexiones internas y unos pocos puentes. Desactívalos: la idea queda encerrada en el primer grupo, aunque aumentes la probabilidad. La estructura de la red importa tanto como la facilidad de compartir. Un puente ofrece una oportunidad, no garantiza que el mensaje cruce.','These four groups have internal connections and a few bridges. Disable them: the idea stays in the first group even if you raise the probability. Network structure matters as much as ease of sharing. A bridge offers an opportunity; it does not guarantee that the message crosses.')),
 chapter(L('4 · Saturación o extinción','4 · Saturation or extinction'),L('El contador nunca supera las sesenta y cuatro personas de esta red. La difusión termina cuando no quedan emisores activos, incluso si algunas personas no recibieron nada. Este modelo describe contactos y transmisión; no mide verdad, persuasión, calidad ni la recomendación de una plataforma.','The counter never exceeds this network’s sixty-four people. Diffusion ends when no active senders remain, even if some people received nothing. This model describes contacts and transmission; it does not measure truth, persuasion, quality or a platform’s recommendation system.'))],
 limitations:L('Cascada independiente simplificada, red sintética no dirigida de 64 nodos y semilla aleatoria fija 731. Una oportunidad de transmisión por enlace desde cada nuevo emisor; sin olvido, reinfección ni algoritmos de recomendación. La línea naranja es una referencia aritmética, no otro resultado empírico.','Simplified independent cascade, synthetic undirected network of 64 nodes and fixed random seed 731. One transmission opportunity per edge from each new sender; no forgetting, reinfection or recommendation algorithms. Orange is an arithmetic reference, not another empirical result.'),
 sources:[['Northwestern · Diffusion on a Directed Network','https://ccl.northwestern.edu/netlogo/models/DiffusiononaDirectedNetwork'],['Diffusion of information in social networks · research','https://arxiv.org/abs/1704.03261']],
 evaluate(p,t){const s=spread(p,t);return {...s,t,metrics:[metric(L('Personas alcanzadas','People reached'),`${s.known.size} / 64`),metric(L('Emisores activos','Active senders'),s.active.length),metric(L('Comunidades alcanzadas','Communities reached'),new Set([...s.known].map(i=>Math.floor(i/16))).size)],series:[{label:L('Red · personas acumuladas','Network · people reached'),values:s.history},{label:L('Referencia lineal: +2 / ronda','Linear reference: +2 / round'),values:s.history.map((_,i)=>Math.min(64,1+2*i))}]};},
 build(k){const {group,sphere,cylinder,tube,label,pulse}=k;const person=(g,x,y,z)=>{sphere(g,[x,y+.45,z],.18,0xf2c898);return cylinder(g,[x,y,z],.18,.5,0x819bb1,L('Cada nuevo emisor dispone de una ronda para intentar compartir.','Each new sender has one round to attempt sharing.'));};const first=group(0);person(first,-2,1.8,0);const recipients=[];for(let i=0;i<4;i++){const x=1.5,y=.6+i*.8;recipients.push(person(first,x,y,0));tube(first,[[-2,1.8,0],[x,y,0]],.025,0x6e8196);}label(first,'1 → ?',0,3.8,0);
 const ring=group(1),ringNodes=[],ringPoints=[];for(let i=0;i<16;i++){const a=i/16*Math.PI*2,p=[Math.cos(a)*2.5,2+Math.sin(a)*1.6,0];ringPoints.push(p);ringNodes.push(sphere(ring,p,.19,0x536b80));}const ringLines=[];for(let i=0;i<16;i++)for(let j=1;j<=4;j++)ringLines.push({j,m:tube(ring,[ringPoints[i],ringPoints[(i+j)%16]],.013,0x607584)});
 const network=group(2),nodes=[],points=[];for(let i=0;i<64;i++){const c=Math.floor(i/16),a=(i%16)/16*Math.PI*2,p=[(c%2)*3-1.5+Math.cos(a)*1.05,1.2+Math.floor(c/2)*2+Math.sin(a)*.8,0];points.push(p);nodes.push(sphere(network,p,.095,0x536b80,L('Nodo: una persona. Los enlaces son contactos; un color nuevo indica que recibió la idea.','Node: one person. Edges are contacts; a new colour indicates receiving the idea.')));}const links=socialEdges({contacts:4,bridges:true}).map(([a,b])=>({a,b,m:tube(network,[points[a],points[b]],.01,Math.floor(a/16)!==Math.floor(b/16)?0xf5c986:0x556776)}));
 const end=group(3),population=[];for(let i=0;i<64;i++)population.push(sphere(end,[-2.8+(i%8)*.8,.45+Math.floor(i/8)*.45,0],.14,0x536b80));label(end,'64',0,4.2,0,1.5);
 const shade=(i,s)=>s.active.includes(i)?0xffd37d:s.known.has(i)?0x8be5bf:0x536b80;
 return(s)=>{recipients.forEach((m,i)=>m.material.color.setHex(shade(i+1,s)));ringNodes.forEach((m,i)=>m.material.color.setHex(shade(i,s)));nodes.forEach((m,i)=>m.material.color.setHex(shade(i,s)));population.forEach((m,i)=>m.material.color.setHex(shade(i,s)));const set=new Set(s.edges.map(([a,b])=>[a,b].join(':')));links.forEach(({a,b,m})=>m.visible=set.has([a,b].join(':')));ringLines.forEach(({j,m})=>m.visible=s.edges.some(([a,b])=>a===0&&b===j));};}
};
