import {L,metric,control,toggle,chapter} from './common.js';
export function shortestPath(edges,start=0,end=4){const d=Array(5).fill(Infinity),previous=[];d[start]=0;const pending=new Set([0,1,2,3,4]);while(pending.size){const u=[...pending].sort((a,b)=>d[a]-d[b])[0];pending.delete(u);for(const [a,b,w]of edges){const v=a===u?b:b===u?a:null;if(v===null)continue;if(d[u]+w<d[v]){d[v]=d[u]+w;previous[v]=u;}}}const path=[];if(Number.isFinite(d[end]))for(let u=end;u!==undefined;u=previous[u])path.unshift(u);return {path,delay:d[end]};}
export const internet={id:'internet',room:'mind',title:L('Internet: el viaje de un mensaje','Internet: a message in motion'),color:'#72d7ef',unit:L('instante','instant'),horizon:30,
 intro:L('Acompaña un mensaje desde el portátil hasta el servidor. Cambia la red y observa qué llega y qué debe repetirse.','Follow a message from a laptop to a server. Change the network and see what arrives and what must be repeated.'),
 controls:[control('size',L('Mensaje · kB','Message · kB'),12,3,30),toggle('cut',L('Cortar el enlace directo','Cut the direct link')),toggle('loss',L('Perder el primer paquete','Lose the first packet'))],
 challenge:L('Corta el enlace y compara la ruta. Después pierde un paquete: ¿llegan los bytes finales completos?','Cut the link and compare routes. Then lose a packet: are the final bytes complete?'),
 limitations:L('Ejemplo HTTP sobre TCP. Se omiten el cifrado TLS, el control de congestión y muchos saltos. El camino mínimo representa una política local ilustrativa; Internet no calcula un óptimo global. Los tiempos son inventados.','Example HTTP over TCP. TLS encryption, congestion control and many hops are omitted. The shortest path represents an illustrative local policy; the Internet does not compute a global optimum. Timings are invented.'),
 sources:[['IETF · TCP','https://www.rfc-editor.org/rfc/rfc9293.html'],['IETF · DNS','https://www.rfc-editor.org/rfc/rfc1034.html']],
 steps:[chapter(L('1 · Escribes una dirección','1 · You type an address'),L('Tu navegador necesita localizar un servicio y comunicarse con él. El equipo entrega datos a su red local. El router permite continuar hacia otras redes; una antena Wi-Fi no contiene Internet. Aquí el mensaje de ejemplo se divide en piezas numeradas.','Your browser needs to locate a service and communicate with it. The computer sends data to its local network. A router provides a path to other networks; a Wi-Fi antenna does not contain the Internet. Here the example message is divided into numbered pieces.')),
 chapter(L('2 · Un nombre encuentra una dirección','2 · A name finds an address'),L('DNS relaciona nombres con registros, entre ellos direcciones IP. Un resolvedor puede utilizar su caché o consultar otros servidores. Esta consulta es distinta de descargar la página. El armario DNS representa ese servicio distribuido, no una única máquina central.','DNS maps names to records, including IP addresses. A resolver can use cached information or query other servers. This lookup is separate from downloading the page. The DNS cabinet represents this distributed service, not a single central machine.')),
 chapter(L('3 · La red elige por dónde continuar','3 · The network forwards the data'),L('Cada router reenvía según su información de encaminamiento. Corta el enlace directo y observa el desvío por la ruta alternativa. El dibujo comprime distancias y equipos: los datos viajan mediante señales físicas y el cambio de ruta real puede tardar.','Each router forwards according to its routing information. Cut the direct link and watch the alternate route. The diagram compresses distances and equipment: data travels as physical signals, and real routing changes can take time.')),
 chapter(L('4 · Ordenar, confirmar y responder','4 · Order, acknowledge and respond'),L('TCP ofrece un flujo ordenado de bytes. Si faltan datos, puede retransmitirlos; recibir un duplicado no duplica el mensaje. El servidor procesa la petición y devuelve datos. La barra cuenta piezas únicas recibidas, mientras que los intentos incluyen la repetición del paquete perdido.','TCP provides an ordered byte stream. Missing data can be retransmitted; a duplicate does not duplicate the message. The server processes the request and returns data. The bar counts unique pieces received, while attempts include retransmitting the lost packet.'))],
 evaluate(p,t){const edges=[[0,1,4],[1,2,7],[2,4,6],[1,3,12],[3,4,14]].filter(([a,b])=>!(p.cut&&a===1&&b===2));const route=shortestPath(edges),packets=Math.ceil(p.size/1.5),delay=route.delay,received=Math.min(packets,Math.max(0,Math.floor((t*8-delay)/3)+1))-(p.loss&&t*8>=delay&&t*8<delay+20?1:0),unique=Math.max(0,received),attempts=Math.min(packets,Math.max(0,Math.floor(t*8/3)+1))+(p.loss&&t*8>=20?1:0);const history=Array.from({length:t+1},(_,i)=>Math.max(0,Math.min(packets,Math.max(0,Math.floor((i*8-delay)/3)+1))-(p.loss&&i*8>=delay&&i*8<delay+20?1:0)));
 return {delay,route:route.path,cut:p.cut,unique,packets,attempts,metrics:[metric(L('Ruta · un sentido','Route · one way'),delay,'ms'),metric(L('Piezas recibidas','Received pieces'),`${unique} / ${packets}`),metric(L('Intentos de envío','Send attempts'),attempts)],series:[{label:L('Piezas únicas','Unique pieces'),values:history}]};},
 build(k){const laptop=k.group(0);k.box(laptop,[0,.65,0],[3,.2,2],0x9eafbc,'Laptop');k.box(laptop,[0,1.75,-.8],[3,2,.15],0x26384b,'Browser');k.label(laptop,'atlas.example',0,1.8,-.68,2.5);const router=k.group(0);k.box(router,[-2,.5,-3],[1.5,.6,1],0xaac5d2,'Router');[-2.5,-1.5].forEach(x=>k.cylinder(router,[x,1.4,-3],.05,1.4,0xaac5d2));
 const dns=k.group(1);k.box(dns,[0,1.6,0],[2.5,3.2,1.5],0x324b68,'DNS resolver');for(let i=0;i<5;i++)k.box(dns,[0,.5+i*.5,.81],[2,.18,.08],0x7fe6d1);k.label(dns,'DNS → IP',0,3.6,0,3);
 const net=k.group(2),coords=[[-3,1,3],[-2,2,0],[0,2,-3],[2,1,0],[3,2,-4]],nodes=coords.map((p,i)=>k.sphere(net,p,.5,0x71c6df,`Router ${i}`)),links=[];[[0,1],[1,2],[2,4],[1,3],[3,4]].forEach(([a,b])=>links.push({a,b,mesh:k.tube(net,[coords[a],coords[b]],.045,0x476685)}));const pulse=k.pulse(net,coords,0xffd786);
 const server=k.group(3);for(let j=0;j<3;j++){k.box(server,[-2+j*2,1.7,0],[1.6,3.4,1.5],0x2a3e53,'Server');for(let i=0;i<7;i++)k.box(server,[-2+j*2,.4+i*.42,.8],[1.3,.08,.05],0x68ddc6);}const bar=k.box(server,[0,4,0],[5,.2,.3],0x71e5bb);k.label(server,'TCP · ACK',0,4.6,0,3);
 return (s,time)=>{links.forEach(l=>{const used=s.route.some((v,i)=>v===l.a&&s.route[i+1]===l.b);l.mesh.visible=!(s.cut&&l.a===1&&l.b===2);l.mesh.material.color.set(used?0xf8d38a:0x476685);});pulse(s.route.map(i=>coords[i]),time*.3);bar.scale.x=Math.max(.005,s.unique/s.packets);nodes.forEach(n=>n.rotation.y=time*.2);};}
};
