import {L,toggle,metric,chapter,clamp} from './common.js';
import {buildChipTrace,sampleChip} from './microchip-model.js';
export {fullAdder} from './microchip-model.js';
let cachedKey,cachedTrace;
export function microchipExperiment(p){const key=[+p.a,+p.b,+p.carry].join(':');if(key!==cachedKey){cachedTrace=buildChipTrace(p);cachedKey=key;}return cachedTrace;}
export function microchipPose(i){const focus=[[-12,2.2,0],[-4.5,2.6,0],[6.1,2.7,0],[13,2.8,0]][i],x=[-12,-4.5,5.2,13][i],z=9;return {x,z,yaw:Math.atan2(x-focus[0],z-focus[2]),pitch:Math.atan2(focus[1]-1.65,Math.hypot(x-focus[0],z-focus[2]))};}
export const microchip={id:'microchip',room:'mind',title:L('Dentro de un microchip','Inside a microchip'),color:'#c0a2ff',unit:L('paso','step'),horizon:12,continuous:true,
 poseAt:microchipPose,walk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.5*Math.min(.05,dt);let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-18,18),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-9,14);if(Math.abs(x)<16.5&&Math.abs(p.z)<3.4)x=p.x;if(Math.abs(x)<16.5&&Math.abs(z)<3.4)z=p.z;return {...p,x,z};},
 overview:{yaw:.06,pitch:.28,distance:9.5},fitLabel:L('Ver el circuito completo','Fit the whole circuit'),
 narrationTime(p,i,u){u=clamp(u,0,1);return i<2?0:12*clamp((u-(i===2?.35:.12))/(i===2?.6:.68),0,1);},
 challenge:L('Construye una suma con interruptores','Build an addition from switches'),controls:[toggle('a',L('Bit A','Bit A'),true),toggle('b',L('Bit B','Bit B'),true),toggle('carry',L('Acarreo de entrada','Carry in'),false)],
 steps:[chapter(L('1 · Un campo abre un canal','1 · A field opens a channel'),L('La puerta de un transistor MOS controla, mediante un campo eléctrico, un canal entre fuente y drenador. La capa aislante separa la puerta del semiconductor. Este corte ampliado es esquemático: los chips modernos también utilizan geometrías tridimensionales. Una señal lógica es un rango de tensión, no una bolita física.','A MOS transistor gate uses an electric field to control a channel between source and drain. An insulating layer separates the gate from the semiconductor. This enlarged cross-section is schematic: modern chips also use three-dimensional geometries. A logic signal is a voltage range, not a physical bead.')),
 chapter(L('2 · Dos transistores invierten un bit','2 · Two transistors invert a bit'),L('Un inversor CMOS combina un transistor de tipo p y otro de tipo n. Idealmente, una entrada baja activa el camino hacia la alimentación; una entrada alta activa el camino hacia tierra. Así, la salida es lo contrario de la entrada. Cambia A para ver ambos caminos.','A CMOS inverter combines a p-type and an n-type transistor. Ideally, a low input enables the path to the supply; a high input enables the path to ground. The output therefore reverses the input. Change A to see both paths.')),
 chapter(L('3 · Combinar puertas lógicas','3 · Combining logic gates'),L('Una puerta XOR produce uno cuando sus dos entradas son diferentes. AND necesita ambas entradas a uno; OR necesita al menos una. Conecta estas operaciones para formar un sumador completo. Los pulsos de color indican qué señales usamos; su velocidad es una ayuda visual, no un tiempo electrónico real.','An XOR gate produces one when its inputs differ. AND needs both inputs to be one; OR needs at least one. Connect these operations to build a full adder. Coloured pulses show the signals being used; their speed is a visual aid, not a real electronic timing.')),
 chapter(L('4 · Suma y acarreo','4 · Sum and carry'),L('Un sumador completo recibe A, B y un acarreo previo. Devuelve un bit de suma y un nuevo acarreo. Uno más uno da diez en binario: suma cero y acarreo uno. Prueba las ocho combinaciones de entrada. Los procesadores encadenan circuitos de este tipo y añaden registros, memoria y control.','A full adder receives A, B and a previous carry. It returns a sum bit and a new carry. One plus one is binary ten: sum zero and carry one. Try all eight input combinations. Processors connect circuits of this kind and add registers, memory and control.'))],
 limitations:L('Maqueta ampliada: corte de un NMOS planar y esquema CMOS ideal, no un diseño de fabricación. El canal se forma bajo el aislante; la puerta actúa mediante un campo, no conduciendo a través del óxido. Un canal abierto requiere diferencia de potencial entre fuente y drenador para que circule corriente. El inversor y el sumador son demostraciones separadas: comparten A, pero NOT A no entra en el sumador. Las cinco puertas lógicas contienen varios transistores; sus formas son símbolos funcionales extruidos, no su layout. Azul = 0 y verde = 1, rangos de tensión válidos. Gris o puntos suspensivos significan aún no evaluado/mostrado en esta secuencia, no alta impedancia ni un estado analógico indefinido. Los marcadores y los 12 pasos muestran dependencias pedagógicas, no electrones, un reloj ni retardos reales. Retroceder la animación no implica lógica físicamente reversible. Se omiten voltajes analógicos, capacitancias, consumo, fugas y diseño físico. Cambiar entradas reinicia el recorrido. La guía presenta las dos demostraciones y luego recorre dos veces el mismo sumador.','Enlarged teaching model: a planar NMOS cross-section and ideal CMOS schematic, not a fabrication design. The channel forms beneath the insulator; the gate acts through an electric field, not conduction through the oxide. An open channel requires a source–drain potential difference for current to flow. The inverter and adder are separate demonstrations: they share A, but NOT A never enters the adder. The five logic gates each contain multiple transistors; their shapes are extruded functional symbols, not their layout. Blue = 0 and green = 1, valid voltage ranges. Grey or ellipses mean not yet evaluated/shown in this sequence, not high impedance or an undefined analogue state. Markers and 12 steps show teaching dependencies, not electrons, a clock or real delays. Rewinding the animation does not imply physically reversible logic. Analogue voltages, capacitances, power, leakage and physical layout are omitted. Changing inputs restarts the sequence. The guide presents the two demonstrations, then traverses the same adder twice.'),
 sources:[['MIT 6.004 · MOSFET and CMOS','https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/pages/c3/c3s1/'],['MIT 6.004 · Adders and circuit design','https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/pages/c8/c8s1/'],['UT Austin · Digital logic and full-adder table','https://users.ece.utexas.edu/~valvano/Volume1/E-Book/C4_DigitalLogic.htm'],['Intel · The transistor explained','https://www.intel.com/content/www/us/en/newsroom/tech101/the-transistor-explained.html']],
 evaluate(p,t){const trace=microchipExperiment(p),s=sampleChip(trace,t),display=v=>v===null?'…':String(v);return {...s,trace,a:s.inputs.a,b:s.inputs.b,c:s.inputs.cin,t:s.time,xor:s.nodes.xor1,sum:s.result.sum,carry:s.result.cout,
 metrics:[metric(L('Entradas A + B + Cin','Inputs A + B + Cin'),`${s.inputs.a} + ${s.inputs.b} + ${s.inputs.cin}`),metric(L('X = A XOR B','X = A XOR B'),display(s.nodes.xor1)),metric(L('Indicadores Cout · Sum','Indicators Cout · Sum'),`${display(s.result.cout)} · ${display(s.result.sum)}`),metric(L('Decimal esperado','Expected decimal'),s.expected.decimal)],
 series:[{label:L('X interno','Internal X'),values:trace.states.map(v=>v.nodes.xor1)},{label:L('Sum interno','Internal Sum'),values:trace.states.map(v=>v.nodes.xor2)},{label:L('Cout interno','Internal Cout'),values:trace.states.map(v=>v.nodes.or)}]};},
 // One connected laboratory is implemented in microchip-world.js.
 build(){return ()=>{};}
};
