import * as THREE from '../vendor/three.module.js';
import {sampleNuclear} from './nuclear-model.js';

export const NUCLEAR_FOCUS=[[-6.5,2.5,0],[-2.2,2.6,0],[4.4,2.0,0],[-6.5,2.5,0]];
export const nuclearOverview={yaw:.06,pitch:.30,distance:9.5};
export const NUCLEAR_BOUNDS=[[-12.15,.25,-1.7,-4.3,5.75,2.55],[-3.8,.15,-1.9,-.55,5.05,1.75],[.9,.25,-1.65,8.95,4.25,2.7],[-8.8,.25,-1.7,-4.4,5.65,2.6],[-8.0,.05,-4.45,9.1,5.7,2.8]];
export function nuclearPoseAt(i){const x=[-7,-2.2,4.4,-10.5][i],z=8.3,[tx,ty,tz]=NUCLEAR_FOCUS[i];return {x,z,yaw:Math.atan2(x-tx,z-tz),pitch:Math.atan2(ty-1.65,Math.hypot(x-tx,z-tz))};}
export function nuclearWalk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),d=3.8*Math.min(.05,dt),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*d,-13,12),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*d,-8,12);const inside=(px,pz)=>px>-9&&px<9&&pz>-4&&pz<2.8;if(inside(x,p.z))x=p.x;if(inside(x,z))z=p.z;return {...p,x,z};}
const C={primary:0xef997f,secondary:0xf2d18a,cooling:0x89cae6,electric:0x91dfba,steel:0xa5b8c2,fission:0xf5ad82,decay:0xdda5ce};
const V=p=>p instanceof THREE.Vector3?p.clone():new THREE.Vector3(...p),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));

export function createNuclearScene(lesson,es=true){
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x1b3040);scene.fog=new THREE.Fog(0x1b3040,45,110);
 const resources=[],targets=[],stands=[],own=x=>(resources.push(x),x),t=(a,b)=>es?a:b,mat=(color,extra={})=>own(new THREE.MeshStandardMaterial({color,roughness:.48,metalness:.18,...extra}));
 scene.add(new THREE.HemisphereLight(0xe2efff,0x394855,2.6));const sun=new THREE.DirectionalLight(0xffe5c6,3);sun.position.set(-9,15,11);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-15,right:15,top:12,bottom:-12,near:.1,far:45});sun.shadow.normalBias=.05;scene.add(sun);own(sun.shadow);
 function mesh(group,geometry,material,p=[0,0,0]){const m=new THREE.Mesh(geometry,material);m.position.copy(V(p));m.castShadow=true;m.receiveShadow=true;group.add(m);return m;}
 function box(group,p,size,color,extra){return mesh(group,own(new THREE.BoxGeometry(...size)),mat(color,extra),p);}
 function ball(group,p,r,color,extra){return mesh(group,own(new THREE.SphereGeometry(r,18,12)),mat(color,extra),p);}
 function cylinder(group,p,r,h,color,extra){return mesh(group,own(new THREE.CylinderGeometry(r,r,h,24)),mat(color,extra),p);}
 function rod(group,a,b,r,color,extra={}){const p=V(a),q=V(b),m=cylinder(group,p.clone().add(q).multiplyScalar(.5),r,p.distanceTo(q),color,extra);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());return m;}
 function curve(points,closed=false){return new THREE.CatmullRomCurve3(points.map(V),closed,'centripetal');}
 function tube(group,path,r,color,extra={},segments=80){const c=path instanceof THREE.Curve?path:curve(path),m=mesh(group,own(new THREE.TubeGeometry(c,segments,r,8,false)),mat(color,extra));return {mesh:m,curve:c};}
 function inspect(object,a,b){object.userData.info=[a,b];targets.push(object);return object;}
 // Captions use measured text and immutable image dimensions on the GPU.
 // Their vocabulary is finite; changing continuous power is represented by geometry/HUD.
 function label(group,words,p,width=3,{height=80,bg=true,depthTest=false,textSize=null}={}){const material=own(new THREE.SpriteMaterial({transparent:true,depthWrite:false,depthTest})),m=new THREE.Sprite(material),cache=new Map();m.position.copy(V(p));group.add(m);if(!depthTest)m.renderOrder=10;let last;
  function set(value){const words=String(value);if(words===last)return;last=words;let entry=cache.get(words);if(!entry){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),lines=words.split('\n');ctx.font='600 60px system-ui';canvas.width=Math.max(96,Math.min(2048,Math.ceil(Math.max(...lines.map(line=>ctx.measureText(line).width))+48)));canvas.height=height;if(bg){ctx.fillStyle='#183542ed';ctx.fillRect(0,0,canvas.width,height);}ctx.fillStyle='#f5f8f8';ctx.font='600 60px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,height*(i+.5)/lines.length,canvas.width-36));const texture=own(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;entry={texture,height:width*height/canvas.width,pixelWidth:canvas.width};cache.set(words,entry);}material.map=entry.texture;material.needsUpdate=true;m.scale.set(textSize?entry.pixelWidth*textSize/60:width,textSize?height*textSize/60:entry.height,1);}set(words);return {m,set};}
 const annotations=new THREE.Group();scene.add(annotations);const zoneAnnotations=Array.from({length:4},()=>{const g=new THREE.Group();annotations.add(g);return g;});
 const floor=box(scene,[-1,-.16,1],[27,.30,21],0x3b5360),platform=box(scene,[-.7,.08,-.6],[19.7,.16,8],0x54747b);for(let x=-12;x<=11;x+=2)box(scene,[x,.015,6.5],[.9,.02,.08],0xd7d8b7);for(let z=-8;z<=10;z+=2)box(scene,[-1,.012,z],[26,.01,.012],0x5d727d);

 // A rear half-vessel is a genuine cutaway; fuel and insertion remain visible.
 const reactorGroup=new THREE.Group();reactorGroup.position.set(-6.5,0,-.4);scene.add(reactorGroup);const vessel=mesh(reactorGroup,own(new THREE.CylinderGeometry(1.15,1.15,3.7,48,1,true,Math.PI/2,Math.PI)),mat(0x9db3c3,{side:THREE.DoubleSide}),[0,2.4,0]);const base=cylinder(reactorGroup,[0,.47,0],1.18,.22,0x637e91),vesselRims=[];for(const y of [.55,4.25]){const ring=mesh(reactorGroup,own(new THREE.TorusGeometry(1.15,.055,8,48,Math.PI)),mat(0xb5c3c8),[0,y,0]);ring.rotation.x=Math.PI/2;vesselRims.push(ring);}const fuel=[],controlRods=[],decayMarkers=[];
 for(let i=0;i<9;i++){const x=(i%3-1)*.43,z=(Math.floor(i/3)-1)*.43;const m=cylinder(reactorGroup,[x,2.05,z],.105,2.55,C.fission,{emissive:C.fission,emissiveIntensity:.25});fuel.push(m);for(const y of [1.20,2.0,2.85])decayMarkers.push(ball(reactorGroup,[x+.12,y,z+.05],.045,C.decay,{emissive:C.decay,emissiveIntensity:.14}));if(i%2===0){const r=cylinder(reactorGroup,[x+.17,3.65,z],.045,2.4,0x607487);r.userData.withdrawnY=3.65;r.userData.insertedY=2.05;controlRods.push(r);}}
 const drive=box(reactorGroup,[0,4.55,-.5],[1.4,.15,.48],0x718b9c),reactorPorts={hot:V([-6.5,3.75,-.4]),cold:V([-6.5,.68,-.4])},reactor={group:reactorGroup,vessel,base,rims:vesselRims,fuel,controlRods,drive,ports:reactorPorts,rodPositions:{withdrawn:3.65,inserted:2.05}};inspect(vessel,'Vasija PWR abierta: agua primaria y combustible. Las barras absorben neutrones; la inserción instantánea en el paso 5 es una instrucción didáctica, no una cinética real.','Open PWR vessel: primary water and fuel. Rods absorb neutrons; instantaneous insertion at teaching step 5 is an instruction, not real kinetics.');fuel.forEach(m=>inspect(m,'Combustible esquemático: la fisión produce calor y crea productos radiactivos que ya liberan calor durante el funcionamiento. Los puntos rosados distinguen ese decaimiento.','Schematic fuel: fission produces heat and radioactive products that already release heat during operation. Pink points distinguish their decay.'));controlRods.forEach(m=>inspect(m,'Barras absorbentes: regulan la reacción en cadena. No calculamos reactividad ni tiempos físicos de inserción.','Absorbing rods: regulate the chain reaction. Reactivity and physical insertion times are not calculated.'));
 const pressurizerGroup=new THREE.Group();pressurizerGroup.position.set(-4.65,0,-2.15);scene.add(pressurizerGroup);const pressurizerVessel=cylinder(pressurizerGroup,[0,2.65,0],.35,1.65,0x90a5b4);ball(pressurizerGroup,[0,3.47,0],.35,0x90a5b4);const pressurePipe=tube(scene,[[-4.65,1.82,-2.15],[-4.65,1.45,-2.15],[-4.5,1.45,-.4],[-4.5,3.75,-.4]],.065,C.primary);const pressurizer={group:pressurizerGroup,vessel:pressurizerVessel,connection:pressurePipe};inspect(pressurizerVessel,'Presurizador conectado al primario: contribuye a mantener el agua líquida en operación normal. Aquí no se calculan presión ni temperaturas.','Pressurizer connected to the primary loop: helps keep water liquid in normal operation. Pressure and temperature are not calculated here.');

 // The primary U-tube is surrounded by secondary fluid; a separate metal wall transfers heat.
 const sgGroup=new THREE.Group();sgGroup.position.set(-2.2,0,-.4);scene.add(sgGroup);const secondaryShell=mesh(sgGroup,own(new THREE.CylinderGeometry(.88,.88,3.5,48,1,true,Math.PI/2,Math.PI)),mat(0xacb9c1,{side:THREE.DoubleSide}),[0,2.30,0]),secondaryFluid=mesh(sgGroup,own(new THREE.CylinderGeometry(.76,.76,2.8,32,1,true,Math.PI/2,Math.PI)),mat(C.secondary,{transparent:true,opacity:.15,depthWrite:false,side:THREE.DoubleSide}),[0,2.05,0]);secondaryFluid.castShadow=false;const sgPorts={primaryIn:V([-2.64,2.75,-.4]),primaryOut:V([-1.76,2.75,-.4]),steam:V([-2.2,4.05,-.4]),feed:V([-2.2,.95,.40])},uPoints=[sgPorts.primaryIn,[-2.64,1.25,-.4],[-2.2,.99,-.4],[-1.76,1.25,-.4],sgPorts.primaryOut],uCurve=curve(uPoints),primaryTube=tube(scene,uCurve,.075,C.primary),transferWall=tube(scene,uCurve,.103,C.steel,{transparent:true,opacity:.40,depthWrite:false}),sgTransfer=[];
 for(const y of [1.40,1.95,2.50])sgTransfer.push(rod(scene,[-2.54,y,-.25],[-2.15,y,.18],.025,0xffe3ab,{emissive:0xffd48f,emissiveIntensity:.6}));const steamGenerator={group:sgGroup,secondaryShell,secondaryFluid,primaryTube,transferWall,ports:sgPorts,transfer:sgTransfer};inspect(primaryTube.mesh,'Tubo primario en U dentro del generador de vapor: sigue cerrado. La energía cruza su pared metálica hacia el secundario; ambas aguas permanecen separadas.','Primary U-tube inside the steam generator: it remains closed. Energy crosses its metal wall to the secondary side; the two waters remain separate.');inspect(transferWall.mesh,'Pared de intercambio térmico: transmite energía y separa los fluidos. Las varillas luminosas son marcadores de energía, no conductos de agua.','Heat-transfer wall: transmits energy while separating fluids. Glowing rods are energy markers, not water pipes.');
 function pump(position,color,name){const g=new THREE.Group();g.position.copy(V(position));scene.add(g);const housing=ball(g,[0,0,0],.23,0x7192a3),rotor=new THREE.Group();g.add(rotor);const impeller=cylinder(rotor,[0,0,0],.16,.10,color);impeller.rotation.x=Math.PI/2;for(let i=0;i<4;i++){const a=i*Math.PI/2,b=box(rotor,[Math.cos(a)*.12,Math.sin(a)*.12,.07],[.16,.055,.06],color);b.rotation.z=a;}const motor=cylinder(g,[0,.38,0],.17,.42,0xa8bbc5);inspect(housing,name[0],name[1]);return {group:g,housing,rotor,motor,angle:0};}
 const primaryPump=pump([-4.1,.88,1.25],C.primary,['Bomba de circulación primaria idealizada. Sigue refrigerando tras la parada mientras queda calor.','Idealised primary circulation pump. It continues cooling after shutdown while heat remains.']),feedPump=pump([.2,.70,1.20],C.secondary,['Bomba de alimentación: devuelve condensado al generador de vapor. En la parada ilustrativa sigue con el bypass disponible.','Feedwater pump: returns condensate to the steam generator. In the illustrated shutdown it continues with the bypass available.']);

 // Steam acts on a rotor; its shaft is physically coaxial with the generator.
 const turbineGroup=new THREE.Group();turbineGroup.position.set(3.2,2.2,-.4);scene.add(turbineGroup);const turbineCasing=mesh(turbineGroup,own(new THREE.CylinderGeometry(.72,.72,2.4,40,1,true,Math.PI/2,Math.PI)),mat(0xa2b5c1,{side:THREE.DoubleSide}),[0,0,0]);turbineCasing.rotation.z=Math.PI/2;const turbineRotor=new THREE.Group();turbineGroup.add(turbineRotor);const shaft=rod(turbineGroup,[-1.32,0,0],[3.3,0,0],.085,0xd1c6ae,{metalness:.75,roughness:.25});const blades=[];for(let row=0;row<5;row++)for(let i=0;i<10;i++){const a=i*Math.PI/5,m=box(turbineRotor,[-.9+row*.44,Math.cos(a)*.40,Math.sin(a)*.40],[.055,.37,.075],0xc9d4d9,{metalness:.6});m.rotation.x=a;blades.push(m);}box(scene,[3.2,.68,-.4],[2.8,.38,1.50],0x6b8898);const turbine={group:turbineGroup,casing:turbineCasing,rotor:turbineRotor,shaft,blades,angle:0};inspect(turbineCasing,'Turbina seccionada: el vapor mueve álabes y eje. En el bypass tras la parada no enviamos vapor por esta rama; su rotación se congela, sin simular inercia mecánica.','Cutaway turbine: steam drives blades and shaft. Shutdown bypass sends no steam through this branch; rotation freezes without modelling mechanical inertia.');
 const generatorGroup=new THREE.Group();generatorGroup.position.set(5.75,2.2,-.4);scene.add(generatorGroup);const generatorStator=mesh(generatorGroup,own(new THREE.CylinderGeometry(.66,.66,1.35,36,1,true,Math.PI/2,Math.PI)),mat(0x83a5a7,{side:THREE.DoubleSide}),[0,0,0]);generatorStator.rotation.z=Math.PI/2;const generatorRotor=new THREE.Group();generatorGroup.add(generatorRotor);const magnet=cylinder(generatorRotor,[0,0,0],.34,1.15,0xc2aa88,{metalness:.55});magnet.rotation.z=Math.PI/2;box(generatorRotor,[0,.28,0],[.98,.17,.30],0x82a5c8);box(generatorRotor,[0,-.28,0],[.98,.17,.30],0xd39f8d);const coils=[];for(let i=0;i<8;i++){const a=i*Math.PI/4,m=box(generatorGroup,[0,Math.cos(a)*.52,Math.sin(a)*.52],[1.18,.14,.14],0xd3ae86,{metalness:.65});m.rotation.x=a;coils.push(m);}box(scene,[5.75,.85,-.4],[1.65,.30,1.45],0x6b8898);const generator={group:generatorGroup,stator:generatorStator,rotor:generatorRotor,magnet,coils,shaft,angle:0};inspect(generatorStator,'Generador conectado al mismo eje de la turbina: movimiento mecánico hacia electricidad. El campo y las bobinas son representativos; no resolvemos inducción ni corriente.','Generator on the turbine shaft: mechanical motion to electricity. Field and coils are representative; induction and current are not solved.');

 // Cooling water is inside a tube; secondary steam/condensate surrounds it.
 const condenserGroup=new THREE.Group();condenserGroup.position.set(3.2,.9,-.4);scene.add(condenserGroup);const condenserShell=mesh(condenserGroup,own(new THREE.CylinderGeometry(.46,.46,2.4,36,1,true,Math.PI/2,Math.PI)),mat(0x9caeb9,{side:THREE.DoubleSide}));condenserShell.rotation.z=Math.PI/2;const condenserPorts={steam:V([3.2,1.15,.0]),feed:V([2.4,.65,.05]),coolingIn:V([2,.9,-.72]),coolingOut:V([4.4,.9,-.72])},coolingCurve=curve([condenserPorts.coolingIn,[2.6,.9,-.72],[3.8,.9,-.72],condenserPorts.coolingOut]),coolingTube=tube(scene,coolingCurve,.055,C.cooling,{},40),condenserWall=tube(scene,coolingCurve,.088,C.steel,{transparent:true,opacity:.42,depthWrite:false},40),condenser={group:condenserGroup,secondaryShell:condenserShell,coolingTube,transferWall:condenserWall,ports:condenserPorts};inspect(condenserShell,'Condensador: el vapor secundario devuelve calor a través de tubos de refrigeración separados y recuperamos agua. El bypass también llega aquí; nunca mezclamos esas aguas.','Condenser: secondary steam transfers heat across separate cooling tubes and becomes water again. The bypass also reaches here; these waters never mix.');
 const hxGroup=new THREE.Group();hxGroup.position.set(7.6,.6,-3.0);scene.add(hxGroup);const water=box(hxGroup,[0,.15,0],[2.2,.60,2.3],0x75a7b5,{transparent:true,opacity:.30,depthWrite:false}),rim=box(hxGroup,[0,-.13,0],[2.4,.18,2.5],0x557789),hxPoints=[[7.6,.9,-2.2],[7.6,.9,-2.7],[7.1,.9,-2.8],[7.1,.9,-3.4],[8.1,.9,-3.4],[8.1,.9,-2.8],[7.6,.9,-3.6]],hxTube=tube(scene,hxPoints,.09,C.cooling);const heatExchanger={group:hxGroup,water,rim,tube:hxTube,ports:{inlet:V(hxPoints[0]),outlet:V(hxPoints.at(-1))}};inspect(water,'Sumidero térmico disponible, representado como intercambiador con agua exterior. Su disponibilidad se supone: no calculamos capacidad, temperatura ni requisitos de seguridad.','Available heat sink, represented by an exchanger with outside water. Availability is assumed; capacity, temperature and safety requirements are not calculated.');

 function flowRoute(id,points,color,{closed=false,draw=true,path=null}={}){const c=path||curve(points,closed),pipe=draw?tube(scene,c,.070,color,{},Math.max(60,points.length*10)).mesh:null,packets=[],packetGeometry=own(new THREE.SphereGeometry(.072,10,7)),packetMaterial=mat(color,{emissive:color,emissiveIntensity:.60});for(let i=0;i<12;i++)packets.push(mesh(scene,packetGeometry,packetMaterial));return {id,color,points:points.map(V),curve:c,segments:c.curves||[c],pipe,packets,closed,flow:0,energy:0,progress:0};}
 const primaryHotPoints=[reactorPorts.hot,[-4.5,3.75,-.4],[-3.3,3.75,-.4],sgPorts.primaryIn],primaryReturnPoints=[sgPorts.primaryOut,[-.9,2.75,1.25],[-.9,.88,1.25],[-4.1,.88,1.25],[-6.5,.88,1.25],reactorPorts.cold],primaryPath=new THREE.CurvePath();primaryPath.add(curve(primaryHotPoints));primaryPath.add(uCurve);primaryPath.add(curve(primaryReturnPoints));const coreChannel=new THREE.CurvePath();coreChannel.add(new THREE.LineCurve3(reactorPorts.cold,V([-6.285,.68,-.185])));coreChannel.add(new THREE.LineCurve3(V([-6.285,.68,-.185]),V([-6.285,3.53,-.185])));coreChannel.add(new THREE.LineCurve3(V([-6.285,3.53,-.185]),reactorPorts.hot));primaryPath.add(coreChannel);reactor.coolantChannel=coreChannel;const primaryPoints=[...primaryHotPoints,...uPoints.slice(1),...primaryReturnPoints.slice(1)],primary=flowRoute('primary',primaryPoints,C.primary,{closed:true,path:primaryPath});
 const steamFork=V([-.6,4.55,-.4]),commonOutPoints=[sgPorts.steam,[-2.2,4.55,-.4],steamFork],normalSteamPoints=[steamFork,[1.7,4.55,-.4],[1.7,2.3,-.4],[1.95,2.2,-.4],[4.3,2.2,-.4],[4.3,1.35,.0],condenserPorts.steam],bypassSteamPoints=[steamFork,[0,4.55,1.10],[0,1.25,1.10],[3.2,1.25,1.10],condenserPorts.steam],returnPoints=[condenserPorts.steam,condenserPorts.feed,[2.4,.70,1.20],[.2,.70,1.20],[-1.25,.70,1.20],sgPorts.feed,[-2.2,1.75,.40],[-2.2,3.50,.40],sgPorts.steam];
 const secondaryOut=flowRoute('secondary-out',commonOutPoints,C.secondary),normalSteam=flowRoute('secondary-turbine',normalSteamPoints,C.secondary),bypassSteam=flowRoute('secondary-bypass',bypassSteamPoints,C.secondary),commonReturn=flowRoute('secondary-return',returnPoints,C.secondary),normal=flowRoute('secondary-normal-loop',[...commonOutPoints,...normalSteamPoints.slice(1),...returnPoints.slice(1,-1)],C.secondary,{closed:true,draw:false}),bypass=flowRoute('secondary-bypass-loop',[...commonOutPoints,...bypassSteamPoints.slice(1),...returnPoints.slice(1,-1)],C.secondary,{closed:true,draw:false});normal.packets.forEach(m=>m.visible=false);bypass.packets.forEach(m=>m.visible=false);
 const normalValve=box(scene,[1.70,2.83,-.4],[.32,.16,.28],C.secondary),bypassValve=box(scene,[0,3.30,1.10],[.32,.16,.28],0x727e88);const secondary={id:'secondary',color:C.secondary,closed:true,normal,bypass,commonOut:secondaryOut,commonReturn,branches:{normalSteam,bypassSteam},valves:{normal:normalValve,bypass:bypassValve},flow:0,energy:0};inspect(bypassValve,'Bypass de turbina: en este caso didáctico conduce el vapor al condensador tras la parada, suponiendo refrigeración y alimentación disponibles. No representa una secuencia operativa ni todos los sistemas de eliminación de calor.','Turbine bypass: this teaching case routes steam to the condenser after shutdown, assuming cooling and feedwater remain available. It represents neither an operating sequence nor all heat-removal systems.');
 const coolingHotPoints=[condenserPorts.coolingOut,[6.1,.9,-.72],heatExchanger.ports.inlet],coolingReturnPoints=[heatExchanger.ports.outlet,[6.0,.9,-4.2],[1.25,.9,-4.2],[1.25,.9,-1.6],condenserPorts.coolingIn],coolingPath=new THREE.CurvePath();coolingPath.add(curve(coolingHotPoints));coolingPath.add(hxTube.curve);coolingPath.add(curve(coolingReturnPoints));coolingPath.add(coolingCurve);const coolingPoints=[...coolingHotPoints,...hxPoints.slice(1),...coolingReturnPoints.slice(1),[2.6,.9,-.72],[3.8,.9,-.72]],cooling=flowRoute('cooling',coolingPoints,C.cooling,{closed:true,path:coolingPath}),coolingPump=pump([1.25,.9,-1.6],C.cooling,['Bomba del circuito de refrigeración separado. Sigue evacuando calor tras la parada en este caso con sumidero disponible.','Separate cooling-loop pump. It continues removing heat after shutdown in this available-heat-sink case.']);const circuits={primary,secondary,cooling};
 const electricity=flowRoute('electricity',[[6.4,2.20,-.4],[7.3,2.20,-.4],[7.3,1.4,.60],[8.4,1.4,.60]],C.electric),output=box(scene,[8.4,1.0,.6],[.62,.75,.62],0x618975);inspect(output,'Salida eléctrica idealizada: solo una fracción del calor se convierte. Tras la parada del ejemplo la salida es cero y el calor residual se evacua por el bypass y la refrigeración.','Idealised electric output: only a fraction of heat is converted. After example shutdown output is zero and residual heat is removed through bypass and cooling.');

 // This inset illustrates one controlled event, not an exponential neutron population.
 const insetGroup=new THREE.Group();insetGroup.position.set(-9.10,2.60,1.6);insetGroup.scale.setScalar(1.6);scene.add(insetGroup);box(insetGroup,[0,-1.0,-.10],[3.65,.10,1.10],0x365864);const heavy=new THREE.Group();insetGroup.add(heavy);for(let i=0;i<16;i++){const a=i*2.39996,r=.07*Math.sqrt(i+1);ball(heavy,[Math.cos(a)*r,Math.sin(a)*r,(i%3-1)*.07],.085,i%2?0xaebdd2:0xebbd9a);}const fragments=[];for(let side=0;side<2;side++){const group=new THREE.Group();insetGroup.add(group);for(let i=0;i<8;i++){const a=i*2.39996,r=.05*Math.sqrt(i+1);ball(group,[Math.cos(a)*r,Math.sin(a)*r,(i%2-.5)*.07],.078,side?0xaebdd2:0xebbd9a);}fragments.push(group);}const incoming=ball(insetGroup,[-1.55,0,0],.06,0xeff9e6,{emissive:0xd9f8dc,emissiveIntensity:.7}),neutrons=[0,1,2].map(()=>ball(insetGroup,[0,0,0],.055,0xecf8e5,{emissive:0xd9f8dc,emissiveIntensity:.7})),destinations={absorb:V([-.75,.85,.1]),leak:V([-1.45,-.72,.1]),fission:V([1.30,.10,.1])};const absorber=box(insetGroup,destinations.absorb,[.26,.40,.23],0x687f94),nextNucleus=ball(insetGroup,destinations.fission,.17,0xd3bea8);const fissionInset={group:insetGroup,nucleus:heavy,fragments,incoming,neutrons,destinations,absorber,nextNucleus,active:false,progress:0};inspect(absorber,'Un neutrón puede ser absorbido. Otros escapan o provocan una nueva fisión. Los tres destinos son ejemplos, no probabilidades ni un cálculo de multiplicación.','A neutron may be absorbed. Others escape or trigger a new fission. These destinations are examples, not probabilities or a multiplication calculation.');label(insetGroup,t('absorbido','absorbed'),[-.75,1.23,.22],1.05,{bg:false});label(insetGroup,t('escape','leakage'),[-1.33,-.88,.25],.85,{bg:false});label(insetGroup,t('otra fisión','next fission'),[1.28,.63,.35],1.35);label(insetGroup,t('UN EVENTO · ESCALAS ILUSTRATIVAS','ONE EVENT · ILLUSTRATIVE SCALES'),[0,-1.34,.25],3.6); 
 function bars(group,position,names,colors,width=3.0){const root=new THREE.Group();root.position.copy(V(position));group.add(root);const items=names.map((name,i)=>{const y=.50-i*.33;box(root,[0,y,0],[width,.12,.13],0x354b57);const bar=box(root,[0,y,.08],[width,.10,.08],colors[i],{emissive:colors[i],emissiveIntensity:.15}),caption=label(root,name,[0,y,.14],1.75,{bg:false,textSize:.24});caption.m.position.x=-width/2-.16-caption.m.scale.x/2;return {name,bar,caption,value:0};});label(root,t('MISMA ESCALA · 0–100','SAME SCALE · 0–100'),[0,.86,.12],width,{bg:false,textSize:.20});return {group:root,items,commonScale:100,width};}
 const powerBars=bars(zoneAnnotations[2],[4.85,.48,2.1],[t('Calor','Heat'),t('Electricidad','Electricity'),t('Evacuado','Rejected')],[C.fission,C.electric,C.cooling],3.2),coreBars=bars(zoneAnnotations[3],[-5.6,.62,1.6],[t('Inmediato','Prompt heat'),t('Decaimiento','Decay'),t('Calor total','Total heat')],[C.fission,C.decay,C.cooling],2.55);
 const coreCaption=label(zoneAnnotations[0],'',[-6.75,5.24,1.0],4.9,{height:128}),sgCaption=label(zoneAnnotations[1],t('DOS AGUAS SEPARADAS\nLa energía cruza la pared','TWO SEPARATE WATERS\nEnergy crosses the wall'),[-2.2,4.57,.95],3.2,{height:128}),turbineCaption=label(zoneAnnotations[2],'',[4.55,3.64,.8],5.8,{height:128}),shutdownCaption=label(zoneAnnotations[3],'',[-6.5,5.20,1.0],4.4,{height:128});
 label(zoneAnnotations[1],t('1 · Primario líquido','1 · Liquid primary'),[-2.2,.32,1.3],3.0);label(zoneAnnotations[2],t('Condensador · aguas separadas','Condenser · separate waters'),[3.3,1.70,1.20],3.5,{textSize:.20});label(zoneAnnotations[3],t('Paso 5: inserción instantánea ilustrativa','Step 5: illustrative instantaneous insertion'),[-6.5,.22,2.35],4.2,{textSize:.18});
 const overviewLabelsGroup=new THREE.Group();scene.add(overviewLabelsGroup);for(const [words,p,width] of [[t('NÚCLEO','CORE'),[-6.5,5.25,.7],2.3],[t('GENERADOR DE VAPOR','STEAM GENERATOR'),[-2.2,5.05,.7],3.8],[t('TURBINA + GENERADOR','TURBINE + GENERATOR'),[4.55,3.5,.7],4.8],[t('REFRIGERACIÓN','COOLING'),[7.6,1.9,-2.7],3.4]])label(overviewLabelsGroup,words,p,width);
 const circuitLegend=new THREE.Group();overviewLabelsGroup.add(circuitLegend);for(const [name,color,x] of [[t('1 · PRIMARIO','1 · PRIMARY'),C.primary,-5.5],[t('2 · SECUNDARIO','2 · SECONDARY'),C.secondary,0],[t('3 · REFRIGERACIÓN','3 · COOLING'),C.cooling,5.5]]){ball(circuitLegend,[x-1.8,.45,2.45],.085,color);label(circuitLegend,name,[x,.45,2.45],3.4);}
 const standsGroup=new THREE.Group();scene.add(standsGroup);for(let i=0;i<4;i++){const x=[-7,-2.2,4.4,-10.5][i],z=5.8;box(standsGroup,[x,.52,z],[1.7,1.04,.75],0x294a59);box(standsGroup,[x,1.09,z],[1.9,.09,.95],0xa5b2b8);const button=box(standsGroup,[x,1.23,z+.12],[.85,.20,.50],0xffd995,{emissive:0xe0bb79,emissiveIntensity:.4});button.userData.action=i;targets.push(button);stands.push(button);label(standsGroup,`${i+1} · ${(es?['FISIÓN','CIRCUITOS','ELECTRICIDAD','PARADA']:['FISSION','CIRCUITS','ELECTRICITY','SHUTDOWN'])[i]}`,[x,.67,z+.4],1.65);label(standsGroup,t('▶ ESCUCHAR','▶ LISTEN'),[x,1.34,z+.20],.86);}
 let lastState;
 function animateRoute(route,power,time,speed=.12,{enabled=true}={}){route.flow=enabled&&power>0?power:0;route.energy=route.flow;route.progress=((time*speed)%1+1)%1;const count=route.flow>0?Math.max(1,Math.ceil(12*clamp(route.flow/100))):0;route.packets.forEach((m,i)=>{m.visible=i<count;m.position.copy(route.curve.getPoint((route.progress+i/12)%1));});}
 function setBars(record,values){record.items.forEach((item,i)=>{item.value=values[i];item.bar.visible=values[i]>0;item.bar.scale.x=clamp(values[i]/record.commonScale);item.bar.position.x=-record.width/2+record.width*item.bar.scale.x/2;});}
 function update(model,time=0,phase=0,whole=false,immersive=false){const s=sampleNuclear(model.trace,Number.isFinite(time)?time:0);lastState=s;const clock=s.time,operating=s.operatingTime,stopped=s.stopped;
  controlRods.forEach(r=>r.position.y=stopped?r.userData.insertedY:r.userData.withdrawnY);fuel.forEach(m=>m.material.emissiveIntensity=.70*s.fission/100);decayMarkers.forEach(m=>m.material.emissiveIntensity=2*s.decay/100);
  turbine.angle=operating*2.2;generator.angle=turbine.angle;turbineRotor.rotation.x=turbine.angle;generatorRotor.rotation.x=generator.angle;for(const p of [primaryPump,feedPump,coolingPump]){p.angle=clock*2.0;p.rotor.rotation.z=p.angle;}
  animateRoute(primary,s.heat,clock);animateRoute(secondaryOut,s.heat,clock);animateRoute(commonReturn,s.heat,clock);animateRoute(normalSteam,s.heat,operating,.12,{enabled:!stopped});animateRoute(bypassSteam,s.heat,s.phaseTime,.12,{enabled:stopped});animateRoute(cooling,s.rejected,clock,.15);animateRoute(electricity,s.electric,operating,.23);normal.flow=stopped?0:s.heat;normal.energy=normal.flow;normal.progress=((operating*.12)%1+1)%1;bypass.flow=stopped?s.heat:0;bypass.energy=bypass.flow;bypass.progress=((s.phaseTime*.12)%1+1)%1;secondary.flow=s.heat;secondary.energy=s.heat;
  normalValve.material.color.setHex(stopped?0x6b7a86:C.secondary);bypassValve.material.color.setHex(stopped?C.secondary:0x6b7a86);sgTransfer.forEach(m=>{m.visible=s.heat>0;m.material.emissiveIntensity=s.heat/100;});
  setBars(powerBars,[s.heat,s.electric,s.rejected]);setBars(coreBars,[s.fission,s.decay,s.heat]);const f=((operating/2.25)%1+1)%1;fissionInset.active=!stopped&&s.fission>0;fissionInset.progress=f;heavy.visible=f<.35;incoming.visible=f<.35&&!stopped;incoming.position.set(-1.55+1.55*clamp(f/.35),0,0);fragments.forEach((g,i)=>{g.visible=f>=.35;g.position.set((i?1:-1)*(.12+.38*clamp((f-.35)/.40)),(i?.12:-.12),0);});neutrons.forEach((m,i)=>{m.visible=!stopped&&f>=.35&&f<.96;const destination=[destinations.absorb,destinations.leak,destinations.fission][i];m.position.copy(destination).multiplyScalar(clamp((f-.35)/.60));});nextNucleus.material.emissive.setHex(C.fission);nextNucleus.material.emissiveIntensity=!stopped&&f>.80?.4:0;
  coreCaption.set(stopped?t('Fisión detenida\nEl decaimiento continúa','Fission stopped\nDecay continues'):t('Reacción controlada\nFisión + decaimiento → calor','Controlled reaction\nFission + decay → heat'));turbineCaption.set(stopped?t('TURBINA PARADA · ELECTRICIDAD 0\nBypass hacia condensador','TURBINE STOPPED · ELECTRICITY 0\nBypass to condenser'):t('VAPOR → EJE → ELECTRICIDAD\nEl resto del calor se evacua','STEAM → SHAFT → ELECTRICITY\nThe rest of the heat is removed'));shutdownCaption.set(stopped?t('Barras insertadas · fisión 0\nCalor residual → bypass → refrigeración','Rods inserted · fission 0\nDecay heat → bypass → cooling'):t('Productos ya liberan calor\nLa parada no lo elimina de golpe','Products already release heat\nShutdown does not erase it instantly'));
  zoneAnnotations.forEach((g,i)=>g.visible=!whole&&i===phase);overviewLabelsGroup.visible=whole;insetGroup.visible=!whole&&phase===0;standsGroup.visible=immersive;stands.forEach((button,i)=>button.material.emissiveIntensity=i===phase?1:.16);
 }
 return {scene,resources,targets,stands,standsGroup,annotations,zoneAnnotations,overviewLabelsGroup,reactor,fuel,controlRods,decayMarkers,pressurizer,steamGenerator,turbine,generator,condenser,heatExchanger,pumps:{primary:primaryPump,feed:feedPump,cooling:coolingPump},circuits,routes:[primary,secondaryOut,normalSteam,bypassSteam,commonReturn,cooling,electricity],electricity,fissionInset,powerBars,coreBars,focus:NUCLEAR_FOCUS,bounds:NUCLEAR_BOUNDS,outlines:[],parts:{floor,platform,reactor,steamGenerator,turbine,generator,condenser,heatExchanger},update,get state(){return lastState;}};
}

export function nuclearFraming(phase,orbit={},aspect=1,fov=46){const whole=orbit.whole===true,index=whole?4:Math.max(0,Math.min(3,phase)),bounds=NUCLEAR_BOUNDS[index],center=new THREE.Vector3((bounds[0]+bounds[3])/2,(bounds[1]+bounds[4])/2,(bounds[2]+bounds[5])/2),yaw=orbit.yaw??nuclearOverview.yaw,pitch=orbit.pitch??nuclearOverview.pitch,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let distance=3;for(const x of [bounds[0],bounds[3]])for(const y of [bounds[1],bounds[4]])for(const z of [bounds[2],bounds[5]]){const p=new THREE.Vector3(x,y,z).sub(center),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),depth+Math.abs(p.dot(up))/tan);}distance*=1.12*(orbit.distance??nuclearOverview.distance)/nuclearOverview.distance;return {center,distance,direction,bounds};}
const isVisible=object=>{for(let o=object;o;o=o.parent)if(!o.visible)return false;return true;};
export function createNuclearWorld(options,legacyLesson,legacyEs,legacyInspect){const objectAPI=!!options?.container,host=objectAPI?options.container:options,lesson=objectAPI?options.lesson:legacyLesson,es=objectAPI?options.lang!=='en':legacyEs,onInspect=(objectAPI?options.onInspect:legacyInspect)||(()=>{}),initialMode=objectAPI?options.mode||'web':'web';const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);renderer.domElement.tabIndex=0;const built=createNuclearScene(lesson,es),camera=new THREE.PerspectiveCamera(46,1,.1,150),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let model,phase=0,elapsed=0;
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=camera.aspect<1?65:46;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(host);resize();
 function nearest(player){let best=null,distance=5.8;built.stands.forEach((stand,i)=>{const p=stand.getWorldPosition(new THREE.Vector3()),d=Math.hypot(player.x-p.x,player.z-p.z);if(d<distance){best=i;distance=d;}});return best;}
 function hit(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);return ray.intersectObjects(built.targets.filter(isVisible))[0];}
 return {canvas:renderer.domElement,update(s,i){model=s;phase=i;},render(player,dt,animation,orbit=nuclearOverview,mode=initialMode,time){if(Number.isFinite(time))elapsed=time;else if(model&&Number.isFinite(model.t))elapsed=model.t;if(model)built.update(model,elapsed,phase,mode==='web'&&orbit.whole===true,mode==='immersive');if(mode==='immersive'){camera.position.set(player.x,1.65,player.z);camera.rotation.set(player.pitch,player.yaw,0,'YXZ');}else{const frame=nuclearFraming(phase,orbit,camera.aspect,camera.fov);camera.position.copy(frame.center).addScaledVector(frame.direction,frame.distance);camera.lookAt(frame.center);}renderer.render(built.scene,camera);},inspect(x,y){const h=hit(x,y);if(h)onInspect(h.object.userData.action===undefined?h.object.userData.info:{chapter:h.object.userData.action});},nearest,activate(){const r=renderer.domElement.getBoundingClientRect(),h=hit(r.left+r.width/2,r.top+r.height/2),chapter=h?.object.userData.action!==undefined&&h.distance<8?h.object.userData.action:nearest({x:camera.position.x,z:camera.position.z});if(chapter!==null)onInspect({chapter});},dispose(){observer.disconnect();built.resources.forEach(resource=>resource.dispose());renderer.dispose();},poseAt:lesson?.poseAt||nuclearPoseAt};
}
