import {L,control,toggle,metric,chapter,clamp} from './common.js';
import {buildNuclearTrace,sampleNuclear} from './nuclear-model.js';
export {heatBalance} from './nuclear-model.js';
let cachedKey,cachedTrace;
export function nuclearExperiment(p){const key=[p.power,p.efficiency,p.stop].join(':');if(key!==cachedKey||!cachedTrace){cachedTrace=buildNuclearTrace(p);cachedKey=key;}return cachedTrace;}
export const nuclearFocus=[[-6.5,2.5,0],[-2.2,2.6,0],[4.4,2,0],[-6.5,2.5,0]],nuclearStandX=[-7,-2.2,4.4,-10.5];
export function nuclearPoseAt(i){const f=nuclearFocus[i],x=nuclearStandX[i],z=8.3;return {x,z,yaw:Math.atan2(x-f[0],z-f[2]),pitch:Math.atan2(f[1]-1.65,Math.hypot(x-f[0],z-f[2]))};}
export function nuclearWalk(p,f,s,dt){const n=Math.max(1,Math.hypot(f,s)),v=3.5*Math.min(.05,dt);let x=clamp(p.x+(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*v,-13,12),z=clamp(p.z+(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*v,-8,12);const inside=(a,b)=>a>-9&&a<9&&b>-4&&b<2.8;if(inside(x,z)){if(!inside(x,p.z))z=p.z;else if(!inside(p.x,z))x=p.x;else{x=p.x;z=p.z;}}return {...p,x,z};}
export const nuclear={id:'nuclear',room:'industry',title:L('Un reactor convierte calor en electricidad','A reactor turns heat into electricity'),color:'#ffb582',unit:L('paso','step'),horizon:24,continuous:true,
 poseAt:nuclearPoseAt,walk:nuclearWalk,overview:{yaw:.06,pitch:.30,distance:9.5},fitLabel:L('Ver la central completa','Fit the whole plant'),
 narrationTime(p,i,u,voiceLang='es'){u=clamp(u,0,1);if(i<3)return [.4,1.6,2.8][i]+[1.2,1.2,1.6][i]*u;const stopAt=voiceLang==='en' ? .56 : .59;if(u<=.10)return 0;if(u<=stopAt)return 5*(u-.10)/(stopAt-.10);return 5+19*clamp((u-stopAt)/(.92-stopAt),0,1);},
 challenge:L('Detén la reacción en cadena: la refrigeración continúa','Stop the chain reaction: cooling continues'),controls:[control('power',L('Potencia térmica ilustrativa · u. de potencia','Illustrative thermal power · power units'),100,20,100,10),control('efficiency',L('Conversión eléctrica idealizada · %','Idealised electrical conversion · %'),33,20,40),toggle('stop',L('Parar la reacción en cadena en el paso 5','Stop the chain reaction at step 5'),true)],
 steps:[chapter(L('1 · Liberar energía en el núcleo','1 · Releasing energy in the core'),L('En la fisión, un núcleo pesado se divide y libera energía y neutrones. Parte de esos neutrones puede provocar nuevas fisiones. Las barras de control absorben neutrones y ayudan a controlar la reacción. Esta escena muestra el principio; las partículas, dimensiones y tiempos son ilustrativos.','In fission, a heavy nucleus splits, releasing energy and neutrons. Some neutrons can cause further fissions. Control rods absorb neutrons and help control the reaction. This scene shows the principle; particles, dimensions and times are illustrative.')),
 chapter(L('2 · Separar dos circuitos','2 · Separating two circuits'),L('Seguimos un reactor de agua a presión. El agua del circuito primario transporta calor sin hervir en funcionamiento normal. Dentro del generador de vapor transfiere calor a otro circuito. Los colores distinguen ambos: se intercambia energía a través de los tubos, no se mezcla el agua.','We follow a pressurised water reactor. Primary-loop water carries heat without boiling during normal operation. Inside the steam generator it transfers heat to another circuit. Colours distinguish the two: energy crosses the tubes, but the water does not mix.')),
 chapter(L('3 · Mover una turbina','3 · Turning a turbine'),L('El vapor del circuito secundario mueve una turbina conectada a un generador. Solo parte de la potencia térmica se convierte en electricidad; el resto debe evacuarse. Cambia el rendimiento idealizado y observa el reparto. El condensador enfría el vapor para recuperar agua y repetir el ciclo.','Secondary-loop steam turns a turbine connected to a generator. Only part of the thermal power becomes electricity; the rest must be removed. Change the idealised efficiency and observe the split. The condenser cools the steam to recover water and repeat the cycle.')),
 chapter(L('4 · Una parada todavía necesita refrigeración','4 · A shutdown still needs cooling'),L('Al insertar las barras se puede detener la reacción en cadena, pero los productos radiactivos siguen liberando calor al decaer. Activa la parada y avanza al paso cinco: la fisión cesa y queda calor residual. La curva es didáctica; no sirve para calcular una refrigeración real ni operar una central.','Inserting control rods can stop the chain reaction, but radioactive products continue releasing heat as they decay. Enable shutdown and advance to step five: fission stops and residual heat remains. This curve is educational; it cannot size real cooling systems or operate a power station.'))],
 limitations:L('Maqueta de un PWR con tres aguas separadas: primario, secundario y refrigeración del condensador. La energía cruza paredes de intercambiadores; el agua no se mezcla. Tras la parada, mostramos vapor secundario derivado al condensador sin mover la turbina, con bombas y sumidero de calor idealmente disponibles. Es un caso explicativo, no un diseño de sistemas de seguridad ni una secuencia de operación. La central empieza en un equilibrio sintético: 93 % de calor inmediato y 7 % de decaimiento, que ya existe antes de parar. La reserva de energía nuclear pendiente se repone durante la fisión y disminuye después: no es calor almacenado ni temperatura. Tras el paso 5, el decaimiento sigue 7 % × exp(−0,2 × pasos), fracción y curva elegidas para esta maqueta, no calibradas para un reactor; en realidad dependen de la historia de irradiación y de los isótopos. Potencias y energías tienen unidades arbitrarias; los 24 pasos no son segundos. Extracción de calor ideal sin almacenamiento térmico; electricidad bruta, sin consumo auxiliar. Se omiten reactividad, neutrones retardados, inercia del rotor, temperaturas, presión, combustible, fallos, alimentación auxiliar y otros modos de refrigeración. Partículas, tamaños y velocidades son ilustrativos. La demostración de fisión no calcula criticidad ni una cascada exponencial. Retroceder reconstruye la explicación, no revierte procesos físicos.','PWR model with three separate waters: primary, secondary and condenser cooling. Energy crosses heat-exchanger walls; water does not mix. After shutdown, secondary steam bypasses the turbine into the condenser, with pumps and a heat sink ideally available. This is an explanatory case, not a safety-system design or operating sequence. The plant starts in synthetic equilibrium: 93% prompt heat and 7% decay heat, already present before shutdown. Pending nuclear energy is replenished during fission and decreases afterwards; it is not stored heat or temperature. After step 5, decay follows 7% × exp(−0.2 × steps), a fraction and curve chosen for this model, not calibrated to a reactor; real values depend on irradiation history and isotopes. Powers and energies have arbitrary units; the 24 steps are not seconds. Ideal heat extraction without thermal storage; gross electricity, without auxiliary consumption. Reactivity, delayed neutrons, rotor inertia, temperatures, pressure, fuel, failures, auxiliary feedwater and other cooling modes are omitted. Particles, dimensions and speeds are illustrative. The fission demonstration calculates neither criticality nor exponential multiplication. Rewinding reconstructs the explanation and does not reverse physical processes.'),
 sources:[['NRC · Pressurized water reactors','https://www.nrc.gov/reactors/power/pwrs'],['DOE · Reactor heat and decay heat','https://www.energy.gov/documents/doe-hdbk-1012-92vol2'],['NRC · Steam dump and turbine bypass (Calvert Cliffs, §5.10.3.16)','https://www.nrc.gov/reactors/operating/licensing/renewal/applications/calvert-cliffs/ccv2.pdf'],['NRC · How a nuclear power plant makes electricity','https://www.nrc.gov/education-regulatory-research/the-student-corner/science-101/how-does-a-nuclear-power-plant-make-electricity']],
 evaluate(p,t){const trace=nuclearExperiment(p),s=sampleNuclear(trace,t),units=L('u. de potencia','power units');return {...s,trace,metrics:[metric(L('Calor total','Total heat'),s.heat,units),metric(L('Electricidad bruta','Gross electricity'),s.electric,units),metric(L('Calor evacuado','Heat removed'),s.rejected,units),metric(L('Calor por decaimiento','Decay heat'),s.decay,units)],series:[{label:L('Calor total','Total heat'),values:trace.states.map(v=>v.heat)},{label:L('Electricidad','Electricity'),values:trace.states.map(v=>v.electric)},{label:L('Decaimiento · ampliado','Decay · enlarged'),values:trace.states.map(v=>v.decay)}]};},
 // A continuous PWR and its three separate circuits live in nuclear-world.js.
 build(){return ()=>{};}
};
