import {L,control,toggle,metric,chapter} from './common.js';
export function heatBalance(p,t){const stopped=p.stop&&t>=5,fission=stopped?0:p.power,decay=stopped?p.power*.08*Math.exp(-(t-5)*.2):0,heat=fission+decay,electric=stopped?0:heat*p.efficiency/100;return {stopped,fission,decay,heat,electric,rejected:heat-electric};}
export const nuclear={id:'nuclear',room:'industry',title:L('Un reactor convierte calor en electricidad','A reactor turns heat into electricity'),color:'#ffb582',unit:L('instante','instant'),horizon:24,
 challenge:L('Detén la fisión: el calor no desaparece de golpe','Stop fission: heat does not vanish instantly'),controls:[control('power',L('Potencia térmica ilustrativa · unidades','Illustrative thermal power · units'),100,20,100,10),control('efficiency',L('Conversión eléctrica idealizada · %','Idealised electrical conversion · %'),33,20,40),toggle('stop',L('Parar la fisión en el paso 5','Stop fission at step 5'),true)],
 steps:[chapter(L('1 · Liberar energía en el núcleo','1 · Releasing energy in the core'),L('En la fisión, un núcleo pesado se divide y libera energía y neutrones. Parte de esos neutrones puede provocar nuevas fisiones. Las barras de control absorben neutrones y ayudan a controlar la reacción. Esta escena muestra el principio; las partículas, dimensiones y tiempos son ilustrativos.','In fission, a heavy nucleus splits, releasing energy and neutrons. Some neutrons can cause further fissions. Control rods absorb neutrons and help control the reaction. This scene shows the principle; particles, dimensions and times are illustrative.')),
 chapter(L('2 · Separar dos circuitos','2 · Separating two circuits'),L('Seguimos un reactor de agua a presión. El agua del circuito primario transporta calor sin hervir en funcionamiento normal. Dentro del generador de vapor transfiere calor a otro circuito. Los colores distinguen ambos: se intercambia energía a través de los tubos, no se mezcla el agua.','We follow a pressurised water reactor. Primary-loop water carries heat without boiling during normal operation. Inside the steam generator it transfers heat to another circuit. Colours distinguish the two: energy crosses the tubes, but the water does not mix.')),
 chapter(L('3 · Mover una turbina','3 · Turning a turbine'),L('El vapor del circuito secundario mueve una turbina conectada a un generador. Solo parte de la potencia térmica se convierte en electricidad; el resto debe evacuarse. Cambia el rendimiento idealizado y observa el reparto. El condensador enfría el vapor para recuperar agua y repetir el ciclo.','Secondary-loop steam turns a turbine connected to a generator. Only part of the thermal power becomes electricity; the rest must be removed. Change the idealised efficiency and observe the split. The condenser cools the steam to recover water and repeat the cycle.')),
 chapter(L('4 · Una parada todavía necesita refrigeración','4 · A shutdown still needs cooling'),L('Al insertar las barras se puede detener la reacción en cadena, pero los productos radiactivos siguen liberando calor al decaer. Activa la parada y avanza al paso cinco: la fisión cesa y queda calor residual. La curva es didáctica; no sirve para calcular una refrigeración real ni operar una central.','Inserting control rods can stop the chain reaction, but radioactive products continue releasing heat as they decay. Enable shutdown and advance to step five: fission stops and residual heat remains. This curve is educational; it cannot size real cooling systems or operate a power station.'))],
 limitations:L('Esquema de un PWR, no simulador operativo. Unidades térmicas arbitrarias, sin segundos reales. Tras el paso 5, la curva residual es 8 % × exp(−0,2 × pasos), elegida solo para mostrar un descenso no instantáneo. La generación eléctrica se detiene y todo el calor residual se evacua. No se calculan reactividad, temperaturas, presión ni sistemas de seguridad.','PWR schematic, not an operational simulator. Arbitrary heat units and no real seconds. After step 5, residual heat follows 8% × exp(−0.2 × steps), chosen only to show a non-instantaneous decrease. Electricity generation stops and all residual heat is removed. Reactivity, temperatures, pressure and safety systems are not calculated.'),
 sources:[['NRC · Heat after shutdown','https://www.nrc.gov/facilities-safety/storage-of-spent-nuclear-fuel/spent-fuel-storage-in-pools-and-dry-casks-key-points-and-questions-answers'],['NRC · Pressurized water reactors','https://www.nrc.gov/reactors/power/pwrs'],['NRC · How a nuclear power plant makes electricity','https://www.nrc.gov/education-regulatory-research/the-student-corner/science-101/how-does-a-nuclear-power-plant-make-electricity']],
 evaluate(p,t){const s=heatBalance(p,t),history=Array.from({length:t+1},(_,i)=>heatBalance(p,i));return {...s,t,metrics:[metric(L('Calor generado','Heat generated'),s.heat,L('u.','units')),metric(L('Electricidad','Electricity'),s.electric,L('u.','units')),metric(L('Calor que evacuar','Heat to remove'),s.rejected,L('u.','units'))],series:[{label:L('Fisión · u.','Fission · units'),values:history.map(h=>h.fission)},{label:L('Calor residual · u.','Residual heat · units'),values:history.map(h=>h.decay)}]};},
 build(k){const {group,cylinder,box,sphere,tube,label,pulse,THREE}=k;const core=group(0);cylinder(core,[0,1.65,0],1.3,3,0x7095b3,L('Vasija del reactor: corte esquemático.','Reactor vessel: schematic cutaway.'),{transparent:true,opacity:.18,depthWrite:false});const rods=[],fuel=[];for(let i=0;i<9;i++){const x=(i%3-1)*.55,z=(Math.floor(i/3)-1)*.55;fuel.push(cylinder(core,[x,1.5,z],.08,1.9,0xefaa79));if(i%2===0)rods.push(cylinder(core,[x+.2,3,z],.045,1.9,0x627886));}label(core,'FISSION → HEAT',0,4.1,0,4);
 const loops=group(1);cylinder(loops,[-2,1.4,0],.65,2.6,0x526e85);cylinder(loops,[1,1.7,0],.85,3.1,0x74899e,null,{transparent:true,opacity:.22,depthWrite:false});const primary=[[-2,2.5,.3],[-1,2.5,.3],[.5,2.5,.3],[1.4,1,.3],[.4,.65,.3],[-2,.65,.3],[-2,2.5,.3]],secondary=[[1.1,3.1,-.3],[2.8,3.1,-.3],[2.8,.3,-.3],[1.1,.3,-.3],[1.1,3.1,-.3]];tube(loops,primary,.09,0xf0a179,L('Circuito primario cerrado: calor desde el reactor.','Closed primary loop: heat from the reactor.'));tube(loops,secondary,.09,0x8ad7ed,L('Circuito secundario separado: vapor hacia la turbina.','Separate secondary loop: steam to the turbine.'));const p1=pulse(loops,primary,0xffcb86),p2=pulse(loops,secondary,0x86e1ef);label(loops,'1       |       2',0,4,0,4);
 const turbine=group(2),rotor=new THREE.Group();rotor.position.set(-.7,2,0);turbine.add(rotor);const shaft=cylinder(rotor,[0,0,0],.2,4,0xa7b9c4);shaft.rotation.z=Math.PI/2;for(let j=0;j<5;j++)for(let i=0;i<10;i++){const a=i*Math.PI/5,m=box(rotor,[-1.5+j*.55,Math.cos(a)*.65,Math.sin(a)*.65],[.1,.55,.12],0xd6dce0);m.rotation.x=a;}box(turbine,[2.2,1.8,0],[1,1.4,1.2],0x809b85,L('Generador: convierte trabajo mecánico en electricidad.','Generator: converts mechanical work into electricity.'));const out=box(turbine,[0,.4,1.7],[5,.2,.5],0x7bdfbe);label(turbine,'HEAT → WORK → ELECTRICITY',0,3.8,0,6);
 const cooling=group(3);cylinder(cooling,[-1.5,1.5,0],1,2.8,0x77909e);const residual=sphere(cooling,[-1.5,1.5,.9],.55,0xff9e70,null,{emissive:0xff724b,emissiveIntensity:.8});const coolingPath=[[-1.5,.6,0],[1.8,.6,0],[1.8,2.5,0],[-1.5,2.5,0],[-1.5,.6,0]];tube(cooling,coolingPath,.09,0x76bdde);const cool=pulse(cooling,coolingPath,0xa5e8ff);box(cooling,[1.8,1.5,0],[1,1.8,.5],0x568a9e,L('Intercambiador: rechaza calor al entorno mediante un circuito de refrigeración.','Heat exchanger: rejects heat to the environment through a cooling circuit.'));label(cooling,'DECAY HEAT',0,3.7,0,4);
 return(s,time)=>{rods.forEach(r=>r.position.y=s.stopped?1.65:3);fuel.forEach(r=>r.material.emissive.setHex(s.stopped?0x180b04:0x814121));p1(primary,time*.17);p2(secondary,time*.13);cool(coolingPath,time*.2);rotor.rotation.x=s.stopped?0:time*2;out.scale.x=Math.max(.01,s.electric/40);residual.scale.setScalar(Math.max(.08,Math.sqrt(s.heat/100)));};}
};
