import * as THREE from '../../vendor/three.module.js';
import {EYE,WALL_H,walls,exhibits,rooms,roomAt,standAt,PAINTING,paintingPlane} from './model.js';
import {paintingCanvas} from './art.js';
import {immersiveHref} from '../immersive/catalog.js';

const THEMES={hall:{wall:0xb2a591,floor:0x8f928d},mind:{wall:0x414b6d,floor:0x343e59},industry:{wall:0x506b6c,floor:0x58676c},cosmos:{wall:0x35415b,floor:0x353b53},life:{wall:0x8c747d,floor:0x667573}};
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));

// No WebGL dependency: shared wall/painting dimensions can be ray-tested.
export function createMuseumScene(es=true,{maxAnisotropy=1,mobile=false,reducedMotion=false}={}){
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x1b2535);scene.fog=new THREE.Fog(0x1b2535,34,88);
 const resources=[],paintings=[],wallMeshes=[],lights=[],portals=[],animatedDetails=[],decorations=[],roomGroups={},roomRecords=[],own=x=>(resources.push(x),x),t=(a,b)=>es?a:b;
 const unitBox=own(new THREE.BoxGeometry(1,1,1)),sphereGeometry=own(new THREE.SphereGeometry(1,20,14)),unitCylinder=own(new THREE.CylinderGeometry(1,1,1,20)),mat=(color,extra={})=>own(new THREE.MeshStandardMaterial({color,roughness:.68,metalness:.08,...extra}));
 const steel=mat(0x8d9ca8,{metalness:.45,roughness:.42}),darkSteel=mat(0x283641,{metalness:.22}),brass=mat(0xbca16b,{metalness:.56,roughness:.36}),bronze=mat(0x6e6555,{metalness:.42}),plaqueBack=mat(0x25303a,{metalness:.18}),lightMaterial=own(new THREE.MeshBasicMaterial({color:0xffead0}));
 const wallMaterials=Object.fromEntries(rooms.map(r=>[r.id,mat(THEMES[r.id].wall,{roughness:.91})])),themeGlow=Object.fromEntries(rooms.map(r=>[r.id,mat(r.color,{emissive:r.color,emissiveIntensity:.55,roughness:.38})]));
 function box(group,x,y,z,w,h,d,color,extra={}){const material=color?.isMaterial?color:mat(color,extra),m=new THREE.Mesh(unitBox,material);m.position.set(x,y,z);m.scale.set(w,h,d);group.add(m);return m;}
 function ball(group,p,r,color){const m=new THREE.Mesh(sphereGeometry,color?.isMaterial?color:mat(color));m.position.set(...p);m.scale.setScalar(r);group.add(m);return m;}
 function rod(group,a,b,r,material){const p=new THREE.Vector3(...a),q=new THREE.Vector3(...b),m=new THREE.Mesh(unitCylinder,material);m.position.copy(p).add(q).multiplyScalar(.5);m.scale.set(r,p.distanceTo(q),r);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),q.sub(p).normalize());group.add(m);return m;}
 function ring(group,radius,tube,p,material,arc=Math.PI*2){const m=new THREE.Mesh(own(new THREE.TorusGeometry(radius,tube,8,64,arc)),material);m.position.set(...p);group.add(m);return m;}
 function boxes(group,records,material){const m=own(new THREE.InstancedMesh(unitBox,material,records.length)),dummy=new THREE.Object3D();records.forEach((r,i)=>{dummy.position.set(...r.p);dummy.scale.set(...r.s);dummy.rotation.set(...(r.r||[0,0,0]));dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix);});m.instanceMatrix.needsUpdate=true;m.computeBoundingBox();m.computeBoundingSphere();group.add(m);return m;}
 function text(group,words,p,width,color='#f2e9d6'){const c=document.createElement('canvas'),g=c.getContext('2d');g.font='600 48px system-ui';c.width=Math.max(96,Math.ceil(g.measureText(words).width+48));c.height=80;g.font='600 48px system-ui';g.fillStyle=color;g.textAlign='center';g.textBaseline='middle';g.fillText(words,c.width/2,40);const tx=own(new THREE.CanvasTexture(c));tx.colorSpace=THREE.SRGBColorSpace;tx.anisotropy=Math.min(8,maxAnisotropy);const m=new THREE.Mesh(own(new THREE.PlaneGeometry(width,width*80/c.width)),own(new THREE.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false})));m.position.set(...p);group.add(m);return m;}
 function plaque(group,lines,{x=0,y=0,z=0,w=3,h=.8,accent='#d9bd8d',depth=.06}={}){const c=document.createElement('canvas'),W=1024,H=Math.round(W*h/w),g=c.getContext('2d');c.width=W;c.height=H;const bg=g.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#26343f');bg.addColorStop(1,'#17212a');g.fillStyle=bg;g.fillRect(0,0,W,H);const gold=g.createLinearGradient(0,0,W,H);gold.addColorStop(0,'#dfc692');gold.addColorStop(.5,'#9f824f');gold.addColorStop(1,'#ddc391');const rim=Math.max(5,H*.045),inset=rim*2.4;g.strokeStyle=gold;g.lineWidth=rim;g.strokeRect(rim/2,rim/2,W-rim,H-rim);g.lineWidth=Math.max(2,rim*.24);g.strokeStyle=accent;g.strokeRect(inset,inset,W-inset*2,H-inset*2);const total=lines.reduce((a,l)=>a+l.size*H*1.18,0);let yy=H/2-total/2;g.textAlign='center';g.textBaseline='middle';lines.forEach(l=>{const px=l.size*H;yy+=px*.59;g.font=(l.weight||600)+' '+px+'px '+(l.serif===false?'Inter,system-ui,sans-serif':'Georgia,"Times New Roman",serif');g.letterSpacing=((l.spacing??.04)*px)+'px';g.fillStyle=l.color||'#f1e6cf';g.fillText(l.text,W/2,yy,W-inset*3);if(l.rule){const rw=Math.min(W*.43,g.measureText(l.text).width*.85);g.fillStyle=gold;g.fillRect(W/2-rw/2,yy+px*.62,rw,2);}yy+=px*.59;});const tx=own(new THREE.CanvasTexture(c));tx.colorSpace=THREE.SRGBColorSpace;tx.anisotropy=Math.min(8,maxAnisotropy);const face=own(new THREE.MeshStandardMaterial({map:tx,emissiveMap:tx,emissive:0xffffff,emissiveIntensity:.36,roughness:.55,metalness:.10})),board=new THREE.Mesh(unitBox,[brass,brass,brass,brass,face,plaqueBack]);board.position.set(x,y,z);board.scale.set(w,h,depth);group.add(board);return board;}
 const ambient=new THREE.HemisphereLight(0xe6efff,0x4d4b46,2.6);scene.add(ambient);lights.push(ambient);const sun=new THREE.DirectionalLight(0xffeed6,3.2);sun.position.set(4,12,6);scene.add(sun);lights.push(sun);
 function nearbyRoom(x,z){return roomAt(x,z)||rooms.reduce((best,r)=>{const dx=Math.max(r.minX-x,0,x-r.maxX),dz=Math.max(r.minZ-z,0,z-r.maxZ),d=dx*dx+dz*dz;return d<best.d?{r,d}:best;},{r:rooms[0],d:Infinity}).r;}
 // These solids are exactly the movement collision boxes; adjacent faces
 // receive their gallery's finish without changing the shared floor plan.
 for(const [i,b] of walls.entries()){const x=(b.minX+b.maxX)/2,z=(b.minZ+b.maxZ)/2,width=b.maxX-b.minX,depth=b.maxZ-b.minZ,material=[wallMaterials[nearbyRoom(x+width/2+.04,z).id],wallMaterials[nearbyRoom(x-width/2-.04,z).id],darkSteel,darkSteel,wallMaterials[nearbyRoom(x,z+depth/2+.04).id],wallMaterials[nearbyRoom(x,z-depth/2-.04).id]],wallMesh=new THREE.Mesh(own(new THREE.BoxGeometry(width,WALL_H,depth)),material);wallMesh.position.set(x,WALL_H/2,z);wallMesh.userData.wall=b;wallMesh.userData.wallIndex=i;scene.add(wallMesh);wallMeshes.push(wallMesh);box(scene,x,.10,z,width+.035,.20,depth+.035,darkSteel);box(scene,x,WALL_H-.12,z,width+.035,.12,depth+.035,darkSteel);}
 for(const r of rooms){const group=new THREE.Group();group.userData.roomId=r.id;scene.add(group);roomGroups[r.id]=group;const theme=THEMES[r.id],w=r.maxX-r.minX,d=r.maxZ-r.minZ,cx=(r.minX+r.maxX)/2,cz=(r.minZ+r.maxZ)/2,floorMaterial=mat(theme.floor,{roughness:r.id==='hall'?.46:.70,metalness:.08}),floor=box(group,cx,-.13,cz,w,.24,d,floorMaterial),ceiling=box(group,cx,WALL_H,cz,w,.12,d,darkSteel),groutMaterial=mat(r.id==='hall'?0xc7bdab:0x7e8e94,{roughness:.9}),grout=[];
  for(let x=r.minX+1;x<r.maxX;x+=2)grout.push({p:[x,.002,cz],s:[.010,.004,d]});for(let z=r.minZ+1;z<r.maxZ;z+=2)grout.push({p:[cx,.002,z],s:[w,.004,.010]});boxes(group,grout,groutMaterial);
  const skylight=box(group,cx,WALL_H-.09,cz,w*.46,.045,d*.48,mat(0xbccbd6,{emissive:0xc6d7ec,emissiveIntensity:.62,roughness:.3})),beams=[];for(let z=r.minZ+1.7;z<r.maxZ;z+=3)beams.push({p:[cx,WALL_H-.23,z],s:[w,.22,.10]});boxes(group,beams,r.id==='life'?bronze:steel);
  const lamp=new THREE.PointLight(r.color,30,26,2);lamp.position.set(cx,4.25,cz);lamp.userData.roomId=r.id;scene.add(lamp);lights.push(lamp);roomRecords.push({room:r,group,floor,ceiling,skylight,light:lamp});
  // Details stay overhead or within the collision buffer, leaving every
  // existing walking route clear of unmodelled furniture.
  if(r.id==='hall'){const oculus=ring(group,2.15,.055,[cx,5.25,cz],brass);oculus.rotation.x=Math.PI/2;const trim=ring(group,1.96,.022,[cx,5.20,cz],themeGlow.hall);trim.rotation.x=Math.PI/2;for(let i=0;i<12;i++){const a=i*Math.PI/6;rod(group,[cx+Math.cos(a)*1.98,5.18,cz+Math.sin(a)*1.98],[cx+Math.cos(a)*2.15,5.25,cz+Math.sin(a)*2.15],.025,brass);}const compass=ring(group,1.18,.025,[0,.027,1],brass);compass.rotation.x=-Math.PI/2;for(let i=0;i<4;i++){const a=i*Math.PI/2,m=box(group,Math.sin(a)*1.1,.026,1+Math.cos(a)*1.1,.05,.012,1.1,brass);m.rotation.y=a;}}
  if(r.id==='mind'){const tokens=new THREE.Group();tokens.position.set(2.85,4.65,-21.1);group.add(tokens);const tiles=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)tiles.push({p:[(x-1.5)*.17,(y-1.5)*.17,.03],s:[.135,.135,.12]});const matrix=boxes(tokens,tiles,themeGlow.mind);box(tokens,0,0,-.055,.76,.76,.08,darkSteel);const input=box(tokens,-1.07,0,.03,.46,.46,.18,steel),output=box(tokens,1.07,0,.03,.46,.46,.18,brass);text(tokens,'?',[-1.07,0,.135],.17);text(tokens,'…',[1.07,0,.135],.21);for(const [left,right] of [[-.82,-.37],[.37,.82]]){rod(tokens,[left,0,.03],[right,0,.03],.025,brass);rod(tokens,[right-.12,.07,.03],[right,0,.03],.018,brass);rod(tokens,[right-.12,-.07,.03],[right,0,.03],.018,brass);}decorations.push({room:r.id,kind:'tokens-matrix-tokens',group:tokens,parts:{input,matrix,output},illustration:true});const tracks=[];for(const side of [-1,1])for(let z=r.minZ+2;z<r.maxZ-1;z+=3)tracks.push({p:[side*5.77,4.68,z],s:[.045,.035,2.2]});boxes(group,tracks,themeGlow.mind);}
  if(r.id==='industry'){for(const z of [r.minZ+2,r.maxZ-2]){rod(group,[r.minX+.4,4.87,z],[r.maxX-.4,4.87,z],.055,steel);rod(group,[r.minX+.4,4.87,z],[cx,5.37,z],.035,bronze);rod(group,[cx,5.37,z],[r.maxX-.4,4.87,z],.035,bronze);}const arm=new THREE.Group();arm.position.set(-22.1,3.38,.8);arm.rotation.y=Math.PI/2;group.add(arm);const body=mat(0xc69c64,{metalness:.3,roughness:.44}),points=[[0,.13,0],[0,.34,0],[.08,.60,0],[.38,.91,.03],[.65,.90,.03],[.82,.81,.03]],joints=[];box(arm,0,0,0,.48,.16,.40,darkSteel);for(let i=0;i<points.length;i++){const p=points[i],joint=new THREE.Mesh(unitCylinder,darkSteel);joint.position.set(...p);joint.scale.set(i<3?.11:.065,i<3?.17:.12,i<3?.11:.065);if(i!==0&&i!==3)joint.rotation.x=Math.PI/2;arm.add(joint);joints.push(joint);if(i)rod(arm,points[i-1],p,i<3?.10:.075,body);}const wrist=points.at(-1);rod(arm,wrist,[.98,.81,.03],.045,steel);boxes(arm,[{p:[1.0,.86,.05],s:[.20,.025,.055]},{p:[1.0,.76,.05],s:[.20,.025,.055]}],steel);const wafer=new THREE.Mesh(unitCylinder,mat(0x243d60,{metalness:.42,roughness:.24}));wafer.position.set(1.16,.81,-.015);wafer.scale.set(.29,.025,.29);wafer.rotation.x=Math.PI/2;arm.add(wafer);ring(arm,.29,.012,[1.16,.81,.006],brass);const dies=[];for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++)if(x*x+y*y<8)dies.push({p:[1.16+x*.088,.81+y*.088,.011],s:[.07,.07,.012]});boxes(arm,dies,themeGlow.industry);decorations.push({room:r.id,kind:'industrial-arm-wafer',group:arm,parts:{joints,wafer},illustration:true});}
  if(r.id==='cosmos'){const stars=own(new THREE.InstancedMesh(own(new THREE.IcosahedronGeometry(1,0)),own(new THREE.MeshBasicMaterial({color:0xccd8f2})),72)),dummy=new THREE.Object3D();for(let i=0;i<72;i++){dummy.position.set(r.minX+1+(i*2.73)%(w-2),5.38,r.minZ+1+(i*3.19)%(d-2));dummy.scale.setScalar(i%11===0?.034:.017);dummy.updateMatrix();stars.setMatrixAt(i,dummy.matrix);}stars.computeBoundingBox();stars.computeBoundingSphere();group.add(stars);const satellite=new THREE.Group();satellite.position.set(22.05,4.59,0);satellite.rotation.y=-Math.PI/2;group.add(satellite);const bus=box(satellite,0,0,0,.37,.38,.37,brass),panelMaterial=mat(0x263c70,{metalness:.30,roughness:.37}),panels=boxes(satellite,[{p:[-.73,0,0],s:[.88,.38,.035]},{p:[.73,0,0],s:[.88,.38,.035]}],panelMaterial),cells=[];for(const side of [-1,1])for(let row=0;row<2;row++)for(let col=0;col<5;col++)cells.push({p:[side*.73+(col-2)*.16,(row-.5)*.165,.025],s:[.14,.14,.012]});boxes(satellite,cells,themeGlow.cosmos);rod(satellite,[-1.20,0,-.026],[1.20,0,-.026],.025,steel);rod(satellite,[0,.18,0],[.18,.39,.12],.013,steel);const antenna=ring(satellite,.09,.020,[.18,.39,.12],steel);antenna.rotation.y=.4;const globe=new THREE.Group();globe.position.set(22.03,4.61,2.60);globe.rotation.y=-Math.PI/2;group.add(globe);const planet=ball(globe,[0,0,0],.35,mat(0x719bc8,{roughness:.73})),equator=ring(globe,.359,.012,[0,0,0],brass);equator.rotation.x=Math.PI/2;const meridian=ring(globe,.359,.012,[0,0,0],steel);meridian.rotation.y=.60;ball(globe,[.12,.17,.28],.10,mat(0x8da98c));ball(globe,[-.13,-.10,.29],.09,mat(0x8da98c));decorations.push({room:r.id,kind:'satellite-globe',group:satellite,parts:{bus,panels,globe,planet},illustration:true});}
  if(r.id==='life'){const organic=new THREE.Group();organic.position.set(3.65,4.04,25.02);group.add(organic);const points=[[],[]];for(let i=0;i<21;i++){const a=i*.46,y=-.66+i*.066;points[0].push(new THREE.Vector3(Math.cos(a)*.44,y,Math.sin(a)*.44));points[1].push(new THREE.Vector3(-Math.cos(a)*.44,y,-Math.sin(a)*.44));if(i%2===0)rod(organic,points[0][i].toArray(),points[1][i].toArray(),.025,brass);}const strands=[];for(const p of points){const m=new THREE.Mesh(own(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(p),60,.035,6,false)),themeGlow.life);organic.add(m);strands.push(m);}animatedDetails.push({object:organic,room:r.id,speed:.05,axis:'y'});decorations.push({room:r.id,kind:'double-helix',group:organic,parts:{strands},illustration:true});const slats=[];for(let x=r.minX+.25;x<r.maxX;x+=.75)slats.push({p:[x,5.21,cz],s:[.035,.15,d]});boxes(group,slats,bronze);}
 }
 // Gates show the next room on one face and the return to the atrium on the
 // other. Posts remain within the original four-metre wall openings.
 for(const [i,r] of rooms.slice(1).entries()){const g=new THREE.Group();g.position.set(r.gate.x,0,r.gate.z);g.rotation.y=r.id==='industry'?Math.PI/2:r.id==='cosmos'?-Math.PI/2:r.id==='life'?Math.PI:0;scene.add(g);for(const x of [-2,2]){box(g,x,2.1,0,.16,4.2,.50,darkSteel);box(g,x,2.1,.27,.045,4.2,.035,themeGlow[r.id]);box(g,x,2.1,-.27,.045,4.2,.035,themeGlow[r.id]);}box(g,0,4.2,0,4.2,.20,.50,darkSteel);const front=plaque(g,[{text:(es?r.es:r.en).toUpperCase(),size:.32,rule:true,color:r.color},{text:r.subtitle[es?0:1],size:.15,weight:400,serif:false,color:'#dce4e5'}],{y:4.82,z:.22,w:3.55,h:.95,accent:r.color}),back=plaque(g,[{text:t('ATRIO · ATLAS','ATRIUM · ATLAS'),size:.33,rule:true},{text:t('Volver a las cuatro salas','Return to the four galleries'),size:.15,weight:400,serif:false}],{y:4.82,z:-.22,w:3.55,h:.95,accent:r.color});back.rotation.y=Math.PI;const threshold=box(g,0,.024,0,3.68,.014,.65,mat(r.color,{roughness:.8,metalness:.04}));portals.push({room:r,group:g,front,back,threshold});
  const dx=r.gate.x,dz=r.gate.z-1,len=Math.hypot(dx,dz),a=Math.atan2(dx,dz),stripeMaterial=themeGlow[r.id];for(let j=0;j<3;j++){const u=(2.1+j*(len-2.9)/3)/len,x=dx*u,z=1+dz*u;for(const side of [-1,1]){const arrow=box(scene,x+Math.cos(a)*side*.12,.028,z-Math.sin(a)*side*.12,.035,.012,.35,stripeMaterial);arrow.rotation.y=a-side*.62;}}const word=text(scene,String(i+1).padStart(2,'0')+' · '+(es?r.es:r.en),[r.gate.x-r.gate.x/len*.9,.025,r.gate.z-dz/len*.9],2.8,r.color);word.rotation.set(-Math.PI/2,0,a+Math.PI);
 }
 plaque(scene,[{text:'ATLAS',size:.40,rule:true,spacing:.20},{text:rooms[0].subtitle[es?0:1],size:.15,weight:400,serif:false,color:'#d8dfdf'}],{x:4.1,y:3.25,z:7.8,w:2.6,h:.95,accent:rooms[0].color}).rotation.y=Math.PI;const floorTitle=text(scene,t('ENTRA EN UN CUADRO','ENTER A PAINTING'),[0,.026,3.0],5.0,'#ece3ca');floorTitle.rotation.x=-Math.PI/2;

 function frameBand(group,w,h,thickness,depth,z,material){return boxes(group,[{p:[0,(h-thickness)/2,z],s:[w,thickness,depth]},{p:[0,-(h-thickness)/2,z],s:[w,thickness,depth]},{p:[-(w-thickness)/2,0,z],s:[thickness,h-2*thickness,depth]},{p:[(w-thickness)/2,0,z],s:[thickness,h-2*thickness,depth]}],material);}
 for(const e of exhibits){const plane=paintingPlane(e),group=new THREE.Group();group.position.set(e.x,PAINTING.centerY,e.z);group.rotation.y=Math.atan2(e.nx,e.nz);scene.add(group);const w=plane.width,h=plane.height,live=!!immersiveHref(e.id),backing=box(group,0,0,-.075,w+.42,h+.42,.16,darkSteel),frameMaterial=mat(0xb89b69,{metalness:.52,roughness:.35,emissive:e.color,emissiveIntensity:.08}),frameParts=[frameBand(group,w+.43,h+.43,.105,.25,.115,bronze),frameBand(group,w+.25,h+.25,.085,.35,.160,frameMaterial),frameBand(group,w+.095,h+.095,.045,.11,.300,brass)],reveal=frameBand(group,w+.02,h+.02,.035,.30,.170,darkSteel),portalTrim=frameBand(group,w+.03,h+.03,.018,.025,.323,mat(e.color,{emissive:e.color,emissiveIntensity:live?.44:.08,roughness:.42}));
  const texture=own(new THREE.CanvasTexture(paintingCanvas(e,es)));texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,maxAnisotropy);const shader=own(new THREE.ShaderMaterial({uniforms:{map:{value:texture},time:{value:0},hover:{value:0},enter:{value:0},available:{value:live?1:0},accent:{value:new THREE.Color(e.color)}},vertexShader:'uniform float time;uniform float hover;uniform float enter;varying vec2 vUv;void main(){vUv=uv;vec3 p=position;float d=length(uv-.5);float envelope=smoothstep(.08,.18,d)*(1.-smoothstep(.40,.52,d));p.z+=(.5+.5*sin(d*24.-time*3.))*.018*hover*envelope+(.5+.5*sin(d*30.-time*5.))*.060*enter*envelope;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}',fragmentShader:'uniform sampler2D map;uniform float hover;uniform float enter;uniform float available;uniform vec3 accent;varying vec2 vUv;void main(){vec2 uv=(vUv-.5)*(1.-enter*.12)+.5;vec4 col=texture2D(map,uv);float edge=pow(max(abs(vUv.x-.5),abs(vUv.y-.5))*2.,14.);col.rgb+=accent*edge*(.05+hover*.22+enter*.30)*available;gl_FragColor=col;\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}'})),mesh=new THREE.Mesh(own(new THREE.PlaneGeometry(w,h,mobile?18:32,mobile?12:22)),shader);mesh.position.z=PAINTING.canvasOffset;mesh.userData.exhibit=e;group.add(mesh);
  const plaqueHeight=Math.min(.62,Math.max(.40,PAINTING.centerY-h/2-.32)),plaqueY=-h/2-.22-plaqueHeight/2,caption=plaque(group,[{text:e.num+' · '+(es?e.es:e.en),size:.34},{text:live?t('ENTRAR EN EL MUNDO 3D','ENTER THE 3D WORLD'):t('NOTEBOOK WEB','WEB NOTEBOOK'),size:.17,weight:500,serif:false,spacing:.08,color:live?'#b5e9d4':'#c9d2dd'}],{y:plaqueY,z:.30,w:Math.min(w,3.0),h:plaqueHeight,accent:e.color,depth:.05});
  const fixture=box(group,0,h/2+.40,.25,w*.55,.055,.10,brass),lightBar=box(group,0,h/2+.35,.33,w*.52,.025,.075,lightMaterial);for(const x of [-w*.22,w*.22])box(group,x,h/2+.30,.02,.025,.14,.28,brass);paintings.push({e,group,mesh,frameMaterial,frameParts,reveal,portalTrim,backing,caption,fixture,lightBar,live,plane,canvasPlaneOffset:PAINTING.canvasOffset,waveBounds:{minCanvasZ:PAINTING.canvasOffset,maxDisplacement:.078,backingFrontZ:.005}});
 }
 const ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),marker=new THREE.Mesh(own(new THREE.RingGeometry(.18,.25,32)),own(new THREE.MeshBasicMaterial({color:0xc6f2e2,side:THREE.DoubleSide,transparent:true,opacity:.85,depthWrite:false})));marker.rotation.x=-Math.PI/2;marker.position.y=.035;marker.visible=false;scene.add(marker);
 function update({time=0,nearId=null,portal=null,destination=null,roomId=null}={}){const clock=reducedMotion?0:Math.max(0,time);for(const p of paintings){const hot=p.e.id===nearId,enter=portal?.exhibit.id===p.e.id?clamp(portal.progress):0,u=p.mesh.material.uniforms;u.hover.value=hot?1:0;u.enter.value=enter;u.time.value=clock;p.frameMaterial.emissiveIntensity=hot?.28:.08;p.portalTrim.material.emissiveIntensity=p.live?(hot?.90:.44):.08;}for(const d of animatedDetails){d.object.rotation[d.axis]=clock*d.speed;}marker.visible=!!destination;if(destination){marker.position.set(destination.x,.035,destination.z);marker.material.opacity=reducedMotion?.85:.65+Math.sin(clock*3)*.18;}}
 function raycast(raycaster){const hit=raycaster.intersectObjects(paintings.map(p=>p.mesh))[0],wall=raycaster.intersectObjects(wallMeshes)[0];if(hit&&hit.distance<24&&(!wall||hit.distance<wall.distance))return {exhibit:hit.object.userData.exhibit,distance:hit.distance};const p=new THREE.Vector3();if(raycaster.ray.intersectPlane(ground,p)&&p.distanceTo(raycaster.ray.origin)<28&&(!wall||p.distanceTo(raycaster.ray.origin)<wall.distance)&&roomAt(p.x,p.z))return {point:{x:p.x,z:p.z}};return null;}
 scene.updateMatrixWorld(true);
 return {scene,resources,paintings,screens:paintings,roomGroups,roomRecords,wallMeshes,solids:wallMeshes,lights,portals,animatedDetails,decorations,marker,update,raycast};
}
export function createMuseum(host,es){const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.setClearColor(0x1b2535);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.append(renderer.domElement);const mobile=(globalThis.matchMedia?.('(pointer: coarse)').matches??false)||host.clientWidth<640,reducedMotion=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false,built=createMuseumScene(es,{maxAnisotropy:renderer.capabilities.getMaxAnisotropy(),mobile,reducedMotion}),camera=new THREE.PerspectiveCamera(68,1,.06,100),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();camera.rotation.order='YXZ';
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=Math.min(110,2*Math.atan(Math.tan(34*Math.PI/180)/Math.min(1,camera.aspect/1.3))*180/Math.PI);camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(host);resize();let time=0;
 function pick(x,y){const r=renderer.domElement.getBoundingClientRect();if(!r.width||!r.height)return null;pointer.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);ray.setFromCamera(pointer,camera);return built.raycast(ray);}
 return {dom:renderer.domElement,pick,render(player,nearId,dt=.016,portal=null,destination=null){time+=Math.max(0,Math.min(.05,dt));camera.position.set(player.x,EYE,player.z);camera.rotation.set(player.pitch,player.yaw,0,'YXZ');camera.updateMatrixWorld();built.update({time,nearId,portal,destination,roomId:roomAt(player.x,player.z)?.id});renderer.render(built.scene,camera);},lookLock(){return renderer.domElement.requestPointerLock?.();},get stats(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};},dispose(){observer.disconnect();built.resources.forEach(r=>r.dispose());renderer.dispose();renderer.domElement.remove();}};
}
export function placeInFront(exhibit){return standAt(exhibit);}
