import {defaults,cleanDysonState,dysonFrameAt} from './model.js';
import {createDysonWorld} from './world.js';
import {dysonPoseAt,restoreDysonPose,dysonWalk,dysonNearestStand,dysonGuidePath} from './walk.js';
import {LESSONS} from './lessons.js';
import {VOICES} from './voices.js';
import {mountDyson,paintDysonView,dysonInputs,CONTROL_KEYS} from './presentation.js';
import {NotebookPlayer} from '../playback/player.js';
import {bindFirstPerson} from '../immersive/first-person.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),query=new URLSearchParams(location.search),bounded=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(v)?v:a));
let params={...defaults},chapter=0,progress=0,timeSource='narration',mode=['diagram','notebook','immersive'].includes(query.get('mode'))?query.get('mode'):'notebook',pose=dysonPoseAt(0),enteredFPS=false,world,notebook,firstPerson,frame=dysonFrameAt(params,0,0),ready=false,restored=false,holdPose=false,changingVoice=false,aligning=false,playing=false,lookActive=false,wasLocked=false,last=performance.now(),raf,travel=null;
const keys=new Set(),touch=new Set();mountDyson(es);
function rebuild(){params={...cleanDysonState(params)};frame=dysonFrameAt(params,chapter,progress);}
function save(){notebook?.save();}
function manual(){timeSource='manual';playing=false;travel=null;notebook?.pause();}
function align(){if(!ready||timeSource!=='manual')return;const c=notebook.clock.timeline[chapter];aligning=true;try{notebook.seek(c.start+progress*c.duration,false);}finally{aligning=false;}}
function paint(){paintDysonView({es,params,frame,chapter,progress,mode,playing,text:VOICES[notebook?.language||(es?'es':'en')][chapter].text,language:notebook?.language||(es?'es':'en')});world?.render(frame);}
function phase(value){manual();progress=bounded(value,0,1);rebuild();paint();align();save();}
function listenAt(index,keep=false){playing=false;travel=null;timeSource='narration';holdPose=keep;notebook?.stage(index,true);holdPose=false;paint();}
function release(){lookActive=false;firstPerson?.release();$('capture').textContent=t('Activar ratón','Enable mouse look');}
function useMode(value){manual();keys.clear();touch.clear();release();mode=value;if(mode==='immersive'&&!enteredFPS){pose=dysonPoseAt(chapter);enteredFPS=true;}world?.setMode(mode);world?.setPose(pose);history.replaceState(null,'','?mode='+mode);paint();if(mode==='immersive')world?.canvas.focus({preventScroll:true});save();}
try{world=createDysonWorld($('space'),{es,onAction:i=>listenAt(i,true),onView:()=>save()});$('loading').hidden=true;}catch(error){console.error(error);$('loading').textContent=t('3D no disponible: puedes seguir el esquema, cifras, texto y voz.','3D unavailable: follow the diagram, figures, text and narration.');mode='diagram';}
notebook=new NotebookPlayer({id:'dyson',getClips:lang=>VOICES[lang],capture:()=>({params:{...params},chapter,progress,timeSource,mode,enteredFPS,pose:{...pose},camera:world?.getViewState(),follow:$('follow').checked}),restore(saved){if(!saved)return;params={...cleanDysonState(saved.params||defaults)};chapter=Math.floor(bounded(saved.chapter,0,5));progress=bounded(saved.progress,0,1);timeSource=saved.timeSource==='manual'?'manual':'narration';if(!['diagram','notebook','immersive'].includes(query.get('mode'))&&['diagram','notebook','immersive'].includes(saved.mode))mode=saved.mode;enteredFPS=saved.enteredFPS===true;pose=restoreDysonPose(saved.pose);$('follow').checked=saved.follow!==false;rebuild();if(saved.camera)world?.restoreViewState(saved.camera);restored=true;},onSync(s){if(!s||aligning)return;if(timeSource==='manual'&&!notebook?.wanted)return;if(changingVoice&&timeSource==='manual')return;const changed=chapter!==s.index;chapter=s.index;progress=s.progress;rebuild();if(ready&&changed&&$('follow').checked&&!holdPose){if(mode==='immersive')travel={path:dysonGuidePath(pose,dysonPoseAt(chapter)),index:1,target:dysonPoseAt(chapter)};else world?.focus(chapter);}paint();}});
ready=true;if(!restored){chapter=notebook.current.index;progress=notebook.current.progress;rebuild();world?.focus(chapter);}if(mode==='immersive'&&!enteredFPS){pose=dysonPoseAt(chapter);enteredFPS=true;}world?.setMode(mode);world?.setPose(pose);dysonInputs(params,es);paint();
if(world)firstPerson=bindFirstPerson({canvas:world.canvas,enabled:()=>mode==='immersive'&&lookActive,onLook:(dx,dy)=>{travel=null;pose.yaw-=dx*.0025;pose.pitch=bounded(pose.pitch-dy*.002,-1.25,1.25);world.setPose(pose);save();},onActivate:(x,y)=>{if(x==null)world.activate();else{const hit=world.inspect(x,y);if(Number.isInteger(hit?.action))listenAt(hit.action,true);else if(hit?.info){$('inspect').textContent=Array.isArray(hit.info)?hit.info[es?0:1]:String(hit.info);$('inspect').hidden=false;}}},onState(state){const locked=state==='locked';if(wasLocked&&!locked){manual();lookActive=false;paint();save();}wasLocked=locked;}});
function enterCanvas(e){if(mode!=='immersive'||lookActive||e.button!==0)return;const hit=world?.inspect(e.clientX,e.clientY);if(Number.isInteger(hit?.action))listenAt(hit.action,true);lookActive=true;world?.canvas.focus({preventScroll:true});firstPerson?.request();$('capture').textContent=t('Ratón activo · Esc','Mouse active · Esc');save();}
world?.canvas.addEventListener('click',enterCanvas);
for(const id of CONTROL_KEYS)$(id).oninput=()=>{const el=$(id);if(el.value===''||!el.checkValidity())return;const value=+el.value;manual();params[id]=value;rebuild();dysonInputs(params,es);paint();align();save();};
for(const form of ['swarm','shell'])$('form-'+form).onclick=()=>{manual();params.form=form;rebuild();dysonInputs(params,es);paint();align();save();};
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{manual();timeSource='narration';notebook.stage(+b.dataset.chapter,false);world?.focus(chapter);save();});
$('listen').onclick=()=>listenAt(chapter,mode==='immersive');$('next').onclick=()=>listenAt(Math.min(5,chapter+1));$('listen-here').onclick=()=>{const hit=dysonNearestStand(pose);if(hit)listenAt(hit.index,true);};for(const m of ['diagram','notebook','immersive'])$('mode-'+m).onclick=()=>useMode(m);
$('capture').onclick=()=>{lookActive=true;world?.canvas.focus({preventScroll:true});firstPerson?.request();$('capture').textContent=t('Ratón activo · Esc','Mouse active · Esc');};$('follow').onchange=()=>{if(!$('follow').checked)travel=null;save();};$('fit').onclick=()=>{world?.focus(chapter);save();};$('overview').onclick=()=>{world?.overview();save();};$('zoom-in').onclick=()=>{world?.zoomBy(1.12);save();};$('zoom-out').onclick=()=>{world?.zoomBy(1/1.12);save();};$('phase').oninput=()=>{const value=+$('phase').value;phase(value);};$('reset').onclick=()=>phase(0);$('finish').onclick=()=>phase(1);$('step').onclick=()=>phase(Math.min(1,progress+.125));$('play').onclick=()=>{const resume=!playing;manual();if(progress===1)progress=0;playing=resume;rebuild();paint();align();save();};$('preset-reset').onclick=()=>{manual();params={...defaults};rebuild();dysonInputs(params,es);paint();align();save();};
const playerToggle=notebook.toggle.bind(notebook);notebook.toggle=()=>{if(!notebook.running)timeSource='narration';playing=false;playerToggle();};const playerLanguage=notebook.changeLanguage.bind(notebook);notebook.changeLanguage=lang=>{const wasManual=timeSource==='manual',oldChapter=chapter,oldProgress=progress;changingVoice=true;playerLanguage(lang);if(wasManual){timeSource='manual';chapter=oldChapter;progress=oldProgress;rebuild();paint();save();}changingVoice=false;};const playerSeek=notebook.seek.bind(notebook);notebook.seek=(seconds,play=notebook.wanted)=>{if(!aligning&&!changingVoice){timeSource='narration';playing=false;}playerSeek(seconds,play);};
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{manual();touch.add(b.dataset.move);b.setPointerCapture?.(e.pointerId);};b.onpointerup=b.onpointercancel=()=>{touch.delete(b.dataset.move);save();};}
function keydown(e){if(e.target.matches('input,select,textarea,button,a')&&e.key!=='Escape')return;if(e.key==='Escape'){manual();release();keys.clear();touch.clear();paint();save();return;}if(mode!=='immersive')return;if(e.key.toLowerCase()==='e'){world?.activate();return;}if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();manual();keys.add(e.key.toLowerCase());}}
window.addEventListener('keydown',keydown);const keyup=e=>{if(keys.delete(e.key.toLowerCase()))save();};window.addEventListener('keyup',keyup);const blur=()=>{keys.clear();touch.clear();travel=null;save();};window.addEventListener('blur',blur);const hidden=()=>{if(document.hidden){keys.clear();touch.clear();travel=null;playing=false;release();save();}};document.addEventListener('visibilitychange',hidden);
function tick(now){const dt=bounded((now-last)/1000,0,.05);last=now;if(!document.hidden){if(playing){progress=Math.min(1,progress+dt/20);if(progress===1)playing=false;rebuild();paint();align();}if(mode==='immersive'){const forward=(keys.has('w')||keys.has('arrowup')||touch.has('forward')?1:0)-(keys.has('s')||keys.has('arrowdown')||touch.has('back')?1:0),strafe=(keys.has('d')||keys.has('arrowright')||touch.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||touch.has('left')?1:0);if(forward||strafe){const n=Math.hypot(forward,strafe),d=dt*3.2;pose=dysonWalk(pose,(-Math.sin(pose.yaw)*forward+Math.cos(pose.yaw)*strafe)*d/n,(-Math.cos(pose.yaw)*forward-Math.sin(pose.yaw)*strafe)*d/n);travel=null;}else if(travel&&notebook?.running){const goal=travel.path[travel.index];if(!goal)travel=null;else{const dx=goal.x-pose.x,dz=goal.z-pose.z,n=Math.hypot(dx,dz);if(n<.05)travel.index++;else{const d=Math.min(n,dt*3.2);pose=dysonWalk(pose,dx*d/n,dz*d/n);}}}world?.setPose(pose);const stand=dysonNearestStand(pose);$('listen-here').textContent=stand?'E · '+t('Escuchar','Listen')+' '+LESSONS[stand.index].title[es?0:1]:t('Acércate a un botón del stand','Approach a stand button');$('listen-here').disabled=!stand;$('position').textContent=pose.x.toFixed(1)+' · '+pose.z.toFixed(1)+' m';}world?.render(frame);}raf=requestAnimationFrame(tick);}
raf=requestAnimationFrame(tick);window.addEventListener('pagehide',()=>{save();cancelAnimationFrame(raf);firstPerson?.dispose();world?.canvas.removeEventListener('click',enterCanvas);world?.dispose();notebook.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);});
