// An observatory floor, not a walk through physically scaled space.
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
export const DYSON_ROOM=[-12,-9,12,9];
export const DYSON_LAYOUT=[{index:0,x:-7,z:-5,yaw:0},{index:1,x:-7,z:5,yaw:Math.PI},{index:2,x:0,z:-5,yaw:0},{index:3,x:7,z:-5,yaw:0},{index:4,x:0,z:5,yaw:Math.PI},{index:5,x:7,z:5,yaw:Math.PI}];
export const DYSON_STANDS=DYSON_LAYOUT.map(s=>[s.x,1.4,s.index===2?-.2:s.z+(s.yaw===0?3.1:-3.1)]);
export const DYSON_FOCUS=DYSON_LAYOUT.map(s=>[s.x,2.05,s.z]);
export const DYSON_WALLS=[[-12.12,-9.12,12.12,-8.88],[-12.12,8.88,12.12,9.12],[-12.12,-9,-11.88,9],[11.88,-9,12.12,9]];
export const DYSON_EXHIBIT_SOLIDS=DYSON_LAYOUT.map(s=>s.index===2?[-3.1,-8.1,3.1,-1.9]:[s.x-2.15,s.z-.75,s.x+2.15,s.z+.75]);
export const DYSON_STAND_SOLIDS=DYSON_STANDS.map(([x,y,z])=>[x-.23,z-.21,x+.23,z+.21]);
export const DYSON_SOLIDS=[...DYSON_WALLS,...DYSON_EXHIBIT_SOLIDS,...DYSON_STAND_SOLIDS];
export const DYSON_BOUNDS=DYSON_LAYOUT.map(s=>s.index===2?[-3.3,.25,-8.3,3.3,4.9,-1.7]:[s.x-2.16,.65,s.z-.5,s.x+2.16,4.03,s.z+1.36]);
const chapter=n=>Math.floor(clamp(Number(n),0,5));
export const dysonCollision=(x,z,r=.24)=>DYSON_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);
export function dysonPoseAt(n=0){const s=DYSON_LAYOUT[chapter(n)];return {x:s.x,z:s.index===2?1.4:s.index===4?.3:s.z+(s.yaw===0?5.2:-5.2),yaw:s.yaw,pitch:.04};}
export function restoreDysonPose(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return dysonPoseAt(0);const p={x:clamp(saved.x,-11.5,11.5),z:clamp(saved.z,-8.5,8.5),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return dysonCollision(p.x,p.z)?dysonPoseAt(0):p;}
export function dysonWalk(pose,dx,dz){if(typeof dx==='object'){const f=Number(dx.forward)||0,s=Number(dx.strafe)||0,n=Math.max(1,Math.hypot(f,s)),d=2.5*clamp(dz,0,.05);dx=(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)/n*d;dz=(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)/n*d;}dx=Number.isFinite(dx)?dx:0;dz=Number.isFinite(dz)?dz:0;const count=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.08));let p={...pose};for(let i=0;i<count;i++){const x=clamp(p.x+dx/count,-11.5,11.5),z=clamp(p.z+dz/count,-8.5,8.5);if(!dysonCollision(x,p.z))p.x=x;if(!dysonCollision(p.x,z))p.z=z;}return p;}
export function dysonSegmentClear(a,b,r=.25,solids=DYSON_SOLIDS){for(const q of solids){let lo=0,hi=1,hit=true;const start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];for(let d=0;d<2;d++){const min=q[d]-r,max=q[d+2]+r;if(Math.abs(delta[d])<1e-12){if(start[d]<=min||start[d]>=max){hit=false;break;}}else{let near=(min-start[d])/delta[d],far=(max-start[d])/delta[d];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>=hi){hit=false;break;}}}if(hit&&hi>0&&lo<1)return false;}return true;}
export function dysonNearestStand(pose){let best=null;DYSON_STANDS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),yaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(yaw-pose.yaw),Math.cos(yaw-pose.yaw))),pitch=Math.atan2(y-1.65,distance);if(distance<2.5&&angle<.8&&Math.abs(pitch-(pose.pitch||0))<.60&&dysonSegmentClear(pose,{x,z},0,DYSON_SOLIDS.filter(b=>b!==DYSON_STAND_SOLIDS[index]))&&(!best||distance<best.distance))best={index,action:index,distance,angle,pitch};});return best;}
let grid;
function navigationGrid(){if(grid)return grid;const step=.30,minX=-11.5,minZ=-8.5,nx=78,nz=58,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*step,z=minZ+zi*step;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!dysonCollision(x,z,.25)});}return grid={step,nx,nz,nodes};}
export function dysonGuidePath(from,to){const start=restoreDysonPose(from),end=restoreDysonPose(to);if(dysonSegmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=navigationGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const v=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&v<d&&dysonSegmentClear(p,q)){best=q;d=v;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const open=new Set([first.index]),cost=new Map([[first.index,0]]),previous=new Map(),closed=new Set();while(open.size){let current,best=Infinity;for(const id of open){const q=g.nodes[id],v=cost.get(id)+Math.hypot(q.x-last.x,q.z-last.z);if(v<best){best=v;current=q;}}open.delete(current.index);if(current.index===last.index){const points=[];for(let id=last.index;id!==undefined;id=previous.get(id)){points.push({x:g.nodes[id].x,z:g.nodes[id].z});if(id===first.index)break;}points.reverse();points.unshift({x:start.x,z:start.z});points.push({x:end.x,z:end.z});const out=[points[0]];for(let i=0;i<points.length-1;){let j=points.length-1;while(j>i+1&&!dysonSegmentClear(points[i],points[j]))j--;out.push(points[j]);i=j;}return out;}closed.add(current.index);for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!dysonSegmentClear(current,q))continue;const v=cost.get(current.index)+g.step*Math.hypot(dx,dz);if(v<(cost.get(q.index)??Infinity)){cost.set(q.index,v);previous.set(q.index,current.index);open.add(q.index);}}}return [];}
