import {bindFirstPerson} from '../immersive/first-person.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,number=(n,d=0)=>Number.isFinite(n)?n.toLocaleString(es?'en-US':'en-US',{maximumFractionDigits:d}):'—';
const sum=a=>(a||[]).reduce((s,n)=>s+n,0),esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={factory:[['Prepare el kit','Prepare the kit'],['Assemble estructura','Assemble structure'],['Actuators and battery','Actuators and battery'],['Test','Test'],['Incorporar','Commission']],district:[['Extraer','Extract'],['Refinar','Refine'],['Estructura','Structure'],['Motores','Motors'],['Batteries','Batteries'],['Electronics','Electronics'],['Kits','Kits'],['Assembly','Assembly'],['Testing','Tests']],city:[['Logistics','Logistics'],['Comercio','Commerce'],['Construcción','Construction'],['Limpieza','Cleaning'],['Cuidados','Care'],['Servicios','Services']],region:[['Extraction','Extraction'],['Refining','Refining'],['Components','Components'],['Robots','Robots'],['Electricidad','Electricity'],['Transporte','Transport']]};
const bar=(value,max=1)=>`<progress max="${Math.max(1,max)}" value="${Math.max(0,value)}"></progress>`;
function diagram(kind,frame){const s=frame.state;if(!s)return '';
 if(kind==='factory')return `<p class="robot-flow-title">${t('Un mismo kit atraviesa cinco operaciones','One kit passes through five operations')}</p><div class="robot-flow">${names.factory.map((name,i)=>{const n=s.robots[i].length,job=s.jobs[i],id=frame.identities?.jobs?.[i]?.id;return `<article><b>${i+1} · ${t(...name)}</b><div class="robot-symbols"><span>H ${2-n}</span><span>R ${n}</span></div><strong>${number(s.queues[i])}</strong><small>${t('kits/piezas esperando','kits/parts waiting')}</small>${bar(job??0)}<p>${job===null?t('Sin pieza en proceso','No item in process'):esc(id||t('Pieza en proceso','Item in process'))+' · '+number(job*100)+'%'}</p><small>${number(s.completed[i])} ${t('operaciones terminadas','operations completed')}</small></article>`;}).join('')}</div><div class="robot-return"><b>↶ ${t('De robot terminado a productor','From finished robot to producer')}</b><p>${s.firstReturn?t('El primer relevo tarda 15 minutos simulados antes de trabajar.','The first handover takes 15 simulated minutes before working.'):t('Aún sin robot incorporado. La capacidad aumenta después de fabricar y trasladar.','No robot has joined yet. Capacity increases after manufacturing and transport.')}</p><strong>${s.deployed} / 10 ${t('puestos con robot','robot positions')}</strong> · ${s.total-s.deployed} ${t('finished robots sin desplegar','finished robots not deployed')}</div>`;
 if(kind==='district')return `<p class="robot-flow-title">${t('La receta necesita toda la cadena','The recipe needs the whole chain')}</p><div class="robot-flow robot-nine">${names.district.map((name,i)=>`<article><b>${i+1} · ${t(...name)}</b><div class="robot-symbols"><span>H ${s.humans[i]}</span><span>R ${s.robots[i]}</span></div><strong>${number(s.flow[i])}</strong><small>${t('lotes · último intervalo completo','batches · last completed interval')}</small><p>${s.projects[i]?t('Ampliación en construcción','Expansion under construction'):t('Instalación disponible','Facility available')}</p></article>`).join('')}</div><p>${t('Ore → material → cuatro familias de componentes → kits → montaje → pruebas. Existencias compartidas, no un lote individual seguido por el dibujo.','Ore → material → four component families → kits → assembly → tests. Shared inventory, not one individually tracked batch.')}</p><strong>${s.humansReplaced} / 74 ${t('tareas industriales con relevo','industrial tasks covered')}</strong>`;
 if(kind==='city')return `<p class="robot-flow-title">${t('Industria → envío → llegada → tarea','Industry → shipment → arrival → task')}</p><div class="robot-dispatch"><b>${number(s.industry.fleet)} ${t('robots industriales','industrial robots')}</b><span>→ ${sum(s.pending.map(p=>p.count))} ${t('on the way','in transit')} →</span><b>${sum(s.assigned)} / 600 ${t('tareas cubiertas','covered tasks')}</b></div><div class="robot-flow">${names.city.map((name,i)=>{const tasks=[80,120,100,80,100,120][i];return `<article><b>${t(...name)}</b><div class="robot-symbols"><span>H ${tasks-s.assigned[i]}</span><span>R ${s.assigned[i]}</span></div>${bar(s.assigned[i],tasks)}<small>${s.assigned[i]} / ${tasks} ${t('tareas','tasks')}</small></article>`;}).join('')}</div><p>${t('Un robot entregado cubre una tarea equivalente. La industria y los robots urbanos son grupos distintos.','One delivered robot covers an equivalent task. Industrial and urban robots are separate groups.')}</p>`;
 return `<p class="robot-flow-title">${t('Producir, ampliar y entregar comparten recursos','Production, expansion and deliveries share resources')}</p><div class="robot-flow">${names.region.map((name,i)=>`<article><b>${t(...name)}</b><strong>${s.sites.filter(p=>p.type===i&&p.status==='open').length} / 6</strong><small>${t('instalaciones abiertas','open facilities')}</small><p>${number(s.flow[i],1)} ${t('salida / ciclo','output / cycle')}</p><small>${s.sites.filter(p=>p.type===i&&p.status==='building').length} ${t('obras','projects')}</small></article>`).join('')}</div><div class="robot-towns">${s.towns.map((town,i)=>{const total=sum(town.tasks),covered=sum(town.assigned);return `<article><b>${t('City','Town')} ${i+1}</b><div class="robot-symbols"><span>H ${total-covered}</span><span>R ${covered}</span></div>${bar(covered,total)}<small>${town.reserved} ${t('reservados · traslado','reserved · travel')} ${town.travel} ${t('ciclos','cycles')}</small></article>`;}).join('')}</div><p>${t('La construcción reserva material y trabajo; las entregas reservan tareas. El mismo robot no se cuenta dos veces.','Construction reserves material and work; deliveries reserve tasks. A robot is not counted twice.')}</p>`;
}

export function createRobotUI({kind,surface,world,guide,pause=()=>{},listen=()=>{},onMode=()=>{}}){
 const query=new URLSearchParams(location.search),container=surface.parentElement,keys=new Set(),touch=new Set(),listeners=[];let mode=query.get('mode')==='immersive'?'immersive':'notebook',pose=world?.poseAt?.(kind==='factory'?1:0),entered=false,look=false,hold=false,travel=null,disposed=false,frame,last=performance.now(),raf,wasLocked=false;
 const stylesheet=document.createElement('link');stylesheet.rel='stylesheet';stylesheet.href=new URL('./robot-lab.css',import.meta.url).href;document.head.append(stylesheet);
 const row=document.createElement('section');row.className='robot-modebar';row.innerHTML=`<div><button data-rmode="diagram">2D</button><button data-rmode="notebook">3D</button><button data-rmode="immersive">${t('Entrar y caminar','Enter and walk')} ↗</button></div><label>${t('Instante del modelo','Model instant')}<input type="range" data-rtime min="0" max="1" step=".001" value="0"><output>0</output></label>`;container.before(row);
 const panel=document.createElement('div');panel.className='robot-diagram';panel.hidden=true;container.append(panel);
 const note=document.createElement('p');note.className='robot-replay-note';note.hidden=true;row.after(note);
 const legend=document.createElement('p');legend.className='robot-representation';legend.textContent=kind==='district'?t('H: people · R: robots. Las operaciones ilustran la última hora completa; los almacenes indican cantidades exactas. No seguimos lotes individuales.','H: humans · R: robots. Operations illustrate the last completed hour; stock labels give exact quantities. Individual batches are not tracked.'):kind==='factory'?t('H: people · R: robots. Una maqueta de cinco operaciones; los identificadores enlazan las piezas y el primer relevo.','H: humans · R: robots. A five-operation teaching model; identifiers connect the parts and the first handover.'):t('H: tareas humanas · R: tareas cubiertas. Cada figura puede representar un grupo; las etiquetas muestran la cantidad exacta. Industria y ciudad son poblaciones distintas.','H: human tasks · R: covered tasks. Each figure may represent a group; labels show the exact quantity. Industry and city are separate populations.');note.after(legend);
 const controls=document.createElement('div');controls.className='robot-walk-controls';controls.hidden=true;controls.innerHTML=`<button data-rcapture>${t('Pack ratón','Enable mouse look')}</button><button data-rlisten>${t('Acércate al stand','Approach a stand')}</button><label><input type="checkbox" data-rfollow checked>${t('Guía de cámara','Camera guide')}</label><span>${t('WASD / flechas · E escuchar · Esc pausar','WASD / arrows · E listen · Esc pause')}</span><div class="robot-walkpad"><button data-rmove="w">↑</button><button data-rmove="a">←</button><button data-rmove="s">↓</button><button data-rmove="d">→</button></div>`;container.append(controls);
 const q=selector=>controls.querySelector(selector),canvas=world?.canvas||surface.querySelector('canvas'),listenAt=action=>{travel=null;hold=true;try{listen(action);}finally{hold=false;}},save=()=>guide.save();
 if(canvas)canvas.tabIndex=0;
 if(!world?.setMode||!world?.walk)row.querySelector('[data-rmode="immersive"]').disabled=true;
 function release(){look=false;firstPerson?.release();q('[data-rcapture]').textContent=t('Pack ratón','Enable mouse look');}
 function setMode(next,{saveState=true,pauseProcess=true}={}){if(next==='immersive'&&!world?.walk)next=world?'notebook':'diagram';if(pauseProcess){pause();guide.stop();}keys.clear();touch.clear();travel=null;release();mode=next;surface.hidden=next==='diagram';panel.hidden=next!=='diagram';controls.hidden=next!=='immersive';container.classList.toggle('robot-diagram-mode',next==='diagram');container.classList.toggle('robot-fps-mode',next==='immersive');row.querySelectorAll('[data-rmode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.rmode===mode)));if(next==='immersive'&&!entered){pose=world.poseAt(kind==='factory'?1:0);entered=true;}world?.setMode?.(next);if(pose){world?.setPose?.(pose);const restored=world?.getViewState?.()?.pose;if(restored)pose={...restored};}onMode(next);if(next==='diagram'&&frame)panel.innerHTML=diagram(kind,frame);if(next==='immersive')canvas?.focus({preventScroll:true});if(saveState){history.replaceState(null,'','?mode='+next);save();}}
 function keyToIndex(id){if(kind==='factory'&&/^robot-factory-\d$/.test(id))return +id.split('-').at(-1);if(kind==='city'&&/^city-\d$/.test(id))return +id.split('-').at(-1);if(kind==='region'&&/^region-\d$/.test(id))return +id.split('-').at(-1);if(kind==='region'&&/^region-city-\d$/.test(id))return 6+(+id.split('-').at(-1));return null;}
 const focus=e=>{if(mode!=='immersive'||hold||!q('[data-rfollow]').checked)return;const i=keyToIndex(e.detail);if(i===null)return;const target=world.poseAt(i);travel={path:world.guidePath(pose,target),index:1,target};};document.addEventListener('narration-focus',focus);listeners.push(()=>document.removeEventListener('narration-focus',focus));
 let firstPerson;if(canvas&&world?.setPose)firstPerson=bindFirstPerson({canvas,enabled:()=>mode==='immersive'&&look,onLook(dx,dy){travel=null;pose.yaw-=dx*.0025;pose.pitch=Math.max(-1.25,Math.min(1.25,pose.pitch-dy*.002));world.setPose(pose);save();},onActivate(x,y){if(x===null){const near=world.nearest();if(near)listenAt(near.action??near.index);}else{const hit=world.inspect(x,y);if(Number.isInteger(hit?.action))listenAt(hit.action);}},onState(state){const locked=state==='locked';if(wasLocked&&!locked){pause();guide.stop();look=false;save();}wasLocked=locked;}});
 function capture(){look=true;canvas?.focus({preventScroll:true});firstPerson?.request();q('[data-rcapture]').textContent=t('Ratón activo · Esc','Mouse active · Esc');}
 q('[data-rcapture]').onclick=capture;q('[data-rlisten]').onclick=()=>{const near=world?.nearest?.();if(near)listenAt(near.action??near.index);};
 const canvasClick=e=>{if(mode!=='immersive'||look||e.button!==0)return;const hit=world.inspect(e.clientX,e.clientY);if(Number.isInteger(hit?.action))listenAt(hit.action);capture();save();};canvas?.addEventListener('click',canvasClick);listeners.push(()=>canvas?.removeEventListener('click',canvasClick));
 row.querySelectorAll('[data-rmode]').forEach(b=>b.onclick=()=>setMode(b.dataset.rmode));row.querySelector('[data-rtime]').oninput=e=>{const targetTime=+e.target.value;travel=null;pause();guide.seek(targetTime);};
 for(const b of controls.querySelectorAll('[data-rmove]')){b.onpointerdown=e=>{pause();guide.stop();travel=null;touch.add(b.dataset.rmove);b.setPointerCapture?.(e.pointerId);};b.onpointerup=b.onpointercancel=()=>{touch.delete(b.dataset.rmove);save();};}
 const down=e=>{if(e.key==='Escape'){pause();guide.stop();keys.clear();touch.clear();travel=null;release();save();return;}if(mode!=='immersive'||e.target.matches('input,select,textarea,button,a'))return;const k=e.key.toLowerCase();if(k==='e'){const near=world?.nearest?.();if(near)listenAt(near.action??near.index);return;}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();pause();guide.stop();travel=null;keys.add(k);}},up=e=>{if(keys.delete(e.key.toLowerCase()))save();},blur=()=>{keys.clear();touch.clear();save();};
 for(const [event,fn] of [['keydown',down],['keyup',up],['blur',blur]]){window.addEventListener(event,fn);listeners.push(()=>window.removeEventListener(event,fn));}
 const visibility=()=>{if(document.hidden){keys.clear();touch.clear();travel=null;pause();guide.stop();release();save();}};document.addEventListener('visibilitychange',visibility);listeners.push(()=>document.removeEventListener('visibilitychange',visibility));
 function tick(now){if(disposed)return;const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!document.hidden&&mode==='immersive'&&world){const f=(keys.has('w')||keys.has('arrowup')||touch.has('w')?1:0)-(keys.has('s')||keys.has('arrowdown')||touch.has('s')?1:0),r=(keys.has('d')||keys.has('arrowright')||touch.has('d')?1:0)-(keys.has('a')||keys.has('arrowleft')||touch.has('a')?1:0);if(f||r){const n=Math.hypot(f,r),distance=dt*3.2;pose=world.walk(pose,(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*r)*distance/n,(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*r)*distance/n);}else if(travel&&guide.player?.running){const goal=travel.path[travel.index];if(!goal){pose.yaw=travel.target.yaw;pose.pitch=travel.target.pitch;travel=null;}else{const dx=goal.x-pose.x,dz=goal.z-pose.z,n=Math.hypot(dx,dz);if(n<.05)travel.index++;else{const step=Math.min(n,dt*3.2);pose=world.walk(pose,dx*step/n,dz*step/n);}}}world.setPose(pose);const near=world.nearest();q('[data-rlisten]').disabled=!near;q('[data-rlisten]').textContent=near?'E · '+t('Escuchar stand','Listen to stand')+' '+((near.index??0)+1):t('Acércate al stand','Approach a stand');}raf=requestAnimationFrame(tick);}
 setMode(mode,{saveState:false,pauseProcess:false});raf=requestAnimationFrame(tick);
 return {get mode(){return mode;},get pose(){return pose;},listenAction:listenAt,setMode,
  update(next){frame=next;const id=guide.player?.current?.id,restart=guide.source==='voice'&&guide.trace.windows[id]?.restart;note.hidden=!restart;note.textContent=kind==='factory'?t('Repetición del primer relevo: volvemos al inicio para seguir fabricación, llegada y trabajo.','First-handover replay: we return to the start to follow manufacturing, arrival and work.'):t('Repetición explicada del escenario desde su inicio.','Narrated replay of the scenario from its start.');row.querySelector('[data-rtime]').max=guide.trace.horizon;row.querySelector('[data-rtime]').value=next.time;row.querySelector('output').textContent=number(next.sampledTime??next.time,3)+' '+(kind==='factory'||kind==='district'?t('h','h'):t('ciclos','cycles'));if(mode==='diagram')panel.innerHTML=diagram(kind,next);},
  capture(){return {mode,entered,pose,view:world?.getViewState?.()||world?.getView?.(),follow:q('[data-rfollow]').checked};},
  restore(saved){if(!saved)return;travel=null;entered=saved.entered===true;if(saved.view)world?.restoreViewState?.(saved.view);if(saved.pose)pose={...saved.pose};q('[data-rfollow]').checked=saved.follow!==false;const next=['diagram','notebook','immersive'].includes(query.get('mode'))?query.get('mode'):['diagram','notebook','immersive'].includes(saved.mode)?saved.mode:'notebook';setMode(next,{saveState:false,pauseProcess:false});},
  dispose(){disposed=true;cancelAnimationFrame(raf);release();firstPerson?.dispose();listeners.forEach(remove=>remove());}
 };
}

export function addRobotSources(){if(document.querySelector('.robot-sources'))return;const section=document.createElement('section');section.className='robot-sources';section.innerHTML=`<h2>${t('Qué es real y qué supone este laboratorio','What is real and what this lab assumes')}</h2><p>${t('La inserción de piezas, el atornillado y la inspección son aplicaciones industriales. Los mecanismos dibujados son esquemáticos y no corresponden a una marca o fábrica.','Part insertion, screwdriving and inspection are industrial applications. The drawn mechanisms are schematic and do not represent a brand or factory.')} <a href="https://www.universal-robots.com/applications/" target="_blank" rel="noreferrer">Universal Robots · ${t('aplicaciones','applications')}</a>.</p><p>${t('La definición de robot industrial describe manipuladores reprogramables; no demuestra un humanoide capaz de cualquier trabajo.','The industrial-robot definition describes reprogrammable manipulators; it does not establish a humanoid capable of any job.')} <a href="https://ifr.org/industrial-robots" target="_blank" rel="noreferrer">IFR · ${t('definición','definition')}</a>.</p><p>${t('NIST evalúa capacidades por tareas. Aquí suponemos dominio fiable de las operaciones y, en la hipótesis Total, de las tareas urbanas representadas. Esa delegación futura no es capacidad comercial demostrada ni una previsión de empleo.','NIST evaluates capabilities by task. Here we assume reliable mastery of the operations and, in the Full hypothesis, of the represented urban tasks. That future delegation is not demonstrated commercial capability or an employment forecast.')} <a href="https://www.nist.gov/publications/measuring-and-representing-performance-manufacturing-assembly-robots" target="_blank" rel="noreferrer">NIST · ${t('medidas de desempeño','performance measures')}</a>.</p><p>${t('Los ritmos, horarios, demoras, recetas y costes relativos son supuestos didácticos. Cada escala arranca con su propio estado. El suministro, la maquinaria, la energía y la logística frenan el bucle; no se promete crecimiento exponencial indefinido. El índice de coste es parcial y no suma el coste total de un producto.','Rates, schedules, delays, recipes and relative costs are teaching assumptions. Each scale starts from its own state. Supply, machinery, energy and logistics slow the loop; indefinite exponential growth is not promised. The cost index is partial and does not sum total product cost.')}</p><p>${t('Los objetos y su velocidad no están a escala física. Los contadores siguen los motores originales; los eventos enteros se muestran al completar el paso. La fracción de voz no mide duración real ni alineación por palabra.','Objects and their speed are not at physical scale. Counters follow the original engines; integer events appear when the step completes. The narration fraction measures neither real duration nor word alignment.')}</p>`;document.querySelector('main')?.append(section);}
