// Viewer collision rectangles match the visible hardware, not painted cell boundaries.
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
export const ROBOT_POSITIONS=[[-11,-4],[-2,-4],[7,-4],[7,5],[-2,5]];
export const ROBOT_ROOM=[-19,-13,17,15];
export const ROBOT_STANDS=ROBOT_POSITIONS.map(([x,z],i)=>i===2?[11,1.15,-4]:[x,1.15,z+3.4]);
export const ROBOT_STAND_YAWS=[0,0,Math.PI/2,0,0];
export const ROBOT_BOUNDS=ROBOT_POSITIONS.map(([x,z])=>[x-3.1,0,z-1.7,x+3.1,3.65,z+1.8]);
export const ROBOT_WALLS=[[-19.12,-13.12,17.12,-12.88],[-19.12,14.88,17.12,15.12],[-19.12,-13,-18.88,15],[16.88,-13,17.12,15]];
export const ROBOT_HARDWARE_SOLIDS=[...ROBOT_POSITIONS.flatMap(([x,z])=>[[x-.44,z-.45,x+.44,z+.45],[x-2.1,z-1.2,x-1.1,z-.2],[x+1.1,z-1.2,x+2.1,z-.2]]),[-15.5,12.9,-7.5,13.7],[-4.4,12.2,-3.3,13.4],...Array.from({length:10},(_,i)=>[1.4+i*1.18-.22,13.20,1.4+i*1.18+.22,13.60]),[-15.4,-11.0,-6.6,-9.0]];
export const ROBOT_STAND_SOLIDS=ROBOT_STANDS.map(([x,y,z])=>[x-.24,z-.20,x+.24,z+.20]);
export const ROBOT_SOLIDS=[...ROBOT_WALLS,...ROBOT_HARDWARE_SOLIDS,...ROBOT_STAND_SOLIDS];
const index=n=>Math.floor(clamp(Number(n),0,4));
export const robotCollision=(x,z,r=.24)=>ROBOT_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);
export function robotPoseAt(chapter=0){const i=index(chapter),[x,y,z]=ROBOT_STANDS[i],yaw=ROBOT_STAND_YAWS[i];return {x:x+Math.sin(yaw)*2.1,z:z+Math.cos(yaw)*2.1,yaw,pitch:.04};}
export function restoreRobotPose(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return robotPoseAt(0);const p={x:clamp(saved.x,-18.5,16.5),z:clamp(saved.z,-12.5,14.5),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return robotCollision(p.x,p.z)?robotPoseAt(0):p;}
export function robotWalk(pose,dx,dz){if(typeof dx==='object'){const f=dx.forward||0,s=dx.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=2.5*clamp(dz,0,.05);dx=(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)/n*d;dz=(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)/n*d;}dx=Number.isFinite(dx)?dx:0;dz=Number.isFinite(dz)?dz:0;let p={...pose};const count=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.10));for(let i=0;i<count;i++){const x=clamp(p.x+dx/count,-18.5,16.5),z=clamp(p.z+dz/count,-12.5,14.5);if(!robotCollision(x,p.z))p.x=x;if(!robotCollision(p.x,z))p.z=z;}return p;}
export function robotSegmentClear(a,b,r=.25,solids=ROBOT_SOLIDS){for(const q of solids){let lo=0,hi=1,hit=true;const start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];for(let d=0;d<2;d++){const min=q[d]-r,max=q[d+2]+r;if(Math.abs(delta[d])<1e-12){if(start[d]<=min||start[d]>=max){hit=false;break;}}else{let near=(min-start[d])/delta[d],far=(max-start[d])/delta[d];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>=hi){hit=false;break;}}}if(hit&&hi>0&&lo<1)return false;}return true;}
export function robotNearestStand(pose){let best=null;ROBOT_STANDS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),yaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(yaw-pose.yaw),Math.cos(yaw-pose.yaw))),pitch=Math.atan2(y-1.65,distance);if(distance<2.45&&angle<.85&&Math.abs(pitch-(pose.pitch||0))<.60&&robotSegmentClear(pose,{x,z},0,ROBOT_SOLIDS.filter(b=>b!==ROBOT_STAND_SOLIDS[index]))&&(!best||distance<best.distance))best={index,distance,angle,pitch};});return best;}
let grid;
function navigationGrid(){if(grid)return grid;const step=.35,minX=-18.5,minZ=-12.5,nx=101,nz=78,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*step,z=minZ+zi*step;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!robotCollision(x,z,.25)});}return grid={step,nx,nz,nodes};}
export function robotGuidePath(from,to){const start=restoreRobotPose(from),end=restoreRobotPose(to);if(robotSegmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=navigationGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const v=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&v<d&&robotSegmentClear(p,q)){best=q;d=v;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const open=new Set([first.index]),cost=new Map([[first.index,0]]),previous=new Map(),closed=new Set();let found=false;while(open.size){let current,best=Infinity;for(const id of open){const q=g.nodes[id],v=cost.get(id)+Math.hypot(q.x-last.x,q.z-last.z);if(v<best){best=v;current=q;}}open.delete(current.index);if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!robotSegmentClear(current,q))continue;const v=cost.get(current.index)+g.step*Math.hypot(dx,dz);if(v<(cost.get(q.index)??Infinity)){cost.set(q.index,v);previous.set(q.index,current.index);open.add(q.index);}}}if(!found)return [];const points=[];for(let id=last.index;id!==undefined;id=previous.get(id)){points.push({x:g.nodes[id].x,z:g.nodes[id].z});if(id===first.index)break;}points.reverse();points.unshift({x:start.x,z:start.z});points.push({x:end.x,z:end.z});const result=[points[0]];for(let i=0;i<points.length-1;){let j=points.length-1;while(j>i+1&&!robotSegmentClear(points[i],points[j]))j--;result.push(points[j]);i=j;}return result;}