import * as THREE from '../vendor/three.module.js';
import {TYPES,WORK} from './region-model.js';
export const DISTRICTS=[[-28,-20],[0,-20],[28,-20],[-28,15],[0,15],[28,15]];
export const INDUSTRIES=[[-40,20],[0,20],[40,20],[-40,47],[0,47],[40,47]];
export const TOWNS=[[-44,-25],[0,-40],[44,-25]];
const INDUSTRY_NAMES_EN=['Extraction','Refining','Components','Robot factory','Power','Transport'];
const COLORS=[0x67bcec,0xeeb478,0xd7ca8d,0x82cdb4,0xea9baf,0xb3a7e2];


// A deterministic scene: moving state comes only from the sampled engine clock.
export function createUrbanScene({regional=false,es=true}={}){
 const scene=new THREE.Scene(),roads=[],solids=[],parts={};
 scene.add(new THREE.HemisphereLight(0xccedff,0x283e53,3));const sun=new THREE.DirectionalLight(0xffe8c2,3);sun.position.set(-40,100,60);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-95,right:95,top:95,bottom:-95,near:1,far:250});sun.shadow.normalBias=.15;scene.add(sun);
 const cube=new THREE.BoxGeometry(1,1,1),cone=new THREE.ConeGeometry(1,1,6),cyl=new THREE.CylinderGeometry(1,1,1,12),mats=new Map(),fixed=new THREE.Group();
 function mat(c){if(!mats.has(c))mats.set(c,new THREE.MeshStandardMaterial({color:c,roughness:c===0x375b76?.26:.72,metalness:[0x8ba8b8,0xb6c8cd,0x90a6a8].includes(c)?.48:.08}));return mats.get(c);}
 function box(g,x,y,z,w,h,d,c,geo=cube){const o=new THREE.Mesh(geo,mat(c));o.position.set(x,y,z);o.scale.set(w,h,d);g.add(o);return o;}
 function road(x,z,w,d){roads.push({x,z,width:w,depth:d,bounds:[x-w/2,z-d/2,x+w/2,z+d/2]});box(fixed,x,.16,z,w,.15,d,0x263c51);if(w>d){for(let a=x-w/2+2;a<x+w/2;a+=4)box(fixed,a,.25,z,1.6,.02,.12,0x8ca8b5);}else for(let a=z-d/2+2;a<z+d/2;a+=4)box(fixed,x,.25,a,.12,.02,1.6,0x8ca8b5);}
 function tree(x,z,k){solids.push([x-.42,z-.42,x+.42,z+.42]);box(fixed,x,.9,z,.22,1.7,.22,0x756b54);box(fixed,x,2.1,z,1,2.1,1,[0x437e70,0x539383,0x6da98e][k%3],cone);}
 const size=regional?142:104,depth=regional?132:96;
 box(fixed,0,-1,0,size,2,depth,0x1b344a);box(fixed,0,.01,0,size-.3,.1,depth-.3,0x4e7774);
 const riverX=regional?-66:-47;box(fixed,riverX,.1,0,5,.1,depth-1,0x328fb0);
 for(let z=-depth/2+3;z<depth/2;z+=4)box(fixed,riverX,.19,z,2,.02,.15,0x7dd9e7);
 const centers=regional?INDUSTRIES:DISTRICTS;
 if(regional){road(0,3,139,5);road(0,-19,4,85);road(-44,-10,3,30);road(44,-10,3,30);road(0,33,112,4);road(-20,32,3,65);road(20,32,3,65);}
 else{for(const z of [-36,-3,33])road(0,z,101,4);for(const x of [-14,14])road(x,-2,3,70);road(-40,0,3,70);road(40,0,3,70);}
 if(regional){for(const x of[-44,0,44])road(x,-3.5,3.2,73);for(const x of[-56,-16,24])road(x,33.5,3.0,29);road(-16,20,81,3.0);road(-16,47,81,3.0);}else for(const [x,z]of DISTRICTS)road(x,z+10,x===0?28:24,2.2);
 const structures=[],pickPoints=[],highlights=[],zoneMarkers=[];
 function building(g,x,z,w,d,h,type,k){const center=g.position;solids.push([x+center.x-w/2,z+center.z-d/2,x+center.x+w/2,z+center.z+d/2]);
  box(g,x,h/2+.3,z,w,h,d,[0xb6c8cd,0x8ba8b8,0xd2d9cd][k%3]);box(g,x,h+.4,z,w+.35,.3,d+.35,COLORS[type]);
  for(let y=1.2;y<h;y+=1.4)for(const xx of [-.28,.28])box(g,x+w*xx,y,z+d/2+.025,w*.23,.55,.05,0x375b76);
  box(g,x,.9,z+d/2+.06,.8,1.3,.08,0x243f57);
  if(type===1){box(g,x,1.9,z+d/2+.6,w+.4,.18,1.3,COLORS[type]);}
  if(type===4&&k===0){box(g,x,h+1.15,z,.32,1.25,.3,0xef91a1);box(g,x,h+1.15,z,1.2,.32,.3,0xef91a1);}
  if(type===5&&k===0){box(g,x,h+.9,z,1.8,.7,1,0xdbe5d5);}
 }
 function ring(x,z,w,d){const temporary=new THREE.BoxGeometry(w,.06,d),edges=new THREE.EdgesGeometry(temporary);temporary.dispose();const r=new THREE.LineSegments(edges,new THREE.LineBasicMaterial({color:0x6deed2}));r.position.set(x,.35,z);r.visible=false;scene.add(r);return r;}
 if(!regional){
  DISTRICTS.forEach(([x,z],type)=>{
   box(fixed,x,.2,z,25,.2,28,0x809b94);road(x,z+10,24,2);road(x,z-1,24,2);
   for(let k=0;k<6;k++){const bx=x+(k%3-1)*7.6,bz=z+(k<3?-7:4),g=new THREE.Group();building(g,bx,bz,5.4,5.3,3.4+((k+type)%3)*1.9,type,k);fixed.add(g);pickPoints.push({x:bx,z:bz,type});}
   const led=new THREE.Mesh(new THREE.BoxGeometry(22,.08,1),mat(0x63edd1));led.position.set(x-11,.34,z+13);scene.add(led);zoneMarkers.push({mesh:led,x,z:z+13,width:22});highlights.push(ring(x,z,25.5,28.5));
   for(let k=0;k<3;k++){tree(x-10+k*9,z+12,k);box(fixed,x-8+k*8,.5,z+9,2,.45,.7,0xb99571);}
   if(type===2){box(fixed,x+8,6,z+4,.3,12,.3,0xf1ba64);box(fixed,x+4,12,z+4,10,.25,.3,0xf1ba64);}
  });
  // Arrival terminal and parked delivery van lie outside the neighbourhoods.
  box(fixed,-43,.3,34,10,.3,11,0x9ab0a3);box(fixed,-43,2,39,9,3,3,0x678ea3);box(fixed,-43,3.7,39,9.4,.3,3.5,0x76cbbd);
 }else{
  INDUSTRIES.forEach(([x,z],type)=>{
   box(fixed,x,.15,z,30,.16,21,0x729386);
   for(let slot=0;slot<6;slot++){const bx=x+(slot%3-1)*9,bz=z+(slot<3?-5:5),g=new THREE.Group();g.position.set(bx,.3,bz);scene.add(g);structures.push(g);pickPoints.push({x:bx,z:bz,type});
    box(fixed,bx,.27,bz,8,.08,8,0x8ea69a);
    if(type===0){for(let k=0;k<3;k++)box(g,0,.2+k*.18,0,7-k*1.6,.3,7-k*1.6,[0x857862,0xaa9170,0xd1b387][k]);box(g,2,1,-2,1.3,1.4,1.5,0xe5b877);}
    else if(type===4){for(let k=0;k<4;k++){const panel=box(g,(k%2)*3-1.5,1,Math.floor(k/2)*3-1.5,2.6,.14,2.2,0x2d5378);panel.rotation.x=-.3;box(g,(k%2)*3-1.5,.5,Math.floor(k/2)*3-1.5,.18,1,.2,0xb6cec5);}}
    else{building(g,0,0,6,5,2.5,type,0);if(type===1){box(g,2,3,-1,.5,5,.5,0x90a6a8,cyl);}if(type===3){box(g,0,3.7,0,.8,1.2,.7,0xe4f4e7);box(g,0,4.6,0,.65,.6,.6,0xe4f4e7);}}
    highlights.push(ring(bx,bz,8.4,8.4));
   }
  });
  TOWNS.forEach(([x,z],i)=>{
   box(fixed,x,.18,z,32,.22,28,0x94aaa0);road(x,z,31,2);road(x,z,2,26);
   for(let k=0;k<12;k++){const bx=x+(k%4-1.5)*7,bz=z+(Math.floor(k/4)-1)*8.5;const g=new THREE.Group();building(g,bx,bz,4.6,4.9,3+(k*3+i)%6,(k+i)%6,k);fixed.add(g);}
   const led=new THREE.Mesh(new THREE.BoxGeometry(29,.09,1),mat(0x63edd1));led.position.set(x-14.5,.35,z+15);scene.add(led);zoneMarkers.push({mesh:led,x,z:z+15,width:29});highlights.push(ring(x,z,33,29));
   for(let k=0;k<4;k++)tree(x-12+k*8,z+13,k);
  });
 }
 for(let k=0;k<45;k++){const x=-size/2+7+(k%15)*(size-14)/15,z=k<15?-depth/2+4:k<30?depth/2-4:3;if(k<30||Math.abs(x)>54)tree(x,z,k);}
 // Batch every static building/window/tree by material and geometry.
 fixed.updateMatrixWorld(true);const buckets=new Map();fixed.traverse(o=>{if(!o.isMesh)return;const key=o.geometry.uuid+o.material.uuid;if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(o);});
 for(const parts of buckets.values()){const mesh=new THREE.InstancedMesh(parts[0].geometry,parts[0].material,parts.length);parts.forEach((p,i)=>mesh.setMatrixAt(i,p.matrixWorld));mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);}
 const dynamicRoot=new THREE.Group(),dynamicBuckets=new Map();structures.forEach(g=>{scene.remove(g);dynamicRoot.add(g);});dynamicRoot.updateMatrixWorld(true);dynamicRoot.traverse(o=>{if(!o.isMesh)return;const key=o.geometry.uuid+o.material.uuid;if(!dynamicBuckets.has(key))dynamicBuckets.set(key,[]);dynamicBuckets.get(key).push(o);});const dynamic=[];for(const parts of dynamicBuckets.values()){const mesh=new THREE.InstancedMesh(parts[0].geometry,parts[0].material,parts.length);mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.frustumCulled=false;scene.add(mesh);dynamic.push({mesh,parts});}const zero=new THREE.Matrix4().makeScale(0,0,0);
 const ACTOR_CAPACITY=512,VEHICLE_CAPACITY=1024,actors=new THREE.InstancedMesh(cube,mat(0xffffff),ACTOR_CAPACITY*7),vehicles=new THREE.InstancedMesh(cube,mat(0xffffff),VEHICLE_CAPACITY*7);actors.instanceMatrix.setUsage(THREE.DynamicDrawUsage);vehicles.instanceMatrix.setUsage(THREE.DynamicDrawUsage);actors.castShadow=vehicles.castShadow=true;actors.frustumCulled=vehicles.frustumCulled=false;actors.setColorAt(0,new THREE.Color(0));vehicles.setColorAt(0,new THREE.Color(0));actors.instanceColor.array.fill(0);vehicles.instanceColor.array.fill(0);actors.count=vehicles.count=0;scene.add(actors,vehicles);parts.actors=actors;parts.vehicles=vehicles;parts.roads=roads;parts.structures=structures;parts.markers=zoneMarkers;parts.highlights=highlights;parts.pickPoints=pickPoints;parts.solids=solids;
 if(regional)for(const p of pickPoints)solids.push([p.x-4,p.z-4,p.x+4,p.z+4]);
 const transform=new THREE.Object3D(),tint=new THREE.Color(),recordPool=new Map(),vehiclePool=new Map();let lastState=null,disposed=false;
 const whole=n=>Math.max(0,Math.floor(Number.isFinite(Number(n))?Number(n):0)),clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
 function put(mesh,i,x,y,z,w,h,d,c,yaw=0){transform.position.set(x,y,z);transform.rotation.set(0,yaw,0);transform.scale.set(w,h,d);transform.updateMatrix();mesh.setMatrixAt(i,transform.matrix);mesh.setColorAt(i,tint.set(c));}
 function person(i,x,z,robot,time,scale=1){const c=robot?0xd3e6e3:0xefad74,gait=Math.sin(time*5+i*.61)*.10,p=[[0,.95,0,.4,.55,.3,c],[0,1.4,0,.36,.32,.32,robot?0xdce9e5:0xc9946e],[0,1.4,.17,.28,.08,.045,robot?0x35c7b3:0x583c30],[-.29,.87,gait,.13,.5,.16,c],[.29,.87,-gait,.13,.5,.16,c],[-.13,.36,gait,.16,.6,.2,0x304862],[.13,.36,-gait,.16,.6,.2,0x304862]];p.forEach(([dx,y,dz,w,h,d,color],j)=>put(actors,i*7+j,x+dx*scale,.3+y*scale,z+dz*scale,w*scale,h*scale,d*scale,color));}
 function caption(g,text,x,y,z,width=4){const material=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,depthWrite:false,toneMapped:false}),o=new THREE.Mesh(new THREE.PlaneGeometry(1,1),material);o.position.set(x,y,z);o.scale.set(width,.30,1);o.userData={isLabel:true,text};if(typeof document!=='undefined'&&document.createElement){const canvas=document.createElement('canvas'),ctx=canvas.getContext?.('2d');if(ctx?.fillText){canvas.width=1024;canvas.height=80;ctx.fillStyle='#173d40';ctx.fillRect?.(0,0,1024,80);ctx.font='600 46px system-ui';ctx.fillStyle='#e8fff4';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,40,990);material.map=new THREE.CanvasTexture(canvas);material.map.colorSpace=THREE.SRGBColorSpace;}}g.add(o);return o;}
 const standGroups=[],stands=[];const standCenters=regional?[...INDUSTRIES.map(([x,z])=>[x,z+12.5]),...TOWNS.map(([x,z])=>[x,z+16])]:DISTRICTS.map(([x,z])=>[x,z+15.8]);
 standCenters.forEach(([x,z],zone)=>{const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);box(g,0,.08,0,.65,.16,.60,0x233f46);box(g,0,.70,0,.10,1.3,.10,0x90a6a8);const button=box(g,0,1.28,0,.65,.40,.18,0x92d9be),action=zone<6?zone*6:36+zone-6;button.userData={action,index:zone,zone,kind:regional&&zone>=6?'town':'sector'};caption(g,(es?'ESCUCHAR':'LISTEN')+' · '+String(zone+1).padStart(2,'0'),0,.96,.18,1.5);const title=regional?zone<6?(es?TYPES[zone].name:INDUSTRY_NAMES_EN[zone]):(es?'City ':'City ')+(zone-5):(es?'Barrio ':'District ')+(zone+1);caption(g,title,0,1.77,.18,1.8);standGroups.push(g);stands.push(button);solids.push([x-.34,z-.31,x+.34,z+.31]);});parts.stands=stands;parts.standGroups=standGroups;parts.standCenters=standCenters;
 const pipelineRoutes=regional?[[[-56,20],[-56,33],[-16,33],[-16,20]],[[-16,20],[-16,33],[24,33],[24,20]],[[24,20],[24,33],[-56,33],[-56,47]]]:[];parts.pipelineRoutes=pipelineRoutes;
 function routePoint(path,progress){const lengths=path.slice(1).map((p,i)=>Math.hypot(p[0]-path[i][0],p[1]-path[i][1])),total=lengths.reduce((a,b)=>a+b,0);let d=clamp(progress)*total;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]||i===lengths.length-1){const a=path[i],b=path[i+1],u=lengths[i]?clamp(d/lengths[i]):0;return {position:[a[0]+(b[0]-a[0])*u,.32,a[1]+(b[1]-a[1])*u],yaw:Math.atan2(-(b[1]-a[1]),b[0]-a[0]),segment:i};}d-=lengths[i];}return {position:[path[0][0],.32,path[0][1]],yaw:0,segment:0};}
 function vehicle(index,record,time){const [x,,z]=record.position,yaw=record.yaw,c=record.kind==='supply'?0xd4b88a:0xb4dacb,body=[[0,.60,0,2.5,.55,1.3,c],[.78,1.02,0,.90,.76,1.22,0x497b89],[.90,1.14,0,.50,.30,1.25,0xbedbdc],[-.8,.30,-.67,.40,.40,.13,0x24373b],[.8,.30,-.67,.40,.40,.13,0x24373b],[-.8,.30,.67,.40,.40,.13,0x24373b],[.8,.30,.67,.40,.40,.13,0x24373b]];body.forEach(([dx,y,dz,w,h,d,color],j)=>{const wx=x+Math.cos(yaw)*dx+Math.sin(yaw)*dz,wz=z-Math.sin(yaw)*dx+Math.cos(yaw)*dz;put(vehicles,index*7+j,wx,y,wz,w,h,d,color,yaw);});record.instanceStart=index*7;record.instanceCount=7;}
 function idRanges(assignments,zone,sector,start,end){const ranges=[];for(const a of assignments){if((regional?a.town===zone:a.sector===zone)&&(!regional||a.sector===sector)){const lo=Math.max(start,a.firstTask??0),hi=Math.min(end,(a.firstTask??0)+a.count);if(hi>lo)ranges.push({idStart:a.idStart+lo-(a.firstTask??0),idEnd:a.idStart+hi-(a.firstTask??0),count:hi-lo,assignedAt:a.assignedAt});}}return ranges;}
 function update(state){if(disposed||!state)return;lastState=state;const time=Math.max(0,Number(state.time)||0),group=regional?6:3,identities=state.identities||{},assignments=(identities.assignments||[]).filter(a=>Number(a.assignedAt)<=time+1e-8),populations=[],industrial=[],deliveryRecords=[],flowRecords=[];let actorCount=0,vehicleCount=0;actors.instanceMatrix.array.fill(0);vehicles.instanceMatrix.array.fill(0);actors.instanceColor?.array.fill(0);vehicles.instanceColor?.array.fill(0);
  if(regional)structures.forEach((g,i)=>{const p=state.sites?.[i];g.visible=!!p&&p.status!=='empty';g.scale.y=p?.status==='building'?.12+.88*clamp(p.progress/WORK):1;});dynamicRoot.updateMatrixWorld(true);for(const {mesh,parts:items}of dynamic){items.forEach((p,i)=>{let show=true;for(let a=p;a;a=a.parent)if(!a.visible)show=false;mesh.setMatrixAt(i,show?p.matrixWorld:zero);});mesh.instanceMatrix.needsUpdate=true;}
  for(const record of recordPool.values())record.group.visible=false;
  const groups=regional?(state.towns||[]).map(t=>({tasks:t.tasks||[],assigned:t.assigned||[]})):(state.cityTasks||[80,120,100,80,100,120]).map((n,i)=>({tasks:[n],assigned:[state.cityAssigned?.[i]||0]}));
  groups.forEach((g,zone)=>{const [cx,cz]=(regional?TOWNS:DISTRICTS)[zone],total=g.tasks.reduce((a,n)=>a+whole(n),0),robotTotal=g.assigned.reduce((a,n,i)=>a+Math.min(whole(n),whole(g.tasks[i])),0),marker=zoneMarkers[zone],ratio=total?robotTotal/total:0;if(marker){marker.mesh.scale.x=Math.max(.001,ratio);marker.mesh.position.x=cx-marker.width*(1-ratio)/2;marker.mesh.userData={tasks:total,robots:robotTotal,humans:total-robotTotal,ratio};}let bucketOrdinal=0;
   g.tasks.forEach((rawTasks,sector)=>{const tasks=whole(rawTasks),assigned=Math.min(tasks,whole(g.assigned[sector]));for(let start=0;start<tasks;start+=group){const end=Math.min(tasks,start+group),robotEnd=Math.min(end,Math.max(start,assigned)),portions=[['robot',start,robotEnd],['human',Math.max(start,assigned),end]],anchor=[cx+(bucketOrdinal%4-1.5)*(regional?6.4:5.6),cz+(regional?(Math.floor(bucketOrdinal/4)%3-1)*8.5+3.6:[-2,8,12.5][Math.floor(bucketOrdinal/4)%3])];for(const [kind,lo,hi]of portions){if(hi<=lo)continue;const id=`${regional?'town':'district'}-${zone}-sector-${sector}-task-${start}-${kind}`;let r=recordPool.get(id);if(!r){r={id,group:new THREE.Group()};recordPool.set(id,r);}const mixed=robotEnd>start&&robotEnd<end,offset=mixed?(kind==='robot'?-.42:.42):0,x=anchor[0]+offset+Math.sin(time*.35+bucketOrdinal*1.73)*.16,z=anchor[1]+Math.cos(time*.35+bucketOrdinal*1.73)*.12;r.group.visible=true;r.group.position.set(x,.3,z);Object.assign(r,{kind,zone,sector,taskStart:lo,taskEnd:hi,representedCount:hi-lo,mixed,position:[x,.3,z],instanceStart:actorCount*7,instanceCount:7,identityScope:'task slots; not whole professions',robotRanges:kind==='robot'?idRanges(assignments,zone,sector,lo,hi):[]});r.group.userData={id,kind,zone,sector,taskStart:lo,taskEnd:hi,representedCount:hi-lo,mixed,robotRanges:r.robotRanges};person(actorCount++,x,z,kind==='robot',time,regional?.82:1.1);populations.push(r);}bucketOrdinal++;}});
  });
  if(regional){const fleet=whole(state.fleet),working=Math.min(fleet,whole(state.working??24)),builders=Math.min(fleet-working,whole(state.builders)),segments=[['working',working,36],['building',builders,18],['idle',fleet-working-builders,18]],open=pickPoints.filter((_,i)=>state.sites?.[i]?.status==='open'),projects=pickPoints.filter((_,i)=>state.sites?.[i]?.status==='building');let first=0;for(const [status,count,maxFigures]of segments){const n=Math.min(maxFigures,count);for(let k=0;k<n;k++){const lo=first+Math.floor(k*count/n),hi=first+Math.floor((k+1)*count/n),place=status==='building'?projects[k%Math.max(1,projects.length)]:open[k%Math.max(1,open.length)],base=place?[place.x,place.z+3.3]:[-62+k%6*1.5,55+Math.floor(k/6)*1.5],x=base[0]+Math.sin(time*.6+k)*.28,z=base[1];const id='industrial-'+status+'-'+k;let r=recordPool.get(id);if(!r){r={id,group:new THREE.Group()};recordPool.set(id,r);}r.group.visible=true;r.group.position.set(x,.3,z);Object.assign(r,{kind:'robot',status,idStart:lo,idEnd:hi,representedCount:hi-lo,rangeScope:'industrial workforce positions',position:[x,.3,z],instanceStart:actorCount*7,instanceCount:7});r.group.userData={id,status,idStart:lo,idEnd:hi,representedCount:hi-lo,rangeScope:r.rangeScope};person(actorCount++,x,z,true,time,.80);industrial.push(r);}first+=count;}}
  const rawShipments=identities.shipments||state.shipments||state.pending||[];let ordinal=0;for(let k=0;k<rawShipments.length;k++){const item=rawShipments[k],count=whole(item.count??(Number.isFinite(item.idStart)&&Number.isFinite(item.idEnd)?item.idEnd-item.idStart:1)),depart=Number.isFinite(item.depart)?item.depart:Number(item.ready)-1,ready=Number(item.ready);if(!count||!Number.isFinite(ready)||depart>time+1e-8||ready<=time+1e-8){ordinal+=count;continue;}const ordinalMatch=String(item.id||'').match(/^export-(\d+)$/),firstId=Number.isFinite(item.idStart)?item.idStart:ordinalMatch?Number(ordinalMatch[1]):ordinal;const town=whole(item.town),path=regional?[[-56,47],[-56,33],[TOWNS[town]?.[0]??0,33],[TOWNS[town]?.[0]??0,(TOWNS[town]?.[1]??0)+15]]:[[-49,33],[-43,33]],progress=clamp((time-depart)/Math.max(1e-9,ready-depart)),at=routePoint(path,progress),id=item.id||`shipment-${town}-${depart}-${ready}-${k}`;let r=vehiclePool.get(id);if(!r){r={id};vehiclePool.set(id,r);}Object.assign(r,{kind:'delivery',town,depart,ready,progress,representedCount:count,idStart:firstId,idEnd:Number.isFinite(item.idEnd)?item.idEnd:firstId+count,path,position:at.position,yaw:at.yaw,assignmentRule:'engine assigns task only at arrival; destination is delivery hub'});if(vehicleCount>=VEHICLE_CAPACITY)throw Error('Urban renderer shipment capacity exceeded');vehicle(vehicleCount++,r,time);deliveryRecords.push(r);ordinal+=count;}
  if(regional)for(let i=0;i<3;i++){const rate=Number(state.flow?.[i])||0;if(!(rate>0)||!(time>0))continue;const path=pipelineRoutes[i],progress=(time/6+i/3)%1,at=routePoint(path,progress),r={id:'supply-flow-'+i,kind:'supply',sourceType:i,destinationType:i+1,rate,progress,path,position:at.position,yaw:at.yaw,countsAsObject:false,representativeCycle:true};vehicle(vehicleCount++,r,time);flowRecords.push(r);}
  if(actorCount>ACTOR_CAPACITY)throw Error('Urban renderer task figure capacity exceeded');actors.boundingSphere=vehicles.boundingSphere=null;actors.boundingBox=vehicles.boundingBox=null;actors.count=actorCount*7;actors.instanceMatrix.needsUpdate=true;if(actors.instanceColor)actors.instanceColor.needsUpdate=true;vehicles.count=vehicleCount*7;vehicles.instanceMatrix.needsUpdate=true;if(vehicles.instanceColor)vehicles.instanceColor.needsUpdate=true;Object.assign(parts,{populations,industrial,shipments:deliveryRecords,flows:flowRecords,time,representations:[...populations,...industrial],totals:{tasks:populations.reduce((n,r)=>n+r.representedCount,0),robots:populations.filter(r=>r.kind==='robot').reduce((n,r)=>n+r.representedCount,0),humans:populations.filter(r=>r.kind==='human').reduce((n,r)=>n+r.representedCount,0),industrial:industrial.reduce((n,r)=>n+r.representedCount,0),inTransit:deliveryRecords.reduce((n,r)=>n+r.representedCount,0)}});scene.updateMatrixWorld(true);return group;
 }
 const resources=[],resourceSet=new Set(),own=r=>{if(r&&!resourceSet.has(r)){resourceSet.add(r);resources.push(r);}};for(const root of[scene,fixed,dynamicRoot])root.traverse(o=>{if(o.isInstancedMesh)own(o);own(o.geometry);for(const m of(Array.isArray(o.material)?o.material:[o.material])){if(m){own(m);own(m.map);}}});own(sun.shadow);scene.updateMatrixWorld(true);
 const bounds=[-size/2,-1,-depth/2,size/2,15,depth/2];return {scene,parts,stands,targets:stands,centers,pickPoints,highlights,bounds,solids,roads,resources,regional,update,applyFrame:update,get state(){return lastState;},dispose(){if(disposed)return;disposed=true;for(const r of resources)r.dispose?.();recordPool.clear();vehiclePool.clear();}};
}
export function urbanPoseAt(index=0,regional=false){const centers=regional?[...INDUSTRIES.map(([x,z])=>[x,z+12.5]),...TOWNS.map(([x,z])=>[x,z+16])]:DISTRICTS.map(([x,z])=>[x,z+15.8]),i=Math.max(0,Math.min(centers.length-1,Math.floor(Number(index)||0))),[x,z]=centers[i];return {x,z:z+2.2,yaw:0,pitch:.04};}
export function createUrbanNavigator(built){const solids=built.solids,[xmin,,zmin,xmax,,zmax]=built.bounds,radius=.40;let grid;
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a)),collision=(x,z,r=radius)=>solids.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]),poseAt=i=>urbanPoseAt(i,built.regional);
 function restore(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return poseAt(0);const p={x:clamp(saved.x,xmin+.7,xmax-.7),z:clamp(saved.z,zmin+.7,zmax-.7),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return collision(p.x,p.z)?poseAt(0):p;}
 function walk(pose,dx,dz){if(typeof dx==='object'){const f=dx.forward||0,s=dx.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=3.2*clamp(dz,0,.05);dx=(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)*d/n;dz=(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)*d/n;}dx=Number.isFinite(dx)?dx:0;dz=Number.isFinite(dz)?dz:0;const p={...pose},steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.16));for(let i=0;i<steps;i++){const x=clamp(p.x+dx/steps,xmin+.7,xmax-.7),z=clamp(p.z+dz/steps,zmin+.7,zmax-.7);if(!collision(x,p.z))p.x=x;if(!collision(p.x,z))p.z=z;}return p;}
 // Exact segment/expanded-rectangle clearance avoids long sampled searches.
 function segmentClear(a,b,r=radius,skip=-1){const dx=b.x-a.x,dz=b.z-a.z;for(let j=0;j<solids.length;j++){if(j===skip)continue;const box=solids[j],minx=box[0]-r+1e-9,maxx=box[2]+r-1e-9,minz=box[1]-r+1e-9,maxz=box[3]+r-1e-9;let lo=0,hi=1;if(Math.abs(dx)<1e-12){if(a.x<=minx||a.x>=maxx)continue;}else{const q=(minx-a.x)/dx,w=(maxx-a.x)/dx;lo=Math.max(lo,Math.min(q,w));hi=Math.min(hi,Math.max(q,w));if(lo>hi)continue;}if(Math.abs(dz)<1e-12){if(a.z<=minz||a.z>=maxz)continue;}else{const q=(minz-a.z)/dz,w=(maxz-a.z)/dz;lo=Math.max(lo,Math.min(q,w));hi=Math.min(hi,Math.max(q,w));if(lo>hi)continue;}return false;}return true;}

 function nearest(pose){let best=null;built.parts.standCenters.forEach(([x,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),yaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(yaw-pose.yaw),Math.cos(yaw-pose.yaw))),pitch=Math.atan2(1.28-1.7,distance),skip=solids.length-built.stands.length+index;if(distance<3.1&&angle<.80&&Math.abs(pitch-pose.pitch)<.65&&segmentClear(pose,{x,z},0,skip)&&(!best||distance<best.distance))best={index,action:built.stands[index].userData.action,distance};});return best;}
 function guidePath(from,to){const start=restore(from),end=restore(to);if(segmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];if(!grid){const step=1.25,nx=Math.floor((xmax-xmin-1.4)/step)+1,nz=Math.floor((zmax-zmin-1.4)/step)+1,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=xmin+.7+xi*step,z=zmin+.7+zi*step;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!collision(x,z,.44)});}grid={step,nx,nz,nodes};}const g=grid,nearestNode=p=>g.nodes.filter(q=>q.open).map(q=>({q,d:(q.x-p.x)**2+(q.z-p.z)**2})).sort((a,b)=>a.d-b.d).find(({q})=>segmentClear(p,q))?.q,first=nearestNode(start),last=nearestNode(end);if(!first||!last)return [];const heap=[],closed=new Set(),cost=new Map([[first.index,0]]),prior=new Map();
 const push=(id,value)=>{let i=heap.length;heap.push({id,value});while(i){const p=(i-1)>>1;if(heap[p].value<=value)break;heap[i]=heap[p];i=p;}heap[i]={id,value};};
 const pop=()=>{const first=heap[0],last=heap.pop();if(heap.length){let i=0;while(true){let c=i*2+1;if(c>=heap.length)break;if(c+1<heap.length&&heap[c+1].value<heap[c].value)c++;if(heap[c].value>=last.value)break;heap[i]=heap[c];i=c;}heap[i]=last;}return first;};
 push(first.index,Math.hypot(first.x-last.x,first.z-last.z));let found=false;while(heap.length){const current=g.nodes[pop().id];if(closed.has(current.index))continue;if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!segmentClear(current,q))continue;const value=cost.get(current.index)+g.step*Math.hypot(dx,dz);if(value<(cost.get(q.index)??Infinity)){cost.set(q.index,value);prior.set(q.index,current.index);push(q.index,value+Math.hypot(q.x-last.x,q.z-last.z));}}}
 if(!found)return [];const points=[];for(let id=last.index;id!==undefined;id=prior.get(id)){points.push({x:g.nodes[id].x,z:g.nodes[id].z});if(id===first.index)break;}points.reverse();points.unshift({x:start.x,z:start.z});points.push({x:end.x,z:end.z});const out=[points[0]];for(let i=0;i<points.length-1;){let j=points.length-1;while(j>i+1&&!segmentClear(points[i],points[j]))j--;out.push(points[j]);i=j;}return out;}
 return {poseAt,restore,walk,guidePath,nearest,collision,segmentClear};
}
export function urbanFraming(built,view={},aspect=1){const target=new THREE.Vector3(Number(view.x)||0,0,Number(view.z)||0),position=target.clone().add(new THREE.Vector3(100,130,135)),camera=new THREE.OrthographicCamera(-1,1,1,-1,.1,500);camera.position.copy(position);camera.lookAt(target);camera.updateMatrixWorld(true);const b=built.bounds;let half=2;for(const x of[b[0],b[3]])for(const y of[b[1],b[4]])for(const z of[b[2],b[5]]){const p=new THREE.Vector3(x,y,z).applyMatrix4(camera.matrixWorldInverse);half=Math.max(half,Math.abs(p.y),Math.abs(p.x)/Math.max(.1,aspect));}half=half*1.04/THREE.MathUtils.clamp(Number(view.zoom)||1,.7,4);return {target,position,half,left:-half*aspect,right:half*aspect,top:half,bottom:-half};}
export function createUrbanWorld(container,{regional=false,es=true,onListen=()=>{},onInfo=()=>{}}={}){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.setClearColor(0x152c37,1);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.append(renderer.domElement);const built=createUrbanScene({regional,es}),canvas=renderer.domElement,mapCamera=new THREE.OrthographicCamera(-70,70,55,-55,.1,500),fpsCamera=new THREE.PerspectiveCamera(80,1,.07,500),navigator=createUrbanNavigator(built),ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();let view={x:0,z:0,zoom:1,selection:-1},mode='notebook',pose=navigator.poseAt(0),state,disposed=false;canvas.tabIndex=0;
 const activeCamera=()=>mode==='immersive'?fpsCamera:mapCamera;
 function cameraUpdate(){const width=Math.max(1,container.clientWidth),height=Math.max(1,container.clientHeight),aspect=width/height,f=urbanFraming(built,view,aspect);Object.assign(mapCamera,{left:f.left,right:f.right,top:f.top,bottom:f.bottom});mapCamera.position.copy(f.position);mapCamera.lookAt(f.target);mapCamera.updateProjectionMatrix();mapCamera.updateMatrixWorld(true);fpsCamera.aspect=aspect;fpsCamera.position.set(pose.x,1.7,pose.z);fpsCamera.rotation.set(pose.pitch,pose.yaw,0,'YXZ');fpsCamera.updateProjectionMatrix();fpsCamera.updateMatrixWorld(true);}
 function draw(){if(disposed)return;cameraUpdate();built.parts.standGroups.forEach(g=>g.visible=mode==='immersive');renderer.render(built.scene,activeCamera());}
 function resize(){renderer.setSize(Math.max(1,container.clientWidth),Math.max(1,container.clientHeight),false);draw();}const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):{observe(){},disconnect(){}};observer.observe(container);resize();
 function select(i,focus=true){view.selection=Number.isInteger(i)?i:-1;built.highlights.forEach((r,k)=>r.visible=k===(regional?view.selection:Math.floor(view.selection/6)));if(i>=0&&focus){const p=regional?(i>=36?{x:TOWNS[i-36]?.[0],z:TOWNS[i-36]?.[1]}:built.pickPoints[i]):{x:DISTRICTS[Math.floor(i/6)]?.[0],z:DISTRICTS[Math.floor(i/6)]?.[1]};if(Number.isFinite(p?.x)&&Number.isFinite(p?.z)){view.x=p.x;view.z=p.z;view.zoom=container.clientWidth<700?2.8:2.1;}}draw();}
 function setView(value={}){view={x:Number.isFinite(value.x)?value.x:0,z:Number.isFinite(value.z)?value.z:0,zoom:THREE.MathUtils.clamp(Number(value.zoom)||1,.7,4),selection:Number.isInteger(value.selection)?value.selection:-1};select(view.selection,false);}
 function inspect(x,y){const rect=canvas.getBoundingClientRect?.()||container.getBoundingClientRect(),pointer=new THREE.Vector2((x-rect.left)/Math.max(1,rect.width)*2-1,1-(y-rect.top)/Math.max(1,rect.height)*2);ray.setFromCamera(pointer,activeCamera());for(const h of ray.intersectObjects(built.scene.children,true)){let visible=true;for(let a=h.object;a;a=a.parent)if(!a.visible)visible=false;if(!visible||h.object.userData.isLabel||h.object.isSprite)continue;if(Number.isInteger(h.object.userData.action))return {...h.object.userData,object:h.object,distance:h.distance};if(h.object.userData.info)return {info:h.object.userData.info,object:h.object,distance:h.distance};if(h.object.isMesh&&(!h.object.material?.transparent||h.object.material.opacity>.5))return null;}return null;}
 function activate(){const stand=navigator.nearest(pose);if(!stand)return false;onListen(stand.action,stand);return true;}
 function projectPoint(x,z){cameraUpdate();const p=new THREE.Vector3(x,2,z).project(activeCamera());return {x:(p.x+1)*container.clientWidth/2,y:(1-p.y)*container.clientHeight/2};}
 return {canvas,dom:canvas,built,scene:built.scene,get camera(){return activeCamera();},get pose(){return {...pose};},get mode(){return mode;},poseAt:navigator.poseAt,walk:navigator.walk,guidePath:navigator.guidePath,nearest(){return navigator.nearest(pose);},setPose(value){pose=navigator.restore(value);draw();},getPose(){return {...pose};},setMode(value){mode=value==='immersive'?'immersive':'notebook';draw();},inspect,activate,select,getView(){return {...view};},setView,getViewState(){return {view:{...view},mode,pose:{...pose}};},restoreViewState(saved={}){setView(saved.view||saved);mode=saved.mode==='immersive'?'immersive':'notebook';pose=navigator.restore(saved.pose);draw();return true;},fit(){view={...view,x:0,z:0,zoom:1};draw();},focus(index){select(regional?index<6?index*6:36+index-6:index*6,true);},zoomBy(f){view.zoom=THREE.MathUtils.clamp(view.zoom*f,.7,4);draw();},pan(dx,dy){const u=(mapCamera.top-mapCamera.bottom)/Math.max(1,container.clientHeight);view.x=THREE.MathUtils.clamp(view.x-dx*u*.8-dy*u*.8,-75,75);view.z=THREE.MathUtils.clamp(view.z+dx*u*.6-dy*u,-65,65);draw();},pick(x,y){const r=container.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((x-r.left)/Math.max(1,r.width)*2-1,1-(y-r.top)/Math.max(1,r.height)*2),activeCamera());if(!ray.ray.intersectPlane(plane,hit))return -1;if(regional){const town=TOWNS.findIndex(([x,z])=>Math.abs(x-hit.x)<16&&Math.abs(z-hit.z)<14);if(town>=0)return 36+town;}return built.pickPoints.findIndex(p=>Math.abs(p.x-hit.x)<4&&Math.abs(p.z-hit.z)<4);},project(i){return projectPoint(built.centers[i][0],built.centers[i][1]-(regional?12:15));},projectTown(i){return projectPoint(TOWNS[i][0],TOWNS[i][1]-16);},render(value,motion){state=value;const group=built.update(value);if(container.clientWidth>0&&container.clientHeight>0)draw();return group??(regional?6:3);},getPopulationTable(){return built.parts.representations?.map(({id,kind,status,zone,sector,representedCount,idStart,idEnd,taskStart,taskEnd,robotRanges})=>({id,kind,status,zone,sector,representedCount,idStart,idEnd,taskStart,taskEnd,robotRanges}))||[];},stats(){return {resources:built.resources.length,figures:built.parts.actors.count/7,vehicles:built.parts.vehicles.count/7};},dispose(){if(disposed)return;disposed=true;observer.disconnect?.();built.dispose();renderer.dispose?.();canvas.remove?.();}};
}
