import {TimelineClock,restoredPosition} from './timeline.js';
const format=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
export class NotebookPlayer {
 constructor({id,language=document.documentElement.lang==='es'?'es':'en',getClips,onSync=()=>{},capture=()=>null,restore=()=>{},onLanguage=()=>{},autoplay=true}){
  Object.assign(this,{id,language,getClips,onSync,capture,restore,onLanguage});this.key='atlas-notebook-v2:'+id;this.wanted=autoplay;this.suspended=false;this.lastSave=0;
  let saved;try{saved=JSON.parse(localStorage.getItem(this.key));}catch{}if(saved&&saved.version===2){this.lastSavedPayload=JSON.stringify(saved);if(['es','en'].includes(saved.language))this.language=saved.language;this.wanted=saved.playing!==false;try{restore(saved.extra);}catch{}}
  const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b;this.t=t;
  if(!document.querySelector('[data-atlas-player-css]')){const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./player.css',import.meta.url);css.dataset.atlasPlayerCss='';document.head.append(css);}
  this.root=document.createElement('section');this.root.className='atlas-player';this.root.setAttribute('aria-label',t('Reproductor del cuaderno','Notebook player'));
  this.root.innerHTML=`<div class="ap-transcript" hidden><div><strong></strong><button type="button" data-ap="close" aria-label="${t('Cerrar texto','Close transcript')}">×</button></div><p></p></div><div class="ap-timeline"><div class="ap-marks"></div><div class="ap-track"><i></i><input data-ap="seek" type="range" min="0" step="0.05" value="0" aria-label="${t('Tiempo de la explicación','Explanation timeline')}"></div></div><div class="ap-bar"><button type="button" data-ap="play" class="ap-play">▶</button><button type="button" data-ap="back" class="ap-skip" aria-label="${t('Retroceder 10 segundos','Back 10 seconds')}">−10</button><div class="ap-heading"><strong></strong><span role="status"></span></div><output class="ap-time"></output><button type="button" data-ap="scene">${t('Escena','Scene')}</button><button type="button" data-ap="text" aria-expanded="false">${t('Texto','Transcript')}</button><select data-ap="language" aria-label="${t('Idioma de voz','Voice language')}"><option value="es">ES</option><option value="en">EN</option></select><button type="button" data-ap="restart" aria-label="${t('Volver al principio','Restart from beginning')}" title="${t('Volver al principio','Restart from beginning')}">↺</button></div>`;
  document.body.append(this.root);document.body.classList.add('has-atlas-player');this.el=name=>this.root.querySelector(`[data-ap="${name}"]`);
  this.clock=new TimelineClock({clips:getClips(this.language),onSync:s=>{this.paint(s);onSync(s);},onState:()=>{if(this.clock)this.paint(this.clock.current);}});
  this.marks();onLanguage(this.language);this.el('language').value=this.language;
  this.el('play').onclick=()=>this.toggle();this.el('back').onclick=()=>this.seek(this.clock.position-10);this.el('restart').onclick=()=>this.seek(0);
  this.el('seek').oninput=e=>this.seek(+e.target.value);
  this.el('text').onclick=()=>{const p=this.root.querySelector('.ap-transcript');p.hidden=!p.hidden;this.el('text').setAttribute('aria-expanded',String(!p.hidden));};this.el('close').onclick=()=>{this.root.querySelector('.ap-transcript').hidden=true;this.el('text').setAttribute('aria-expanded','false');};
  this.el('scene').onclick=()=>document.querySelector('.lab,.visual,.stage,#machine,canvas')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  this.el('language').onchange=e=>this.changeLanguage(e.target.value);
  this.resize=new ResizeObserver(()=>{document.documentElement.style.setProperty('--atlas-player-height',this.root.offsetHeight+'px');});this.resize.observe(this.root);
  document.addEventListener('visibilitychange',()=>{if(document.hidden){this.save();this.suspended=true;this.clock.pause();}else{this.suspended=false;if(this.wanted)this.clock.play();}});
  window.addEventListener('pagehide',()=>{this.save();this.clock.pause();});
  this.clock.seek(restoredPosition(saved,this.clock.timeline),this.wanted);
  let last=performance.now();const frame=now=>{if(this.disposed)return;const dt=(now-last)/1000;last=now;if(!document.hidden){this.clock.tick(dt);if(now-this.lastSave>800){this.save();this.lastSave=now;}}requestAnimationFrame(frame);};requestAnimationFrame(frame);
 }
 marks(){const marks=this.root.querySelector('.ap-marks');marks.replaceChildren();for(const c of this.clock.timeline){const b=document.createElement('button');b.type='button';b.title=`${format(c.start)} · ${c.title||c.id}`;b.setAttribute('aria-label',b.title);b.style.left=`${c.start/this.clock.total*100}%`;b.textContent=this.clock.timeline.length<=20||c.index%5===0?String(c.index+1).padStart(2,'0'):'';b.onclick=()=>this.seek(c.start);marks.append(b);}this.el('seek').max=this.clock.total;}
 paint(s){if(!s)return;const c=this.clock,state=c.state;this.el('seek').value=c.position;this.el('seek').setAttribute('aria-valuetext',`${format(c.position)} · ${s.title||s.id}`);this.root.querySelector('.ap-track i').style.width=c.position/c.total*100+'%';this.root.querySelector('.ap-heading strong').textContent=`${s.index+1} / ${c.timeline.length} · ${s.title||s.id}`;this.root.querySelector('.ap-heading span').textContent=({loading:this.t('Cargando voz…','Loading voice…'),playing:this.t('MiniMax · voz y escena sincronizadas','MiniMax · voice and scene synchronized'),gap:this.t('Observa · continúa en unos segundos','Observe · continuing in a few seconds'),blocked:this.t('Pulsa ▶ para activar el sonido y continuar aquí','Press ▶ to enable sound and continue here'),error:this.t('Audio no disponible · pulsa ▶ para reintentar','Audio unavailable · press ▶ to retry'),paused:this.t('En pausa · tu posición se guarda','Paused · your position is saved'),finished:this.t('Recorrido completado · puedes volver a cualquier etapa','Journey complete · revisit any chapter')})[state]||'';
  this.el('play').textContent=c.running?'Ⅱ':'▶';this.el('play').setAttribute('aria-label',c.running?this.t('Pausar explicación','Pause explanation'):this.t('Reproducir explicación','Play explanation'));this.root.querySelector('.ap-time').textContent=`${format(c.position)} / ${format(c.total)}`;
  const text=this.root.querySelector('.ap-transcript p');if(text.textContent!==s.text){text.textContent=s.text||'';text.lang=this.language;this.root.querySelector('.ap-transcript strong').textContent=s.title||s.id;}
  this.root.querySelectorAll('.ap-marks button').forEach((b,i)=>b.setAttribute('aria-current',i===s.index?'step':'false'));
 }
 get running(){return this.clock.running;}
 get current(){return this.clock.current;}
 seek(seconds,play=this.wanted){this.wanted=play;this.clock.seek(seconds,play);this.save();}
 stage(index,play=this.wanted){this.seek(this.clock.timeline[Math.max(0,Math.min(this.clock.timeline.length-1,index))].start,play);}
 toggle(){if(this.running)this.pause();else{this.wanted=true;this.clock.play();this.save();}}
 pause(){this.wanted=false;this.clock.pause();this.save();}
 save(){const c=this.clock.current;if(!c)return;try{const payload=JSON.stringify({version:2,language:this.language,chapter:c.id,offset:this.clock.position-c.start,playing:this.wanted,extra:this.capture()});if(payload===this.lastSavedPayload)return;localStorage.setItem(this.key,payload);this.lastSavedPayload=payload;}catch{}}
 changeLanguage(language){const c=this.current,progress=c.progress,index=c.index;this.clock.dispose();this.language=language;this.onLanguage(language);this.clock=new TimelineClock({clips:this.getClips(language),onSync:s=>{this.paint(s);this.onSync(s);},onState:()=>this.paint(this.current)});this.marks();this.el('language').value=language;const next=this.clock.timeline[index]||this.clock.timeline[0];this.seek(next.start+progress*next.duration);}
 rebuild(){this.clock.dispose();this.clock=new TimelineClock({clips:this.getClips(this.language),onSync:s=>{this.paint(s);this.onSync(s);},onState:()=>this.paint(this.current)});this.marks();this.seek(0,false);}
 dispose(){this.save();this.disposed=true;this.clock.dispose();this.resize.disconnect();this.root.remove();document.body.classList.remove('has-atlas-player');}
}
