import {makeFlightTrace,flightFrameAt} from './model.js';
import {createSpaceWorld} from './world.js';
import {NotebookPlayer} from '../playback/player.js';
import {VOICES} from './voices.js';
import {NARRATION_CHAPTERS,narrationTime,narrationProgress} from './guide.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),nf=new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:1});
const clean=p=>({vehicle:p?.vehicle==='starship'?'starship':'falcon',recovery:['droneship','rtls','expendable'].includes(p?.recovery)?p.recovery:'droneship'});
let params=clean(),time=0,chapter=0,timeSource='narration',playing=false,speed=1,trace=makeFlightTrace(params),frame=flightFrameAt(trace,0),world,notebook,ready=false,restored=false,changingVoice=false,keepCamera=false,last=performance.now(),elapsed=0;
const titles=VOICES[es?'es':'en'].map(c=>c.title),offset=()=>params.vehicle==='starship'?4:0;
const profileName=()=>params.vehicle==='starship'?t('Retorno y captura · esquema de pruebas','Return and catch · test scheme'):({droneship:t('Barcaza mar adentro','Downrange droneship'),rtls:t('Regreso a costa','Return to coast'),expendable:t('Sin recuperar booster','Booster expendable')})[params.recovery];
const summaries=[['Dos etapas propulsoras, nueve Merlin abajo y uno de vacío arriba. La cofia protege el satélite; sus dos mitades son piezas diferentes de las etapas.','Two powered stages: nine Merlins below and one vacuum engine above. Two fairing halves protect the satellite and are separate from the stages.'],['Los motores inferiores se apagan antes de separar. La etapa superior enciende su propio motor; la cofia se abre después. El booster toma otra trayectoria.','Lower engines shut down before separation. The upper stage starts its own engine; fairing halves open afterwards. The booster takes a different path.'],['Barcaza: regresar mar adentro. Costa: cambiar antes la trayectoria con boostback. Los motores se apagan entre maniobras; las patas llegan al destino.','Droneship: return downrange. Coast: change the path earlier using boostback. Engines are off between manoeuvres; legs reach the destination.'],['La carga se libera después de cortar el empuje superior. Un booster recuperado todavía exige inspección y preparación para volver a lanzar.','Payload is released after upper-stage thrust shuts down. A recovered booster still needs inspection and preparation before reflight.'],['Referencia publicada: 124 m, booster de 72 m y nave de 52 m. Treinta y tres motores abajo y seis arriba; sin cofia separable ni patas en el booster.','Published reference: 124 m, a 72 m booster and 52 m ship. Thirty-three engines below and six above; no detachable fairing or booster landing legs.'],['La nave enciende antes de separar: hot staging. El booster conserva un subconjunto de motores durante la transición y cambia su trayectoria para volver.','The ship ignites before separation: hot staging. A booster engine subset remains active during the transition, then changes its path to return.'],['Los brazos reciben los apoyos del booster cerca de su extremo superior. Empuje apagado al contacto. Capturar el booster no equivale a recuperar toda la nave.','Arms receive booster support points near its upper end. Thrust shuts down at contact. Catching the booster does not recover the entire ship.'],['Escudo y alerones durante la entrada, cambio de orientación y encendido final. El amerizaje del esquema no cuenta como una nave disponible para reutilizar.','Heat shield and flaps during entry, an orientation change and a final burn. A schematic splashdown does not count as a ship available for reuse.']];
document.title=t('SpaceX · Un lanzamiento, dos trayectorias','SpaceX · One launch, two paths');
$('app').innerHTML=`<nav class="nav"><a href="../museo/index.html?pieza=spacex">← ${t('Museo','Museum')}</a><span>ATLAS / 06</span><a href="../lunar/index.html">${t('Industria lunar','Lunar industry')} ↗</a><a id="page-language" href="${es?'../../spacex/index.html':'../es/spacex/index.html'}">${es?'EN':'ES'}</a></nav>
<header><div><span class="eyebrow">${t('LANZAR · SEPARAR · RECUPERAR','LAUNCH · SEPARATE · RECOVER')}</span><h1>${t('Un lanzamiento.<br>Dos trayectorias.','One launch.<br>Two paths.')}</h1></div><p>${t('Sigue el hardware que regresa y la carga que continúa. Compara Falcon 9 con la arquitectura de Starship y ve cuándo los motores empujan.','Follow returning hardware and the continuing payload. Compare Falcon 9 with Starship architecture and see when engines fire.')}</p></header>
<section id="metrics" class="metrics" aria-label="${t('Estado de las piezas visibles','State of the visible parts')}"></section>
<section class="engine-chart"><div class="chart-key"><b>${t('Encendidos durante el recorrido','Burns during the journey')}</b><span>● ${t('Encendido · gris: sin empuje','Firing · grey: no thrust')}</span></div><div id="burn-booster" class="burn-row"></div><div id="burn-upper" class="burn-row"></div><div class="burn-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div><small>${t('Estados hasta tu posición. No calculamos la cantidad exacta de motores de regreso.','States up to your position. Exact return-engine counts are not calculated.')}</small></section>
<div class="scenario"><div class="forms"><button id="v-falcon" aria-pressed="true">Falcon 9</button><button id="v-starship" aria-pressed="false">Starship</button></div><label for="recovery">${t('Perfil Falcon','Falcon profile')}<select id="recovery"><option value="droneship">${t('Barcaza mar adentro','Downrange droneship')}</option><option value="rtls">${t('Regreso a costa','Return to coast')}</option><option value="expendable">${t('Desechable','Expendable')}</option></select></label><span id="profile"></span></div>
<nav class="chapters">${NARRATION_CHAPTERS.map((c,i)=>`<button id="chapter-${i}" data-chapter="${i}"><small>0${c.local+1}</small><span>${titles[i]}</span></button>`).join('')}</nav>
<div class="layout"><section class="stage visual"><div id="space" tabindex="0" role="img" aria-label="${t('Vehículos 3D con rutas de la carga y el booster','3D vehicles with payload and booster paths')}"></div><div class="scene-heading"><b id="action"></b><span>${t('Paisaje comprimido · curvas didácticas','Compressed scenery · teaching curves')}</span></div><p id="loading">${t('Preparando el lanzamiento…','Preparing the launch…')}</p><div class="view-controls"><button id="fit">${t('Seguir','Follow')}</button><button id="view-booster">Booster</button><button id="view-upper">${t('Nave / carga','Ship / payload')}</button><button id="overview">${t('Ambas rutas','Both paths')}</button><button id="zoom-in" aria-label="${t('Acercar','Zoom in')}">+</button><button id="zoom-out" aria-label="${t('Alejar','Zoom out')}">−</button></div><small class="camera-help">${t('Arrastra para mirar · rueda para acercar','Drag to look · wheel to zoom')}</small></section>
<aside><span class="eyebrow" id="chapter-number"></span><h2 id="chapter-title"></h2><p id="step-body"></p><div class="actions"><button id="listen" class="primary">▶ ${t('Escuchar etapa','Listen to chapter')}</button><button id="next">${t('Siguiente voz','Next narration')} →</button></div><label class="check"><input id="follow" type="checkbox" checked>${t('Encuadrar las etapas de la voz','Frame narrated chapters')}</label><p id="mechanism" class="mechanism"></p><details class="read-along"><summary>${t('Texto completo de esta voz','Full narration transcript')}</summary><p id="narration-text"></p></details></aside></div>
<section class="lab"><div class="lab-heading"><span class="eyebrow">${t('EXPLORA EL MISMO RECORRIDO','EXPLORE THE SAME JOURNEY')}</span><span id="time-source"></span></div><div class="actions"><button id="play" class="primary">▶ ${t('Reproducir recorrido','Play journey')}</button><button id="reset">↺ ${t('Reiniciar','Restart')}</button><button id="step">${t('Siguiente etapa','Next chapter')}</button><button id="finish">${t('Ver resultado','See outcome')}</button><label for="speed">${t('Velocidad de presentación','Presentation speed')}<select id="speed"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div><label class="experiment-timeline" for="timeline"><span>${t('Posición del esquema','Schematic position')} <output id="time">0</output> / 100</span><input id="timeline" type="range" min="0" max="100" step="0.05" value="0"></label><p class="experiment-note">${t('Esta barra no mide segundos, kilómetros ni velocidad. Cambiar de perfil conserva el punto del recorrido; cambiar de vehículo abre otro lanzamiento. El footer recorre la voz y mueve la escena con ella.','This bar measures neither seconds, kilometres nor speed. Changing profiles preserves the point in the journey; changing vehicle opens another launch. The footer follows narration and moves the scene with it.')}</p><p id="outcome"></p></section>
<section class="principles"><article><span class="eyebrow">01 · ${t('EL DESTINO','DESTINATION')}</span><h3>${t('Órbita es velocidad','Orbit is speed')}</h3><p>${t('La carga necesita velocidad lateral suficiente, no solo subir. Estas curvas muestran la secuencia sin resolver una órbita real.','Payload needs sufficient lateral velocity, not simply altitude. These curves show the sequence without solving a real orbit.')}</p></article><article><span class="eyebrow">02 · ${t('LA REUTILIZACIÓN','REUSE')}</span><h3>${t('Conservar hardware','Retain hardware')}</h3><p>${t('Combustible de regreso y equipamiento de recuperación tienen un coste de rendimiento. Un booster recuperado aún necesita preparación.','Return propellant and recovery hardware carry a performance tradeoff. A recovered booster still needs preparation.')}</p></article><article><span class="eyebrow">03 · ${t('LO PUBLICADO','PUBLISHED REFERENCE')}</span><h3 id="reference-number"></h3><p id="reference-note"></p></article></section>
<details class="sources"><summary>${t('Modelo, límites y fuentes primarias','Model, limits and primary sources')}</summary><p>${t('Falcon 9: 70 m y diámetro publicado de 3,7 m; cofia estándar de 13,1 m × 5,2 m. Starship usa la referencia publicada de 124 m y 9 m, con Super Heavy de 72 m y nave de 52 m. Son proporciones de una arquitectura, no CAD ni réplica de la última versión. Equipos pequeños y paisaje se amplían o comprimen para verse.','Falcon 9: 70 m and a published diameter of 3.7 m; a 13.1 m × 5.2 m standard fairing. Starship uses the published 124 m and 9 m reference, with a 72 m Super Heavy and 52 m ship. These are architecture proportions, not CAD or a replica of the latest version. Small hardware and scenery are enlarged or compressed for visibility.')}</p><p>${t('Las rutas son curvas reversibles elegidas para explicar maniobras. No calculan fuerzas, aerodinámica, órbitas, combustible, fiabilidad, costes ni oportunidades de lanzamiento. Tiempos, alturas y encendidos varían por misión. Los subconjuntos de chorros de regreso son representativos. No simulamos la recuperación de cofias ni el abandono posterior de la etapa superior de Falcon.','Routes are reversible curves chosen to explain manoeuvres. They do not compute forces, aerodynamics, orbits, propellant, reliability, costs or launch opportunities. Timing, altitude and firing vary by mission. Return plume subsets are representative. Fairing retrieval and subsequent disposal of the Falcon upper stage are not simulated.')}</p><p>${t('Starship ilustra captura del booster y entrada/amerizaje de la nave, mecanismos demostrados en ensayos. No reproduce una prueba concreta ni equivale a reutilización completa rutinaria. La carga permanece dentro y no se acredita entrega orbital o lunar. Una nave amerizada no se suma al hardware disponible para otro vuelo. Voz y escena usan tramos aproximados; el navegador puede exigir pulsar play para permitir sonido.','Starship illustrates booster catching and ship entry/splashdown, mechanisms demonstrated in tests. It neither replays one test nor implies routine full reuse. Payload remains inside and no orbital or lunar delivery is credited. A splashed-down ship is not counted as hardware available for another flight. Narration and scene use approximate cue segments; your browser may require pressing play to permit sound.')}</p><div>${[['SpaceX · Falcon 9','https://www.spacex.com/vehicles/falcon-9/fairing'],['Falcon Payload User’s Guide · 2025','https://www.spacex.com/assets/media/falcon-users-guide-2025-05-09.pdf'],['SpaceX · Starship reference','https://new.spacex.com/vehicles/starship'],['SpaceX · flight-test updates','https://www.spacex.com/updates/reusability']].map(([text,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`).join('')}</div></details>`;
if(typeof ResizeObserver==='function'){new ResizeObserver(([entry])=>{const height=entry.borderBoxSize?.[0]?.blockSize??$('metrics').offsetHeight;document.documentElement.style.setProperty('--metrics-height',Math.ceil(height)+'px');}).observe($('metrics'));}
function rebuild(){params=clean(params);trace=makeFlightTrace(params);frame=flightFrameAt(trace,time);}
function save(){notebook?.save();}
function manual(){timeSource='manual';playing=false;notebook?.pause();}
function localChapter(){return time<8?0:time<50?1:time<85?2:3;}
function inputs(){$('recovery').value=params.recovery;$('recovery').disabled=params.vehicle==='starship';$('speed').value=speed;for(const vehicle of ['falcon','starship'])$('v-'+vehicle).setAttribute('aria-pressed',String(params.vehicle===vehicle));}
function focusChapter(){world?.focus(chapter%4===2?'booster':chapter%4===3?'upper':'follow');}
function select(index,move=true){chapter=Math.max(0,Math.min(7,index));const c=NARRATION_CHAPTERS[chapter];params.vehicle=c.vehicle;time=c.start;rebuild();inputs();if(move)focusChapter();paint();}
let burnCache='';
function burnChart(){const key=params.vehicle+':'+params.recovery;if(key!==burnCache){burnCache=key;for(const part of ['booster','upper'])$('burn-'+part).innerHTML=`<span>${part==='booster'?'Booster':t('Etapa superior','Upper stage')}</span><div class="burn-cells">${Array.from({length:100},(_,i)=>`<i data-burn="${i}" class="${flightFrameAt(trace,i+.5).engines[part].firing?'on':'off'}"></i>`).join('')}<b class="burn-cursor"></b></div>`;}
 for(const part of ['booster','upper']){for(const cell of $('burn-'+part).querySelectorAll('[data-burn]'))cell.classList.toggle('future',Number(cell.dataset.burn)+.5>time);$('burn-'+part).querySelector('.burn-cursor').style.left=time+'%';}
}
function paint(){frame=flightFrameAt(trace,time);const booster=frame.engines.booster,upper=frame.engines.upper,recovered=frame.result.recoveredStages,payloadDelivered=frame.result.payloadDeployed;
 $('metrics').innerHTML=[[booster.installedCount+' + '+upper.installedCount,t('Motores instalados · inferior + superior','Installed engines · lower + upper')],[booster.firing?t('Encendido','Firing'):t('Apagado','Off'),t('Empuje del booster','Booster thrust')],[recovered+' / 2',t('Etapas recuperadas en el esquema','Stages recovered in the scheme')],[params.vehicle==='starship'?t('A bordo','On board'):payloadDelivered?t('Liberada','Released'):t('Sujeta','Attached'),t('Carga de ejemplo','Example payload')]].map(([value,label])=>`<article><strong>${value}</strong><span>${label}</span></article>`).join('');
 Object.assign($('metrics').dataset,{vehicle:params.vehicle,time:String(time),recovered:String(recovered),payload:String(payloadDelivered),boosterFiring:String(booster.firing),upperFiring:String(upper.firing),phase:frame.phase,chapter:String(chapter)});
 $('chapter-number').textContent=`0${chapter%4+1} / 04 · ${params.vehicle==='falcon'?'FALCON 9':'STARSHIP'}`;$('chapter-title').textContent=titles[chapter];$('step-body').textContent=summaries[chapter][es?0:1];$('profile').textContent=profileName();$('action').textContent=titles[chapter];$('time').textContent=nf.format(time);$('timeline').value=time;$('play').textContent=playing?'Ⅱ '+t('Pausar recorrido','Pause journey'):'▶ '+t('Reproducir recorrido','Play journey');$('time-source').textContent=timeSource==='manual'?t('Exploración manual · voz pausada','Manual exploration · narration paused'):t('Recorrido guiado por la voz','Journey guided by narration');
 $('mechanism').textContent=booster.firing?t('El booster empuja. Los chorros se conectan a sus boquillas; los de regreso son representativos.','The booster fires. Plumes attach to its nozzles; return plumes are representative.'):upper.firing?(params.vehicle==='starship'&&time>=93?t('Los motores de la nave participan en el cambio de orientación y el descenso final.','Ship engines participate in the orientation change and final descent.'):t('El booster no empuja. La etapa superior usa sus propios motores para continuar con la carga.','The booster is not firing. The upper stage uses its own engines to continue with the payload.')):t('Sin empuje en ninguna etapa. Movimiento y calentamiento de entrada no son una llama de motor.','Neither stage fires. Motion and entry heating are not an engine flame.');
 $('narration-text').textContent=VOICES[notebook?.language||(es?'es':'en')][chapter].text;$('narration-text').lang=notebook?.language||(es?'es':'en');
 $('reference-number').textContent=params.vehicle==='falcon'?t('70 m · 22.800 kg LEO','70 m · 22,800 kg LEO'):'124 m · 9 m';$('reference-note').textContent=params.vehicle==='falcon'?t('Dimensiones y capacidad máxima publicada. No es carga garantizada con recuperación.','Published dimensions and maximum capacity. This is not guaranteed payload with recovery.'):t('Arquitectura publicada: 72 m de booster y 52 m de nave. No acredita una misión real.','Published architecture: a 72 m booster and 52 m ship. It does not certify a real mission.');
 $('outcome').textContent=time<100?t('Cada pieza conserva su identidad. Retrocede para comprobar de dónde vino.','Every part retains its identity. Rewind to see where it came from.'):params.vehicle==='starship'?t('Resultado: booster capturado; nave amerizada y carga a bordo. Una de dos etapas recuperada; requiere inspección posterior.','Outcome: booster caught; ship splashed down with payload aboard. One of two stages recovered; subsequent inspection is needed.'):params.recovery==='expendable'?t('Resultado: carga liberada; ninguna etapa recuperada. No se simula la recogida de las cofias.','Outcome: payload released; no stages recovered. Fairing retrieval is not simulated.'):t('Resultado: carga liberada y booster aterrizado. Una etapa recuperada; aún requiere transporte, inspección e integración.','Outcome: payload released and booster landed. One stage recovered; transport, inspection and integration are still needed.');
 document.querySelectorAll('[data-chapter]').forEach(b=>{const i=Number(b.dataset.chapter);b.hidden=NARRATION_CHAPTERS[i].vehicle!==params.vehicle;b.setAttribute('aria-current',i===chapter?'step':'false');});burnChart();
}
try{world=createSpaceWorld($('space'),es);$('loading').hidden=true;}catch(error){$('loading').textContent=t('3D no disponible. Puedes seguir la voz y los estados.','3D unavailable. You can follow narration and states.');console.error(error);}
notebook=new NotebookPlayer({id:'spacex',autoplay:true,getClips:language=>VOICES[language],capture:()=>({params:{...params},time,chapter,timeSource,view:world?.getViewState?.(),follow:$('follow').checked,speed}),
 restore(saved){if(!saved)return;restored=true;params=clean(saved.params);time=Math.max(0,Math.min(100,Number(saved.time)||0));chapter=offset()+localChapter();timeSource=saved.timeSource==='manual'?'manual':'narration';$('follow').checked=saved.follow!==false;speed=[1,2,4].includes(saved.speed)?saved.speed:1;rebuild();world?.restoreViewState?.(saved.view);},
 onLanguage(){changingVoice=ready;},onSync(s){if(!s||!ready)return;if(changingVoice){changingVoice=false;paint();return;}if(timeSource==='manual'&&s.reason!=='seek')return;if(s.reason==='pause')return;playing=false;timeSource='narration';const previous=chapter;chapter=s.index;const previousVehicle=params.vehicle;params.vehicle=NARRATION_CHAPTERS[chapter].vehicle;time=narrationTime(chapter,s.progress,notebook.language);if(previousVehicle!==params.vehicle)rebuild();inputs();if((previous!==chapter||s.reason==='seek')&&!keepCamera&&$('follow').checked)focusChapter();paint();}
});
ready=true;if(!restored){chapter=notebook.current.index;params.vehicle=NARRATION_CHAPTERS[chapter].vehicle;time=narrationTime(chapter,notebook.current.progress,notebook.language);rebuild();focusChapter();}else if(timeSource==='manual')notebook.pause();else chapter=notebook.current.index;inputs();paint();world?.render(frame,0);
const changeVoice=notebook.changeLanguage.bind(notebook);notebook.changeLanguage=language=>{const anchor={time,chapter,timeSource,progress:notebook.current.progress};changeVoice(language);if(anchor.timeSource==='narration'){const clip=notebook.clock.timeline[anchor.chapter];keepCamera=true;try{notebook.seek(clip.start+narrationProgress(anchor.chapter,anchor.time,language,anchor.progress)*clip.duration,notebook.wanted);}finally{keepCamera=false;}}};
const playerToggle=notebook.el('play').onclick;notebook.el('play').onclick=()=>{if(!notebook.running){timeSource='narration';notebook.onSync({...notebook.current,reason:'seek'});}playerToggle();};
function listenAt(index,hold=false){playing=false;timeSource='narration';keepCamera=hold;notebook.stage(index,true);keepCamera=false;paint();}
$('listen').onclick=()=>listenAt(chapter,true);$('next').onclick=()=>listenAt((chapter+1)%8);$('follow').onchange=save;$('page-language').onclick=save;
for(const vehicle of ['falcon','starship'])$('v-'+vehicle).onclick=()=>{manual();params.vehicle=vehicle;select(vehicle==='falcon'?0:4);save();};
$('recovery').onchange=()=>{manual();params.recovery=$('recovery').value;rebuild();inputs();paint();save();};$('speed').onchange=()=>{speed=Number($('speed').value);save();};
$('play').onclick=()=>{const previous=playing;manual();playing=!previous;if(time>=100)time=0;chapter=offset()+localChapter();paint();save();};$('reset').onclick=()=>{manual();select(offset());save();};$('step').onclick=()=>{manual();time=[0,8,50,85,100].find(value=>value>time)??100;chapter=offset()+localChapter();focusChapter();paint();save();};$('finish').onclick=()=>{manual();time=100;chapter=offset()+3;world?.overview();paint();save();};$('timeline').oninput=()=>{manual();time=Math.min(100,Math.max(0,Number($('timeline').value)||0));chapter=offset()+localChapter();paint();save();};
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{manual();select(Number(b.dataset.chapter));save();});
for(const [id,view] of [['fit','follow'],['overview','overview'],['view-booster','booster'],['view-upper','upper']])$(id).onclick=()=>{world?.focus(view);save();};$('zoom-in').onclick=()=>{world?.zoomBy(1.18);save();};$('zoom-out').onclick=()=>{world?.zoomBy(.85);save();};
window.addEventListener('blur',()=>{manual();save();});document.addEventListener('visibilitychange',()=>{if(document.hidden){manual();save();}last=performance.now();});window.addEventListener('pagehide',save);
function loop(now){const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;if(!document.hidden){if(playing){time=Math.min(100,time+dt*speed);chapter=offset()+localChapter();if(time>=100)playing=false;}elapsed+=dt;if(playing||elapsed>.15){paint();elapsed=0;}world?.render(frame,dt);}requestAnimationFrame(loop);}
requestAnimationFrame(loop);