import {defaults,cleanGrowthState,createGrowthTrace,growthFrameAt,growthPositionForDay} from './model.js';
import {createGrowthWorld} from './world.js';
import {growthPoseAt,restoreGrowthPose,growthWalk,growthNearestStand,growthGuidePath} from './walk.js';
import {NotebookPlayer} from '../playback/player.js';
import {bindFirstPerson} from '../immersive/first-person.js';
import {VOICES} from './voices.js';
import {LESSONS} from './lessons.js';
import {mountGrowth,paintGrowthView,growthInputs,CONTROL_KEYS} from './presentation.js';
const es=document.documentElement.lang==='es',t=(a,b)=>es?a:b,$=id=>document.getElementById(id),query=new URLSearchParams(location.search);
const fmt=(n,d=2)=>new Intl.NumberFormat(es?'es-ES':'en-US',{maximumFractionDigits:d}).format(n),bounded=(n,a,b,whole=false)=>{const value=Math.max(a,Math.min(b,Number.isFinite(n)?n:a));return whole?Math.floor(value):value;};
let params={...defaults},chapter=0,progress=0,metric=0,timeSource='narration',mode=['diagram','notebook','immersive'].includes(query.get('mode'))?query.get('mode'):'diagram',enteredFPS=false,pose=growthPoseAt(0),world,notebook,firstPerson,trace=createGrowthTrace(params),frame=growthFrameAt(trace,0,0),paramSignature=JSON.stringify(params),ready=false,restored=false,holdPose=false,changingVoice=false,aligning=false,playing=false,lookActive=false,wasLocked=false,last=performance.now(),raf,travel=null;
const keys=new Set(),touch=new Set();
mountGrowth(es);
const metricObserver=new ResizeObserver(()=>document.documentElement.style.setProperty('--metrics-height',Math.ceil($('metrics').offsetHeight)+'px'));metricObserver.observe($('metrics'));
function inputs(){growthInputs(params,es);}
function rebuild(){const clean=cleanGrowthState(params),signature=JSON.stringify(clean);params={...clean};if(signature!==paramSignature){trace=createGrowthTrace(params);paramSignature=signature;}frame=growthFrameAt(trace,chapter,progress);}
function manual(){timeSource='manual';playing=false;travel=null;notebook?.pause();}
function save(){notebook?.save();}
function align(){if(!ready||timeSource!=='manual')return;const c=notebook.clock.timeline[chapter];aligning=true;try{notebook.seek(c.start+progress*c.duration,false);}finally{aligning=false;}}
function phase(value){manual();progress=bounded(value,0,1);rebuild();paint();align();save();}
function paint(){paintGrowthView({es,params,frame,chapter,progress,metric,timeSource,playing,mode,text:VOICES[notebook?.language||(es?'es':'en')][chapter].text,language:notebook?.language||(es?'es':'en')});world?.render(frame);}
function listenAt(index,keep=false){playing=false;travel=null;timeSource='narration';holdPose=keep;notebook?.stage(index,true);holdPose=false;paint();}
function release(){lookActive=false;firstPerson?.release();$('capture').textContent=t('Activar ratón','Enable mouse look');}
function useMode(value){manual();keys.clear();touch.clear();release();mode=value;if(mode==='immersive'&&!enteredFPS){pose=growthPoseAt(chapter);enteredFPS=true;}world?.setMode(mode);world?.setPose(pose);history.replaceState(null,'','?mode='+mode);paint();if(mode==='immersive')world?.canvas.focus({preventScroll:true});save();}
try{world=createGrowthWorld($('space'),es,i=>listenAt(i,true),info=>{$('inspect').textContent=Array.isArray(info)?info[es?0:1]:String(info);$('inspect').hidden=false;});$('loading').hidden=true;}catch(error){console.error(error);$('loading').textContent=t('3D no disponible: puedes seguir cifras, texto y voz.','3D unavailable: follow numbers, text and narration.');}
notebook=new NotebookPlayer({id:'growth',getClips:lang=>VOICES[lang],capture:()=>({metric,params:{...params},chapter,progress,timeSource,mode,enteredFPS,pose:{...pose},camera:world?.getViewState(),follow:$('follow').checked}),restore(saved){if(!saved)return;restored=true;metric=[0,1,2].includes(saved.metric)?saved.metric:0;params={...cleanGrowthState(saved.params||saved.state)};chapter=bounded(saved.chapter,0,5,true);progress=bounded(saved.progress,0,1);timeSource=saved.timeSource==='manual'?'manual':'narration';if(['diagram','notebook','immersive'].includes(query.get('mode')))mode=query.get('mode');else if(['diagram','notebook','immersive'].includes(saved.mode))mode=saved.mode;enteredFPS=saved.enteredFPS===true;pose=restoreGrowthPose(saved.pose);$('follow').checked=saved.follow!==false;rebuild();if(saved.camera)world?.restoreViewState(saved.camera);},onLanguage(){changingVoice=true;queueMicrotask(()=>changingVoice=false);},onSync(s){if(!s||aligning)return;const changed=chapter!==s.index;if(timeSource==='manual'&&!notebook?.wanted)return;if(changingVoice&&timeSource==='manual')return;chapter=s.index;progress=s.progress;rebuild();if(ready&&changed&&$('follow').checked&&!holdPose){if(mode==='immersive')travel={path:growthGuidePath(pose,growthPoseAt(chapter)),index:1,target:growthPoseAt(chapter)};else world?.focus(chapter);}paint();}});
ready=true;if(!restored){chapter=notebook.current.index;progress=notebook.current.progress;rebuild();if(mode==='immersive'){pose=growthPoseAt(chapter);enteredFPS=true;}world?.focus(chapter);}if(mode==='immersive'&&!enteredFPS){pose=growthPoseAt(chapter);enteredFPS=true;}world?.setMode(mode);world?.setPose(pose);inputs();paint();
if(world)firstPerson=bindFirstPerson({canvas:world.canvas,enabled:()=>mode==='immersive'&&lookActive,onLook:(dx,dy)=>{travel=null;pose.yaw-=dx*.0025;pose.pitch=Math.max(-1.25,Math.min(1.25,pose.pitch-dy*.002));world.setPose(pose);save();},onActivate:(x,y)=>{if(x==null)world.activate();else{const hit=world.inspect(x,y);if(Number.isInteger(hit?.action))listenAt(hit.action,true);else if(hit?.info){$('inspect').textContent=hit.info[es?0:1];$('inspect').hidden=false;}}},onState(state){const locked=state==='locked';if(wasLocked&&!locked){manual();lookActive=false;paint();save();}wasLocked=locked;}});
function enterCanvas(e){if(mode!=='immersive'||lookActive||e.button!==0)return;const hit=world?.inspect(e.clientX,e.clientY);if(Number.isInteger(hit?.action))listenAt(hit.action,true);lookActive=true;world?.canvas.focus({preventScroll:true});firstPerson?.request();$('capture').textContent=t('Ratón activo · Esc','Mouse active · Esc');save();}
world?.canvas.addEventListener('click',enterCanvas);
for(const id of CONTROL_KEYS)$(id).oninput=()=>{const el=$(id);if(el.type!=='checkbox'&&(el.value===''||!el.checkValidity()))return;manual();params[id]=el.type==='checkbox'?el.checked:+el.value;rebuild();inputs();paint();align();save();};
document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{manual();timeSource='narration';notebook.stage(+b.dataset.chapter,false);world?.focus(chapter);save();});
$('listen').onclick=()=>listenAt(chapter,mode==='immersive');$('next').onclick=()=>listenAt(Math.min(5,chapter+1));$('listen-here').onclick=()=>{const hit=growthNearestStand(pose);if(hit)listenAt(hit.index,true);};$('mode-diagram').onclick=()=>useMode('diagram');$('mode-notebook').onclick=()=>useMode('notebook');$('mode-immersive').onclick=()=>useMode('immersive');$('capture').onclick=()=>{lookActive=true;world?.canvas.focus({preventScroll:true});firstPerson?.request();$('capture').textContent=t('Ratón activo · Esc','Mouse active · Esc');};$('fit').onclick=()=>{world?.focus(chapter);save();};$('closeup').onclick=()=>{world?.closeup?.();save();};$('overview').onclick=()=>{world?.overview();save();};$('zoom-in').onclick=()=>{world?.zoomBy(1.12);save();};$('zoom-out').onclick=()=>{world?.zoomBy(1/1.12);save();};$('phase').oninput=()=>phase(+$('phase').value);$('reset').onclick=()=>phase(0);$('finish').onclick=()=>phase(1);$('step').onclick=()=>phase(Math.min(1,progress+.125));$('play').onclick=()=>{const resume=!playing;manual();if(progress===1)progress=0;playing=resume;rebuild();paint();align();save();};
const playerToggle=notebook.toggle.bind(notebook);notebook.toggle=()=>{if(!notebook.running)timeSource='narration';playing=false;playerToggle();};const playerLanguage=notebook.changeLanguage.bind(notebook);notebook.changeLanguage=lang=>{const wasManual=timeSource==='manual',savedProgress=progress;changingVoice=true;playerLanguage(lang);if(wasManual){timeSource='manual';progress=savedProgress;rebuild();paint();save();}changingVoice=false;};const playerSeek=notebook.seek.bind(notebook);notebook.seek=(seconds,play=notebook.wanted)=>{if(!aligning&&!changingVoice){timeSource='narration';playing=false;}playerSeek(seconds,play);};
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{manual();touch.add(b.dataset.move);b.setPointerCapture?.(e.pointerId);};b.onpointerup=b.onpointercancel=()=>{touch.delete(b.dataset.move);save();};}
function keydown(e){if(e.target.matches('input,select,textarea,button,a')&&e.key!=='Escape')return;if(e.key==='Escape'){manual();release();keys.clear();touch.clear();paint();save();return;}if(mode!=='immersive')return;if(e.key.toLowerCase()==='e'){world?.activate();return;}if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();manual();keys.add(e.key.toLowerCase());}}
window.addEventListener('keydown',keydown);const keyup=e=>{if(keys.delete(e.key.toLowerCase()))save();};window.addEventListener('keyup',keyup);const blur=()=>{keys.clear();touch.clear();save();};window.addEventListener('blur',blur);
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!document.hidden){if(playing){progress=Math.min(1,progress+dt/20);if(progress===1)playing=false;rebuild();paint();align();}if(mode==='immersive'){const forward=(keys.has('w')||keys.has('arrowup')||touch.has('forward')?1:0)-(keys.has('s')||keys.has('arrowdown')||touch.has('back')?1:0),strafe=(keys.has('d')||keys.has('arrowright')||touch.has('right')?1:0)-(keys.has('a')||keys.has('arrowleft')||touch.has('left')?1:0);if(forward||strafe){const n=Math.hypot(forward,strafe),d=dt*3.2;pose=growthWalk(pose,(-Math.sin(pose.yaw)*forward+Math.cos(pose.yaw)*strafe)*d/n,(-Math.cos(pose.yaw)*forward-Math.sin(pose.yaw)*strafe)*d/n);travel=null;}else if(travel&&notebook?.running){const goal=travel.path[travel.index];if(!goal){pose.yaw=travel.target.yaw;pose.pitch=travel.target.pitch;travel=null;}else{const dx=goal.x-pose.x,dz=goal.z-pose.z,n=Math.hypot(dx,dz);if(n<.05)travel.index++;else{const d=Math.min(n,dt*3.2);pose=growthWalk(pose,dx*d/n,dz*d/n);}}}world?.setPose(pose);const stand=growthNearestStand(pose);$('listen-here').textContent=stand?'E · '+t('Escuchar','Listen')+' '+LESSONS[stand.index].title[es?0:1]:t('Acércate a un botón del stand','Approach a stand button');$('listen-here').disabled=!stand;$('position').textContent=fmt(pose.x,1)+' · '+fmt(pose.z,1)+' m';}world?.render(frame);}raf=requestAnimationFrame(tick);}
raf=requestAnimationFrame(tick);window.addEventListener('pagehide',()=>{save();metricObserver.disconnect();cancelAnimationFrame(raf);firstPerson?.dispose();world?.canvas.removeEventListener('click',enterCanvas);world?.dispose();notebook.dispose();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',blur);});

function seekDay(value){manual();const next=growthPositionForDay(trace,value,chapter),changed=chapter!==next.chapter;chapter=next.chapter;progress=next.progress;rebuild();if(changed&&mode==='notebook')world?.focus(chapter);paint();align();save();}
$('day').oninput=()=>seekDay(+$('day').value);
$('chart').onclick=e=>{const svg=e.target.closest?.('svg');if(!svg)return;const rect=svg.getBoundingClientRect(),x=(e.clientX-rect.left)*720/Math.max(1,rect.width);seekDay(bounded((x-65)/625*trace.horizon,0,trace.horizon));};
document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{metric=+b.dataset.metric;paint();save();});
function preset(values){manual();Object.assign(params,values);rebuild();inputs();paint();align();save();}
$('preset-fair').onclick=()=>preset({hours:24,shifts:3});$('preset-no-grow').onclick=()=>preset({reinvest:0});$('preset-unlimited').onclick=()=>preset({limited:false});$('preset-default').onclick=()=>preset(defaults);
