// Walking solids below have matching industrial fixtures in growth/world.js.
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a));
export const GROWTH_ROOM=[-16,-10,24,14];
export const GROWTH_LANES=[{id:'human',z:-6},{id:'fixed',z:0},{id:'growing',z:6}];
export const GROWTH_BENCH_X=[-12,-9.3,-6.6,-3.9,-1.2];
export const GROWTH_NEW_X=Array.from({length:10},(_,i)=>5.6+i*1.6);
export const GROWTH_STANDS=[[2.2,1.15,10.5],[-6,1.15,3],[8,1.15,10.5],[4.2,1.15,4.5],[22,1.15,-3.5],[-13.5,1.15,11.2]];
export const GROWTH_STAND_YAWS=[0,0,0,-Math.PI/2,0,0];
export const GROWTH_FOCUS=[[2.8,1.7,2.0],[-6.6,1.4,-2.5],[12.8,1.35,8],[12.8,1.35,4.5],[19.5,1.8,-5.8],[-13.5,1.8,9.5]];
export const GROWTH_BOUNDS=[[-15.3,0,-7.8,23.3,4.3,10.4],[-14.8,0,-7.0,2.0,3.5,1.8],[4.8,0,7.1,23.3,3.4,8.8],[4.8,0,.7,23.3,3.4,8.8],[15.8,0,-7.5,23.3,3.7,-4.4],[-15.4,.18,9.1,-11.6,3.75,9.9]];
export const GROWTH_WALLS=[[-16.12,-10.12,24.12,-9.88],[-16.12,13.88,24.12,14.12],[-16.12,-10,-15.88,14],[23.88,-10,24.12,14]];
export const GROWTH_FIXTURE_SOLIDS=[...GROWTH_LANES.flatMap(l=>GROWTH_BENCH_X.map(x=>[x-1,l.z-.50,x+1,l.z+.50])),...GROWTH_LANES.flatMap(l=>[[-15.1,l.z-.65,-13.9,l.z+.65],[.50,l.z-.65,1.7,l.z+.65]]),...GROWTH_NEW_X.flatMap(x=>[8,4.5,1.5].map(z=>[x-.45,z-.42,x+.45,z+.42])),[20.8,-6.50,23.2,-5.55],[-15.2,9.1,-11.8,9.6]];
export const GROWTH_STAND_SOLIDS=GROWTH_STANDS.map(([x,y,z])=>[x-.24,z-.20,x+.24,z+.20]);
export const GROWTH_SOLIDS=[...GROWTH_WALLS,...GROWTH_FIXTURE_SOLIDS,...GROWTH_STAND_SOLIDS];
const index=n=>Math.floor(clamp(Number(n),0,5));
export const growthCollision=(x,z,r=.24)=>GROWTH_SOLIDS.some(b=>x+r>b[0]&&x-r<b[2]&&z+r>b[1]&&z-r<b[3]);
export function growthPoseAt(chapter=0){const i=index(chapter),[x,y,z]=GROWTH_STANDS[i],yaw=GROWTH_STAND_YAWS[i];return {x:x+Math.sin(yaw)*2.1,z:z+Math.cos(yaw)*2.1,yaw,pitch:.04};}
export function restoreGrowthPose(saved){if(!saved||!['x','z','yaw','pitch'].every(k=>Number.isFinite(saved[k])))return growthPoseAt(0);const p={x:clamp(saved.x,-15.5,23.5),z:clamp(saved.z,-9.5,13.5),yaw:saved.yaw,pitch:clamp(saved.pitch,-1.25,1.25)};return growthCollision(p.x,p.z)?growthPoseAt(0):p;}
export function growthWalk(pose,dx,dz){if(typeof dx==='object'){const f=dx.forward||0,s=dx.strafe||0,n=Math.max(1,Math.hypot(f,s)),d=2.5*clamp(dz,0,.05);dx=(-Math.sin(pose.yaw)*f+Math.cos(pose.yaw)*s)/n*d;dz=(-Math.cos(pose.yaw)*f-Math.sin(pose.yaw)*s)/n*d;}dx=Number.isFinite(dx)?dx:0;dz=Number.isFinite(dz)?dz:0;let p={...pose};const count=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.10));for(let i=0;i<count;i++){const x=clamp(p.x+dx/count,-15.5,23.5),z=clamp(p.z+dz/count,-9.5,13.5);if(!growthCollision(x,p.z))p.x=x;if(!growthCollision(p.x,z))p.z=z;}return p;}
export function growthSegmentClear(a,b,r=.25,solids=GROWTH_SOLIDS){for(const q of solids){let lo=0,hi=1,hit=true;const start=[a.x,a.z],delta=[b.x-a.x,b.z-a.z];for(let d=0;d<2;d++){const min=q[d]-r,max=q[d+2]+r;if(Math.abs(delta[d])<1e-12){if(start[d]<=min||start[d]>=max){hit=false;break;}}else{let near=(min-start[d])/delta[d],far=(max-start[d])/delta[d];if(near>far)[near,far]=[far,near];lo=Math.max(lo,near);hi=Math.min(hi,far);if(lo>=hi){hit=false;break;}}}if(hit&&hi>0&&lo<1)return false;}return true;}
export function growthNearestStand(pose){let best=null;GROWTH_STANDS.forEach(([x,y,z],index)=>{const distance=Math.hypot(x-pose.x,z-pose.z),yaw=Math.atan2(pose.x-x,pose.z-z),angle=Math.abs(Math.atan2(Math.sin(yaw-pose.yaw),Math.cos(yaw-pose.yaw))),pitch=Math.atan2(y-1.65,distance);if(distance<2.45&&angle<.85&&Math.abs(pitch-(pose.pitch||0))<.60&&growthSegmentClear(pose,{x,z},0,GROWTH_SOLIDS.filter(b=>b!==GROWTH_STAND_SOLIDS[index]))&&(!best||distance<best.distance))best={index,distance,angle,pitch};});return best;}
let grid;
function navigationGrid(){if(grid)return grid;const step=.35,minX=-15.5,minZ=-9.5,nx=113,nz=67,nodes=[];for(let zi=0;zi<nz;zi++)for(let xi=0;xi<nx;xi++){const x=minX+xi*step,z=minZ+zi*step;nodes.push({x,z,xi,zi,index:zi*nx+xi,open:!growthCollision(x,z,.25)});}return grid={step,nx,nz,nodes};}
export function growthGuidePath(from,to){const start=restoreGrowthPose(from),end=restoreGrowthPose(to);if(growthSegmentClear(start,end))return [{x:start.x,z:start.z},{x:end.x,z:end.z}];const g=navigationGrid(),nearest=p=>{let best=null,d=Infinity;for(const q of g.nodes){const v=Math.hypot(q.x-p.x,q.z-p.z);if(q.open&&v<d&&growthSegmentClear(p,q)){best=q;d=v;}}return best;},first=nearest(start),last=nearest(end);if(!first||!last)return [];const open=new Set([first.index]),cost=new Map([[first.index,0]]),previous=new Map(),closed=new Set();let found=false;while(open.size){let current,best=Infinity;for(const id of open){const q=g.nodes[id],v=cost.get(id)+Math.hypot(q.x-last.x,q.z-last.z);if(v<best){best=v;current=q;}}open.delete(current.index);if(current.index===last.index){found=true;break;}closed.add(current.index);for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const xi=current.xi+dx,zi=current.zi+dz;if(xi<0||xi>=g.nx||zi<0||zi>=g.nz)continue;const q=g.nodes[zi*g.nx+xi];if(!q.open||closed.has(q.index)||!growthSegmentClear(current,q))continue;const v=cost.get(current.index)+g.step*Math.hypot(dx,dz);if(v<(cost.get(q.index)??Infinity)){cost.set(q.index,v);previous.set(q.index,current.index);open.add(q.index);}}}if(!found)return [];const points=[];for(let id=last.index;id!==undefined;id=previous.get(id)){points.push({x:g.nodes[id].x,z:g.nodes[id].z});if(id===first.index)break;}points.reverse();points.unshift({x:start.x,z:start.z});points.push({x:end.x,z:end.z});const result=[points[0]];for(let i=0;i<points.length-1;){let j=points.length-1;while(j>i+1&&!growthSegmentClear(points[i],points[j]))j--;result.push(points[j]);i=j;}return result;}