import * as THREE from '../vendor/three.module.js';
import {createPost} from '../fx/fx.js';
import {GROWTH_ROOM,GROWTH_LANES,GROWTH_BENCH_X,GROWTH_NEW_X,GROWTH_STANDS,GROWTH_STAND_YAWS,GROWTH_FOCUS,GROWTH_BOUNDS,GROWTH_WALLS,GROWTH_SOLIDS,growthPoseAt,restoreGrowthPose,growthNearestStand} from './walk.js';
export * from './walk.js';
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:a)),chapter=n=>Math.floor(clamp(Number(n),0,5));
const TITLES=[['Tres líneas, la misma tarea','Three lines, the same task'],['Horas efectivas y turnos','Effective hours and shifts'],['Trabajo que construye capacidad','Work that builds capacity'],['Dos días para incorporarse','Two days before joining'],['Flota, suministro y puestos','Fleet, supply and workstations'],['Coste por unidad equivalente','Cost per equivalent unit']];
export const growthOverview={yaw:.22,pitch:.65,distance:10,whole:true,closeup:false};
export function growthFraming(index=0,orbit={},aspect=1,fov=46,frame=null){const i=chapter(index);let b=orbit.whole?[-15.6,0,-8.3,23.4,4.7,11.5]:GROWTH_BOUNDS[i];if(orbit.closeup&&frame&&(i===2||i===3)){const s=growthRobotPose(frame,frame.trace.initialFleet);b=[s.position[0]-.85,0,s.position[2]-.80,s.position[0]+2.80,2.80,s.position[2]+.80];}const center=new THREE.Vector3((b[0]+b[3])/2,(b[1]+b[4])/2,(b[2]+b[5])/2),yaw=orbit.yaw??.12,pitch=orbit.pitch??.46,direction=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),up=new THREE.Vector3(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)),tan=Math.tan(fov*Math.PI/360);let d=2;for(const x of[b[0],b[3]])for(const y of[b[1],b[4]])for(const z of[b[2],b[5]]){const p=new THREE.Vector3(x,y,z).sub(center);d=Math.max(d,p.dot(direction)+Math.abs(p.dot(right))/(tan*Math.max(.1,aspect)),p.dot(direction)+Math.abs(p.dot(up))/tan);}return {center,direction,distance:d*1.035*(orbit.distance??10)/10,bounds:b};}
// Same identity follows this path; commissioning has no productive work before readyDay.
export function growthRobotPose(frame,id){const n=typeof id==='string'?Number(id.replace('robot-','')):id,rank=n-frame.trace.initialFleet,x=GROWTH_NEW_X[rank];if(!Number.isFinite(x))return null;const batch=frame.batches.find(b=>n>=b.idStart&&n<b.idEnd);if(!batch){const p=clamp((frame.constructionCredit-(n-frame.construction.nextId)*frame.params.buildHours)/frame.params.buildHours);return {id:'robot-'+n,position:[x,.24,8],status:p>0?'building':'future',fraction:p,visible:p>0,active:false,batchId:null};}const c=clamp(frame.time-batch.completedAt,0,2),smooth=u=>{u=clamp(u);return u*u*(3-2*u);},z=c<.40?8+(4.5-8)*smooth(c/.40):c<1.60?4.5:4.5+(1.5-4.5)*smooth((c-1.60)/.40);return {id:'robot-'+n,position:[x,.24,z],status:batch.status,fraction:1,visible:true,active:batch.status==='active',batchId:batch.id,readyDay:batch.readyDay,commissioningProgress:batch.commissioningProgress};}
export function createGrowthScene(es=true){
 const t=(a,b)=>es?a:b,scene=new THREE.Scene(),resources=[],owned=new Set(),targets=[],stands=[],parts={},own=r=>{if(!owned.has(r)){owned.add(r);resources.push(r);}return r;},release=r=>{if(owned.delete(r)){resources.splice(resources.indexOf(r),1);r.dispose();}};let disposed=false,lastFrame;
 scene.background=new THREE.Color(0x25221c);scene.fog=new THREE.Fog(0x25221c,65,120);
 const cube=own(new THREE.BoxGeometry(1,1,1)),cylinder=own(new THREE.CylinderGeometry(1,1,1,20)),sphere=own(new THREE.SphereGeometry(1,16,10)),plane=own(new THREE.PlaneGeometry(1,1)),materialCache=new Map();
 function mat(color,extra={}){const key=String(color)+JSON.stringify(extra);if(!materialCache.has(key))materialCache.set(key,own(new THREE.MeshStandardMaterial({color,roughness:.64,metalness:.15,...extra})));return materialCache.get(key);}
 const P={floor:mat(0x786d59,{roughness:.9}),wood:mat(0x65503b),board:mat(0x29302f),steel:mat(0x9caaae,{metalness:.75,roughness:.27}),dark:mat(0x283239),white:mat(0xe8e2d4),mint:mat(0x92cbb8),gold:mat(0xe5b772),coral:mat(0xd5937d),skin:mat(0xc99874),cloth:mat(0x64818a),sole:mat(0x313534),copper:mat(0xbb8754),glow:mat(0xb5e1ce,{emissive:0x83c8ac,emissiveIntensity:.3}),glass:mat(0xd3e5dc,{transparent:true,opacity:.16,depthWrite:false})};
 function mesh(g,geo,m,p=[0,0,0]){const o=new THREE.Mesh(geo,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;g.add(o);return o;}
 function box(g,p,s,m=P.white){const o=mesh(g,cube,m,p);o.scale.set(...s);return o;}
 function ball(g,p,r,m=P.steel){const o=mesh(g,sphere,m,p);o.scale.setScalar(r);return o;}
 function setRod(o,a,b,r=.02){const v=new THREE.Vector3(...a),w=new THREE.Vector3(...b),d=w.clone().sub(v),len=d.length();o.position.copy(v).add(w).multiplyScalar(.5);o.scale.set(r,len>0?len:.0001,r);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),len>0?d.multiplyScalar(1/len):new THREE.Vector3(0,1,0));o.userData.from=[...a];o.userData.to=[...b];}
 function rod(g,a,b,r=.02,m=P.steel){const o=mesh(g,cylinder,m);setRod(o,a,b,r);return o;}
 function label(g,initial,p,width=3.4,maxHeight=.20){const m=mesh(g,plane,own(new THREE.MeshBasicMaterial({transparent:true,depthWrite:false,toneMapped:false})),p),cache=new Map();m.castShadow=m.receiveShadow=false;m.userData.isLabel=true;let last;function set(value){const text=String(value);if(text===last)return;last=text;let entry=cache.get(text);if(!entry){const c=document.createElement('canvas'),ctx=c.getContext('2d');ctx.font='600 48px system-ui';c.width=Math.max(90,Math.min(1800,Math.ceil(ctx.measureText(text).width+32)));c.height=68;ctx.fillStyle='#25322ff5';ctx.fillRect(0,0,c.width,c.height);ctx.font='600 48px system-ui';ctx.fillStyle='#fff3dc';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,c.width/2,34,c.width-22);const texture=own(new THREE.CanvasTexture(c));texture.colorSpace=THREE.SRGBColorSpace;const w=Math.min(width,maxHeight*c.width/68);entry={texture,w,h:w*68/c.width};cache.set(text,entry);if(cache.size>6){const [key,old]=cache.entries().next().value;cache.delete(key);release(old.texture);}}m.material.map=entry.texture;m.material.needsUpdate=true;m.scale.set(entry.w,entry.h,1);m.userData.text=text;}set(initial);return {m,set,cache};}
 const integer=n=>Number.isFinite(n)?Math.round(n).toLocaleString(es?'es-ES':'en-US'):'—',number=n=>Number.isFinite(n)?n.toLocaleString(es?'es-ES':'en-US',{maximumFractionDigits:1}):'—',money=n=>Number.isFinite(n)?'€'+n.toFixed(2):'—';
 function info(o,text){o.userData.info=text;targets.push(o);return o;}
 const architecture=new THREE.Group();scene.add(architecture);parts.architecture=architecture;parts.floor=box(architecture,[4,-.12,2],[40.2,.24,24.2],P.floor);for(let x=-16;x<=24;x+=2)box(architecture,[x,.005,2],[.012,.01,24],P.wood);for(let z=-10;z<=14;z+=2)box(architecture,[4,.005,z],[40,.01,.012],P.wood);parts.walls=GROWTH_WALLS.map(b=>box(architecture,[(b[0]+b[2])/2,2.7,(b[1]+b[3])/2],[b[2]-b[0],5.4,b[3]-b[1]],P.wood));const rear=new THREE.Group();architecture.add(rear);parts.rearWall=rear;const plaster=mat(0xafa38a,{roughness:.9,metalness:0});box(rear,[4,1.12,-9.99],[40,2.24,.24],plaster);box(rear,[4,4.97,-9.99],[40,1.06,.24],plaster);const windowCenters=Array.from({length:6},(_,i)=>-13+i*6.8);let last=-16;for(const x of windowCenters){const left=x-2.2,right=x+2.2;if(left>last)box(rear,[(left+last)/2,3.35,-9.99],[left-last,2.2,.24],plaster);last=right;box(rear,[x,3.35,-9.96],[4.4,2.18,.07],mat(0x94aaa6,{roughness:.70,metalness:.1,emissive:0x526b6b,emissiveIntensity:.10}));for(const y of[2.25,4.45])box(rear,[x,y,-9.78],[4.53,.10,.16],P.steel);for(const dx of[-2.20,0,2.20])box(rear,[x+dx,3.35,-9.78],[.085,2.22,.16],P.steel);box(rear,[x,2.23,-9.70],[4.60,.12,.44],P.wood);}if(last<24)box(rear,[(last+24)/2,3.35,-9.99],[24-last,2.2,.24],plaster);
parts.ceiling=new THREE.Group();architecture.add(parts.ceiling);parts.lights=[];for(let x=-12;x<=20;x+=8){box(parts.ceiling,[x,5.25,2],[.16,.24,24],P.steel);for(const z of[-8.8,12.8]){const fixture=box(architecture,[x,4.91,z],[3.6,.09,.27],P.dark),lamp=box(architecture,[x,4.85,z],[3.42,.018,.20],mat(0xf0d8ad,{emissive:0xe9c395,emissiveIntensity:.26})),support=rod(architecture,[x,5.2,z],[x,4.95,z],.025,P.steel);if(z<0)box(architecture,[x,5.18,-9.34],[.10,.12,1.10],P.steel);parts.lights.push({fixture,lamp,support,front:z>0});}}
for(const lane of GROWTH_LANES){for(const z of[lane.z-1.25,lane.z+1.55])box(architecture,[-6.8,.018,z],[15.7,.012,.055],lane.id==='human'?P.coral:lane.id==='fixed'?P.gold:P.mint);for(const x of[-14.65,1.05])box(architecture,[x,.018,lane.z+.15],[.055,.012,2.8],P.gold);}for(const x of[4.8,21.5])box(architecture,[x,.018,4.75],[.055,.012,7.5],P.gold);for(const z of[.98,8.5])box(architecture,[13.15,.018,z],[16.7,.012,.055],P.gold);
 scene.add(new THREE.HemisphereLight(0xffead0,0x6a6351,2.3));const key=new THREE.DirectionalLight(0xffecd1,3.1);key.position.set(-10,20,12);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-28,right:28,top:22,bottom:-20,near:.2,far:70});key.shadow.normalBias=.035;own(key.shadow);scene.add(key);const fill=new THREE.DirectionalLight(0xc9e3d8,1.4);fill.position.set(20,12,-10);scene.add(fill);
 function actor(kind,color=P.mint){const g=new THREE.Group(),chassis=new THREE.Group();g.add(chassis);const robot=kind==='robot',sections={legs:new THREE.Group(),torso:new THREE.Group(),head:new THREE.Group(),arms:new THREE.Group()};for(const p of Object.values(sections))chassis.add(p);box(sections.torso,[0,1.05,0],[robot?.43:.41,.52,.27],robot?color:P.cloth);box(sections.torso,[0,.75,0],[.36,.15,.22],P.dark);if(robot){box(sections.torso,[0,1.13,.15],[.25,.23,.035],P.dark);for(let i=0;i<3;i++)box(sections.torso,[-.07+i*.07,1.15,.176],[.035,.03,.014],P.glow);rod(sections.torso,[-.16,.85,-.16],[-.16,1.27,-.16],.021,P.copper);rod(sections.torso,[.16,.85,-.16],[.16,1.27,-.16],.021,P.copper);box(sections.head,[0,1.50,0],[.31,.30,.27],P.white);box(sections.head,[0,1.52,.148],[.25,.10,.025],P.dark);for(const x of[-.07,.07])ball(sections.head,[x,1.53,.167],.025,P.glow);}else{ball(sections.head,[0,1.50,0],.165,P.skin);box(sections.head,[0,1.64,-.015],[.31,.10,.27],P.dark);box(sections.head,[0,1.58,.145],[.28,.055,.016],P.gold);}
  const legs=[];for(const side of[-1,1]){const hip=[side*.11,.77,0],knee=[side*.12,.40,.025],ankle=[side*.12,.09,0];legs.push({upper:rod(sections.legs,hip,knee,robot?.073:.082,robot?P.white:P.cloth),lower:rod(sections.legs,knee,ankle,robot?.063:.074,robot?P.steel:P.cloth),knee:ball(sections.legs,knee,.081,P.dark),foot:box(sections.legs,[side*.12,.045,.085],[.16,.09,.31],P.sole)});}
  const arms={};for(const [name,side]of[['left',-1],['right',1]]){const shoulder=[side*.27,1.25,0];arms[name]={shoulder,upper:rod(sections.arms,shoulder,[side*.35,.99,.10],.065,robot?P.white:P.cloth),lower:rod(sections.arms,[side*.35,.99,.10],[side*.22,.90,.30],.052,robot?P.steel:P.skin),elbow:ball(sections.arms,[side*.35,.99,.10],.071,P.dark),hand:box(sections.arms,[side*.22,.90,.30],[.12,.10,.12],robot?P.dark:P.skin)};ball(sections.arms,shoulder,.082,P.dark);}
  const record={group:g,chassis,sections,arms,legs,kind,hands:{left:arms.left.hand,right:arms.right.hand},workHours:0};return record;
 }
 function poseActor(a,position,yaw=0,hands=null,formed=1){a.group.position.set(...position);a.group.rotation.y=yaw;a.sections.legs.visible=formed>.02;a.sections.torso.visible=formed>.28;a.sections.head.visible=formed>.62;a.sections.arms.visible=formed>.82;a.group.updateMatrixWorld(true);for(const [name,side]of[['left',-1],['right',1]]){const arm=a.arms[name],h=hands?.[name]?a.group.worldToLocal(new THREE.Vector3(...hands[name])).toArray():[side*.18,.94,.30],s=arm.shoulder,d=new THREE.Vector3(...h).sub(new THREE.Vector3(...s)),len=d.length(),mid=new THREE.Vector3(...s).add(new THREE.Vector3(...h)).multiplyScalar(.5),bend=new THREE.Vector3(side,0,0).addScaledVector(d,len?-(side*d.x)/(len*len):0).normalize().multiplyScalar(Math.sqrt(Math.max(0,.43*.43-len*len/4)));const e=mid.add(bend).toArray();setRod(arm.upper,s,e,.065);setRod(arm.lower,e,h,.052);arm.elbow.position.set(...e);arm.hand.position.set(...h);arm.hand.userData.contactPoint=hands?.[name]?[...hands[name]]:null;}a.group.userData.formed=formed;}
 function conveyor(g,a,b,width=.31){const length=Math.hypot(b[0]-a[0],b[2]-a[2]),o=box(g,[(a[0]+b[0])/2,a[1],(a[2]+b[2])/2],[width,.10,length],P.dark);o.rotation.y=Math.atan2(b[0]-a[0],b[2]-a[2]);for(const p of[a,b])rod(g,[p[0],.04,p[2]],[p[0],p[1]-.08,p[2]],.035,P.steel);o.userData.from=[...a];o.userData.to=[...b];return o;}
 function rack(g,x,z,color){const root=new THREE.Group();root.loads=[];root.position.set(x,0,z);g.add(root);box(root,[0,.72,0],[1.2,1.44,1.3],P.steel);for(let i=0;i<3;i++){box(root,[0,.36+i*.40,.10],[1.02,.26,1.12],P.dark);for(let j=0;j<4;j++)root.loads.push(box(root,[(j-1.5)*.21,.53+i*.40,.19],[.17,.11,.78],color));}return root;}
 function sample(g,id,x,z){const group=new THREE.Group();g.add(group);const raw=box(group,[0,.025,0],[.25,.05,.18],P.steel),goods=new THREE.Group();group.add(goods);box(goods,[0,.025,0],[.25,.05,.18],P.gold);box(goods,[0,.105,-.055],[.25,.16,.055],P.gold);group.userData={objectId:id,countsAsObject:false,representativeCycle:true,info:t('Pieza equivalente de ejemplo. El movimiento es un ciclo normalizado; el total exacto está en el registro.','Sample equivalent piece. Motion is a normalized cycle; the exact total is in the ledger.')};return {group,raw,goods,x,z,id};}
 parts.lanes={};parts.fixedRobots=[];parts.seedRobots=[];parts.humans=[];parts.samples=[];
 for(const lane of GROWTH_LANES){const g=new THREE.Group();scene.add(g);const color=lane.id==='human'?P.coral:lane.id==='fixed'?P.gold:P.mint,benches=[],actors=[],samples=[];for(let j=0;j<5;j++){const x=GROWTH_BENCH_X[j],b=new THREE.Group();b.position.set(x,0,lane.z);g.add(b);box(b,[0,.86,0],[2,.12,1],P.wood);for(const dx of[-.83,.83])for(const dz of[-.38,.38])box(b,[dx,.42,dz],[.08,.84,.08],P.steel);const press=[];for(const dx of[-.48,.48]){box(b,[dx,1.08,-.22],[.36,.28,.18],P.steel);box(b,[dx,1.47,-.16],[.38,.11,.38],color);rod(b,[dx,1.14,-.25],[dx,1.44,-.25],.075,P.dark);press.push(box(b,[dx,1.23,.10],[.10,.32,.10],P.steel));}benches.push({group:b,press});for(let k=0;k<2;k++){const idx=j*2+k,px=x+(k-.5)*.96,a=actor(lane.id==='human'?'human':'robot',color);g.add(a.group);a.id=lane.id==='growing'?'robot-'+idx:lane.id+'-'+idx;a.group.userData.objectId=a.id;actors.push(a);const s=sample(g,lane.id+'-sample-'+idx,px,lane.z+.28);samples.push(s);parts.samples.push(s);}}
  const title=label(g,'',[-6.6,3.05,lane.z+.4],12.6,.36),ledger=label(g,'',[-6.6,2.64,lane.z+.4],12.0,.28),scope=label(g,t('Misma pieza y ritmo base · ciclos normalizados','Same piece and base pace · normalized cycles'),[-6.6,2.30,lane.z+.4],11.4,.18),inputRack=rack(g,-14.5,lane.z,P.steel),stock=rack(g,1.1,lane.z,P.gold);conveyor(g,[-14.5,.73,lane.z-.68],[1.1,.73,lane.z-.68],.26);const inputLabel=label(g,t('ENTRADA','INPUT'),[-14.5,1.74,lane.z+.69],1.6,.16),stockLabel=label(g,t('MUESTRA DE BIENES','GOODS SAMPLE'),[1.1,1.74,lane.z+.69],1.6,.16);parts.lanes[lane.id]={group:g,benches,actors,samples,title,ledger,scope,inputRack,stock,inputLabel,stockLabel};if(lane.id==='human')parts.humans=actors;else if(lane.id==='fixed')parts.fixedRobots=actors;else parts.seedRobots=actors;
 }
 // Each of the first ten produced identities uses all three bays. Rails are low and walkable.
 const capacity=new THREE.Group();scene.add(capacity);parts.capacity=capacity;parts.newRobots=new Map();parts.newSlots=[];parts.newSamples=[];parts.constructionFixtures=[];parts.commissioningFixtures=[];parts.activePosts=[];
 for(let i=0;i<10;i++){const x=GROWTH_NEW_X[i];for(const [z,kind]of[[8,'construction'],[4.5,'commissioning'],[1.5,'active']]){const f=new THREE.Group();f.position.set(x,0,z);capacity.add(f);box(f,[0,.12,0],[.9,.24,.84],kind==='construction'?P.gold:kind==='commissioning'?P.steel:P.mint);if(kind==='construction'){for(const dx of[-.36,.36])rod(f,[dx,.24,-.30],[dx,1.3,-.30],.025,P.steel);box(f,[0,1.3,-.30],[.78,.07,.08],P.steel);}if(kind==='commissioning'){box(f,[0,.93,-.27],[.48,.72,.13],P.dark);for(let j=0;j<3;j++)box(f,[(j-1)*.10,1.12,-.19],[.04,.04,.012],P.glow);rod(f,[-.20,.51,-.18],[-.20,.75,.18],.012,P.copper);}if(kind==='active'){box(f,[0,.90,-.30],[.83,.10,.23],P.wood);box(f,[0,1.05,-.30],[.32,.20,.14],P.steel);}parts[kind==='construction'?'constructionFixtures':kind==='commissioning'?'commissioningFixtures':'activePosts'].push(f);}
  for(const dx of[-.34,.34])box(capacity,[x+dx,.025,4.75],[.055,.05,6.7],P.steel);const a=actor('robot',P.mint);capacity.add(a.group);a.group.visible=false;const activeSample=sample(capacity,'new-sample-'+i,x,1.14);activeSample.group.position.set(x,.98,1.14);activeSample.goods.visible=false;parts.newSamples.push(activeSample);const carriage=box(capacity,[x,.12,8],[.68,.24,.72],P.dark),name=label(capacity,'',[x,2.07,8.19],1.46,.14);const slot={rank:i,actor:a,group:a.group,carriage,name,id:null,state:null};carriage.visible=false;slot.sample=activeSample;parts.newSlots.push(slot);
 }
 parts.assemblyTitle=label(capacity,t('FABRICAR · trabajo separado de los bienes','BUILD · work separate from goods'),[12.8,3.06,8.0],16.8,.31);parts.assemblySummary=label(capacity,'',[12.8,2.67,8.0],17,.24);parts.commissionTitle=label(capacity,t('INCORPORAR · dos días completos sin producir','COMMISSION · two full days without production'),[12.8,3.03,4.5],17,.29);parts.commissionSummary=label(capacity,'',[12.8,2.64,4.5],17,.22);parts.activeTitle=label(capacity,t('NUEVOS PUESTOS · sólo robots ya incorporados','NEW WORKSTATIONS · commissioned robots only'),[12.8,2.84,1.5],17,.25);
 parts.branch=conveyor(capacity,[1.1,.56,6.75],[5.6,.56,6.75],.34);conveyor(capacity,[5.6,.56,6.75],[5.6,.56,7.5],.34);parts.branch.userData.info=t('El modelo reparte las horas de trabajo entre bienes y construcción. El crédito parcial permanece en el banco.','The model splits work hours between goods and construction. Partial credit stays in the bank.');targets.push(parts.branch);
 // Aggregate badges are range records, not additional robots. Max90 batches, never millions of meshes.
 const aggregateGroup=new THREE.Group();scene.add(aggregateGroup);parts.aggregateGroup=aggregateGroup;parts.aggregateRack=box(aggregateGroup,[22,1.7,-6.025],[2.4,3.4,.95],P.board);parts.batchRecords=new Map();parts.batchSlots=[];
 for(let i=0;i<90;i++){const group=new THREE.Group();aggregateGroup.add(group);const body=box(group,[0,0,0],[.17,.16,.11],P.mint);box(group,[0,.12,0],[.12,.08,.10],P.white);group.userData.countsAsObject=false;group.userData.aggregate=true;group.visible=false;parts.batchSlots.push({group,body,index:i,count:0,id:null});}
 parts.aggregateTitle=label(aggregateGroup,t('LOTES AGREGADOS','AGGREGATE BATCHES'),[22,3.51,-5.51],3.2,.22);parts.aggregateCount=label(aggregateGroup,'',[22,3.22,-5.51],3.2,.23);parts.aggregateRanges=label(aggregateGroup,'',[22,2.92,-5.51],3.2,.15);parts.limitBoard=new THREE.Group();parts.limitBoard.position.set(17.6,0,-6);scene.add(parts.limitBoard);box(parts.limitBoard,[0,1.87,0],[3.0,3.32,.16],P.board);for(const x of[-1.3,1.3])box(parts.limitBoard,[x,.14,0],[.12,.28,.40],P.steel);parts.limitTitle=label(parts.limitBoard,t('LÍMITES DEL ESCENARIO','SCENARIO LIMITS'),[0,3.22,.12],2.8,.21);parts.limitValues=[2.72,2.28,1.84,1.38,.92].map(y=>label(parts.limitBoard,'',[0,y,.12],2.8,.19));
 // Cost decomposition is a calculation board; it does not pretend to simulate money financing construction.
 const cost=new THREE.Group();cost.position.set(-13.5,0,9.35);scene.add(cost);box(cost,[0,1.95,0],[3.4,3.5,.16],P.board);for(const x of[-1.4,1.4])box(cost,[x,.12,0],[.10,.24,.5],P.steel);parts.costBoard={group:cost,title:label(cost,t('COSTE · unidad equivalente','COST · equivalent unit'),[0,3.48,.13],3.15,.20),rows:[3.05,2.66,2.27,1.88,1.49,1.10,.72].map(y=>label(cost,'',[0,y,.13],3.08,.17)),state:null};
 const standGroups=[];for(let i=0;i<6;i++){const g=new THREE.Group();g.position.set(...[GROWTH_STANDS[i][0],0,GROWTH_STANDS[i][2]]);g.rotation.y=GROWTH_STAND_YAWS[i];scene.add(g);box(g,[0,.05,0],[.48,.10,.40],P.dark);rod(g,[0,.10,0],[0,1.0,0],.055,P.steel);const button=box(g,[0,1.15,0],[.43,.30,.12],P.mint);button.userData={action:i,chapter:i};targets.push(button);stands.push(button);label(g,t('ESCUCHAR','LISTEN'),[0,.89,.15],.80,.10);const title=label(g,String(i+1).padStart(2,'0')+' · '+t(...TITLES[i]),[0,1.46,.15],1.75,.14);standGroups.push(g);}
 parts.stands=stands;parts.standGroups=standGroups;parts.populationRepresentations=[];
 parts.closeupCaptions=[label(scene,'',[6.4,2.55,8.2],3.4,.18),label(scene,'',[6.4,2.30,8.2],3.4,.15)];parts.closeupCaptions.forEach(l=>l.m.visible=false);const standStats=standGroups.map(g=>[label(g,'',[0,2.11,.15],1.80,.14),label(g,'',[0,1.87,.15],1.80,.14)]);parts.standStats=standStats;
 function integrateRobotHours(f,ready=0){let h=0;for(const row of f.trace.rows){const overlap=Math.max(0,Math.min(f.time,row.day+1)-Math.max(ready,row.day));if(overlap&&row.fleet)h+=overlap*row.work/row.fleet;if(row.day>=f.time)break;}return h;}
 function updateSample(s,a,hours,position,yaw=Math.PI){const phase=((hours/4+s.index*.13*clamp(hours/4))%1+1)%1,dx=phase<.20?-.30+.30*(phase/.20):phase<.65?0:phase<.85?.30*(phase-.65)/.20:.30-.60*(phase-.85)/.15,y=phase<.85?.95:.36,z=s.z;const p=[s.x+dx,y,z];s.group.position.set(...p);s.raw.visible=phase<.65;s.goods.visible=phase>=.65;s.group.visible=phase<.85;const working=phase>=.20&&phase<.65,left=[p[0]+.08,p[1]+.05,p[2]+.015],right=[p[0]-.08,p[1]+.05,p[2]+.015];const reach=phase<.20?clamp((phase-.10)/.10):phase<.65?1:phase<.75?1-(phase-.65)/.10:0,hands={};for(const [name,side,target]of[['left',1,left],['right',-1,right]]){const from=[position[0]+dx+side*.18,position[1]+.94,position[2]-.30];hands[name]=from.map((v,d)=>v+(target[d]-v)*reach);}poseActor(a,[position[0]+dx,position[1],position[2]],yaw,reach>0?hands:null,1);a.group.userData.reachProgress=reach;a.workHours=hours;a.group.userData.workHours=hours;s.phase=phase;s.stage=phase<.20?'input':phase<.65?'work':phase<.85?'goods':'return';s.group.userData.phase=phase;s.group.userData.stage=s.stage;s.group.userData.elapsedWork=hours;s.group.userData.contactPoints=working?{left,right}:null;return phase;}
 function update(frame,selected=frame?.chapter??0,whole=false,immersive=false,closeup=false){if(disposed||!frame?.trace)return;lastFrame=frame;const c=chapter(selected),detail=closeup&&!whole&&!immersive&&(c===2||c===3),p=frame.params,seed=frame.trace.initialFleet,seedHours=integrateRobotHours(frame),representations=[];parts.walls.forEach((w,i)=>w.visible=immersive&&i!==0);parts.ceiling.visible=immersive;parts.lights.forEach(l=>{l.fixture.visible=l.lamp.visible=l.support.visible=immersive||!l.front;});parts.mode=immersive?'immersive':'notebook';parts.chapter=c;
  for(const lane of GROWTH_LANES){const r=parts.lanes[lane.id],isHuman=lane.id==='human',isGrowing=lane.id==='growing',hours=isHuman?frame.elapsed.human/10:isGrowing?seedHours:frame.elapsed.fixed/10,goods=isHuman?frame.elapsed.human:isGrowing?frame.elapsed.goods:frame.elapsed.fixed,budget=isHuman?frame.budget.human:isGrowing?frame.budget.work:frame.budget.fixed,visibleCount=isGrowing?seed:10;r.state={goods,work:isGrowing?frame.elapsed.work:goods,budget,hours,workers:isHuman?10*p.shifts:visibleCount};r.title.set(isHuman?t('HUMANOS · 10 puestos · ','HUMANS · 10 workstations · ')+10*p.shifts+t(' personas en turnos',' people in shifts'):isGrowing?t('REINVERSIÓN · flota ','REINVESTMENT · fleet ')+integer(frame.state.fleet):t('REFERENCIA · 10 robots fijos','REFERENCE · 10 fixed robots'));r.ledger.set(number(goods)+t(' bienes acumulados · ',' cumulative goods · ')+number(budget)+t(' h de trabajo/día',' work h/day')+(isGrowing?' · '+number(frame.budget.buildWork)+t(' h a construir',' h to construction'):''));r.stock.loads.forEach((load,i)=>{load.visible=goods>0&&i<Math.min(12,Math.ceil(goods));load.userData.countsAsObject=false;load.userData.representedCount=goods>0?goods/Math.min(12,Math.ceil(goods)):0;});r.stock.userData.representedGoods=goods;const annotation=!immersive&&!detail&&(whole||c===0||c===1&&!isGrowing||c===2&&isGrowing);r.title.m.visible=r.ledger.m.visible=r.scope.m.visible=annotation;r.inputLabel.m.visible=r.stockLabel.m.visible=!immersive&&(whole||c<2);
   r.actors.forEach((a,i)=>{const sample=r.samples[i];sample.index=i;a.group.visible=sample.group.visible=i<visibleCount;if(i>=visibleCount){poseActor(a,[sample.x,0,lane.z+.96],Math.PI,null,1);a.workHours=0;a.group.userData={objectId:'robot-'+i,status:'not-installed',countsAsObject:false,representedCount:0,workHours:0,reachProgress:0};sample.group.position.set(sample.x,.95,sample.z);sample.raw.visible=true;sample.goods.visible=false;sample.phase=0;sample.stage='input';sample.group.userData.phase=0;sample.group.userData.stage='input';sample.group.userData.elapsedWork=0;sample.group.userData.contactPoints=null;r.benches[Math.floor(i/2)].press[i%2].position.y=1.23;return;}const x=sample.x,phase=updateSample(sample,a,hours,[x,0,lane.z+.96]);a.id=isGrowing?'robot-'+i:lane.id+'-'+i;a.group.userData.objectId=a.id;a.group.userData.status='active';a.group.userData.countsAsObject=true;a.group.userData.representedCount=1;if(isGrowing)representations.push({id:a.id,idStart:i,idEnd:i+1,count:1,status:'active',group:a.group,aggregate:false});if(isHuman)a.group.userData.representedShiftPeople=p.shifts;const press=r.benches[Math.floor(i/2)].press[i%2];press.position.y=1.23-(phase>=.20&&phase<.65?.12*Math.sin((phase-.20)/.45*Math.PI):0);});
  }
  parts.newRobots.clear();parts.newSlots.forEach((slot,i)=>{const id='robot-'+(seed+i),s=growthRobotPose(frame,id),a=slot.actor;slot.id=id;slot.state=s;parts.newRobots.set(id,slot);a.id=id;a.group.userData={objectId:id,status:s.status,batchId:s.batchId,countsAsObject:true,representedCount:s.status==='future'||s.status==='building'?0:1,active:s.active,readyDay:s.readyDay};slot.group.visible=s.visible;slot.carriage.visible=s.visible&&s.status==='commissioning'&&(Math.abs(s.position[2]-4.5)>.001&&Math.abs(s.position[2]-8)>.001);slot.carriage.position.set(s.position[0],.12,s.position[2]);slot.name.m.position.set(s.position[0],2.09,s.position[2]+.19);slot.name.set(id+' · '+(s.status==='active'?t('produce','working'):s.status==='commissioning'?t('incorporación','commissioning'):s.status==='building'?Math.round(s.fraction*100)+'%':t('sin construir','unbuilt')));slot.name.m.visible=s.visible&&!immersive&&(whole||c===2||c===3)&&(!detail||i<2&&Math.abs(s.position[2]-growthRobotPose(frame,seed).position[2])<.70);const hours=s.active?integrateRobotHours(frame,s.readyDay):0;slot.workHours=hours;let hands=null;const dy=.04*Math.sin(hours/4*Math.PI*2),reach=s.active?1:s.status==='commissioning'?clamp((s.commissioningProgress*2-1.90)/.10):0;slot.sample.group.position.set(s.position[0],.98+dy,1.14);slot.sample.raw.visible=true;slot.sample.goods.visible=false;slot.sample.group.userData.status=s.active?'work':'input';slot.sample.group.userData.elapsedWork=hours;if(reach>0){hands={};for(const [name,side]of[['left',1],['right',-1]]){const from=[s.position[0]+side*.18,s.position[1]+.94,s.position[2]-.30],to=[s.position[0]+side*.10,1.03+dy,1.14];hands[name]=from.map((v,d)=>v+(to[d]-v)*reach);}}poseActor(a,s.position,Math.PI,hands,s.fraction);a.group.userData.workHours=hours;slot.contactPoints=hands;slot.formingProgress=s.fraction;if(s.status==='active'||s.status==='commissioning')representations.push({id,idStart:seed+i,idEnd:seed+i+1,count:1,status:s.status,group:a.group,aggregate:false});});
  let aggregateActive=0,aggregatePending=0;parts.batchRecords.clear();const visibleBatches=new Map(frame.batches.map(b=>[b.id,b]));parts.batchSlots.forEach(slot=>{slot.group.visible=false;slot.count=0;slot.id=null;});for(let i=0;i<frame.trace.batches.length&&i<90;i++){const scheduled=frame.trace.batches[i],b=visibleBatches.get(scheduled.id),slot=parts.batchSlots[i],idStart=Math.max(scheduled.idStart,seed+10),count=Math.max(0,scheduled.idEnd-idStart);slot.id=scheduled.id;slot.idStart=idStart;slot.idEnd=scheduled.idEnd;slot.count=b?count:0;slot.state=b||null;slot.group.userData={batchId:scheduled.id,idStart,idEnd:scheduled.idEnd,representedCount:b?count:0,status:b?.status??'future',aggregate:true,countsAsObject:false,info:t('Icono agregado de un lote; cada rango cuenta una sola vez. No es un robot adicional.','Aggregate batch icon; every range counts once. It is not an additional robot.')};parts.batchRecords.set(scheduled.id,slot);if(!b||!count)continue;slot.group.visible=true;const elapsed=clamp(frame.time-b.completedAt,0,2),smooth=u=>{u=clamp(u);return u*u*(3-2*u);},z=elapsed<.40?8+(4.5-8)*smooth(elapsed/.40):elapsed<1.60?4.5:4.5+(-5.49-4.5)*smooth((elapsed-1.60)/.40);slot.group.position.set(21.00+(i%9)*.24,.44+Math.floor(i/9)*.23,z);slot.body.material=b.status==='active'?P.mint:P.gold;representations.push({id:b.id,idStart,idEnd:b.idEnd,count,status:b.status,group:slot.group,aggregate:true});if(b.status==='active')aggregateActive+=count;else aggregatePending+=count;}
  parts.populationRepresentations=representations;parts.representedPopulation={active:representations.filter(r=>r.status==='active').reduce((n,r)=>n+r.count,0),pending:representations.filter(r=>r.status==='commissioning').reduce((n,r)=>n+r.count,0),aggregateActive,aggregatePending};parts.aggregates={active:aggregateActive,pending:aggregatePending,total:aggregateActive+aggregatePending,ranges:representations.filter(r=>r.aggregate)};parts.aggregateCount.set(integer(aggregateActive)+t(' activos · ',' active · ')+integer(aggregatePending)+t(' en incorporación',' commissioning'));parts.aggregateRanges.set(t('Un icono = un lote · cantidad variable','One icon = one batch · variable quantity'));
  parts.assemblySummary.set(number(frame.ledger.assemblyWork)+t(' h hoy + ',' h today + ')+number(frame.state.bank)+t(' h guardadas · ',' h carried · ')+p.buildHours+t(' h/robot · cierre del día',' h/robot · day-close commitment'));parts.assemblySummary.m.userData.state={credit:frame.constructionCredit,assemblyWork:frame.assemblyWork,carriedWork:frame.state.bank,made:frame.state.made};parts.commissionSummary.set(integer(frame.state.pending)+t(' terminados aún sin trabajar · creados ',' completed but not working · built ')+integer(frame.state.made));const assemblyShow=!immersive&&!detail&&(whole||c===2||c===3);parts.assemblyTitle.m.visible=parts.assemblySummary.m.visible=assemblyShow;parts.commissionTitle.m.visible=parts.commissionSummary.m.visible=parts.activeTitle.m.visible=!immersive&&!detail&&(whole||c===3);parts.aggregateTitle.m.visible=parts.aggregateCount.m.visible=parts.aggregateRanges.m.visible=immersive||whole||c===4;
  const potential=frame.potentialBudget;parts.limitValues[0].set(integer(frame.state.fleet)+t(' robots activos',' active robots'));parts.limitValues[1].set(p.limited?t('Puestos máximos: ','Maximum workstations: ')+integer(p.slots):t('Sin límite de puestos supuesto','Assumed unlimited workstations'));parts.limitValues[2].set(p.limited?t('Suministro: ','Supply: ')+number(p.supply)+t(' h/día',' h/day'):t('Suministro ilimitado supuesto','Assumed unlimited supply'));parts.limitValues[3].set(t('Trabajo posible: ','Potential work: ')+number(potential.work)+t(' h/día',' h/day'));parts.limitValues[4].set(frame.bottlenecks.supply?t('Límite activo: suministro','Active limit: supply'):frame.bottlenecks.slots?t('Límite activo: puestos','Active limit: workstations'):p.reinvest===0?t('Sin reinversión','No reinvestment'):t('Escenario, no predicción','Scenario, not a forecast'));parts.limitBoard.visible=true;
  const depreciation=p.installed/(p.life*365),service=p.service/365,energy=p.power*p.energy*p.hours,cost=parts.costBoard;cost.state={...frame.costs,depreciation,service,energy,supervision:p.supervision,material:p.material};cost.rows[0].set(t('Humano: ','Human: ')+money(frame.costs.human)+t('/unidad','/unit'));cost.rows[1].set(t('Robot: ','Robot: ')+money(frame.costs.robot)+t('/unidad','/unit'));cost.rows[2].set(t('Amort. + servicio: ','Deprec. + service: ')+money(depreciation+service)+t('/día','/day'));cost.rows[3].set(t('Supervisión: ','Supervision: ')+money(p.supervision)+t('/día','/day'));cost.rows[4].set(t('Energía: ','Energy: ')+money(energy)+t('/día','/day'));cost.rows[5].set(t('Material: ','Material: ')+money(p.material)+t('/unidad','/unit'));cost.rows[6].set(t('Utilización plena · coste constante con la flota','Full utilization · cost constant with fleet'));cost.group.visible=true;
  parts.closeupCaptions.forEach(l=>l.m.visible=detail);if(detail){const hero=parts.newSlots[0],s=hero.state;parts.closeupCaptions.forEach((l,i)=>l.m.position.set(s.position[0]+.85,2.55-i*.25,s.position[2]+.20));parts.closeupCaptions[0].set(hero.id+' · '+(s.status==='building'?t('fabricación ','building ')+Math.round(s.fraction*100)+'%':s.status==='active'?t('ya produce','now working'):s.status==='commissioning'?t('incorporación ','commissioning ')+number(s.commissioningProgress*2)+'/2d':t('aún sin fabricar','not built yet')));parts.closeupCaptions[1].set(s.active?t('Trabajo desde incorporación: ','Work since commissioning: ')+number(hero.workHours)+' h':t('Mismo ID · 0 h productivas hasta estar listo','Same ID · 0 productive h until ready'));}const summaries=[[t('Flota ','Fleet ')+integer(frame.state.fleet),t('Bienes ','Goods ')+number(frame.elapsed.goods)],[t('Humano ','Human ')+number(frame.budget.human)+t(' h/d',' h/d'),t('10 robots ','10 robots ')+number(frame.budget.fixed)+t(' h/d',' h/d')],[t('Crédito ','Credit ')+number(frame.constructionCredit)+' h',t('Creados ','Built ')+integer(frame.state.made)],[t('Incorporación ','Commissioning ')+integer(frame.state.pending),t('Espera: 2 días completos','Wait: 2 full days')],[t('Activos ','Active ')+integer(frame.state.fleet),p.limited?t('Máximo ','Maximum ')+integer(p.slots):t('Sin topes supuestos','Assumed no limits')],[t('Humano ','Human ')+money(frame.costs.human),t('Robot ','Robot ')+money(frame.costs.robot)]];standStats.forEach((r,i)=>r.forEach((l,j)=>{l.set(summaries[i][j]);l.m.visible=immersive||whole;}));stands.forEach((s,i)=>{s.material=i===c?P.gold:P.mint;});standGroups.forEach(g=>g.visible=immersive||whole);scene.updateMatrixWorld(true);
 }
 scene.updateMatrixWorld(true);return {scene,parts,stands,targets,resources,bounds:GROWTH_BOUNDS,solids:GROWTH_SOLIDS,update,applyFrame:update,get state(){return lastFrame;},dispose(){if(disposed)return;disposed=true;for(const r of [...resources])r.dispose();}};
}
function isVisible(o){for(let p=o;p;p=p.parent)if(!p.visible)return false;return true;}
export function createGrowthWorld(host,es=true,onListen=()=>{},onInfo=()=>{}){
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;host.append(renderer.domElement);const built=createGrowthScene(es),camera=new THREE.PerspectiveCamera(46,1,.055,220),post=createPost(renderer,built.scene,camera,{strength:.30,radius:.40,threshold:1.2}),canvas=renderer.domElement,orbit={...growthOverview},ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let active=0,mode='notebook',pose=growthPoseAt(0),frame,disposed=false,dragging=false,lastX=0,lastY=0,down,pinch=0;const listeners=[];canvas.tabIndex=0;
 function listen(target,event,fn,options){target.addEventListener(event,fn,options);listeners.push(()=>target.removeEventListener(event,fn,options));}
 function draw(){if(disposed)return;const fov=mode==='immersive'?80:camera.aspect<1?64:46;if(camera.fov!==fov){camera.fov=fov;camera.updateProjectionMatrix();}if(frame)built.update(frame,active,orbit.whole&&mode!=='immersive',mode==='immersive',orbit.closeup);if(mode==='immersive'){camera.position.set(pose.x,1.65,pose.z);camera.rotation.set(pose.pitch,pose.yaw,0,'YXZ');}else{const f=growthFraming(active,orbit,camera.aspect,camera.fov,frame);camera.position.copy(f.center).addScaledVector(f.direction,f.distance);camera.lookAt(f.center);}camera.updateMatrixWorld();built.scene.updateMatrixWorld(true);post.render(0);}
 function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();post.setSize(w,h,Math.min(globalThis.devicePixelRatio||1,1.5));draw();}const observer=new ResizeObserver(resize);observer.observe(host);
 function inspect(x,y){if(disposed)return null;const rect=canvas.getBoundingClientRect();pointer.set((x-rect.left)/rect.width*2-1,1-(y-rect.top)/rect.height*2);ray.setFromCamera(pointer,camera);for(const hit of ray.intersectObjects(built.scene.children,true)){if(!isVisible(hit.object)||hit.object.isSprite||hit.object.userData.isLabel)continue;const o=hit.object,action=o.userData.action;if(Number.isInteger(action))return {action,index:action,object:o,distance:hit.distance};if(o.userData.info)return {info:o.userData.info,object:o,distance:hit.distance};if(o.isMesh&&(!o.material?.transparent||o.material.opacity>.5))return null;}return null;}
 const fire=hit=>{if(!hit)return false;if(Number.isInteger(hit.action)){onListen(hit.action);return true;}if(hit.info){onInfo(hit.info,hit);return true;}return false;};
 listen(canvas,'pointerdown',e=>{if(mode!=='notebook')return;dragging=true;lastX=e.clientX;lastY=e.clientY;down={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);});listen(canvas,'pointermove',e=>{if(!dragging||mode!=='notebook')return;orbit.yaw-=(e.clientX-lastX)*.004;orbit.pitch=clamp(orbit.pitch+(e.clientY-lastY)*.004,-.25,1.15);lastX=e.clientX;lastY=e.clientY;draw();});listen(canvas,'pointerup',e=>{if(mode==='notebook'){dragging=false;if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<5)fire(inspect(e.clientX,e.clientY));down=null;}});listen(canvas,'wheel',e=>{if(mode!=='notebook')return;e.preventDefault();orbit.distance=clamp(orbit.distance*(e.deltaY>0?1.06:.94),5,22);draw();},{passive:false});listen(canvas,'touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);},{passive:true});listen(canvas,'touchmove',e=>{if(mode!=='notebook'||e.touches.length!==2)return;const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);if(pinch){orbit.distance=clamp(orbit.distance*pinch/Math.max(1,d),5,22);draw();}pinch=d;},{passive:true});listen(canvas,'webglcontextlost',e=>e.preventDefault());resize();
 return {canvas,dom:canvas,camera,built,scene:built.scene,orbit,render(f){frame=f;active=chapter(f?.chapter??active);draw();},applyFrame(f){this.render(f);},focus(index){active=chapter(index);orbit.yaw=active===5?.06:.12;orbit.pitch=active===5?.10:active===0?.65:.46;orbit.distance=10;orbit.whole=false;orbit.closeup=false;draw();},closeup(){orbit.whole=false;orbit.closeup=true;orbit.yaw=.12;orbit.pitch=.46;orbit.distance=10;draw();},fit(){orbit.distance=10;orbit.whole=false;orbit.closeup=false;draw();},overview(){orbit.closeup=false;orbit.whole=true;orbit.yaw=.22;orbit.pitch=.65;orbit.distance=10;draw();},zoomBy(f){orbit.distance=clamp(orbit.distance/f,5,22);draw();},setMode(value){mode=value==='immersive'?'immersive':'notebook';draw();},setPose(value){pose=restoreGrowthPose(value);draw();},getViewState(){return {chapter:active,mode,orbit:{...orbit},pose:{...pose}};},restoreViewState(saved){if(!saved||typeof saved!=='object')return false;active=chapter(saved.chapter);mode=saved.mode==='immersive'?'immersive':'notebook';const o=saved.orbit||{};orbit.yaw=Number.isFinite(o.yaw)?o.yaw:active===5?.06:.12;orbit.pitch=clamp(Number.isFinite(o.pitch)?o.pitch:active===5?.10:.46,-.25,1.15);orbit.distance=clamp(Number.isFinite(o.distance)?o.distance:10,5,22);orbit.whole=o.whole===true;orbit.closeup=o.closeup===true;pose=restoreGrowthPose(saved.pose);draw();return true;},focusPose(index,aspect=1){return growthFraming(index,{},aspect,aspect<1?64:46);},focusBounds:GROWTH_BOUNDS,nearest(){return growthNearestStand(pose);},activate(){const near=growthNearestStand(pose);if(!near)return false;onListen(near.index);return true;},inspect,stats(){return {geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,resources:built.resources.length};},dispose(){if(disposed)return;disposed=true;observer.disconnect();listeners.forEach(fn=>fn());built.dispose();post.dispose();renderer.dispose();canvas.remove?.();}};
}
